### ISSUE TITLE
Would it be possible to add a feature to dump structures in hexadecimal?

### ISSUE THREAD

**Issue by mimoo** [go-delve/delve#1038]
Hello!

At the moment I can print some slices, but what I would like to do would be to do something like this:

```go
print hex.Dump(something)
```

Is this something that is currently possible?

**Comment by aarzilli** [comment]
what do you mean exactly? What would the output look like?

**Comment by mimoo** [comment]
the output would be the hexadecimal string representation of a byte/int slice

**Comment by derekparker** [comment]
This could be solved when we do better conversions for interface values:

```
(dlv) call fmt.Printf("%#v", 4)
> main.main() ./server.go:19 (hits goroutine(1):3 total:3) (PC: 0x73f918)
Command failed: can not convert 4 constant to []interface {}
```
