### ISSUE TITLE
Can't ctrl+c server after debugger attaches

### ISSUE THREAD

**Issue by nicksnyder** [go-delve/delve#1057]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
1.0.0-rc.2
2. What version of Go are you using? (`go version`)?
go version go1.9.2 darwin/amd64
3. What operating system and processor architecture are you using?
macOS High Sierra 10.13.2
4. What did you do?
Write a simple web server
```go
package main

import (
	"fmt"
	"net/http"
)

func handler(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hi there, I love %s!", r.URL.Path[1:])
}

func main() {
	x := 11
	fmt.Println("running frontend", x)
	http.HandleFunc("/", handler)
	err := http.ListenAndServe(":8989", nil)
	fmt.Printf("ending frontend %d: %s", x, err)
}
```

Run it with delve
```bash
go install -gcflags='-N -l'
dlv exec --headless --listen=:2345 --log ./main
```

Attach using Visual Studio Code
```
    {
            "name": "Attach to main",
            "type": "go",
            "request": "launch",
            "mode": "remote",
            "remotePath": "${workspaceRoot}",
            "port": 2345,
            "host": "127.0.0.1",
            "program": "${workspaceRoot}",
            "env": {},
            "args": []
        }
```

ctrl+c in my terminal and nothing happens
stopping the Visual Studio Code debugger also does nothing.

5. What did you expect to see?

I expected the process to stop and the debugger to detach.

6. What did you see instead?

I had to manually kill the process.

**Comment by aarzilli** [comment]
This is basically the same problem as https://github.com/derekparker/delve/issues/852 and at the moment we can't do anything about it.
However if you pause the process through the debugger and quit delve you will have the option of also killing the attached process.

**Comment by wheelcomplex** [comment]
Hi @nicksnyder , you may want to have a look with this fork: https://github.com/wheelcomplex/delve

When remote debugging in headless mode, we have to kill the dlv process every time while application has exited.
(Maybe there is a better way then fork and modify, let me know please, many thanks)

I did a small modification to add --exit-on-proc-exited to make debugger exit when debugged application process exited: https://github.com/wheelcomplex/delve/commit/4482920081000f08e488c6ae3c89e709b1af8417

If you application will exit by ctl+c, I believe this can help you.

**Comment by zlymeda** [comment]
@wheelcomplex will you/did you create PR for that? thanks

**Comment by wheelcomplex** [comment]
> @wheelcomplex will you/did you create PR for that? thanks

@zlymeda Yep, I just have a try.

**Comment by aarzilli** [comment]
Parent issue #852 was closed. If you have a version of debugserver with the patch SIGINT will now be propagated to the target program.
