### ISSUE TITLE
Condition is always true

### ISSUE THREAD

**Issue by dlsniper** [go-delve/delve#1071]
Hi,

In the following code snippet: https://github.com/derekparker/delve/blob/7bec20e5fca48552b004fc8776dd9e6502a11706/pkg/proc/core/core.go#L96-L128

The following condition is always true:
https://github.com/derekparker/delve/blob/7bec20e5fca48552b004fc8776dd9e6502a11706/pkg/proc/core/core.go#L101

Unfortunately I'm not really sure what the intention was here so I can't provide a patch myself. 
Hope it helps.

**Comment by mrsiano** [comment]
which means always false (if !started).
I believe this flag were added to prevent the program to return the errr on line 104.

1. we can just let the code continue, ang get rid of the started flag
2. or break the recursive loop in by keep the flag and set it to after line 112 and return err

@derekparker ?!

**Comment by derekparker** [comment]
Paging @heschik as the original author of this code.

**Comment by heschik** [comment]
Indeed. started should be set to true on 106 or so. Without it, if a read goes into an unmapped region, it will be silently continued at the next mapping instead of failing or zero-filling. Nothing should be reading unmapped memory anyway, which is presumably why nobody noticed this as an actual bug.

A good starter fix if anyone is interested in learning this code, otherwise I'll get around to a PR sometime.

**Comment by pjot726** [comment]
Hello everyone, 

Is this issue still open? I am interested in learning the code and contributing.

**Comment by heschik** [comment]
It is, I completely forgot about it. Feel free to take it.

**Comment by pjot726** [comment]
Do I need to get this issue assigned to me, or am I good to go? (Sorry if this is a silly question, I'm new to Github.)

**Comment by heschik** [comment]
Varies per project, so @derekparker would be the one to answer authoritatively. But I definitely won't work on it for a while and I highly doubt anyone else will either.

**Comment by derekparker** [comment]
@pjot726 feel free to start working on this issue! No need to be assigned.

**Comment by derekparker** [comment]
Closing this out per the commit above.
