### ISSUE TITLE
Add code sample for getting started doc

### ISSUE THREAD

**Issue by schomatis** [go-delve/delve#1092]
The [getting started guide](https://github.com/derekparker/delve/blob/master/Documentation/cli/getting_started.md) references a dummy `github.com/me/foo/cmd/foo` code. It would be useful to add a concrete (albeit dummy) code, that would have it's own project and `cmd/program` structure, to expand the guide and be able to have reproducible examples.

This issue really aims at using that same sample code for the internal documentation (#1074), and "fit" those two guides together (the getting started guide as a basic introduction and the internal documentation as the advanced part), providing some continuity for the reader.

My question is where should this code be added?

I'd rather not have it embedded in the markdown forcing the reader to copy/paste it, but somewhere it would be accessible through a command (e.g., `go get`) and thus provide the reader with the commands to follow the documentation (I'd rather copy/paste single commands rather than big pieces of code). I think it would be nice to have some sort of `example` project inside `github.com/derekparker` (or maybe just a directory inside this same repository if the previous solution is too complicated).

**Comment by derekparker** [comment]
I think a sample program would be a good idea, but I think it'd be nice to add that in addition to also expanding the scope of the getting started document. For example, adding a few commands (e.g. `print`, `goroutines`, `next`, `step`, `stepout`). That way we can tailor the example program towards the guide, provide variables to print, some interesting control flow, etc.

I think it's fine for this example program to live in `github.com/derekparker/delve/Documentation/getting_started/example` or possible have it's own repo under the Delve Github org (`github.com/go-delve`).

**Comment by schomatis** [comment]
Great, I was just opening PR #1093 to refactor the getting started guide, I'll add those commands to the list.

**Comment by schomatis** [comment]
@derekparker Thinking about an example for the `goroutines` command (which is a good way for a new user to get more involved in how Go itself works), I was thinking of using the canonical [Go by Example](https://gobyexample.com/goroutines) which has a nice and simple program printing output to the terminal that can allow Delve to inspect and compare the `main` goroutine with other non-`main` goroutines, to see how they behave.

What do you think? Did you have other type of examples in mind?

**Comment by derekparker** [comment]
Yeah that seems like a fine idea. Another thing I like to add sometimes for examples / demos is an `id` param to the goroutine function, and step through examining the value of that `id` variable and examining the output of `goroutines` to show how Delve can follow a specific goroutine correctly.

**Comment by derekparker** [comment]
Going to close this issue due to old age.
