### ISSUE TITLE
goroutine(s) commands: discriminate between user and runtime

### ISSUE THREAD

**Issue by schomatis** [go-delve/delve#1104]
Delve does a very informative distinction for the inexperienced Go developer between the user and runtime domains when printing information about goroutine's stack in the `goroutine` and `goroutines` commands (something I didn't see in the Go specs).

Basically it can show the topmost stack frame that belongs to a user defined function as the active one, hiding superior stack frames that belong to runtime code (e.g., when a user function is waiting to receive information from a channel, a job that is handled by Go's runtime system). This makes it simpler for a user to identify the goroutines "belonging" to him, distinguishing them from goroutines in which the user has no direct influence with his code (e.g., a goroutine working on GC).

This distinction is implemented in the function [`UserCurrent`](https://github.com/derekparker/delve/blob/v1.0.0-rc.2/pkg/proc/variables.go#L494) used by the debugger which (if I understand correctly) iterates the stack from top to bottom and returns the first function call not identified with the runtime system, and if it doesn't it just returns the topmost frame (belonging to runtime). This means that for runtime goroutines that do not have any user functions in it's stack it will print a runtime function next to the label `User:` which can be confusing for inexperienced users.

I think it would be useful to modify this behavior in the `goroutine` family commands to make the distinction more clear. The PR needed to achieve that doesn't seem much complicated but I'm raising this issue first because I would like to expand upon that distinction.

The objective is that a new user will see (by default or with the appropriate flag) only his own code, that means hiding goroutines from the runtime system, and besides that, as already implemented, that if one of his goroutines is parked in runtime (waiting for something), to hide the runtime stack frames  above his function. This would achieve something similar in spirit to debugging a C program with `gdb` and not seeing all the stack frames inside the kernel.

If one debugs an empty `main` function with Delve the output of `goroutines` is:

```
     1:	package main
     2:	
     3:	func main() {
=>   4:	}
(dlv) goroutines
[3 goroutines]
* Goroutine 1 - User: ./main.go:4 main.main (0x4554c0) (thread 26786)
  Goroutine 2 - User: /usr/local/go/src/runtime/proc.go:288 runtime.gopark (0x427acd)
  Goroutine 3 - User: /usr/local/go/src/runtime/proc.go:288 runtime.gopark (0x427acd)

```

It would be more clear to only show `Goroutine 1`, that the user can clearly identify with his code. (Or at least to show the other two goroutines with the label `Runtime:`).

So to the already existing discrimination that `UserCurrent` does in the "vertical axis" of the stack, this new division in the "horizontal axis" would permit to label goroutines as "belonging" to the runtime or to the user.

My question is what rule to implement for this "horizontal" distinction to be able to define a *user goroutine* and a *runtime goroutine*, there isn't one in the Go spec as far as I know and the objective is not to redefine the language, just to provide the new user with a conceptual tool to better understand the interaction between his code and the Go's runtime system. It doesn't even need to be a strict distinction but some guide or rule of thumb.

One possibility could be to inspect if the stack of that goroutine contains a user defined function or not, to be able to label it as a runtime goroutine. A simpler and more clear distinction would be to define any goroutine started by a `go` statement inside user code as a user goroutine (plus the `main` function), but I'm not sure if user functions can be registered as callbacks and be called as goroutines by the runtime system.

**Comment by aarzilli** [comment]
> My question is what rule to implement for this "horizontal" distinction to be able to define a user goroutine and a runtime goroutine

The logical way to do this is to copy `runtime.isSystemGoroutine` as defined in `$GOROOT/src/runtime/traceback.go`.

Personally I'm not a fan of this, I think we should show those goroutines since they exist. We should however expose g.startpc as an option in the `goroutines` command.

**Comment by derekparker** [comment]
I'm also not in favor of hiding goroutines. Even if it may not be necessarily useful to the user, it isn't up to Delve to make that distinction for them. I could be in favor of better labeling, potentially. 

>  We should however expose g.startpc as an option in the goroutines command.

I agree with this.

**Comment by schomatis** [comment]
Thanks for pointing me in the right direction. Just to clarify, I didn't mean that the runtime goroutines should always (or even by default) stay hidden from the user, as said before I'd be more than happy to just have a flag that would make the `goroutines` command hide runtime goroutines to avoid cluttering the output when the user (and here I'm thinking of a beginner) just wants to see the goroutines he created. The  standard `runtime/debug` function [`PrintStack`](https://golang.org/pkg/runtime/debug/#PrintStack) has different output detail levels (see [`GOTRACEBACK`](https://golang.org/pkg/runtime/#hdr-Environment_Variables)) for printing (or not) goroutines that belong to the runtime system (by default it hides them).

What I propose is:

1. Adopting the discrimination logic from [`isSystemGoroutine`](https://github.com/golang/go/blob/release-branch.go1.9/src/runtime/traceback.go#L848) to reserve the name *runtime goroutine* (or *system goroutine*) to the specific hard-coded functions listed there (and *user goroutine* for the rest). I'm not sure how much work is implicated in bringing that logic into Delve (without duplicating too much code, as none of those functions are exported).

2. (a) Change the labeling system in the `goroutines` command. Use the `User:` and `Runtime:` labels to indicate if the goroutine is a runtime or a user goroutine, not if the same stack is showed with or without the top runtime frames (specially because for runtime goroutines that do not contain user frames it has an -at least at first sight- inconsistent output: the same stack is showed both as `User:` and `Runtime:` without any modification).

2. (b) This would also imply modifying the output of the `goroutine` command to not show both `User:` and `Runtime:` together, but one of the two depending if it's a user or runtime goroutine. When listing `Runtime:`, `User:` and `Go:` all together it gives the impression (at least to me, this is subjective of course) that 3 different goroutines are being displayed, when actually the first two are different presentations of the same one, and only the third is really different from the first two (as it was the one which created the goroutine).

3. Optional: adopt another label to signal the user if the function listed is really at the top of the stack or if upper runtime stack frames where hidden (e.g., something like `[u]` at the end).

**Comment by derekparker** [comment]
Closing this out for now. We've added some more information to the `goroutine` output. If that still does not satisfy this issue please reopen with more details.
