### ISSUE TITLE
Disable or improve optimized function warning when using `dlv trace`

### ISSUE THREAD

**Issue by derekparker** [go-delve/delve#1105]
When using the `dlv trace` command, the current warning: `Warning: debugging optimized function` clutters up the output. I think it's best if it were not printed, or printed in a less obtrusive way.

This may be a non-issue with Go 1.10, I'll investigate further.

**Comment by mrsiano** [comment]
whats that it means ?! can you share a example output ?! or how to reproduce ?

**Comment by nuliknol** [comment]
```
> main.trace_block() ./github.com/afterether/ethbot/ebtrace.go:67 (PC: 0xf9e0fa)
Warning: debugging optimized function
    62:	
    63:		lcfg:=&vm.LogConfig{
    64:	            DisableMemory: false,
    65:	            DisableStack: false,
    66:	            DisableStorage: false,
=>  67:	            FullStorage: false,
    68:	    }
```
I think this is the reason of why the current source line is not located correctly, it doesn't match the PC
