### ISSUE TITLE
Add rerun(a watcher in the debug mode)  to delve

### ISSUE THREAD

**Issue by scaria** [go-delve/delve#1172]
This is not an issue ticket, so I am gonna omit all my environment details.

I am using delve extensively for debugging go apps. But having no watcher in debug mode and not being able to actively recompile the app, as I am making changes is painful. I would love to suggest this feature. This could be something like rerun([https://github.com/skelterjohn/rerun/blob/master/rerun.go]). I am trying to implement this and . submit as a patch. But I just wanted to know what people think about this. Also, is there any reason why it is not there?

Thank you

**Comment by exapsy** [comment]
Yes please :D I would applaud this feature so <-----------> much.
It's even more painful if you have the app dockerized like I do, and you have to restart the container every time you update the code.

**Comment by aarzilli** [comment]
A rebuild command was added in 95e7cafd0c77790d728a6dc6ffc65c2cb29a13c0
