### ISSUE TITLE
Redirect the log to file

### ISSUE THREAD

**Issue by Shnitzelil** [go-delve/delve#1179]
Hi,

Is it possible to redirect the log to file?

Thanks

**Comment by aarzilli** [comment]
Not currently.

**Comment by narqo** [comment]
I would be very happy to see this feature in delve. 
Recently I had a chance to debug a coredump with hundreds of thousands stacked goroutines and I couldn't even have a list of them with `goroutines` cmd, as the list was so huge it didn't fit into my terminal's buffer. I had to scrap the output out of delve's RPC debug logging and "analyze" it with jq until I managed to find the goroutine id I was interested in.

**Comment by aarzilli** [comment]
Implemented by 48f1f51ef9c5c281af79630e3d7b6216778d2914

**Comment by Shnitzelil** [comment]
Great!!!

**Comment by aktau** [comment]
I couldn't get `--log`, `--log-dest` or `--log-output` to work for the use case mentioned by @narqo above (save the goroutines somewhere). But, I could use the following: 

```
$ dlv --allow-non-terminal-interactive core ./mybin ./mycore <<< goroutines > ./goroutines.out
```
