### ISSUE TITLE
Add (optional) verbose logging to debugger

### ISSUE THREAD

**Issue by lggomez** [go-delve/delve#1217]
Currently, the [debugger](https://github.com/derekparker/delve/blob/master/service/debugger/debugger.go) only logs info from some of the steps

Some additional info (like LocalVariables state/return, just to name an example) would be helpul when diagnosing issues with clients on headless servers, making it optional so the users don't get cluttered with log messages by default

I was thinking on a new `--log-detail` or `--log-verbose` parameter for that end, if it makes sense

**Comment by aarzilli** [comment]
The intended way to implement this would be to add options to `--log-output`.

**Comment by davidmichaelkarr** [comment]
If it matters, additional logging could possibly help for situations where delve doesn't appear to be working properly.  In my situation, Delve seems to think it can't find any of my source files: https://stackoverflow.com/questions/69936099/debugging-go-in-vscode-doesnt-stop-at-breakpoints-says-could-not-find-file

**Comment by aarzilli** [comment]
Closing, we've added a bunch of logging since 2018 if more is needed specific issues can be opened.
