### ISSUE TITLE
next/step/stepout should work on the current frame instead of the topmost frame

### ISSUE THREAD

**Issue by jankratochvil** [go-delve/delve#1240]
1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.0.0
Build: 2a2d1040e9b85e069c101bf9916d333e9e3cf54d

2. What version of Go are you using? (`go version`)?
go version go1.10.3 linux/amd64

3. What operating system and processor architecture are you using?
Fedora 28 x86_64

4. What did you do?
Tried to switch to a goroutine and step it.

5. What did you expect to see?
Stepping in a goroutine.

6. What did you see instead?
It just run away and the debuggee finished.

[1.txt](https://github.com/derekparker/delve/files/2119943/1.txt)

**Comment by jankratochvil** [comment]
So now I got an error:
```(dlv) n
Command failed: not on topmost frame
```
OK, so I did few `stepout`s first:
```(dlv) stepout
(dlv) bt
0  0x000000000044851b in time.Sleep
   at /usr/lib/golang/src/runtime/time.go:103
1  0x000000000049fcb8 in main.main.func2
   at ./stateful-goroutines.go:85
2  0x0000000000457281 in runtime.goexit
   at /usr/lib/golang/src/runtime/asm_amd64.s:2361
```
But then it again exited the program despite it should have stayed at `stateful-goroutines.go:85`, like if GDB did a `finish`:
```(dlv) stepout
readOps: 4685
writeOps: 12
Process has exited with status 0
(dlv) _
```

**Comment by aarzilli** [comment]
Looking at what you've posted it looks like there's nothing waiting for the goroutine you are debugging, there is no guarantee that the runtime will chose to resume it.

**Comment by jankratochvil** [comment]
So I guess Delve is using `set scheduler-locking off`? Can one use a different mode?
```
(gdb) show scheduler-locking
Mode for locking scheduler during execution is "step".
(gdb) help set scheduler-locking
Set mode for locking scheduler during execution.
off    == no locking (threads may preempt at any time)
on     == full locking (no thread except the current thread may run)
          This applies to both normal execution and replay mode.
step   == scheduler locked during stepping commands (step, next, stepi, nexti).
          In this mode, other threads may run during other commands.
          This applies to both normal execution and replay mode.
replay == scheduler locked in replay mode and unlocked during normal execution.
(lldb) help step
       -m <run-mode> ( --run-mode <run-mode> )
            Determine how to run other threads while stepping the current thread.
            Values: this-thread | all-threads | while-stepping
```

**Comment by aarzilli** [comment]
No, there is no way to do that with go.

**Comment by jankratochvil** [comment]
OK, then just this commit should be added to mainline, thanks for resolving it.
