### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by Ma124** [go-delve/delve#1273]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 1.0.0
Build: $Id: c98a142125d0b17bb11ec0513bde346229b5f533 $
```
2. What version of Go are you using? (`go version`)?
`go version go1.10.2 linux/amd64`
3. What operating system and processor architecture are you using?
Ubuntu 18.04 LTS x86_64
4. What did you do?
`l`
5. What did you ~expect~ want to see?
Syntax highlighted code
6. What did you see instead?
Non syntax highlighted code

I now this is difficult but it would be quite useful.

**Comment by bulentkazanci** [comment]
Hi, I would like to contribute by implementing this feature if it wasn't implemented yet. Is it okay to use an external highlighter like [chroma](https://github.com/alecthomas/chroma) for highlighting?

**Comment by aarzilli** [comment]
External highlighters are ok, but chroma has a lot of indirect dependencies.
