### ISSUE TITLE
Mangled .debug_info section on macOS with external linking

### ISSUE THREAD

**Issue by wopol** [go-delve/delve#1316]
1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.1.0
Build: $Id: 1990ba12450cab9425a2ae62e6ab988725023d5c $
2. What version of Go are you using? (`go version`)?
go version go1.10.2 darwin/amd64
3. What operating system and processor architecture are you using?
macOS High Sierra 10.13.6

I have a problem with debugging, i suppose so the reason is my project structure. Sometimes when i create new package, i create inside "cmd" directory where is my main file(attached file). In this case i can add breakpoints only in my main file, because each breakpoints in other file is unverified. I get error: "Error on CreateBreakpoint: could not find ...src/location/scanner/monitor.go:34". Summarizing, main.go file is in main package, transport and monitor file is in scanner package. Is it possible to debugging project with structure like this ? When i move monitor.go, transport.go and main.go to one main package, all works great.

I also tried debugging directly in delve debugger and i got the same error "Command failed: could not find /Users/wojciechpolus/go-workspace/src/location/scanner/transport.go:43"

<img width="1036" alt="zrzut ekranu 2018-08-18 o 22 41 31" src="https://user-images.githubusercontent.com/9054681/44303104-50915d00-a338-11e8-8e45-34cbfc3c1c16.png">

<img width="298" alt="zrzut ekranu 2018-08-18 o 22 38 03" src="https://user-images.githubusercontent.com/9054681/44303096-41121400-a338-11e8-9843-a038a3c1c447.png">

**Comment by aarzilli** [comment]
Where the files are shouldn't matter. I'd like to see the executable built by delve.

**Comment by wopol** [comment]
I built executable file for my platform.
[scanner.zip](https://github.com/derekparker/delve/files/2300200/scanner.zip)

**Comment by aarzilli** [comment]
This is not an executable built by delve.

**Comment by wopol** [comment]
Could you tell my how can i build it ?

**Comment by aarzilli** [comment]
When you do `dlv debug` it will create a file called `debug` in the current directory. Alternatively `go build -gcflags='all=-N -l'`

I must say however that even in that optimized binary not a single line of monitor.go is present in your final executable.

**Comment by wopol** [comment]
thank you for clarification. I send new file, i used command: `go build -gcflags='all=-N -l'`
[scanner.zip](https://github.com/derekparker/delve/files/2300211/scanner.zip)

**Comment by aarzilli** [comment]
PS. if it should it's not a bug with delve but with go.

**Comment by wopol** [comment]
I'm sure that should contains. I sent entire project, in cmd/scanner directory is debug file.
[scanner.zip](https://github.com/derekparker/delve/files/2300233/scanner.zip)

**Comment by aarzilli** [comment]
Can you reproduce it with 1.11rc1?

**Comment by wopol** [comment]
Yes, i have exactly the same with 1.11rc1

**Comment by aarzilli** [comment]
cc @heschik

**Comment by heschik** [comment]
Weird. Something is going badly wrong during external linking; the functions disappear from the symbol table, the subroutine DIEs vanish from .debug_info, etc, etc. Additionally this callq in main.main looks very bad:
 42c0dee:       e8 fd e6 ff ff  callq   -6403 <type..eq.github.com/streadway/amqp.queuePurge+0xE80>
That's supposed to be (*QueueTransport).Wait.

This program doesn't work, does it? It looks completely trashed to me.

I'll bisect and maybe file an upstream bug.

**Comment by wopol** [comment]
This program isn't beautiful, because i wanted just test possibility bluetooth. This program work. It constantly scans beacons devices in nearby.

**Comment by heschik** [comment]
Ah, I didn't notice that it reproduces with 1.10. That's a bit of a relief.

@wopol can you put together a self-contained reproducer and file a bug against Go itself? This is going to take more investigation than I can do right now for something that's not a 1.11 release blocker.

**Comment by heschik** [comment]
Oops, we raced.

It works? Really? Hmm. I'll have to look harder.

**Comment by wopol** [comment]
OK, i will create new issue against GO.
PS. If you want run this program, you must do it on macOS with enabled bluetooth.

**Comment by heschik** [comment]
Yes, please do. I think the missing symbol table entry is the primary problem -- dsymutil is probably dropping the DWARF for the functions it doesn't know existed.

For the record, the "bad" callq is fine; it's just giving the offset from the last symbol it does have.
