### ISSUE TITLE
dlv freeze when external debugger break connection

### ISSUE THREAD

**Issue by dmitryvakulenko** [go-delve/delve#1318]
1. dlv version 1.0.0
2. go version 1.10.3
3. Mint linux 19 on Intel i7

I use Interllij Idea Go plugin to debug program. Debug be started with a command

`dlv debug --headless --listen=:2345 --api-version=2 --wd=../.. -- --config /app/config.json `

Debug session works fine but after I press Ctrl+F2 in IDE to terminate a debug session a console process freeze and I can't interrupt one other than close terminal at all.
It looks like this

`# dlv debug --headless --listen=:2345 --api-version=2 --wd=../.. -- --config /app/config.json 
API server listening at: [::]:2345
2018/08/22 13:16:36 Service started
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C`

This happend not every time but very frequent.

**Comment by dlsniper** [comment]
Are you debugging on the same machine using a "Go Remote Debug" configuration?

Do you need this for any particular reason (the only one I can think of is to allow the debugged process to receive input from the user for a CLI process).

What are the exact steps to reproduce this?
- start the debug session in the terminal using the above command
- press ` ^C ` 

or

- start the debug session in the terminal using the above command
- start the ` Go Remote Debug ` configuration
- press ` ^C `

or some other variation of this?
Is the application open-source or the issue reproducible in a small sample?

Is the terminal the built-in IDE terminal or your OS terminal?

I'm asking these to know if we need to move this over to the [GoLand tracker](https://youtrack.jetbrains.com/issues/Go) or leave it here.
Thank you.

**Comment by dmitryvakulenko** [comment]
Actually, I debug in a docker container. But I tried to reproduce this on the host machine and got same behaviour. I don't use IDE terminal, all of this I do in OS terminal.
Application isn't open source, sorry, but it quite simple. This bug may happend even on show usage info with flag.PrintDefaults().

Steps to reproduce:
- start the debug session on a terminal
- start the Go Remote Debug
- maybe do some debug steps
- press Ctrl+F2
- the debug session freeze, ^C can't help to break it

Hm... wait a minute. I try to reproduce this bug on other application, but it works fine. I try to find out the reason now.

**Comment by dlsniper** [comment]
What IDE version do you use? Help | About and use the copy (clipboard) button from there.

**Comment by dmitryvakulenko** [comment]
I can't reproduce this bug now. Sorry.
I use Idea 2018.2.2 but the same problem was on 2018.2.1

**Comment by dmitryvakulenko** [comment]
Hello!
I figured out a minimum application to reproduce the bug at last. This is it

    package main
    
    import (
        "log"
        "os"
        "os/signal"
        "syscall"
    )
    
    func main() {
        log.Println("Service started")
    
        sigs := make(chan os.Signal, 1)
        signal.Notify(sigs, syscall.SIGKILL, syscall.SIGTERM, syscall.SIGINT)
        s := <-sigs
        log.Printf("RECEIVED SIGNAL: %s", s)
    }

Steps to reproduce:
1. dlv debug --headless --listen=:2345 --api-version=2 ./test.go
1. Press ^C

The bug is not stable, maybe you need to repeat this steps several times.

**Comment by aarzilli** [comment]
Just starting an headless instance and then pressing ^C isn't going to do anything because you didn't do anything to restart the target process. Regardless I'd like to see the output of `--log --log-output=rpc`.

**Comment by dmitryvakulenko** [comment]
There are no any output

    % dlv debug --headless --listen=:2345 --api-version=2 --log --log-output=rpc ./test.go
    API server listening at: [::]:2345
    ^C^C^C^C^C^C^C^C

**Comment by aarzilli** [comment]
Did you connect to it?

**Comment by dmitryvakulenko** [comment]
No. I not connected yet. Just start and try to break it.

**Comment by aarzilli** [comment]
You can't. Delve itself, in headless mode, will ignore SIGINT. To stop the headless instance you have to connect to it and then terminate the connection. To send a SIGINT to the target program you have to start the target program, which you didn't, because to start the target program you have to connect to delve first.

**Comment by dmitryvakulenko** [comment]
Ok, I understood. This is log when I ran the program. The trouble is same.
```bash
 % dlv debug --headless --listen=:2345 --api-version=2 --log --log-output=rpc ./test.go
API server listening at: [::]:2345
DEBU[0003] <- RPCServer.FindLocation(rpc2.FindLocationIn{"Scope":{"GoroutineID":-1,"Frame":0},"Loc":"main.main"})  layer=rpc
DEBU[0003] -> *rpc2.FindLocationOut{"Locations":[{"pc":4920235,"file":"/home/n0dwis/go/src/github.com/dmitryvakulenko/test/test.go","line":10,"function":{"name":"main.main","value":4920208,"type":0,"goType":0,"optimized":false}}]} error: ""  layer=rpc
DEBU[0003] <- RPCServer.ListSources(rpc2.ListSourcesIn{"Filter":""})  layer=rpc
DEBU[0003] -> *rpc2.ListSourcesOut{"Sources":["/home/n0dwis/go/src/github.com/dmitryvakulenko/test/test.go","/usr/local/go/src/errors/errors.go","/usr/local/go/src/fmt/format.go","/usr/local/go/src/fmt/print.go","/usr/local/go/src/fmt/scan.go","/usr/local/go/src/internal/bytealg/compare_amd64.s","/usr/local/go/src/internal/bytealg/equal_amd64.s","/usr/local/go/src/internal/bytealg/index_amd64.go","/usr/local/go/src/internal/bytealg/indexbyte_amd64.s","/usr/local/go/src/internal/cpu/cpu.go","/usr/local/go/src/internal/cpu/cpu_x86.go","/usr/local/go/src/internal/cpu/cpu_x86.s","/usr/local/go/src/internal/poll/fd.go","/usr/local/go/src/internal/poll/fd_mutex.go","/usr/local/go/src/internal/poll/fd_poll_runtime.go","/usr/local/go/src/internal/poll/fd_unix.go","/usr/local/go/src/internal/race/norace.go","/usr/local/go/src/internal/syscall/unix/nonblocking.go","/usr/local/go/src/io/io.go","/usr/local/go/src/io/pipe.go","/usr/local/go/src/log/log.go","/usr/local/go/src/math/bits/bits.go","/usr/local/go/src/math/exp_asm.go","/usr/local/go/src/math/unsafe.go","/usr/local/go/src/os/error.go","/usr/local/go/src/os/exec_unix.go","/usr/local/go/src/os/executable_procfs.go","/usr/local/go/src/os/file.go","/usr/local/go/src/os/file_posix.go","/usr/local/go/src/os/file_unix.go","/usr/local/go/src/os/proc.go","/usr/local/go/src/os/signal/signal.go","/usr/local/go/src/os/signal/signal_unix.go","/usr/local/go/src/reflect/asm_amd64.s","/usr/local/go/src/reflect/makefunc.go","/usr/local/go/src/reflect/type.go","/usr/local/go/src/reflect/value.go","/usr/local/go/src/runtime/alg.go","/usr/local/go/src/runtime/asm.s","/usr/local/go/src/runtime/asm_amd64.s","/usr/local/go/src/runtime/atomic_pointer.go","/usr/local/go/src/runtime/cgo_mmap.go","/usr/local/go/src/runtime/cgo_sigaction.go","/usr/local/go/src/runtime/cgocall.go","/usr/local/go/src/runtime/cgocheck.go","/usr/local/go/src/runtime/chan.go","/usr/local/go/src/runtime/cpuflags_amd64.go","/usr/local/go/src/runtime/cpuprof.go","/usr/local/go/src/runtime/debug.go","/usr/local/go/src/runtime/debugcall.go","/usr/local/go/src/runtime/defs_linux_amd64.go","/usr/local/go/src/runtime/duff_amd64.s","/usr/local/go/src/runtime/env_posix.go","/usr/local/go/src/runtime/error.go","/usr/local/go/src/runtime/extern.go","/usr/local/go/src/runtime/fastlog2.go","/usr/local/go/src/runtime/float.go","/usr/local/go/src/runtime/hash64.go","/usr/local/go/src/runtime/iface.go","/usr/local/go/src/runtime/internal/atomic/asm_amd64.s","/usr/local/go/src/runtime/internal/sys/intrinsics.go","/usr/local/go/src/runtime/lfstack.go","/usr/local/go/src/runtime/lfstack_64bit.go","/usr/local/go/src/runtime/lock_futex.go","/usr/local/go/src/runtime/malloc.go","/usr/local/go/src/runtime/map.go","/usr/local/go/src/runtime/map_fast32.go","/usr/local/go/src/runtime/map_fast64.go","/usr/local/go/src/runtime/map_faststr.go","/usr/local/go/src/runtime/mbarrier.go","/usr/local/go/src/runtime/mbitmap.go","/usr/local/go/src/runtime/mcache.go","/usr/local/go/src/runtime/mcentral.go","/usr/local/go/src/runtime/mem_linux.go","/usr/local/go/src/runtime/memclr_amd64.s","/usr/local/go/src/runtime/memmove_amd64.s","/usr/local/go/src/runtime/mfinal.go","/usr/local/go/src/runtime/mfixalloc.go","/usr/local/go/src/runtime/mgc.go","/usr/local/go/src/runtime/mgclarge.go","/usr/local/go/src/runtime/mgcmark.go","/usr/local/go/src/runtime/mgcsweep.go","/usr/local/go/src/runtime/mgcsweepbuf.go","/usr/local/go/src/runtime/mgcwork.go","/usr/local/go/src/runtime/mheap.go","/usr/local/go/src/runtime/mprof.go","/usr/local/go/src/runtime/msize.go","/usr/local/go/src/runtime/mstats.go","/usr/local/go/src/runtime/mwbbuf.go","/usr/local/go/src/runtime/netpoll.go","/usr/local/go/src/runtime/netpoll_epoll.go","/usr/local/go/src/runtime/os_linux.go","/usr/local/go/src/runtime/os_linux_generic.go","/usr/local/go/src/runtime/os_linux_noauxv.go","/usr/local/go/src/runtime/os_nonopenbsd.go","/usr/local/go/src/runtime/panic.go","/usr/local/go/src/runtime/print.go","/usr/local/go/src/runtime/proc.go","/usr/local/go/src/runtime/profbuf.go","/usr/local/go/src/runtime/relax_stub.go","/usr/local/go/src/runtime/rt0_linux_amd64.s","/usr/local/go/src/runtime/runtime.go","/usr/local/go/src/runtime/runtime1.go","/usr/local/go/src/runtime/runtime2.go","/usr/local/go/src/runtime/rwmutex.go","/usr/local/go/src/runtime/select.go","/usr/local/go/src/runtime/sema.go","/usr/local/go/src/runtime/signal_amd64x.go","/usr/local/go/src/runtime/signal_linux_amd64.go","/usr/local/go/src/runtime/signal_sighandler.go","/usr/local/go/src/runtime/signal_unix.go","/usr/local/go/src/runtime/sigqueue.go","/usr/local/go/src/runtime/slice.go","/usr/local/go/src/runtime/stack.go","/usr/local/go/src/runtime/string.go","/usr/local/go/src/runtime/stubs.go","/usr/local/go/src/runtime/symtab.go","/usr/local/go/src/runtime/sys_linux_amd64.s","/usr/local/go/src/runtime/sys_x86.go","/usr/local/go/src/runtime/time.go","/usr/local/go/src/runtime/timestub.go","/usr/local/go/src/runtime/trace.go","/usr/local/go/src/runtime/traceback.go","/usr/local/go/src/runtime/type.go","/usr/local/go/src/runtime/typekind.go","/usr/local/go/src/runtime/unaligned1.go","/usr/local/go/src/runtime/utf8.go","/usr/local/go/src/runtime/vdso_linux.go","/usr/local/go/src/runtime/write_err.go","/usr/local/go/src/strconv/atoi.go","/usr/local/go/src/strconv/decimal.go","/usr/local/go/src/strconv/extfloat.go","/usr/local/go/src/strconv/ftoa.go","/usr/local/go/src/strconv/itoa.go","/usr/local/go/src/strconv/quote.go","/usr/local/go/src/sync/atomic/asm.s","/usr/local/go/src/sync/atomic/value.go","/usr/local/go/src/sync/map.go","/usr/local/go/src/sync/mutex.go","/usr/local/go/src/sync/once.go","/usr/local/go/src/sync/pool.go","/usr/local/go/src/sync/runtime.go","/usr/local/go/src/sync/rwmutex.go","/usr/local/go/src/syscall/asm_linux_amd64.s","/usr/local/go/src/syscall/env_unix.go","/usr/local/go/src/syscall/exec_unix.go","/usr/local/go/src/syscall/str.go","/usr/local/go/src/syscall/syscall.go","/usr/local/go/src/syscall/syscall_linux.go","/usr/local/go/src/syscall/syscall_unix.go","/usr/local/go/src/syscall/zsyscall_linux_amd64.go","/usr/local/go/src/time/format.go","/usr/local/go/src/time/sys_unix.go","/usr/local/go/src/time/time.go","/usr/local/go/src/time/zoneinfo.go","/usr/local/go/src/time/zoneinfo_read.go","/usr/local/go/src/time/zoneinfo_unix.go","/usr/local/go/src/unicode/tables.go","/usr/local/go/src/unicode/utf8/utf8.go","\u003cautogenerated\u003e"]} error: ""  layer=rpc
DEBU[0003] (async 3) <- RPCServer.Command(api.DebuggerCommand{"name":"continue","ReturnInfoLoadConfig":null})  layer=rpc
2018/09/01 22:38:27 Service started
^C2018/09/01 22:38:40 RECEIVED SIGNAL: interrupt
DEBU[0016] (async 3) -> rpc2.CommandOut{"State":{"Running":false,"Threads":null,"NextInProgress":false,"exited":true,"exitStatus":0,"When":""}} error: ""  layer=rpc
DEBU[0016] (async 4) <- RPCServer.Command(api.DebuggerCommand{"name":"halt","ReturnInfoLoadConfig":null})  layer=rpc
DEBU[0016] (async 4) -> <nil>null error: "Process 8209 has exited with status 0"  layer=rpc
^C^C^C^C^C^C^C^C^C
```

**Comment by aarzilli** [comment]
Delve itself, in headless mode, will ignore SIGINT. To stop the headless instance you have to connect to it and then terminate the connection. To send a SIGINT to the target program it has to be running and in this case it has already exited.

**Comment by dmitryvakulenko** [comment]
Thank you for explanation! Sorry for disturb you.

**Comment by aarzilli** [comment]
I don't think there's anything more to do here.

**Comment by sbalabanov** [comment]
Just ran into issue that delve in headless mode ignores SIGINT (Ctrl+C) sent from terminal before the debugger attaches. The only way to stop it is to attach and detach a debugger or send "kill" command to dlv process PID directly. Ironically you can even send 'kill -SIGINT $PID' to kill it.

This is on MacOS.
