### ISSUE TITLE
Unable to add breakpoint while running debugger

### ISSUE THREAD

**Issue by amitdix** [go-delve/delve#1338]
Please answer the following before submitting your issue:
Unable to add breakpoint while running debugger, this started happening after Sierra update

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
1.0.0
2. What version of Go are you using? (`go version`)? 
go version go1.10.3 darwin/amd64
3. What operating system and processor architecture are you using?
Mac Os
4. What did you do?
Tried putting breakpoint when debugger was on 
5. What did you expect to see?
Breakpoint 
6. What did you see instead?
It showed unverified Breakpoint and debugger did not stop

**Comment by aarzilli** [comment]
what's an "unverified Breakpoint"? We'll need to see a transcript of the delve session or the output of `--log --log-output=rpc`

**Comment by aarzilli** [comment]
Breakpoints can not be added while the program is running, vscode shouldn't let you do that.

**Comment by julestruong** [comment]
funny it works for once, and stop working.

It that a particularity of 
1. delve ? 
2. debugger with compile language ?
3. every debugger ?

i've already use debugger with php or js , and i could add breakpoint at runtime.

**Comment by aarzilli** [comment]
> funny it works for once, and stop working.

The first breakpoint was set before resuming execution

> i've already use debugger with php or js , and i could add breakpoint at runtime.

it's a lot simpler to do it with a scripting language.
