### ISSUE TITLE
state returned on Halt doesn't include currentGoroutine

### ISSUE THREAD

**Issue by brycekahle** [go-delve/delve#1396]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 1.1.0
Build: $Id: 1990ba12450cab9425a2ae62e6ab988725023d5c $
```

2. What version of Go are you using? (`go version`)?
`go version go1.11.1`

3. What operating system and processor architecture are you using?
`darwin/amd64`

4. What did you do?

Issued the `Halt` [RPC command](https://godoc.org/github.com/derekparker/delve/service/rpc2#RPCClient.Halt) from the vscode-go extension while a program was running.

5. What did you expect to see?

The returned `*api.DebuggerState` to include `currentGoroutine`, as it does when a breakpoint is hit.

6. What did you see instead?

A very simplified state, such as:
```
{"Running":false,"currentThread":{"id":418703,"pc":140734763598258,"file":"","line":0,"goroutineID":0,"ReturnValues":null},"Threads":[{"id":418722,"pc":140734763598258,"file":"","line":0,"goroutineID":0,"ReturnValues":null},{"id":418723,"pc":140734763598258,"file":"","line":0,"goroutineID":0,"ReturnValues":null},{"id":418703,"pc":140734763598258,"file":"","line":0,"goroutineID":0,"ReturnValues":null},{"id":418720,"pc":140734763598258,"file":"","line":0,"goroutineID":0,"ReturnValues":null},{"id":418721,"pc":140734763598258,"file":"","line":0,"goroutineID":0,"ReturnValues":null}],"NextInProgress":false,"exited":false,"exitStatus":0,"When":""}
```

**Comment by aarzilli** [comment]
Judging by the PC value it's executing some OS code or a dynamic library, there might not be a current goroutine.

**Comment by aarzilli** [comment]
PS. If the implication is that there should always be a current goroutine field set, that's not possible.

**Comment by brycekahle** [comment]
Shouldn't there always be goroutines, even if the stack goes deep enough to not be Go code (OS or library as you mentioned)?
