### ISSUE TITLE
cursor invisible in CLI mode

### ISSUE THREAD

**Issue by morya** [go-delve/delve#1397]
1. What version of Delve are you using (`dlv version`)?

```
Delve Debugger
Version: 1.1.0
Build: ea3428550d3ff55fd569640fc01e5aaefe37bc18
```

2. What version of Go are you using? (`go version`)?

`go version go1.11 darwin/amd64`

3. What operating system and processor architecture are you using?

`MacOS x86_64 Majove inside iTerm` and Putty working with CentOS7 too.

4. What did you do?

```
dlv debug xxx.main
b someFunction
continue
```

and, when stopped, cursor front-color and cusor-background-color must be mixed.
Then I can't see where the cursor is.
Still, it is working. Press Left/Right arrow can move cursor back and forward, if you count it, and you can delete or type text still. 

5. What did you expect to see?

cursor visible.

6. What did you see instead?

cursor become invisible.

If, you quit `dlv` and go back to bash prompt, the cursor is still invisible.
and start a `vim` then quit will get the cursor back.

lost cursor:
<img width="726" alt="image" src="https://user-images.githubusercontent.com/1030182/47947145-19ebdb80-df52-11e8-99d5-2c89e9727529.png">

visible cursor:
<img width="409" alt="image" src="https://user-images.githubusercontent.com/1030182/47947159-4ef82e00-df52-11e8-92d7-7ba734af7111.png">

**Comment by derekparker** [comment]
Closing, please reopen if still an issue.
