### ISSUE TITLE
cannot find module for path golang.org/x/arch/x86/x86asm

### ISSUE THREAD

**Issue by iamybj** [go-delve/delve#1404]
/usr/local/Cellar/go/1.11.2/libexec/bin/go get -u github.com/derekparker/delve/cmd/dlv [/Users/apple/Workspace/rrystt/src/sqltemplate]
go: finding github.com/derekparker/delve/cmd/dlv latest
go: finding github.com/derekparker/delve/cmd latest
go: finding github.com/cosiner/argv latest
build github.com/derekparker/delve/cmd/dlv: cannot find module for path golang.org/x/arch/x86/x86asm
Command exited with code 1.

**Comment by aarzilli** [comment]
Could not reproduce. What operating system are you using, what's the value of GOPATH, GO111MODULE and GOFLAGS? Also `go get` will add delve as a dependency to your project if you run it inside a project.
