### ISSUE TITLE
How to get the address of entry point?

### ISSUE THREAD

**Issue by LichFaker** [go-delve/delve#1422]
1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 1.1.0
Build: $Id: 1990ba12450cab9425a2ae62e6ab988725023d5c $
```
2. What version of Go are you using? (`go version`)?
```
go version go1.10.3 darwin/amd64
```
3. What operating system and processor architecture are you using?
```
Mojave 10.14.1
```

I want to get the information of program's entry point, like `info files` in `gdb`:

```
(gdb) info files
Local exec file:
 Entry point: 0x44dd00
(gdb) b *0x44dd00 
```

**Comment by aarzilli** [comment]
PS. why are you interested?

**Comment by LichFaker** [comment]
I want to debug the go source, but I can only break points on the main function wrote myself.

So I want to know the initial entry point.

**Comment by aarzilli** [comment]
When you start the target program with delve you are already stopped at the entry point.
