### ISSUE TITLE
printGoroutines want show all stack, not limit with depth 10

### ISSUE THREAD

**Issue by tty5** [go-delve/delve#1443]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
2. What version of Go are you using? (`go version`)?
3. What operating system and processor architecture are you using?
4. What did you do?
5. What did you expect to see?
6. What did you see instead?

**Comment by tty5** [comment]
some times, goroutines -t will print all stack of goroutine, but the depth of stack is truncated with 10, maybe add option with full depth

**Comment by tty5** [comment]
if the app hang, and need to know all goroutines' stack to find root cause , so sometimes, it is needed

**Comment by aarzilli** [comment]
I think this should be handled by #1415 when we are done with that.

**Comment by aarzilli** [comment]
PS. I don't think adding more options to `goroutines` is a good idea.

**Comment by faicker** [comment]
There is no need to add new option but change the -t with argument of stack depth.

**Comment by derekparker** [comment]
Can be done via scripting.

**Comment by aktau** [comment]
I was looking at the examples of https://github.com/go-delve/delve/blob/master/Documentation/cli/starlark.md, which even has examples of manipulating goroutines, but I spent a decent amount of time recreating the Delve functionality, without truncating. I would've vastly preferred another option to not truncate, or even making truncation not the default anymore.

But, to anyone else that's looking, here's a starlark script that should get you going:

```
# Sourcing this script will print out all goroutines, without truncation. The format is slightly different from the dlv one, making it easier for me to parse.

# Takne from pkg/terminal/command.go
waitReasonStrings = [
    "",
    "GC assist marking",
    "IO wait",
    "chan receive (nil chan)",
    "chan send (nil chan)",
    "dumping heap",
    "garbage collection",
    "garbage collection scan",
    "panicwait",
    "select",
    "select (no cases)",
    "GC assist wait",
    "GC sweep wait",
    "GC scavenge wait",
    "chan receive",
    "chan send",
    "finalizer wait",
    "force gc (idle)",
    "semacquire",
    "sleep",
    "sync.Cond.Wait",
    "timer goroutine (idle)",
    "trace reader (blocked)",
    "wait for GC cycle",
    "GC worker (idle)",
    "preempted",
    "debug call",
]

def command_cgoroutines(args):
    gs = goroutines().Goroutines
    for g in gs:
        print("Goroutine %d - User: %s:%d (0x%x) [%s]" % (g.ID, g.UserCurrentLoc.File, g.UserCurrentLoc.Line, g.UserCurrentLoc.PC, waitReasonStrings[g.WaitReason]))

        frames = stacktrace(g.ID, 1000, False, True, None, None)
        for f in frames.Locations:
            print("  0x%x in %s at %s:%d" % (f.Location.PC, f.Location.Function.Name_, f.Location.File, f.Location.Line))

def main():
    dlv_command("cgoroutines")
```

This

**Comment by ovandriyanov** [comment]
> I would've vastly preferred another option to not truncate, or even making truncation not the default anymore.

+1 to this

**Comment by aarzilli** [comment]
See ec1d1efb7f1c10b8442b984dcb03fe0ab9b71bc7

**Comment by ovandriyanov** [comment]
> See [ec1d1ef](https://github.com/go-delve/delve/commit/ec1d1efb7f1c10b8442b984dcb03fe0ab9b71bc7)

This looks very helpful, thank you. Does it mean that now you can print full stack traces for each goroutine by typing `goroutines -exec stack -full`, like in the example [here](https://github.com/go-delve/delve/issues/3043#issuecomment-1165541493)? If so, including this example in the help message would be great.
