### ISSUE TITLE
Remove code licensed under incompatible license?

### ISSUE THREAD

**Issue by nickboldt** [go-delve/delve#1460]
Would it be possible to remove (or move to a fork off master branch) this file? 

* https://github.com/go-delve/delve/blob/master/pkg/proc/native/mach_exc.defs

I'm asking because that one file is licensed under APSL 2.0, where the rest of this repo is under MIT License. 

IANAL, but I don't think you can cross-license stuff with APSL and MIT.

**Comment by derekparker** [comment]
Thanks for raising this issue!

That file can actually be removed. That definition file is available elsewhere and doesn't even need to be checked into our source.

**Comment by nickboldt** [comment]
OMG thanks! I'm fairly sure that makes everything in the repo MIT licensed and open source friendly. 

#iOweYouABeer
