### ISSUE TITLE
Is there a way to debug with delve on Heroku?

### ISSUE THREAD

**Issue by frederikhors** [go-delve/delve#1463]
Is there a way to debug with delve on Heroku?

**Comment by aarzilli** [comment]
Looks like nobody knows here.

**Comment by leandro-andrade-candido** [comment]
go build -gcflags="all=-N -l" -o bin/YOUR-EXECUTABLE -v YOUR-FILE.go

Procfile:
web:~/go/bin/dlv --listen=:2345 --headless=true --api-version=2 --accept-multiclient exec bin/YOUR-EXECUTABLE

@frederikhors 

breakpoints working here.

**Comment by leandro-andrade-candido** [comment]
Install delve https://github.com/go-delve

I created a file ProcfileDebug:

web: ~/go/bin/dlv --listen=:2341 --headless=true --api-version=2 --accept-multiclient exec bin/YOUR-EXECUTABLE-01
worker_hub: /home/leandro/go/bin/dlv --listen=:2342 --headless=true --api-version=2 --accept-multiclient exec bin/YOUR-EXECUTABLE-02

then...
heroku local -f ProcfileDebug

then...
start remote debug listening (I use the golang IDE)

@frederikhors
