### ISSUE TITLE
Win7 64bit  use vscode report errors undefined: archInst

### ISSUE THREAD

**Issue by zoocke** [go-delve/delve#1464]
system:win7 64Bit
Golang:1.11.4
use vscode settings report errors:
dlv:
Error: Command failed: E:\Software\Development\Go\bin\go.exe get -u -v github.com/derekparker/delve/cmd/dlv
github.com/derekparker/delve (download)
github.com/go-delve/delve (download)
github.com/go-delve/delve/pkg/proc
# github.com/go-delve/delve/pkg/proc
E:\WorkSpace\VSCode\Go\src\github.com\go-delve\delve\pkg\proc\disasm.go:12:14: undefined: archInst
github.com/derekparker/delve (download)
github.com/go-delve/delve (download)
github.com/go-delve/delve/pkg/proc
# github.com/go-delve/delve/pkg/proc
E:\WorkSpace\VSCode\Go\src\github.com\go-delve\delve\pkg\proc\disasm.go:12:14: undefined: archInst

**Comment by aarzilli** [comment]
Copy here the output of `go version`. I think you are using `windows/i386` which is not supported.

**Comment by aarzilli** [comment]
Closing, no user feedback, likely duplicate.
