### ISSUE TITLE
'dlv debug' hangs for a long time then exits with error message

### ISSUE THREAD

**Issue by crimsonalucard** [go-delve/delve#1467]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 1.1.0
Build: $Id: 1990ba12450cab9425a2ae62e6ab988725023d5c $
```
2. What version of Go are you using? (`go version`)?
`go version go1.11.4 darwin/amd64`
3. What operating system and processor architecture are you using?
```
osx high sierra
Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro15,1
  Processor Name:	Intel Core i7
  Processor Speed:	2.2 GHz
  Number of Processors:	1
  Total Number of Cores:	6
  L2 Cache (per Core):	256 KB
  L3 Cache:	9 MB
  Memory:	16 GB
  Boot ROM Version:	220.230.16.0.0 (iBridge: 16.16.2542.0.0,0)
  Serial Number (system):	C02XJAJHJG5H
  Hardware UUID:	2BBB371F-6B1A-50AC-95A5-7F6F779D8EAD
```

4. What did you do?
run dlv debug
5. What did you expect to see?
I expected it to eventually enter the dlv prompt
6. What did you see instead?
dlv hangs for a really really long time. Then exits with an error:

```
$ dlv debug
# github.com/parsable/mothership/vendor/github.com/parsable/thrift-api/v1/thrift_metadata
<autogenerated>:1: internal compiler error: bvbulkalloc too big: nbit=42963 count=567595 nword=1343 size=762280085

Please file a bug report including a short program that triggers the error.
https://golang.org/issue/new
exit status 2
```

**Comment by aarzilli** [comment]
This is a bug with the go compiler, you should report it to Go like the error message says. However it sounds like [a similar bug was fixed](https://github.com/golang/go/issues/26560) so you should first check with go1.12beta2.

**Comment by crimsonalucard** [comment]
@aarzilli this code compiles under go.

**Comment by aarzilli** [comment]
Try passing `-gcflags='all=-N -l'` to the compiler, it should fail with that same error message.
