### ISSUE TITLE
could not find symbol value for err1

### ISSUE THREAD

**Issue by bruteforce1414** [go-delve/delve#1468]
1. Delve version is:
Delve Debugger
Version: 1.1.0
Build: $Id: 1990ba12450cab9425a2ae62e6ab988725023d5c $

2. What version of Go are you using? 
I use IDE Goland 2018.3 with Project SDK (1.11.4)
3. What operating system and processor architecture are you using?
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
CPU op-mode(s):      32-bit, 64-bit
Model name:          Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
4. What did you do?
Debugging in IDE Goland 
5. What did you expect to see?
Value of err1 in variables window of IDE Goland
6. What did you see instead?
could not find symbol value for err1

**Comment by aarzilli** [comment]
If you are debugging tests this is a [known bug](https://github.com/golang/go/issues/27681) that will be fixed in 1.11.5 and 1.12. If you aren't then we'll need a way to reproduce this.

**Comment by dlsniper** [comment]
I would also recommend to first upgrade to GoLand 2018.3.3 and then try debugging. Also, I'm not sure how you took the above version of delve, but we ship delve bundled with the IDE which means we don't rely on the version present in your GOPATH/bin so the version reported might not have anything to do with the actual version used by the IDE. Let us know if upgrading solves your problem. Thank you.

**Comment by aarzilli** [comment]
Closing, no user feedback.
