### ISSUE TITLE
Duplicate goroutineIDs and wrong stack trace

### ISSUE THREAD

**Issue by nd** [go-delve/delve#1469]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
  Delve built on revision b0056ebc97d8d43a13050839521a2110655fc7eb

2. What version of Go are you using? (`go version`)?
  1.9.2

3. What operating system and processor architecture are you using?
  linux

4. What did you do?
  In GoLand we have delve integration test suite and we noticed that sometimes threads in the debugger state contain duplicate goroutineIDs. E.g. in this log: https://gist.github.com/nd/7eb187a80b0f1fa638a3ce2a70da6bcb on line 7 threads `25085` and `25090` both have `goroutineID=1`. A subsequent `Stacktrace` call with `goroutineID=1` returns a stack of non-current thread `25090`. Can it be the result of the recent optimization (503bf529ca13cdb9a786d04c1768923f937301d3)? Unfortunately we cannot reproduce it reliably, sometimes it works fine.

5. What did you expect to see?
Each thread with its own goroutineID (with the exception of goroutineID=0). `Stacktrace` call returns meaningful results.

6. What did you see instead?

See above.

**Comment by nd** [comment]
Still cannot reproduce it locally with go 1.9.2, 1.11, and 1.12beta1..

Got another failure with the same code but a different behavior (https://gist.github.com/nd/d62c62c7010bbb9ef99dc3a080dd5aa9#file-delve-log).

We attach to delve, create a breakpoint on a marked line in the code above, and continue. Normally continue returns once breakpoint is reached, but as you can see in the log, it returns a state with the current thread inside rt0_linux_amd64.s, not there the breakpoint was created. Also the list of goroutines in this point is empty.

Not sure how to debug it further. I've tried running delve with more --log-output options, not only `rpc`, but they don't show anything useful.

**Comment by nd** [comment]
Reproduced it on my local 8-core machine with go1.11.5. It looks like it somehow depends on go scheduler. In CI environment tests are failing on 2-core machines. To reproduce it I had to specify cpu affinity for delve via taskset. Test failed on 39-th run. The code is the following:

```
package main

import "time"

func main() {
	for i := 0; i < 5; i++ {
		go func() {
			time.Sleep(11 * time.Millisecond)
		}()
	}

	x := 255
	println(x) //break
}
```

In test we start delve, create a breakpoint on a line with `//break` comment, continue, and try to evaluate `x` once the breakpoint is reached. Evaluation fails: `x` cannot be found. Rpc log from the test: https://gist.github.com/nd/a68cbe5158307eb813ba0d6be87287be. Notice that on line 15 we got a state where 2 threads have goroutineID=1. My theory is that a subsequent Eval fails because FindGoroutine() returns a goroutine not from the current thread.

BTW the situation when state has threads with duplicate goroutineID is not rare and can be reproduced without limiting number of cores. Our tests didn't fail in this case because clashing goroutine is not the one where breakpoint was reached.

**Comment by nd** [comment]
Was trying to record the failing execution trace using mozilla rr, but delve doesn't seem to work with it..

**Comment by aarzilli** [comment]
PTAL

**Comment by nd** [comment]
quick testing didn't show any duplicate goroutineIDs

**Comment by nd** [comment]
@aarzilli I wonder if there are any workaround for delve clients until the fix is merged? Also please let me know if I can help somehow to merge it sooner. 

P.S. your commit messages are amazing! Very enlightening! Thanks a lot.

**Comment by aarzilli** [comment]
> I wonder if there are any workaround for delve clients until the fix is merged?

The answer is no.
