### ISSUE TITLE
Setting a value does not work on function calls

### ISSUE THREAD

**Issue by dlsniper** [go-delve/delve#1473]
1. What version of Delve are you using (`dlv version`)?
b0056ebc97d8d43a13050839521a2110655fc7eb

2. What version of Go are you using? (`go version`)?
go version go1.11.4 windows/amd64
go version go1.12beta2 windows/amd64

3. What operating system and processor architecture are you using?
Windows 10 / amd64

4. What did you do?
- create a project using Go Modules support and the code below
- place a breakpoint on line 22
- run the application and make a request with ` curl -i http://localhost:8080/ `
- run ` set returnStatus = 404 ` in delve then resume the application

5. What did you expect to see?
I'd expect to get the status 404 on the request as well as the text should print ` [...] with status 404! `

6. What did you see instead?
Only the text prints ` [...] with status 404! ` but the status of the request is still 200.

This happens when running from GoLand as well as from the command line, so it's not related to the IDE.

I noticed that if I swap lines 22 and 23 and keep the breakpoint on line 22 then the result is the expected one. Hope it helps.

```go
package main

import (
	"fmt"
	"log"
	"net/http"
	"os"
	"time"

	"github.com/gorilla/mux"
)

const (
	readTimeout = 50
	writeTimeout = 100
	idleTimeout = 1200
)

func indexHandler(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/plain")
	returnStatus := http.StatusOK
	w.WriteHeader(returnStatus)
	message := fmt.Sprintf("Hello %s with status %d!", r.UserAgent(), returnStatus)
	w.Write([]byte(message))
}

func main() {
	serverAddress := ":8080"
	l :=log.New(os.Stdout, "sample-srv ", log.LstdFlags | log.Lshortfile)
	m := mux.NewRouter()

	m.HandleFunc("/", indexHandler)

	srv := &http.Server{
		Addr:         serverAddress,
		ReadTimeout:  readTimeout * time.Second,
		WriteTimeout: writeTimeout * time.Second,
		IdleTimeout:  idleTimeout * time.Second,
		Handler:      m,
	}

	l.Println("server started")
	if err := srv.ListenAndServe(); err != nil {
		panic(err)
	}
}
```

**Comment by aarzilli** [comment]
that line compiles to:

```
  blah.go:22		0x750931		488b8424e0000000		MOVQ 0xe0(SP), AX		
  blah.go:22		0x750939		8400				TESTB AL, 0(AX)			
  blah.go:22		0x75093b		488b4028			MOVQ 0x28(AX), AX		
  blah.go:22		0x75093f		488b8c24e8000000		MOVQ 0xe8(SP), CX		
  blah.go:22		0x750947		48890c24			MOVQ CX, 0(SP)			
  blah.go:22		0x75094b		48c7442408c8000000		MOVQ $0xc8, 0x8(SP)		
  blah.go:22		0x750954		ffd0				CALL AX				
```

the instruction of interest is 0x75094b which sets one of the function arguments directly to the constant 0xc8 (200). The compiler noticed that the value of the variable is constant and optimized the read away.

**Comment by dlsniper** [comment]
It's interesting that the same optimization does not happen when swapping the lines around. Should I open an issue with the Go Team given that we tell the build system to disable optimizations?

**Comment by aarzilli** [comment]
> Should I open an issue with the Go Team given that we tell the build system to disable optimizations?

You can try, it's something of a philosophical point.

**Comment by chainhelen** [comment]
@dlsniper 
![image](https://user-images.githubusercontent.com/7046329/51956882-557c4000-2484-11e9-8f79-2367df3f5bb5.png)  

Maybe `404`, not `22`??

**Comment by aarzilli** [comment]
Closing, tracked upstream.
