### ISSUE TITLE
Breakpoint filename resolution does not respect relative paths

### ISSUE THREAD

**Issue by ollien** [go-delve/delve#1474]
When attempting to set a breakpoint within a file that has the same name as a standard library file, I'm met with the following.

```
(dlv) break reader.go:176
Command failed: Location "reader.go:176" ambiguous: /home/nick/Documents/code/lolv/logread/reader.go, /usr/lib64/go/1.11/src/bytes/reader.go, /usr/lib64/go/1.11/src/net/textproto/reader.go, /usr/lib64/go/1.11/src/strings/reader.go…
```
I was hoping I could just do `break ./reader.go:176`, but this does not work.

```
(dlv) break ./reader.go:176
Command failed: Location "./reader.go:176" not found
```

However, if I give the absolute path, it's clear that delve can somehow resolve these relative paths

```
(dlv) break /home/nick/Documents/code/lolv/logread/reader.go:176
Breakpoint 1 set at 0x54a544 for github.com/ollien/lolv/logread.(*LogReader).ReadBackwardsToStartOfObject.func1() ./reader.go:176
```

Note that the output above quite clearly lists `./reader.go`. It would be nice if `break ./reader.go:176` worked as expected. Pasting the full path when I want a breakpoint can be quite frustrating.

1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 1.1.0
Build: $Id: 1990ba12450cab9425a2ae62e6ab988725023d5c $
```
2. What version of Go are you using? (`go version`)?
```
go version go1.11.4 linux/amd64
```
3. What operating system and processor architecture are you using?
OpenSUSE Tumbleweed on x86_64

**Comment by aarzilli** [comment]
You can specify partial paths `logread/reader.go`. I'm not a fan of this, personally. If `./reader.go` gets interpreted as a relative path should `logread/reader.go` also be interpreted as a relative path or should it be used for a partial match like we do now? The latter is more useful because it works regardless of what the current directory is.

**Comment by ollien** [comment]
You can specify the package path, sure, but then the output message should reflect that. It's confusing to see `./reader.go` when `logread/reader.go` gets that file.
