### ISSUE TITLE
Add a command to print the stack of all goroutines

### ISSUE THREAD

**Issue by yasushi-saito** [go-delve/delve#1475]
gdb has "thread apply all where" that shows the backtraces of all the threads. This command is pretty useful to get the state of the entire process with one command.

In general, it's nice to have an equivalent of "thread apply" that runs some command for a subset of goroutines.

If you can give me some guidance about the UX and design, I'm happy to volunteer w/ this feature.

**Comment by aarzilli** [comment]
`goroutines -t` does that, for more general things we are looking into adding a scripting language: #1466
