### ISSUE TITLE
Print fails with "expected operand, found 'go'"

### ISSUE THREAD

**Issue by jhendrixMSFT** [go-delve/delve#1476]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
Version: 1.1.0
Build: $Id: 1990ba12450cab9425a2ae62e6ab988725023d5c $
2. What version of Go are you using? (`go version`)?
go version go1.11.1 windows/amd64
3. What operating system and processor architecture are you using?
Win10 AMD64
4. What did you do?
p *(*github.com/andygrunwald/go-jira.ChangelogHistory)(0xc000098a20)
5. What did you expect to see?
value of ChangelogHistory
6. What did you see instead?
Command failed: 1:28: expected operand, found 'go'

Repro and debugging session output at https://gist.github.com/jhendrixMSFT/894fb1285ff01ccaf88cce35cd602683

**Comment by aarzilli** [comment]
the type needs to be in quotes: ` p *(*"github.com/andygrunwald/go-jira.ChangelogHistory")(0xc000098a20)`, we can't parse it otherwise, unfortunately.

**Comment by jhendrixMSFT** [comment]
Thanks I can confirm this works.  Re-reading the docs [here](https://github.com/go-delve/delve/blob/master/Documentation/api/ClientHowto.md#loading-more-of-a-variable) I overlooked the `%q` in syntax, sorry about that.
