### ISSUE TITLE
Starting dlv on a process immediately segfaults 

### ISSUE THREAD

**Issue by PazAharon** [go-delve/delve#1481]
Hi, 
We are compiling our code via go and try to debug it via dlv.
When we executing the next line : 
`dlv exec <binary> `
We get a segfault when delve is trying to read the ELF contents.
Here is the stacktrace:
```
API server listening at: [::]:36693
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x69706e]

goroutine 11 [running]:
github.com/derekparker/delve/pkg/proc.(*BinaryInfo).setGStructOffsetElf(0xc42009b600, 0xc4201240a0, 0xc42011e380)
                /usr/local/go/src/github.com/derekparker/delve/pkg/proc/bininfo.go:675 +0x14e
created by github.com/derekparker/delve/pkg/proc.(*BinaryInfo).LoadBinaryInfoElf
                /usr/local/go/src/github.com/derekparker/delve/pkg/proc/bininfo.go:619 +0x31f
```
The binary otherwise runs perfectly outside of delve.

1. What version of Delve are you using (`dlv version`)?
   v1.1.0 release
2. What version of Go are you using? (`go version`)?
    go1.8.7
3. What operating system and processor architecture are you using?
   Linux linux-vta3 4.20.0-1-default #1 SMP PREEMPT Tue Jan 8 08:38:29 UTC 2019 (34f009a) x86_64 x86_64 x86_64 GNU/Linux
4. What did you do?
    Execute the binary file via delve (also fails when attaching to the process)
5. What did you expect to see?
     Delve running out process
6. What did you see instead?
        SIGSEGV

**Comment by aarzilli** [comment]
line 675 isn't inside setGStructOffsetElf either in master or on the release 1.1.0 branch. Do you know the commit hash of delve that you are building? or can you reproduce this with either a build of release1.1.0 or master?

**Comment by PazAharon** [comment]
We downloaded the release via GitHub’s release tab, by downloading the assets (both the zip and tar.gz version).
We tried downloading it again, and the code in question is indeed inside ‘setGStructOffsetElf’.
From a fresh download:
delve-1.1.0.zip\delve-1.1.0\pkg\proc\bininfo.go
Line 675:
`bi.gStructOffset = ^(tls.Memsz) + 1 + tlsg.Value // -tls.Memsz + tlsg.Value`
Under method:
`func (bi *BinaryInfo) setGStructOffsetElf(exe *elf.File, wg *sync.WaitGroup)
`

**Comment by aarzilli** [comment]
You can try #1483 but it's possible that it won't work anyway. Your executable has runtime.tlsg but no PT_TLS section which shouldn't happen (and didn't happen with pure go back when we tested 1.8). If you absolutely have to use 1.8 and debug this program you may have to disassemble main.main and hard code the g struct offset yourself. Otherwise I would suggest updating to a supported version of Go.

**Comment by PazAharon** [comment]
But by github's documentation version 1.8 **is** supported:
https://github.com/go-delve/delve/tree/master/Documentation/installation

**Comment by aarzilli** [comment]
I meant "supported by the go team"

**Comment by PazAharon** [comment]
After some work, we found out the issue was that our binary was dynamically linked to other go binaries.
After removing the "linkshared" flag (and getting a binary that takes 10 times the space), we managed to delve it properly.
We searched around a bit, but couldn't find anything about how to delve shared binaries. Is there a specific procedure for it? It is even supported?

**Comment by aarzilli** [comment]
It is not supported, the plugin PRs would get you part of the way there, but I'm not sure where we should look for the TLS offset of g.

**Comment by PazAharon** [comment]
ok
thanks!
