### ISSUE TITLE
how to print stack on a breakpoint and continue to run

### ISSUE THREAD

**Issue by tty5** [go-delve/delve#1482]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)? 
master

2. What version of Go are you using? (`go version`)?
3. What operating system and processor architecture are you using?
4. What did you do?
5. What did you expect to see?
6. What did you see instead?

i find that command on can add commands on a bp, but only use

Supported commands: print, stack and goroutine

how to continue to run after commands are finished?

**Comment by aarzilli** [comment]
You can do this using the commands `trace` and `on`
