### ISSUE TITLE
dlv throws "could not launch process: could not find external debug info file"

### ISSUE THREAD

**Issue by openstacks** [go-delve/delve#1485]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.2.0
2. What version of Go are you using? (`go version`)?
go version go1.11.5 
3. What operating system and processor architecture are you using?
linux/amd64
4. What did you do?
root@cloudcome:/home/cloudcome/go_projects/src/k8s.io/kubernetes/_output/bin# dlv exec ./openapi-gen

5. What did you expect to see?
    Type 'help' for list of commands.
   (dlv) 
6. What did you see instead?
  could not launch process: could not find external debug info file

**Comment by chainhelen** [comment]
```
// ErrNoDebugInfoFound is returned when Delve cannot find the external debug information file.
var ErrNoDebugInfoFound = errors.New("could not find external debug info file")
```  
It means there is not any debug symbols.

**Comment by dlsniper** [comment]
The binary is probably built with the ` -w ` flag which strips out the DWARF information from it. Try to build the binary using Delve itself, ` delve debug k8s.io/kubernetes/<path to openapi-gen command> ` or something similar

**Comment by aarzilli** [comment]
What @chainhelen and @dlsniper said.

**Comment by barbu110** [comment]
Hello! I am building my executable without the `-w` flag, like this:

    go build -ldflags="-s -compressdwarf=false" -gcflags="all=-N -l" ./mypackage

and I still get the error

**Comment by dlsniper** [comment]
Then you are not stripping the DWARF info, you are stripping all debug info as well, see: https://golang.org/cmd/link/
```
-s Omit the symbol table and debug information.
```

**Comment by RiccardoManfrin** [comment]
Same issue, different flags:

    CGO_ENABLED=0 GOOS=linux go build -gcflags '-N -l' -a -ldflags '-extldflags "-static"' -o susancalvin.debug

    dlv exec ./susancalvin.debug 
could not launch process: could not find external debug info file

Can you spot the nasty option in here?

**Comment by justinejose91** [comment]
I am getting the error "Could not open debug info", when I attach a process in DLV, this is how I am building - go build -gcflags=all="-N -l" -v -o file.go.
Can someone give some insight into this?
