### ISSUE TITLE
dlv failed to find lib when debug consul

### ISSUE THREAD

**Issue by varnson** [go-delve/delve#1489]
dlv: ver1.2.0
go: go1.11.4 windows/amd64
Consul: 1.4.0 (windows, https://github.com/hashicorp/consul)

msg：
D:\go-repo\consul>dlv debug
# _/D_/go-repo/consul
.\main.go:47:3: cannot use cmds (type map[string]"github.com/hashicorp/consul/vendor/github.com/mitchellh/cli".CommandFactory) as type map[string]"github.com/mitchellh/cli".CommandFactory in field value
exit status 2

**Comment by chainhelen** [comment]
@varnson  The source code are compiled failed，maybe you can try `go build` to find reason.

**Comment by aarzilli** [comment]
Not a bug, your code doesn't compile like @chainhelen said.
