### ISSUE TITLE
Make use of tracebackancestors

### ISSUE THREAD

**Issue by gracenoah** [go-delve/delve#1491]
Go 1.11 introduced the following flag:

```
GODEBUG=tracebackancestors=n
```

When it's used, stacktraces include the most recent ancestors of goroutines. Therefore, this information must be available somewhere. It would be very helpful if delve had some way to access this information.

Maybe there already is an I'm missing something? If so, at least this issue will make the feature more googleable. If not, I guess this is a feature request.

**Comment by derekparker** [comment]
I think this would be a good flag to add when creating stack traces, and shouldn't be all that hard to accomplish. Ancestors are being stored on the newly created G struct, so we have access to that information.

**Comment by aarzilli** [comment]
CL: https://go-review.googlesource.com/c/go/+/70993/
Ancestors are stored in runtime.g.ancestors

**Comment by aarzilli** [comment]
Does github not close issues automatically anymore? Implemented by 98265315975c6ecd46e5a19268c39889bfbe9b9d
