### ISSUE TITLE
syscall_windows.go:105: syntax error: unexpected = in type

### ISSUE THREAD

**Issue by waytoharish** [go-delve/delve#1494]
Hi Team,
I am facing below issue when trying to install dlv on window env-
Installing github.com/go-delve/delve/cmd/dlv FAILED

1 tools failed to install.

dlv:
Error: Command failed: C:\Go\bin\go.exe get -u -v github.com/go-delve/delve/cmd/dlv
github.com/go-delve/delve (download)
github.com/go-delve/delve/pkg/proc/native
# github.com/go-delve/delve/pkg/proc/native
C:\Users\HarishSharma\go\src\github.com\go-delve\delve\pkg\proc\native\syscall_windows.go:105: syntax error: unexpected = in type declaration

My Go env details are-
PS C:\Harish\squash> go env
set GOARCH=amd64
set GOBIN=C:\Go\bin
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\HarishSharma\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2

PS C:\Harish\squash> go version
go version go1.8.1 windows/amd64

**Comment by dlsniper** [comment]
You should upgrade to Go 1.9 as the error comes from using a feature named `Type alias`, which is not present in Go 1.8. Furthermore, the latest Go version is 1.11.5 and you should probably upgrade to that if possible since it brings a lot of improvements to the debugging experience and overall performance and experience for non-debugging as well.

**Comment by PazAharon** [comment]
If you have to use go1.8, download the 1.1 release and compile it yourself, worked great for me :)

**Comment by waytoharish** [comment]
Thanks both. 
Working fine with 1.11.
