### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by dharmab** [go-delve/delve#1505]
`go get -u github.com/go-delve/delve/cmd/dlv` fails due to https://github.com/golang/lint/issues/436

```
$ go get -u github.com/go-delve/delve/cmd/dlv
go: finding github.com/go-delve/delve/cmd/dlv latest
[snip]
go: finding github.com/golang/lint latest
go: github.com/golang/lint@v0.0.0-20190227174305-5b3e6a55c961: parsing go.mod: unexpected module path "golang.org/x/lint"
go: finding github.com/beorn7/perks latest
go: finding github.com/shurcooL/go latest
go: finding github.com/gorilla/mux v1.7.0
go get: error loading module requirements
```

1. What version of Delve are you using (`dlv version`)? None
2. What version of Go are you using? (`go version`)? `go version go1.12 darwin/amd64`
3. What operating system and processor architecture are you using? macOS, x86-64
4. What did you do? Run `go get -u github.com/go-delve/delve/cmd/dlv`
5. What did you expect to see? Delve install
6. What did you see instead? Delve failed to install

**Comment by aarzilli** [comment]
We don't depend on any of those things. You are using `go get` in modules mode, where it does something different. See https://github.com/golang/go/issues/24250. You have to turn off modules mode before using go get.
