### ISSUE TITLE
Problem: Installation(repo) error on windows

### ISSUE THREAD

**Issue by Bazis007** [go-delve/delve#1509]
I Have problem with installation on Windows.

When I do steps from instruction, 
https://github.com/go-delve/delve/blob/master/Documentation/installation/windows/install.md

I got:
C:\Go\bin>go get -u github.com/go-delve/delve/cmd/dlv
# cd C:\Users\**********\go\src\github.com\go-delve\delve; git pull --ff-only
fatal: Not a git repository (or any of the parent directories): .git
package github.com/go-delve/delve/cmd/dlv: exit status 128

Please chek repo or manual.

**Comment by Bazis007** [comment]
Upd: go version go1.12 windows/amd64

**Comment by chainhelen** [comment]
@Bazis007 Something wrong with git, not dlv. Just like [this](https://stackoverflow.com/questions/9617336/how-to-resolve-git-did-not-exit-cleanly-exit-code-128-error-on-tortoisegit) about `exit status 128`, or [it](https://github.com/kardianos/govendor/issues/363)

**Comment by Bazis007** [comment]
@chainhelen  Thank you!
I am remove folder : C:\Users(User)\go\src\github.com\go-delve and I was abble to iinstall.
Sorry for stupid question :)
