### ISSUE TITLE
dlv fails with certain combinations of flags

### ISSUE THREAD

**Issue by firelizzard18** [go-delve/delve#1510]
When running delve as a headless debug server, it fails to start when the value of the `--wd` flag starts with `~/` and other flags are passed. Running an interactive (shell) debug session with the same value of `--wd` succeeds. Running a headless session with a relative or absolute `--wd` path succeeds. More details are available on Microsoft/vscode-go#2374.
```
# works
dlv debug --wd=~/path/to/workspace/src/other/project

# fails
dlv debug --headless=true --listen=127.0.0.1:PORT --api-version=2 --wd=~/path/to/workspace/src/other/project

# works
dlv debug --headless=true --listen=127.0.0.1:PORT --api-version=2 --wd=../../../../src/other/project

# works
dlv debug --headless=true --listen=127.0.0.1:PORT --api-version=2 --wd=/Users/me/path/to/workspace/src/other/project
```

1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 1.2.0
Build: $Id: 068e2451004e95d0b042e5257e34f0f08ce01466 $
```
2. What version of Go are you using? (`go version`)?
```
go version go1.12 darwin/amd64
```
3. What operating system and processor architecture are you using? macoS Mojave 10.14.3 (18D109), Intel Core i7 (x86_64).
4. What did you do?
```
% dlv debug --headless=true --listen=127.0.0.1:37689 --api-version=2 --wd=~/path/to/workspace/src/other/project
```
5. What did you expect to see? A successful debug server.
6. What did you see instead?
```
API server listening at: 127.0.0.1:37689
could not launch process: fork/exec /Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver: no such file or directory
```

**Comment by aarzilli** [comment]
This is just how shell expansion works. `~` is expanded by the shell, but only if it's at the start of an argument if you do `--wd ~/path/to/workspace/src/other/project` it should work.

**Comment by aarzilli** [comment]
IMHO we shouldn't do anything as this is consistent with the behavior of most tools, for example doing `go build -o=~/somedir/out` will create a `~` directory in the current directory, `somedir` inside that directory and then write its output to `$PWD/~/somedir/out` (don't do this btw, removing a directory named `~` from the command line is complicated)
