### ISSUE TITLE
Empty value of a string variable

### ISSUE THREAD

**Issue by nd** [go-delve/delve#1511]
1. What version of Delve are you using (`dlv version`)?
    
built on commit ac3b1c7

2. What version of Go are you using? (`go version`)?

go version go1.12 darwin/amd64

3. What operating system and processor architecture are you using?

linux x86_64

4. What did you do?

Evaluated the `&x[0]` expression once the breakpoint is reached in the following program:

```
package main

import "runtime"

func main() {
	x := []string{"a"}
	println(&x[0])
	runtime.Breakpoint()
}
```

5. What did you expect to see?

Delve rpc response where the only child of the pointer has value "a"

6. What did you see instead?

The following response:

```
DEBU[0014] <- RPCServer.Eval(rpc2.EvalIn{"Scope":{"GoroutineID":-1,"Frame":0,"DeferredCall":0},"Expr":"\u0026x[0]","Cfg":{"FollowPointers":true,"MaxVariableRecurse":3,"MaxStringLen":100,"MaxArrayValues":100,"MaxStructFields":-1}})  layer=rpc
DEBU[0014] -> *rpc2.EvalOut{"Variable":{"name":"\u0026x[0]","addr":0,"onlyAddr":false,"type":"*string","realType":"*string","flags":0,"kind":22,"value":"","len":0,"cap":0,"children":[{"name":"","addr":824633993048,"onlyAddr":true,"type":"string","realType":"string","flags":0,"kind":24,"value":"","len":1,"cap":0,"children":[],"base":4667440,"unreadable":"","LocationExpr":"","DeclLine":0}],"base":0,"unreadable":"","LocationExpr":"","DeclLine":0}} error: ""  layer=rpc
```

Notice `"value":""` inside the child node. Increasing `MaxVariableRecurse` doesn't help.

**Comment by aarzilli** [comment]
We're doing this because the assumption is that if the user uses `&` it's because they want to see the address of the expression, which is what we return.

**Comment by nd** [comment]
Makes sense for front-end, but I'd expect rpc api to respect the `FollowPointers: true` option.

**Comment by nd** [comment]
Imaging I have an intermediate variable `y := &x[0]`. Evaluating `y` returns children, evaluating `&x[0]` doesn't. Imho this is surprising given that `FollowPointers` is set to true. 

GoLand provides a way to expand children in UI, but it doesn't work for expressions starting with `&`. We can probably workaround that by detecting `&` and sending a different request (or 2 requests), but every Delve client with a similar UI will have to do the same.
