### ISSUE TITLE
Inappropriate constant returned as the value of a variable

### ISSUE THREAD

**Issue by palsivertsen** [go-delve/delve#1516]
Given the following program
```go
package main

import (
  _ "net/http"
  "time"
)

var d time.Duration

func main() {
  d = time.Hour * 24 * 7 
}
```
when printing the `d` variable I get the following output:
```
d: crypto/tls.maxSessionTicketLifetime
```

I'm assuming the go compiler does some magic here since `crypto/tls.maxSessionTicketLifetime == d`. The problem is that the debugger does not show the actual value. I'd expect to see either `d: 168h0m0s` or `d: 604800000000000`.

## Steps to reproduce
1. Save the above main.go file
2. Create a file named `cmd.dlv` with the following content:
```
trace main.go:12
on 1 print d
continue
q
```
3. Run the debugger:
```
$ dlv debug --init cmd.dlv 
Type 'help' for list of commands.
Tracepoint 1 set at 0x6f3571 for main.main() ./main.go:12
> main.main() ./main.go:12 (hits goroutine(1):1 total:1) (PC: 0x6f3571)
	d: crypto/tls.maxSessionTicketLifetime
cmd.dlv:3: Process 13116 has exited with status 0
Process 13116 has exited with status 0
```

## Additional inforamtion
1. What version of Delve are you using (`dlv version`)?
```
$ dlv version
Delve Debugger
Version: 1.2.0
Build: $Id: 068e2451004e95d0b042e5257e34f0f08ce01466 $
```
2. What version of Go are you using? (`go version`)?
```
$ go version
go version go1.12.1 linux/amd64
```
3. What operating system and processor architecture are you using?
```
$ uname -a
Linux pal-desktop 4.15.0-46-generic #49~16.04.1-Ubuntu SMP Tue Feb 12 17:45:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by aarzilli** [comment]
This happens because there is a constant defined by crypto/tls, called maxSessionTicketLifetime that happens to have the same value and type as d. We do the constant lookup thing because usually it helps, your case being a counterexample. I'd be inclined to not doing anything here.

**Comment by palsivertsen** [comment]
> We do the constant lookup

That's a cool feature ;)

> I'd be inclined to not doing anything here.

Agreed. But maybe update `print` documentation describing this behaviour?

## Workaround
For anyone interested in a workaround you can cast the variable to another type. In this case casting `time.Duration` to `int64` does the trick:
```
(dlv) p int64(d)
604800000000000
```

**Comment by aarzilli** [comment]
On second thought I think we should do better and not look up constant that don't belong in either the variable's package, the current function's package or the variable's type's package.

**Comment by palsivertsen** [comment]
Another option is to change the formatting to include both like so: `constant (value)`.

The output from this issue would then be:
```
d: crypto/tls.maxSessionTicketLifetime (604800000000000)`
