### ISSUE TITLE
Printing a variable from a type switch does not work correctly

### ISSUE THREAD

**Issue by dlsniper** [go-delve/delve#1518]
1. What version of Delve are you using (`dlv version`)?
ac3b1c7a786d681a5aefcdded9888090d69b3832

2. What version of Go are you using? (`go version`)?
go1.12.1

3. What operating system and processor architecture are you using?
windows/amd64

4. What did you do?
- use the sample code below
- place a breakpoint on line 17
- debug the application
- use ` whatis p `

5. What did you expect to see?
` int `

6. What did you see instead?
```
interface {}
Concrete type: int
```

Sample code:
```go
package main

import "fmt"

func main() {
	demo(2)
}

func demo(val interface{}) {
	switch v := val.(type) {
	case int32:
		println("int32", v)
	case int64:
		println("int64", v)
	default:
		fmt.Printf("%#v -- %T", v, v)
		println("something else", v)
	}
}
```

**Comment by aarzilli** [comment]
I disagree that you should see a `v` variable of type `int` anywhere. The [go language specification](https://golang.org/ref/spec#TypeSwitchStmt) clearly states that the type of `v` in the default branch should be the same as `val` (id est `interface {}`). We could replace the type of interface variables with their concrete type but we don't do that anywhere else, so why here. I'm leaning strongly towards not a bug.
