### ISSUE TITLE
Not work when "go build -buildmode=pie"

### ISSUE THREAD

**Issue by imxyb** [go-delve/delve#1522]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
 1.2.0
2. What version of Go are you using? (`go version`)?
1.11.6
3. What operating system and processor architecture are you using?
centos7
4. What did you do?
build cmd:
```
go build -buildmode=pie -gcflags="all=-N -l" -ldflags "-X main.gitCommit="dd22a84864│   runc ps [command options] <container-id> [ps options]
f529678e92dfe2d23b3daf6c786257" -X main.version=1.0.0-rc6+dev " -tags "seccomp" -o runc .
```
i use `goland` to  connect my centos vbox to debug `runc`, but my goland display `numberfomation exception` and warn the address is overflow
5. What did you expect to see?
can work in buildmod=pie
6. What did you see instead?

**Comment by dlsniper** [comment]
It would be helpful to have the error message that you receive, and maybe a screenshot of it as well. At which part of the process do you receive the error? How is GoLand related to this problem? Which IDE version do you use?

**Comment by imxyb** [comment]
@dlsniper my goland version is 2018.3.5，and the error:
![image](https://user-images.githubusercontent.com/7411249/54976814-65bd2100-4fd6-11e9-9f2d-8c8ffcaf8d8d.png)

And the delve log is:
`INFO[0005] created breakpoint: &api.Breakpoint{ID:1, Name:"", Addr:0x5578a7215b28, File:"/go/src/github.com/opencontainers/runc/run.go", Line:66, FunctionName:"main.glob..func13", Cond:"", Tracepoint:false, TraceReturn:false, Goroutine:false, Stacktrace:0, Variables:[]string(nil), LoadArgs:(*api.LoadConfig)(nil), LoadLocals:(*api.LoadConfig)(nil), HitCount:map[string]uint64{}, TotalHitCount:0x0}  layer=debugger`

**Comment by imxyb** [comment]
@dlsniper if build without `buildmod=pie`, devle is work.

**Comment by dlsniper** [comment]
@imxyb please try https://www.jetbrains.com/go/nextversion/ and see if the Release Candidate solves the issue. Thank you.

**Comment by aarzilli** [comment]
Looks like delve is creating the breakpoint, goland bug?

**Comment by imxyb** [comment]
@dlsniper @aarzilli  em...may be goland bug, because my goland is newest

**Comment by imxyb** [comment]
I have report to goland, thank you.
