### ISSUE TITLE
Option to suppress "API server listening..." message

### ISSUE THREAD

**Issue by thallgren** [go-delve/delve#1523]
1. What version of Delve are you using (`dlv version`)? Version: 1.2.0
2. What version of Go are you using? (`go version`)? go version go1.11.5 linux/amd64
3. What operating system and processor architecture are you using? GNU/Linux 4.20.8 x86_64
4. What did you do? Try debug a Hashicorp Go-plugin with delve exec [command] --headless
5. What did you expect to see? Plugin starting and waiting
6. What did you see instead? The message "error while loading plugin executable [command]: Unrecognized remote plugin message: API server listening at: xxx" is printed and the plugin terminates.

The Hashicorp go-plugin expects that the first message printed by the executable adheres to a handshake protocol. Instead, the first line printed is the "API servier listening...". It would be great if there was an option like --quiet or similar to prevent this message from being printed.

**Comment by aarzilli** [comment]
Implemented by 48f1f51ef9c5c281af79630e3d7b6216778d2914
