### ISSUE TITLE
Debugger does not stop at correct breakpoint

### ISSUE THREAD

**Issue by dlsniper** [go-delve/delve#1527]
1. What version of Delve are you using (`dlv version`)?
ac3b1c7a786d681a5aefcdded9888090d69b3832
2. What version of Go are you using? (`go version`)?
go version go1.12.1
3. What operating system and processor architecture are you using?
windows 10/amd64 (i7 7600HQ)
4. What did you do?
Debug the code below with a breakpoint on line 15
5. What did you expect to see?
` print i => i = 0 `
6. What did you see instead?
` print i => i = 3 `

I tried this on Go 1.11.6 and it worked as expected, which makes me wonder if it's a bug in Go or in Delve's reading of Go information. I'll be happy to report it to the Go team if this is the wrong place. Thank you.

```go
package main

type Struct struct {
	Name string
	Func func()
}

func NewStruct(name string) Struct {
	return Struct{Name:name}
}

func FindIndex2(structs []Struct, s string) int {
	for i, st := range structs { // breakpoint here, then step
		// fmt.Println(i) // uncomment this and it will work
		if st.Name == s { // starts with i = 3
			return i
		}
	}
	return -1
}

func main() {
	structs := []Struct{
		NewStruct("a"),
		NewStruct("b"),
		NewStruct("c"),
		NewStruct("dddddddd1"),
		NewStruct("dddddddd2"),
	}

	FindIndex2(structs, "dddddddd2")
}
```

**Comment by aarzilli** [comment]
Fixed upstream.
