### ISSUE TITLE
Failed to evaluate expression - entry.Data (type github.com/sirupsen/logrus.Fields) is not a struct

### ISSUE THREAD

**Issue by Strum355** [go-delve/delve#1528]
1. What version of Delve are you using (`dlv version`)? 1.2.0
2. What version of Go are you using? (`go version`)? 1.12.1 linux/amd64
3. What operating system and processor architecture are you using? Ubuntu 16.04 amd64
4. What did you do? Expand `sirupsen/logrus.Entry.Data` field of type `type Field map[string]interface{}`
5. What did you expect to see? Each key-value pair of the `map[string]interface{}`
6. What did you see instead?
```
Failed to eval expression:  {
 "Expr": "entry.Data.Data[\"info\"]",
 "Scope": {
  "goroutineID": -1,
  "frame": 0
 },
 "Cfg": {
  "followPointers": true,
  "maxVariableRecurse": 1,
  "maxStringLen": 64,
  "maxArrayValues": 64,
  "maxStructFields": -1
 }
} 

Eval error: entry.Data (type github.com/sirupsen/logrus.Fields) is not a struct
Failed to evaluate expression - entry.Data (type github.com/sirupsen/logrus.Fields) is not a struct
```

![image](https://user-images.githubusercontent.com/18282288/55163918-93cf6c00-5162-11e9-8bab-58fea698c7ca.png)

**Comment by aarzilli** [comment]
It looks like the editor (VSCode?) is trying to evaluate `entry.Data.Data["info"]` which fails because `entry.Data.Data` doesn't exist. This is a bug in the editor, not delve.
