### ISSUE TITLE
why this map key in debug window is empty？

### ISSUE THREAD

**Issue by bluegeek** [go-delve/delve#1531]
1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 1.2.0
Build: $Id: 068e2451004e95d0b042e5257e34f0f08ce01466 $
```
2. What version of Go are you using? (`go version`)?
```
go version go1.12 darwin/amd64
```
3. What operating system and processor architecture are you using?
```
MacBook Pro (Retina, 15-inch, Mid 2015)
```
4. What did you do?
```go
package main

import (
	"fmt"
)

type W struct {
	x int
	y int
}
func main() {
	testMaps()
}

func testMaps() {

	m := make(map[string]W)

	m["t"] = W{}
	m["s"] = W{}
	m["r"] = W{}
	m["v"] = W{}

	mm := map[string]W{
		"r": {},
		"s": {},
		"t": {},
		"v": {},
	}

	delete(mm, "s")
	delete(m, "t")
	fmt.Println(m,mm)
}

```

![image](https://user-images.githubusercontent.com/3932305/55382945-839c0000-5559-11e9-8cb9-7333ed5f63a2.png)

why mm[0][key] is empty please?

**Comment by joshw** [comment]
Has this fix been merged yet?  I believe i'm encountering this issue in delve 1.2.0 and was hoping it will be fixed in the next release

**Comment by klanghans** [comment]
I am having the same bug, was chasing a concurrency issue for hours before i found out that my map is still consistent, just delve was broken.
FYI: if you insert a new key after the delete, the debugger shows a consistent representation again.
