### ISSUE TITLE
could not launch process: stub exited while waiting for connection: exit status 0

### ISSUE THREAD

**Issue by sbromberger** [go-delve/delve#1534]
1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 1.2.0
Build: $Id: 068e2451004e95d0b042e5257e34f0f08ce01466 $
```
2. What version of Go are you using? (`go version`)?
```
go version go1.12.1 darwin/amd64
```

3. What operating system and processor architecture are you using?
macOS 10.14.4 (18E226)

4. What did you do?
  - `go get github.com/golang/example/...`
  - `dlv debug ./hello` from the directory

5. What did you expect to see?
A delve prompt

6. What did you see instead?
```
could not launch process: stub exited while waiting for connection: exit status 0
```

**Comment by sbromberger** [comment]
Solved: I was running `dlv` via ssh, and I was not a member of the `_developers` group. Adding myself to that group made things work again.

**Comment by shanemcd** [comment]
I just found myself here and the solution described above did not help me. This did the trick:

```
$ sudo /usr/sbin/DevToolsSecurity --enable
```
