### ISSUE TITLE
dlv debug fail due to undefined object in same package

### ISSUE THREAD

**Issue by winhung** [go-delve/delve#1535]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)? 1.2.0
2. What version of Go are you using? (`go version`)? go1.11.4 linux/amd64
3. What operating system and processor architecture are you using? CentOS 7 64-bit
4. What did you do?
I have 2 files all in the same directory and part of the same package, main.go and common.go, as shown below. When i run 'dlv debug --listen=:2345 --headless --api-version=2 --log main.go', it fails with ./main.go:21:16: undefined: NewSimpleStruct.
```
package main

import (
	"fmt"
)

func main() {
	fmt.Println("HELLO WORLD!")
	segasaturn := NewSimpleStruct("SS", 69)
	segasaturn.WhoAmI()

	fmt.Println("BYE WORLD!")
}
```
```
common.go

package main

import "fmt"

type simpleStruct struct {
	name string
	id   int
}

func NewSimpleStruct(name string, id int) *simpleStruct {
	return &simpleStruct{name, id}
}

func (ss *simpleStruct) WhoAmI() {
	fmt.Printf("name: %s, id: %d\n", ss.name, ss.id)
}
```
5. What did you expect to see?
Successful execution of dlv debug.
6. What did you see instead?
./main.go:21:16: undefined: NewSimpleStruct

**Comment by aarzilli** [comment]
You need to list all go files or just use `debug` without specifying any files. `go build main.go` wouldn't work either.
