### ISSUE TITLE
Is Delve able to recover after WS connection failure? 

### ISSUE THREAD

**Issue by PavelSosin** [go-delve/delve#1536]
Please answer the following before submitting your issue:

See issue https://github.com/theia-ide/theia/issues/4590
and other Go debugging related issues on Theia and vscode
You can communicate with everybody who opened these issues directly. 

Due to using of non-stable cloud proxies like Traefic which has issues with WS any short-term WS ping-pong frames interchange timeout can cause WS session break by infra. What is your proposals for debug session recovery? If Delve server is deployed to cloud infra and the correct afinity is configured in Proxy server any re-connection attempt from the client side will be useless if server state will be lost. If Delve is deployed on kubernetes pod Delve failure will cause pod re-start but kubernetes doesn't restore container states when re-starting pods.   
Unfortunately, DAP protocol spec doesn't contain any recovery sequence.
1. What version of Delve are you using (`dlv version`)?
2. What version of Go are you using? (`go version`)?
3. What operating system and processor architecture are you using?
4. What did you do?
5. What did you expect to see?
Automatic or manual debug station recovery or restart
6. What did you see instead?
Debug session freeze

**Comment by aarzilli** [comment]
Delve doesn't use WebSockets in any way and doesn't implement DAP.
