### ISSUE TITLE
Delve Is Amazing - You Don't Get Enough Credit

### ISSUE THREAD

**Issue by swtch1** [go-delve/delve#1537]
This is **not** an issue, I just wanted to say that **Delve is amazing**.  It provides a level of introspection that I take for granted every day in my IDE and that which has dug me out of many holes.  You guys, and open source maintainers in general, don't get enough credit or praise.

So take a deep breath, press the close button for free, and remember that what you're doing matters to a lot of people.

1. What version of Delve are you using (`dlv version`)? the last one
2. What version of Go are you using? (`go version`)? the last one
3. What operating system and processor architecture are you using? all of them
4. What did you do? delvey things
5. What did you expect to see? something mediocre
6. What did you see instead? something amazing

**Comment by aarzilli** [comment]
Thanks :smile:

**Comment by derekparker** [comment]
Thank you! Really appreciate that!

**Comment by tylerb** [comment]
Agreed. Thanks for creating this! It's fantastic!
