### ISSUE TITLE
testing multiple packages with delve

### ISSUE THREAD

**Issue by MalloZup** [go-delve/delve#1539]
Hi! thx for your project i like it a lot.

Currently I'm trying to figure out out to run multiple tests pkgs with delve.

Suppose we have a dir with 2 pkgs directory which contains some tests and golang files
layout:
``` 
myFirstpkg/
      ---> _test.go files..
mySecondpkg/
     ---> _test.go files etc.
```

Let me illustrate the `go test` behaviour: (i added some fake names but this works)

```golang
go test -v ./myFirstPkg/... ./mySecondPkg/...
=== RUN   TestPrintVersion
TestPrintVersion
--- FAIL: TestPrintVersion (0.00s)
=== RUN   TestFoo
TestFoo
--- PASS: TestFoo (0.00s)
FAIL
FAIL	github.com/my1stpkg 0.054s
=== RUN   TestPrintVersion33
TestPrintVersion33
--- PASS: TestPrintVersion33 (0.00s)
=== RUN   TestFoo11
TestFoo11
--- PASS: TestFoo11 (0.00s)
PASS
ok  	secondpkg	(cached)
```
But when i run with `dlv`

```golang

dlv test  ./myFirstPkgl/... ./mySecondPkg/...
cannot use -c flag with multiple packages
```

note that :

``` dlv test  ./myFirstPkg/... ``` (1one pkg) works fine
```
(dlv) continue
TestPrintVersion
--- FAIL: TestPrintVersion (0.00s)
TestFoo
FAIL
Process 3383 h

```

I'm using one of the latest version 

```
 dlv version
Delve Debugger
Version: 1.2.0
Build: $Id: 068e2451004e95d0b042e5257e34f0f08ce01466 $
```

thank you for your help

**Comment by aarzilli** [comment]
`go test` with multiple packages will build and run each package individually, delve needs a single executable to work. Supporting this poses numerous problems and isn't really worth the effort.

**Comment by MalloZup** [comment]
@aarzilli thx for answer. I understand your pov in that sense. :+1:

**Comment by demeralde** [comment]
Having to run `dlv test` for each individual package, instead of being able to run it for the entire project (e.g like `go test ./...`) is a huge PITA.

It makes debugging with `dlv` more of a hassle than just using print statements.
