### ISSUE TITLE
[Question] : Debugging delve

### ISSUE THREAD

**Issue by AndreyZWorkAccount** [go-delve/delve#1547]
Hi guys,

I've built delve locally and now I'm using it with "vscode-go" plugin.
So delve is running as a separate process ( Windows ).
I want to debug delve for learning purposes, but I can't attach to it from VS Code ( looks like it's attached, but no breakpoints are active and I even can't pause the delve process ).
Are there best practices to debug delve?

P.s.: thank you very much for the amazing project.

**Comment by aarzilli** [comment]
I've never tried debugging delve with delve on windows, it's possible that there's some reason why it doesn't work on that platform, but it's also possible that it's a problem with VSCode, I'd suggest trying it with just the command line. Also debugging a test (for example one in proc_test.go) is also more useful than debugging the whole thing.

**Comment by AndreyZWorkAccount** [comment]
@aarzilli , Did you do source-level debugging of Delve on Linux platform? If so, what tools did you use?

**Comment by aarzilli** [comment]
Typically gdlv.

**Comment by AndreyZWorkAccount** [comment]
@aarzilli Wow! It looks like a tool that I must try. Thank you!

**Comment by dlsniper** [comment]
For the record, I debug delve using delve (via GoLand) on Windows and it works for me. Like a config issue like @aarzilli mentioned.
