### ISSUE TITLE
no source available

### ISSUE THREAD

**Issue by msaf1980** [go-delve/delve#1550]
I can't list sources of program in Delve (gdb work fine)
Breakpoints also no work.
But I can see source files with `sources` command

1. `$ dlv version`
Delve Debugger
Version: 1.1.0
Build: $Id: 1990ba12450cab9425a2ae62e6ab988725023d5c

2. `$ go version`
go version go1.10.4 linux/amd64

3. What operating system and processor architecture are you using?
    Fedora Linux 28 (Kernel 4.18.12-200.fc28.x86_64)

Delve session

`$ dlv exec ./aliasByTags`
Type 'help' for list of commands.
`(dlv) b main.main`
Breakpoint 1 set at 0xa187bb for main.main() ./main.go:7
`(dlv) list`
Stopped at: 0x7f9eab8d7f60
=>no source available
`(dlv) r`
Process restarted with PID 8001
`(dlv) bt`
0  0x00007f82b7d39f60 in ???
   at ?:-1
   error: input/output error
(truncated)

But sources are shown
`(dlv) sources`
/home/msaf1980/go/src/github.com/bookingcom/carbonapi/expr/helper/helper.go
/home/msaf1980/go/src/github.com/bookingcom/carbonapi/expr/helper/sort.go
..
/home/msaf1980/go/src/github.com/msaf1980/aliasByTags/main.go
..
`(dlv) c`
Process 9720 has exited with status 0

All worked in GDB session

`$ gdb ./aliasByTags`
GNU gdb (GDB) Fedora 8.1.1-3.fc28
Loading Go Runtime support.
`(gdb) b main.main`
Breakpoint 1 at 0xa187a0: file /home/msaf1980/go/src/github.com/msaf1980/aliasByTags/main.go, line 7.
`(gdb) r`
Starting program: /home/msaf1980/go/src/github.com/msaf1980/aliasByTags/aliasByTags 
Thread 1 "aliasByTags" hit Breakpoint 1, main.main () at /home/msaf1980/go/src/github.com/msaf1980/aliasByTags/main.go:7
7	func main() {
`(gdb) bt`
#0  main.main () at /home/safronov/go/src/github.com/msaf1980/aliasByTags/main.go:7
`(gdb) c`
Continuing.
[Inferior 1 (process 12094) exited normally]

**Comment by aarzilli** [comment]
You should try doing the same thing you are doing with gdb, set a breakpoint and `continue`.

**Comment by msaf1980** [comment]
I'll do it. All work in GDB, but not
GDB                 Status in GDB                   Delve                 status in Delve
'b main.main'    OK                                    'b main.main'      OK
list                     OK                                    list                      FAIL (no source available)
run                    OK (stop on breakpoint)   run                      FAIL (not stopped on breakpoint)
bt                      OK                                    bt                        FAIL (can't extract locations in code)
continue            OK                                    continue             OK

**Comment by aarzilli** [comment]
```
$ dlv debug temp/hello.go 
Type 'help' for list of commands.
(dlv) b main.main
Breakpoint 1 set at 0x45923f for main.main() ./temp/hello.go:3
(dlv) c
> main.main() ./temp/hello.go:3 (hits goroutine(1):1 total:1) (PC: 0x45923f)
     1:	package main
     2:	
=>   3:	func main() {
     4:		println("hello world")
     5:	}
(dlv) list
> main.main() ./temp/hello.go:3 (hits goroutine(1):1 total:1) (PC: 0x45923f)
     1:	package main
     2:	
=>   3:	func main() {
     4:		println("hello world")
     5:	}
(dlv) 
```

**Comment by msaf1980** [comment]
With continue all work.

**Comment by liza-yemini** [comment]
@msaf1980 
I might not have explained the issue clearly before. The problem is that Delve never hits any breakpoints in my Go projects. When I start a debugging session in GoLand, the breakpoints turn into empty circles with a slash, and I see this error:
`protocol error E09 during set breakpoint for packet $Z0,7ff800e4a7e0,4
`

I also noticed an initial warning message: “While Delve 1.23.0 might not fully support Go 1.22.6...”.

I’ve updated both GoLand and Delve, tried different projects, and followed related issues, but the problem persists across all services. Any guidance would be greatly appreciated.
