### ISSUE TITLE
Feature: Add reload command to refresh code being debugged

### ISSUE THREAD

**Issue by jseutter** [go-delve/delve#1551]
1. What version of Delve are you using (`dlv version`)? 1.2.0
2. What version of Go are you using? (`go version`)? 1.12.1 darwin/amd64
3. What operating system and processor architecture are you using? OS x/intel
4. What did you do? I ran delve to debug an issue and set some breakpoints, found the issue and updated my source code.  Afterwards, in the same delve instance, I issued a restart command
5. What did you expect to see? N/A
6. What did you see instead? new source files and old code running.

The current behavior is similar to how gdb works.  After you edit the code, gdb will show the new source files but run old code.  This can be handy if you want to avoid recompiling because your disk is excessively slow.

However, in gdb you can issue a ```file "executable.exe"``` command.  At this point it reloads the executable from disk and you now have updated machine code.  You can issue a ```restart``` and verify the changes you made are working as expected, with your existing breakpoints and traces still in place.

The ```file``` command wouldn't make sense for delve because of delves ability to run the code without an executable file on disk.  How about adding a ```reload``` command that triggers delve to read sources from disk and recompile?  Is this sort of thing possible? hard? easy? foolhardy?

**Comment by rabble** [comment]
How do you force it to reload in the current setup?

**Comment by JAicewizard** [comment]
This would be really nice.
Breakpoints should all be reloaded to make sure that they are all set properly.

**Comment by dongwangdw** [comment]
Yes, I wonder if there any one to reload methods to workaround this currently.
