### ISSUE TITLE
how to use delve if my program has conditional compilation options

### ISSUE THREAD

**Issue by fullstackYou** [go-delve/delve#1552]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
latest
2. What version of Go are you using? (`go version`)?
1.12.4
3. What operating system and processor architecture are you using?
mac
4. What did you do?
go build main.go -tags linux
5. What did you expect to see?
I can debug by using delve
6. What did you see instead?
Warning: debugging optimized function
        runtime.curg._panic.arg: interface {}(string) "Please add build tags to run this program"

**Comment by aarzilli** [comment]
Use `--build-flags`.
