### ISSUE TITLE
Need help to port delve for AARCH64

### ISSUE THREAD

**Issue by floodcaptain** [go-delve/delve#1558]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)? `v1.2.0`
2. What version of Go are you using? (`go version`)? `go1.12.4 linux/arm64`
3. What operating system and processor architecture are you using? `GOOS=linux  GOARCH=arm64`
4. What did you do?
I am interested in regenerating files for my native environment (arm64 with linux), located at :
> vendor/golang.org/x/sys/unix/

I looked at the file mkall.sh that generates files for Architecture/OS combination .
> vendor/golang.org/x/sys/unix/mkall.sh

line 51 in file mkall.sh, requires a dockerfile present at ${GOOS}/Dockerfile but i can't locate it anywhere in the source .

`line 51:  $cmd docker build --tag generate:$GOOS $GOOS`

please suggest how can i get this dockerfile .

error in running the script is as follows:
`unable to prepare context: path "linux" not found`
`Unable to find image 'generate:linux' locally`for Architecture/OS combination .

5. What did you expect to see?
I expected to find a dockerfile present in   $GOOS or atleast anywhere in the repository .

6. What did you see instead?
`unable to prepare context: path "linux" not found`
`Unable to find image 'generate:linux' locally`

**Comment by aarzilli** [comment]
The 'linux' directory doesn't get vendored because it doesn't contain any go code. The [original repository](https://go.googlesource.com/sys/+/refs/heads/master/unix/linux/) contains linux and the dockerfile you are looking for. That's also the correct place to make changes to x/sys/unix, we won't merge direct changes to vendored code.

**Comment by derekparker** [comment]
Closing this as the work must be done upstream and then re-vendored.
