### ISSUE TITLE
Debugging process hung

### ISSUE THREAD

**Issue by korvinko** [go-delve/delve#1560]
Debugging process hung and it does not actually start my application. I can only see the following log and nothing more:
API server listening at: [::]:40000
2019-05-29T10:56:01+03:00 info layer=debugger launching process with args: [./main]

I tried to start the debug process from the docker container and on the host. I saw the same result in both cases.
CMD ["dlv", "exec", "--listen=:40000", "--headless=true", "--api-version=2", "--log", "./main"]

But follow command works well
CMD [""./main"]

1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.2.0
Build: $Id: 068e2451004e95d0b042e5257e34f0f08ce01466

2. What version of Go are you using? (`go version`)?
Host: go version go1.12 (build binary here)
Container: go version go1.12.5 linux/amd64

3. What operating system and processor architecture are you using?
Docker container golang:alpine:latest
Host: Ubuntu Bionic. 
uname -a: Linux ws-064-22a 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

4. What did you do?
Tried to start the process in docker CMD:
CMD ["dlv", "exec", "--listen=:40000", "--headless=true", "--api-version=2", "--log", "./main"]

5. What did you expect to see?
API server listening at: [::]:40000 with my application logs and working http endpoints  

6. What did you see instead?
API server listening at: [::]:40000
2019-05-29T10:56:01+03:00 info layer=debugger launching process with args: [./main]
My application did not start

**Comment by derekparker** [comment]
This is not a bug, but a feature request. We don't have a really great way of continuing a process automatically upon connect. There are a few ways to work around it. This is pretty low hanging fruit I think and I might be able to get to it pretty soon.

cc @aarzilli on this, I know you did some work related to this, but IIRC we still have to have a client connect and send `exit -c` as an init script for the workaround, correct?

**Comment by aarzilli** [comment]
This feature has been requested a few times but I'm not sure that this specific issue is a feature request but rather confusion at the behavior of delve. Maybe we should start writing a FAQ.

**Comment by aarzilli** [comment]
> but IIRC we still have to have a client connect and send exit -c as an init script for the workaround, correct?

yes.
