### ISSUE TITLE
allow setting breakpoint at non-instruction line

### ISSUE THREAD

**Issue by rogpeppe** [go-delve/delve#1566]
```
% dlv version
Delve Debugger
Version: 1.2.0
Build: $Id: 068e2451004e95d0b042e5257e34f0f08ce01466 $

% go version
go version devel +e883d000f4 Wed May 29 13:27:00 2019 +0000 linux/amd64

% uname -a
Linux snazzy 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```

With this program in `tst.go`:
```
package main

import "fmt"

func main() {
	fmt.Println("hello, world")

	for i := 0; i < 10; i++ {
		fmt.Println(i)
	}
}
```

I did this:
```
% dlv debug tst.go
Type 'help' for list of commands.
(dlv) break tst.go:7
Command failed: could not find /home/rog/src/s/tst.go:7
```

Line 7 is the empty line just before the for loop.

Instead of failing in this case, it would be more helpful to set the breakpoint at the next available break point location (it could print the actual line that was chosen), or at least provide a more helpful error message that indicates the next line that can be used for a breakpoint.

**Comment by derekparker** [comment]
With tip the error message is improved via: https://github.com/go-delve/delve/pull/1556
