### ISSUE TITLE
pkg/proc: panic on call to Ancestors

### ISSUE THREAD

**Issue by rogpeppe** [go-delve/delve#1568]
I ran [this program](https://play.golang.org/p/pavMaGOV153) under [gdlv](https://github.com/aarzilli/gdlv), set a breakpoint for line 22 (`Println("hi")`) and let it run. I see the following stack trace (apologies for the screenshot but the text isn't selectable):

![image](https://user-images.githubusercontent.com/66491/58716722-8d0ee080-83c1-11e9-9079-7879bd99c588.png)

I'm running with Go tip:

    go version devel +e883d000f4 Wed May 29 13:27:00 2019 +0000 linux/amd64

I'm using commit 7c18354c1c304277a2150c74a50f0acf5ce0a79e of delve and I'm using Go modules.

For the record, the line that it panics on is the first line of the `G.Ancestors` method:

     scope := globalScope(g.Thread.BinInfo(), g.Thread.BinInfo().Images[0], g.Thread)

**Comment by derekparker** [comment]
Can you reproduce this without gdlv using just the CLI?

**Comment by rogpeppe** [comment]
No, but I'm not familiar enough with delve to know what a command line
equivalent of the Ancestors RPC might be.
