### ISSUE TITLE
Delve fails when encountering unterminated CUs

### ISSUE THREAD

**Issue by heschik** [go-delve/delve#1579]
We just upgraded Delve ([commits](https://github.com/go-delve/delve/compare/520d7924...72fae3c9)) and got a failure report. Our copy of libc has an object file with an incomplete CU -- it lacks a terminating 0 abbrev. After one of the changes in that range, probably #1565, Delve runs off the end of the CU, proceeds to the next, and then crashes looking at the wrong CU's file table.

I'm not sure if this is a bug in our libc or what, but either way it's also a regression in Delve from our perspective. Let me know if you need more information and I can try to get it for you.

```
$ readelf --debug-dump=info [redacted]/lib64/crt1.o                
Contents of the .debug_info section:

  Compilation Unit @ offset 0x0:
   Length:        0x63 (32-bit)
   Version:       2
   Abbrev Offset: 0x0
   Pointer Size:  8
 <0><b>: Abbrev Number: 1 (DW_TAG_compile_unit)
    <c>   DW_AT_stmt_list   : 0x0
    <10>   DW_AT_low_pc      : 0x0
    <18>   DW_AT_high_pc     : 0x2a
    <20>   DW_AT_name        : ../sysdeps/x86_64/start.S
    <3a>   DW_AT_comp_dir    : [redacted]
    <59>   DW_AT_producer    : GNU AS 2.24
    <65>   DW_AT_language    : 32769	(MIPS assembler)
  Compilation Unit @ offset 0x67:
   Length:        0x7a (32-bit)
   Version:       4
   Abbrev Offset: 0x14
   Pointer Size:  8
[snip]
```

cc @hyangah

**Comment by aarzilli** [comment]
I think this is a duplicate of #1572 and #1574 should fix it.

**Comment by heschik** [comment]
Yep, tested the patch and looks good. Sorry for the dupe.
