### ISSUE TITLE
Can't install on windows

### ISSUE THREAD

**Issue by jndz2** [go-delve/delve#1580]
`go get -u github.com/go-delve/delve/cmd/dlv
 \# bytes
C:\Go\src\bytes\bytes_decl.go:10:6: IndexByte redeclared in this block
        previous declaration at C:\Go\src\bytes\bytes.go:101:34
C:\Go\src\bytes\bytes_decl.go:17:6: Equal redeclared in this block
        previous declaration at C:\Go\src\bytes\bytes.go:18:25
C:\Go\src\bytes\bytes_decl.go:24:6: Compare redeclared in this block
        previous declaration at C:\Go\src\bytes\bytes.go:37:27
\# crypto/rc4
C:\Go\src\crypto\rc4\rc4_asm.go:15:18: (*Cipher).XORKeyStream redeclared in this block
        previous declaration at C:\Go\src\crypto\rc4\rc4.go:61:6
\# crypto/cipher
C:\Go\src\crypto\cipher\xor_amd64.go:9:6: xorBytes redeclared in this block
        previous declaration at C:\Go\src\crypto\cipher\xor.go:58:33
C:\Go\src\crypto\cipher\xor_amd64.go:22:6: xorWords redeclared in this block
        previous declaration at C:\Go\src\crypto\cipher\xor.go:83:27
\# strings
C:\Go\src\strings\strings_decl.go:8:6: IndexByte redeclared in this block
        previous declaration at C:\Go\src\strings\strings.go:150:34`

1. What version of Delve are you using (`dlv version`)?
latest

2. What version of Go are you using? (`go version`)?
go version go1.12.5 windows/amd64

3. What operating system and processor architecture are you using?
Windows 10 & Intel

4. What did you do?
go get -u github.com/go-delve/delve/cmd/dlv

5. What did you expect to see?
that it has been installed

6. What did you see instead?
Error in console

**Comment by dlsniper** [comment]
It looks like your Go installation is broken, perhaps your GOROOT and GOPATH are mixed up, and the GOPATH contains the Go SDK, or the GOPATH points Go SDK (Go SDK is the GOROOT).
Run `go env` and make sure that `GOROOT` points where Go itself is installed, and that `GOPATH` is a totally different directory than the `GOROOT` one.

**Comment by jndz2** [comment]
> It looks like your Go installation is broken, perhaps your GOROOT and GOPATH are mixed up, and the GOPATH contains the Go SDK, or the GOPATH points Go SDK (Go SDK is the GOROOT).
> Run `go env` and make sure that `GOROOT` points where Go itself is installed, and that `GOPATH` is a totally different directory than the `GOROOT` one.

Yes, my installation was broken. I reinstalled it and now it loads without problems.
