### ISSUE TITLE
Can't debug TinyGo: 'panic: interface conversion: interface {} is int64, not dwarf.Offset'

### ISSUE THREAD

**Issue by justinclift** [go-delve/delve#1581]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

### What version of Delve are you using (`dlv version`)?

The problem occurs with the version of Delve included in GoLand 2019.1.3 (and the upcoming GoLand 2019.2 EAP):

```
$ ./dlv version
Delve Debugger
Version: 1.2.0
Build: c30a333f7be2f4ca636a93cd198b1762c5615513
```

It does **not** occur with the version of Delve included in GoLand 2018.3.6:

```
$ ./dlv version
Delve Debugger
Version: 1.1.0
Build: $Id$
```

Copying the `dlv` binary from the (working) 2018.3.6 installation to the (non-working) 2019.2 EAP **does** then allow the 2019.2 EAP to work.

### What version of Go are you using? (`go version`)?

```
$ go version
go version go1.12.5 linux/amd64
```

### What operating system and processor architecture are you using?

CentOS 7 x64 (Linux)

### What did you do?

Attempting to start a debug session from GoLand, specifically on the [TinyGo project source](https://github.com/tinygo-org/tinygo).

This problem doesn't seem to occur with any other project.  Yes, this is weird. :wink:

### What did you expect to see?

The debug session to start as per normal, and execution breaking on any of the defined breakpoints.

### What did you see instead?

The debug session wasn't able to start, instead it fails with:

```
panic: interface conversion: interface {} is int64, not dwarf.Offset

goroutine 131 [running]:
github.com/go-delve/delve/pkg/proc.(*BinaryInfo).loadDebugInfoMaps(0xc0001a2300, 0xc0000de790, 0xc00573c000, 0xae85, 0xae85, 0xc004604030, 0x0)
	/opt/buildAgent/work/4c3e5e3eabfaf2d2/pkg/proc/types.go:275 +0x3f37
created by github.com/go-delve/delve/pkg/proc.loadBinaryInfoElf
	/opt/buildAgent/work/4c3e5e3eabfaf2d2/pkg/proc/bininfo.go:860 +0x38a
```

**Comment by justinclift** [comment]
Oops, pressed enter too early, still filling this in...

**Comment by justinclift** [comment]
Manually running the same commands from the same working directory compiles the program without issue, and starts Delve in headless mode as expected without any error being shown.

**Comment by justinclift** [comment]
Connecting to the manually started Delve server works, but attempting to run the executable after setting a break point fails:

```
$ /home/jc/GoLand-192.4787.18/plugins/go/lib/dlv/linux/dlv connect 127.0.0.1:34686
Type 'help' for list of commands.
(dlv) b foo main.go:572
Breakpoint foo set at 0xab531b for main.main() ./main.go:572
(dlv) c
Command failed: unexpected EOF
(dlv) bp
Command failed: connection is shut down
(dlv)
```

In the terminal session where `dlv` was executed, the error appeared when the `c` command ran:

```
$ /home/jc/GoLand-192.4787.18/plugins/go/lib/dlv/linux/dlv --listen=localhost:34686 --headless=true --api-version=2 exec /tmp/___tinygo_main_wasm -- build -o src/examples/wasm/main/wasm.wasm -target wasm -gc dumb -wasm-abi js src/examples/wasm/main/main.go #gosetup
API server listening at: 127.0.0.1:34686
panic: interface conversion: interface {} is int64, not dwarf.Offset

goroutine 27 [running]:
github.com/go-delve/delve/pkg/proc.(*BinaryInfo).loadDebugInfoMaps(0xc00019c180, 0xc0028ac160, 0xc005a1c000, 0xae85, 0xae85, 0xc0050c4020, 0x0)
        /opt/buildAgent/work/4c3e5e3eabfaf2d2/pkg/proc/types.go:275 +0x3f37
created by github.com/go-delve/delve/pkg/proc.loadBinaryInfoElf
        /opt/buildAgent/work/4c3e5e3eabfaf2d2/pkg/proc/bininfo.go:860 +0x38a
```

Anyone have ideas on how to investigate?

**Comment by aarzilli** [comment]
Can you copy the tinygo executable somewhere?

**Comment by justinclift** [comment]
Yep.  It's here now (bzipped):

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/other/___tinygo_main_wasm.bz2

**Comment by justinclift** [comment]
Hmmm, ignore this.  Should be able to dig into this, and figure out what's going wrong myself.

I'll re-open or create a PR as necessary, at that point. :smile:

**Comment by aarzilli** [comment]
I've taken a look to the file you posted but I can't reproduce the problem and it doesn't contain any DW_TAG_imported_units so I don't see how it could happen.

**Comment by justinclift** [comment]
No worries.  Suspiciously, it started happening after I started learning how to run Delve in a headless debug session.

Kind of thinking there might be some left over config file or something hanging around, which is causing something to go wrong.  I'll investigate it properly at a later point. :smile:
