### ISSUE TITLE
Could delve inspect goroutine stack frame layout?

### ISSUE THREAD

**Issue by runningbar** [go-delve/delve#1584]
I want to list golang stack frame memory layout for diving into golang runtime。and noticed that gdb can inspect memory layout.

I list all delve commands with `help`, and test them one by one, but failed to find which I want.

can delve do it? or any plan about this? 

thank you

**Comment by aarzilli** [comment]
What do you mean "inspect memory layout"? gdb's `x` command?

**Comment by runningbar** [comment]
> What do you mean "inspect memory layout"? gdb's `x` command?

yes, like `x` command print values in specific memory address range

**Comment by aarzilli** [comment]
Not exactly, but you can cast arbitrary addresses to [N]byte.

**Comment by derekparker** [comment]
Adding enhancement / discussion labels because it could be nice to improve how we enable the user to dive into memory.
