### ISSUE TITLE
Add ability for more advanced UI like gdb

### ISSUE THREAD

**Issue by RobinBaeckman** [go-delve/delve#1586]
It would be nice to have more information available like https://github.com/cyrus-and/gdb-dashboard. In gdb a file .gdbinit is read from the home dir is this something that we could use too?

I would be up for working on this issue.

**Comment by aarzilli** [comment]
This can be implemented using the [API](https://github.com/go-delve/delve/blob/master/Documentation/api/ClientHowto.md), there are some [alternative UIs](https://github.com/go-delve/delve/blob/master/Documentation/EditorIntegration.md) although none of them are TUI. I think implementing one is beyond the scope of this project.

**Comment by derekparker** [comment]
I agree, I think this is outside the scope of this project and should be maintained separately. If you would like to build something like this we absolutely encourage it!
