### ISSUE TITLE
Unable call optimized functions

### ISSUE THREAD

**Issue by dlsniper** [go-delve/delve#1589]
For this issue, I'm using the following repository: https://github.com/dlsniper/debugging/tree/0cf1692cb8518c1ec982c72d71064ffba1d0ed1c
My apologies for not being able to further narrow it down.

1. What version of Delve are you using (`dlv version`)?
local:
remote:

2. What version of Go are you using? (`go version`)?
Go 1.12.6
3. What operating system and processor architecture are you using?
Alpine 3.10 and Debian Stretch

4. What did you do?
- run the container
- connect a delve instance to it
- run the following commands:
```
b main.go:55
c
```
- make an http request on ` curl http://127.0.0.1:8080/fact `
- when the debugger stops, run the following command ` call strconv.ParseInt("123", 10, 64) `

5. What did you expect to see?
I expected to see the result of the function call.

6. What did you see instead?
The following error message;
```
could not get argument location of i: could not find loclist entry at 0x[...] for address 0x[...]
```

As this happens with both Alpine and Debian containers, I believe it's not an OS problem.
Also, this works when running from the Windows host (in my case I'm running Windows 10).

**Comment by aarzilli** [comment]
How did you compile the program that you are debugging? This is probably because the strconv package is optimized.

**Comment by dlsniper** [comment]
You are right, I forgot to add the `-gcflags="all=-N -l". Sorry for being silly. Should we keep this open still for the optimized part?

**Comment by aarzilli** [comment]
yes.
