### ISSUE TITLE
Graceful detach with kill=false

### ISSUE THREAD

**Issue by nd** [go-delve/delve#1607]
[Documentation](https://github.com/go-delve/delve/blob/master/Documentation/api/ClientHowto.md#gracefully-ending-the-debug-session) states that in order to end debug session gracefully a client has to `halt` first. It seems like there is no way to shutdown gracefully without killing a process: it is expected that the process will continue running, but if the client `halt` before `detach`, the process will stay halted.

**Comment by derekparker** [comment]
The the process should continue after the debugger issues the detach command. Do you have more information on the environment you are using and experiencing this problem in?

**Comment by nd** [comment]
I've seen it a few times on mac. I attached to a go process from GoLand and then stopped the debug session. In this scenario GoLand sends `detach` with kill=false and the process under debug was behaving as if it was halted. 

Do I understand correctly that this logic of continue after detach is implemented inside debugserver? GoLand kills a whole process tree when debug session ends. Maybe it killed the debugserver before it had a chance to resume the process under debug.

**Comment by derekparker** [comment]
@nd are you able to reproduce this outside of GoLand just with the CLI?

**Comment by nd** [comment]
I cannot reproduce it without GoLand so far. Most likely it was caused by GoLand. Sorry for the noise.

> Do I understand correctly that this logic of continue after detach is implemented inside debugserver? 

Could you please confirm/comment on that?

**Comment by derekparker** [comment]
@nd the logic of continue after detach is implemented by the various kernels. For example, on unix systems `PtraceDetach` is supposed to continue the process.

Going to close this out as it doesn't seem to be our bug.

**Comment by aarzilli** [comment]
> Do I understand correctly that this logic of continue after detach is implemented inside debugserver?

On macOS with the default backend detach calls `debugger.(*Debugger).Detach` in debugger.go, which calls `gdbserver.(*Process).Detach` which if the process didn't exit (!p.exited) and kill == false calls `gdbserver.(*gdbConn).detach`, which sends the `D` packet to debugserver.

This packet is documented [here](https://sourceware.org/gdb/onlinedocs/gdb/Packets.html#Packets):

> The first form of the packet is used to detach GDB from the remote system. It is sent to the remote target before GDB disconnects via the detach command.
