### ISSUE TITLE
Sometimes delve doesn't responds to a halt command

### ISSUE THREAD

**Issue by nd** [go-delve/delve#1608]
1. What version of Delve are you using (`dlv version`)?

```
Delve Debugger
Version: 1.2.0
Build: dd4fd5dc9cf5d45092f97f2ba376f3e69d7a5a8e
```

2. What version of Go are you using? (`go version`)?

```
go version go1.12.6 darwin/amd64
```

3. What operating system and processor architecture are you using?

Mac OS 10.12.5

4. What did you do?

Debug the following program

```
package main

import "time"

func main() {
	x := 1 //break
	_ = x
	for {
		time.Sleep(10 * time.Second)
	}
}
```

Once debugger reaches the breakpoint, `continue` and then `halt` immediately.

5. What did you expect to see?

Debugger halts the program and responds to the `halt` request.

6. What did you see instead?

Sometimes delve doesn't responds to the `halt` request. 

The scenario is a part of an automatic test. If I insert a 1 second delay between continue and halt, debugger handles the halt command as expected. It also works as expected without a delay on linux.

Log (rpc,gdbwire) without delay: https://gist.github.com/nd/e5ec2d8ab9143ad371719a415dc36087. Test stops in 10 seconds if it didn't get a response, but delve doesn't responds with a longer timeout as well: https://gist.github.com/nd/ee91ca2cf59adf725932a10d95bbc8c7.

It seems like when continue and halt are really close, delve responds to the halt command without actually halting the program: https://gist.github.com/nd/e8fbace9e291703be0c246b948207a08.

Delve works as expected with 1 second delay before halt: https://gist.github.com/nd/eaee4ab76b15890bdf0cf9d03b958bb3

**Comment by aarzilli** [comment]
The problem is that Command requests that are received simultaneously can be executed out of order. See serveJSONCodec in service/rpccommon/server.go, specifically around line :339.
