### ISSUE TITLE
Debug hangs during evaluation get from a long map

### ISSUE THREAD

**Issue by nd** [go-delve/delve#1609]
Delve doesn't respond to halt command

1. What version of Delve are you using (`dlv version`)?

```
Delve Debugger
Version: 1.2.0
Build: dd4fd5dc9cf5d45092f97f2ba376f3e69d7a5a8e
```

2. What version of Go are you using? (`go version`)?

```
go version go1.12.6 darwin/amd64
```

3. What operating system and processor architecture are you using?

Mac OS 10.12.5

4. What did you do?

Debug the [client test scenario](https://github.com/aarzilli/delve_client_testing/blob/master/12to18vars/main.go) where `runtime.Breakpoint` is replaced with breakpoint added via api.

Once debugger reached the breakpoint, evaluate `"longmap[\"iteration 2\"].value"`.

5. What did you expect to see?

Debugger returns `"3"`.

6. What did you see instead?

Debugger hangs on mac os: https://gist.github.com/nd/42b75f4ded8fd6398b06b07315d1d1bf.

Works fine on linux.

**Comment by aarzilli** [comment]
Are you sure that it hangs instead of simply taking a long time? Is that the full log or is it truncated (it's 8849 lines, a suspicious number of lines).

**Comment by nd** [comment]
The log is truncated. Will check if it ever completes. But it works instantly on linux, that's why I thought the command is hanging.

**Comment by nd** [comment]
It is indeed not hanging, delve responds in 2 minutes: https://gist.github.com/nd/4137b4ffb6595701a94c991b22e183ea. I wonder why is such a difference in performance on mac and linux?

**Comment by aarzilli** [comment]
Map access (in delve) is done with a linear scan, we've never measured the actual read speed difference between native/linux and gdbserial/osx (not that we could do much about it anyway).

**Comment by aarzilli** [comment]
PS. if you are using different versions of go on linux and macos it could also be that the map randomization changed and it's farther away on macos.

**Comment by nd** [comment]
I was wrong. It is not instant on linux as well: takes ~25 seconds on my machine.
