### ISSUE TITLE
A redundant breakpoint hit

### ISSUE THREAD

**Issue by nd** [go-delve/delve#1610]
1. What version of Delve are you using (`dlv version`)?

```
Delve Debugger
Version: 1.2.0
Build: dd4fd5dc9cf5d45092f97f2ba376f3e69d7a5a8e
```

2. What version of Go are you using? (`go version`)?

```
go version go1.12.6 darwin/amd64
```

3. What operating system and processor architecture are you using?

Mac OS 10.12.5

4. What did you do?

Debug the following program on mac in a delve with tty enabled:

```
package main

func main() {
	println("test") //break
}
```

5. What did you expect to see?

Execution stops at the breakpoint once, after continue program exits.

6. What did you see instead?

Execution stops at the breakpoint twice.

It doesn't always happend. Here are logs (prc,gdbwire) when the breakpoint reached once: https://gist.github.com/nd/96eb43768cd7327b99ccfe1e7b6acb44, and twice: https://gist.github.com/nd/6106f0234fb94b0f62f65c9a7d2305ff. On linux the breakpoint is hit only once.

**Comment by quoctruong** [comment]
I can also repro this problem on my Windows machine.
