### ISSUE TITLE
panic: interface conversion: interface {} is nil, not dwarf.Offset

### ISSUE THREAD

**Issue by feodor-shi** [go-delve/delve#1614]
I've found a [similar issue](https://github.com/go-delve/delve/issues/1581) but there is no helpful information. Also, in my case, it crashes from an IDEA and terminal.

1. What version of Delve are you using (`dlv version`)?

```
Delve Debugger
Version: 1.2.0
Build: $Id: 068e2451004e95d0b042e5257e34f0f08ce01466 $
```

2. What version of Go are you using? (`go version`)?

`go version go1.12.5 linux/amd64`

3. What operating system and processor architecture are you using?

`debian:stretch-slim GOARCH=amd64`

4. What did you do?

[Debugging containerized Go applications](https://blog.jetbrains.com/go/2018/04/30/debugging-containerized-go-applications/).

`CMD ["/dlv", "--listen=:40000", "--headless=true", "--api-version=2", "exec", "/service"]`

5. What did you expect to see?
```

API server listening at: [::]:40000
...
```

6. What did you see instead?

```
API server listening at: [::]:40000
panic: interface conversion: interface {} is nil, not dwarf.Offset

goroutine 5 [running]:
github.com/go-delve/delve/pkg/proc.(*BinaryInfo).loadDebugInfoMaps(0xc000190680, 0xc001122000, 0x203ab1, 0x203ab1, 0xc000148240, 0x0)
        /root/go/pkg/mod/github.com/go-delve/delve@v1.2.0/pkg/proc/types.go:444 +0x3bee
created by github.com/go-delve/delve/pkg/proc.(*BinaryInfo).LoadBinaryInfoElf
        /root/go/pkg/mod/github.com/go-delve/delve@v1.2.0/pkg/proc/bininfo.go:704 +0x34d
```

**UPDATE 1**

when I switched the building approach from

`go get -u github.com/go-delve/delve/cmd/dlv`

to

```
$ git clone https://github.com/go-delve/delve.git $GOPATH/src/github.com/go-delve/delve
$ cd $GOPATH/src/github.com/go-delve/delve
$ make install
```

it works

**Comment by aarzilli** [comment]
There was a bug in 1.2.0 that can conceivably cause this but it has already been fixed in master, which is probably why `git clone` solves the problem.
