### ISSUE TITLE
Add print depth options for dereferense pointers and etc

### ISSUE THREAD

**Issue by msaf1980** [go-delve/delve#1625]
Can you add option for print depth of pointers, nested structs and etc ?
May be use existing MaxVariableRecurse or other options.

**Comment by derekparker** [comment]
Not sure what you mean here, you simply want an option to print the number which represents the depth of nesting or pointer derefs?

**Comment by msaf1980** [comment]
This is a option for evaluation depth of nested struct members, array items, dereference pointers, etc
when traversing into them.
By default its a 1 - so no traverse into. If I need a print value of nested element. I'll need print a casted memory addres. It's not a simple. With this parameter it's more easy.
I think, this will be useful for cli debugging.

**Comment by aarzilli** [comment]
Implemented by 89d2167c31e57c83b716a0b772b1465df6b0b4c4
