### ISSUE TITLE
dlv returns "" for strings that are both empty and (NULL, 0)

### ISSUE THREAD

**Issue by robbmanes** [go-delve/delve#1630]
During a debugging session of a docker crash which ended up being resolved by https://github.com/moby/moby/pull/33832/commits/917050c5728f2fb9958ccb3ab66a23766f741adc a nil pointer string went undetected because of unexpected output.

The issue in a nutshell was that msg.Source caused a pointer dereference that caused a panic, here:

```
(dlv) frame 6
> runtime.raise() /opt/rh/go-toolset-1.10/root/usr/lib/go-toolset-1.10-golang/src/runtime/sys_linux_amd64.s:159 (PC: 0x46f2c4)
Warning: debugging optimized function
Frame 6: /usr/src/debug/docker-b2f74b220126bddbae585cfe2406498ced3ae065/_build/src/github.com/docker/docker/daemon/logger/journald/journald.go:113 (PC: 11a2b2a)
   108:		}
   109:	
   110:		line := string(msg.Line)
   111:		logger.PutMessage(msg)
   112:	
=> 113:		if msg.Source == "stderr" {
   114:			return journal.Send(line, journal.PriErr, vars)
   115:		}
   116:		return journal.Send(line, journal.PriInfo, vars)
   117:	}
   118:	
```

However, when we just `p msg.Source`, we get the same output for an empty string as we do for something with an invalid pointer:

```
(dlv) p msg.Source
""
```

After some deeper investigation we found, since a string is `(char *ptr, size_t len)`, that this particular `msg.Source` was `(NULL, 0)`, as the length was `0` and the pointer was missing, hence the invalid dereference.

It would be particularly nice if the print of the string showed the pointer was invalid, instead of an empty string; some sort of detection if a string is nil.  I'm not sure what would be best here, but thought I would bring it up.

1. What version of Delve are you using (`dlv version`)?
```
dlv version
Delve Debugger
Version: 1.2.0
Build: cb658772972d74042ba75f006ac14023e552c7cd
```

2. What version of Go are you using? (`go version`)?
```
$ go version
go version go1.12.7 linux/amd64
```

3. What operating system and processor architecture are you using?
Fedora 30 - 5.1.16-300.fc30.x86_64 

4. What did you do?
Printed a string with a nil pointer.

5. What did you expect to see?
Possibly have seen that the pointer was missing from the output.

6. What did you see instead?
Got empty string syntax returned.

I am not familiar with the dlv project, but will see if I can figure out where this logic is on my own.  This isn't particularly pressing (you can just read the pointer manually when you realize that nothing in the output would cause an invalid dereference) but detection of this would be nice.

**Comment by aarzilli** [comment]
`{ nil, 0 }` is the normaly way empty strings are represented in go. It's possible to coax the language into producing an empty string with a non-nil data pointer, through reslicing, but it isn't the norm. See https://play.golang.org/p/gSEmrFi5Eyw

Regarding your problem I don't see how a valid empty string could cause that, the only theory I have is that you are debugging an optimized program and the line that caused the error isn't the one we are showing (there's been improvements in the way line/instruction associations are done by the compiler since 1.10). Looking at the actual disassembly and the full stacktrace could help here. Otherwise something strange is happening.

**Comment by derekparker** [comment]
@aarzilli good catch. I was thinking that the string was maybe a pointer we were auto deref'ing and giving an incorrect result (e.g. `*s == null` vs `s == ""`).

**Comment by robbmanes** [comment]
I come from C-debugging land, only using `dlv` and Go daily for about 4 months or so, so its highly likely I misunderstood something.

The full stack is here:

```
(dlv) bt
0  0x000000000046f2c4 in runtime.raise
   at .opt/rh/go-toolset-1.10/root/usr/lib/go-toolset-1.10-golang/src/runtime/sys_linux_amd64.s:159
1  0x000000000046b6a0 in runtime.systemstack_switch
   at .opt/rh/go-toolset-1.10/root/usr/lib/go-toolset-1.10-golang/src/runtime/asm_amd64.s:363
2  0x000000000043eb5a in runtime.dopanic
   at .opt/rh/go-toolset-1.10/root/usr/lib/go-toolset-1.10-golang/src/runtime/panic.go:597
3  0x000000000043e791 in runtime.gopanic
   at .opt/rh/go-toolset-1.10/root/usr/lib/go-toolset-1.10-golang/src/runtime/panic.go:551
4  0x000000000043d66e in runtime.panicmem
   at .opt/rh/go-toolset-1.10/root/usr/lib/go-toolset-1.10-golang/src/runtime/panic.go:63
5  0x00000000004544ca in runtime.sigpanic
   at .opt/rh/go-toolset-1.10/root/usr/lib/go-toolset-1.10-golang/src/runtime/signal_unix.go:388
6  0x00000000011a2b2a in github.com/docker/docker/daemon/logger/journald.(*journald).Log
   at .usr/src/debug/docker-b2f74b220126bddbae585cfe2406498ced3ae065/_build/src/github.com/docker/docker/daemon/logger/journald/journald.go:113
7  0x00000000008deba9 in github.com/docker/docker/daemon/logger.(*Copier).copySrc
   at .usr/src/debug/docker-b2f74b220126bddbae585cfe2406498ced3ae065/_build/src/github.com/docker/docker/daemon/logger/copier.go:89
8  0x000000000046e231 in runtime.goexit
   at .opt/rh/go-toolset-1.10/root/usr/lib/go-toolset-1.10-golang/src/runtime/asm_amd64.s:2361

(dlv) frame 6
> runtime.raise() .opt/rh/go-toolset-1.10/root/usr/lib/go-toolset-1.10-golang/src/runtime/sys_linux_amd64.s:159 (PC: 0x46f2c4)
Warning: debugging optimized function
Frame 6: .usr/src/debug/docker-b2f74b220126bddbae585cfe2406498ced3ae065/_build/src/github.com/docker/docker/daemon/logger/journald/journald.go:113 (PC: 11a2b2a)
   108:		}
   109:	
   110:		line := string(msg.Line)
   111:		logger.PutMessage(msg)
   112:	
=> 113:		if msg.Source == "stderr" {
   114:			return journal.Send(line, journal.PriErr, vars)
   115:		}
   116:		return journal.Send(line, journal.PriInfo, vars)
   117:	}
   118:	

(dlv) p msg.Source
""

(dlv) p &msg.Source
(*string)(0xc420eda068)
```

I don't know of any functionality like `rd` or `x` to dereference this further in `dlv` and look at the string's fields; I used GDB for that.

```
(gdb) x 0xc420eda068
0xc420eda068:	0x00000000
```

The string manipulation doesn't happen in the Log method, it happens during PutMessage which is itself optimized:

```
// PutMessage puts the specified message back n the message pool.
// The message fields are reset before putting into the pool.
func PutMessage(msg *Message) {
        msg.reset()
        messagePool.Put(msg)
}

- - - - 8< - - - -

// reset sets the message back to default values
// This is used when putting a message back into the message pool.
// Any changes to the `Message` struct should be reflected here.
func (m *Message) reset() {
        m.Line = m.Line[:0]
        m.Source = ""
        m.Attrs = nil
        m.Partial = false
}
```

And the disassembly:

```
(dlv) disassemble -a 0x11a2b0b 0x11a2b43
TEXT github.com/docker/docker/daemon/logger/journald.(*journald).Log(SB) /usr/src/debug/docker-b2f74b220126bddbae585cfe2406498ced3ae065/_build/src/github.com/docker/docker/daemon/logger/journald/journald.go
	journald.go:111	0x11a2b0b	48891424		mov qword ptr [rsp], rdx
	journald.go:111	0x11a2b0f	e88cda73ff		call $github.com/docker/docker/daemon/logger.PutMessage
	journald.go:111	0x11a2b14	488b842408020000	mov rax, qword ptr [rsp+0x208]
	journald.go:113	0x11a2b1c	488b4820		mov rcx, qword ptr [rax+0x20]
	journald.go:113	0x11a2b20	488b4018		mov rax, qword ptr [rax+0x18]
	journald.go:113	0x11a2b24	4883f906		cmp rcx, $C.stdout+6
	journald.go:113	0x11a2b28	7514			jnz 0x11a2b3e
	journald.go:113	0x11a2b2a	8b08			mov ecx, dword ptr [rax]
	journald.go:113	0x11a2b2c	81f973746465		cmp ecx, 0x65647473
	journald.go:113	0x11a2b32	750a			jnz 0x11a2b3e
	journald.go:113	0x11a2b34	0fb74004		movzx eax, word ptr [rax+0x4]
	journald.go:113	0x11a2b38	663d7272		cmp ax, $C.stdout+29298
	journald.go:113	0x11a2b3c	7455			jz 0x11a2b93
	journald.go:113	0x11a2b3e	488b442448		mov rax, qword ptr [rsp+0x48]

(dlv) disassemble -l PutMessage
TEXT github.com/docker/docker/daemon/logger.PutMessage(SB) /usr/src/debug/docker-b2f74b220126bddbae585cfe2406498ced3ae065/_build/src/github.com/docker/docker/daemon/logger/logger.go
	logger.go:38	0x8e05a0	64488b0c25f8ffffff	mov rcx, qword ptr fs:[0xfffffff8]
	logger.go:38	0x8e05a9	483b6110		cmp rsp, qword ptr [rcx+0x10]
	logger.go:38	0x8e05ad	0f8687000000		jbe 0x8e063a
	logger.go:38	0x8e05b3	4883ec20		sub rsp, $C.stdout+32
	logger.go:38	0x8e05b7	48896c2418		mov qword ptr [rsp+0x18], rbp
	logger.go:38	0x8e05bc	488d6c2418		lea rbp, ptr [rsp+0x18]
	logger.go:38	0x8e05c1	488b4c2428		mov rcx, qword ptr [rsp+0x28]
	logger.go:59	0x8e05c6	48c7410800000000	mov qword ptr [rcx+0x8], 0x0
	logger.go:60	0x8e05ce	48c7412000000000	mov qword ptr [rcx+0x20], 0x0
	logger.go:60	0x8e05d6	8b155488cc01		mov edx, dword ptr [runtime.writeBarrier]
	logger.go:60	0x8e05dc	488d7918		lea rdi, ptr [rcx+0x18]
	logger.go:61	0x8e05e0	488d5940		lea rbx, ptr [rcx+0x40]
	logger.go:60	0x8e05e4	85d2			test edx, edx
	logger.go:60	0x8e05e6	753f			jnz 0x8e0627
	logger.go:60	0x8e05e8	48c7411800000000	mov qword ptr [rcx+0x18], 0x0
	logger.go:61	0x8e05f0	48c7414000000000	mov qword ptr [rcx+0x40], 0x0
	logger.go:62	0x8e05f8	c6414800		mov byte ptr [rcx+0x48], 0x0
	logger.go:40	0x8e05fc	488b059df7c301		mov rax, qword ptr [github.com/docker/docker/daemon/logger.messagePool]
	logger.go:40	0x8e0603	48890424		mov qword ptr [rsp], rax
	logger.go:40	0x8e0607	488d05d234d600		lea rax, ptr [runtime.types+1760512]
	logger.go:40	0x8e060e	4889442408		mov qword ptr [rsp+0x8], rax
	logger.go:40	0x8e0613	48894c2410		mov qword ptr [rsp+0x10], rcx
	logger.go:40	0x8e0618	e8633abaff		call $sync.(*Pool).Put
	logger.go:41	0x8e061d	488b6c2418		mov rbp, qword ptr [rsp+0x18]
	logger.go:41	0x8e0622	4883c420		add rsp, $C.stdout+32
	logger.go:41	0x8e0626	c3			ret
	logger.go:60	0x8e0627	31c0			xor eax, eax
	logger.go:60	0x8e0629	e812dcb8ff		call $runtime.gcWriteBarrier
	logger.go:60	0x8e062e	4889df			mov rdi, rbx
	logger.go:61	0x8e0631	31c0			xor eax, eax
	logger.go:61	0x8e0633	e808dcb8ff		call $runtime.gcWriteBarrier
	logger.go:60	0x8e0638	ebbe			jmp 0x8e05f8
	logger.go:38	0x8e063a	e8c1b1b8ff		call $runtime.morestack_noctxt
	logger.go:38	0x8e063f	e95cffffff		jmp $github.com/docker/docker/daemon/logger.PutMessage
```

This kind of easily shows that `msg.Source` is made an empty string, but its not quite that simple here.  Log is called in the context of a goroutine, and multiples can be called simultaneously with the same `msg`, which means we can race *just right* if we're in the middle of assigning an empty string to `msg.Source` when another goroutine does that comparison evaluation.  We see it infrequently and the fix is in the `moby` PR I linked above; I opened this because I was confused as to how we received `""` for the empty address above, but maybe I am doing something very wrong here.

**Comment by robbmanes** [comment]
Also @aarzilli, understood about the default representation of empty strings, thank you for that; I can see in the disassembly where we set this to nil:

```
	logger.go:62	0x8e05f8	c6414800		mov byte ptr [rcx+0x48], 0x0
```

I think that answers my questions, and we die here in a comparison:

```
	journald.go:113	0x11a2b2c	81f973746465		cmp ecx, 0x65647473
```

So not a dlv issue, but just a very funky race condition by not protecting data structures, and dlv is going to represent the `nil` as best it can.  If you agree with that, I think this issue is closed.  Thanks!

**Comment by derekparker** [comment]
@robbmanes thanks for the detailed follow up!
