### ISSUE TITLE
API for getting the information about the backend

### ISSUE THREAD

**Issue by zolotov** [go-delve/delve#1640]
It would be nice for clients to know what type of backend they were attached. In this case GoLand will be able to attach to the remote Dlv process and decide if it can/should show `Rewind` button (in case of `rr` backend).

Relative issue: https://youtrack.jetbrains.com/issue/GO-6578

Thanks.

**Comment by aarzilli** [comment]
I think it could be useful for other things but for this the way to do it is by calling Recorded.

**Comment by derekparker** [comment]
Implemented via #1641
