### ISSUE TITLE
Set value to variables doesn't persist

### ISSUE THREAD

**Issue by ramya-rao-a** [go-delve/delve#1642]
1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.2.0
Build: $Id: 068e2451004e95d0b042e5257e34f0f08ce01466 $

2. What version of Go are you using? (`go version`)?
go version go1.12.6 darwin/amd64

3. What operating system and processor architecture are you using?
macOS Mojave
Version 10.14

4. What did you do?
Sample code:
```go
package main

import (
	"fmt"
)

func main() {
	a := 123
	a = a + 1
	fmt.Println(a)
}
```

Use delve to add break point at line 9, use the `set` command to change the value of the variable `a`, hit next, the value of `a` is reverted

5. What did you expect to see?
Value for `a` persists

6. What did you see instead?
Value for `a` reverted

<img width="699" alt="Screen Shot 2019-07-27 at 10 56 46 AM" src="https://user-images.githubusercontent.com/16890566/61997931-65549580-b05d-11e9-9ecf-3f1fed7e03c1.png">

**Comment by derekparker** [comment]
This technically isn't a bug with Delve, but how the compiler chose to optimize this particular operation.

Take a look at the disassembly:

```
> main.main() ./main.go:8 (PC: 0x10b00bf)
     3:	import (
     4:		"fmt"
     5:	)
     6:
     7:	func main() {
=>   8:		a := 123
     9:		a = a + 1
    10:		fmt.Println(a)
    11:	}
(dlv) locals
a = 16798145
(dlv) disassemble -l main.main
TEXT main.main(SB) /Users/derekparker/code/delve-test-progs/main.go
	main.go:7	0x10b0090	65488b0c2530000000	mov rcx, qword ptr gs:[0x30]
	main.go:7	0x10b0099	488d4424f8		lea rax, ptr [rsp-0x8]
	main.go:7	0x10b009e	483b4110		cmp rax, qword ptr [rcx+0x10]
	main.go:7	0x10b00a2	0f86e6000000		jbe 0x10b018e
	main.go:7	0x10b00a8*	4881ec88000000		sub rsp, 0x88
	main.go:7	0x10b00af	4889ac2480000000	mov qword ptr [rsp+0x80], rbp
	main.go:7	0x10b00b7	488dac2480000000	lea rbp, ptr [rsp+0x80]
=>	main.go:8	0x10b00bf	48c74424307b000000	mov qword ptr [rsp+0x30], 0x7b
	main.go:9	0x10b00c8*	48c74424307c000000	mov qword ptr [rsp+0x30], 0x7c
	main.go:10	0x10b00d1	48c74424387c000000	mov qword ptr [rsp+0x38], 0x7c
```

If you look at where the arrow is and the 3 instructions, it is moving the immediate value `0x7b` (123) and then directly after it is moving the immediate `0x7c` (124), effectively ignoring the stored variable and computing the result directly without using an `add` instruction. I'm not sure if there is a way to prevent to compiler from performing this calculation itself as opposed to actually storing the value and issuing an `add` instruction.

cc @heschik

**Comment by aarzilli** [comment]
Upstream bug: https://github.com/golang/go/issues/29977

**Comment by derekparker** [comment]
Closing this as an upstream issue.
