### ISSUE TITLE
cannot compile dlv

### ISSUE THREAD

**Issue by jeffguorg** [go-delve/delve#1643]
Hi, i cannot get dlv installed with golang from fedora repository

1. What version of Delve are you using (`dlv version`)
not installed. problem happened during installation
2. What version of Go are you using? (`go version`)?
```
<user>@localhost ~ % go version
go version go1.12.2 gccgo (GCC) 9.1.1 20190503 (Red Hat 9.1.1-1) linux/amd64
```
3. What operating system and processor architecture are you using?
fedora30 on x86_64
4. What did you do?
```go get -u -v github.com/go-delve/delve/cmd/dlv```
5. What did you expect to see?
dlv fetched from github and compiled.
6. What did you see instead?
https://gist.github.com/jeffguorg/fcbebb96bb7b4292e12ac945966dd5cf

**Comment by derekparker** [comment]
We don't test against building with gccgo. Is there any reason you have chosen that as opposed to gc?
