### ISSUE TITLE
Delve install for mac not working.

### ISSUE THREAD

**Issue by esker** [go-delve/delve#1644]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
I can't get the install to work.

2. What version of Go are you using? (`go version`)?
go version go1.12.6 darwin/amd64

3. What operating system and processor architecture are you using?
OSX 10.14.5 (18F132) 2.3 GHz Intel Core i5

4. What did you do?
go get -u github.com/go-delve/delve/cmd/dlv

5. What did you expect to see?
dlv version - to show something

6. What did you see instead?
bash: dlv: command not found

**Comment by derekparker** [comment]
It looks like this is an issue with your $PATH. Is $GOPATH included in your $PATH?

**Comment by esker** [comment]
Thanks for the quick response, yes my $GOPATH is in $PATH

**Comment by aarzilli** [comment]
Maybe you did the `go get` from inside a folder that contains a go project that uses modules and therefore added delve as a dependency instead of installing it.

**Comment by esker** [comment]
Nope that isn't the case either, it's in my go/src directory.

**Comment by esker** [comment]
is there an additional build step I'm missing? From my understanding I just "go get" and then restart the terminal and dlv version should show something.

**Comment by esker** [comment]
export GOPATH=/Users/igibbs/go
export PATH=$PATH:$GOPATH/bin

**Comment by derekparker** [comment]
Is there any output or error after the `go get`? Can you verify the binary is in fact in `$GOPATH/bin`? What happens when you simply run `make install` from the dlv repo?

**Comment by esker** [comment]
No error after `go get`, the binary is not in go path bin. 

The following is the output of running make install from the go-delve/delve directory

fork/exec /var/folders/nl/fgzvqknd43v4tzls14hb558r0000gn/T/go-build401011845/b001/exe/make: exec format error
make: *** [install] Error 1

**Comment by esker** [comment]
In my `GOPATH/bin` directory there is a `linux_amd64` directory where the dlv binary is. I've tried both moving and copying it into the `GOPATH/bin` each time I receive the follow error.

bash: /Users/igibbs/go/bin/dlv: cannot execute binary file

**Comment by aarzilli** [comment]
Your install of go is misconfigured and you are crosscompiling everything. You probably have a GOOS environment variable set to linux. Regardless of the cause it is not a bug in delve.

**Comment by camilamacedo86** [comment]
How you solve it @aarzilli ? How you solve the `You probably have a GOOS environment variable set to linux`?
