### ISSUE TITLE
"unknown opcode

### ISSUE THREAD

**Issue by dr2chase** [go-delve/delve#1660]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.2.0
Build: $Id: 068e2451004e95d0b042e5257e34f0f08ce01466 $

2. What version of Go are you using? (`go version`)?
go version devel +08b04c27bf Tue Aug 6 13:36:20 2019 -0400 darwin/amd64

(i.e., 1.13almost)

3. What operating system and processor architecture are you using?
Darwin/macOS 10.14.16, everything up to date.

4. What did you do?
Shaggy dog story, this is part of working on https://github.com/dr2chase/dwarf-goodness/

5. What did you expect to see?
For an unknown opcode processed by (*StateMachine).next, an error message that would tell me about the unknown opcode, e.g., "unknown opcode 17 with 3 operands at offset 12345 in file foo.out"

6. What did you see instead?
"unknown opcode"

**Comment by derekparker** [comment]
Dup of https://github.com/go-delve/delve/issues/1661.
