### ISSUE TITLE
"unknown opcode" message could say more about the mystery opcode

### ISSUE THREAD

**Issue by dr2chase** [go-delve/delve#1661]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.2.0
Build: $Id: 068e2451004e95d0b042e5257e34f0f08ce01466 $

2. What version of Go are you using? (`go version`)?
go version devel +08b04c27bf Tue Aug 6 13:36:20 2019 -0400 darwin/amd64

(i.e., 1.13almost)

3. What operating system and processor architecture are you using?
Darwin/macOS 10.14.16, everything up to date.

4. What did you do?
Shaggy dog story, this is part of working on https://github.com/dr2chase/dwarf-goodness/

5. What did you expect to see?
For an unknown opcode processed by (*StateMachine).next, an error message that would tell me about the unknown opcode, e.g., "unknown opcode 17 with 3 operands at offset 12345 in file foo.out"

6. What did you see instead?
"unknown opcode"

**Comment by dr2chase** [comment]
A sample for what I might have liked to see, not 100% sure it does for debugging the problem, but
```
unknown opcode 13(0xd), 1 arguments, file /Users/drchase/work/bent/gopath/pkg/mod/github.com/!data!dog/zstd@v1.4.0/zstd_opt.c, line 80201, address 0x509df93
```

**Comment by jordanlewis** [comment]
Hey @derekparker or @dr2chase, could you provide some detail on what `unknown opcode` actually means for a user of delve? This comes up somewhat frequently in my usage and I want to understand if it means that the results of the debugging session might differ significantly from a native run of the same program.

**Comment by dr2chase** [comment]
I suspect it means there is some C code in there using some opcode that Go doesn't currently use.
I needed to know where the opcode came from to be sure it was not our (Go) problem (mistake, or new opcode that we had failed to warn the Delve team about).

**Comment by jordanlewis** [comment]
That makes sense - the program in question does in fact have a rather large CGo component. Thanks.

**Comment by aarzilli** [comment]
I imagine it's DW_LNS_set_isa which for some reasone we didn't implement.
