### ISSUE TITLE
Add grep and xargs for batch operation 

### ISSUE THREAD

**Issue by thatreguy** [go-delve/delve#1667]
1. What version of Delve are you using (`Delve Debugger
Version: 1.2.0
Build: $Id: 068e2451004e95d0b042e5257e34f0f08ce01466 $`)?
2. What version of Go are you using? (`go version go1.12.6 darwin/amd64`)?
3. What operating system and processor architecture are you using? `macOS 10.14.5`

While doing `func foo` inside delve I get a bunch of functions containing the name foo
I would like to filter this result using grep and pass it to xargs:
`xargs break` so that I can break inside only a subset of these functions.

Both xargs and grep have various other use cases as well (e.g. filtering a long list of sources)

On a broader use case I think it would help if one could execute shell operations inside delve

**Comment by aarzilli** [comment]
This is what the scripting interface is for https://github.com/go-delve/delve/blob/master/Documentation/cli/starlark.md

**Comment by derekparker** [comment]
I agree, I think we simply use the scripting support for this type of functionality as opposed to trying to make the debug interface behave like a shell.
