### ISSUE TITLE
Suggestion: Continuous Fuzzing

### ISSUE THREAD

**Issue by yevgenypats** [go-delve/delve#1670]
Hi, I'm Yevgeny Pats Founder of [Fuzzit](https://fuzzit.dev) - Continuous fuzzing as a service platform.

We have a free plan for OSS and I would be happy to contribute a PR if that's interesting.
The PR will include the following
- [go-fuzz](https://github.com/dvyukov/go-fuzz) fuzzers (This is generic step not-connected to fuzzit)
- Continuous Fuzzing of master branch which will generate new corpus and look for new crashes
- Regression on every PR that will run the fuzzers through all the generated corpus and fixed crashes from previous step. This will prevent new or old bugs from crippling into master.

You can see our basic example [here](https://github.com/fuzzitdev/example-go) and you can see an example of "in the wild" integration [here](https://github.com/google/syzkaller).

Let me know if this is something worth working on.

Cheers,
Yevgeny

**Comment by aarzilli** [comment]
It would be useful for the variable parser (pkg/proc/variables.go) and the stack unwind (pkg/proc/stack.go), because we don't want to crash with corrupted memory. I've been wanting to do it for a long time, unfortunately it's complicated to do, since we aren't just reading from a []byte but from discontiguous areas of memory.

Doing it for the debug_frame (pkg/debug/frame) and debug_line (pkg/debug/line) parsers would be easier but also much less useful.

**Comment by yevgenypats** [comment]
@aarzilli Thanks for the reply. I think it might be beneficial to start with the simplest fuzz target though less useful. Once we get through this as well as through the integration with fuzzit, we can look at the complex case. It is indeed looks non-trivial (for the variables.go and stack.go) from a quick glance (maybe I missed something) though go-fuzz is also currently working on providing structured fuzzing and not only byte array so maybe this is something that can help.

**Comment by yevgenypats** [comment]
Also, I need to mention that we have a [reward program](https://fuzzit.dev/2019/08/12/announcing-rewards-for-go-rust-oss-projects/) in case you have time/want to implement this yourself I would be happy to reward you as well as get unbiased feedback on how smooth the integration was. Let me know what you prefer.

**Comment by yevgenypats** [comment]
Closing as fuzzit was acquired by GitLab
