### ISSUE TITLE
1.2.0 release zip not present in Bintray 

### ISSUE THREAD

**Issue by karuppiah7890** [go-delve/delve#1675]
1. What did you do?
Download v1.2.0 using this link - https://dl.bintray.com/jetbrains/golang/com/jetbrains/delve/1.2.0/delve-1.2.0.zip

2. What did you expect to see?
The zip file

3. What did you see instead?
404 page

I'm only guessing that the maintainers of this project might have control over the bintray artifact. If not, I'm sorry, I'll close the issue. And this issue is related to https://github.com/fishworks/fish-food/issues/323 hence the issue report here

**Comment by karuppiah7890** [comment]
It's over here - https://bintray.com/jetbrains/golang/delve . Looks like jetbrains maintains it? Not sure 🤷‍♂

**Comment by aarzilli** [comment]
Not controlled by us, cc @dlsniper.

**Comment by karuppiah7890** [comment]
Thanks for the clarification @aarzilli

**Comment by dlsniper** [comment]
cc @zolotov

**Comment by zolotov** [comment]
I wonder what exactly commit is stated for v1.2.0?

Anyway, we use own versioning for uploaded delve package as we build it from an arbitrary delve's revision. Feel free to use the latest uploaded package.

**Comment by karuppiah7890** [comment]
@zolotov where is this uploaded package? 😄 I don't see it in installation methods

**Comment by zolotov** [comment]
@karuppiah7890 I don't understand what installation methods you're talking about but all packages are on bintray: https://bintray.com/jetbrains/golang/delve.

Also, note, that we do not provide any guarantees that we will continue uploading new delve binaries there. We won't remove already uploaded packages, though.

**Comment by karuppiah7890** [comment]
@zolotov Is bintray the only place where binaries are provided? If that's the case, is it wrong to expect that I would look for new releases too over there? For pre built binaries. Or GitHub releases could include prebuilt binaries. I can raise a PR to help with doing that using travis CI so that whenever the repo is released, it will upload pre built binaries automatically in GitHub releases - we do need to modify the config and put some secrets for access, but nothing much other than that

**Comment by zolotov** [comment]
> Or GitHub releases could include prebuilt binaries.

@karuppiah7890 I am not a maintainer of Delve, I cannot answer.

> Is bintray the only place where binaries are provided?

I don't know. We at jetbrains do not upload it elsewhere.

>  If that's the case, is it wrong to expect that I would look for new releases too over there? 

At the moment, yes. But I cannot give you any guarantees that we will continue use that repo in future.
