### ISSUE TITLE
[Feature Request?] Don't break on unrecovered-panic

### ISSUE THREAD

**Issue by BitPhinix** [go-delve/delve#1678]
There should be a command-line flag to opt-out of #317.

I have multiple microservices running inside docker containers (using delve in the local env) so I can always attach to the running microservices and debug them. The big problem with that is that the microservices don't automatically get restarted once a panic occurs (This will, for example, happen if the service is started but the database isn't up yet) since delve will prevent the program form exiting.

**Comment by aarzilli** [comment]
The unrecovered-panic breakpoint is a normal breakpoint and can be removed with `clear`. Relying on unrecovered panics and autorestarts as part of the normal functioning of a system sounds like a niche design to me and if you don't care about program crashes why would you run it inside a debugger? I'd vote against a flag for this.

Also, if you are running your production servers under delve at all times I hope you are at least taking some serious precautions with your firewalls.

**Comment by BitPhinix** [comment]
@aarxilli First of all, I'm not running the applications on our production servers under delve. Only the containers for the LOCAL dev environment. Relying on unrecovered panics is a common practice when it comes to DB connections etc. on program startup. I'm not relying on panic once the application is bootstrapped.

Thanks for the tip with clean, I will try to load a script which does that on container startup.

**Comment by derekparker** [comment]
Closing this issue out as we have provided a workaround.
