### ISSUE TITLE
delve-1.3.0 reports itself as 1.2.0

### ISSUE THREAD

**Issue by briandealwis** [go-delve/delve#1683]
Looks like the v1.3.0 tag is pointing at the wrong commit?

```sh
$ curl -sL https://github.com/go-delve/delve/archive/v1.3.0.tar.gz | tar xzf -
$ grep -A 3 DelveVersion delve-1.3.0/pkg/version/version.go
	// DelveVersion is the current version of Delve.
	DelveVersion = Version{
		Major: "1", Minor: "2", Patch: "0", Metadata: "",
		Build: "$Id: 068e2451004e95d0b042e5257e34f0f08ce01466 $",
	}
```

And the CHANGELOG is missing 1.3.0 too.

**Comment by aarzilli** [comment]
The wrong commit was tagget 1.3.0, tags are immutable so I pushed a new tag 1.3.1 pointing to the correct commit. 1.3.0 shall forever remain wrong.

**Comment by briandealwis** [comment]
Now it reports itself as 1.3.0.  It's an improvement though :-)
