### ISSUE TITLE
Continue flag vscode attach to dlv server not working

### ISSUE THREAD

**Issue by snmed** [go-delve/delve#1687]
1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 1.3.0
Build: $Id: 2f59bfc686d60989dcef9de40b480d0a34aa2fa5
```
2. What version of Go are you using? (`go version`)?
```
go version go1.13 darwin/amd64
```
3. What operating system and processor architecture are you using?
macOS Mojave 10.14.6 amd64
4. What did you do?
I'm using vscode for debugging with the following configuration:
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Attach to Process",
      "type": "go",
      "request": "attach",
      "mode": "remote",
      "port": 2345,
      "host": "127.0.0.1"
    }
  ]
}
```
and starting the dlv server with this command: `dlv exec  -l ":2345" --api-version 2 --accept-multiclient  --headless  testapp --continue`
5. What did you expect to see?
vscode stops at all defined breakpoints
6. What did you see instead?
breakpoints don't get hit, but if i use this command `dlv exec  -l ":2345" --api-version 2 --accept-multiclient  --headless  testapp` all breakpoints get hit

i'm not sure if this is really a bug, it might be that i miss some properties in the launch.json file. I would appreciate any suggestions or help on that topic.

**Comment by aarzilli** [comment]
I'm pretty sure VSCode never implemented support for the --continue flag. I'd need to see the output of `--log --log-output=rpc` to be sure.

**Comment by snmed** [comment]
The log says "broken pipe" while creating the breakpoint, but i'm not an expert on delve logs. I've attached the log file, so you can have a look into it.
[dlv.log](https://github.com/go-delve/delve/files/3587486/dlv.log)

**Comment by aarzilli** [comment]
yes, VSCode's DAP doesn't support --continue.
