### ISSUE TITLE
Can not call method of an embedded field directly

### ISSUE THREAD

**Issue by nd** [go-delve/delve#1688]
1. What version of Delve are you using (`dlv version`)?

```
Delve Debugger
Version: 1.3.0
Build: 69e6b613d81ae115521571c7550b0926be031d52
```

2. What version of Go are you using? (`go version`)?

```
go version go1.12.9 linux/amd64
```

3. What operating system and processor architecture are you using?

linux, amd64

4. What did you do?

Debug the following program with breakpoint on line 13

```
package main

type Base struct{}
type Derived struct {
	Base
}

func (b *Base) Method() int { return 4 }

var d Derived

func main() {
	println(d.Method()) // break
}
```

Execute the `call d.Method()` command once debugger stops at the breakpoint.

5. What did you expect to see?

Result of `d.Method()`

6. What did you see instead?

Error: `Command failed: d has no member Method`. The `call d.Base.Method()` command works fine.

**Comment by rillig** [comment]
Originally reported as https://youtrack.jetbrains.com/issue/GO-8053.

**Comment by rillig** [comment]
There's a typo in the test name. Instead of `Filed`, it should be `Field` or `Fields`.
