### ISSUE TITLE
Document minimum required version golang 1.10

### ISSUE THREAD

**Issue by juanluisvaladas** [go-delve/delve#1689]
1. What version of Delve are you using (`dlv version`)?
$ git show --oneline HEAD --summary 
69e6b61 pkg/dwarf/frame/parser: Fix `parse augmentation` (#1679)

2. What version of Go are you using? (`go version`)?
$ go version
go version go1.9.4 linux/amd64

3. What operating system and processor architecture are you using?
Red Hat Enterprise linux 7.7 x86_64

4. What did you do?
Tried to build delve

5. What did you expect to see?
Successful build

6. What did you see instead?
```
# make
Testing default backend
# github.com/go-delve/delve/vendor/go.starlark.net/syntax
vendor/go.starlark.net/syntax/quote.go:97:13: undefined: strings.Builder
vendor/go.starlark.net/syntax/quote.go:206:13: undefined: strings.Builder
vendor/go.starlark.net/syntax/scan.go:836:14: undefined: strings.Builder
FAIL    github.com/go-delve/delve/cmd/dlv [build failed]
exit status 1
make: *** [test] Error 1
```
go.starlark.net/syntax/scan.go uses strings.Builder which was introduced in [go 1.10](https://golang.org/doc/go1.10#strings). According to [Linux installation guide](https://github.com/go-delve/delve/blob/master/Documentation/installation/linux/install.md) and [Windows installation guide](https://github.com/go-delve/delve/blob/master/Documentation/installation/windows/install.md) golang 1.5 should be compatible by enabling experimental features.

**Comment by nqb** [comment]
Able to reproduce the issue.

**Comment by derekparker** [comment]
Fixed via https://github.com/go-delve/delve/pull/1708.
