### ISSUE TITLE
Prompt error when installing dlv in Termux

### ISSUE THREAD

**Issue by Droid-MAX** [go-delve/delve#1697]
I just installed dlv on the termux as written in the README, but there was an error like the described below.

1. OS Info:
Android 7.0 & Arch is aarch64/armv8a

2. Go Version:
go1.12.7

3. Output Result:
go/src/github.com/go-delve/delve/pkg/proc/disasm.go:10:14: undefined: archInst

**Comment by chainhelen** [comment]
https://github.com/go-delve/delve/pull/1690  

AARCH64 platform is not supported currently, but soon.

**Comment by aarzilli** [comment]
Duplicate of #118
