### ISSUE TITLE
could not attach to pid #: could not open debug info

### ISSUE THREAD

**Issue by kirk-patton** [go-delve/delve#1698]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)? 
     1.3.0
2. What version of Go are you using? (`go version`)?
    go1.13
3. What operating system and processor architecture are you using?
    root@0b3fee5b1a18:/# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=19.10
DISTRIB_CODENAME=eoan
DISTRIB_DESCRIPTION="Ubuntu Eoan Ermine (development branch)"
4. What did you do?
   I am trying to run delv from a debug container that is running in the same namespace as the prod container.
sudo docker run -ti --pid container:b6b1e489ebf3 --cap-add=ALL --privileged=true --cap-add=SYS_PTRACE --security-opt=seccomp:unconfined  f5088a891b1d bash

Where;
b6b1e489ebf3 prod container
f5088a891b1d debug container

I am able to see the process id of prod container that I want to debug, but I get the error;
> dlv attach 13
could not attach to pid 13: could not open debug info

5. What did you expect to see?
debug prompt
6. What did you see instead?
could not attach to pid 13: could not open debug info

**Comment by kirk-patton** [comment]
Here the tail end of a strace of the attach attempt
https://gist.github.com/kirk-patton/6e218379ca46c5098d13db66a0e108a0

**Comment by kirk-patton** [comment]
I verified the file reference by the pid is *not* stripped using;

cp /proc/13/exe /tmp/exe

root@e038f2e52968:/# file /tmp/exe
/tmp/exe: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=ludYycq9soDNJaDsdoBN/IO2g35uyvdIOB5dIpcXe/yiuwEegIzbB845fAvn-9/7S_YUx70bw_8d1aX3Exk, not stripped

**Comment by chainhelen** [comment]
@kirk-patton 
It relate to `DWARF symbol table`, not `stripped`. 

For example, `-w` flag in [go link](https://golang.org/cmd/link/) omit the DWARF symbol table.

```
// main.go
package main
import "fmt"
func main() {
	fmt.Println("hello world")
}

// build with `omit the DWARF symbol table`
go build -ldflags "-w"  -o main main.go

// debug
dlv exec ./main
could not launch process: could not open debug info

// file
file main         
main: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped
```

**Comment by kirk-patton** [comment]
Confirmed:

I rebuilt using (-gcflags "-N -l") and am able to attach.

Thanks!
Kirk

**Comment by aarzilli** [comment]
@kirk-patton you should really be using `-gcflags='all=-N -l'`

**Comment by niernzc** [comment]
I make it by trim "-w -s" from ldflags

**Comment by bwangelme** [comment]
I start my process by `go run main.go`.

After that, I use `dlv attach <pid>` command to debug my process, also meet the error

```
could not attach to pid 13: could not open debug info
```

And then, I use the `go build main.go -o main && ./main` to start my process, after this, `dlv attach <pid>` works.

So I think the default go build options can work with `dlv attach`, We donn't need to set the compile options `gcflags="-N -l"`

`gcflags="-N -l"` is used to disable optimizations and disable inline, It donn't change the debug info, So I think it didn't help for error `could not attach to pid 13: could not open debug info`
