### ISSUE TITLE
Command failed: EOF

### ISSUE THREAD

**Issue by liuhuanqiang** [go-delve/delve#1700]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?

Version: 1.3.0

2. What version of Go are you using? (`go version`)?
go version go1.13 linux/amd64

3. What operating system and processor architecture are you using?

4. What did you do?
dlv core ./newscenter core.26945
(dlv) goroutines
Command failed: EOF

5. What did you expect to see?

6. What did you see instead?

**Comment by chainhelen** [comment]
@liuhuanqiang Could you provide core files?

**Comment by liuhuanqiang** [comment]
[Uploading core.zip…]

**Comment by liuhuanqiang** [comment]
[core.zip](https://github.com/go-delve/delve/files/3660598/core.zip)

**Comment by chainhelen** [comment]
@liuhuanqiang en... Could you provide newscenter?  [smile~]

**Comment by liuhuanqiang** [comment]
[newscenter155.zip](https://github.com/go-delve/delve/files/3661339/newscenter155.zip)

**Comment by chainhelen** [comment]
The core file is truncated, maybe need to check `ulimit -c ` in the OS.  
And the error that `dlv` return is not friendly.  [core.go#L117](https://github.com/go-delve/delve/blob/a82e6d69875ed11a0bb3b80d15efba4b4722106e/pkg/proc/core/core.go#L117).

**Comment by liuhuanqiang** [comment]
![image](https://user-images.githubusercontent.com/20590428/65843524-aa9a8980-e364-11e9-8623-34df67c705b3.png)


Excuse me, I don't quite understand what you mean.
