### ISSUE TITLE
disassemble cmd cause nil ptr exception if run before program is started (v 1.3)

### ISSUE THREAD

**Issue by danscales** [go-delve/delve#1703]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?

  Version: 1.3.0
  
2. What version of Go are you using? (`go version`)?

  Version 1.13

3. What operating system and processor architecture are you using?

  Linux-amd64

4. What did you do?

  Tried to disassemble a function immediately after starting delve using 'delve exec'.  I wanted to see what the code of a function looked like before debugging.  E.g. 'disassemble -l main.main'

5. What did you expect to see?

  Disassembly output.

6. What did you see instead?

I got a runtime error because of a nil pointer:

```
Command failed: Internal debugger error: runtime error: invalid memory address or nil pointer dereference
runtime.gopanic (0x545491)
        go/gc/src/runtime/panic.go:679
runtime.panicmem (0x55a92b)
        go/gc/src/runtime/panic.go:199
runtime.sigpanic (0x55a768)
        go/gc/src/runtime/signal_unix.go:394
google3/third_party/golang/delve/service/debugger/debugger.(*Debugger).Disassemble (0x8da8be)
        golang/delve/service/debugger/debugger.go:1180
google3/third_party/golang/delve/service/rpc2/rpc2.(*RPCServer).Disassemble (0xad5053)
        golang/delve/service/rpc2/server.go:610
reflect.Value.call (0x5d65b5)
        go/gc/src/reflect/value.go:460
reflect.Value.Call (0x5d5d73)
        go/gc/src/reflect/value.go:321
google3/third_party/golang/delve/service/rpccommon/rpccommon.(*ServerImpl).serveJSONCodec.func2 (0xb150ca)
        golang/delve/service/rpccommon/server.go:324
google3/third_party/golang/delve/service/rpccommon/rpccommon.(*ServerImpl).serveJSONCodec (0xb132f9)
        /golang/delve/service/rpccommon/server.go:326
```

In the previous version of dlv, running 'disassemble -l' right after starting dlv worked fine.  It looks like this change happened with commit 583d335 .   With that change, there is code to get and access through the current Goroutine in (*Debugger).Disassemble that causes nil pointer when there is no current goroutine:

```
	g, err := proc.FindGoroutine(d.target, goroutineID)
	if err != nil {
		return nil, err
	}

	var regs proc.Registers
	var mem proc.MemoryReadWriter = d.target.CurrentThread()
	if g.Thread != nil {
```

g comes back nil (even though err is also nil), so g.Thread gives a nil pointer exception.
I believe goroutineID is -1 (no current goroutine?)

**Comment by aarzilli** [comment]
The culprit is actually 9963458d77e0c6a96869945f9848de2b7e54cbb6
