### ISSUE TITLE
Process terminates after continue

### ISSUE THREAD

**Issue by akrylysov** [go-delve/delve#1711]
> 1. What version of Delve are you using (`dlv version`)?

Delve Debugger
Version: 1.3.0
Build: $Id: 2f59bfc686d60989dcef9de40b480d0a34aa2fa5 $

> 2. What version of Go are you using? (`go version`)?

go version go1.13.1 linux/amd64

> 3. What operating system and processor architecture are you using?

Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco

> 4. What did you do?

The `goroutines` command works fine the first time in the debugging session, but all the consecutive runs fail.
 
> 5. What did you expect to see?

List of goroutines.

> 6. What did you see instead?

```
Internal debugger error: runtime error: invalid memory address or nil pointer dereference
runtime.gopanic (0x42f181)
	/usr/lib/go-1.13/src/runtime/panic.go:679
runtime.panicmem (0x4442eb)
	/usr/lib/go-1.13/src/runtime/panic.go:199
runtime.sigpanic (0x444128)
	/usr/lib/go-1.13/src/runtime/signal_unix.go:394
github.com/go-delve/delve/pkg/proc.GetG (0x6e7a09)
	/home/ddeng/go/src/github.com/go-delve/delve/pkg/proc/threads.go:481
github.com/go-delve/delve/service/api.ConvertThread (0x70120e)
	/home/ddeng/go/src/github.com/go-delve/delve/service/api/conversions.go:73
github.com/go-delve/delve/service/debugger.(*Debugger).state (0x7553f5)
	/home/ddeng/go/src/github.com/go-delve/delve/service/debugger/debugger.go:370
github.com/go-delve/delve/service/debugger.(*Debugger).State (0x7551be)
	/home/ddeng/go/src/github.com/go-delve/delve/service/debugger/debugger.go:342
github.com/go-delve/delve/service/rpc2.(*RPCServer).State (0x985e9b)
	/home/ddeng/go/src/github.com/go-delve/delve/service/rpc2/server.go:103
reflect.Value.call (0x4bedb5)
	/usr/lib/go-1.13/src/reflect/value.go:460
reflect.Value.Call (0x4be573)
	/usr/lib/go-1.13/src/reflect/value.go:321
github.com/go-delve/delve/service/rpccommon.(*ServerImpl).serveJSONCodec.func2 (0x9c6d9a)
	/home/ddeng/go/src/github.com/go-delve/delve/service/rpccommon/server.go:318
github.com/go-delve/delve/service/rpccommon.(*ServerImpl).serveJSONCodec (0x9c5105)
	/home/ddeng/go/src/github.com/go-delve/delve/service/rpccommon/server.go:320
runtime.goexit (0x45ca10)
	/usr/lib/go-1.13/src/runtime/asm_amd64.s:1357
```

**Comment by derekparker** [comment]
Hey, thanks for reporting this issue.

By consecutive do you mean without entering another command, or are you continuing the debug session and then trying to use that command later and it's failing with this panic?

Also, can you provide a reproducible example?

**Comment by aarzilli** [comment]
A way to reproduce this and figure out what is actually happening would be appreciated. If that's impossible see associated PR.

**Comment by akrylysov** [comment]
Hi! I'm trying to see if I can reproduce it with a binary that doesn't contain any sensitive code, sorry for delay.

**Comment by derekparker** [comment]
@akrylysov can you verify the patch submitted by @aarzilli fixes the issue for you?

**Comment by akrylysov** [comment]
Thanks, it doesn't panic anymore, but now for all 600 goroutines it shows:
```
Goroutine N - User: /root/.gimme/versions/go1.13.linux.amd64/src/runtime/proc.go:305 runtime.gopark (0x451050)
```
(the second time I run `goroutines`). Still trying to find an easy was to reproduce it.

Also after I switch to a goroutine and type `locals` it shows:
```
mp = (unreadable could not find loclist entry at 0x3b3ae for address 0x451050)
gp = (unreadable could not find loclist entry at 0x3b3e1 for address 0x451050)
status = (unreadable could not find loclist entry at 0x3b414 for address 0x451050)
```

**Comment by aarzilli** [comment]
> the second time I run goroutines

This isn't consecutive, right? You do goroutines the first time and it works fine, then you continue the target program somehow and after that you get this output. Correct?

I'm skeptical that all of the goroutines are actually stopped at runtime.gopark, I bet only the vast majority of them are. You can save this code:

```
def command_goexcl(args):
	"""Prints all goroutines not stopped in the function passed as argument."""
	excluded = 0
	start = 0
	while start >= 0:
		gr = goroutines(start, 10)
		start = gr.Nextg
		for g in gr.Goroutines:
			fn = g.UserCurrentLoc.Function
			if fn == None:
				print("Goroutine", g.ID, "User:", g.UserCurrentLoc.File, g.UserCurrentLoc.Line)
			elif fn.Name_ != args:
				print("Goroutine", g.ID, "User:", g.UserCurrentLoc.File, g.UserCurrentLoc.Line, fn.Name_)
			else:
				excluded = excluded + 1
	print("Excluded", excluded, "goroutines")
```

As goexcl.star and then do:

```
(dlv) source path_to_goexcl.star
(dlv goexcl runtime.gopark
```

to only print goroutines that are not stopped on runtime.gopark.

It is strange that you are getting all three local variables of runtime.gopark as unreadable. I just tested it on go 1.13.1 and mp and gp should be readable at runtime/proc.go:305, are you sure you are compiling with go 1.13.1. Also the stack command could tell you why you have so many goroutines that are just running runtime code.

**Comment by akrylysov** [comment]
When I run the script I get `Command failed: no such process`. I'm running the commit `6b20e880e2c756760f112686459541fe01111091` of delve.

> I'm skeptical that all of the goroutines are actually stopped at runtime.gopark, I bet only the vast majority of them are.

Yes. you are right, I looked closer, I see 3 groups of goroutines:
1. `Goroutine 1 - User: /root/.gimme/versions/go1.13.1.linux.amd64/src/runtime/proc.go:305 runtime.gopark (0x451050)` ~300 goroutines
2. `  Goroutine 8 - User: /root/.gimme/versions/go1.13.1.linux.amd64/src/runtime/lock_futex.go:228 runtime.notetsleepg (0x42aef4)` ~20 goroutines
3. `  Goroutine 30 - User: :0 ??? (0x7f61fe9ae7be) (thread 356)` 1 goroutine

**Comment by aarzilli** [comment]
As far as the goroutines go I don't see anything bad. Goroutine 30 is weird but there could be many reasons for that.

> When I try to continue (c) I get Process 343 has exited with status 0. According to top the process 343 is still running.

I think you should share more details about what you are doing and what's happening. Was "thread 356" (the weird one) the current thread when you hit continue? Why shouldn't the program terminate when you continue?

**Comment by derekparker** [comment]
Issue has been dead for ~2 weeks, closing. Please reopen if still a valid issue.
