### ISSUE TITLE
Feature: to include a go compiler version into GetVersion result

### ISSUE THREAD

**Issue by nd** [go-delve/delve#1713]
It would be great to get the go compiler version so that the client can implement an analog of the `--check-go-version` logic.

**Comment by aarzilli** [comment]
Do you mean it should contain the minimum and maximum versions of go supported?

**Comment by nd** [comment]
I'm insterested in the result of `BinaryInfo.Producer()`, but min/max version supported by Delve can be useful as well.

**Comment by nd** [comment]
Thank you!

I was reading version-related code and noticed that `1.14beta2` is `AfterOrEqual` to `1.14rc1`. Shouldn't it be otherwise?

**Comment by aarzilli** [comment]
> I was reading version-related code and noticed that 1.14beta2 is AfterOrEqual to 1.14rc1. Shouldn't it be vice versa?

Yes, but it doesn't matter because we never care about anything beyond the minor version. The thing is a massive overkill.
