### ISSUE TITLE
Not able to calculate TLS value on ARM64 platform

### ISSUE THREAD

**Issue by ossdev07** [go-delve/delve#1715]
we are not able to calculate TLS using ptrace function in delve for ARM64

ptrace(PTRACE_GETREGSET,pid,uintptr(elf.NT_ARM_TLS),uintptr(unsafe.Pointer(&iovec)))
**but always getting value "0"**

We tried to find out TLS in our sample code (**in C language not in GO lang**) and able to calculate correctly
with following function..
 ret = ptrace (PTRACE_GETREGSET, pid,(void*)NT_ARM_TLS, (void*)&iovec);

_we are suspecting that NT_ARM_TLS is not handled in go lang , please suggest_
****
if you need sample code , please let us know

**Comment by aarzilli** [comment]
Let's keep discussion of the arm PR on the arm PR.
