### ISSUE TITLE
intall failed

### ISSUE THREAD

**Issue by johnnylei** [go-delve/delve#1719]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
v1.0.0.0
2. What version of Go are you using? (`go version`)?
go1.7.1
3. What operating system and processor architecture are you using?
ubuntu 14.04, kernel: 3.13.0-83-generic
4. What did you do?
make install
5. What did you expect to see?
succeed
6. What did you see instead?
go install -ldflags="-X main.Build=279a8a792e2748ba07be9ca15688d1871c0f1a5f" github.com/derekparker/delve/cmd/dlv
../../derekparker/delve/pkg/proc/bininfo.go:31:2: cannot find package "github.com/go-delve/delve/pkg/logflags" in any of:
	/root/go/src/github.com/derekparker/delve/vendor/github.com/go-delve/delve/pkg/logflags (vendor tree)
	/usr/local/go/src/github.com/go-delve/delve/pkg/logflags (from $GOROOT)
	/root/go/src/github.com/go-delve/delve/pkg/logflags (from $GOPATH)
../../derekparker/delve/pkg/proc/core/windows_amd64_minidump.go:6:2: cannot find package "github.com/go-delve/delve/pkg/proc/core/minidump" in any of:
	/root/go/src/github.com/derekparker/delve/vendor/github.com/go-delve/delve/pkg/proc/core/minidump (vendor tree)
	/usr/local/go/src/github.com/go-delve/delve/pkg/proc/core/minidump (from $GOROOT)
	/root/go/src/github.com/go-delve/delve/pkg/proc/core/minidump (from $GOPATH)
../../derekparker/delve/pkg/proc/core/linux_amd64_core.go:13:2: cannot find package "github.com/go-delve/delve/pkg/proc/linutil" in any of:
	/root/go/src/github.com/derekparker/delve/vendor/github.com/go-delve/delve/pkg/proc/linutil (vendor tree)
	/usr/local/go/src/github.com/go-delve/delve/pkg/proc/linutil (from $GOROOT)
	/root/go/src/github.com/go-delve/delve/pkg/proc/linutil (from $GOPATH)
../../derekparker/delve/pkg/proc/core/windows_amd64_minidump.go:7:2: cannot find package "github.com/go-delve/delve/pkg/proc/winutil" in any of:
	/root/go/src/github.com/derekparker/delve/vendor/github.com/go-delve/delve/pkg/proc/winutil (vendor tree)
	/usr/local/go/src/github.com/go-delve/delve/pkg/proc/winutil (from $GOROOT)
	/root/go/src/github.com/go-delve/delve/pkg/proc/winutil (from $GOPATH)
../../derekparker/delve/pkg/terminal/starlark.go:4:2: cannot find package "github.com/go-delve/delve/pkg/terminal/starbind" in any of:
	/root/go/src/github.com/derekparker/delve/vendor/github.com/go-delve/delve/pkg/terminal/starbind (vendor tree)
	/usr/local/go/src/github.com/go-delve/delve/pkg/terminal/starbind (from $GOROOT)
	/root/go/src/github.com/go-delve/delve/pkg/terminal/starbind (from $GOPATH)
make: *** [install] Error 1

**Comment by aarzilli** [comment]
That version of Go is no longer supported, if you can't update to a newer version you'll have to download an older version of delve (probably 0.12)
