### ISSUE TITLE
debug often disappear

### ISSUE THREAD

**Issue by 1363129424** [go-delve/delve#1721]
Hello, when I use GoLand's debugging mode, The debug often disappear when I gradually track the breakpoint. At this time, I can't click to track the next step, the program does not stop , and the request is still displayed as the sending status. But I can't do anything at this time, I can only stop the program manually and restart the debug mode to re-track. How can I solve this problem? I tried to print the log through the command line, but I failed. I don't know how to print out the DLEVE log in the GoLand command line. I need help, this problem has caused me a lot of obstacles to writing programs, especially programs with many steps.

**Comment by dlsniper** [comment]
I would recommend opening on issue on GoLand's tracker first, and check to see if this is not an IDE/configuration problem before continuing here.
That being said, make sure that you use the latest version of GoLand, 2019.2.3 at the time of writing this comment, and a newer version of Go, at least Go 1.12 if Go 1.13 is not possible.

**Comment by derekparker** [comment]
Closing this out until we have more information on whether this is a Delve or GoLand issue.
