### ISSUE TITLE
How does Delve geta addresses and values of variables?

### ISSUE THREAD

**Issue by vaastav** [go-delve/delve#1726]
Hi,

I am currently building a property checker for go programs and I was hoping to use some of the delve source code for getting the addresses for variables.
I am working with a modified version of go-runtime where I can get access to the stacks of all the goroutines.
What I need in addition is to be able to get the values of the variables for which I need to find the address for that specific variable.

I was looking through the delve source code but I couldn't wrap my head around as to how Delve was getting the addresses and values of variables during runtime.
I know that Delve is parsing the Dwarf info which has offsets for variables and parameters, but I was wondering how
does Delve put these offsets in context with the absolute addresses.
Just to be more specific, my question is what all information from the go-runtime do I need to be able to get the address/values of the variables. 

I have been able to parse the DWARF debugging information to get some sort of relative address but I am not sure if that
is correct or what it is relative to. Do I just need to look at the stack pointer or base pointer of the goroutine?
If someone could please explain this to me, I would greatly appreciate it.

**Comment by aarzilli** [comment]
Responded to in the mailing list https://groups.google.com/d/msg/delve-dev/2fMYEGbR2B0/UtzgzNFLEAAJ

**Comment by vaastav** [comment]
Thanks so much for a great response :)
