### ISSUE TITLE
Breakpoint on absolute path not working

### ISSUE THREAD

**Issue by Meai1** [go-delve/delve#1730]
Start listening for debug clients:

> dlv --listen=:2345 --headless=true --api-version=2 --accept-multiclient --wd=/home/pc/workarea/projects/GOPATH/src/k8s.io/kubernetes exec /home/pc/.cache/bazel/_bazel_pc/6a1773eb858882fef994ad8c7782523f/execroot/io_k8s_kubernetes/bazel-out/k8-dbg/bin/cmd/kube-apiserver/linux_amd64_pure_debug/kube-apiserver
API server listening at: [::]:2345

Connect:

> dlv --api-version 2 connect localhost:2345
(dlv) b cmd/kube-apiserver/apiserver.go:32
Breakpoint 1 set at 0x468b101 for main.main() cmd/kube-apiserver/apiserver.go:32
(dlv) b /home/pc/workarea/projects/GOPATH/src/k8s.io/kubernetes/cmd/kube-apiserver/apiserver.go:34
Command failed: Location "/home/pc/workarea/projects/GOPATH/src/k8s.io/kubernetes/cmd/kube-apiserver/apiserver.go:34" not found
`

So the issue is that `/home/pc/workarea/projects/GOPATH/src/k8s.io/kubernetes/cmd/kube-apiserver/apiserver.go` definitely exists but it still cant set a breakpoint on it for some reason. The problem is that vscode sets paths via absolute path, so it has to work. I think Goland IDE does that too. 

To reproduce, the kubernetes software in question was built by checking out the kubernetes trunk and running `bazel build --compilation_mode=dbg //cmd/kube-apiserver:kube-apiserver`
The resulting binary is then in a deep nested folder as you've seen above: `/home/pc/.cache/bazel/_bazel_pc/6a1773eb858882fef994ad8c7782523f/execroot/io_k8s_kubernetes/bazel-out/k8-dbg/bin/cmd/kube-apiserver/linux_amd64_pure_debug/kube-apiserver`

btw my GOPATH folder is actually named GOPATH, it's not a shell expansion problem in case you wondered.

dlv version 1.3.2
go version 1.7.4

My suggestion: Could you maybe add some more detailed logging to the error "Location not found"? Is the file not found? Surely it has to be found, it's right there, the path is absolute. So how can it not be found, there has to be something else going on here.

**Comment by derekparker** [comment]
Hm, I agree that the error message could be more descriptive here as to what actually went wrong when looking up the location.

However, is there any actual code at the location you're trying to set a breakpoint at? What if you use the absolute path and line 32 like the breakpoint above which succeeded?

**Comment by Meai1** [comment]
yeah line 34 has some code on it. I didnt change anything in kubernetes, here: https://github.com/kubernetes/kubernetes/blob/2905275a08f8e3999e7e6bc8b02f407fd6a0ff36/cmd/kube-apiserver/apiserver.go#L34

**Comment by dlsniper** [comment]
The way your code is built might affect this (paths and all). Let me know if you tried from GoLand 2019.2.3 (since you mentioned the IDE), and if it fails. The IDE itself has some heuristics to figure out where to put the breakpoint and the path matching is automatic.

**Comment by Meai1** [comment]
Ok but I cant exactly change how these IDEs want to do their debugging and I dont see any option for bazel+go to change the debug symbol paths either, at least I havent found anything with google searches just now.
It would be much easier and flexible if Delve had an option for me to specify a prefix or search path like GDB does. I already tried the substitute-path: 

```
substitute-path:
  - {from: /home/pc/workarea/projects/GOPATH/src/k8s.io/kubernetes/, to: }
```

and: 

```
substitute-path:
  - {from: /home/pc/workarea/projects/GOPATH/src/k8s.io/kubernetes/cmd, to: cmd}
```
but that doesnt seem to help delve with converting absolute paths to relative as I would expect it would need to start working.

**Comment by dlsniper** [comment]
GoLand looks at whatever the paths are in the binary and based on the configuration of the project, it can infer the paths to match the debugged target when debugging.

By the sounds of it, something went wrong with the heuristics in this case.

However, I don't know how the Bazel part work, but I'll ask my colleagues, @zolotov and @nd to have a look at it as well.

I know there's a Bazel plugin, https://plugins.jetbrains.com/plugin/8609-bazel/, which might be able to help you in this case.

**Comment by aarzilli** [comment]
> It would be much easier and flexible if Delve had an option for me to specify a prefix or search path like GDB does. In GDB if it cant find the sources, I usually just add the project directory to the search path and it immediately starts working

Th

**Comment by nd** [comment]
@Meai1 we improved path mapping in GoLand 2019.2.4 which will be released in a week or so. Please give it a try and [file an issue](https://youtrack.jetbrains.com/newIssue?project=GO&c=Subsystem%20Go%20Debugger) if it doesn't work as expected.
