### ISSUE TITLE
delve cannot stop at breakpoints

### ISSUE THREAD

**Issue by chendave** [go-delve/delve#1734]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)? 1.2.0
2. What version of Go are you using? (`go version`)? go1.12.4
3. What operating system and processor architecture are you using? 
```
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

# uname -a
Linux dave-desktop 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
4. What did you do?
debug kuernetes API server with delve.

5. What did you expect to see?
stop at the breakpoint as expected.

6. What did you see instead?
seems delve knows the breakpoints and try to stop at the breakpoint, but the session is not interactive, I cannot input anything in the console. 
```
I1025 11:11:27.620715   15531 asm_amd64.s:1337] ccResolverWrapper: sending new addresses to cc: [{127.0.0.1:2379 0  <nil>}]
I1025 11:11:27.620951   15531 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{127.0.0.1:2379 <nil>}]
I1025 11:11:27.647093   15531 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{127.0.0.1:2379 <nil>}]
> k8s.io/apiserver/pkg/registry/generic/registry.(*Store).Delete() ./staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store.go:929 (hits goroutine(10553):1 total:1) (PC: 0x1c42d19)
   924:         var deleteImmediately bool = true
   925:         var lastExisting, out runtime.Object
   926:
   927:         // Handle combinations of graceful deletion and finalization by issuing
   928:         // the correct updates.
=> 929:         shouldUpdateFinalizers, _ := deletionFinalizersForGarbageCollection(ctx, e, accessor, options)
   930:         // TODO: remove the check, because we support no-op updates now.
   931:         if graceful || pendingFinalizers || shouldUpdateFinalizers {
   932:                 err, ignoreNotFound, deleteImmediately, out, lastExisting = e.updateForGracefulDeletionAndFinalizers(ctx, name, key, options, preconditions, deleteValidation, obj)
   933:         }
   934:
(dlv)   *the session is flown away, I cannot input anything here with my keyboard*
E1025 12:28:13.722338   15531 watcher.go:214] watch chan error: etcdserver: mvcc: required revision has been compacted
```
delve works correctly in the first place, but after I continuing the process, it will never give me chance to input anything.

If there any way to give back the control to me?

**Comment by aarzilli** [comment]
See #65

**Comment by chendave** [comment]
it just doesn't give me a chance to input dlv commands.

**Comment by aarzilli** [comment]
So it does stop at breakpoints but you can not type anything? I don't understand.

**Comment by chendave** [comment]
sorry for my bad description!  this is what I can see from the screen, 

```
> k8s.io/apiserver/pkg/registry/generic/registry.(*Store).Delete() ./staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store.go:929 (hits goroutine(10553):1 total:1) (PC: 0x1c42d19)
   924:         var deleteImmediately bool = true
   925:         var lastExisting, out runtime.Object
   926:
   927:         // Handle combinations of graceful deletion and finalization by issuing
   928:         // the correct updates.
=> 929:         shouldUpdateFinalizers, _ := deletionFinalizersForGarbageCollection(ctx, e, accessor, options)
   930:         // TODO: remove the check, because we support no-op updates now.
   931:         if graceful || pendingFinalizers || shouldUpdateFinalizers {
   932:                 err, ignoreNotFound, deleteImmediately, out, lastExisting = e.updateForGracefulDeletionAndFinalizers(ctx, name, key, options, preconditions, deleteValidation, obj)
   933:         }
   934:
**(dlv)   <--------------** the session doesn't stopped here but do print info like this.
E1025 12:28:13.722338   15531 watcher.go:214] watch chan error: etcdserver: mvcc: required revision has been compacted
...

```

If dlv works as expected, I can input some dlv command in the terminal, right?
but I can see "(dlv)" print on the screen and the it continue to print other information after that, and it have not stopped there.

everything I strike on my keyboard doesn't have any effect on the session, seems like it's flown away.

I must **ctrl + c** to stop it.

**Comment by chendave** [comment]
After clean up some kubernetes resources and restart the debug process, the issue gone, I am not sure how the race conditions impact delve, but seems they are related.

**Comment by aarzilli** [comment]
My impression is that it did stop at a breakpoint, specifically inside `registry.(*Store).Delete`, that's what the listing and `(dlv)` prompt is. The other lines being print could be from a child process spawned by the process you are debugging.

**Comment by chendave** [comment]
I also think it was stopped at a breakpoint, but the issue here is it doesn't allow me to input dlv command (bt, for example).
