### ISSUE TITLE
Cannot evaluate expression when using constant defined in another package

### ISSUE THREAD

**Issue by dlsniper** [go-delve/delve#1753]
1. What version of Delve are you using (`dlv version`)?
Version: 1.3.2
Build: 5a947bceffa8aac96574f3f7f50cdede74fc2fa7

2. What version of Go are you using? (`go version`)?
go1.13.4 

3. What operating system and processor architecture are you using?
windows/amd64

4. What did you do?
- Use the code at: https://github.com/dlsniper/democonstdbg
- Place a breakpoint on line 19
- Evaluate the expression
```
approved == "play/internal/test".Approved
```

5. What did you expect to see?
I would expect to see a boolean result

6. What did you see instead?
An error:
```
type string is not a struct
```

**Comment by aarzilli** [comment]
Same as https://github.com/golang/go/issues/35527 but additionally `"play/internal/test".Approved` is not a valid expression, it should be `test.Approved`.

**Comment by dlsniper** [comment]
Thanks. Feel free to reword/close this as we track this upstream already.

**Comment by x-yuri** [comment]
> `"play/internal/test".Approved` is not a valid expression, it should be `test.Approved`.

I just [tried][a], both `"play/internal/test".Approved` and `test.Approved` work with variables. But neither works with constants (even the integer ones).

[a]: https://gist.github.com/x-yuri/77d04d75e18661936d21779c7b89cba5
