### ISSUE TITLE
proc/native/freebsd: verify compatiblity with current go-tip (which will become Go 1.14)

### ISSUE THREAD

**Issue by aarzilli** [go-delve/delve#1754]
Go 1.14 uses a new system to preempt goroutines non-cooperatively by sending a SIGURG signal to its own threads. This necessitates [increased rigour in signal routing](https://github.com/go-delve/delve/pull/1752). We should verify that this doesn't expose latent bugs in the freebsd native backend before Go 1.14/Delve 1.4.0 is released.

cc @rayrapetyan

**Comment by rayrapetyan** [comment]
Currently it fails couple:

> FAIL: TestIssue411
> support.go:246: enabling recording for github.com/go-delve/delve/pkg/terminal.TestIssue411
>     command_test.go:105: output of "break math.go:8": ""
>     command_test.go:106: Error executing <break math.go:8>: Location "math.go:8" ambiguous: /ara/devel/go/src/github.com/go-delve/delve/_fixtures/math.go, /home/robert/sdk/gotip/src/runtime/internal/math/math.go…

> FAIL: Test1ClientServer_traceContinue
> FAIL: Test1ClientServer_traceContinue2
> FAIL: TestDisasm

I believe first and last one should be common fails in all envs (please confirm). I can take care of the rest two.

**Comment by aarzilli** [comment]
Check out  #1727 for fixes for os independent fixes for 1.14.

**Comment by derekparker** [comment]
I think we can close this one. @aarzilli please reopen if I'm mistaken.
