### ISSUE TITLE
unable to make install

### ISSUE THREAD

**Issue by Z14010040** [go-delve/delve#1760]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
latest
2. What version of Go are you using? (`go version`)?
go version go1.13.4 linux/amd64
3. What operating system and processor architecture are you using?
CentOS Linux release 7.7.1908 (Core)
4. What did you do?
make install
5. What did you expect to see?
success
6. What did you see instead?
go: github.com/cosiner/argv@v0.0.0-20170225145430-13bacc38a0a5: Get https://proxy.golang.org/github.com/cosiner/argv/@v/v0.0.0-20170225145430-13bacc38a0a5.mod: EOF
make: *** [install] Error 1

**Comment by aarzilli** [comment]
It seems that you have problems contacting proxy.golang.org. If you are in China be advised that [proxy.golang.org does not work](https://github.com/golang/go/issues/31755), otherwise you should report this problem to [Go](https://github.com/golang/go).
Closing, not our fault.
