### ISSUE TITLE
Feature: to expose goroutine labels in API

### ISSUE THREAD

**Issue by nd** [go-delve/delve#1763]
It is possible to [set pprof labels for a goroutine](https://tip.golang.org/pkg/runtime/pprof/#Do). It would be great to have access to these labels via API. They can make it easier to find a goroutine without looking into its stack.

**Comment by nd** [comment]
I was able to read labels map using a direct address syntax expression evaluation like this inside parseG():

```
if labelsVar := v.loadFieldNamed("labels"); labelsVar != nil && len(labelsVar.Children) == 1 {
	if address := labelsVar.Children[0]; address.Addr != 0 {
		scope := globalScope(v.bi, v.bi.Images[0], v.mem)
		labelsMap, _ := scope.EvalExpression(fmt.Sprintf("*(*pprof.labelMap)(%d)", address.Addr), loadFullValue)
		//...
	}
}
```

I'm sure it is wasteful to do that. I was trying to construct the var manually using `newVariable()` but cannot create a proper type for it. The following doesn't work:

```
t := new(godwarf.MapType)
t.KeyType = new(godwarf.StringType)
t.ElemType = new(godwarf.StringType)
```
	
What is the right way to create such a type?

**Comment by aarzilli** [comment]
`findType("runtime/pprof.labelMap")`
