### ISSUE TITLE
Set breakpoints in dlv command

### ISSUE THREAD

**Issue by tacnoman** [go-delve/delve#1769]
Feature to add breakpoints in dlv command, like:

`dlv debug cmd/server/main.go --breakpoints "./pkg/api/server.go:33;./pkg/api/server.go:44;./pkg/model/user.go:13"`

And this will set theese breakpoints:

- ./pkg/api/server.go at line 33
- ./pkg/api/server.go at line 44
- ./pkg/model/user.go at line 13

How difficult is implement this? I'm thinking to make a PR to solve this.

--------

Please answer the following before submitting your issue:

1. What version of Delve are you using (`dlv version`)?
1.3.0

2. What version of Go are you using? (`go version`)?
go1.13

3. What operating system and processor architecture are you using?
Ubuntu (Linux)

**Comment by aarzilli** [comment]
See the `--init` flag

**Comment by tacnoman** [comment]
@aarzilli 

Is possible to set the breakpoints before?

I tried this:

```bash
dlv debug main.go -- --init "./breakpoints.txt"
```

and not worked :/

Do you have any example?
