### ISSUE TITLE
Allow dumping of entire string

### ISSUE THREAD

**Issue by Arteneko** [go-delve/delve#1783]
1. What version of Delve are you using (`dlv version`)? 1.3.2
2. What version of Go are you using? (`go version`)? 1.13.4
3. What operating system and processor architecture are you using? Arch-Linux x86_64
4. What did you do? `p <string variable>`
5. What did you expect to see? a full dump of the variable
6. What did you see instead? a cropped dump of the variable

I'd like to be able to see the *full* dump of the string variable at once.

Is there a way to do so?

**Comment by aarzilli** [comment]
Use `config max-string-len` to change the maximum number of character displayed. There is no way to disable this maximum because the full string could be very long.

**Comment by nexovec** [comment]
Sorry for reviving this old issue, but it would be very helpful if it was possible to optionally dump an entire string(or any object), is there really no way to do this?
