### ISSUE TITLE
Error while installing dlv using go get command , unexported reference to runtime.stringHash

### ISSUE THREAD

**Issue by iGeek098** [go-delve/delve#1790]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
Not installing
2. What version of Go are you using? (`go version`)?
go1.10.3 gccgo
3. What operating system and processor architecture are you using?
x86-64 Linux
4. What did you do?
go get -u github.com/go-delve/delve/cmd/dlv
5. What did you expect to see?
installation succeeds 
6. What did you see instead?
failure
the installation fails because of reference to unexported function stringHash

**Comment by iGeek098** [comment]
exact error is:
 /home/youssef/go/src/github.com/go-delve/delve/vendor/go.starlark.net/starlark/hashtable.go:357: undefined reference to `runtime.stringHash'

**Comment by aarzilli** [comment]
Building with gccgo is not supported.
