### ISSUE TITLE
[question] How to set a breakpoint on a struct method when testing

### ISSUE THREAD

**Issue by kaelzhang** [go-delve/delve#1792]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)? any
2. What version of Go are you using? (`go version`)? any
3. What operating system and processor architecture are you using? macos, 
4. What did you do?

As we know, we could set a breakpoint on func main by:

```sh
(dlv) b main.main
```

If we have a `main.go` and a `main_test.go`

```go
// main.go
package main

type someStruct struct {
	id int
}

func (s *someStruct) Name() string {  // <------- how can we set a breakpoint here?
	return "someStruct"
}
```

```go
// main_test.go
package main

import "testing"

func TestRunsSuite(t *testing.T) {
	s := someStruct{1}

	if s.Name() != "someStruct" {
		t.Errorf("error")
	}
}
```

we run delve as

```sh
$ dlv test
```

But there is not enough document about how to set a breakpoint on a struct method.

If we

```sh
(dlv) b main.(*someStruct).Name
Command failed: Location "main.(*someStruct).Name" not found
```

There will be a LOCATION_NOT_FOUND error.

5. What did you expect to see?
- we could set a breakpoint
- the use case is well documented

6. What did you see instead?

**Comment by qingyunha** [comment]
You can use  `break main.(*someStruct).Name`.

**Comment by kaelzhang** [comment]
@qingyunha it works if we run the debugger with `dlv debug main.go`, but how about testing cases? Sorry that I didn't describe my use case very well.

I've updated the issue.

**Comment by kaelzhang** [comment]
I've figured it out:

```sh
(dlv) b main main.go:7
```

**Comment by qingyunha** [comment]
It doesn't work in testing mode may casuse by `go test` change the importpath of the `main pacakge`. You can try `funcs someStruct` to check.

**Comment by chainhelen** [comment]
@kaelzhang `(dlv) b main.go:7` is enough if `<filename>:<line>` in `test`.

btw, set breakpoint as `b command-line-arguments.(*someStruct).Name`  by name  in `test`.

**Comment by aarzilli** [comment]
`b someStruct.Name` will also usually work.
