### ISSUE TITLE
Feature request: invoke debugger from inside program

### ISSUE THREAD

**Issue by icholy** [go-delve/delve#1794]
Python's PDB and Ruby's IRB both have a convenient feature for starting the debugger programatically from inside the code. The advantage is that it's equal or less effort than printf debugging.

Ex:

``` go
package main

import "github.com/go-delve/delve"

func main() {
	delve.Debug()
}
```

I don't know if this is feasible, but I figured it would be worth asking.

**Comment by chainhelen** [comment]
Maybe what you want is `runtime.Breakpoint`.
```
package main

import (
	"fmt"
	"runtime"
)

func main() {
	runtime.Breakpoint()
	fmt.Printf("hello world")
}
```
`dlv debug main.go` then `c`

**Comment by icholy** [comment]
@chainhelen  I'm aware of `runtime.Breakpoint`. This is a purely ergonomic improvement which would make me (and I think a lot of others) reach for delve in a lot of cases where I/they usually wouldn't.

**Comment by aarzilli** [comment]
The only way to do this would be to have the target program start the delve (as a separate process) and ask it to attach. It's likely to be a lot of work to provide a minor convenience.

**Comment by icholy** [comment]
@aarzilli complexity aside, would it be possible to run delve in the same process as the target program?

**Comment by aarzilli** [comment]
No, it would deadlock itself.

**Comment by icholy** [comment]
I see. Would you be opposed to leaving this issue open just to gauge interest?

**Comment by aarzilli** [comment]
Yes, that's fine.

**Comment by aarzilli** [comment]
Doesn't look like there's been enough interest for this in the past 3 years.
