### ISSUE TITLE
dlv attach running process error

### ISSUE THREAD

**Issue by huang2287832** [go-delve/delve#1797]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
`Delve Debugger
Version: 1.3.2
Build: $Id: 569ccbd514fc47c8b4c521b142556867ec5e6917 $
`
2. What version of Go are you using? (`go version`)?
`go version go1.13.5 linux/amd64`
3. What operating system and processor architecture are you using?
`Linux ubuntu`
4. What did you do?
`package main

import (
	"time"
	"fmt"
)

func main() {
	p(1)
}

func p(n int)  {
	time.Sleep(2*time.Second)
	n++
	fmt.Println("bbbbbb", n)
	p(n+1)
}`
5. What did you expect to see?
```
go run hbtest.go
ps aux|grep main
dlv attch pid
l hbtest.go:14
Command failed: Location "hbtest.go:14" not found
```
6. What did you see instead?
Command failed: Location "hbtest.go:14" not found

why???  but if I build hbtest first,  and then ./hbtest, it can found the file
eg:
```
go buld hbtest.go 
./hbtest
ps aux|grep main
dlv attch pid
l hbtest.go:14
```

that's right！！！ why？？？

**Comment by aarzilli** [comment]
go run executables do not have debug symbols.
