### ISSUE TITLE
Question: Live Reloading and Debugging

### ISSUE THREAD

**Issue by ivorscott** [go-delve/delve#1798]
I am using VSCode and Docker. I want to live reload a go api and use the delve debugger in the same container instance.

Here's what I have so far: https://github.com/ivorscott/go-delve-reload

In the docker-compose.yml file you will see two services api and debug api. One uses CompileDaemon, the other uses Delve. Both containers are based off the same "dev" build stage in a multi-stage scenario. 

Whenever I tried combining both approaches within one container I had issues. Ideally I want to have both features in one container.

**Comment by PhillDubois** [comment]
Have you got any progress?

**Comment by ivorscott** [comment]
Unfortunately no.  Someone wrote a blog post about getting live reloading and debugging working at the same time, they made a bash script. Today I use Goland. It has built in support for delve. So my workflow now with docker has changed. When I want live reloading I use a continaer with CompileDaemon. My go backend is not dependent on Docker (I always keep a db container though). When I want an idiomatic development process I start the backend with out live reloading and without a container. Goland has a powerful debug feature and connects to your app with delve. I still use VSCode but Goland is amazing.

**Comment by eldad87** [comment]
You can try this one:
https://medium.com/@hananrok/debugging-hot-reloading-go-app-within-docker-container-b44d2929e8bd
