### ISSUE TITLE
opensuse 15.1 vs code debug failed with fork/exec

### ISSUE THREAD

**Issue by liuheqi** [go-delve/delve#1799]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.3.2

2. What version of Go are you using? (`go version`)?
go version go1.13.5 linux/amd64

3. What operating system and processor architecture are you using?
opensuse 15.1
4. What did you do?
debug with vs code

5. What did you expect to see?
normal debug

6. What did you see instead?
<pre>
Running: /home/.go/bin/dlv debug --headless=true --listen=127.0.0.1:47250 --api-version=2 --log=true --log-output=rpc --build-flags=-tags=exe
API server listening at: 127.0.0.1:47250
InitializeEvent
could not launch process: fork/exec /home/client/__debug_bin: exec format error
Process exiting with code: 1
Sending TerminatedEvent as delve is closed
DisconnectRequest
HaltRequest
ConfigurationDoneRequest
</pre>

But, the command line can be run in terminal with out error

**Comment by chainhelen** [comment]
It looks that execute something on the wrong architecture/OS, instead of `dlv`.  
Maybe you can `go build` and `run` manually.

**Comment by liuheqi** [comment]
> It looks that execute something on the wrong architecture/OS, instead of `dlv`.
> Maybe you can `go build` and `run` manually.

So, is that a bug on vscode? Or something unknown? Is that a common problem on OpenSuse, or just for me?LOL

**Comment by chainhelen** [comment]
No, I mean maybe some wrong operations for this and should try it manually.

**Comment by aarzilli** [comment]
Closing, no user feedback.
