### ISSUE TITLE
When to support read var from stdin in debug mode

### ISSUE THREAD

**Issue by xieyuanhuata** [go-delve/delve#1801]
Delve Debugger
Version: 1.3.2
Build: $Id: 569ccbd514fc47c8b4c521b142556867ec5e6917 $

**Comment by aarzilli** [comment]
What do you mean exactly?

**Comment by chainhelen** [comment]
@xieyuanhuata  You use `--headless` mode to distinguish between two inputs of `dlv` and `target`.  

ps, also use pipeline `<` for input of `target`.

**Comment by aarzilli** [comment]
Closing, no user feedback.
