### ISSUE TITLE
Install Delve on CENTOS Fails

### ISSUE THREAD

**Issue by davesargrad** [go-delve/delve#1809]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)? 
2. What version of Go are you using? (`go version`)? 1.13.5

![image](https://user-images.githubusercontent.com/48793689/71737239-1e937480-2e21-11ea-8995-457eea55cca6.png)

3. What operating system and processor architecture are you using?
Centos 7    linux/amd64
4. What did you do?
Installed go in /usr/local/go
![image](https://user-images.githubusercontent.com/48793689/71736863-29013e80-2e20-11ea-85e0-978427c37f17.png)

![image](https://user-images.githubusercontent.com/48793689/71737125-d07e7100-2e20-11ea-899e-fb37a453e67a.png)

Tried to install delve 
go get -u github.com/go-delve/delve/cmd/dlv
5. What did you expect to see?
Installed delve
6. What did you see instead?
![image](https://user-images.githubusercontent.com/48793689/71736920-4e8e4800-2e20-11ea-9e5e-1266f104cb11.png)

![image](https://user-images.githubusercontent.com/48793689/71736950-5e0d9100-2e20-11ea-8cf6-3f047cbfb9d2.png)

I believe I've installed go correctly. I am using the default GOPATH (its not set so it goes to ~/go)..

**Comment by davesargrad** [comment]
![image](https://user-images.githubusercontent.com/48793689/71737170-f3108a00-2e20-11ea-891d-9d570d71b5f2.png)

**Comment by aarzilli** [comment]
Looks like a problem with your install of go: https://github.com/golang/go/issues/35018

**Comment by davesargrad** [comment]
> Looks like a problem with your install of go: [golang/go#35018](https://github.com/golang/go/issues/35018)

I had seen that issue, and I didnt see anything that helped me in the response to 35018.

I followed a simple set of install instructions as seen here:
https://linuxize.com/post/how-to-install-go-on-centos-7/

So, the install was quite simple, and as the "hello" screenshot shows, go seems to be working.. Can you suggest what the problem might be.

The essence of my install was 

 wget https://dl.google.com/go/go1.13.5.linux-amd64.tar.gz
sudo tar -C /usr/local -xzf go1.13.5.linux-amd64.tar.gz

**Comment by davesargrad** [comment]
I have the following line at end of /etc/profile

export PATH=$PATH:/usr/local/go/bin

**Comment by davesargrad** [comment]
So its hard to imagine that there is a problem with the install unless the 
sudo tar -C /usr/local -xzf go1.13.5.linux-amd64.tar.gz

is not proper

**Comment by aarzilli** [comment]
I'm guessing that you had a previous version of go installed in /usr/local/go and didn't delete it before unpacking the new version. That issue has a 1 line reproducer, does it work for you?

**Comment by davesargrad** [comment]
No.. I never installed go previsouly. This is a relatively pristine centos 7 platform.

What is the 1 line reproducer that i should try?

**Comment by aarzilli** [comment]
```
 err := http.ListenAndServe(":8080", http.FileServer(http.Dir(".")))
```

**Comment by davesargrad** [comment]
I am quite certain that I didnt have go installed. I'm pretty dilligent with the servers I work with. I often strip them down to bare metal and reconfigure. I had done this on the server that I am working with just before the holidays. I'll try that one line reproducer.

**Comment by aarzilli** [comment]
The fact that it's a build error inside a standard library says this is a problem with your install of go.

**Comment by davesargrad** [comment]
import "net/http"

**Comment by davesargrad** [comment]
@aarzilli I certainly hear you.

But this is the extent of the install:
sudo tar -C /usr/local -xzf go1.13.5.linux-amd64.tar.gz

How can the install go wrong?

I'll delete and re-tar

**Comment by davesargrad** [comment]
Ok.. so i've reinstalled.. in the following you see i first deleted /usr/local/go
![image](https://user-images.githubusercontent.com/48793689/71738309-47693900-2e24-11ea-9e2e-52b284e52ad2.png)

**Comment by davesargrad** [comment]
Ok.. i now know the problem.. The problem was that the tar.gz file was in ~/go

I moved it, and it works. So it wasnt a problem with the install. It was a problem with the workspace in GOPATH
