### ISSUE TITLE
missing SetDX method when go getting dlv

### ISSUE THREAD

**Issue by realB12** [go-delve/delve#1811]
Executing
go get -u github.com/derekparker/delve/cmd/dlv
on an up to date Windows 10 Pro machine in a VS Code Terminal with newest version of git and go (1.13) fails with the following errors: 

C:\Users\reneb\go\src\github.com\go-delve\delve\pkg\proc\native\proc.go:165:13: cannot use v (type *Thread) as type proc.Thread in append:
        *Thread does not implement proc.Thread (missing SetDX method)
C:\Users\reneb\go\src\github.com\go-delve\delve\pkg\proc\native\proc.go:173:2: cannot use th (type *Thread) as type proc.Thread in return argument:
        *Thread does not implement proc.Thread (missing SetDX method)
C:\Users\reneb\go\src\github.com\go-delve\delve\pkg\proc\native\proc.go:178:12: cannot use dbp.currentThread (type *Thread) as type proc.Thread in return argument:
        *Thread does not implement proc.Thread (missing SetDX method)
C:\Users\reneb\go\src\github.com\go-delve\delve\pkg\proc\native\proc.go:267:2: cannot use trapthread (type *Thread) as type proc.Thread in return argument:
        *Thread does not implement proc.Thread (missing SetDX method)
C:\Users\reneb\go\src\github.com\go-delve\delve\pkg\proc\native\proc.go:284:40: impossible type assertion:
        *Thread does not implement proc.Thread (missing SetDX method)
C:\Users\reneb\go\src\github.com\go-delve\delve\pkg\proc\native\proc.go:299:22: cannot use thread (type *Thread) as type proc.Thread in argument to proc.GetG:
        *Thread does not implement proc.Thread (missing SetDX method)
C:\Users\reneb\go\src\github.com\go-delve\delve\pkg\proc\native\proc.go:312:43: cannot use dbp.currentThread (type *Thread) as type proc.Thread in argument to proc.GetG:
        *Thread does not implement proc.Thread (missing SetDX method)

Something wrong in delve or on my side ?

**Comment by chainhelen** [comment]
I updates my go version to 1.13 on windows 10 and `go get` is ok. 
Maybe you can remove `C:\Users\reneb\go\src\github.com\go-delve\` and try again (or use `cmd` instead of `VS Code Terminal`).

**Comment by aarzilli** [comment]
It's possible that it's because you are using `github.com/derekparker/delve` instead of `github.com/go-delve/delve`, otherwise try what @chainhelen says. It's something with your install.

**Comment by lovelife-amtf** [comment]
It's possible this version only support  64bit  golang

**Comment by skynet2** [comment]
Same issue during installation for Raspberry PI 3 Model B v1.2 

```
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
```
```
pi@raspberrypi:~ $ go version
go version go1.13.6 linux/arm
```
Install log
```
pi@raspberrypi:~ $ go get -u github.com/go-delve/delve/cmd/dlv
# github.com/go-delve/delve/pkg/proc/native
go/src/github.com/go-delve/delve/pkg/proc/native/proc.go:165:13: cannot use v (type *Thread) as type proc.Thread in append:
        *Thread does not implement proc.Thread (missing SetDX method)
go/src/github.com/go-delve/delve/pkg/proc/native/proc.go:173:2: cannot use th (type *Thread) as type proc.Thread in return argument:
        *Thread does not implement proc.Thread (missing SetDX method)
go/src/github.com/go-delve/delve/pkg/proc/native/proc.go:178:12: cannot use dbp.currentThread (type *Thread) as type proc.Thread in return argument:
        *Thread does not implement proc.Thread (missing SetDX method)
go/src/github.com/go-delve/delve/pkg/proc/native/proc.go:267:2: cannot use trapthread (type *Thread) as type proc.Thread in return argument:
        *Thread does not implement proc.Thread (missing SetDX method)
go/src/github.com/go-delve/delve/pkg/proc/native/proc.go:284:40: impossible type assertion:
        *Thread does not implement proc.Thread (missing SetDX method)
go/src/github.com/go-delve/delve/pkg/proc/native/proc.go:299:22: cannot use thread (type *Thread) as type proc.Thread in argument to proc.GetG:
        *Thread does not implement proc.Thread (missing SetDX method)
go/src/github.com/go-delve/delve/pkg/proc/native/proc.go:312:43: cannot use dbp.currentThread (type *Thread) as type proc.Thread in argument to proc.GetG:
        *Thread does not implement proc.Thread (missing SetDX method)
go/src/github.com/go-delve/delve/pkg/proc/native/threads.go:131:14: t.SetPC undefined (type *Thread has no field or method SetPC)
go/src/github.com/go-delve/delve/pkg/proc/native/threads.go:135:42: cannot use t (type *Thread) as type proc.Thread in argument to bp.CheckCondition:
        *Thread does not implement proc.Thread (missing SetDX method)
go/src/github.com/go-delve/delve/pkg/proc/native/threads.go:137:26: cannot use t (type *Thread) as type proc.Thread in argument to proc.GetG:
        *Thread does not implement proc.Thread (missing SetDX method)
go/src/github.com/go-delve/delve/pkg/proc/native/threads.go:137:26: too many errors
```

**Comment by chainhelen** [comment]
Dlv v1.3.2 (lasted tag) not support linux-arm64, you can try master branch.

**Comment by zogyi** [comment]
@realB12 hey, have you solved this problem, I encountered the same issue when I install the dev tool in VS code(windows 64bit, go version: go1.13.8 windows/386, latest go-delve), thanks.

**Comment by jdu9** [comment]
Same here.

 ```
[user@void ~]$ uname -a
Linux void 5.4.19_1 #1 SMP Wed Feb 12 15:24:37 UTC 2020 ppc64le GNU/Linux
```

```
[user@void ~]$ go version
go version go1.13.8 linux/ppc64le
```

```
[user@void delve]$ make install
go install "-ldflags=-X main.Build=fcba29112560ddbd61d2adbcb3abd88aa20f0911" github.com/go-delve/delve/cmd/dlv
# github.com/go-delve/delve/pkg/proc/native
pkg/proc/native/proc.go:164:13: cannot use v (type *Thread) as type proc.Thread in append:
	*Thread does not implement proc.Thread (missing SetDX method)
pkg/proc/native/proc.go:172:2: cannot use th (type *Thread) as type proc.Thread in return argument:
	*Thread does not implement proc.Thread (missing SetDX method)
pkg/proc/native/proc.go:177:12: cannot use dbp.currentThread (type *Thread) as type proc.Thread in return argument:
	*Thread does not implement proc.Thread (missing SetDX method)
pkg/proc/native/proc.go:265:2: cannot use trapthread (type *Thread) as type proc.Thread in return argument:
	*Thread does not implement proc.Thread (missing SetDX method)
pkg/proc/native/proc.go:275:43: cannot use dbp.currentThread (type *Thread) as type proc.Thread in argument to proc.GetG:
	*Thread does not implement proc.Thread (missing SetDX method)
pkg/proc/native/threads.go:131:14: t.SetPC undefined (type *Thread has no field or method SetPC)
pkg/proc/native/threads.go:135:42: cannot use t (type *Thread) as type proc.Thread in argument to bp.CheckCondition:
	*Thread does not implement proc.Thread (missing SetDX method)
pkg/proc/native/threads.go:137:26: cannot use t (type *Thread) as type proc.Thread in argument to proc.GetG:
	*Thread does not implement proc.Thread (missing SetDX method)
pkg/proc/native/threads.go:167:9: undefined: registers
pkg/proc/native/threads.go:173:10: t.restoreRegisters undefined (type *Thread has no field or method restoreRegisters, but does have RestoreRegisters)
pkg/proc/native/threads.go:173:10: too many errors
exit status 1
make: *** [Makefile:10: install] Error 1
```

**Comment by dlsniper** [comment]
@zogyi/@jdu9 you seem to have Go for Windows 386, not for amd64. Replace your Go installation and try again.

**Comment by jdu9** [comment]
@dlsniper "go version go1.13.8 linux/ppc64le".

**Comment by dlsniper** [comment]
@jdu9 sorry, in your case, that's not supported either, see #1564

**Comment by realB12** [comment]
> I updates my go version to 1.13 on windows 10 and `go get` is ok.
> Maybe you can remove `C:\Users\reneb\go\src\github.com\go-delve\` and try again (or use `cmd` instead of `VS Code Terminal`).

Done that: same result

**Comment by realB12** [comment]
> @realB12 hey, have you solved this problem, I encountered the same issue when I installed the dev tool in VS code(windows 64bit, go1.13.8 windows/386, latest go-delve), thanks.

No, still have the same problem: 
Im on a most updated Windows 10 64-Bit i386 Machine with latest version of Go (v1.13.4) an no other issues than this one. Can it be that with Go Version 13 default is Module-Mode and no longer GOPATH mode and delve not yet "fit" on this?

**Comment by dlsniper** [comment]
@realB12 Please see my comment here: https://blog.jetbrains.com/go/2019/02/06/debugging-with-goland-getting-started/#comment-20789

**Comment by realB12** [comment]
Issue solved for me: 
Solution: Uninstall the i386/32Bit Go version and Install the newest amd64/64-bit version!

Problem was due to 32Bit Go installation rather than 64Bit!
(I have accidently installed the i386 = 32-Bit Go Version when upgrading go to the newest 1.13.4 version. The dumb person I am, I have taken i386 for Intel (I am running on Intel Processors) and amd64 for AMD Processors assuming that both are 64Bit per default - so - shame on me! ). 

So for me - having a 64Bit machine - the problem is solved for me. 
However it seems that 32-Bit is not or no longer supported as mentioned by other Issues here already.
