### ISSUE TITLE
The version of golang in the go.mod is error

### ISSUE THREAD

**Issue by xieyuanhuata** [go-delve/delve#1813]
Go Modules is a feature since go1.11 , but :
module github.com/go-delve/delve

go 1.10

**Comment by aarzilli** [comment]
I don't see why this would be a problem.

**Comment by chainhelen** [comment]
@xieyuanhuata 
You should follow the [rule](https://github.com/go-delve/delve/blob/master/CONTRIBUTING.md#filing-issues) for resolving issues quickly..

**Comment by derekparker** [comment]
Technically not a bug, however in our CI we only test back to Go 1.11. I don't think it would hurt anything to bump the required Go version to 1.11.
