### ISSUE TITLE
input/output error when setting a breakpoint in some cases 

### ISSUE THREAD

**Issue by chainhelen** [go-delve/delve#1817]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)? 
master(059c51e)  

2. What version of Go are you using? (`go version`)?  
go version go1.12.5 linux/amd64

3. What operating system and processor architecture are you using?
Ubuntu 18.04.2 LTS  
Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz  

4. What did you do?  
set breakpoint 
```
// t6.go
        package main
        
        import (
        	"fmt"
        	"unsafe"
        	"runtime"
        )
        
        func main() {
        	l := int(51)
        	bs := make([]byte, l)
        	for i := 0; i < l; i++ {
        		bs[i] = byte(i + int(10))
        	}
        
16 ==>  	p := uintptr(unsafe.Pointer(&bs))
        
        	fmt.Println(p)
        
        	bs[0] = 254
        
        	runtime.KeepAlive(bs)
        }
```
`dlv debug t6.go`  and type `b t6.go:16`  

5. What did you expect to see?  
`Breakpoint 1 set at...` successed  Or `Command failed: could not find statement` failed

6. What did you see instead?  
`Command failed: input/output error`   

-----
This is becase [bininfo.go#L358](https://github.com/go-delve/delve/blob/059c51ea0caf6cba882f248284c52245423a14c6/pkg/proc/bininfo.go#L358) get one nonzero `pc`, but [bininfo.go#L390](https://github.com/go-delve/delve/blob/059c51ea0caf6cba882f248284c52245423a14c6/pkg/proc/bininfo.go#L390)`appendLineToPCIn` doesn't append it. Actually the essential difference is the judgemet about `isStmt` of `StateMachine` between  [LineToPC](https://github.com/go-delve/delve/blob/059c51ea0caf6cba882f248284c52245423a14c6/pkg/dwarf/line/state_machine.go#L272) and [LineToPCIn](https://github.com/go-delve/delve/blob/059c51ea0caf6cba882f248284c52245423a14c6/pkg/dwarf/line/state_machine.go#L306).  (It is involved in ##1717.) 

I not sure whether the compiler with `-gcflag="all=-N -l"` doesn't write any `lineentry` with `isstmt` being true for `16th line` is correct or not ? (I need more time to check it because my current weak ability). 

But I think I can add one pr 
```
	if len(pcs) == 0 {
		return []uint64{pc}, nil
	}
```
and one testcase to ensure backward compatibility.

**Comment by aaron-sysdig** [comment]
this issue occurred for me on M1 mac because the GOARCH flag was set to amd64, changing it to arm64 fixed the issue
