### ISSUE TITLE
I want to debug Remote's Server's Go Program on my Local Win 10 with Goland, it doesn't work

### ISSUE THREAD

**Issue by cw4t** [go-delve/delve#1819]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
1.3.2
2. What version of Go are you using? (`go version`)?
go version go1.13.4 linux/amd64
3. What operating system and processor architecture are you using?
Local: Win 10, Remote Server: Centos7, x86_64, GNU/Linux, 
4. What did you do?
I want to Use Goland to debug the Centos's Go Program with delve, but it failed!
5. What did you expect to see?
Codes that can be debug on my Local win10 with GoLand
6. What did you see instead?
nothing

**Comment by chainhelen** [comment]
Maybe you should open one issue for  goland community first. 

But you can try `dlv connect [remote ip:port] --log --log-output=rpc`, and see what client output.

**Comment by cw4t** [comment]
![1](https://user-images.githubusercontent.com/15030650/72055554-fff01a80-3305-11ea-98ef-8e5507674916.PNG)
as above

**Comment by cw4t** [comment]
> Maybe you should open one issue for goland community first.
> 
> But you can try `dlv connect [remote ip:port] --log --log-output=rpc`, and see what client output.

![Uploading 1.PNG…]()

**Comment by cw4t** [comment]
see issue 1820 Please..

**Comment by cw4t** [comment]
Oh, still can reply, then it's ok, I made fault that close this issue...

**Comment by chainhelen** [comment]
@cw4t how about any other operations , for example set breakpoint or list source file. [cli](https://github.com/go-delve/delve/tree/master/Documentation/cli).   

If output is ok,  it means nothing about delve.

**Comment by cw4t** [comment]
Yeah , sees like nothing about delve, maybe I should find GoLand or Go for help, Thanks

**Comment by dlsniper** [comment]
You can use our issue tracker and report the problem: https://youtrack.jetbrains.com/issues/Go Please include steps to reproduce it.

**Comment by cw4t** [comment]
> You can use our issue tracker and report the problem: https://youtrack.jetbrains.com/issues/Go Please include steps to reproduce it.

Thank you, I have report this problem through the link.

**Comment by aarzilli** [comment]
cc @dlsniper

**Comment by derekparker** [comment]
Closing this for now until it is shown to be a problem on our end.
