### ISSUE TITLE
Breakpoint / Tracepoint autocompletion

### ISSUE THREAD

**Issue by quarnster** [go-delve/delve#183]
For example `break Test<tab>` should list all the functions starting with Test or complete to the single function starting with Test if there's only one available.

**Comment by ahakanbaba** [comment]
+1 to the autocompletion. 
The tab autocompletion is super productivity enhancer.

**Comment by jinleileiking** [comment]
+1 to the autocompletion.
The tab autocompletion is super productivity enhancer.

**Comment by derekparker** [comment]
Closing as this as been resolved.
