### ISSUE TITLE
Ubuntu - Command 'dlv' not found

### ISSUE THREAD

**Issue by ankur0101** [go-delve/delve#1831]
I referred to documentation available at https://github.com/go-delve/delve/blob/master/Documentation/installation/linux/install.md

1. What version of Delve are you using (`dlv version`)?
Error **Command 'dlv' not found** appears when I write **dlv** in console
2. What version of Go are you using? (`go version`)?
go version go1.13.6 linux/amd64
3. What operating system and processor architecture are you using?
Ubuntu 64bit
4. What did you do?
I ran command dlv in console
5. What did you expect to see?
Some options showing parameters for dlv
6. What did you see instead?
![image](https://user-images.githubusercontent.com/2085372/72407954-4a025180-3787-11ea-97b7-66d82365dd39.png)

Following are path set for $GOPATH & $GOROOT
![image](https://user-images.githubusercontent.com/2085372/72408073-a8c7cb00-3787-11ea-90e3-c933eb42772d.png)

Am I missing anything?

**Comment by chainhelen** [comment]
@ankur0101 I aslo use ubuntu.  There is any error or other output information when you type `make install` ? 
Just like below 

![image](https://user-images.githubusercontent.com/7046329/72410271-fd2c7400-37a2-11ea-8d5a-0fde35ae83b9.png)

**Comment by ankur0101** [comment]
Just now I solved it, an env variable was missing:

**export PATH=$GOPATH/bin:$PATH**

@chainhelen I received the same response you have in place. Fire above line in console and add the same in /etc/profiles

**Comment by RyanMcNamara86** [comment]
This issue should not have been closed since the installation instructions are still incorrect.

**Comment by msscaroso** [comment]
I am new to go and I did the same mistake. This issue helped me

**Comment by mezorian** [comment]
Same here

**Comment by iSobiX** [comment]
I had such a problem when installing delve for َbuntu 22.; And adding these statements to PATH solved my problem:
`export PATH="$PATH:/usr/local/go/bin"`
`export GOPATH=$HOME/go`
`export PATH=$GOPATH/bin:$PATH`

**Comment by iSobiX** [comment]
I had such a problem when installing delve for َbuntu 22.; And adding these statements to PATH solved my problem:
`export GOPATH=$HOME/go`
`export PATH=$GOPATH/bin:$PATH`

**Comment by iSobiX** [comment]
I had such a problem when installing delve for Ubuntu 22; and adding these statements to PATH solved my problem:
`export GOPATH=$HOME/go`
`export PATH=$GOPATH/bin:$PATH`

**Comment by kosimas** [comment]
> 

This fixed my problem. I also think there should be a hint in the installation instructions.
