### ISSUE TITLE
Gitter chat link is dead

### ISSUE THREAD

**Issue by epelc** [go-delve/delve#1842]
The link to gitter chat from readme is a 404

https://gitter.im/go-delve/delve?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

![image](https://user-images.githubusercontent.com/5204642/72741781-5535f280-3b76-11ea-9803-374b29a39212.png)

**Comment by chainhelen** [comment]
@epelc Yes, the gitter chat link of readme is invalid. 
You can open this [link](https://gitter.im/derekparker/delve?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
