### ISSUE TITLE
close "ALSR" to make debug convenient

### ISSUE THREAD

**Issue by hengwu0** [go-delve/delve#1847]
I checked and find delve Do Not Close Address Space Layout Randomization(ALSR) when debugging. It made us hard to locate the problems when randomization of  debuggee's virtual address space is on. So, i think it needs to be enhanced(like GDB already seted ASLR closed by default).

**Comment by aarzilli** [comment]
Go binaries are not position independent by default so ASLR doesn't do anything for them. Goroutine stack are allocated on the heap and I don't think there's a way to disable randomization of heap addresses (it would require deterministic scheduling of goroutines).

**Comment by hengwu0** [comment]
Ofcourse go-binaries have ALSR. It's kernel feature! All __dynamically linked__ binaries have ALSR.

**Comment by aarzilli** [comment]
Sorry this got forgotten. Go binaries are statically linked, go does not produce PIE by default. The address space you are seeing is from go's malloc and can not be turned off.

**Comment by hengwu0** [comment]
> Go binaries are statically linked, go does not produce PIE by default.

If using CGO, then go binaries are dynamically linked. And there also have `-linkshared` param in go.

**Comment by aarzilli** [comment]
They still aren't PIE and I don't even know if linkshared works with delve.

**Comment by hengwu0** [comment]
> They still aren't PIE and I don't even know if linkshared works with delve.

 All dynamically linked binaries have ALSR, no matter with PIE.
