### ISSUE TITLE
Cannot set breakpoint with go1.14beta1 on windows

### ISSUE THREAD

**Issue by nd** [go-delve/delve#1855]
1. What version of Delve are you using (`dlv version`)?

```
Delve Debugger
Version: 1.3.2
Build: bc9d95d615987ae78b946dd18ef1989775c705e8
```

2. What version of Go are you using? (`go version`)?

```
go version go1.14beta1 windows/amd64
```

3. What operating system and processor architecture are you using?

windows/amd64

4. What did you do?

Debug the program (with go version check disabled):

```
package main

func main() {
	println("ok")
}

```

and try to set a breakpoint at line 4 via the `b main.go:4` command.

5. What did you expect to see?

Breakpoint set

6. What did you see instead?

Command fails with an error:

```
Location main.go:4 ambiguous: c:/Path/to/main.go, C:\Path\to\main.go
```

Running the `sources` command also shows 2 paths different only in a path separator. Trying to set breakpoint using a full path fails as well.

**Comment by aarzilli** [comment]
[Support for Go 1.14](https://github.com/go-delve/delve/pull/1727) hasn't been merged in yet. This thing in particular was [a bug in Go](https://github.com/golang/go/issues/36495) which would be fixed if you had built from master but regardless delve 1.3.0 will be seriously broken with go 1.14.

**Comment by derekparker** [comment]
Now that support for Go 1.14 has been merged, we can close this. Please reopen if this is still an issue.
