### ISSUE TITLE
testing: should "make test" use the same flags as CI?

### ISSUE THREAD

**Issue by eliben** [go-delve/delve#1862]
In tip Delve, Travis runs builds/tests with `GOFLAGS=-mod=vendor`.

But "make test" does not. When a dependency is added or changed in `go.mod`, "make test" will pass but then Travis will break.

Would it make sense for "make test" to run with `GOFLAGS=-mod=vendor` as well?

Alternatively, is the introduction of `GOPROXY` affecting the decision to keep using a `vendor` directory in any way?

**Comment by aarzilli** [comment]
I'd like to keep the vendor directory, I think repositories should be self contained and I think that we should test that what we have in vendor works (although that's less of a priority now that go itself checks the integrity of the vendor directory, to some extent).

I don't have strong feelings either for or against adding GOFLAGS=-mod=vendor to make.go. One argument against is that adding a temporary replace directive to go.mod to test something is harder when -mod=vendor is involved.

Maybe we should just have a better way to check that go.mod and vendor match.
