### ISSUE TITLE
RPC error when waiting for remote debugger

### ISSUE THREAD

**Issue by Djolivald** [go-delve/delve#1868]
With Headless dlv, I instantly get a protobuff error while waiting for the remote debugger to connect. If I'm quick enough to start the remote debugger, it may continue without error.

1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.4.0
Build: $Id: 67422e6f7148fa1efa0eac1423ab5594b223d93b $
2. What version of Go are you using? (`go version`)?
1.13
3. What operating system and processor architecture are you using?
App on docker (alpine:latest), from windows 10
4. What did you do?
Launch my debug app via docker, dockerfile:
```Dockerfile
ARG GO_VERSION=1.13

# API builder
FROM golang:${GO_VERSION}-alpine AS builder
ENV CGO_ENABLED 0

RUN apk update && apk add alpine-sdk git && rm -rf /var/cache/apk/*
RUN go get github.com/derekparker/delve/cmd/dlv

RUN mkdir -p /api
WORKDIR /api

COPY src/go.mod .
COPY src/go.sum .

RUN go mod download

COPY src/ .

RUN mkdir /api/app && go build -gcflags "all=-N -l" -o /api/app ./...

# Runner
FROM alpine:latest
RUN apk update && apk add ca-certificates libc6-compat && rm -rf /var/cache/apk/*

RUN mkdir -p /api
WORKDIR /api

COPY --from=builder /api/app/my_app .
COPY --from=builder /go/bin/dlv /
COPY resources/config/config_dev.yml .

ENV CONFIG_FILE config_dev
ENV CONFIG_TYPE yaml
RUN /dlv version
EXPOSE 8080 40000
CMD ["/dlv", "--listen=:40000", "--log", "--headless=true", "--api-version=2", "exec", "/api/my_app"]
```
5. What did you expect to see?
I expected dlv to wait for remote debugger connection
`API server listening at: [::]:40000`
6. What did you see instead?
```
API server listening at: [::]:40000
2020-02-18T10:16:29Z info layer=debugger launching process with args: [/api/my_app]
2020-02-18T10:16:29Z error layer=rpc rpc:invalid character 'H' looking for beginning of value
```

**Comment by aarzilli** [comment]
You have something that connects to port 40000 and sends some sort of request, probably an HTTP client.

**Comment by Djolivald** [comment]
Hun... Alright... weirdly enough, when I start my container, docker is making the requests to `:40000`...

**Comment by Djolivald** [comment]
For some reason it has to do with the location of the dockerfile/docker-compose relative to the go app. If the docker files are outside the app root (higher than `main.go`) I have this issue.
I have absolutely no clue why, I'll leave it to it for now.
