### ISSUE TITLE
Cannot call method of non-struct type

### ISSUE THREAD

**Issue by ear7h** [go-delve/delve#1870]
1. What version of Delve are you using (`dlv version`)?

```txt
Delve Debugger
Version: 1.4.0
Build: $Id: 67422e6f7148fa1efa0eac1423ab5594b223d93b $
```

2. What version of Go are you using? (`go version`)?

```
go version go1.13 darwin/amd64
```

3. What operating system and processor architecture are you using?

```
Darwin 18.7.0 x86_64
```

4. What did you do?
Ran `dlv debug main.go --init dlvscript.txt`
```go
// main.go
package main

type X int

func (_ X) M() {
	print("in X.M")
}

func main() {
	var x X
	x.M() // LINE 12
}
```

```
p "dlvscript.txt"
b main.go:12
c
call x.M()
```

5. What did you expect to see?

```
...
in X.M
```

6. What did you see instead?
```
...
dlvscript.txt:4: x (type main.X) is not a struct
```

**Comment by ear7h** [comment]
I have done some debugging for this with `dlv debug $GOPATH/src/github.com/go-delve/delve/cmd/dlv -- debug main.go --init dlvscript.txt`, you can see the log in [this gist](https://gist.github.com/ear7h/f07da14eb6bd25bbe18b7788e7505864). The stack trace led me to think that part of the problem is the `findMethod` call in this function:

https://github.com/go-delve/delve/blob/8db632e55b6a5156b5698d3c3b5ab74c405d9d63/pkg/proc/eval.go#L1038-L1052

I don't know much about this program but semantically, the method should be found before reaching the `structMember` call. After further debugging down this route, the core of the problem looks to be here:

https://github.com/go-delve/delve/blob/8db632e55b6a5156b5698d3c3b5ab74c405d9d63/pkg/proc/eval.go#L1825

Despite `X` being a user defined type, the variable's type is being set as a `*godwarf.IntType`:

```
list
> github.com/go-delve/delve/pkg/proc.(*Variable).findMethod() ./lib/go/src/github.com/go-delve/delve/pkg/proc/eval.go:1826 (PC: 0x142a2b2)
  1821:		if isptr {
  1822:			typ = ptyp.Type
  1823:		}
  1824:	
  1825:		if _, istypedef := typ.(*godwarf.TypedefType); !istypedef {
=>1826:			return nil, nil
  1827:		}
  1828:	
  1829:		typePath := typ.Common().Name
  1830:		dot := strings.LastIndex(typePath, ".")
  1831:		if dot < 0 {
(dlv) whatis typ
github.com/go-delve/delve/pkg/dwarf/godwarf.Type
Concrete type: *github.com/go-delve/delve/pkg/dwarf/godwarf.IntType
```

At this point, I'm not sure what *should* be happening. If the maintainers could direct me, I can submit a PR for this :)

**Comment by ear7h** [comment]
Additionally, I tried simply removing the guard in `eval.go:1825` as a workaround and there was a panic at the following line:

https://github.com/go-delve/delve/blob/8db632e55b6a5156b5698d3c3b5ab74c405d9d63/pkg/proc/eval.go#L1947

This was because method `M` was defined with `_` as the receiver.

```go
func (_ X) M()
```

Changing the method definition to the followin worked as expected.

```go
func (x X) M()
```

**Comment by derekparker** [comment]
@ear7h thanks for reporting this. There are some limitations still to how function calls work, but I investigated this and have a patch which fixes your issue and allows a method call on non-struct types which also do not have a receiver (well, technically _do_ have one but it isn't passed in as a formal parameter).

I'll be posting the patch soon and you can let me know if it adequately fixes and addresses your use case.

**Comment by aarzilli** [comment]
Fixed by related commit.
