### ISSUE TITLE
Transparent middleware mode

### ISSUE THREAD

**Issue by sylr** [go-delve/delve#1880]
I'm wondering if we could have a mode where delve could act as a transparent middleware so that we could use delve to debug go processes launched by wrappers.

My use case is debugging https://github.com/hashicorp/terraform providers.

Terraform is using a grpc plugins (providers) mechanism.

 - terraform launch the terraform provider as a child process
 - terraform provider writes messages to stdout to tell terraform what unix socket they should use to communicate
 - terraform and the provider communicates via grpc using the previsouly mentionned unix socket

The original process tree looks like this (on MacOS)

```
 | |     \-+= 71949 s.rabot terraform plan
 | |       \-+- 71952 s.rabot /Users/s.rabot/go/bin/terraform-provider-azurerm
```

What I'm trying to do is insert delve in the middle so that I can debug the provider.

I managed to tweak terraform to launch its provider **with delve in the middle**.

```
 | |     \-+= 72120 s.rabot terraform plan
 | |       \-+- 72122 s.rabot /Users/s.rabot/go/bin/dlv exec --headless --listen=127.0.0.1:2346 --api-version=2 -- /Users/s.rabot/go/bin/terraform-provider-azurerm
 | |         \-+= 72123 s.rabot /Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver --stdio-path /dev/tty -F -R 127.0.0.1:53363 -- /Users/s.rabot/go/bin/terraform-provider-azurerm
 | |           \--- 72124 s.rabot /Users/s.rabot/go/bin/terraform-provider-azurerm
```

So far so good but there are still a problem with standard inputs and outputs. I did not manage with the options to make delve forward `stdin` & `stdout` correctly between the father and the child.

What I would need is a mode where :

- father stdout -> delve stdin -> child stdin 
- child stdout -> delve stdout -> father
- child stderr -> delve stderr -> father
- delve logging into /dev/console or /dev/tty 

Regards.

**Comment by aarzilli** [comment]
You should use `--headless` and `--log-dest` to redirect delve's logs, I suspect your only problem is that the "API listening" message is disrupting the communication between terraform and the plugin and `--log-dest` will move that message out of stdout and somewhere else.

**Comment by sylr** [comment]
Hi @aarzilli  :wave:

I've tried that but it does not work. I even recompiled delve with the "API listening" message removed.

The terraform providers messages ends up in my terminal instead of being forwarded to the father process.

I'm wondering if it is not because of this ` --stdio-path /dev/tty -F -R 127.0.0.1:53363` (see the 2nd process tree I pasted above).

**Comment by aarzilli** [comment]
It could be, you could try replacing it with `--stdin-path /dev/stdin --stdout-path /dev/stdout --stderr-path /dev/stderr`. It's in pkg/proc/gdbserial/gdbserver.go.

**Comment by sylr** [comment]
:+1: Thanks I'll try that

**Comment by aarzilli** [comment]
Closing, inactive.
