### ISSUE TITLE
[Question] How can I debug test binary with optimization turned off?

### ISSUE THREAD

**Issue by chendave** [go-delve/delve#1893]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)? 1.3.2
2. What version of Go are you using? (`go version`)? go version go1.13.4 linux/amd64
3. What operating system and processor architecture are you using?
4. What did you do?
`go test -c -o "perf.test"`
 and then debug with 
`dlv exec ./perf.test -- ...`

try  below but doesn't work,
`go test -gcflags="all=-N -l" -c -o "perf.test"`

5. What did you expect to see?
6. What did you see instead?
some method report "Warning: debugging optimized function"

**Comment by chainhelen** [comment]
`go test -gcflags="all=-N -l" -c -o "perf.test"` is without optimization .
@chendave Which compile unit that the warns that you met belong to?

**Comment by chainhelen** [comment]
`go test -gcflags="all=-N -l" -c -o "perf.test"` is without optimization .
@chendave Which compile unit that the warns that you met belong to?

**Comment by chendave** [comment]
@chainhelen thank you for your promptly response, but I don't understand what's the "compile unit" you mean here?

**Comment by chendave** [comment]
hey, here is more information,
source code is here,
`https://github.com/chendave/kubernetes/tree/sche_perf_master_backup/test/integration/scheduler_perf`

under that dir, run below command to generate test binary
`go test -gcflags="all=-N -l" -c -o "perf.test"`
and launch debug process, 
`dlv exec ./perf.test -- -test.bench=. -test.run=BenchmarkExtraSchedulingSecrets -test.cpuprofile=prof.out -test.short=false
break pkg/server/genericapiserver.go:428`
step in util apiserver/pkg/server/genericapiserver.go:556
and you will see warning here, and debug returned.
Warning: debugging optimized function
Values returned:
        ~r2: k8s.io/kube-openapi/pkg/util/proto.Models nil
        ~r3: error (unreadable unknown or unsupported kind: "invalid")

since the test binary is too large (124M), cannot find a suitable place to upload, could you pls kindly built it locally?

**Comment by chainhelen** [comment]
In general, `compile unit` mean `package` .

**Comment by chendave** [comment]
Thanks sir!  Does my previous comments include the info you want?

**Comment by chainhelen** [comment]
@chendave 
I did not reproduct the warning. 

1.
Make generated_files and install etcd first for preparation.
Then I set breakpoint at genericapiserver.go:428 and step into.

```
   550:	func (s *GenericAPIServer) getOpenAPIModels(apiPrefix string, apiGroupInfos ...*APIGroupInfo) (openapiproto.Models, error) {
   551:		if s.openAPIConfig == nil {
=> 552:			return nil, nil
   553:		}
   554:		pathsToIgnore := openapiutil.NewTrie(s.openAPIConfig.IgnorePrefixes)
   555:		resourceNames := make([]string, 0)
   556:		for _, apiGroupInfo := range apiGroupInfos {

```
It hit line 552, not 556 that you say. (There is any config?) 

when I stepout, 
```
Values returned:
	~r2: k8s.io/kube-openapi/pkg/util/proto.Models nil
	~r3: error nil
``` 
without warns.  

---

2. 
Then I get the AttrProducer of this package (k8s.io/apiserver/pkg/server) from binary is `Go cmd/compile go1.13.4; -N -l`, so this mean compiler do it without optimization .

**Comment by chendave** [comment]
thank you, there is nothing else I configured, I think return from Line552 should be right.  But I do see those warning message and errors.

Warning: debugging optimized function
...
~r3: error (unreadable unknown or unsupported kind: "invalid")

**Comment by aarzilli** [comment]
If you are using linux can you run `objdump --dwarf temp/test | grep -A2 "DW_TAG_compile_unit\|DW_AT_producer"` and see what the output is? If you did specify the command line options correctly the DW_AT_producer line should say: `Go cmd/compile go1.13.4; -N -l` for almost all packages (except runtime).

**Comment by chendave** [comment]
I am so sorry! 
Seems like "-N" is not turned on. Not sure what the hell I was doing.
```
# objdump --dwarf ./perf.test | grep -A2 "DW_TAG_compile_unit\|DW_AT_producer"
...
    <1cd66eb>   DW_AT_producer    : Go cmd/compile go1.13.4; -l
```
Recompiled the test binary with "-N" turned on, everything is good!

**Comment by chendave** [comment]
thank you! @chainhelen  @aarzilli
