### ISSUE TITLE
Use dlv to debug openlambda executable

### ISSUE THREAD

**Issue by GindaChen** [go-delve/delve#1900]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?

```
Delve Debugger
Version: 1.4.0
Build: $Id: 67422e6f7148fa1efa0eac1423ab5594b223d93b $
```

2. What version of Go are you using? (`go version`)?
`go version go1.12.5 linux/amd64`

3. What operating system and processor architecture are you using?
`Linux node0.olfs.zygoteoptimizer-pg0.wisc.cloudlab.us 4.4.0-173-generic #203-Ubuntu SMP Wed Jan 15 02:55:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

4. What did you do?

I would like to use `dlv` to debug my [open-labmda](https://github.com/open-lambda/open-lambda) executable. I did:

```
# Install the dependency according to script 
# https://github.com/open-lambda/testing/blob/master/dev-build/bootstrap2.sh
$ git clone https://github.com/open-lambda/open-lambda.git
$ cd open-lambda
$ make ol
$ dlv exec ol worker
Type 'help' for list of commands.
(dlv) l
Stopped at: 0x7f55c9558c30
=>no source available
```

Then my `list` failed with `no source available`.

Note that the `open-lambda` executable `ol` is built with the command
```
go build -mod vendor -o ../ol
```
and if a GOPATH is specified during the build it could fail, for example
```
$ GOPATH="/root/open-lambda" go build -mod vendor -o ../ol
build flag -mod=vendor only valid when using modules
```

5. What did you expect to see?

See the `list`-ed command and debug the file.

6. What did you see instead?

```
$ open-lambda dlv exec ol worker
Type 'help' for list of commands.
(dlv) l
Stopped at: 0x7f55c9558c30
=>no source available
```

**Comment by chainhelen** [comment]
I have check. 

open-labmda  is not pure go (/src/sandbox/forkRequest.go),  so it enter one place where has no  source file first. See #935 for detail.

But don't worry this, set breakpoint at where you are interesting directly, then continue.

-----
ps :

If you want a better experience, use
```
go build -mod vendor -gcflags="all=-N -l" -o ../ol
```
and (because cgo and just development environment)
```
 sudo sh -c "echo 0 > /proc/sys/kernel/randomize_va_space"
```

**Comment by GindaChen** [comment]
Thanks! Just a followup, if I would like to connect to VSCode, what would be the best command to run?

**Comment by chainhelen** [comment]
Sorry, to be honest, I never use vscode to debug go.  Maybe other can tell you.   

But I see [vscode-go](https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code),  any one of the three modes `debug` `remote` `exec` looks OK.

**Comment by GindaChen** [comment]
Thanks again!
