### ISSUE TITLE
Turn off asyncpreempt on MacOS

### ISSUE THREAD

**Issue by derekparker** [go-delve/delve#1905]
Running a binary built with Go 1.14 and the async preemption causes significant slowdown on MacOS (see https://github.com/golang/go/issues/37528). We already disable this by default on Windows, so I don't think it would hurt to also disable on MacOS.

**Comment by dr2chase** [comment]
Do you know anything about the root cause here?  There's another signal-related bug on MacOS (having to do with floating point registers not being marked clean on return from signal handler -- something a debugger might also care about).

**Comment by Cyberax** [comment]
I _think_ this might have something to do with somewhat unusual stack arrangement. The reproduction case creates an array of slices into a large array. As far as I remember, asyncpreempt treats stack conservatively during GC pauses which would cause a lot of unnecessary work

I've tested this hypothesis by running with GOGC=off and it indeed fixes the issue:
```
cyberax@CybMac:~/aurora/bug$ ./repro.sh
Elapsed 4 ms
Type 'help' for list of commands.
Elapsed 7 ms
Process 7323 has exited with status 0
exit
```

**Comment by aarzilli** [comment]
> Do you know anything about the root cause here?

Without looking: signals get sent to debugserver which sends them to us, we send them back to debugserver which sends them to the target process. A certain amount of slowdown is inevitable, we might be slow at parsing messages from debugserver and responding and debugserver might do something slow with signal handling on top of that.

**Comment by aarzilli** [comment]
Taken a look, there's an optimization opportunity that we are not taking with calling jThreadsInfo instead of qThreadStopInfo but it doesn't make a whole lot of difference. Apart from that there is nothing especially wrong with the code, most of the time is spent doing syscalls to send commands to debugserver and reading responses.
