### ISSUE TITLE
Multi-goroutine debugging hit breakpoint question

### ISSUE THREAD

**Issue by hawkwzh** [go-delve/delve#1923]
HI:
 There is  a  question when i debugging multi-goroutine code.

```
func main() {
	go p("1") // g1
	go p("2") //g2
	go p("3") //g3
	go p("4") //g4
	w := sync.WaitGroup{}
	w.Add(1)
	w.Wait()
}

func p(s string) {
	for {
		fmt.Println(s)
		if "1" == s {
			fmt.Println("break") // breakpoint here
		}
	}
}
```
All goroutines is paused when  hit the breakpoint .

I think the goroutine pause triggered by breakpoint hit should only work on "g1" and others should be kept running.

please check it 

THANKS.

**Comment by chainhelen** [comment]
1. Not sure "g1" run, could be any one of four goroutines. It depends on runtime schedule of go.
2. Not support stopping a single goroutine at present, please see [1529](https://github.com/go-delve/delve/issues/1529). This depends on upstream(golang) ability.

**Comment by hawkwzh** [comment]
@chainhelen 
Thanks for reply. It's very helpful.
:)

**Comment by hawkwzh** [comment]
Maybe other one have different opinions.

**Comment by aarzilli** [comment]
What @chainhelen said is correct, we don't support any kind of non-stop debugging and the breakpoint won't necessarily hit g1 first.

**Comment by derekparker** [comment]
What the others said.

If you have any identifier for each goroutine you could set a conditional breakpoint.

**Comment by hawkwzh** [comment]
@aarzilli @derekparker 
Thanks for reply. It's very helpful.
