### ISSUE TITLE
Doesn't exit when binary fails with exit code 1

### ISSUE THREAD

**Issue by mingrammer** [go-delve/delve#1929]
1. What version of Delve are you using (`dlv version`)?

> Delve Debugger
> Version: 1.3.2
> Build: $Id: 569ccbd514fc47c8b4c521b142556867ec5e6917 $

2. What version of Go are you using? (`go version`)?

> go version go1.14 darwin/amd64

3. What operating system and processor architecture are you using?

`Darwin me-mbp.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64`

4. What did you do?

`dlv --listen=:2346 --headless=true --api-version=2 --accept-multiclient --check-go-version=false exec mybinary run --continue`

And `mybinary run` failed due to local database was not running.

5. What did you expect to see?

The program failure is not a real problem. It is my issue. However, in this case, I expected the debug process would be closed due to the `mybinary run` exited with exit code 1. But it didn't.

I think the debug process should be exited when binary program run fails. (exits)

6. What did you see instead?

```
API server listening at: [::]:2346
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1100.0.30..1
 for x86_64.
Got a connection, launched process karrotauth (pid = 85159).
{"level":"warn","time":"2020-03-14T17:38:52+09:00","message":"monitor: tracking is not enabled"}
{"level":"warn","time":"2020-03-14T17:38:52+09:00","message":"monitor: tracing is not enabled"}
{"level":"fatal","error":"db: failed to ping postgres: failed to connect to `host=localhost user=postgres database=dev`: dial error (dial tcp 127.0.0.1:5433: connect: connection refused)","time":"2020-03-14T17:38:52+09:00","message":"grpc: failed to initialize the db"}
Exiting.

```

Then hangs, so debug process never ends.

**Comment by chainhelen** [comment]
No exit and you can `dlv connect` then `quit` .
Even `restart` for a new round of debugging, it depend on user.  

But maybe it need to be written into FAQ.

**Comment by aarzilli** [comment]
This is how it works by design.

**Comment by ocket8888** [comment]
There should be a way to force delve to exit when the process being debugged exits, e.g. `--quit-on-exit`. Right now, I have to do
```bash
trap 'docker exec container_name ps | grep dlv | tr -s " " | cut -d " " -f1 | xargs docker exec container_name kill' INT;
```
in my bash functions that start a debugging session with a binary in a container, which still isn't ideal because I have to <kbd>CTRL</kbd>+<kbd>C</kbd> to get the process to stop, and users will probably expect `SIGINT` to break out of the running function (which is bad because it leaves the debugging open and bound to a port - even if I wanted to automate selecting an open port, that would cause port leakage).

**Comment by maelvls** [comment]
From what I observed, the culprit is `--accept-multiclient`. Delve doesn't seem to want to stop after the binary stops in multi-client mode.

With `--accept-multiclient=false`, the Delve session properly stops after the binary exits.
