### ISSUE TITLE
Still can't install on ARM

### ISSUE THREAD

**Issue by kevindtimm** [go-delve/delve#1933]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)? latest
2. What version of Go are you using? (`go version`)? 1.14
3. What operating system and processor architecture are you using? raspbian armv7l
4. What did you do? go get and then make install
5. What did you expect to see? delve installed
6. What did you see instead? found packages native (proc.go) and your_operating_system_and_architecture_combination_is_not_supported_by_delve (support_sentinel.go) in /home/pi/go/src/github.com/go-delve/delve/pkg/proc/native

I suspect I have to make a change to my architecture but don't know what it should be. When I run 

If I do:
export GOARCH=arm64 make install
I get
fork/exec /tmp/go-build292453166/b001/exe/make: exec format error
make: *** [Makefile:10: install] Error 1

**Comment by chainhelen** [comment]
Armv7l is 32bit, delve only support 64bit for ARM linux at present.

**Comment by aarzilli** [comment]
Closing, what @chainhelen said.

**Comment by kevindtimm** [comment]
Isn't the RPI 4 a 64 bit processor?

**Comment by dlsniper** [comment]
@kevindtimm it is, but Raspbian, the default OS, is still 32bit.

You can use something like Ubuntu Server for getting a proper 64bit OS on it (note, there are alternatives out there like Balena OS, Majaro, Gentoo).  I wrote this article on [getting GoLand to work on a Raspberry Pi 4](https://blog.jetbrains.com/go/2020/02/18/running-goland-on-a-raspberry-pi-4/), but it should give you some insights into running other software on it as well. Delve setup is included in the process. Maybe that helps.

**Comment by kevindtimm** [comment]
> @kevindtimm it is, but Raspbian, the default OS, is still 32bit.
> 
> You can use something like Ubuntu Server for getting a proper 64bit OS on it (note, there are alternatives out there like Balena OS, Majaro, Gentoo). I wrote this article on [getting GoLand to work on a Raspberry Pi 4](https://blog.jetbrains.com/go/2020/02/18/running-goland-on-a-raspberry-pi-4/), but it should give you some insights into running other software on it as well. Delve setup is included in the process. Maybe that helps.

Thank you very much!

**Comment by cusspvz** [comment]
Same on the Macbook M1 while installing the Golang extension tools

```
Tools environment: GOPATH=/Users/redacted/go
Installing 1 tool at /Users/redacted/go/bin in module mode.
  dlv

Installing github.com/go-delve/delve/cmd/dlv FAILED
{
 "killed": false,
 "code": 1,
 "signal": null,
 "cmd": "/opt/homebrew/Cellar/go/1.15.6/libexec/bin/go get -v github.com/go-delve/delve/cmd/dlv",
 "stdout": "",
 "stderr": "/Users/redacted/go/pkg/mod/github.com/go-delve/delve@v1.5.1/service/debugger/debugger.go:26:2: found packages native (nonative_darwin.go) and your_operating_system_and_architecture_combination_is_not_supported_by_delve (support_sentinel.go) in /Users/redacted/go/pkg/mod/github.com/go-delve/delve@v1.5.1/pkg/proc/native\n"
}

1 tools failed to install.

dlv: failed to install dlv(github.com/go-delve/delve/cmd/dlv): Error: Command failed: /opt/homebrew/Cellar/go/1.15.6/libexec/bin/go get -v github.com/go-delve/delve/cmd/dlv
/Users/redacted/go/pkg/mod/github.com/go-delve/delve@v1.5.1/service/debugger/debugger.go:26:2: found packages native (nonative_darwin.go) and your_operating_system_and_architecture_combination_is_not_supported_by_delve (support_sentinel.go) in /Users/redacted/go/pkg/mod/github.com/go-delve/delve@v1.5.1/pkg/proc/native
 no output 

```
