### ISSUE TITLE
Error while reading spliced memory in ListGoroutines command

### ISSUE THREAD

**Issue by nd** [go-delve/delve#1951]
1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 1.4.0
Build: 697310fc296883780f1a57cf162a8c68ebb187d3
```

2. What version of Go are you using? (`go version`)?
```
go version go1.14 linux/amd64

```

3. What operating system and processor architecture are you using?
```
linux/amd64
```

4. What did you do?
Compiled 

```
package main

func main() {
	fail(nil)
}

//go:noinline
func fail(p *string) {
	println(*p)
}
```

with `go build -o exe -gcflags="all=-N -l" .`.

Ran it to crash: `GOTRACEBACK=crash ./exe`

Opened core dump in Delve: `dlv --headless --listen=:2345 --api-version=2 --accept-multiclient core ./exe core`.

5. What did you expect to see?

ListGoroutines command returns goroutines on the moment of crash.

6. What did you see instead?

ListGoroutines command fails with the `error while reading spliced memory at 0x4e9b90: EOF` error. Full log: https://gist.github.com/nd/d5a7776c22f5eff526d7234ddd03032b

**Comment by aarzilli** [comment]
I can't reproduce this and we have a test (TestCore in pkg/proc/core/core_test.go) to test this specifically. The logical reason why this would happen is that ulimit truncated your core file. Could this be the case?

**Comment by nd** [comment]
It was indeed problem with ulimit. If I `export GOTRACEBACK=crash` and then run a program to crash in the same shell, core dump debugging works fine. Not sure why it doesn't work if I do `GOTRACEBACK=crash ./exe` in a single command, but it is not problem of delve. Sorry for the noise.
