### ISSUE TITLE
How to avoid print truncating output?

### ISSUE THREAD

**Issue by siddjain** [go-delve/delve#1954]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?

```
 dlv version
Delve Debugger
Version: 1.3.2
Build: $Id: 569ccbd514fc47c8b4c521b142556867ec5e6917
```
2. What version of Go are you using? (`go version`)?

```
$ go version
go version go1.13.3 darwin/amd64
```

3. What operating system and processor architecture are you using?

```
$ uname -a
Darwin WITSC02X6385JGH 18.7.0 Darwin Kernel Version 18.7.0: Thu Jan 23 06:52:12 PST 2020; root:xnu-4903.278.25~1/RELEASE_X86_64 x86_64
```

4. What did you do?

I tried to print a variable

```
(dlv) print ccid
"mycc_1.0:ce4e81ee8835ad0a01f7629b4646f52535b91378311f11cee703b30...+9 more"
```

5. What did you expect to see?

I want to see full output without truncation

```
(dlv) print ccid
"mycc_1.0.ce4e81ee8835ad0a01f7629b4646f52535b91378311f11cee703b3011d7adfdf"
```

6. What did you see instead?

```
(dlv) print ccid
"mycc_1.0:ce4e81ee8835ad0a01f7629b4646f52535b91378311f11cee703b30...+9 more"
```

**Comment by chainhelen** [comment]
Two ways 
1. Re-config `max-array-values` by command `config`, here is [doc](https://github.com/go-delve/delve/blob/master/Documentation/cli/expr.md#elements-limit)
2. print ccid[64:]

**Comment by aarzilli** [comment]
Closing, what @chainhelen said.
