### ISSUE TITLE
dlv wait for ever at break point and write broken pipe erro

### ISSUE THREAD

**Issue by mikej2020** [go-delve/delve#1965]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
/ # /dlv version
Delve Debugger
Version: 1.4.0
Build: $Id: 67422e6f7148fa1efa0eac1423ab5594b223d93b

2. What version of Go are you using? (`go version`)?
go version go1.14 linux/amd64

3. What operating system and processor architecture are you using?
vm station

4. What did you do?
/dlv --listen=:40000 --headless=true --api-version=2 --log --log-output=rpc attach 1
then debug from goland, set break point and start debug

5. What did you expect to see?
step into, step over

6. What did you see instead?
debugger catch the bk, but step into, over will hung there and sometime error with write broken pipe

huge amount of log output and never stopped.

**Comment by dlsniper** [comment]
Is there a way to share the logs to understand what's happening? What's your IDE version? I'm not sure if this is a bug on our side or Delve's just yet, so if you want to share the logs in a secure way, you can use GoLand's issue tracker at https://youtrack.jetbrains.com/issues/Go and once we replicate it, if it proves to be from Delve, we can add here a replication scenario.

**Comment by aarzilli** [comment]
Closing, no user feedback.
