### ISSUE TITLE
Delve 1.4 can't debug on Catalina 10.15.4

### ISSUE THREAD

**Issue by dialtone** [go-delve/delve#1966]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.4.0
Build: $Id: 67422e6f7148fa1efa0eac1423ab5594b223d93b $

2. What version of Go are you using? (`go version`)?
go version go1.14 darwin/amd64

3. What operating system and processor architecture are you using?
MacOSX 10.15.4, freshly updated

4. What did you do?
`dlv test --headless=true --listen=127.0.0.1:34086 --api-version=2 --log=true`
from the project root.

5. What did you expect to see?
The thing debugs without errors

6. What did you see instead?
```
API server listening at: 127.0.0.1:34086
2020-03-27T01:08:49-07:00 info layer=debugger launching process with args: [/Users/dialtone/dev/go/src/github.com/xyz/bouncer/debug.test]
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1103.0.22
 for x86_64.
...
error: failed to launch process /Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver: failed to get the task for process 29651
Exiting.
could not launch process: stub exited while waiting for connection: exit status 0
```

This possibly has to do with a new xcode tools that came with the new catalina.
In turn this causes VSCode go debugging to fail.

**Comment by nd** [comment]
Got the same error after update, it is gone once I've updated XCode as well. Ensure that you have the latest XCode version installed.

**Comment by dialtone** [comment]
I have XCode Version 11.4 (11E146) and command line tools associated with it (xcode-select --install refuses to do anything and says already updated, so I tried uninstalling them and reinstalling them but no different...).

**Comment by dialtone** [comment]
Even tried reinstalling go from source using `brew install --build-from-source` and no luck there either.

**Comment by nd** [comment]
Maybe removing the `/Library/Developer/CommandLineTools` and running `xcode-select --install` can help, but I'm not sure.

**Comment by dialtone** [comment]
yeah I've done that already.

**Comment by aarzilli** [comment]
You can try running debug server manually:

```
/Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver -- /path/to/some/executable
```

If it fails with the same error then the problem is with lldb/debugserver and you should report it to Apple.

**Comment by dialtone** [comment]
Indeed it fails when I try to use a random binary from a C helloworld. It could possibly be related to code signing perhaps, although I have developer mode active on this laptop. https://lapcatsoftware.com/articles/debugging-mojave.html perhaps this changed further in 10.15.4

**Comment by dialtone** [comment]
tried downgrading to xcode tools 11.3.1 which worked fine until 2 days ago but sadly that doesn't fix it, making me believe it isn't a command line tool issue either but an OS level problem with permissions/authorization.

**Comment by dialtone** [comment]
alright so... Literally seconds ago apple released an updated version of xcode tools and the issue went away. Cheers and thanks for the suggestions... Never updating again.

**Comment by xstephen95x** [comment]
@dialtone what versions of xcode + macos finally worked for you?

**Comment by dialtone** [comment]
At the moment I have XCode Version 11.4.1 (11E503a) and it works.
