### ISSUE TITLE
VSCode debug error : Version of Delve is too old for this version of Go

### ISSUE THREAD

**Issue by AdolphKevin** [go-delve/delve#1974]
**vscode** debug error in macos :

Version of Delve is too old for this version of Go (maximum supported version 1.13, suppress this error with --check-go-version=false)

go version is 1.14.1 darwin/amd64 , dlv version is 1.4.0

i try reinstall  go-delve in $GOPATH and appoint 1.14 in go mod 

i try upgrade and reinstall vscode

but still no solution.

**Comment by AdolphKevin** [comment]
is solution.
 
```
sudo rm $GOROOT/bin/dlv
sudo rm $GOPATH/bin/dlv
sudo go get -u github.com/go-delve/delve/cmd/dlv
```

check dlv local path
```
which dlv
```

result is `$GOROOT/bin/dlv`. then 
```
sudo mv $GOROOT/bin/dlv $GOPATH/bin/
```

**Comment by AdolphKevin** [comment]
keep vscode and delve is updates available

**Comment by leobeosab** [comment]
Easier solution for me is just doing
```
go get -u github.com/go-delve/delve/cmd/dlv
```

No sudo or moving necessary for me at least.

**Comment by Antony-redzone** [comment]
don't forget you may need to do a 
`go mod tidy`
after this command

**Comment by mofei1** [comment]
{
    // 使用 IntelliSense 了解相关属性。 
    // 悬停以查看现有属性的描述。
    // 欲了解更多信息，请访问: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [

        {
            "name": "Launch Package",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": "${workspaceFolder}",
            "dlvLoadConfig":{
                "followPointers": true,
                "maxVariableRecurse": 1,
                "maxStringLen": 512, //字符串最大长度
                "maxArrayValues": 64,
                "maxStructFields": -1
              },
             "dlvFlags": ["--check-go-version=false"] 

        }
    ]
}

//这是我的配置文件

**Comment by mofei1** [comment]
we can add flag with    "dlvFlags": ["--check-go-version=false"] 

this is my launch file
 {
        "name": "Launch Package",
        "type": "go",
        "request": "launch",
        "mode": "debug",
        "program": "${workspaceFolder}",
        "dlvLoadConfig":{
            "followPointers": true,
            "maxVariableRecurse": 1,
            "maxStringLen": 512, //字符串最大长度
            "maxArrayValues": 64,
            "maxStructFields": -1
          },
         "dlvFlags": ["--check-go-version=false"] 

    }
]

it work
dlv-dap dap --check-go-version=false --listen=127.0.0.1:40236 --log-dest=3

**Comment by mofei1** [comment]
{
    // 使用 IntelliSense 了解相关属性。 
    // 悬停以查看现有属性的描述。
    // 欲了解更多信息，请访问: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [

        {
            "name": "Launch Package",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": "${workspaceFolder}",
            "dlvLoadConfig":{
                "followPointers": true,
                "maxVariableRecurse": 1,
                "maxStringLen": 512, //字符串最大长度
                "maxArrayValues": 64,
                "maxStructFields": -1
              },
             "dlvFlags": ["--check-go-version=false"] 

        }
    ]
}
add flag it also can  solve it ，the dlv-dap version is too hight will cause it.

**Comment by nikhilbhavsar5895** [comment]
> {
> // 使用 IntelliSense 了解相关属性。
> // 悬停以查看现有属性的描述。
> // 欲了解更多信息，请访问: https://go.microsoft.com/fwlink/?linkid=830387
> "version": "0.2.0",
> "configurations": [
> 
> ```
>     {
>         "name": "Launch Package",
>         "type": "go",
>         "request": "launch",
>         "mode": "debug",
>         "program": "${workspaceFolder}",
>         "dlvLoadConfig":{
>             "followPointers": true,
>             "maxVariableRecurse": 1,
>             "maxStringLen": 512, //字符串最大长度
>             "maxArrayValues": 64,
>             "maxStructFields": -1
>           },
>          "dlvFlags": ["--check-go-version=false"] 
> 
>     }
> ]
> ```
> 
> }
> add flag it also can solve it ，the dlv-dap version is too hight will cause it.

Thanks for answer,
This solves my debug server issue but I'm not able to debug test cases. Can you please help me?

**Comment by coffeedome** [comment]
@nikhilbhavsar5895 just saw your question above - just go to settings.json file (Settings -> Extensions -> Go -> Select "Edit in settings.json under "Go:Delve Config" section) then add the "dlvFlags": ["--check-go-version=false"] section to that block just like above.

**Comment by nixomose** [comment]
for those of you using a dlv-sudo.sh type script, I had to run go install from above as both my user and as root.
it updated /home/nixo/<user>/go/bin/dlv which is what my script was pointing to.
But since it runs as root I needed to install as root as well.

**Comment by msa1317** [comment]
> sudo rm $GOROOT/bin/dlv
> sudo rm $GOPATH/bin/dlv
> sudo go get -u github.com/go-delve/delve/cmd/dlv

There is a situation, dlv's version is too newer,
so U do cmd "sudo go get -u github.com/go-delve/delve/cmd/dlv" can assign version.
eg:go version 1.14, dlv version 1.7+,    --->Correct command:sudo go get -u github.com/go-delve/delve/cmd/dlv@v1.6.0

**Comment by RunningFaster** [comment]
> Since `go get` is no longer supported outside a module and depricated <1.17 & removed from >=1.18, https://go.dev/doc/go-get-install-deprecation
> 
> I just `rm`'d the old dlv using, (_but I don't think this is required since the install command should overwrite the binary._)
> 
> ```
> rm $GOPATH/bin/dlv
> ```
> 
> Then installed the latest version using,
> 
> ```
> go install github.com/go-delve/delve/cmd/dlv@latest
> ```
> 
> Works just fine

It's useful!

**Comment by Alexander-Serov** [comment]
> Easier solution for me is just doing
> 
> ```
> go get -u github.com/go-delve/delve/cmd/dlv
> ```
> 
> No sudo or moving necessary for me at least.

This worked for me, but gave a "build error" until I restarted VSCode.

**Comment by sdklab007** [comment]
This is how I solved:

```
sudo rm -rf vendor
go get -u github.com/go-delve/delve/cmd/dlv
go mod tidy
go mod vendor
```

**Comment by justinIs** [comment]
I had to update delve with `go install`:

```sh
go install github.com/go-delve/delve/cmd/dlv@latest
```
