### ISSUE TITLE
Breaking changes in github.com/cosiner/argv

### ISSUE THREAD

**Issue by ip01** [go-delve/delve#1988]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
Version: 1.4.0
Build: $Id: 67422e6f7148fa1efa0eac1423ab5594b223d93b $

2. What version of Go are you using? (`go version`)?
go version go1.14.1 windows/amd64

3. What operating system and processor architecture are you using?
windows/amd64

4. What did you do?
go get -u github.com/go-delve/delve/cmd/dl

5. What did you expect to see?
Successful install

6. What did you see instead?
github.com/go-delve/delve/pkg/terminal
C:\Users\user\go\pkg\mod\github.com\go-delve\delve@v1.4.0\pkg\terminal\command.go:959:28: cannot use ([]rune)(args) (type []rune) as type string in argument to argv.Argv
C:\Users\user\go\pkg\mod\github.com\go-delve\delve@v1.4.0\pkg\terminal\command.go:959:36: undefined: argv.ParseEnv as type argv.Expander in argument to argv.Argv

The reason is https://github.com/cosiner/argv/commit/0e2b0bed5d2192501434fcddeca7c485a929f513

**Comment by aarzilli** [comment]
You are using `go get` from inside a directory containing a module, this will cause it to add delve as a dependency, and given that you used `-u` to try to inappropriately upgrade delve's dependencies. You shouldn't do this.

**Comment by slacki** [comment]
Here's a link explaining how to install delve properly: https://github.com/go-delve/delve/blob/master/Documentation/installation/linux/install.md

Especially this part
>Note: if you are using Go in modules mode you must execute this command outside of a module directory or Delve will be added to your project as a dependency.
