### ISSUE TITLE
can't install dlv

### ISSUE THREAD

**Issue by mojo-zd** [go-delve/delve#1991]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
v1.4.0 | master
2. What version of Go are you using? (`go version`)?
go1.14 | go1.13
3. What operating system and processor architecture are you using?
macos | centos | 

4. What did you do?
go get -u github.com/go-delve/delve/cmd/dlv
5. What did you expect to see?
success build
6. What did you see instead?
pkg/mod/github.com/go-delve/delve@v1.4.0/pkg/terminal/command.go:959:36: undefined: argv.ParseEnv
pkg/mod/github.com/go-delve/delve@v1.4.0/pkg/terminal/command.go:960:3: cannot use func literal (type func([]rune, map[string]string) ([]rune, error)) as type argv.Expander in argument to argv.Argv
The command '/bin/sh -c go get -u github.com/go-delve/delve/cmd/dlv' returned a non-zero code: 2
Makefile:50: recipe for target 'build-shadow' failed
make: *** [build-shadow] Error 2
The command "make build-shadow" exited with 2.

**Comment by chainhelen** [comment]
Same as #1988

**Comment by chainhelen** [comment]
You can set `export GO111MODULE=off` before `go get` temporarily. The final solution requires code changes.
