### ISSUE TITLE
--continue doesn't available for attach

### ISSUE THREAD

**Issue by oxycoder** [go-delve/delve#1995]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)? 1.4.0
2. What version of Go are you using? (`go version`)? 1.14.1
3. What operating system and processor architecture are you using? Mac OS 10.15.4
4. What did you do? `dlv --listen=:2345 --headless=true --accept-multiclient --continue --api-version=2 attach PID`
5. What did you expect to see? dlv started
6. What did you see instead? 
```
Error: unknown flag: --continue
```

According to #245, it should be available to use --continue with attach. Is this bug or unavailable features?

**Comment by xyzst** [comment]
@aarzilli: This seems like another easy one. I'll give it a try. Looks like I need to declare the `continue` flag on the `attachCommand` variable:

https://github.com/go-delve/delve/blob/3cf685e5ea5b4b9bac6ab57abb5b5e4e69231804/cmd/dlv/cmds/commands.go#L123

Basically, it should look like this:
https://github.com/go-delve/delve/blob/3cf685e5ea5b4b9bac6ab57abb5b5e4e69231804/cmd/dlv/cmds/commands.go#L186
