### ISSUE TITLE
`dlv exec` leave target process running that was not successfully launch caused by missing debug info

### ISSUE THREAD

**Issue by qingyunha** [go-delve/delve#2017]
1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.4.0
Build: $Id: 67422e6f7148fa1efa0eac1423ab5594b223d93b $

2. What version of Go are you using? (`go version`)?
go version go1.13.5 linux/amd64

3. What operating system and processor architecture are you using?
linux/amd64

4. What did you do?
`dlv exec` a stripped binary. 

5. What did you expect to see?
dlv exit

6. What did you see instead?
dlv exit with error message `could not launch process: could not open debug info` but leaving the target process running.

**Comment by chainhelen** [comment]
@qingyunha 
Whether this stripped binary runs directly is also a dead cycle？(for example, listen tcp port)

**Comment by qingyunha** [comment]
Yes, It's a long running process.
