### ISSUE TITLE
a way to trace function and add custom command like p local variable on print msg

### ISSUE THREAD

**Issue by tty5** [go-delve/delve#2022]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.4.0
Build: 9c24b56f62caffbd072e721b1edd13b1bdb3d621

2. What version of Go are you using? (`go version`)?
1.14

3. What operating system and processor architecture are you using?
centos8

4. What did you do?
```
dlv  attach `pgrep http-s`
Type 'help' for list of commands.
(dlv) trace main.urlTracepoint 1 set at 0x78b17b for main.url() ./http-s.go:41
(dlv) c
> main.url() ./http-s.go:41 (hits goroutine(3949):1 total:1) (PC: 0x78b17b)
> main.url() ./http-s.go:41 (hits goroutine(3951):1 total:2) (PC: 0x78b17b)
> main.url() ./http-s.go:41 (hits goroutine(3992):1 total:3) (PC: 0x78b17b)
> main.url() ./http-s.go:41 (hits goroutine(3953):1 total:4) (PC: 0x78b17b)
```

5. What did you expect to see?
i want to print the parameters with custom command. is there a way can do it

6. What did you see instead?

**Comment by aarzilli** [comment]
`help on`

**Comment by tty5** [comment]
> `help on`

```
bp
Breakpoint mu at 0x78b17b for main.url() ./http-s.go:41 (1)
        print r
(dlv) on mu c
Command failed: command not available
(dlv)
```

the difficult is can't add cmd continue to a break point.

**Comment by aarzilli** [comment]
Use a tracepoint then `on`.

**Comment by tty5** [comment]
thanks a lot
