### ISSUE TITLE
dlv attach can't find the external debug file properly

### ISSUE THREAD

**Issue by coderplay** [go-delve/delve#2024]
1. What version of Delve are you using (`dlv version`)?

```
$ dlv version
Delve Debugger
Version: 1.4.0
Build: $Id: 67422e6f7148fa1efa0eac1423ab5594b223d93b
```

2. What version of Go are you using? (`go version`)?

```
$ go version
go version go1.14.2 linux/amd64
```

3. What operating system and processor architecture are you using?

```
$ uname -a
Linux 4.15.0-1057 #59-Ubuntu SMP Wed Dec 4 10:02:00 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

4. What did you do?

I was attaching dlv to a daemon process of of kubernetes.  
executable path:  `/usr/bin/kubelet`
external debug file : `/usr/lib/debug/kubelet.debug`
debug-info-directories: `["/usr/lib/debug/.build-id", "/usr/lib/debug"]`

```bash
$ sudo dlv attach `pgrep kubelet`
```

5. What did you expect to see?

dlv should able to attach the target running process.

6. What did you see instead?

```
could not attach to pid 8020: could not open debug info
```

7. Root cause

The commit 
https://github.com/go-delve/delve/commit/f3b149bda706005283f547e0cf090457d084349c#diff-102e824b326c8dd9e8721394368821a8L625  switch the executable path to `image.Path` 

``` go
potentialDebugFilePath = fmt.Sprintf("%s/%s.debug", dir, filepath.Base(image.Path))
```

The above `image.Path` was originally from `proc_linux.go` passed by its `Attach` method
```
func Attach(pid int, debugInfoDirs []string) (*proc.Target, error) {
...
	tgt, err := dbp.initialize(findExecutable("", dbp.pid), debugInfoDirs)
...
}

func findExecutable(path string, pid int) string {
	if path == "" {
		path = fmt.Sprintf("/proc/%d/exe", pid)
	}
	return path
}
```

So for my case the `image.Path` was `/proc/8020/exe`.  Delve tried to open `/usr/lib/debug/exe.debug` instead of `/usr/lib/debug/kubelet.debug`.

**Comment by aarzilli** [comment]
Fixed by #2025
