### ISSUE TITLE
dlv trace duplicate entries (function calls)

### ISSUE THREAD

**Issue by zultu** [go-delve/delve#2027]
1. What version of Delve are you using (`dlv version`)?

both master and 1.4.0 ( 37bee98a8821843314b561bc6ab328dfff2aad1b )

2. What version of Go are you using? (`go version`)?

go version go1.14.2 linux/amd64

3. What operating system and processor architecture are you using?

arch linux x64

4. What did you do?

dlv trace z.go main.

plus:
dlv debug z.go

then:
1) trace main.main
2) trace main.f
3) c

5. What did you expect to see?

> main.main()
> main.f()

each only called once, instead of:

> main.main()
> main.f()
> main.f()
> main.main()

6. What did you see instead?

> runtime.main.func1() /usr/lib/go/src/runtime/proc.go:133 (hits goroutine(1):1 total:1) (PC: 0x45812f)
Warning: debugging optimized function
> runtime.main.func1() /usr/lib/go/src/runtime/proc.go:135 (hits goroutine(1):1 total:1) (PC: 0x45815f)
Warning: debugging optimized function
main()
> main.main() ./z.go:7 (hits goroutine(1):1 total:1) (PC: 0x45fc9f)
f()
> main.f() ./z.go:3 (hits goroutine(1):1 total:1) (PC: 0x45fc3f)
> main.f() ./z.go:5 (hits goroutine(1):1 total:1) (PC: 0x45fc79)
> main.main() ./z.go:10 (hits goroutine(1):1 total:1) (PC: 0x45fcde)
Process 436778 has exited with status 0

z.go content:
```
package main

func f() {
        println("f()")
}

func main() {
        println("main()")
        f()
}
```

if i run in interactively in the debugger (dlv debug), then it works correctly (no duplicates at the end of function calls):

```
$ dlv debug z.go 
Type 'help' for list of commands.
(dlv) trace main.main
Tracepoint 1 set at 0x45fc9f for main.main() ./z.go:7
(dlv) trace main.f
Tracepoint 2 set at 0x45fc3f for main.f() ./z.go:3
(dlv) c
main()
> main.main() ./z.go:7 (hits goroutine(1):1 total:1) (PC: 0x45fc9f)
f()
> main.f() ./z.go:3 (hits goroutine(1):1 total:1) (PC: 0x45fc3f)
Process 436873 has exited with status 0

```

other code works in a similar way: each function is called twice (second time with "incorrect" location, just somewhere at the end of the actual call).
library functions and external code is also broken, and i couldn't fix it

i can send more logs, for instance wrapper calls from go-gl etc, they all have dupes
i tried to disable GC but it didn't help

**Comment by derekparker** [comment]
This is because in the `dlv trace` command we also try and set breakpoints wherever the function returns so that we can display the return arguments as well. Something seems to have broken with this feature however. I'll look into it.
