### ISSUE TITLE
# command-line-arguments undefined: xxxx

### ISSUE THREAD

**Issue by liesauer** [go-delve/delve#2029]
1. What version of Delve are you using (`dlv version`)?
`1.2.0`
2. What version of Go are you using? (`go version`)?
`go version go1.13.4 darwin/amd64`
3. What operating system and processor architecture are you using?
`macOS x64`
4. What did you do?
try to debug my project in vscode, and it failed, and then i also tried `/Users/imac/go/bin/dlv debug /path/to/project/src/main/beauty.go`, failed either.
5. What did you expect to see?
no error and debug my project
6. What did you see instead?
```
# command-line-arguments
src/main/beauty.go:41:2: undefined: Umask
exit status 2
```

it was totally fine before i update the dlv. i tried updating dlv to latest version, still happened. because of the internet issue in china, i can not build an older one and test it(download dependencies failed).

releated codes:
`src/main/beauty.go`
```go
package main

func main() {
	Umask()
}
```
`src/main/umask_nonwindows.go`
```go
// +build !windows

package main

import (
	"syscall"
)

func Umask() {
	syscall.Umask(0)
}
```

**Comment by liesauer** [comment]
update to `1.4.0`, still happened.

**Comment by liesauer** [comment]
it looks like not a dlv problem.

**Comment by justin-watkinson-sp** [comment]
In case someone else finds this, I ran into this issue with vscode's debugger for go.  I've had vscode pointing to the <name>.go file for my project for probably a year, and some update must've changed something to the point where it doesn't work that way any more.  I had to change the "program" directive to point to the directory.

**Comment by liesauer** [comment]
> In case someone else finds this, I ran into this issue with vscode's debugger for go. I've had vscode pointing to the .go file for my project for probably a year, and some update must've changed something to the point where it doesn't work that way any more. I had to change the "program" directive to point to the directory, and not the file. I have tests and other files locally, so it makes sense in the go paradigm, but it was difficult to track down given its been like that forever.

exactly the same issue as mime.

**Comment by liesauer** [comment]
to fix this, try not specifying the main `.go` to "program" in `launch.json`, specify the path of the main package instead.

example:
~"program": "${workspaceFolder}/src/main.go"~
"program": "${workspaceFolder}/src/main"
