### ISSUE TITLE
Make `list` display the next set of lines when the empty command is sent

### ISSUE THREAD

**Issue by dmlary** [go-delve/delve#2030]
Note: This is a **feature request**.

Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
```txt
Delve Debugger
Version: 1.4.0
Build: $Id: 67422e6f7148fa1efa0eac1423ab5594b223d93b $
```

2. What version of Go are you using? (`go version`)? `go version go1.14.2 linux/amd64`

3. What operating system and processor architecture are you using? `x86_64 GNU/Linux`

4. What did you do?

* `list <func>` # output 10 lines of code
* `<pressed enter>` # output same 10 lines of code

5. What did you expect to see?

Next 10 lines of code, similar to gdb & lldb.  Makes displaying source while debugging more convenient.

6. What did you see instead?

The same 10 lines of code

Example:
```txt
(dlv) list snode.attr
Showing /go/pkg/mod/bazil.org/fuse@v0.0.0-20200419173433-3ba628eaf417/fs/serve.go:492 (PC: 0x56d9d3)
 487:		//     - hold Server.meta while calling wg.Add, then unlock
 488:		//     - do NOT try to reacquire Server.meta
 489:		wg sync.WaitGroup
 490:	}
 491:
 492:	func (sn *serveNode) attr(ctx context.Context, attr *fuse.Attr) error {
 493:		err := nodeAttr(ctx, sn.node, attr)
 494:		if attr.Inode == 0 {
 495:			attr.Inode = sn.inode
 496:		}
 497:		return err
(dlv)
Showing /go/pkg/mod/bazil.org/fuse@v0.0.0-20200419173433-3ba628eaf417/fs/serve.go:492 (PC: 0x56d9d3)
 487:		//     - hold Server.meta while calling wg.Add, then unlock
 488:		//     - do NOT try to reacquire Server.meta
 489:		wg sync.WaitGroup
 490:	}
 491:
 492:	func (sn *serveNode) attr(ctx context.Context, attr *fuse.Attr) error {
 493:		err := nodeAttr(ctx, sn.node, attr)
 494:		if attr.Inode == 0 {
 495:			attr.Inode = sn.inode
 496:		}
 497:		return err
```

**Comment by aarzilli** [comment]
There's an edit command that can open the source code at the current line. You can even set it up to open the source in a different window easily. I've always thought the behavior of `list` in gdb was archaic, designed for physical teletypes from the '70s.

**Comment by dmlary** [comment]
It is, but occasionally you're working in an environment like that.  For example, writing a user-space filesystem with bazil.org/fuse on a mac, which doesn't support mac, I'm forced to run all tests & debugging within a docker image.

**Comment by jginsburgn** [comment]
+1
Also, there should be a way to see the previous lines and to set the number of lines printed when issuing `list`.

**Comment by jcass8695** [comment]
Not to derail OP's original issue, but I would like to add my +1 to @jginsburgn's suggestion: 

> set the number of lines printed when issuing list.

It would be useful to be able to print more than the 5 lines either side of the current line, similar to `grep`'s A, B and C flags.

**Comment by aarzilli** [comment]
That can already be done:

```
(dlv) config source-list-line-count 10
```

**Comment by jcass8695** [comment]
I think it might be more intuitive and user-friendly to have something like `list -A 15 -B 12` or `list -C 17`.  If you know roughly where in the codebase I could get started, I might have time over the next few weekends to take a look.

**Comment by aarzilli** [comment]
List takes a location expression as an argument, which can be anything. It's difficult to change it to also take other arguments in an unambiguous way. Also I still think there's little need for this when there's `edit`.

**Comment by jcass8695** [comment]
Fair enough 👍🏻

**Comment by aarzilli** [comment]
Closing, dubious usefulness combined with implementation difficulties.

**Comment by dmlary** [comment]
For context, `edit` does not provide the same capability here in all situations. `edit` doesn’t allow you to see both source code and the current values of variables when you’re ssh’d into a remote host. Keep in mind, not everyone is doing local development.

Despite the argument ambiguities for the `list -C` command, that may path have been a good solution. 

Along that line of thinking, it may be possible to extract function length in source code lines from the dwarf info (or equivalent).  ELF function symbols have sizes, and you can look up source line from virtual addresses within the function range. If that’s the case, `list` could dynamically determine function length and display the entire function.
