### ISSUE TITLE
regs -a only lists XMM, no YMM and ZMM

### ISSUE THREAD

**Issue by rleiwang-traceableai** [go-delve/delve#2033]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
1.4.0
2. What version of Go are you using? (`go version`)?
1.14.2
3. What operating system and processor architecture are you using?
Linux
```
processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 85
model name	: Intel(R) Xeon(R) CPU
stepping	: 7
microcode	: 0x1
cpu MHz		: 2800.168
cache size	: 33792 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced kaiser fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat md_clear arch_capabilities
bugs		: spectre_v1 spectre_v2 spec_store_bypass mds swapgs taa itlb_multihit
bogomips	: 5600.33
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
```
4. What did you do?
 regs -a

5. What did you expect to see?
all CPU registers, including XMM, YMM, ZMM

6. What did you see instead?
all other registers except YMM and ZMM

**Comment by aarzilli** [comment]
Our ability to display registers depends on the operating system returning them to us. I don't have a computer with zmm registers but I do have ymm registers and my version of linux doesn't return them anyway (or maybe it only does when they are used?). What are you doing exactly.

**Comment by rleiwang-traceableai** [comment]
The OS is Linux 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linux. It's a hello world Go application. I am able to list all ZMM registers with gdb.
