### ISSUE TITLE
Misleading error message when trying to debug non-existent tests

### ISSUE THREAD

**Issue by deitch** [go-delve/delve#2042]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?

```
Delve Debugger
Version: 1.4.0
Build: 0f83fa66f5ebc17be9349ac51951f78454a1269b
```

Pulled latest master from github and installed

2. What version of Go are you using? (`go version`)?

```
go version go1.14 darwin/amd64
```

3. What operating system and processor architecture are you using?

macOS 10.15.4 (latest), Intel x86_64

4. What did you do?

```
dlv test .
```

5. What did you expect to see?

The interactive debugger shell

6. What did you see instead?

```
2020-05-07T12:28:06+03:00 info layer=debugger launching process with args: [/path/to/repo/debug.test]
could not launch process: open /path/to/repo/debug.test: no such file or directory
could not remove /path/to/repo/debug.test: remove /path/to/repo/debug.test: no such file or directory
```

FYI, this does not appear to be the code signer issue from earlier. I ran `make install`, and then manually code-signed again. More importantly, I can run `dlv debug .` without an issue, but not `dlv test .`

I did hunt through the issues to find the many code-signing or VSCode issues, but this does not (appear to be) one of them.

**Comment by aarzilli** [comment]
what happens if you do `go test -c -o debug.test .`? Does it create a debug.test file?

**Comment by deitch** [comment]
```console
$ go test -c -o debug.test .
?   	github.com/lf-edge/adam	[no test files]
$  ls -l debug.test
ls: debug.test: No such file or directory
```

**Comment by deitch** [comment]
Aw drat. I ran it in a directory without any tests. That only showed up with the above.

**Comment by deitch** [comment]
* `dlv debug .` works because it is the `package main`
* `dlv debug ./foo/bar` works because there are tests there
* `dlv debug ./...` does not work because you cannot use `-c` with multiple packages
* `dlv debug .` does not work because of no test files

**Comment by deitch** [comment]
Any chance we can get better messaging on it? Similar to what `go` gives?

**Comment by aarzilli** [comment]
The tests are built by GoTestBuild in pkg/gobuild/gobuild which calls gocommand. I see that we are passing Stderr through but that probably doesn't show up because it's on Stdout. Maybe we should pass through Stdout too.

**Comment by aarzilli** [comment]
You know, one could argue that `go test -c` should os.Exit(1) and print an error to stderr instead of pretending the `-c` didn't exist.

**Comment by deitch** [comment]
> Maybe we should pass through Stdout too.

Definitely would be helpful.

> one could argue that go test -c should os.Exit(1) and print an error to stderr instead of pretending the -c didn't exist.

Probably! 😀

In the end, yeah, my CLI arguments error, but the error message was misleading.

Would it helped if I opened a clean issue on that?

**Comment by aarzilli** [comment]
> Would it helped if I opened a clean issue on that?

Not necessary.

**Comment by aarzilli** [comment]
See #2044

**Comment by deitch** [comment]
Thanks @aarzilli
