### ISSUE TITLE
Question: How to prevent the binary file __debug_bin from getting deleted when dlv exits?

### ISSUE THREAD

**Issue by siddjain** [go-delve/delve#2045]
When `dlv` exits it auto-deletes the compiled binary. How can I tell it not to delete the compiled binary - for example, I would like to re-use it for another session.

**Comment by chainhelen** [comment]
Type `dlv debug --help`   and see 
```
...
      --output string   Output path for the binary. (default "./__debug_bin")
...
```
So you can specify `--output`.

**Comment by aarzilli** [comment]
Build it with `go` and `-gcflags="all=-N -l"` then debug with `dlv exec`.

**Comment by siddjain** [comment]
for curiosity, What are the exact flags used by dlv debug? When I build a binary with `-gcflags="all=-N -l"` I get a different size than if I build it using `dlv debug`. I am using 

```
$ go version
go version go1.13.3 darwin/amd64
```

and 

```
$ dlv version
Delve Debugger
Version: 1.3.2
Build: $Id: 569ccbd514fc47c8b4c521b142556867ec5e6917 
```

**Comment by chainhelen** [comment]
`dlv` just use `go build -o ./__debug_bin -gcflags "all=-N -l" main.go ` to generate binary file.
