### ISSUE TITLE
rewind Command failed: command not available

### ISSUE THREAD

**Issue by siddjain** [go-delve/delve#2046]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?

```
$ dlv version
Delve Debugger
Version: 1.3.2
Build: $Id: 569ccbd514fc47c8b4c521b142556867ec5e6917 $
```

2. What version of Go are you using? (`go version`)?

```
$ go version
go version go1.13.3 darwin/amd64
```

3. What operating system and processor architecture are you using?

```
$ uname -a
Darwin WITSC02X6385JGH 18.7.0 Darwin Kernel Version 18.7.0: Mon Feb 10 21:08:45 PST 2020; root:xnu-4903.278.28~1/RELEASE_X86_64 x86_64
```

4. What did you do?

I tried to run the `rewind` command as documented in https://github.com/go-delve/delve/tree/v1.3.2/Documentation/cli#rewind

5. What did you expect to see?

Run backwards until breakpoint or program termination.

6. What did you see instead?

```
(dlv) rewind
Command failed: command not available
```

**Comment by dlsniper** [comment]
Rewind uses Mozilla rr, which works only on Linux at the moment. See additional requirements here https://github.com/mozilla/rr#system-requirements

**Comment by chainhelen** [comment]
duplicate #2036

**Comment by aarzilli** [comment]
What @dlsniper and @chainhelen said.
