### ISSUE TITLE
Internal debugger error: runtime error: invalid memory address or nil pointer dereference.

### ISSUE THREAD

**Issue by vincentjocodes** [go-delve/delve#2049]
1. What version of Delve are you using (`dlv version`)?
1.4.0

2. What version of Go are you using? (`go version`)?
1.14

3. What operating system and processor architecture are you using?
Docker

4. What did you do?
Ran `ENTRYPOINT ["dlv", "exec", "/app/frontend", "--continue", "--accept-multiclient", "--api-version=2", "--headless", "--listen=:3000", "--log"]` and then reloaded the application to hit the breakpoint in VSCode.

5. What did you expect to see?
I expected the debugger to stop on the breakpoint.

6. What did you see instead?
The instance shut down and got the following error message:
```
Unable to produce stack trace: "Internal debugger error: runtime error: invalid memory address or nil pointer dereference
runtime.gopanic (0x434455)
	/usr/local/go/src/runtime/panic.go:969
runtime.panicmem (0x44abe9)
	/usr/local/go/src/runtime/panic.go:212
runtime.sigpanic (0x44aa38)
	/usr/local/go/src/runtime/signal_unix.go:695
github.com/go-delve/delve/pkg/proc.(*EvalScope).Locals (0x6eecc9)
	/go/src/github.com/go-delve/delve/pkg/proc/eval.go:269
github.com/go-delve/delve/pkg/proc.(*EvalScope).LocalVariables (0x6f00ce)
	/go/src/github.com/go-delve/delve/pkg/proc/eval.go:411
github.com/go-delve/delve/service/debugger.(*Debugger).convertStacktrace (0x78eecb)
	/go/src/github.com/go-delve/delve/service/debugger/debugger.go:1389
github.com/go-delve/delve/service/debugger.(*Debugger).Stacktrace (0x78e165)
	/go/src/github.com/go-delve/delve/service/debugger/debugger.go:1325
github.com/go-delve/delve/service/rpc2.(*RPCServer).Stacktrace (0x9b4346)
	/go/src/github.com/go-delve/delve/service/rpc2/server.go:187
reflect.Value.call (0x4c30da)
	/usr/local/go/src/reflect/value.go:460
reflect.Value.Call (0x4c25e3)
	/usr/local/go/src/reflect/value.go:321
github.com/go-delve/delve/service/rpccommon.(*ServerImpl).serveJSONCodec.func2 (0xa09186)
	/go/src/github.com/go-delve/delve/service/rpccommon/server.go:311
github.com/go-delve/delve/service/rpccommon.(*ServerImpl).serveJSONCodec (0xa07539)
	/go/src/github.com/go-delve/delve/service/rpccommon/server.go:313
runtime.goexit (0x464a90)
	/usr/local/go/src/runtime/asm_amd64.s:1373"
```

**Comment by briandealwis** [comment]
The stack trace seems odd as `/go/src/github.com/go-delve/delve/pkg/proc/eval.go:269` corresponds to the comment on `SetVariable()`:
https://github.com/go-delve/delve/blob/81a86086dd9974d5bab76b1749d7450bb6b5cfab/pkg/proc/eval.go#L268-L271

[`eval.go:411`](https://github.com/go-delve/delve/blob/81a86086dd9974d5bab76b1749d7450bb6b5cfab/pkg/proc/eval.go#L411)  is in `findGlobalInternal()`.

[`service/debugger/debugger.go:1389`](https://github.com/go-delve/delve/blob/81a86086dd9974d5bab76b1749d7450bb6b5cfab/service/debugger/debugger.go#L1389) is a blank line between to function definitions.

**Comment by chainhelen** [comment]
@briandealwis Because the used version `dlv`  is `master` instead of `1.4.0`.

**Comment by briandealwis** [comment]
<blush> too right @chainhelen — the sample @vincentjocodes was using was/will be rewritten to use Skaffold's `debug` which installs delve on the fly.  I've hidden my comment since it's not actually useful.

**Comment by vincentjocodes** [comment]
> @briandealwis Because the used version `dlv` is `master` instead of `1.4.0`.

I checked the version and it at 1.4.0.

**Comment by derekparker** [comment]
@vincentjocodes does https://github.com/go-delve/delve/pull/2050 fix your issue? Do you think you could provide a small reproducer?

**Comment by vincentjocodes** [comment]
@derekparker Hello, I'm not sure how I would test the branch at the moment pulling it in within my Dockerfile, but I'm okay with closing this issue until it comes up in the next release. Would that be okay with you?
