### ISSUE TITLE
Is it possible to run a single test by name? 

### ISSUE THREAD

**Issue by jcollum** [go-delve/delve#2052]
1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.4.0
Build: $Id: 67422e6f7148fa1efa0eac1423ab5594b223d93b $

2. What version of Go are you using? (`go version`)?
go version go1.14 darwin/amd64

I want to run a single test by name (like `go test ./... -run TestGetBulkUserData`. Is this possible in Delve? [A post on SO](https://stackoverflow.com/a/43403880/30946) implies that it is but that command causes an error. I don't see any documentation that answers this. 

Closest I got was `dlv test --listen=:20000 -- -test.run TestGetBulkUserData`, which resulted in: 

```
Type 'help' for list of commands.
(dlv) exit
```

**Comment by chainhelen** [comment]
```
Type 'help' for list of commands.
(dlv)
```
is right. It run only `TestGetBulkUserData`.  

But then you need to type `b TestGetBulkUserData` and `continue`

**Comment by aarzilli** [comment]
`dlv test package -- -test.run TestName`

**Comment by jcollum** [comment]
Is this in the documentation?
