### ISSUE TITLE
dlv debug kube-apiserver the cpu is very high when execute step by step

### ISSUE THREAD

**Issue by 13567436138** [go-delve/delve#2063]
Please answer the following before submitting your issue:
```
23310 root 20 0 1396024 485428 6984 S 95.3 17.1 0:49.74 dlv
11104 root 20 0 10.2g 133980 23284 S 1.3 4.7 0:39.74 etcd
3126 root 20 0 56624 17812 17396 S 1.0 0.6 0:25.99 systemd-journal
8851 root 20 0 660284 70768 33672 S 1.0 2.5 0:21.57 kubelet
```
Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
```
[root@master01 ~]# dlv version
Delve Debugger
Version: 1.4.0
Build: $Id: 67422e6f7148fa1efa0eac1423ab5594b223d93b $
```
2. What version of Go are you using? (`go version`)?
[root@master01 ~]# go version
go version go1.12.4 linux/amd64
3. What operating system and processor architecture are you using?
centos 7.4
4. What did you do?
remote debug kube-apiserver
5. What did you expect to see?
6. What did you see instead?
cpu is high,debug very slow

**Comment by aarzilli** [comment]
How did you "remote debug kube-apiserver" exactly? Did you start it with `dlv debug` or did you run `dlv attach`? Did this happen as soon as you ran the local headless instance of delve or after you connected to it? How did you connect to it?

**Comment by 13567436138** [comment]
···
dlv --listen=:39999 --headless=true --api-version=2 exec /opt/kube/bin/kube-apiserver -- --basic-auth-file=/etc/kubernetes/auth/basic_auth_file --advertise-address=192.168.198.154 --allow-privileged=true --anonymous-auth=false --authorization-mode=Node,RBAC --bind-address=192.168.198.154 --client-ca-file=/etc/kubernetes/ssl/ca.pem --endpoint-reconciler-type=lease --etcd-cafile=/etc/kubernetes/ssl/ca.pem --etcd-certfile=/etc/kubernetes/ssl/kubernetes.pem --etcd-keyfile=/etc/kubernetes/ssl/kubernetes-key.pem --etcd-servers=https://192.168.198.154:2379,https://192.168.198.155:2379,https://192.168.198.156:2379 --insecure-bind-address=127.0.0.1 --kubelet-https=true --kubelet-client-certificate=/etc/kubernetes/ssl/admin.pem --kubelet-client-key=/etc/kubernetes/ssl/admin-key.pem --service-account-key-file=/etc/kubernetes/ssl/ca-key.pem --service-cluster-ip-range=10.68.0.0/16 --service-node-port-range=20000-40000 --tls-cert-file=/etc/kubernetes/ssl/kubernetes.pem --tls-private-key-file=/etc/kubernetes/ssl/kubernetes-key.pem --requestheader-client-ca-file=/etc/kubernetes/ssl/ca.pem --requestheader-allowed-names= --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --proxy-client-cert-file=/etc/kubernetes/ssl/aggregator-proxy.pem --proxy-client-key-file=/etc/kubernetes/ssl/aggregator-proxy-key.pem --enable-aggregator-routing=true --v=2
···
I run this command on server，then on my windows ,I use goland remote debug，to debug the server

**Comment by dlsniper** [comment]
If you are using GoLand, please make sure that you are using 2020.1.2, as we made a number of performance improvements for the interaction with Delve, see https://blog.jetbrains.com/go/2020/05/06/goland-2020-1-2/#debugger-performance-improvements for details.

I'm not sure if we should continue this on here on GoLand's tracker, https://youtrack.jetbrains.com/issues/Go

**Comment by 13567436138** [comment]
the cpu is high,doesn't because of goland,but dlv,in the server,not client.the cpu is high only when run step by step

**Comment by dlsniper** [comment]
@13567436138 have you upgraded the IDE or not?

**Comment by aarzilli** [comment]
In any case you should pass `--log --log-output=rpc` to delve and post the output.

**Comment by 13567436138** [comment]
my goland is 2020.1

**Comment by 13567436138** [comment]
is this because of the client or server

**Comment by dlsniper** [comment]
> my goland is 2020.1
2020.1 or 2020.1.2? This is important.

> is this because of the client or server
As @aarzilli already mentioned, it's probably better to follow his advice and run your delve server with the parameters he suggested, to understand what happens with the communication between the IDE and delve as well as observe the amount of data passed between these two.

For reference, here's his comment again:
> In any case you should pass `--log --log-output=rpc` to delve and post the output.

**Comment by 13567436138** [comment]
file is too big ,can not upload

**Comment by 13567436138** [comment]
the log is very frequency,running a lot of time

**Comment by 13567436138** [comment]
[dlv.log.txt](https://github.com/go-delve/delve/files/4721135/dlv.log.txt)
one step ,the log output

**Comment by dlsniper** [comment]
I see two calls for `ListFunctionArgs` in that log. Can you please attach a screenshot of the Help | About window?
We may still have a problem invoking API calls twice, but I need to check that first before further investigation.

**Comment by 13567436138** [comment]
I don't understand you.what do you want me to de?

**Comment by aarzilli** [comment]
@dlsniper what I see is that ListLocalVars is large and takes 3~4 seconds to load.

**Comment by 13567436138** [comment]
how to solve?

**Comment by 13567436138** [comment]
is this because of goland or dlv

**Comment by aarzilli** [comment]
I don't think there's anything to do here for us, goland is just asking for a lot.
