### ISSUE TITLE
Confusing --api-version default of 1 and related documentation

### ISSUE THREAD

**Issue by polinasok** [go-delve/delve#2066]
RPC APIv1 is deprecated. Documentation [says](https://github.com/go-delve/delve/blob/master/service/rpc1/readme.txtr) RPC APIv1 is only kept around for backward compatibility and [notes](https://github.com/go-delve/delve/blob/master/Documentation/api/json-rpc/README.md#api-versions) new clients must use v2.

Yet the [--api-version flag](https://github.com/go-delve/delve/blob/f96663a243ac3d844a3e43731d7eaf5b1bf3dfab/cmd/dlv/cmds/commands.go#L118) that sets the API for a headless server defaults to 1. This became a point of confusion in a recent meeting with my workgroup, when developers tried to use the flag default as a way to look up which API to focus the client code on.

It appears that instead of relying on this flag on server start-up (which is not even always possible as the debugger might be started independently), the clients are supposed to force the API to be v2 using [RPCServer.SetApiVersion](https://github.com/go-delve/delve/blob/c06a1a0252ee164a4a775c587396945ab771c498/service/rpccommon/server.go#L387). Yet I do not see this captured in the [documentation](https://github.com/go-delve/delve/blob/master/Documentation/api/json-rpc/README.md#api-versions). 

Using SetApiVersion is indeed what dlv frontend does itself as part of [rpc2 client set up](https://github.com/go-delve/delve/blob/8bb93e9ae19589b7ee665225c2206ef118928ae9/service/rpc2/client.go#L36). And this results in the following a bit unexpected log:
```
$ dlv exec --log --log-output=rpc helloworld
2020-05-27T10:03:11-07:00 info layer=rpc Using API v1
2020-05-27T10:03:11-07:00 debug layer=rpc <- RPCServer.SetApiVersion(
api.SetAPIVersionIn{"APIVersion":2})
2020-05-27T10:03:11-07:00 debug layer=rpc -> *api.SetAPIVersionOut{} error:""
2020-05-27T10:03:11-07:00 debug layer=rpc <-RPCServer.IsMulticlient(rpc2.IsMulticlientIn{})
... more rpc2 calls ...
```

I therefore propose the following improvements (and happy to make all or some these changes myself):
1.  Update --api-version flag default to 2.
2. Update --api-version flag description to stress that rpc2 is the encouraged version for all new clients while rpc1 is only around for backward compatibility. 
3. Update --api-version flag description to mention SetAPIVersion rpc for cases when changing the flag value is outside of user control.
4. Update  [API documentation](https://github.com/go-delve/delve/blob/master/Documentation/api/json-rpc/README.md#api-versions) to encourage using SetAPIVersion to switch to rpc2.

**Comment by chainhelen** [comment]
According to the comment `apiVersion is the requested API version while running headless`, it should be efftive on `headless` mode. I have try those, both ways look like the same result.
