### ISSUE TITLE
Error when trying install delve in traditional way

### ISSUE THREAD

**Issue by kt1755** [go-delve/delve#2067]
https://github.com/go-delve/delve/blob/4be75bec5910d17c119acfd79d9017078e8ae3e3/pkg/proc/native/proc_linux.go#L170

I'm using delve to debug our code inside docker container. And I got error: `# github.com/go-delve/delve/pkg/proc/native
/go/src/github.com/go-delve/delve/pkg/proc/native/proc_linux.go:170:16: undefined: strings.ReplaceAll` when install delve using command `go get github.com/go-delve/delve/cmd/dlv`. Please tell me what happened, and how to fix it.

**Comment by aarzilli** [comment]
Which version of go are you using?

**Comment by chainhelen** [comment]
@aarzilli 

According to [installation doc](https://github.com/go-delve/delve/tree/master/Documentation/installation), `Please note you must have Go 1.10 or higher installed in order to compile Delve.`    
In code, it is `MinSupportedVersionOfGoMinor = 12`. 

Doc need to be changed or I am  wrong?

**Comment by aarzilli** [comment]
Version 1.12 is being tested in CI so that one should be fine.

**Comment by yc-alex-xu** [comment]
I met the same problem with Go 1.10 under Ubuntu too.

$ go version
go version go1.10.4 linux/amd64

**Comment by aarzilli** [comment]
We only test and support the three most recent versions of Go. Use a more recent version of Go or a less recent version of Delve.

**Comment by mmatoscom** [comment]
hi good day guys
i got same error for versions 1.10 and 1.11, when trying to install beego

however using 1.12 I got the following:
`# github.com/gadelkareem/delve/service/debugger
src/github.com/gadelkareem/delve/service/debugger/debugger.go:129:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type *"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value
# github.com/gadelkareem/delve/service/rpccommon
src/github.com/gadelkareem/delve/service/rpccommon/server.go:83:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type *"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value
The command '/bin/sh -c go get github.com/beego/bee' returned a non-zero code: 2`

any clues on how to fix?
thanks!
