### ISSUE TITLE
Get errors while installing:"cannot use ([]rune)(args) (type []rune) as type string in argument to argv.Argv"

### ISSUE THREAD

**Issue by hnzxmutex** [go-delve/delve#2073]
Hey guys,I just get errors while installing delve:"cannot use ([]rune)(args) (type []rune) as type string in argument to argv.Argv"

1. What version of Delve are you using (`dlv version`)?
The newest version, probably 1.4.1 but not install successfully
2. What version of Go are you using? (`go version`)?
go version go1.14.3 darwin/amd64
3. What operating system and processor architecture are you using?
macOS Mojave 10.14/4.2 GHz Intel Core i7
4. What did you do?
Installing delve, running the command "go get github.com/go-delve/delve/cmd/dlv"
5. What did you expect to see?
Build delve successfully.
6. What did you see instead?
$ go get github.com/go-delve/delve/cmd/dlv

go: found github.com/go-delve/delve/cmd/dlv in github.com/go-delve/delve v1.4.1
#github.com/go-delve/delve/pkg/terminal
/Users/shaun/go/pkg/mod/github.com/go-delve/delve@v1.4.1/pkg/terminal/command.go:1045:28: cannot use ([]rune)(args) (type []rune) as type string in argument to argv.Argv
/Users/shaun/go/pkg/mod/github.com/go-delve/delve@v1.4.1/pkg/terminal/command.go:1045:36: undefined: argv.ParseEnv
/Users/shaun/go/pkg/mod/github.com/go-delve/delve@v1.4.1/pkg/terminal/command.go:1046:3: cannot use func literal (type func([]rune, map[string]string) ([]rune, error)) as type argv.Expander in argument to argv.Argv

**Comment by hnzxmutex** [comment]
My bad，I just run the go get command in a directory which has a go.mod file, probably the go.mod file affect the behavior of "go get"

**Comment by xgoeforever** [comment]
I also get this issue in centos7.4 golang-1.13.11，so anyone get this answer?
