### ISSUE TITLE
Can't display go code if I use cgo to import a dynamic library(.so)

### ISSUE THREAD

**Issue by Simon-Zh-0409** [go-delve/delve#2074]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
1.4.0
2. What version of Go are you using? (`go version`)?
1.14.2
3. What operating system and processor architecture are you using?
ubuntu 18.04
4. What did you do?
use dlv to debug go program
5. What did you expect to see?
6. What did you see instead?
Can't display go code if I use cgo to import a dynamic library(.so)

**Comment by Simon-Zh-0409** [comment]
With sources command, I can see there are only files in the dynamic library intead of go file.

**Comment by Simon-Zh-0409** [comment]
@aarzilli Thank you so much for your quick response, that solve the issue.

**Comment by Simon-Zh-0409** [comment]
@aarzilli This issue seems still exist, after your patch, the sources command could see the package code which enable the cgo, but once the dlv hit a breakpoint, it still can't show the code, the reason is dlv move all the source files in the package which enable cgo to the root package, could you help to check this? Thanks a lot.

**Comment by aarzilli** [comment]
I don't understand the problem. Delve doesn't move any source files.

**Comment by Simon-Zh-0409** [comment]
Hi Aarzilli, what I mean is Delve can't find the package enabled the cgo in the right place. Such as, my code path is A.B.cgo.go, but once Delve attach to the process, the command sources show that the package is in the root package but it will still try to find the cgo code in A.B.cgo once hit a breakpoint which will lead can't find file issue. Thanks for your help.

**Comment by aarzilli** [comment]
Do you have a minimal way to reproduce this issue? Maybe a screenshot of what's happening?

**Comment by Simon-Zh-0409** [comment]
Below is the sources command output, socket.go is in a package which enable cgo, you could see that socket.go is in root package, but actually the real location should be another package
![Screen Shot 2020-06-12 at 3 32 49 PM](https://user-images.githubusercontent.com/29631272/84477300-fc502d80-acc1-11ea-8924-d9c89f1dee6c.png)

once hit a break point, it can't find the file in the real location, if the break point is in a package not enable cgo, it could work properly.
![Screen Shot 2020-06-12 at 3 35 21 PM](https://user-images.githubusercontent.com/29631272/84477546-581ab680-acc2-11ea-9127-6771e99fae99.png)
Thanks a lot

**Comment by aarzilli** [comment]
The most likely explanation is that whatever you are using to build your code is passing `-trimpath` to the compiler.
