### ISSUE TITLE
How can I get an older version of dlv that works with go1.10?

### ISSUE THREAD

**Issue by arashout** [go-delve/delve#2076]
Hi I'm trying to get my debugging environment to work after I broke it by briefly experimenting with a newer version of go.
Currently I use go1.10, but it seems that everytime I try to install `dlv` with vscode or by using `go get` I end up with a version that doesn't support go1.10.
When trying to debug in vscode I get:
```
Version of Go is too old for this version of Delve (minimum supported version 1.12, suppress this error with --check-go-version=false)
Process exiting with code: 1
```

1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 1.4.1
Build: $Id: bda606147ff48b58bde39e20b9e11378eaa4db46 $
```
2. What version of Go are you using? (`go version`)?
`go version go1.10 darwin/amd64`
3. What operating system and processor architecture are you using?
MacOS
4. What did you do?
Tried debugging with vscode
5. What did you expect to see?
Debug working
6. What did you see instead?
Error related to mismatched versions of Go and DLV

**Comment by aarzilli** [comment]
```
cd $GOPATH/src/github.com/go-delve/delve
git checkout v1.2.0
make install
```

**Comment by arashout** [comment]
I tried something like this, but I think I might be doing something wrong because it doesn't seem to be compiling on my Mac.
There aren't any instructions for installing from source in the "Mac" installation section of the README.

**Comment by aarzilli** [comment]
you could try `go build github.com/go-delve/delve/cmd/dlv` after cloning.

**Comment by vin047** [comment]
Using go modules (not GOPATH mode), I managed to download an older version of delve using the following command:

`go get github.com/go-delve/delve/cmd/dlv@v1.3.2`

Adjust the `@v1.3.2` accordingly (v1.3.2 is suitable for go 1.11)

**Comment by luojiego** [comment]
![image](https://user-images.githubusercontent.com/3175699/130602321-f86311cc-261a-48c8-ba80-81e73613f2dc.png)

Too bad，In my Windows，go version is 1.14.13，the error dlv version is 1.7.0，Even I install dlv1.3.2 or 1.2.0，Error still exists。
