### ISSUE TITLE
Error reading debug_info: concrete subprogram without address range at 0x3bd499

### ISSUE THREAD

**Issue by siddjain** [go-delve/delve#2080]
This is a question, not an issue.

Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?

```
$ dlv version
Delve Debugger
Version: 1.3.2
Build: $Id: 569ccbd514fc47c8b4c521b142556867ec5e6917 $
```

2. What version of Go are you using? (`go version`)?

```
$ go version
go version go1.13.3 darwin/amd64
```

3. What operating system and processor architecture are you using?

```
$ uname -a
Darwin WITSC02X6385JGH 18.7.0 Darwin Kernel Version 18.7.0: Mon Feb 10 21:08:45 PST 2020; root:xnu-4903.278.28~1/RELEASE_X86_64 x86_64
```

4. What did you do?

I ran `dlv debug` command

5. What did you expect to see?

no errors. 

6. What did you see instead?

```
info layer=debugger launching process with args: [/Users/sjain68/go/src/github.com/siddjain/phf/debugging-fabric/__debug_bin]
error layer=debugger Error reading debug_info: concrete subprogram without address range at 0x31bd92
error layer=debugger Error reading debug_info: concrete subprogram without address range at 0x31dfbd
error layer=debugger Error reading debug_info: could not find abstract origin (0x33508e) of inlined call at 0x334091
```

I want to understand meaning of above error messages.

**Comment by chainhelen** [comment]
There are warnings, not fatal mistakes. It means some debug infos can't be found correctly according to dwarf sections of binary executable.

**Comment by aarzilli** [comment]
If you are using cgo gcc will sometimes produce entries that we can't understand/don't make sense. If you have a concrete problem reopen this issue or open a new one.
