### ISSUE TITLE
make install github.com/go-delve/delve error

### ISSUE THREAD

**Issue by YuHuShangWei** [go-delve/delve#2083]
$ git clone https://github.com/go-delve/delve.git $GOPATH/src/github.com/go-delve/delve
$ cd $GOPATH/src/github.com/go-delve/delve
$ make install

![Screenshot from 2020-06-12 10-19-12](https://user-images.githubusercontent.com/18142345/84457832-386d9900-ac96-11ea-9a14-9ccd23289317.png)

**Comment by chainhelen** [comment]
Can you provide some infomation below?
```
1. What version of Delve are you using (`dlv version`)?
2. What version of Go are you using? (`go version`)?
3. What operating system and processor architecture are you using? (`uname -a` on linux)
```

**Comment by aarzilli** [comment]
Closing, no feedback.
