### ISSUE TITLE
Delve Cannot Debug with Externally compiled plugins

### ISSUE THREAD

**Issue by linkjay** [go-delve/delve#2085]
1. What version of Delve are you using (`dlv version`)? `1.4.1`
2. What version of Go are you using? (`go version`)? `go1.14.4 linux/amd64`
3. What operating system and processor architecture are you using? `Linux 5.7.2-arch1-1 x86_64`

I am currently using VSCode for Go. I have it set up with delve installed. I have a project setup with Go plugins, and in order for me to use those plugins, I have to compile them. I have a build script that will build them all with this command before I launch delve to debug:

`go build -buildmode=plugin -o plugins/plugin.so plugins/plugin.go`

The problem is now when I use delve to launch the process, it works properly, but it throws out this error when loading the plugin:

`2020/06/13 17:44:23 Fatal error when opening plugin! Err: plugin.Open("plugins/plugin"): plugin was built with a different version of package runtime/internal/sys`

I believe this is because Delve uses something different to compile the `main.go` file? I have a test repository here if anyone would like to clone and test: https://github.com/linkjay/go-plugin-bug

My workflow is set up so that I have a task in VSCode that will run `main.go` with Delve, but before hand, it will execute `build.sh` which will compile the plugins. I think what is required here is either a way of building the plugins with Delve, or somehow using the same Go binary to build.

**Comment by chainhelen** [comment]
@linkjay 
```
go build -gcflags="all=-N -l" -buildmode=plugin -o plugins/test-plugin.so plugins/test-plugin.go

// dlv compile
go build -gcflags="all=-N -l" -o main main.go
```
Please keep the `-gcflags="all=-N -l"` when plugin and executable. 

Same as https://github.com/microsoft/vscode-go/issues/3048

**Comment by linkjay** [comment]
Works perfectly!

Thank you.
