### ISSUE TITLE
I can not debug go 1.14  in linux with idea ?

### ISSUE THREAD

**Issue by l-xue-yu** [go-delve/delve#2094]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
1.4.1
2. What version of Go are you using? (`go version`)?
1.14
3. What operating system and processor architecture are you using?
linux x86_64
4. What did you do?
click the debug buutton 
![image](https://user-images.githubusercontent.com/42016055/85945875-2b79c680-b973-11ea-85d5-606dc2c32b13.png)

5. What did you expect to see?
bug the program
6. What did you see instead?
Version of Delve is too old for this version of Go (maximum supported version 1.13, suppress this error with --check-go-version=false)

**Comment by aarzilli** [comment]
You are not using verison 1.4.1. cc @dlsniper

**Comment by dlsniper** [comment]
I can't tell the IDE version, but you are using a very old one (iirc we fixed this in an earlier 2019 build).
Upgrade to 2020.1.3 please and it should be fixed

**Comment by l-xue-yu** [comment]
> I can't tell the IDE version, but you are using a very old one (iirc we fixed this in an earlier 2019 build).
> Upgrade to 2020.1.3 please and it should be fixed

thanks,it is .
