### ISSUE TITLE
ppc64le 

### ISSUE THREAD

**Issue by macthev** [go-delve/delve#2104]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?

Cant run this , won't build.

latest master branch.

2. What version of Go are you using? (`go version`)?

1.14.4

3. What operating system and processor architecture are you using?

RHEL 7.7
ppc64le

4. What did you do?

[root@ppc64host ~]# go get github.com/go-delve/delve/cmd/dlv
go/src/github.com/go-delve/delve/service/debugger/debugger.go:26:2: found packages native (proc.go) and your_operating_system_and_architecture_combination_is_not_supported_by_delve (support_sentinel.go) in /root/go/src/github.com/go-delve/delve/pkg/proc/native
5. What did you expect to see?

No errors

6. What did you see instead?

Unsupported message

**Comment by chainhelen** [comment]
duplicate #1564. (label `kind/enhancement`)
