### ISSUE TITLE
Files specified in //line directive are not made absolute

### ISSUE THREAD

**Issue by nd** [go-delve/delve#2108]
1. What version of Delve are you using (`dlv version`)?

```
Delve Debugger
Version: 1.4.1
Build: 54664c54db768453791c0192646a4366e5ee86f1
```

2. What version of Go are you using? (`go version`)?

```
go version go1.14.6 linux/amd64
```

but it is the same for other go versions

3. What operating system and processor architecture are you using?

linux/amd64, but it is the same on other platforms

4. What did you do?

Debugging code containing `//line` directives. Code has the following structure:

- $GOPATH/gen/f.go:
```
package main

import "gen/pkg"

func main() {
	F("ok")     
	pkg.F("ok")
}

func F(s string) {
//line foo:2
	println(s)
}
```

- $GOPATH/gen/foo:
```
function f(var s) {
  println(s)
}
```

- $GOPATH/gen/pkg/f.go:
```
package pkg

func F(s string) {
//line foo:2
	println(s)
}
```

- $GOPATH/gen/pkg/foo:
```
function f(var s) {
  println(s)
}
```

I put breakpoints into main.F and pkg.F and invoke `bt` when debugger enters the generated code affected by the `//line`directive.

5. What did you expect to see?

Debugger reports absolute file locations `$GOPATH/gen/foo` and `$GOPATH/gen/pkg/foo`.

6. What did you see instead?

Backtrace returns `foo` in both cases.

Log: https://gist.github.com/nd/1ad7960281b44e2f9a669f36722f4551

**Comment by derekparker** [comment]
I don't see this as a bug with Delve.

This is what `objdump` shows:

```
 The File Name Table (offset 0x1c610):
  Entry Dir     Time    Size    Name
  1     0       0       0       <autogenerated>
  2     0       0       0       /go/src/gen/pkg/f.go
  3     0       0       0       foo
```

As you can see there simply is no path information for the file specified in the line directive.

**Comment by nd** [comment]
Filed https://github.com/golang/go/issues/40365.

**Comment by derekparker** [comment]
Closing this as not a Delve bug. Moving discussion to Go.
