### ISSUE TITLE
install dlv error: found packages native (proc.go)...

### ISSUE THREAD

**Issue by hudingchen** [go-delve/delve#2109]
1. What version of Delve are you using (`dlv version`)?
```
v1.4.1
```

2. What version of Go are you using? (`go version`)?
```
go version go1.14.6 windows/386
```

3. What operating system and processor architecture are you using?
```
Windows 10 1803
```

4. What did you do?
```
go get -v github.com/go-delve/delve/cmd/dlv
```
error:
```
go: found github.com/go-delve/delve/cmd/dlv in github.com/go-delve/delve v1.4.1
go\pkg\mod\github.com\go-delve\delve@v1.4.1\service\debugger\debugger.go:25:2: found packages native (proc.go) and your_operating_system_and_architecture_combination_is_not_supported_by_delve (support_sentinel.go) in C:\Users\xxx\go\pkg\mod\github.com\go-delve\delve@v1.4.1\pkg\proc\native
```

Could you tell me how to solve it?

**Comment by chainhelen** [comment]
@hudingchen 
As the message says, dlv don't support windows/386 currently.  

https://groups.google.com/d/msg/delve-dev/uUkP7MjET6Q/PX4o4r9OBwAJ  
duplicate [32-bit Windows support # 656](https://github.com/go-delve/delve/issues/656)

**Comment by hudingchen** [comment]
@chainhelen 
thank you for your reply.
