### ISSUE TITLE
use dlv attach to trace app, is there a method to quick exit

### ISSUE THREAD

**Issue by tty5** [go-delve/delve#2114]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.4.0
Build: 81a86086dd9974d5bab76b1749d7450bb6b5cfab

2. What version of Go are you using? (`go version`)?
go version go1.14.4 linux/amd64

3. What operating system and processor architecture are you using?
linux

4. What did you do?
dlv attach pid --init dlv-init

cat dlv-init
t b1 http-s.go:100
on b1 p r.Method

c

5. What did you expect to see?
use ctrl c to exit dlv will cause app pause running, is there can quit quickly

6. What did you see instead?

**Comment by aarzilli** [comment]
There isn't, ctrl-c will go back to the prompt where you can use `exit`. This is how other debuggers also behave and I think it's fine, my inclination would be to close this without doing anything. cc @derekparker.

**Comment by derekparker** [comment]
I agree, I don't think there's really a feature to add or something to fix here. Going to close this for now, but feel free to respond with more information if there's a concrete reason the current approach to stopping and exiting doesn't work for you.
