### ISSUE TITLE
The debug result is different with go run result ( using unsafe. Pointer, got []byte cap = 0 and len >0 )

### ISSUE THREAD

**Issue by fxxkingNoob** [go-delve/delve#2115]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.4.0
Build: $Id: 67422e6f7148fa1efa0eac1423ab5594b223d93b $

2. What version of Go are you using? (`go version`)?
go version go1.13.9 darwin/amd64

3. What operating system and processor architecture are you using?
mac OS 10.15.4
darwin/amd64

4. What did you do?
Debug with goland

5. What did you expect to see?

- The Result same with go run
- The unsafe.Pointer didnt return []byte with cap = 0 and len > 0

6. What did you see instead?

- The debug result is different with go run result
- I got a []byte with  cap = 0 and len > 0

```
package main

import (
   "unicode/utf8"
   "unsafe"
)

func main() {
   b := stringToBytes("模板ID")
   println(len(b))
   println(cap(b))
   r, width := utf8.DecodeRune(b[6:])
   println(r)
   println(width)
   println(b[0:5])
}

func stringToBytes(s string) []byte {
   return *(*[]byte)(unsafe.Pointer(&s))
}
```

go run print:
```
8
824633993168
73
1
[5/824633993168]0x107187a
```

debug result
```
8
0
65533
1
panic: runtime error: slice bounds out of range [:5] with capacity 0

goroutine 1 [running]:
main.main()
        /xxxx/main.go:19 +0x1c2
Exiting.
```

**Comment by qingyunha** [comment]
You can try `go build -gcflags "all=-N -l"` that was `delve`  used.  this issue may not about delve.

**Comment by chainhelen** [comment]
@fxxkingNoob I have try, as @qingyunha say.

```
go version go1.14 linux/amd64
```

1.
```
go build -o main1 main.go 

./main1  

8
824633927632
73
1
[5/824633927632]0x475d75
```

2. 
```
go build -o main2 -gcflags="all=-N -l" main.go

./main2

8
0
65533
1
panic: runtime error: slice bounds out of range [:5] with capacity 0

goroutine 1 [running]:
main.main()
	/home/chainhelen/main.go:15 +0x1c2

```

Need to create one issue on https://github.com/golang/go/issues for tracing.

**Comment by aarzilli** [comment]
The correct way to convert a string to a `[]byte` is doing a cast without using unsafe.Pointer. The "correct" way to do this unsafely, avoiding an allocation, is to cast the string to `reflect.StringHeader`, cast a `[]byte` variable to a `reflect.SliceHeader` and copy the fields manually between the two. As it is, your code is depending on uninitialized memory.
