### ISSUE TITLE
Sometimes ListGoroutines hangs on windows

### ISSUE THREAD

**Issue by nd** [go-delve/delve#2119]
1. What version of Delve are you using (`dlv version`)?

```
Delve Debugger
Version: 1.5.0
Build: ff20b316f353f07d13262cebe7a2a8f56bd2edd5
```

but I've also seen it in

```
Delve Debugger
Version: 1.4.1
Build: f9c8f7f55b798a472013dd6a20bf688387eb0c53
```

2. What version of Go are you using? (`go version`)?

```
go version go1.15beta1 windows/amd64
```

3. What operating system and processor architecture are you using?

windows/amd64

4. What did you do?

Debugged the program:
https://github.com/dlsniper/golandtipsandtricks/blob/master/run-test-debug/tip003/main.go
and listed goroutines.

5. What did you expect to see?

ListGoroutines call returns.

6. What did you see instead?

ListGoroutines call hangs inside a system call:
```
<unknown>
syscall.Syscall6(syscall_windows.go:201)
github.com/go-delve/delve/pkg/proc/native._ReadProcessMemory(zsyscall_windows.go:112)
github.com/go-delve/delve/pkg/proc/native.(*nativeThread).ReadMemory(threads_windows.go:165)
github.com/go-delve/delve/pkg/proc.(*stackIterator).readRegisterAt(stack.go:519)
github.com/go-delve/delve/pkg/proc.(*stackIterator).executeFrameRegRule(stack.go:480)
github.com/go-delve/delve/pkg/proc.(*stackIterator).advanceRegs(stack.go:443)
github.com/go-delve/delve/pkg/proc.(*stackIterator).Next(stack.go:239)
github.com/go-delve/delve/pkg/proc.(*G).UserCurrent(variables.go:490)
github.com/go-delve/delve/service/api.ConvertGoroutine(conversions.go:266)
github.com/go-delve/delve/service/debugger.(*Debugger).Goroutines(debugger.go:1335)
github.com/go-delve/delve/service/rpc2.(*RPCServer).ListGoroutines(server.go:559)
runtime.call64(asm_amd64.s:1)
reflect.Value.call(value.go:460)
reflect.Value.Call(value.go:321)
github.com/go-delve/delve/service/rpccommon.(*ServerImpl).serveJSONCodec.func2(server.go:311)
github.com/go-delve/delve/service/rpccommon.(*ServerImpl).serveJSONCodec(server.go:313)
runtime.goexit(asm_amd64.s:1373)
github.com/go-delve/delve/service/rpccommon.(*ServerImpl).Run.func1(server.go:151)
```

I've waited for a few minutes, the stack is always the same. I have a dump of a delve process if needed.

So far I've seen such hanging only twice, usually ListGoroutines works fine.

**Comment by aarzilli** [comment]
> I have a dump of a delve process if needed.

I'd like to take a look.

**Comment by nd** [comment]
executable: https://drive.google.com/file/d/1dPuJmdHQRF6NuQTiB-Garrf4CqjqcFu8/view?usp=sharing
dump: https://drive.google.com/file/d/1y50-8zwzYMTk8i0zDQ4Be283zZpg8jZt/view?usp=sharing

**Comment by aarzilli** [comment]
I don't see anything obviously wrong in the dump and MSDN doesn mention anything about ReadProcessMemory blocking. Do you mind trying #2132?

**Comment by aarzilli** [comment]
PS. if it doesn't work I'd like another dump.

**Comment by nd** [comment]
I was wrong, it is not hanging in system call, the problem is that iterator in proc.G.UserCurrent doesn't advance properly and returns the same frame again and again with frame.Call.Fn == nil, it cannot leave the loop.

**Comment by nd** [comment]
It still happens in #2132.

**Comment by nd** [comment]
Correction: it is not the same frame again and again: it repeats every 40 iterations. I'm judging by frame.lastpc.
