### ISSUE TITLE
dlv locals not intact

### ISSUE THREAD

**Issue by PandaTea** [go-delve/delve#2120]
1. What version of Delve are you using (`dlv version`)?
1.5.0
Build: $Id: ca5318932770ca063fc9885b4764c30bfaf8a199 $

2. What version of Go are you using? (`go version`)?
go1.14.4 darwin/amd64

3. What operating system and processor architecture are you using?
macos 10.15.6

4. What did you do?
i go build my project with params  -gcflags="-N -l"
and i run 
dlv attach `pid`
and `list`
![image](https://user-images.githubusercontent.com/29042336/89396587-50ffaa00-d741-11ea-9e25-a45cdaa091bf.png)
everything goes ok

but
i run `locals` for list Print local variables
![image](https://user-images.githubusercontent.com/29042336/89396938-c8353e00-d741-11ea-92c7-37aa428fc523.png)

its merely print `amount` in locals result
but lack of. `from` and `to` in this function 
![image](https://user-images.githubusercontent.com/29042336/89397029-ea2ec080-d741-11ea-95de-ce055688d313.png)

5. What did you expect to see?

how can i find the value of `from` and `to` local variables?

**Comment by chainhelen** [comment]
@PandaTea 
I notice the msg `Warning: debugging optimized function` on your screen shot. 
So could you try   `-gcflags="all=-N -l"` instead of ` -gcflags="-N -l"`

**Comment by PandaTea** [comment]
i love u
