### ISSUE TITLE
Should dlv test chdir to the package directory like go test does?

### ISSUE THREAD

**Issue by abustany** [go-delve/delve#2125]
1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 1.4.1
Build: $Id: bda606147ff48b58bde39e20b9e11378eaa4db46 $
```

2. What version of Go are you using? (`go version`)? `go version go1.13.6 linux/amd64`
3. What operating system and processor architecture are you using? Linux x86/64
4. What did you do?
```
# On a test that attempts to read a file from ./testdata/foo.txt
dlv test ./mypackage
```

5. What did you expect to see?
Similar to what `go test` does, `dlv test` chdirs to `./mypackage` before running the test, so the test can open the file

6. What did you see instead?
Test fails to open the file, because dlv stays in the current directory

**Comment by chainhelen** [comment]
Ps: 

`--wd string            Working directory for running the program. (default ".")`  
`dlv test --wd ./mypackage ./mypackage` .

**Comment by abustany** [comment]
Thanks for the tip, I completely overlooked that flag! I guess the question of whether it should be a default still stands, but I'd also understand not wanting to break existing behavior...
