### ISSUE TITLE
delve should produce an error when the go command cannot be found

### ISSUE THREAD

**Issue by lolbinarycat** [go-delve/delve#2126]
I was having some problems with my `$PATH`, and tried running `dlv test`, and it just did nothing.

1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.5.0
Build: $Id: ca5318932770ca063fc9885b4764c30bfaf8a199 $
2. What version of Go are you using? (`go version`)?
go version go1.15 linux/amd64
3. What operating system and processor architecture are you using?
linux/amd64
4. What did you do?
run `dlv test` with `$GOPATH/bin` in `$PATH`, but not `$GOROOT/path`.
5. What did you expect to see?
An error, an exit code, or something similar.
6. What did you see instead?
Nothing whatsoever.

**Comment by chainhelen** [comment]
@lolbinarycat  
1. What's the path of  package which you want to debug?
2. Can you list all files in $GOPATH/bin where you run execution ?

**Comment by lolbinarycat** [comment]
I don't really know why that matter, as the bug isn't dependant on any of those things, all you need to replecate is `PATH=$GOPATH/bin dlv test`. You will get no output (although you will get a silent exit code of 1, you can check with `echo $?`).
I don't really know why that matter, as the bug isn't dependant on any of those things, all you need to replecate is `PATH=$GOPATH/bin dlv test`. You will get no output (although you will get a silent exit code of 1, you can check with `echo $?`).

But if you insist:

1. `go/src/github.com/lolbinarycat/hookshot-oak/`
2. `
But if you insist:
1. `go/src/github.com/lolbinarycat/hookshot-oak/`
2. `dewm  dlv  gopls`
