### ISSUE TITLE
Get error "function calls not allowed without using 'call'" when trying to access field via "print" direct access

### ISSUE THREAD

**Issue by jrryjcksn** [go-delve/delve#2137]
1. What version of Delve are you using (`dlv version`)?
```
Version: 1.5.0
Build: 07c9163c52b673eb9bd6aeca52fe98312f2fb0fa
```
2. What version of Go are you using? (`go version`)?
```
go version go1.14.4 linux/amd64
```
3. What operating system and processor architecture are you using?
```
Ubuntu 18.04 x86_64
```
4. What did you do?
```
(dlv) p obj
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.Unstructured {
	Object: map[string]interface {} [
		"apiVersion": *(*interface {})(0xc00040fa68), 
		"kind": *(*interface {})(0xc00040fa78), 
		"metadata": *(*interface {})(0xc00040fa88), 
	],}
(dlv) p *((*"interface{}")(0xc00040fa78))
Command failed: function calls not allowed without using 'call'
```
5. What did you expect to see?
The contents of the "kind" field 
6. What did you see instead?
`Command failed: function calls not allowed without using 'call'`

**Comment by aarzilli** [comment]
You have to put a space before the curly brace: `p *((*"interface {}")(0xc00040fa78))`
