### ISSUE TITLE
Retrieve go module information

### ISSUE THREAD

**Issue by quoctruong** [go-delve/delve#2145]
1. What version of Delve are you using (`dlv version`)?
`1.4.0`
2. What version of Go are you using? (`go version`)?
`1.14`
3. What operating system and processor architecture are you using?
`linux/amd64`

Is there a way to retrieve the name of the go module of the debug program launched through dlv?

**Comment by quoctruong** [comment]
@aarzilli For example, in this Go folder, the `go.mod` has `module frontend`. From a breakpoint set in the `main.go` file, how do I get this `frontend` name?

**Comment by hyangah** [comment]
If you have access to the source code the `go list` command will provide the information about the module in "Module" field.

```
$ go list -m -f '{{.Dir}} {{.Path}}'
/Users/hakim/projects/cloud-code-samples/golang/go-guestbook/src/frontend frontend
```

Or even you can just parse the `go.mod` file :-)

If you don't have access to the source code
  - if you can access the binary, `go version -m <binary>` is convenient. 

```
  $ go version -m frontend
frontend: go1.14.5
	path	frontend
	mod	frontend	(devel)	
```
 -  if the binary is not locally accessible but you have to work through delve running remotely, retrieving the variable info `runtime.modinfo[16:]` is one option. Plain text, new line separated.

```
(dlv) p runtime.modinfo[16:]
"path\tfrontend\nmod\tfrontend\t(devel)\t\n�2C1�\x18 r\x00�B\x10A\x16��...+-10 more"
```

**Comment by quoctruong** [comment]
Thanks @hyangah! I'll use `p runtime.modinfo[16:]`.
