### ISSUE TITLE
I can't debug with dlv when importing the "net" package

### ISSUE THREAD

**Issue by shangruitong** [go-delve/delve#2153]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.4.1
Build: $Id: bda606147ff48b58bde39e20b9e11378eaa4db46 $
2. What version of Go are you using? (`go version`)?
go version go1.14.3 linux/amd64
3. What operating system and processor architecture are you using?
linux
x86_64
4. What did you do?
dlv debug main.go
5. What did you expect to see?
I can debug the program
6. What did you see instead?
process xxx has exited with status 0

**Comment by aarzilli** [comment]
Can not reproduce.

**Comment by aarzilli** [comment]
Closing, no user feedback.
