### ISSUE TITLE
Add ability to chose the base used to print integers

### ISSUE THREAD

**Issue by daniel-santos** [go-delve/delve#2159]
Delve 1.5.0
Go 1.14.7 linux/amd64
Gentoo

Printing a pointer variable from within delve gives a BEAUTIFUL pretty-print of the struct it points to, but does not display the address.  Attempting to print the address of the expression (double indirection), only gives the address of the pointer variable its self.

```
(dlv) p a
*main.A {
        number: 1,}
(dlv) p &a
(**main.A)(0xc000167ae8)
(dlv) p uintptr(a)
824633917608
```

824633917608 is 0xc0000300a8 in hex.  I suggest that printing any pointer variable display the address in additional to the pretty-print of the dereferenced value.

**Comment by aarzilli** [comment]
`p uintptr(a)`

**Comment by daniel-santos** [comment]
> `p uintptr(a)`

Well yes, I mentioned that, but can you format it as hex?  I'm new to Go and delve, but I did try `p/x uintptr(a)` to no avail.

**Comment by aarzilli** [comment]
> > `p uintptr(a)`
> 
> Well yes, I mentioned that, but can you format it as hex? I'm new to Go and delve, but I did try `p/x uintptr(a)` to no avail.

Oh, sorry I didn't see that. No we don't have an option to change how we print numbers.

**Comment by daniel-santos** [comment]
Thank you.  Of course, in lieu of that (or even in addition to) it would be nice to get to see the address with a normal print.  I understand _why_ you dereference it by default, since that's what Go does with the dot operator, but it's not what anyone familiar with gdb or other debuggers would expect to see.  Perhaps even an option that you can set for it?

Along those same lines, some (apparently) people don't like the pretty-printed structs, so having an option could be added to disable that too.

The more I talk, the more I feel like I'll be expected to produce the patches, so I'll shut up here. :)

**Comment by aarzilli** [comment]
> The more I talk, the more I feel like I'll be expected to produce the patches, so I'll shut up here. :)

Realistically you should anyway. This interface has been like this for a while so the set of people who care enough about these features to produce patches appears to be empty.

**Comment by daniel-santos** [comment]
Yeah, I was looking at it this morning.  This may not sound original, as it mirrors gdb, but I'm thinking that there needs to be some fairly universal modifiers for `x`, `p` and other similar commands.  If you want hex with `x`, you need to type `x -fmt hex` and if you want 20 hex bytes, you have to type `x -fmt hex -len 20`, which is quite a lot.  In gdb, you get the same with `x/20xb`.

Reading up a tiny bit on starlink, integrating the modifier into the command may not be feasible or desirable.  So I'm thinking of proposing modifiers as any expression that begins with `/`, so that what I want to do could be accomplished with `print /x unitptr(a)` or even `x /xa &a` -- are you immediately aware of any conflicts that could cause?  I don't think any other valid expression could start with a `/`.

**Comment by aarzilli** [comment]
The problem is syntactic consistency. We don't use '/' for options anywhere else, we use '-'. Except of course that options for 'print' can't start with '-' because that could be a valid expression. I thought about using '%' as a separator, it can't be the start of an expression and it could have a syntax similar to fmt escapes.

>  If you want hex with x,

hex is the default for examinemem. I wouldn't muddle the design of 'print' with concerns about examinemem, even in gdb the options to print are a small subset of what x takes.
