### ISSUE TITLE
install

### ISSUE THREAD

**Issue by antichown** [go-delve/delve#2175]
Installing github.com/go-delve/delve/cmd/dlv FAILED

1 tools failed to install.

dlv: failed to install [object Object]: Error: Command failed: /usr/bin/go get -v github.com/go-delve/delve/cmd/dlv
go: finding github.com/go-delve/delve/cmd/dlv latest
go: finding github.com/go-delve/delve/cmd latest
# github.com/go-delve/delve/cmd/dlv
/usr/bin/ld: /home/linux/.cache/go-build/f4/f482dc75e096be0abb4391fc133d78f1985c996cfb8b1dfa1a68e2cf0e4d905a-d(_go_.o): in function `go.starlark.net..z2fstarlark.hashString':
/home/linux/go/pkg/mod/go.starlark.net@v0.0.0-20190702223751-32f345186213/starlark/hashtable.go:357: undefined reference to `runtime.stringHash'
collect2: error: ld returned 1 exit status
 undefined  

linux@root:~$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/linux/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/linux/go"
GOPROXY=""
GORACE=""
GOROOT="/usr"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/gcc/x86_64-linux-gnu/9"
GCCGO="/usr/bin/x86_64-linux-gnu-gccgo-9"
CC="x86_64-linux-gnu-gcc-9"
CXX="x86_64-linux-gnu-g++-9"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build568602838=/tmp/go-build -gno-record-gcc-switches -funwind-tables"

**Comment by aarzilli** [comment]
`go version`?

**Comment by antichown** [comment]
> `go version`?

go version
go version go1.12.2 gccgo (Ubuntu 9.3.0-10ubuntu2) 9.3.0 linux/amd64

**Comment by aarzilli** [comment]
We only support down to current_version-2, so the minimum for delve 1.5.0 is go 1.13. Downgrade delve or upgrade go.
