### ISSUE TITLE
"dlv debug" leads to ld errors: undefined reference to `mk_datum'

### ISSUE THREAD

**Issue by balta2ar** [go-delve/delve#2187]
Hi. I may be missing something, but here we go:
```
$ go get -u github.com/go-delve/delve/cmd/dlv
$ git clone --depth=1 https://github.com/cfdrake/go-gdbm && cd go-gdbm
$ go build
$ go test -v
=== RUN   TestVersion
--- PASS: TestVersion (0.00s)
=== RUN   TestKeys
--- PASS: TestKeys (0.01s)
=== RUN   TestRecreate
--- PASS: TestRecreate (0.00s)
=== RUN   TestWriteErrorWhenReader
--- PASS: TestWriteErrorWhenReader (0.01s)
=== RUN   TestReplace
--- PASS: TestReplace (0.01s)
=== RUN   TestExists
--- PASS: TestExists (0.01s)
=== RUN   TestDelete
--- PASS: TestDelete (0.01s)
=== RUN   TestReorganize
--- PASS: TestReorganize (0.01s)
=== RUN   TestSync
--- PASS: TestSync (0.01s)
PASS
$ dlv debug
# _/home/ybochkarev/dev/from-src/go-gdbm
/usr/bin/ld: $WORK/b001/_x002.o: in function `_cgo_d74df84b6f3c_Cfunc_mk_datum':
/tmp/go-build/cgo-gcc-prolog:300: undefined reference to `mk_datum'
collect2: error: ld returned 1 exit status
exit status 2
```

go-gdbm has this in its gdbm.go:
```
// #cgo CFLAGS: -std=gnu99
// #cgo LDFLAGS: -lgdbm
// #include <stdlib.h>
// #include <gdbm.h>
// #include <string.h>
// inline datum mk_datum(char * s) {
//     datum d;
//     d.dptr = s;
//     d.dsize = strlen(s);
//     return d;
// }
import "C"
```

Maybe it doesn't make sense to debug a library using delve, but I get exactly the same output when I debug (**debug**, not **run**) a test of a program that uses go-gdbm in GoLand 2020.2.3. I looked into it and it boiled down to `dlv debug`.

1. What version of Delve are you using (`dlv version`)?
Version: 1.5.0
Build: $Id: ca5318932770ca063fc9885b4764c30bfaf8a199
2. What version of Go are you using? (`go version`)?
go version go1.13.4 linux/amd64
3. What operating system and processor architecture are you using?
Ubuntu 20.04.1 LTS x86_64 GNU/Linux

**Comment by aarzilli** [comment]
What happens if you do `CGO_CFLAGS='-O0 -g' go build -gcflags='all=-N -l'` on the same directory? I think this could be a bug in Go, so you should also try with 1.15.x so we can be sure that it hasn't already been fixed.

**Comment by balta2ar** [comment]
Tried 1.13.4 with:
```
→ CGO_CFLAGS='-O0 -g' go build -gcflags='all=-N -l'
# _/home/ybochkarev/dev/from-src/go-gdbm
/usr/bin/ld: $WORK/b001/_x002.o: in function `_cgo_d74df84b6f3c_Cfunc_mk_datum':
/tmp/go-build/cgo-gcc-prolog:300: undefined reference to `mk_datum'
collect2: error: ld returned 1 exit status

# compiles OK
→ CGO_CFLAGS='-O1 -g' go build -gcflags='all=-N -l'

# compiles OK
→ CGO_CFLAGS='-O2 -g' go build -gcflags='all=-N -l'
```
Switched to 1.15.2:
```
→ CGO_CFLAGS='-O0 -g' go build -gcflags='all=-N -l'
# _/home/ybochkarev/dev/from-src/go-gdbm
/usr/bin/ld: $WORK/b001/_x002.o: in function `_cgo_d74df84b6f3c_Cfunc_mk_datum':
/tmp/go-build/cgo-gcc-prolog:300: undefined reference to `mk_datum'
collect2: error: ld returned 1 exit status

# compiles OK
→ CGO_CFLAGS='-O1 -g' go build -gcflags='all=-N -l'

# compiles OK
→ CGO_CFLAGS='-O2 -g' go build -gcflags='all=-N -l'
```

Consequently, this also works:
```
$ CGO_CFLAGS='-O1 -g' dlv debug
```

I wonder how I can forward that flag to GoLand :thinking: I have it installed on snap, so I tried to substitute dlv with a wrapper:
```
→ pwd && ls -1
/snap/goland/current/plugins/go/lib/dlv/linux
dlv
dlv-orig

→ cat dlv
#!/bin/bash

ORIG_DLV=/snap/goland/current/plugins/go/lib/dlv/linux/dlv-orig
CGO_CFLAGS='-O1 -g' $ORIG_DLV $*
```
But that didn't have any effect, compilation still failed. Then I used opensnoop (https://github.com/iovisor/bcc/blob/master/tools/opensnoop.py) to see which processes are executed by GoLand:
```
$ sudo execsnoop-bpfcc -Tx > snoop.txt
```
After some filtering I found no evidence of dlv or delve keywords in the output, but there was this:
```
/home/ybochkarev/.gvm/gos/go1.15.2/bin/go test -c -o /tmp/___go_test_company_project_internal_db -gcflags all=-N -l company/project/internal/db
```

So I went for the hacky substitution again:
```
$ pwd
/home/ybochkarev/.gvm/gos/go1.15.2/bin
$ ls -1
go
gofmt
go-orig
$ cat go
#!/bin/bash

CGO_CFLAGS='-O1 -g' /home/ybochkarev/.gvm/gos/go1.15.2/bin/go-orig $*
```
This is terrible but at least I managed to get my project running in a debugger. Though I don't know whether `-O1` will bring any issues to the debugging process.

How do we proceed from here? Should I create an issue in golang repo?

**Comment by aarzilli** [comment]
As far as I know goland doesn't use delve to build binaries, it just calls go directly with the appropriate setup (which is the same we use) and then uses `dlv exec` to debug the executable.

I think you should report this bug to golang, and include the gcc version on the report.

**Comment by aarzilli** [comment]
PS. as long as you don't set breakpoints in C code, or step into it, the `-O1` won't affect the debugger.

**Comment by dlsniper** [comment]
Sorry to jump in :)

> I wonder how I can forward that flag to GoLand

In GoLand, you can add the `CGO_CFLAGS='-O1 -g'` environment variables to the Run Configuration environment variables section, see [our documentation](https://www.jetbrains.com/help/go/creating-and-editing-run-debug-configurations.html#2fc1d) on how to do this.

As a note, when running a Debug session on a run configuration, the IDE should add automatically these environment variables `CGO_CFLAGS="-O -g"`.

> As far as I know goland doesn't use delve to build binaries, it just calls go directly with the appropriate setup (which is the same we use) and then uses dlv exec to debug the executable.

That is correct. Setting those environment variables should be sent to both the `go build` and the `delve exec` steps.

**Comment by balta2ar** [comment]
After a bit of debugging I stared seeing `R0` and `R1` in the list of variables in GoLand. Must be processor registers, never saw them in the GoLand debugger before.

**Comment by aarzilli** [comment]
Under what circumstances are you seeing R0/R1?

**Comment by balta2ar** [comment]
Just when debugging a random test, but I can't reproduce it anymore now :( I've upgraded from go1.13 to go1.15 and from gcc9 to gcc10 along the way, maybe it had some effect. Not a big deal though, I'll report reproducible steps if I can manage to catch it again.

**Comment by aarzilli** [comment]
> Not a big deal though, I'll report reproducible steps if I can manage to catch it again.

Thanks. I'm closing this since there's an upstream bug. Feel free to open a new bug for this.
