### ISSUE TITLE
Build flags in eval.go, proc_test.go (gollvm; Go 1.15.2)

### ISSUE THREAD

**Issue by advancedwebdeveloper** [go-delve/delve#2191]
Hi.
I am using [gollvm](https://go.googlesource.com/gollvm/) - my "release" build could be found [here](https://drive.google.com/file/d/1n7vV2GPG09oftZj7jWceH3o23A5VOaYG/view?usp=sharing).

> $ make
> # github.com/go-delve/delve/pkg/proc
> pkg/proc/eval.go:653:9: conversion from int64 to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
> # github.com/go-delve/delve/pkg/proc_test
> pkg/proc/proc_test.go:32:24: github.x2ecom/go-delve/delve/pkg/proc.LoadConfig composite literal uses unkeyed fields
> pkg/proc/proc_test.go:2656:33: github.x2ecom/go-delve/delve/pkg/proc.LoadConfig composite literal uses unkeyed fields
> make: *** [Makefile:19: vet] Error 2

Here is my environment:

> $ go version
> go version go1.15.2 gollvm LLVM 12.0.0git linux/amd64

> $ go env
> GO111MODULE=""
> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/home/oceanfish81/.cache/go-build"
> GOENV="/home/oceanfish81/.config/go/env"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GOINSECURE=""
> GOMODCACHE="/home/oceanfish81/go/pkg/mod"
> GONOPROXY=""
> GONOSUMDB=""
> GOOS="linux"
> GOPATH="/home/oceanfish81/go"
> GOPRIVATE=""
> GOPROXY="https://proxy.golang.org,direct"
> GOROOT="/home/oceanfish81/gollvm_dist"
> GOSUMDB="sum.golang.org"
> GOTMPDIR=""
> GOTOOLDIR="/home/oceanfish81/gollvm_dist/tools"
> GCCGO="/home/oceanfish81/gollvm_dist/bin/llvm-goc"
> AR="ar"
> CC="/usr/bin/clang"
> CXX="/usr/bin/clang++"
> CGO_ENABLED="1"
> GOMOD="/home/oceanfish81/go_projects/delve/go.mod"
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build260809972=/tmp/go-build -gno-record-gcc-switches -funwind-tables"
> 

CC @ianlancetaylor @thanm @cherrymui

**Comment by ianlancetaylor** [comment]
The "uses unkeyed fields" warning is an issue in x/tools/go/analysis/passes/composite.  It recognizes that the type is local when using the gc compiler, but not when using GoLLVM.  Please open an issues at https://golang.org/issue against x/tools/go/analysis.  Thanks.

It looks like the other error ("conversion from int64 to string") was fixed by f9c8f7f55b798a472013dd6a20bf688387eb0c53.

**Comment by aarzilli** [comment]
Closing, see other response. BTW I don't know how well delve will work with executables produced by gollvm. Probably not at all.
