### ISSUE TITLE
is dlv support until or temp breakpoint?

### ISSUE THREAD

**Issue by tty5** [go-delve/delve#2200]
temp breakpoint can remove bp auto after hit. is dlv support it?

or until command that run to specific line for debug

**Comment by aarzilli** [comment]
I think this is a duplicate of #2197

**Comment by popeye8777** [comment]
Hell I'm trying to open it lol we got this

**Comment by aarzilli** [comment]
Closing, duplicate of #2197

**Comment by popeye8777** [comment]
> temp breakpoint can remove bp auto after hit. is dlv support it?
> 
> or until command that run to specific line for debug .... I am new to this... I have only begin in June and I really don't know the codes just getting used to them.
Hell I just learned how make a issue and a pull report and just now figured out how to send messages I don't know how to set the respiratory I know how to do the work my Android does it in simplory mode and then I transfer it into the language......I have worked at figuring out things all day and night just to be this again it's all good thank you
