### ISSUE TITLE
Order of execution of RPCServer.Command requests is not guaranteed

### ISSUE THREAD

**Issue by nd** [go-delve/delve#2216]
1. What version of Delve are you using (`dlv version`)?

```
Version: 1.5.0
Build: 775c923ec41e92db72122482d69343ef712546c7
```

2. What version of Go are you using? (`go version`)?
```
go version go1.15 windows/amd64
```

But it happens with other go versions as well.

3. What operating system and processor architecture are you using?
```
windows/amd64
```

But it happens on other OSes as well, I've seen it on mac.

4. What did you do?

Compiled the program with debug options:

```
package main

import "time"

func main() {
	for {
		time.Sleep(time.Second)
	}
}
```

Ran it, attached Delve to the process in headless mode and connected to the Delve from GoLand. After that disconnected with the option to keep the process under debug running.

5. What did you expect to see?

Delve responds to the Detach command and exists, the program continues running.

6. What did you see instead?

In some cases Delve doesn't respond to the Detach command and doesn't exit.

It doesn't always happen, sometimes it works as expected.

Expected behavior log:
https://gist.github.com/nd/4a04aabf51a16368719316de1247fab1

Unexpected behavior log:
https://gist.github.com/nd/70d1a3592647433c21f9afe7a81c918f

**Comment by aarzilli** [comment]
I think this could be happening because we are executing simultaneously received commands out of order. It looks like in the second log halt executes before continue and detach hangs because continue is in progress. Can you put a pause between continue and halt in your test so that we can determine if that's the cause?

**Comment by nd** [comment]
Looks like adding 500ms delay before sending halt helps.
