### ISSUE TITLE
Command failed: could not restore registers: bad address

### ISSUE THREAD

**Issue by lberki** [go-delve/delve#2219]
Delve apparently cannot evaluate expressions, even in the simplest cases. Reproduction:

```
$ cat > hello.go <<'EOF'
package main

import "fmt"

func Add(a, b int) int {
        return a + b
}

func main() {
        fmt.Println("Hello, World")
        fmt.Printf("The result is %d\n", Add(1, 2))
}
EOF
$ dlv debug
(dlv) b hello.go:11
Breakpoint 1 set at 0x4bc67a for main.main() ./hello.go:11
(dlv) c
...
(dlv) call Add(4,5)
> main.main() ./hello.go:11 (hits goroutine(1):2 total:2) (PC: 0x4bc67a)
Command failed: could not restore registers: bad address
```

I expected to see "9" or some version of it. It looks like the only plausible place where this could come from is one of these `SYS_PTRACE` calls:

https://github.com/go-delve/delve/blob/3c8d4d52b825e313f21824da63c0904ba2ebb76e/pkg/proc/native/threads_linux_amd64.go#L34

but I'm afraid my knowledge of ptrace isn't enough to go further. This is similar to https://github.com/go-delve/delve/issues/1802, except completely reproducible.

Delve version:
```
Delve Debugger
Version: 1.5.0
Build: $Id: ca5318932770ca063fc9885b4764c30bfaf8a199 $
```

Go version: `go version go1.15 linux/amd64`
OS: `5.7.10-1rodete2-amd64 #1 SMP Debian 5.7.10-1rodete2 (2020-08-12 > 2018) x86_64 GNU/Linux` (Xeon Gold 6154 in case that matters)

**Comment by aarzilli** [comment]
What output do you get from `regs -a`?

**Comment by lberki** [comment]
A completely normal-looking register dump. See here: https://gist.github.com/lberki/f59885273e3f1a13f0d954b93094b89c

**Comment by aarzilli** [comment]
Can you try #2220 and see what happens, both `regs -a` and `call Add(4,5)`. This has something to do with you combination of kernel and CPU so I can't test it.

**Comment by lberki** [comment]
```
git clone https://github.com/aarzilli/delve delve
cd delve
git fetch origin fix2173
git checkout FETCH_HEAD # git log says I'm at dcac2e6cea
make install
ls -l $GOPATH/bin/dlv  # mtime is recent
$GOPATH/bin/dlv debug
# Do the above dance
```

Yields:

```
(dlv) call Add(4,5)
PTRACE_GETFPREGS failed
> main.main() ./hello.go:11 (hits goroutine(1):2 total:2) (PC: 0x4bc67a)
Command failed: could not restore registers: bad address
```

I changed the error message a bit and it turns out that `err` is 0 and not `ENODEV`.

**Comment by lberki** [comment]
`regs -a` says this: https://gist.github.com/lberki/57f9c8fcc53ac66dad574f474d1fd71a

**Comment by aarzilli** [comment]
It doesn't print something like `PTRACE_SETFPREGS error`? Weird.

**Comment by aarzilli** [comment]
Can you put some printf in proc.(*nativeThread).restoreRegisters in pkg/proc/native/thread_linux_amd64.go and figure out which one of the ptrace calls makes the function return?

**Comment by lberki** [comment]
Nope. However, I added some more debugging information with this patch: https://gist.github.com/lberki/dfb3c79c04d8722ef2ee72991731cc2a

And the output is:

```
(dlv) call Add(4,5)
PTRACE_GETFPREGS failed: errno 0
PTRACE_GETFPREGS args: 1eec75 c000364b00
PTRACE_GETREGSET args: 1eec75 c0006ad4a8
PTRACE_SETREGSET error: bad address
PTRACE_SETREGSET args: 1eec75 c0006adf30
> main.main() ./hello.go:11 (hits goroutine(1):2 total:2) (PC: 0x4bc67a)
Command failed: could not restore registers: bad address
```

Is it important that the addresses for the `PTRACE_GETREGSET` and the `PTRACE_SETREGSET` calls are not the same?

**Comment by lberki** [comment]
I did, see above :)

**Comment by lberki** [comment]
I see, that's only the address of the sys.Iovec structure. I printed `iov.Base` and `iov.Len` for both the `PTRACE_GETREGSET` and `PTRACE_SETREGSET`, and those are the same.

**Comment by lberki** [comment]
FWIW, I dumped `xstateargs` right after the `PTRACE_GETREGSET` call and `sr.Fpregset.Xsave` right before the `PTRACE_SETREGSET` call and they seem to contain the exact same bytes, if that helps.

**Comment by lberki** [comment]
I found this thread: https://lkml.org/lkml/2017/6/20/876

And on a whim, I tried doubling the size of `xstateargs` in the `PTRACE_GETREGSET` call and, to my surprise, it actually worked. That call also politely set `Iovec.Len` to the minimum value it accepts, 0xa88.

```
PTRACE_GETFPREGS failed: errno 0
PTRACE_GETFPREGS args: 1f3edc c00020f600
PTRACE_GETREGSET args: 1f3edc c00033d478 c000340000 a88
PTRACE_GETREGSET err: errno 0
PTRACE_SETREGSET error: errno 0
PTRACE_SETREGSET args: 1f3edc c00033df10 c000340000 a88
> main.main() ./hello.go:11 (hits goroutine(1):2 total:2) (PC: 0x4bc67a)
Values returned:
        ~r2: 9
```

**Comment by aarzilli** [comment]
Try this. Go in pkg/proc/native/registers_linux_amd64.go and change the value of _X86_XSTATE_MAX_SIZE to 2696. If it doesn't work in pkg/proc/native/ptrace_linux_amd64.go print the value of `regset.Xsave[0:16]` in hexadecimal, right before the call to `linutil.AMD64XstateRead`.

**Comment by aarzilli** [comment]
Ah I see you already tried it. I guess your cpu is too good for us. I'm going to make a PR for this.

**Comment by lberki** [comment]
Yep. I did try to create that pull request, but `make install` said `cannot find package "github.com/derekparker/delve/cmd/dlv"` which is scary for a Developer With Very Little Brain like me (why didn't it do that on the `fix2173` branch?), so I'll leave this to you. Thanks for the help!

This is somewhat surprising because it's not actually a very new CPU (it is still a very fancy one, though)

Apparently, the Intel documentation [1] says that the CPUID instruction can tell how many bytes are needed, but I have no clue if one can call CPUID from user space, how to embed assembly into Go, whether that would work on every CPU, how what ptrace does is related to the XSAVE instruction and probably a bunch of pitfalls I can't even guess so I'll be content with stopping after digging this deep.

1: _Intel® 64 and IA-32 Architectures Developer's Manual: Vol. 1,_ Section 13.4.3: Extended Region of an XSAVE Area
