### ISSUE TITLE
how to make dlv display current instruction at each stop debuging

### ISSUE THREAD

**Issue by w0x12ef** [go-delve/delve#2221]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
2. What version of Go are you using? (`go version`)?
3. What operating system and processor architecture are you using?
4. What did you do?
5. What did you expect to see?
6. What did you see instead?

**Comment by derekparker** [comment]
Delve already does this? 

The file:line and instruction pointer address is always printed when Delve stops. If you want the actual CPU instruction you can use the disassemble command which will print a asterisk (*) next to the instruction the program is currently stopped at.
