### ISSUE TITLE
IntelliJ Idea disconnect headless process exists zombie process

### ISSUE THREAD

**Issue by LiveAlone** [go-delve/delve#2226]
1. What version of Delve are you using (`dlv version`)?
1.5.0

2. What version of Go are you using? (`go version`)?
1.13.5

3. What operating system and processor architecture are you using?
macOs 10.15.7

4. What did you do?

i run command start headless 

dlv --listen=:9999 --headless=true --api-version=2 --accept-multiclient exec ./Traxex

IntelliJ Idea start 
![image](https://user-images.githubusercontent.com/20422416/99028712-75261f00-25ab-11eb-98e3-c4d3177a4ec9.png)

when is exist listener in idea,  connect process still exists, even exist idea, multi zombie process

yaoqijun          4422   0.0  0.0        0      0   ??  Z    12:05PM   0:00.00 (Traxex)
yaoqijun          3584   0.0  0.0        0      0   ??  Z    11:51AM   0:00.00 (Traxex)
yaoqijun          2870   0.0  0.0        0      0   ??  Z    11:43AM   0:00.00 (Traxex)

ext:

dlv --listen=:9999 --headless=true --api-version=2 --accept-multiclient attach 5867 (ofcourse 5867 is ./Traxex process)

not produce  zombie process

**Comment by aarzilli** [comment]
Can you add `--log --log-output=rpc` to the command line and post the output?

**Comment by nd** [comment]
@LiveAlone we addressed it in the scope of https://youtrack.jetbrains.com/issue/GO-7353: now IDE asks whether you want to terminate the remote Delve process on detach. The fix will be available in the upcoming 2020.3 release, or you can install 2020.3 beta.

**Comment by aarzilli** [comment]
No user feedback + likely fixed in IntelliJ.
