### ISSUE TITLE
[dlv attach pid] truncated: goroutines -t

### ISSUE THREAD

**Issue by xqzhang2015** [go-delve/delve#2237]
<pre>
!44 $ dlv version
Delve Debugger
Version: 1.5.0
Build: 7555d1c06339e51a4f1e2d7a62dc9c44745e10b7
</pre>

<pre>
go version
1.15.3
</pre>

<pre>
!45 $ uname -a
Linux xxxxx 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
</pre>

There are too many goroutines in my process, which can't show in the screen.
<pre>
	(truncated)
[3096 goroutines]
</pre>

Is there a way to output the grs stack trace into file?

**Comment by aarzilli** [comment]
You could use [starlark to write a script](https://github.com/go-delve/delve/blob/master/Documentation/cli/starlark.md), there's no other way to do this at the moment.
