### ISSUE TITLE
TestStepCallPtr fails on linux/386

### ISSUE THREAD

**Issue by zhsj** [go-delve/delve#2239]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?

 `v1.5.0-62-g579b17ce`

2. What version of Go are you using? (`go version`)?

`go version go1.15.5 linux/386`

3. What operating system and processor architecture are you using?

```
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux bullseye/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

`Intel(R) Xeon(R) CPU E5-2640 v2 @ 2.00GHz`

4. What did you do?

Run the tests.

5. What did you expect to see?

Succeed.

6. What did you see instead?

```
$ go test -mod=vendor -v -run TestStepCallPtr ./pkg/proc/
=== RUN   TestStepCallPtr
    support.go:248: enabling recording for github.com/go-delve/delve/pkg/proc_test.TestStepCallPtr
    proc_test.go:517: Program did not continue to correct next location expected 9 was teststepprog.go:5 (0x809a4d0) (testcase 0)
--- FAIL: TestStepCallPtr (0.56s)
FAIL
FAIL    github.com/go-delve/delve/pkg/proc      0.574s
FAIL
```

**Comment by aarzilli** [comment]
There is a known problem with go 1.15.4 and 1.15.5 and line numbers: https://github.com/golang/go/issues/42484

**Comment by aarzilli** [comment]
If this still fails with delve 1.5.1 and go 1.15.6 please reopen.
