### ISSUE TITLE
Suggestions for release precompiled binary

### ISSUE THREAD

**Issue by sc0Vu** [go-delve/delve#2241]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
2. What version of Go are you using? (`go version`)?
3. What operating system and processor architecture are you using?
4. What did you do?
5. What did you expect to see?
6. What did you see instead?

Thanks for this great debugger, I use a lot in my golang projects. And I wonder whether it's possible to release precompiled binary? Because recently I try to debug the compiled binary in my vm that wasn't installed golang before.
And I had to install golang, then install delve.

Thanks!

**Comment by aarzilli** [comment]
I don't think this is very useful. If you have the need to debug a program you also have the ability to compile a program, the same method you used to get a compiled binary in your vm can be used to get delve on the same.

**Comment by derekparker** [comment]
This is a duplicate of https://github.com/go-delve/delve/issues/494. We had plans at one point to do something like this, but as @aarzilli mentioned it didn't seem worth the effort at the time.

**Comment by derekparker** [comment]
This issue has come up again, my response is here: https://github.com/go-delve/delve/issues/4275#issuecomment-4006024576.

I do think there is value for this, so I will reopen this issue.
