### ISSUE TITLE
Allow users to show  the arguments of current debugged like gdb `show args`

### ISSUE THREAD

**Issue by llhuii** [go-delve/delve#2242]
Now dlv has no method to show the arguments of current debugged program in the dlv interactive cmd.

Can we add a command to show current running arguments like gdb `show args`?

**Comment by aarzilli** [comment]
`p os.Args` will do this

**Comment by llhuii** [comment]
Seems `p os.Args` can't do this? ![image](https://user-images.githubusercontent.com/419660/100820450-33d9ae80-3489-11eb-8329-2bfe746af6d1.png)


> `p os.Args` will do this

**Comment by llhuii** [comment]
another problem with `p os.Args` is that the program should be running, otherwise it reports this `(dlv) p os.Args
Process 23179 has exited with status 0`

**Comment by aarzilli** [comment]
os.Args needs to be initialized by the go runtime so it won't be available immediately after starting a program. Also, as you note, you can't read it after the program has quit. But features have a complexity cost and I don't think it's worth paying it to cover this edge cases.

**Comment by hitzhangjie** [comment]
To o run 'p os.Args' at breakpoint 'main.main' may meet your needs. @llhuii
