### ISSUE TITLE
How to exec binary with arguments

### ISSUE THREAD

**Issue by tintinlam007** [go-delve/delve#2243]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

What version of Delve are you using (dlv version)?
Delve Version: V1.3.2

What version of Go are you using? (go version)?
Go Version: 1.13.4 linux/amd64

What operating system and processor architecture are you using?
Operating System: Alpine Linux v3.10.3. Processor Architecture: Run In Docker

What did you do?
dlv --listen=:2345 --headless=true --api-version=2 exec bin/agent "1"
bin/agent is the binary and it has arguments, how can I pass the arguments to the binary?

What did you expect to see?
How to exec binary with arguments

What did you see instead?
nothing

Thank you!

**Comment by aarzilli** [comment]
Pass arguments you want passed to the target program after `--`: `dlv --listen=:2345 --headless=true --api-version=2 exec bin/agent -- arguments for bin/agent here`
