### ISSUE TITLE
How to debug through delve like java's "suspend=n"

### ISSUE THREAD

**Issue by tintinlam007** [go-delve/delve#2247]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

What version of Delve are you using (dlv version)?
Delve Version: V1.3.2

What version of Go are you using? (go version)?
Go Version: 1.13.4 linux/amd64

What operating system and processor architecture are you using?
Operating System: Alpine Linux v3.10.3. Processor Architecture: Run In Docker

What did you do?
Delve will suspend the program until the debug client connected, just like java's "suspend=y". 
How to debug through delve like java's "suspend=n"?

What did you expect to see?
How to debug through delve like java's "suspend=n"?

What did you see instead?
nothing

Thank you!

**Comment by aarzilli** [comment]
Are you looking for the `--continue` option?

**Comment by tintinlam007** [comment]
Yes it is! Thank you!

**Comment by tintinlam007** [comment]
> Are you looking for the `--continue` option?
