### ISSUE TITLE
Error protocol wrong type for socket when using delve connect

### ISSUE THREAD

**Issue by renaissains** [go-delve/delve#2272]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
1.5.1

2. What version of Go are you using? (`go version`)?
go1.15.5 darwin/amd64

3. What operating system and processor architecture are you using?
BigSur 11.1
2,6 GHz 6-Core Intel Core i7

4. What did you do?
Run `dlv --continue --headless --listen=:2345 --accept-multiclient --log --api-version=2 debug main.go`
Then connect via vim-delve `:DlvConnect :2345`

5. What did you expect to see?
Debugger running and will stop at breakpoint

6. What did you see instead?
Program does not stop at breakpoint
```
/nvim/vim-delve/57443.1608198142:1: write tcp 127.0.0.1:49241->127.0.0.1:2345: write: protocol wrong type for socket
```

I updated the OS just before encountering this problem, though I'm not really sure whether it's connected or not. 
Would really appreciate it if you could point out where the problem is. Thanks!

**Comment by aarzilli** [comment]
Go 1.15 doesn't support BigSur, you need 1.16. Delve does not support darwin/arm64, see #2246.
