### ISSUE TITLE
Is it reasonable to enable compiler-optimization to allow debugging huge packages?

### ISSUE THREAD

**Issue by krobelus** [go-delve/delve#2295]
We have a huge package of circa 500k lines of generated Go code.
(I didn't try splitting this package, maybe that would help alleviate the problem).

Running `dlv test some_package_that_depends_on_huge_package` will spawn this compilation process

```sh
$ go test -c some_package_that_depends_on_huge_package -x -gcflags "all=-N -l" 
```

which uses >10GB of memory - too much for my setup.
After changing the gcflags from `all=-N` to `-N`, 1-2GB of memory are enough, and the debugger works as expected.
The `-N` flag disables optimizations, see `go tool compile help`. The `all=` prefix means that the flag applies to all dependencies, not just the current package. This is described [here](https://golang.org/cmd/go/) (search for `all=`).

Hence enabling optimizations actually makes the compiler use less memory! As far as I can tell our workaround did not affect debug information - I am still able to set breakpoints in dependent packages, step around, print variables, etc.

The gcflags are hardcoded in delve. Would it be reasonable to be able to pass custom gcflags? We're currently using the patch below. Is it crazy to use such huge packages? It works fairly okay otherwise.
Thanks

```diff
diff --git a/pkg/gobuild/gobuild.go b/pkg/gobuild/gobuild.go
index fde64f80..052cb167 100644
--- a/pkg/gobuild/gobuild.go
+++ b/pkg/gobuild/gobuild.go
@@ -31,5 +31,5 @@ func optflags(args []string) []string {
 	switch {
 	case ver.Major < 0 || ver.AfterOrEqual(goversion.GoVersion{Major: 1, Minor: 10, Rev: -1}):
-		args = append(args, "-gcflags", "all=-N -l")
+		args = append(args, "-gcflags", "-N -l")
 	case ver.AfterOrEqual(goversion.GoVersion{Major: 1, Minor: 9, Rev: -1}):
 		args = append(args, "-gcflags", "-N -l", "-a")
```

Delve version 1.5.1
Go version 1.15.6
linux/amd64

**Comment by aarzilli** [comment]
There's an `exec` command, you can compile your program independently and then run dlv on the executable, that's why the flags are hardcoded. It doesn't make sense to replicate the command line of cmd/go inside delve, you can achieve the same with simple shell scripts.

Things should generally work on optimized code, except that:

* the execution order of instructions could be surprising
* some variables might disappear
* the `set` command might not work
* the `call` command might not work

> Is it crazy to use such huge packages?

I wouldn't know.

**Comment by aarzilli** [comment]
PS. Delve itself is over 100k lines of code if we count vendored dependencies, and it doesn't use much memory to compile, it's possible that you have encountered an edge case that the compiler people might be interested in knowing about.

**Comment by krobelus** [comment]
Thanks for the explanation, that makes a ton of sense.

I suspect that the performance problem is mostly because everything is in one Go package.
 AFAIK those are the compilation units, so the compiler might choke on a large one.

There are some similar issues in the go compiler, for example one about a failure to compile large maps literals. Most of these should be fixed by now, I'll check if mine is interesting.
