### ISSUE TITLE
Failed to install on Macos Arm64

### ISSUE THREAD

**Issue by nightofmind** [go-delve/delve#2302]
Go version: `go version go1.16beta1 darwin/arm64`

Macos 11.1, Apple Silicon chip, arm64 architecture

I want to install delve using `go get github.com/go-delve/delve/cmd/dl`, but it reports:
```
../../go/pkg/mod/github.com/go-delve/delve@v1.5.1/service/debugger/debugger.go:26:2: found packages native (nonative_darwin.go) and your_operating_system_and_architecture_combination_is_not_supported_by_delve (support_sentinel.go) in /Users/harden/go/pkg/mod/github.com/go-delve/delve@v1.5.1/pkg/proc/native
```

**Comment by derekparker** [comment]
This is fixed via https://github.com/go-delve/delve/pull/2285. Your `go get` is pulling the latest tagged release (`v1.5.1`) and we haven't issued a release with M1 support yet (it's only in the main branch).

Try building from `main` and you should be good to go.
