### ISSUE TITLE
How to specify C header file paths when using dlv debug?

### ISSUE THREAD

**Issue by vshashi01** [go-delve/delve#2308]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)? 
  1.5.1
2. What version of Go are you using? (`go version`)? 
  1.15.6
![image](https://user-images.githubusercontent.com/28664567/104981115-f9c96980-5a42-11eb-8a6e-7c163a3ff90a.png)

3. What operating system and processor architecture are you using? 
   Windows/AMD64
4. What did you do? 
   Trying to compile a program with a dependency package that uses CGO.
5. What did you expect to see? 
   dlv debug to be able to compile the project and launch the debugger.
6. What did you see instead? 
   Linker errors with my MinGW compiler related to undefined reference to the functions defined in the C header file. Using go 
   build works fine in compiling the program into an executable. Running go exec on the generate executable also works. So how 
   do ensure the dlv debug call is able to build as does go build? 

![image](https://user-images.githubusercontent.com/28664567/104981045-d7375080-5a42-11eb-9df7-af5682ca1edc.png)

I looked at the docs, its currently unclear to me if all the settings of the go environment are also adopted by the delve debug command or if I have to pass extra flags to it.

**Comment by aarzilli** [comment]
You can pass extra flags to `go build` with `--build-flags`. There's also some cases when disabling optimizations will lead to compilation errors: https://github.com/go-delve/delve/issues/2187. You can work around those problems by explicitly setting CGO_CFLAGS.

**Comment by vshashi01** [comment]
I am sorry I am not sure if I follow. My problem is that I am able to build my project with `go build` without any flags. However `dlv debug` doesn't. So I am just wondering if I need to pass some extra flag for delve as well in this case.

**Comment by aarzilli** [comment]
Try this: 
* set the environment variable`CGO_CFLAGS` to `-O0 -g`
* run `go build -gcflags='all=-N -l'`. 

This is what delve does, nothing else. Given that you are not passing anything to `go build` you don't need to pass anything to `dlv` either. 
The problem is likely with the value of CGO_CFLAGS, see https://github.com/go-delve/delve/issues/2187, which you can work around by manually setting CGO_CFLAGS to something else, for example `-O2 -g`.

**Comment by vshashi01** [comment]
So setting my CGO__CFLAGS to `-O1 - g` allowed `go build -gcflags='all=-N -l'` to work. However calling `dlv debug` still doesnt work. Any idea how I can ensure the VSCode debugger to change these flags on debug?
