### ISSUE TITLE
pkg/terminal: add option to disable auto-continue during next/step/stepout

### ISSUE THREAD

**Issue by hzzb** [go-delve/delve#2317]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
```
localhost:~ xxx$ dlv version
Delve Debugger
Version: 1.2.0
Build: 86d4b0b9915d55833a99bfb4c8b3a138f03ab802
localhost:~ xxx$ 
```

2. What version of Go are you using? (`go version`)?
```
localhost:~ xxx$ go version
go version go1.12.8 darwin/amd64
localhost:~ xxx$ 
```

3. What operating system and processor architecture are you using?
```
localhost:~ xxx$ uname -a
Darwin Hanss-MacBook-Pro.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64
localhost:~ xxx$ sysctl -a | grep machdep.cpu 
machdep.cpu.max_basic: 20
machdep.cpu.max_ext: 2147483656
machdep.cpu.vendor: GenuineIntel
machdep.cpu.brand_string: Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
machdep.cpu.family: 6
machdep.cpu.model: 61
localhost:~ xxx$ 
```

4. What did you do?
```Golang
// file main.go
package main

import (
	"time"
)

func main() {
	go b()
	time.Sleep(time.Second)
	time.Sleep(time.Second)
}

func b() {
	time.Sleep(time.Second)    // breakpoint  2
}
```

```
localhost:~ xxx$ dlv debug main.go
Type 'help' for list of commands.
(dlv) b main.main
Breakpoint 1 set at 0x105882f for main.main() ./main.go:7
(dlv) b main.b
Breakpoint 2 set at 0x105888f for main.b() ./main.go:13
(dlv) c
(dlv) n
```
In main func, repeat `n` command.

5. What did you expect to see?
After some one particular `n` command, dlv stops at breakpoint 2.

6. What did you see instead?

The dlv debugger didn't catch breakpoint 2.

Will dlv switch goroutine automatically to catch breakpoints on different goroutines?   I found gdb works as expected.

**Comment by aarzilli** [comment]
Can I see a full transcript of a failing session, including the full output of delve? It should stop at the second breakpoint after the first continue not after any next command.

**Comment by hzzb** [comment]
> Can I see a full transcript of a failing session, including the full output of delve? It should stop at the second breakpoint after the first continue not after any next command.

```
localhost:~ xxx$ dlv debug main.go
Type 'help' for list of commands.
(dlv) b main.main
Breakpoint 1 set at 0x106e92f for main.main() ./main.go:8
(dlv) b main.b
Breakpoint 2 set at 0x106e9af for main.b() ./main.go:14
(dlv) c
> main.main() ./main.go:8 (hits goroutine(1):1 total:1) (PC: 0x106e92f)
     3:	
     4:	import (
     5:		"time"
     6:	)
     7:	
=>   8:	func main() {
     9:		go b()
    10:		time.Sleep(time.Second)
    11:		time.Sleep(time.Second)
    12:	}
    13:	
(dlv) n
> main.main() ./main.go:9 (PC: 0x106e93d)
     4:	import (
     5:		"time"
     6:	)
     7:	
     8:	func main() {
=>   9:		go b()
    10:		time.Sleep(time.Second)
    11:		time.Sleep(time.Second)
    12:	}
    13:	
    14:	func b() {
(dlv) n
> main.b() ./main.go:14 (hits goroutine(17):1 total:1) (PC: 0x106e9af)
> main.main() ./main.go:10 (PC: 0x106e955)
     5:		"time"
     6:	)
     7:	
     8:	func main() {
     9:		go b()
=>  10:		time.Sleep(time.Second)
    11:		time.Sleep(time.Second)
    12:	}
    13:	
    14:	func b() {
    15:		time.Sleep(time.Second) // breakpoint  2
(dlv) n
> main.main() ./main.go:11 (PC: 0x106e965)
     6:	)
     7:	
     8:	func main() {
     9:		go b()
    10:		time.Sleep(time.Second)
=>  11:		time.Sleep(time.Second)
    12:	}
    13:	
    14:	func b() {
    15:		time.Sleep(time.Second) // breakpoint  2
    16:	}
(dlv) n
> main.main() ./main.go:12 (PC: 0x106e972)
     7:	
     8:	func main() {
     9:		go b()
    10:		time.Sleep(time.Second)
    11:		time.Sleep(time.Second)
=>  12:	}
    13:	
    14:	func b() {
    15:		time.Sleep(time.Second) // breakpoint  2
    16:	}
(dlv) n
> runtime.main() ./github.com/hzzb/go/src/runtime/proc.go:234 (PC: 0x10367a3)
Warning: debugging optimized function
Values returned:

   229:	
   230:		// Make racy client program work: if panicking on
   231:		// another goroutine at the same time as main returns,
   232:		// let the other goroutine finish printing the panic trace.
   233:		// Once it does, it will exit. See issues 3934 and 20018.
=> 234:		if atomic.Load(&runningPanicDefers) != 0 {
   235:			// Running deferred functions should not take long.
   236:			for c := 0; c < 1000; c++ {
   237:				if atomic.Load(&runningPanicDefers) == 0 {
   238:					break
   239:				}
(dlv) bp
Breakpoint unrecovered-panic at 0x1034100 for runtime.fatalpanic() ./github.com/hzzb/go/src/runtime/panic.go:1185 (0)
	print runtime.curg._panic.arg
Breakpoint 1 at 0x106e92f for main.main() ./main.go:8 (1)
Breakpoint 2 at 0x106e9af for main.b() ./main.go:14 (1)
(dlv)
```

Stopping at `main.main` is expected after first `c`.  Should the second `n` catch breakpoint 2?  Thanks!

**Comment by aarzilli** [comment]
You are right about the the first `c`, of course. But the second next does catch the breakpoint:

```
(dlv) n
> main.b() ./main.go:14 (hits goroutine(17):1 total:1) (PC: 0x106e9af)
> main.main() ./main.go:10 (PC: 0x106e955)
     5:		"time"
     6:	)
     7:	
     8:	func main() {
     9:		go b()
=>  10:		time.Sleep(time.Second)
    11:		time.Sleep(time.Second)
    12:	}
    13:	
    14:	func b() {
    15:		time.Sleep(time.Second) // breakpoint  2
```

See the first line? That's the breakpoint hit, it just happens simultaneously with finishing `next`

**Comment by hzzb** [comment]
Yep, the first line logs out breakpoint hitting. It seems that breakpoint hit during `next` command continued automatically on other goroutines?  I feel it is somewhat misleading that  function `main.b` didn't run. Is there one way out to disable the auto-continue? Thanks!

**Comment by aarzilli** [comment]
There is no auto-continue here, the two breakpoint just happen close enough to appear simultaneous to the debugger.

**Comment by hzzb** [comment]
Identity the goroutine that running func `main.b` as `gb`.  Would debugger stop  `gb` when the breakpoint 2 hit?  

I would rather to see `gb` paused so I can switch to it and `bt` the call trace after `n` finished.  The `gb` ran normally without pausing in my situation.

**Comment by aarzilli** [comment]
> Identity the goroutine that running func main.b as gb. Would debugger stop gb when the breakpoint 2 hit?

In this case *it did*. In general it wouldn't it would say `breakpoint hit during next, continuing...` and auto-continue.

> I would rather to see gb paused so I can switch to it and bt the call trace after n finished. The gb ran normally without pausing in my situation.

In this particular case, you can. You can switch to gb and it will be stopped at your breakpoint. In general we believe that wanting to see the `next` command to completion is the more common use case and a text UI has a limited interface to work with.

**Comment by hzzb** [comment]
In general case, could the auto-continue mechanism be switched off?  Debugger pauses at any breakpoint hit during `next` like during `continue`. Thanks!

**Comment by aarzilli** [comment]
Yes, that's something that could be added.

**Comment by polinasok** [comment]
@hzzb 
> In general case, could the auto-continue mechanism be switched off? Debugger pauses at any breakpoint hit during next like during continue.
Let's say we do stop at breakpoints explicitly. What would you expect the behavior of next or continue operation to be after that?

**Comment by aarzilli** [comment]
Given that this is a terminal interface the way to do this would be to prompt the user to either (1) stop and cancel next, (2) continue once, (3) continue as much as needed for next to finish.

**Comment by hzzb** [comment]
@polinasok  
> Let's say we do stop at breakpoints explicitly. What would you expect the behavior of next or continue operation to be after that?

Sorry for the late reply.  I agree with aarzilli and vote (1) in my situation.






> Given that this is a terminal interface the way to do this would be to prompt the user to either (1) stop and cancel next, (2) continue once, (3) continue as much as needed for next to finish.
