### ISSUE TITLE
crash in loadDebugInfoMapsInlinedCalls for DWARF 5 compilation unit

### ISSUE THREAD

**Issue by thanm** [go-delve/delve#2319]
Please answer the following before submitting your issue:

1. What version of Delve are you using (`dlv version`)? tip/master

I am using a freshly built Delve at main branch:

```
$ dlv version
Delve Debugger
Version: 1.5.1
Build: $Id: bca418ea7ae2a4dcda985e623625da727d4525b5 $
```

2. What version of Go are you using? (`go version`)?

Tip of golang main branch:
$ go version
go version devel +9abbe27710 Mon Dec 21 04:23:39 2020 +0000 linux/amd64

3. What operating system and processor architecture are you using?

linux/amd64
Debian or equivalent

4. What did you do?

$ dlv exec ./dlvdw5

for an application with a mix of Go and C++. Original program was a large google-internal application; I have whittled it down to a much smaller reproducer (tar file attached).

5. What did you expect to see?

Successful startup

6. What did you see instead?

panic: runtime error: index out of range [-1]

```
goroutine 51 [running]:
github.com/go-delve/delve/pkg/proc.(*BinaryInfo).loadDebugInfoMapsInlinedCalls(0xc0002423c0, 0xc000038020, 0xc00005e4b0, 0xc000163480)
	/w/go1/src/github.com/go-delve/delve/pkg/proc/bininfo.go:1940 +0xa9a
github.com/go-delve/delve/pkg/proc.(*BinaryInfo).addConcreteSubprogram(0xc0002423c0, 0xc0001a6570, 0xc000038020, 0xc00005e4b0, 0xc000163480)
	/w/go1/src/github.com/go-delve/delve/pkg/proc/bininfo.go:1865 +0x1ee
github.com/go-delve/delve/pkg/proc.(*BinaryInfo).loadDebugInfoMapsCompileUnit(0xc0002423c0, 0xc000038020, 0xc00024a9c0, 0xc00005e4b0, 0xc000163480)
	/w/go1/src/github.com/go-delve/delve/pkg/proc/bininfo.go:1748 +0xe25
github.com/go-delve/delve/pkg/proc.(*BinaryInfo).loadDebugInfoMaps(0xc0002423c0, 0xc00024a9c0, 0xc0004a0000, 0x4e802, 0x4e802, 0xc0004f0000, 0x20a6e, 0x20a6e, 0xc000214ae0, 0x0)
	/w/go1/src/github.com/go-delve/delve/pkg/proc/bininfo.go:1628 +0x731
created by github.com/go-delve/delve/pkg/proc.loadBinaryInfoElf
	/w/go1/src/github.com/go-delve/delve/pkg/proc/bininfo.go:1178 +0x5d2
```

In this application, there are a mix of compilation units, some C++ and some Go. The C++ units are built using a recent version of clang, with "-gdwarf-5" or equivalent. The problem above is happening when dlv is examining one of the C++ compilation units. 

From section 6.2.4 of the DWARF 5 standard, describing the line table "file table" section in the header:

Prior to DWARF Version 5, the current compilation file name was not represented in the file_names field. In DWARF Version 5, the current compilation file name is explicitly present and has index 0. This is needed to support the common practice of stripping all but the line number sections (.debug_line and .debug_line_str) from an executable.

I don't think Delve is taking this into account when making file table references -- it always subtracts 1, which doesn't seem right. Source code above that is crashing:

```
			if int(callfileidx-1) >= len(cu.lineInfo.FileNames) {
				bi.logger.Warnf("reading debug_info: CallFile (%d) of inlined call does not exist in compile unit file table at %#x", callfileidx, entry.Offset)
				reader.SkipChildren()
				continue
			}
			callfile := cu.lineInfo.FileNames[callfileidx-1].Path

			fn.InlinedCalls = append(fn.InlinedCalls, InlinedCall{
				cu:     cu,
				LowPC:  lowpc,
				HighPC: highpc,
			})
```

Note the "callfileidx-1" -- this is the problem.  

In the DWARF line table dump for the C compilation unit (in the attached testcase), here's the dump:

```
debug_line[0x000209be]
Line table prologue:
    total_length: 0x000000ac
         version: 5
    address_size: 8
 seg_select_size: 0
 prologue_length: 0x00000037
 min_inst_length: 1
max_ops_per_inst: 1
 default_is_stmt: 1
       line_base: -5
      line_range: 14
     opcode_base: 13
standard_opcode_lengths[DW_LNS_copy] = 0
standard_opcode_lengths[DW_LNS_advance_pc] = 1
standard_opcode_lengths[DW_LNS_advance_line] = 1
standard_opcode_lengths[DW_LNS_set_file] = 1
standard_opcode_lengths[DW_LNS_set_column] = 1
standard_opcode_lengths[DW_LNS_negate_stmt] = 0
standard_opcode_lengths[DW_LNS_set_basic_block] = 0
standard_opcode_lengths[DW_LNS_const_add_pc] = 0
standard_opcode_lengths[DW_LNS_fixed_advance_pc] = 1
standard_opcode_lengths[DW_LNS_set_prologue_end] = 0
standard_opcode_lengths[DW_LNS_set_epilogue_begin] = 0
standard_opcode_lengths[DW_LNS_set_isa] = 1
include_directories[  0] = "/w/go1/src/dlvdw5-clean"
file_names[  0]:
           name: "csrc/cfile.c"
      dir_index: 0
   md5_checksum: f5c6404098de627ae086f64a18e234c0
```

Note the file_names above -- just a single entry. 

To reproduce the problem, unpack the attached tar file and run the script "doit.sh", which will perform the compile and run "dlv exec". 

Warning: it took me a long time to cook the test case correctly to reproduce this-- it is very sensitive to code shape. One thing that kind of got in the way is that Delve seems to have an implicit requirement if you have an abstract/concrete function pair, the abstract function seems to have to come first (and sometimes the C compiler decides not to do this).

[dlvrepro.zip](https://github.com/go-delve/delve/files/5858693/dlvrepro.zip)

Let me know if you have any questions.

**Comment by thanm** [comment]
I have a prototype fix at https://github.com/thanm/delve/tree/issue_2319 -- I would welcome advice on how to write a test for this, however. I dredged around looking for something similar but didn't have much luck.  Any suggestions appreciated.

**Comment by aarzilli** [comment]
@thanm I don't think we have any test that is similar. Requiring a specific C compiler to reproduce complicates things.
The easiest way would probably be to drop the precompiled binary in `_fixtures` and then in pkg/proc/proc_test.go do something like this:

```
bi := proc.NewBinaryInfo("linux", "amd64")
assertNoError(bi.LoadBinaryInfo(filepath.Join(protest.FindFixturesDir(), "executable.elf"), 0, nil), t, "LoadBinaryInfo")
```

**Comment by thanm** [comment]
Thanks that is helpful. I'll work up something along those lines.
