### ISSUE TITLE
Goland debug go program failed to run

### ISSUE THREAD

**Issue by xichengliudui** [go-delve/delve#2330]
Please answer the following before submitting your issue:

1. What version of Delve are you using (`dlv version`)?
2. What version of Go are you using? (`go version`)?
```
go version go1.16beta1 darwin/arm64
```
3. What operating system and processor architecture are you using?
```
MacBook Pro (13-inch, M1, 2020)
Apple M1
arm
```
4. What did you do?
```
debug with goland
i print out some numbers and debug them
goland version: goland-2020.3.1-aarch64
```
5. What did you expect to see?
```
good running
```
6. What did you see instead?
```
API server listening at: [::]:57824
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1200.0.44
 for x86_64.
error: failed to launch process /Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver: (os/kern) invalid argument
Exiting.
could not launch process: stub exited while waiting for connection: exit status 0
```

**Comment by dlsniper** [comment]
We are going to release GoLand 2020.3.2 today, which includes an update for Delve to support Apple M1 debugging.
If you encounter any issues, please report them on our tracker: https://youtrack.jetbrains.com/issues/Go

This is not related to Delve, for now, and can be closed.

**Comment by xichengliudui** [comment]
good job
/close

**Comment by cajias1** [comment]
Just got the same issue on:

### Goland version
> GoLand 2021.1
> Build #GO-211.6693.119, built on April 7, 2021
> Licensed to XXXX
> Subscription is active until March 31, 2022.
> Runtime version: 11.0.10+9-b1341.35 x86_64
> VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
> macOS 11.2.3
> GC: G1 Young Generation, G1 Old Generation
> Memory: 750M
> Cores: 8
> Registry: ide.completion.variant.limit=500, suggest.all.run.configurations.from.context=true

### Go Version

>go version go1.16.3 darwin/arm64

**Comment by dlsniper** [comment]
@cajias1 Please ensure that you [downloaded GoLand for ARM M1](https://www.jetbrains.com/go/download/download-thanks.html?platform=macM1).
If the problem still persists, please report this to our tracker, https://youtrack.jetbrains.com/issues/Go, where my colleagues will help you sort this out.
Thanks.

**Comment by GeekRicardo** [comment]
1. 强制刷新开发者权限
即使已执行过授权命令，SSH会话可能需要显式激活：

bash
# 启用开发者模式
sudo devtoolssecurity -enable

# 将当前用户加入开发者组（确保生效）
sudo dscl . append /Groups/_developer GroupMembership $(whoami)

# 重启相关服务（关键步骤）
sudo killall taskgated
2. 检查被调试程序的签名状态
macOS要求被调试程序必须携带调试权限标识。对于Go程序，需确认编译时关闭优化并启用调试：

bash
# 强制编译时保留调试符号（必须参数）
go build -gcflags="all=-N -l" -o myapp

# 确认文件包含调试权限
codesign -d --entitlements - myapp 2>&1 | grep get-task-allow
如果输出中无com.apple.security.get-task-allow，需手动签名：

3. 临时签名调试程序
为Go编译后的二进制文件添加调试权限：

bash
# 创建临时签名证书（仅需一次）
security find-identity -p codesigning  # 确认有可用的证书
codesign -s - --entitlements <(echo '<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict><key>com.apple.security.get-task-allow</key><true/></dict></plist>') -f myapp
4. 以非root用户运行调试器
在SSH会话中避免使用sudo，直接以普通用户启动：

bash
# 确保进程未被其他权限限制
ps aux | grep myapp  # 确认进程属于当前用户
dlv attach <PID>     # 直接附加进程
5. 直接调试而非附加进程
通过dlv exec启动程序而非附加到已有进程：

bash
dlv exec ./myapp --headless --listen=:2345 --api-version=2
6. 更新系统组件
确保所有调试组件为最新：

bash
# 更新Xcode命令行工具
softwareupdate --all --install --force

# 重新安装LLDB和debugserver
sudo rm -rf /Library/Developer/CommandLineTools
xcode-select --install
7. 检查系统完整性保护 (SIP)
如果问题持续，临时禁用SIP测试：

bash
# 重启进入Recovery模式，执行：
csrutil disable
注意：调试完成后务必重新启用SIP（csrutil enable）。

关键原因：
macOS的TCC（Transparency, Consent, and Control）机制在SSH会话中无法弹出权限请求窗口，导致调试权限未实际授予。通过强制签名程序 + 重启权限服务可绕过交互式授权。

执行上述步骤后，远程调试应成功附加进程。如仍失败，请提供以下信息：

bash
# 执行并反馈结果
codesign -dv --entitlements :- $(which debugserver)
devtoolssecurity -status
本回答由 AI 生成，内容仅供参考，请仔细甄别。
