### ISSUE TITLE
could not launch process on m1

### ISSUE THREAD

**Issue by eaglemoor** [go-delve/delve#2332]
could not launch process on m1

1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.6.0
Build: 75485427957fba167a6eaca76b1ee9549d62916f
2. What version of Go are you using? (`go version`)?
go version go1.16beta1 darwin/arm64
3. What operating system and processor architecture are you using?
MacBook Air (M1, 2020) Big Sur 11.1
4. What did you do?
Try to run go application
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "showLog": true,
            "name": "app",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": "${workspaceFolder}",
            "cwd": "${workspaceFolder}/bin",
            "envFile": "${workspaceFolder}/.env",
        }
    ]
}
```
5. What did you expect to see?
```
API server listening at: 127.0.0.1:20210
could not launch process: stub exited while waiting for connection: exit status 0
2021-01-29T14:50:43+03:00 info layer=debugger launching process with args: [.../__debug_bin]

```

But, if I run 
```
CGO_ENABLED=0 arch -arch arm64 dlv debug --log --headless .
```

all fine. How I can launch dlv with arm64 mod by default ?

**Comment by aarzilli** [comment]
1. Find the debugserver executable at `$(xcode-select --print-path)/../SharedFrameworks/LLDB.framework/Versions/A/Resources/debugserver`
2. Run it manually `path-to-debugserver -D -F -R 127.0.0.1:30000 path-to-executable-to-debug`

What happens?

**Comment by eaglemoor** [comment]
```
CGO_ENABLED=0 dlv debug --log --headless .
API server listening at: 127.0.0.1:62497
2021-01-29T17:28:11+03:00 info layer=debugger launching process with args: [.../__debug_bin]
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1200.0.44
 for x86_64.
error: failed to launch process /Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver: (os/kern) invalid argument
Exiting.
could not launch process: stub exited while waiting for connection: exit status 0
```

**Comment by eaglemoor** [comment]
```/Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver -D -F -R 127.0.0.1:30000 .
Password:
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1200.0.44
 for x86_64.
error: failed to launch process /Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver: Permission denied
Exiting.```

**Comment by aarzilli** [comment]
It seems that you have a version of debugserver installed for 86x64 instead of arm64.

**Comment by eaglemoor** [comment]
I only find this https://developer.apple.com/forums/thread/662738 
But I can't find, how I can run dlv with prefix `arch -arch arm64` in VSCode

**Comment by aarzilli** [comment]
cc @polinasok

**Comment by hyangah** [comment]
The easiest way I can think of is to write a wrapper script and `"go.alternateTools": {"dlv": "path_to_your_wrapper_script"}`. 

I hope once the vscode releases the native arm64 support (1.53), it becomes more usable. ([background story](https://github.com/golang/vscode-go/issues/1087)).

**Comment by eaglemoor** [comment]
https://github.com/golang/vscode-go/blob/master/docs/settings.md#goalternatetools we don't have dlv in alternateTools

**Comment by hyangah** [comment]
Don't worry - it will work. There were so many tools the extension used so at some point people forgot to update the list. Here is the list of [recognized tool names](https://github.com/golang/vscode-go/blob/master/src/goTools.ts#L188)

**Comment by eaglemoor** [comment]
```
go version
go version go1.16rc1 darwin/arm64

go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/eaglemoor/Library/Caches/go-build"
GOENV="/Users/eaglemoor/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/eaglemoor/go/pkg/mod"
GONOPROXY="go.avito.ru"
GONOSUMDB="go.avito.ru"
GOOS="darwin"
GOPATH="/Users/eaglemoor/go"
GOPRIVATE="go.avito.ru"
GOPROXY="proxy.golang.org,direct"
GOROOT="/Users/eaglemoor/sdk/go1.16rc1"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/eaglemoor/sdk/go1.16rc1/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.16rc1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/eaglemoor/go/src/gitlab.com/teso.world/avalonbot/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/rx/_25pz67j5vb77f75svj9_nj40000gn/T/go-build3995285346=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

```
{
    "explorer.confirmDelete": false,
    "go.useLanguageServer": true,
    "explorer.confirmDragAndDrop": false,
    "workbench.colorTheme": "Visual Studio Dark",
    "go.toolsEnvVars": {
        "GOARCH": "arm64",
        "CGO_ENABLED":1,
        "GO111MODULE":"on",
    },
    "go.delveConfig": {
        "dlvLoadConfig": {
            "followPointers": true,
            "maxVariableRecurse": 1,
            "maxStringLen": 64,
            "maxArrayValues": 64,
            "maxStructFields": -1
        },
        "apiVersion": 2,
        "showGlobalVariables": false
    },
    "go.alternateTools": {
        "dlv": "/usr/bin/arch -arch arm64 /Users/eaglemoor/go/bin/dlv"
    }
}
```

```
API server listening at: 127.0.0.1:2826
2021-01-29T20:38:56+03:00 info layer=debugger launching process with args: [/Users/eaglemoor/go/src/gitlab.com/teso.world/avalonbot/__debug_bin]
could not launch process: stub exited while waiting for connection: exit status 0
```

**Comment by eaglemoor** [comment]
```
"go.alternateTools": {
    "dlv": "/usr/bin/arch -arch arm64 /Users/eaglemoor/go/bin/dlv"
 }
```
Maybe it not wrapper script, but error of dlv or dlv not installed I don't see

**Comment by polinasok** [comment]
"API server listening at: 127.0.0.1:2826" - means dlv was found the launched.
"could not launch process" - means dlv was not able to launch the process.

**Comment by eaglemoor** [comment]
Yes, used default dlv

**Comment by hyangah** [comment]
@eaglemoor It should be a wrapper script (which should be executable) and you are supposed to pass the path to the script. Otherwise, the extension falls back to `dlv` found in your path.

**Comment by eaglemoor** [comment]
```
#!/bin/sh
exec /usr/bin/arch -arch arm64 /Users/eaglemoor/go/bin/dlv "$@"
```

@hyangah Thanks a lot !!!

**Comment by Jerry-yz** [comment]
> ```
> #!/bin/sh
> exec /usr/bin/arch -arch arm64 /Users/eaglemoor/go/bin/dlv "$@"
> ```
> 
> @hyangah Thanks a lot !!!

how to add this file

**Comment by hyangah** [comment]
@Jerry-yz You can use `go.alternateTools` setting. But now both Go and VS Code officially support M1, so you will not need this hack any further if you install the correct VS Code and the correct Go tool chain.

VS Code: https://code.visualstudio.com/download --> select "Universal" or "Apple Silicon" installer

Go: darwin-arm64 installer at https://golang.org/dl/go1.16.7.darwin-arm64.pkg

**Comment by Jerry-yz** [comment]
i install correct vscode and go, but i cannot be used normally debug

**Comment by sagardeore7** [comment]
After removing all GO Packages, remove folder :Users/{name}/**go**

Then Install arm64 version go build. This worked for me

**Comment by pwmcintyre** [comment]
my problem was that i installed `amd` and not `arm` (URLs so similar!)
```
https://go.dev/dl/go1.17.5.darwin-amd64.pkg
https://go.dev/dl/go1.17.5.darwin-arm64.pkg
```

### FIX:
i had to sudo remove my go dir (the installer didn't do this properly):

1. remove old
    ```shell
    sudo rm -rf ~/go
    ```
2. install ARM go
3. reload VS Code; and reinstall go tools
4. success ✅

**Comment by pstudiodev1** [comment]
Hi pwmcintyre

you are save my life. your step is good
- sudo rm -rf /usr/local/go
- sudo rm -rf /User/[xxxx]/go
- then install go arm64
- then install vscode arm64
- setup terminal start with arm64 not using rosetta

Thanks

**Comment by JoeFerrucci** [comment]
### ✅  SOLUTION ✅ 

I provided a solution over on another issue thread: https://github.com/go-delve/delve/issues/2604#issuecomment-1468766540
