### ISSUE TITLE
The program enters a dead cycle，proc_linux.go .wait 467  wpid, err := sys.Wait4(pid, &s, sys.WNOHANG|sys.WALL|options, nil) 

### ISSUE THREAD

**Issue by fanhai** [go-delve/delve#2339]
dlv debug
dlv debug main.go --log
debugger.New 138:&{WorkingDir:. AttachPid:0 CoreFile: Backend:default Foreground:false DebugInfoDirectories:[/usr/lib/debug/.build-id] CheckGoVersion:true TTY: Packages:[main.go] BuildFlags: ExecuteKind:1 Redirects:[  ] DisableASLR:false}
debugger.New 176
2021-02-12T22:59:34+08:00 info layer=debugger launching process with args: [/home/hai/projects/go/helloworld/__debug_bin]
debugger.Launch:[/home/hai/projects/go/helloworld/__debug_bin],.
debugger.Launch 291
proc_linux.Launch 56
proc_linux.Launch 74
proc_linux.Launch 76
proc_linux.Launch 116
proc_linux.Launch 118
proc_linux.Launch 124:&{Pid:14373 handle:0 isdone:0 sigMu:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:0 readerWait:0}}
proc_linux.wait 467:0proc_linux.wait 469
proc_linux.wait 467:0proc_linux.wait 469
proc_linux.wait 467:0proc_linux.wait 469
proc_linux.wait 467:0proc_linux.wait 469
proc_linux.wait 467:0proc_linux.wait 469

 Source code proc_linux.go 467

for {
		fmt.Printf("proc_linux.wait 467:%+v", s)
		wpid, err := sys.Wait4(pid, &s, sys.WNOHANG|sys.WALL|options, nil)
		fmt.Println("proc_linux.wait 469")
		if err != nil {
			return 0, nil, err
		}
		if wpid != 0 {
			return wpid, &s, err
		}
		if status(pid, dbp.os.comm) == statusZombie {
			return pid, nil, nil
		}
		time.Sleep(2000 * time.Millisecond)
	}

go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/hai/.cache/go-build"
GOENV="/home/hai/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/hai/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/hai/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build736576126=/tmp/go-build -gno-record-gcc-switches"

`Linux version 4.4.0-18362-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1049-Microsoft Thu Aug 14 12:01:00 PST 2020`

**Comment by aarzilli** [comment]
The Windows Subsystem for Linux is not supported.

**Comment by aarzilli** [comment]
PS. arguably this is a bug with WSL and should be reported to them.
