### ISSUE TITLE
Issue with variable value and stepping through the code on Apple arm64

### ISSUE THREAD

**Issue by zdima** [go-delve/delve#2346]
### What version of Delve are you using (`dlv version`)?
$ dlv version
Delve Debugger
Version: 1.6.0
Build: $Id: 8cc9751909843dd55a46e8ea2a561544f70db34d $

### What version of Go are you using? (`go version`)?
$ go version
go version go1.16 darwin/arm64

### What operating system and processor architecture are you using?
macOS 11.2 Apple M1

### What did you do?
$ git clone https://github.com/zdima/debug-test 
$ cd debug-test/
$ go build 
$ dlv debug debug-test 
(dlv) b main.callback
(dlv) c
Application start and provide a dialog with entry field and 2 buttons.
Enter text (test) into entry field, and click OK
The debugger will stop on callback function.
(dlv) p s
(dlv) n

### What did you expect to see?
The debugger for [p s] command should print value stored in variable s (test)
When command [n] entered, the debugger moved to next line 12.

### What did you see instead?
The result of [p s]
(unreadable could not read string at 0x4 due to protocol error E08 during memory read for packet $m4,40)
When [n] command entered, the program resume and stopped outside the callback function.
![Screen Shot 2021-02-17 at 10 14 59 PM](https://user-images.githubusercontent.com/298260/108300508-6f257880-716e-11eb-90e7-cdb157d2f488.png)
![Screen Shot 2021-02-17 at 10 21 29 PM](https://user-images.githubusercontent.com/298260/108300545-85333900-716e-11eb-991b-ebb7ea6dd6dd.png)

**Comment by ebilling** [comment]
I've seen similar problems with the official 1.16 release.  I went back to 1.16rc1 and things worked fine.  Unfortunately, they've pulled the installer for rc1.

**Comment by MindaWang** [comment]
I've seen similar problems with the official 1.16 rc1

**Comment by alleindrach** [comment]
I've encountered the same problem on macbook pro m1

**Comment by rahulkhairwar** [comment]
Facing a similar same issue on Macbook Pro M1, with Go1.16 and Go1.16rc1. During debug of a program, I see random behaviour for the values - sometimes they hold some random values(I've seen this behaviour for integers), sometimes they hold the error message `unreadable: protocol error E08 during memory read for packet $m40,20`.

**Comment by lcwangchao** [comment]
Same issue with me

**Comment by vince91** [comment]
I also have an issue with variable values using a specific module (go-ethereum), only on Apple arm64.

Reproduction repository: https://github.com/vince91/delve-m1

`go version go1.16 darwin/arm64`

```
Delve Debugger
Version: 1.6.0
Build: 5534839ff7165639d73fdb33950990e3841e2a3d
```

![image](https://user-images.githubusercontent.com/6903139/110106558-1e3a9480-7daa-11eb-967e-c563013695ed.png)

**Comment by aarzilli** [comment]
@vince91 or anyone else having this problem can you:

* Build @vince91's reproduction repository with this command `go build -gcflags='all=-N -l' -buildmode=exe -o testbin`
* Run delve with `dlv exec ./testbin`
* If the problem still reproduces upload testbin somewhere I can see it
* If the problem does not reproduce rebuild the repository with `go build -gcflags='all=-N -l'` and upload that binary somewhere

**Comment by aarzilli** [comment]
PS. the suspect is that this is just a duplicate of https://github.com/golang/go/issues/25841

**Comment by nd** [comment]
https://drive.google.com/file/d/130-2DyfG0BLPZ8tMiHNBSdxWowZ8J2Ar/view?usp=sharing

**Comment by nd** [comment]
If it helps, here is the output of dsymutil:

```
$ dsymutil testbin
warning: no debug symbols in executable (-arch arm64) dsymutil testbin
```

**Comment by nd** [comment]
binary without -buildmode=exe https://drive.google.com/file/d/1BeFZCXeMLHvaY3zDk5I1sru008jxq8bt/view?usp=sharing

delve fails to exec it with the error

    could not launch process: stub exited while waiting for connection: exit status 0

**Comment by aarzilli** [comment]
As suspected this is in fact a duplicate of golang/go#25841.

**Comment by aarzilli** [comment]
Someone here should try the workaround #2374 and see if it works. If it doesn't post the output with `--log-output=debugger`.

**Comment by nd** [comment]
Example provided by @vince91 works with the workaround.

**Comment by nd** [comment]
@aarzilli do you know why debugserver might fail to launch the inferior process when invoked in ssh terminal but works fine under the same user when invoked from graphical terminal in remote desktop?

**Comment by zdima** [comment]
> Someone here should try the workaround #2374 and see if it works. If it doesn't post the output with `--log-output=debugger`.

variable value show correct with this workaround!

**Comment by aarzilli** [comment]
@nd it's because it wants to show you the authentication dialog, but it can't.

**Comment by vince91** [comment]
@aarzilli many thanks for the workaround!

**Comment by filippetroviccc** [comment]
@aarzilli I've used this workaround #2374, but the issue with decoding is still present. 

Here are error messages that are showing inside a debugger.
```
 unreadable: could not read string at 0x6537333063306366 due to protocol error E08 during memory read for packet $m6537333063306366,6...
```

Also the decoded "value" (inside GoLand debugger) of a non-native type it using not showing correctly. The same occurs for structured object. I tried to extract debug log of `go-delve`, but GoLand is not allowing me to play around with custom flags and I couldn't "attach" another go delve process (on a running one) to extract the log. I can also try running debuger iVSCode or directly with CLI, just wanted to see if this is the topic of the issue.

**Comment by nd** [comment]
@filippetroviccc you can point GoLand to a wrapper script like this:

```
#!/bin/bash

/path/to/dlv --log --log-dest /path/to/dlv.log --log-output debugger $*
```

by invoking `Edit Custom Property` action, adding `dlv.path=/path/to/wrapper/script` there and restarting the IDE.

**Comment by aarzilli** [comment]
@filippetroviccc without a log or an executable file to look at it is impossible to know what the problem is. I will likely need both.

**Comment by filippetroviccc** [comment]
@nd Thank you for your help.

@aarzilli Here is the [log](https://gist.github.com/filippetroviccc/0203d0cabe5b11d38518145e97fa713f)

And I'll try to create an executable file later this evening or tomorrow.

**Comment by aarzilli** [comment]
@filippetroviccc from the log file I can tell that you aren't actually using a version of delve that has the workaround.

**Comment by filippetroviccc** [comment]
Yup, you're right. 

It's working correctly, thank you for your help.

**Comment by cfstras** [comment]
FYI, stolen from https://youtrack.jetbrains.com/issue/GO-10640:

1. Run `go get -u -v github.com/go-delve/delve/cmd/dlv@master`
2. In IntelliJ/GoLand, run action "Edit custom properties..." -> and set `dlv.path=$HOME/go/bin/dlv` (replace $HOME with you home dir!)

**Comment by itart-top** [comment]
@cfstras works for me，thanks！

**Comment by schaepher** [comment]
@cfstras works for me, thanks!

for vscode users: there's no need to configure dlv path.

**Comment by dragonly** [comment]
@cfstras It works for me, thanks!
@aarzilli BIG thanks to your workaround!!! 🎉 
Hope this will be soon in the next release.

**Comment by zdima** [comment]
Closing issue.
I am using launch configuration with following settings and have no issues:
        {
            "name": "Debug",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": "${workspaceFolder}",
            "debugAdapter": "dlv-dap",
        }
