### ISSUE TITLE
Issue installing delve

### ISSUE THREAD

**Issue by ARao0123** [go-delve/delve#2366]
1. What version of Delve are you using (`dlv version`)? - Currently 1.4, but trying to upgrade
2. What version of Go are you using? (`go version`)? - 1.16
3. What operating system and processor architecture are you using? - MacOS (amd64)
4. What did you do?

Tried to install both ways shown below:

```
abc-MacBook-Pro:~ username$ cd delve/
abc-MacBook-Pro:delve username$ go install github.com/go-delve/delve/cmd/dlv
go: go.starlark.net@v0.0.0-20200821142938-949cc6f4b097: unrecognized import path "go.starlark.net": parse https://go.starlark.net/?go-get=1: no go-import meta tags ()

abc-MacBook-Pro:delve username$ go install github.com/go-delve/delve/cmd/dlv@latest
go install github.com/go-delve/delve/cmd/dlv@latest: github.com/go-delve/delve@none updating to
	github.com/go-delve/delve@v1.6.0 requires
	go.starlark.net@v0.0.0-20200821142938-949cc6f4b097: unrecognized import path "go.starlark.net": parse https://go.starlark.net/?go-get=1: no go-import meta tags ()
```

Tried the above commands with and without sudo but no luck. Added "--check-go-version=false" in launch.json, no use.

5. What did you expect to see? - Successful upgrade to delve 1.6
6. What did you see instead? - import error related to starlark.net

**Comment by aarzilli** [comment]
I think this is either a transient network error or a network configuration problem on your end. Either way you can pass `-mod=vendor` to use the vendor directory (in the cloned repository directory). In any case this is a problem with go-starlark and I see that you have already [reported the issue there](https://github.com/google/starlark-go/issues/355).
