### ISSUE TITLE
Allow specifying location on continue

### ISSUE THREAD

**Issue by icholy** [go-delve/delve#2373]
I usually always set a breakpoint on `main.main` and then continue to it.

```
dlv debug
(dlv) b main.main
(dlv) c
```

It would be nice if I could specify this in one command.

```
dlv debug
(dlv) c main.main
```

This would:

1. Create the breakpoint.
2. Continue until it hit the breakpoint.
3. Remove the breakpoint.

**Comment by aarzilli** [comment]
This is pretty simple to implement. This is the function implementing the `continue` command:

https://github.com/go-delve/delve/blob/4364c728f0697ea63da7ddf90d8bb6a99c414dc8/pkg/terminal/command.go#L1193

Add a call to `setBreakpoint` at the start and defer a call to `t.client.ClearBreakpoint`.

**Comment by icholy** [comment]
@aarzilli I've went ahead and implement this in my fork. After playing with it, what I actually want is a "continue until here".

1. Disable all breakpoints
2. Create temp breakpoint.
3. Continue until it hit the breakpoint.
4. Remove temp breakpoint.
5. Enable all breakpoints.

Also, you should be able to pass the name of an existing breakpoint to continue until it's hit. What are your thoughts?

**Comment by aarzilli** [comment]
This behavior seems to different from the normal behavior of `continue`, and too non-orthogonal, to be part of `continue`. It seems more like a candidate for a starlark script once #2208 is merged (but you could do it already).

**Comment by icholy** [comment]
@aarzilli that's fair. I've opened a PR.
