### ISSUE TITLE
Is there a way to delve attach without stop the world?

### ISSUE THREAD

**Issue by lotsofone** [go-delve/delve#2375]
Once I run `dlv attach xxx`, the program will stop. Is there a way to print all goroutines without stop the world?

1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.6.0
Build: $Id: 8cc9751909843dd55a46e8ea2a561544f70db34d $
2. What version of Go are you using? (`go version`)?
go version go1.15.6 linux/amd64
3. What operating system and processor architecture are you using?
linux
4. What did you do?
run `dlv attach 15`
5. What did you expect to see?
the program can still respond to requests
6. What did you see instead?
requests get no response until I exit dlv

**Comment by derekparker** [comment]
Yes, you can use `dlv attach --continue <pid>`: https://github.com/go-delve/delve/blob/master/Documentation/usage/dlv_attach.md#options.

**Comment by lotsofone** [comment]
Yeal but `--continue` also requires `--headless --accept-multiclient`
The program didn't stop when I run `dlv attach 15 --continue --headless --accept-multiclient`
but It stopped again when I run `dlv connect 127.0.0.1:39801`

**Comment by derekparker** [comment]
Well once you're connected you can just issue a `continue` command, right?
