### ISSUE TITLE
locals, unreadable could not find loclist entry at 0x... for address 0x...

### ISSUE THREAD

**Issue by lotsofone** [go-delve/delve#2380]
1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.6.0
Build: $Id: 8cc9751909843dd55a46e8ea2a561544f70db34d $
2. What version of Go are you using? (`go version`)?
go version go1.15.6 linux/amd64
3. What operating system and processor architecture are you using?
Linux
4. What did you do?
run a binary file built with `go build  -gcflags="all=-N -l"`
it contains some code like this:
```
    a := 3
    b := 5
    fmt.Println(a)
    fmt.Println(b)
    for {
        message := <-s.FileStorage.MasterUpdateChan
        ........
    }
```
dlv attach to the process
run `grs`
and I see goroutine 52 is the one I need
it outputs:
`Goroutine 52 - User: ./src/master.go:42 modelpool/src.(*modelPoolServiceImpl).LoopUpdateFile (0xffcb05) [chan receive 439630h4m0.875846018s]`
showing it's blocked at `message := <-s.FileStorage.MasterUpdateChan`
run `gr 52` to switch to this goroutine
run `locals` to see local variable
5. What did you expect to see?
I should see those local variables, or `no locals` if local variables are optimized away.
6. What did you see instead?
mp = (*runtime.m)(0xc000068c00)
gp = (*runtime.g)(0xc000092d80)
status = (unreadable could not find loclist entry at 0x31e9b for address 0x443935)

**Comment by aarzilli** [comment]
The location shown by `goroutines` is not necessarily the topmost frame of the stack, check which function you are actually executing with `stack` after switching goroutines, then `frame N` to switch to the frame executing LoopUpdateFile.
