### ISSUE TITLE
goland could not attach to pid, stub exited while waiting for connection

### ISSUE THREAD

**Issue by ahuang98** [go-delve/delve#2381]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 1.6.0
Build: $Id: 8cc9751909843dd55a46e8ea2a561544f70db34d $
```
2. What version of Go are you using? (`go version`)?
```
go version go1.16 darwin/amd64
```
3. What operating system and processor architecture are you using?
macOS Catalina v 10.15.6
2.3 GHz 8-Core Intel Core i9

4. What did you do?
```
ENV_VAR=ENV_VAR_VALUE dlv --listen=:2350 --headless=true --api-version=2 --accept-multiclient exec ./MY_PROGRAM ARG1 ARG2 -- --PROGRAM_OPTION 
```
which returned 
```
API server listening at: [::]:2350
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1103.0.22
 for x86_64.
Got a connection, launched process ./MY_PROGRAM (pid = 48504).
```
In GoLand, created remote debug configuration with host: localhost, port:2350
Then 'Attach to Process', selected `48504 ARG1 ARG2 --PROGRAM_OPTION` which resulted in the following output
```
/Applications/GoLand.app/Contents/plugins/go/lib/dlv/mac/dlv --listen=0.0.0.0:55494 --headless=true --api-version=2 --check-go-version=false --only-same-user=false attach 48504 --
API server listening at: [::]:55494
could not attach to pid 48504: stub exited while waiting for connection: exit status 0

Debugger finished with exit code 1
```
What I've checked/tried:

- `/etc/hosts` file

```
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost
```
- `sudo /usr/sbin/DevToolsSecurity --enable`

- Attempted to "run debug server manually"
```
/Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver 0:0:0:0:2350 --attach=48504
```
which output
```
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1103.0.22
 for x86_64.
Attaching to process 48504...
error: failed to attach process 48504: (os/kern) invalid task - process 48504 is already being debugged
Exiting.
```
Very grateful for any help! And sorry in advance if this is an obvious issue

**Comment by aarzilli** [comment]
You are already debugging the program at PID 48504 with the first instance of delve, what you need to do is connect to it on port 2350. For example on the command line `dlv connect :2350` will do it. I don't know how to configure GoLand for this. cc @dlsniper.

**Comment by dlsniper** [comment]
@ahuang98, it would be useful to know what GoLand version you are using (make sure it's 2020.3.3 or 2021.1, now in EAP).
You can also reach out to us via our issue tracker https://youtrack.jetbrains.com/issues/Go where @s0xzwasd can do a better job at helping you out than I can.

@aarzilli, thanks for the ping!

**Comment by ahuang98** [comment]
Thanks @aarzilli and @dlsniper!
I am currently using GoLand 2020.3.2. I'll be sure to check out the issue tracker if I run into more problems!
