### ISSUE TITLE
Could not launch process on macos m1

### ISSUE THREAD

**Issue by erifan** [go-delve/delve#2382]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
    Delve Debugger
    Version: 1.6.0
    Build: $Id: 8cc9751909843dd55a46e8ea2a561544f70db34d
2. What version of Go are you using? (`go version`)?
    go version devel +7fc638d6f1 Thu Mar 11 21:43:04 2021 +0000 darwin/arm64
3. What operating system and processor architecture are you using?
    Macmini m1 chip
4. What did you do?
$ go install github.com/go-delve/delve/cmd/dlv@latest
$ cat hello.go
package main
func main() {
        println("hello")
}
$ dlv debug hello.go

5. What did you expect to see?
  dlv works as usual.
6. What did you see instead?
    could not launch process: stub exited while waiting for connection: exit status 0

**Comment by aarzilli** [comment]
Try running debugserver manually:

```
/Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver -D -- path_to_executable
```

and see what happens.

**Comment by erifan** [comment]
> Try running debugserver manually:
> 
> ```
> /Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver -D -- path_to_executable
> ```
> 
> and see what happens.

$ /Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver -D -- path_to_executable
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1200.0.44
 for arm64.
Usage:
  debugserver host:port [program-name program-arg1 program-arg2 ...]
  debugserver /path/file [program-name program-arg1 program-arg2 ...]
  debugserver host:port --attach=<pid>
  debugserver /path/file --attach=<pid>
  debugserver host:port --attach=<process_name>
  debugserver /path/file --attach=<process_name>

**Comment by nd** [comment]
Please check if running
```
sudo /usr/sbin/DevToolsSecurity -enable 
```
helps.

**Comment by aarzilli** [comment]
Try it without `-D --`:

```
/Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver path_to_executable
```

**Comment by erifan** [comment]
> Please check if running
> 
> ```
> sudo /usr/sbin/DevToolsSecurity -enable 
> ```
> 
> helps.

Output "Developer mode is now enabled.", with no luck, thanks.

**Comment by erifan** [comment]
> Try it without `-D --`:
> 
> ```
> /Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver path_to_executable
> ```
$ /Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver path_to_executable
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1200.0.44
 for arm64.
Usage:
  debugserver host:port [program-name program-arg1 program-arg2 ...]
  debugserver /path/file [program-name program-arg1 program-arg2 ...]
  debugserver host:port --attach=<pid>
  debugserver /path/file --attach=<pid>
  debugserver host:port --attach=<process_name>
  debugserver /path/file --attach=<process_name>

It also doesn't help, thanks.

**Comment by erifan** [comment]
Note that I don't have sudo right on the macmini, but I can install `dlv `and run `dlv version`. I don't know if the sudo right matters.

**Comment by aarzilli** [comment]
You are replacing path_to_executable with the path to an executable, right?

**Comment by mikfreedman** [comment]
Hi, I believe I have the same problem as OP. I am able to successfully run `dlv` and `DebugServer` using the command line by attaching to the pid. However I get this when launching from VSCode:

```
API server listening at: 127.0.0.1:22481
could not launch process: stub exited while waiting for connection: exit status 0
```


When I check out the system log here's what I see:

```
default	21:11:06.239140-0400	debugserver	debugserver will use os_log for internal logging.
default	21:11:06.239418-0400	debugserver	debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1200.0.44
 for x86_64.
default	21:11:06.239450-0400	debugserver	Usage:
  debugserver host:port [program-name program-arg1 program-arg2 ...]
default	21:11:06.239468-0400	debugserver	  debugserver /path/file [program-name program-arg1 program-arg2 ...]
default	21:11:06.239481-0400	debugserver	  debugserver host:port --attach=<pid>
default	21:11:06.239495-0400	debugserver	  debugserver /path/file --attach=<pid>
default	21:11:06.239506-0400	debugserver	  debugserver host:port --attach=<process_name>
default	21:11:06.239518-0400	debugserver	  debugserver /path/file --attach=<process_name>
default	21:11:06.246463-0400	debugserver	debugserver will use os_log for internal logging.
default	21:11:06.246768-0400	debugserver	debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1200.0.44
 for x86_64.
default	21:11:06.247359-0400	kernel	AMFI: '/Users/[user-name]/workspace/[program-name]/cmd/[program-name]/__debug_bin' has no CMS blob?
default	21:11:06.247364-0400	kernel	AMFI: '/Users/[user-name]/workspace/[program-name]/cmd/[program-name]/__debug_bin': Unrecoverable CT signature issue, bailing out.
default	21:11:06.278990-0400	authd	Succeeded authorizing right 'system.privilege.taskport.debug' by client '/usr/libexec/taskgated' [668] for authorization created by '/usr/libexec/taskgated' [6111] (3,1) (engine 48)
default	21:11:06.279495-0400	debugserver	1 +0.000000 sec [17dd/0203]: error: ::task_set_exception_ports ( task = 0x2703, exception_mask = 0x00001bfe, new_port = 0x2603, behavior = 0x80000001, new_flavor = 0x0000000d ) err = (os/kern) invalid argument (0x00000004)
default	21:11:06.279558-0400	debugserver	Could not get inferior's Mach exception port, sending ptrace PT_KILL and exiting.
default	21:11:06.279618-0400	debugserver	2 +0.000147 sec [17dd/0203]: RNBRunLoopLaunchInferior DNBProcessLaunch() returned error: '(os/kern) invalid argument'
default	21:11:06.279639-0400	debugserver	error: failed to launch process /Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver: (os/kern) invalid argument
default	21:11:06.279658-0400	debugserver	Exiting.
```

---

What version of Delve are you using (dlv version)?
Delve Debugger
Version: 1.6.0
Build: $Id: 8cc9751909843dd55a46e8ea2a561544f70db34d

What version of Go are you using? (go version)?
go version go1.16rc1 darwin/arm64

What operating system and processor architecture are you using?
Big Sur 11.2.1
MacBook Pro (13-inch, M1, 2020)

What did you do?
```
$ go install github.com/go-delve/delve/cmd/dlv@latest
$ cat hello.go

package main

func main() {
	println("hello")
}

$ dlv debug hello.go

Type 'help' for list of commands.
(dlv)
```
*Success!*

But when I launch dlv from a VS Code debug configuration i get: 

```
could not launch process: stub exited while waiting for connection: exit status 0
```

Appreciate that this is probably a VS Code go extension configuration problem but it seemed like an exact match for this issue too so I thought i'd post the extra info!

**Comment by erifan** [comment]
Hi, I have figured out the reason. The user of dlv need to be a developer group member.
$ sudo dscl . append /Groups/_developer GroupMembership dlv_user
