### ISSUE TITLE
无法在windows x64安装 

### ISSUE THREAD

**Issue by pyjlwc2016** [go-delve/delve#2396]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
2. What version of Go are you using? (`go version`)?
3. What operating system and processor architecture are you using?
4. What did you do?
5. What did you expect to see?
6. What did you see instead?

**Comment by pyjlwc2016** [comment]
go version go1.16.2 windows/386
执行这个go install github.com/derekparker/delve/cmd/dlv  
报错，不支持

**Comment by aarzilli** [comment]
windows/386 is not supported install windows/amd64.

**Comment by pyjlwc2016** [comment]
what version should i choose?give me a  installation package .thank you
