### ISSUE TITLE
your_operating_system_and_architecture_combination_is_not_supported_by_delve error while installing

### ISSUE THREAD

**Issue by gekigek99** [go-delve/delve#2401]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
none

2. What version of Go are you using? (`go version`)?
go version go1.15.2 windows/386

3. What operating system and processor architecture are you using?
windows 10 - 64bit

4. What did you do?
try to install dlv

5. What did you expect to see?
dlv to be installed successfully

6. What did you see instead?
an error message

trace:
```
C:\Users\gekigek99>go get -v github.com/go-delve/delve/cmd/dlv
github.com/go-delve/delve (download)
go\src\github.com\go-delve\delve\service\debugger\debugger.go:26:2: found packages native (proc.go) and your_operating_system_and_architecture_combination_is_not_supported_by_delve (support_sentinel.go) in C:\Users\gekigek99\go\src\github.com\go-delve\delve\pkg\proc\native
```

what can I do to solve this? windows 10 64-bit should be supported right? (because the only `your_operating_system_and_architecture_combination_is_not_supported_by_delve` error that I could find was about ARM)

**Comment by dlsniper** [comment]
Use the Go version for 64bit (it should be the amd64 on) instead of 32 bit one (the 386 one).

**Comment by aarzilli** [comment]
Closing, what @dlsniper said.

**Comment by gekigek99** [comment]
> Use the Go version for 64 bit (it should be the amd64 one) instead of 32 bit one (the 386 one).

Yep I **obviously** tried that, but it does not work

**Comment by dlsniper** [comment]
> Yep I obviously tried that, but it does not work

Per report above:

> go version go1.15.2 windows/386

So, please make sure you use the correct binary when installing the amd64 version. 
Assuming you are installing it via the `.msi` installer, here's the correct link https://golang.org/dl/go1.15.6.windows-amd64.msi

Also, make sure you uninstall the 386 version first.

**Comment by gekigek99** [comment]
ok thank you a did that before... but maybe it's a problem with go... now I installed the 1.15.10 version and i get this:
```

C:\Users\gekigek99>go env
set GO111MODULE=auto
set GOARCH=386
set GOBIN=
set GOCACHE=C:\Users\gekigek99\AppData\Local\go-build
set GOENV=C:\Users\gekigek99\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
...
```

i really do not understandd why `GOARCH=386` and `GOHOSTARCH=amd64` (after a clean golang installation)...

anyway, setting `GOARCH=amd64` solved the problem

thank you for the support

**Comment by gekigek99** [comment]
apparently I had the go env file (`C:\Users\gekigek99\AppData\Roaming\go\env`) set like this:

```
GOARCH=386
GO111MODULE=auto
GOOS=windows
```

so that GOARCH was always set to 386 even though golang architecture was amd64

running `go env -u GOARCH` fixed the problem for me (unset the GOARCH parameter from go env file)  
(also removing the go env file works)
