### ISSUE TITLE
couldn't start listener: listen tcp: address 40000: missing port in address

### ISSUE THREAD

**Issue by dragonDScript** [go-delve/delve#2404]
1. What version of Delve are you using (`dlv version`)?
I'm running this in Docker, so every time I build my docker container I update the version. I can reproduce this from any version.
2. What version of Go are you using? (`go version`)?
1.16.2 (also happened in 1.15)
3. What operating system and processor architecture are you using?
Linux (Ubuntu) AMD64.
4. What did you do?
I started a delve listener (`dlv debug ./main --headless --listen 40000`)
5. What did you expect to see?
A new listener is created on port 0.0.0.0:40000, which can be used from any program.
6. What did you see instead?
I got this message error: couldn't start listener: listen tcp: address 40000: missing port in address

**Comment by aarzilli** [comment]
The argument of listen is an address, not a port number: `--listen :40000`.
