### ISSUE TITLE
How to show source code for go modules after step in a breakpoint?

### ISSUE THREAD

**Issue by a2232189** [go-delve/delve#2419]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
1.6.0
2. What version of Go are you using? (`go version`)?
go version go1.14.10 linux/amd64
3. What operating system and processor architecture are you using?
Linux
4. What did you do?
dlv attach 23
b file_name.go:426
c
(After breakpoint was hit)
s
n
n
s(enter a function from a go module)

5. What did you expect to see?
See source code around the current location of the line from the go module
```
something like this
  421:
   422:		go func() {
   423:			ticker := time.NewTicker(time.Minute * 10)
   424:			for range ticker.C {
   425:				progress := atomic.LoadInt64(&userDoneCounter) * 100 / maxUserid
=> 426:				clog.Infof(context.TODO(), "Scanned %d%% users, scanned user count:%d, "+
   427:					"total users count:%d will report progress every 10 mins",
   428:					progress, userDoneCounter, maxUserid)
   429:
   430:				fmt.Printf( "Printed by fmt. Scanned %d%% users, scanned user count:%d, "+
   431:					"total users count:%d will report progress every 10 mins\n",
(dlv) s
```
6. What did you see instead?

```
(dlv) s
> git.xx.com/xx/xx/x/clog.Infof() /root/go/pkg/mod/xx/xx/xx/xx@v0.0.74/clog/clog.go:390 (PC: 0xff5f78)
```
Additional info:
I built the program with `-gcflags="all=-N -l"`

**Comment by aarzilli** [comment]
If you try to `cat /root/go/pkg/mod/xx/xx/xx/xx@v0.0.74/clog/clog.go` does it work? If not, that's your problem. See `help config`, in particular `config substitute-path` for how to deal with this.

**Comment by a2232189** [comment]
Thanks. `cat /root/go/pkg/mod/xx/xx/xx/xx@v0.0.74/clog/clog.go doesn't work.` and yes it's my problem
