### ISSUE TITLE
g command fails on most recent version of debugserver on darwin/arm64

### ISSUE THREAD

**Issue by susnow** [go-delve/delve#2436]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)? Version 1.6.0
2. What version of Go are you using? (`go version`)? Go1.16.2
3. What operating system and processor architecture are you using? Macmini m1 chip
4. What did you do? 

- cd /Documents && mkdir test && cd test && touch main.go 

- use vscode set main.go like 

 `
package main 
import "fmt"
 
func main() {
	a := 1
 	fmt.Print("123")
 	fmt.Println(a)
}
`

- add  break point at line 6 and line 8
- go mod init test
- go mod tidy
- create default debug config ./vscode/launch.json
`{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Package",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": "${workspaceFolder}"
        }
    ]
}`
- click Launch Package

5. What did you expect to see? run debug success and go to breakpoint
6. What did you see instead?
![image](https://user-images.githubusercontent.com/990980/114668250-1835bd00-9d33-11eb-8c9b-ae99015f08f3.png)

无法加载源“”。means can not  load source

what should i do?

**Comment by aarzilli** [comment]
This looks like a problem with your computer, try updating or reinstalling xcode. See if the same thing happens using lldb.

**Comment by jimcroft** [comment]
I've encountered the same problem but only with the Big Sur 11.3 betas (with current and beta xcode's too), under Big Sur 11.2 delve works fine for me.

I didn't raise the issue as all bets are off running a beta, but if anyone wants any additional info or debug I'm happy to provide

**Comment by aarzilli** [comment]
@jimcroft you could see if the same thing happens using lldb with a compiled binary. Also in pkg/proc/gdbserial/gdbserver.go there's a version check that sets `p.gcmdok = false`, you could try to enable it always, it could be that they broke the `g` command again.

**Comment by jimcroft** [comment]
Thanks @aarzilli !!

I've changed the version number checked for [here](https://github.com/go-delve/delve/blob/master/pkg/proc/gdbserial/gdbserver.go#L337) to `1205` and delve is working for me again. 🎉 

FYI:

```
❯ /Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1205.0.22
 for arm64.
```

**Comment by aarzilli** [comment]
You should report this problem to apple/llvm, after all that's what betas are for.

**Comment by susnow** [comment]
> 1205



> Thanks @aarzilli !!
> 
> I've changed the version number checked for [here](https://github.com/go-delve/delve/blob/master/pkg/proc/gdbserial/gdbserver.go#L337) to `1205` and delve is working for me again. 🎉
> 
> FYI:
> 
> ```
> ❯ /Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver
> debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1205.0.22
>  for arm64.
> ```

i'll try resintall xcode and set this code  and  report the newest status

**Comment by susnow** [comment]
> > 1205
> 
> > Thanks @aarzilli !!
> > I've changed the version number checked for [here](https://github.com/go-delve/delve/blob/master/pkg/proc/gdbserial/gdbserver.go#L337) to `1205` and delve is working for me again. 🎉
> > FYI:
> > ```
> > ❯ /Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver
> > debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1205.0.22
> >  for arm64.
> > ```
> 
> i'll try resintall xcode and set this code and report the newest status

last it still can't work, i've reinstall xcode, and changed the version number to 1205

i get the same result can't load source

**Comment by aarzilli** [comment]
Try doing the same thing but on the command line, pass the options `--log --log-output=gdbwire` and post the output.

**Comment by sebastian-quintero** [comment]
Hi! I am experiencing similar issues. Everything was working fine and all of a sudden it isn't working. I think something got updated in the background that I didn't notice but now the debugger doesn't work anymore. This is what I have tried so far:
- Removing go completely and reinstalling via homebrew.
- Removing the go extension from VSCode and reinstalling.
- Removing Xcode from my system and reinstalling.

1. What version of Delve are you using (`dlv version`)?
```
❯ dlv version
Delve Debugger
Version: 1.6.0
Build: $Id: 8cc9751909843dd55a46e8ea2a561544f70db34d $
```
2. What version of Go are you using? (`go version`)?
```
❯ go version
go version go1.16.3 darwin/arm64
```
3. What operating system and processor architecture are you using?
- operating system: macOS Big Sur 11.2.3
- processor architecture: m1 apple sillicon
4. What did you do?
Try to debug anything.
5. What did you expect to see?
The debugging interface working.
6. What did you see instead?
```
PI server listening at: 127.0.0.1:4324
Failed to continue - protocol error E74 during registers read for packet $g;thread:61c7;
Last known immediate stacktrace (goroutine id 0):
	?:-1
		<unknown>
	:0
		<unknown>


```
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/42215971/116307658-3b695f00-a76c-11eb-866c-c3546bbb58a9.png">

**Comment by rwbaskette** [comment]
I am now experiencing the same problem after upgrading to macOS 11.3...

**system:**
```
% uname -a
Darwin hsot.domain 20.4.0 Darwin Kernel Version 20.4.0: Fri Mar  5 01:14:02 PST 2021; root:xnu-7195.101.1~3/RELEASE_ARM64_T8101 arm64
```

**go:**
```
% go version
go version go1.16.3 darwin/arm64
```

**dlv** :
```
% dlv version
Delve Debugger
Version: 1.6.0
Build: $Id: 8cc9751909843dd55a46e8ea2a561544f70db34d $
```

**debug console:**
```
API server listening at: 127.0.0.1:28107
Failed to continue - protocol error E74 during registers read for packet $g;thread:fb41;
Last known immediate stacktrace (goroutine id 0):
	?:-1
		<unknown>
	:0
		<unknown>

Failed to get list local variables - unable to find function context
Last known immediate stacktrace (goroutine id 0):
	?:-1
		<unknown>
	:0
		<unknown>
```

**Comment by sebastian-quintero** [comment]
I was looking into using the backend of delve to see if I could get it to work and maybe the issue was with VS Code, but I doesn't work either. I set up a simple program:

```go
package main

import "fmt"

func main() {
	msg := "Please help me."
	fmt.Println(msg)
}

```

Then ran the debugger...
```
❯ dlv debug main.go
Type 'help' for list of commands.
(dlv)
````

And set a breakpoint:
```
(dlv) break main.go:7
Breakpoint 1 set at 0x104f0bed0 for main.main() ./main.go:7
````

And got this after trying to `continue`:
```
(dlv) continue
Stopped at: 0x0
=>   1:	no source available
Command failed: protocol error E74 during registers read for packet $g;thread:ad85;
```

It seems the delve debugger did stop working for me... Not sure how to proceed.

**Comment by RuffianLiu** [comment]
![1619574846745](https://user-images.githubusercontent.com/72987542/116335208-08c17400-a809-11eb-97bb-4047763db948.jpg)


> Hi! I am experiencing similar issues. Everything was working fine and all of a sudden it isn't working. I think something got updated in the background that I didn't notice but now the debugger doesn't work anymore. This is what I have tried so far:
> 
> * Removing go completely and reinstalling via homebrew.
> * Removing the go extension from VSCode and reinstalling.
> * Removing Xcode from my system and reinstalling.
> 
> 1. What version of Delve are you using (`dlv version`)?
> 
> ```
> ❯ dlv version
> Delve Debugger
> Version: 1.6.0
> Build: $Id: 8cc9751909843dd55a46e8ea2a561544f70db34d $
> ```
> 
> 1. What version of Go are you using? (`go version`)?
> 
> ```
> ❯ go version
> go version go1.16.3 darwin/arm64
> ```
> 
> 1. What operating system and processor architecture are you using?
> 
> * operating system: macOS Big Sur 11.2.3
> * processor architecture: m1 apple sillicon
> 
> 1. What did you do?
>    Try to debug anything.
> 2. What did you expect to see?
>    The debugging interface working.
> 3. What did you see instead?
> 
> ```
> PI server listening at: 127.0.0.1:4324
> Failed to continue - protocol error E74 during registers read for packet $g;thread:61c7;
> Last known immediate stacktrace (goroutine id 0):
> 	?:-1
> 		<unknown>
> 	:0
> 		<unknown>
> ```
> 
> 
I was also caused by the upgrade. Later, the DLV source code was modified and recompiled
<img alt="image" width="1437" src="https://user-images.githubusercontent.com/42215971/116307658-3b695f00-a76c-11eb-866c-c3546bbb58a9.png">

**Comment by RuffianLiu** [comment]
> 你好！我遇到类似的问题。一切工作正常，突然间它不工作。我认为某些内容在后台被更新了，但我没有注意到，但是现在调试器不再起作用了。到目前为止，这是我尝试过的：
> 
> * 完全移除go，然后通过自制软件重新安装。
> * 从VSCode移除go扩展，然后重新安装。
> * 从我的系统中删除Xcode并重新安装。
> 
> 1. 您正在使用哪个版本的Delve（`dlv version`）？
> 
> ```
> ❯ dlv version
> Delve Debugger
> Version: 1.6.0
> Build: $Id: 8cc9751909843dd55a46e8ea2a561544f70db34d $
> ```
> 
> 1. 您正在使用哪个版本的Go？（`go version`）？
> 
> ```
> ❯ go version
> go version go1.16.3 darwin/arm64
> ```
> 
> 1. 您正在使用什么操作系统和处理器体系结构？
> 
> * 操作系统：macOS Big Sur 11.2.3
> * 处理器架构：M1苹果sillicon
> 
> 1. 你做了什么？
>    尝试调试任何东西。
> 2. 您期望看到什么？
>    调试界面正常工作。
> 3. 您看到了什么？
> 
> ```
> PI server listening at: 127.0.0.1:4324
> Failed to continue - protocol error E74 during registers read for packet $g;thread:61c7;
> Last known immediate stacktrace (goroutine id 0):
> 	?:-1
> 		<unknown>
> 	:0
> 		<unknown>
> ```
> 
> 

<img alt="图像" width="1437" src="https://user-images.githubusercontent.com/42215971/116307658-3b695f00-a76c-11eb-866c-c3546bbb58a9.png">
I was caused by upgrading 11.3. After adding the code as shown in the figure to the dlv source code, dlv continued to work for me

**Comment by RuffianLiu** [comment]
> 你好！我遇到类似的问题。一切工作正常，突然间它不工作。我认为某些内容在后台被更新了，但我没有注意到，但是现在调试器不再起作用了。到目前为止，这是我尝试过的：
> 
> * 完全移除go，然后通过自制软件重新安装。
> * 从VSCode移除go扩展，然后重新安装。
> * 从我的系统中删除Xcode并重新安装。
> 
> 1. 您正在使用哪个版本的Delve（`dlv version`）？
> 
> ```
> ❯ dlv version
> Delve Debugger
> Version: 1.6.0
> Build: $Id: 8cc9751909843dd55a46e8ea2a561544f70db34d $
> ```
> 
> 1. 您正在使用哪个版本的Go？（`go version`）？
> 
> ```
> ❯ go version
> go version go1.16.3 darwin/arm64
> ```
> 
> 1. 您正在使用什么操作系统和处理器体系结构？
> 
> * 操作系统：macOS Big Sur 11.2.3
> * 处理器架构：M1苹果sillicon
> 
> 1. 你做了什么？
>    尝试调试任何东西。
> 2. 您期望看到什么？
>    调试界面正常工作。
> 3. 您看到了什么？
> 
> ```
> PI server listening at: 127.0.0.1:4324
> Failed to continue - protocol error E74 during registers read for packet $g;thread:61c7;
> Last known immediate stacktrace (goroutine id 0):
> 	?:-1
> 		<unknown>
> 	:0
> 		<unknown>
> ```
> 
> 

<img alt="图像" width="1437" src="https://user-images.githubusercontent.com/42215971/116307658-3b695f00-a76c-11eb-866c-c3546bbb58a9.png">
I was caused by upgrading 11.3. After adding the code as shown in the figure to the dlv source code, dlv continued to work for me

**Comment by RuffianLiu** [comment]
> I am now experiencing the same problem after upgrading to macOS 11.3...
> 
> **system:**
> 
> ```
> % uname -a
> Darwin hsot.domain 20.4.0 Darwin Kernel Version 20.4.0: Fri Mar  5 01:14:02 PST 2021; root:xnu-7195.101.1~3/RELEASE_ARM64_T8101 arm64
> ```
> 
> **go:**
> 
> ```
> % go version
> go version go1.16.3 darwin/arm64
> ```
> 
> **dlv** :
> 
> ```
> % dlv version
> Delve Debugger
> Version: 1.6.0
> Build: $Id: 8cc9751909843dd55a46e8ea2a561544f70db34d $
> ```
> 
> **xcode version:**
> 
> ```
> % xcodebuild -version
> Xcode 12.5
> Build version 12E262
> ```
> 
> **debug console:**
> 
> ```
> API server listening at: 127.0.0.1:28107
> Failed to continue - protocol error E74 during registers read for packet $g;thread:fb41;
> Last known immediate stacktrace (goroutine id 0):
> 	?:-1
> 		<unknown>
> 	:0
> 		<unknown>
> 
> Failed to get list local variables - unable to find function context
> Last known immediate stacktrace (goroutine id 0):
> 	?:-1
> 		<unknown>
> 	:0
> 		<unknown>
> ```

![1619574846745](https://user-images.githubusercontent.com/72987542/116336341-f47e7680-a80a-11eb-94ba-3759afa8c535.jpg)
I was caused by upgrading 11.3. After adding the code as shown in the figure to the dlv source code, dlv continued to work for me

**Comment by sebastian-quintero** [comment]
Ok so I figured what happened on my end. I had installed `xcode` via the App Store on Mac. I had set the app store to update my apps automatically (big mistake). Yesterday, `xcode` was automatically updated to 12.5 as you can see from the [More Downloads for Apple Developers](https://developer.apple.com/download/more/?q=xcode) page. What I did to solve the issue was:
1. Uninstall `xcode` following [this tutorial](https://dzone.com/articles/how-to-completely-uninstall-xcode-from-mac).
2. Reboot.
3. Install `xcode` version 12.4 from the  [More Downloads for Apple Developers](https://developer.apple.com/download/more/?q=xcode) page.
<img width="753" alt="image" src="https://user-images.githubusercontent.com/42215971/116336770-bea3a880-a79e-11eb-8351-d883642d2c96.png">
4. Reboot.

After this, everything is working correctly. I would presume something is fishy about `xcode` 12.5. Hope this helps

**Comment by aarzilli** [comment]
Anyone experiencing this issue should:

1. post the output produced by delve when using the options `--log --log-output=gdbwire`.
2. try the workaround in https://github.com/go-delve/delve/issues/2436#issuecomment-821809170

in this order.

**Comment by MarcelXia** [comment]
I've changed a local delve to have the option
```
				if v[len("version:"):] == "1205" && p.bi.Arch.Name == "arm64" {
					p.gcmdok = false
				}
```
and can confirm this works on the latest xcode

**Comment by rwbaskette** [comment]
Patching worked!

@aarzilli - logs per your request

Stock:
[dlv-1.6.0.log](https://github.com/go-delve/delve/files/6394170/dlv-1.6.0.log)

Patched:
[dlv-1.6.0-patched.log](https://github.com/go-delve/delve/files/6394172/dlv-1.6.0-patched.log)

**Comment by ormissia** [comment]
> > I am now experiencing the same problem after upgrading to macOS 11.3...
> > **system:**
> > ```
> > % uname -a
> > Darwin hsot.domain 20.4.0 Darwin Kernel Version 20.4.0: Fri Mar  5 01:14:02 PST 2021; root:xnu-7195.101.1~3/RELEASE_ARM64_T8101 arm64
> > ```
> > 
> > 
> > **go:**
> > ```
> > % go version
> > go version go1.16.3 darwin/arm64
> > ```
> > 
> > 
> > **dlv** :
> > ```
> > % dlv version
> > Delve Debugger
> > Version: 1.6.0
> > Build: $Id: 8cc9751909843dd55a46e8ea2a561544f70db34d $
> > ```
> > 
> > 
> > **xcode version:**
> > ```
> > % xcodebuild -version
> > Xcode 12.5
> > Build version 12E262
> > ```
> > 
> > 
> > **debug console:**
> > ```
> > API server listening at: 127.0.0.1:28107
> > Failed to continue - protocol error E74 during registers read for packet $g;thread:fb41;
> > Last known immediate stacktrace (goroutine id 0):
> > 	?:-1
> > 		<unknown>
> > 	:0
> > 		<unknown>
> > 
> > Failed to get list local variables - unable to find function context
> > Last known immediate stacktrace (goroutine id 0):
> > 	?:-1
> > 		<unknown>
> > 	:0
> > 		<unknown>
> > ```
> 
> ![1619574846745](https://user-images.githubusercontent.com/72987542/116336341-f47e7680-a80a-11eb-94ba-3759afa8c535.jpg)
> I was caused by upgrading 11.3. After adding the code as shown in the figure to the dlv source code, dlv continued to work for me

- I add this code to delve and rebuild, copy dlv to a temp path, I am using `/Users/myName/go/bin`.

- Open goland and run the `Edit Custom Properties` action (`Help | Edit Custom Properties`), add the path to Delve on a new line: `dlv.path=/path/to/delve/macarm` (e.g. `dlv.path=/Users/myName/go/bin/dlv`).
Flowing this step [Goland Edit Custom Properties](https://youtrack.jetbrains.com/issue/GO-11011#focus=Comments-27-4864841.0-0).

![image](https://user-images.githubusercontent.com/55517494/116495715-0e38c000-a8d6-11eb-9117-92a6fb7eb41c.png)

- And then debug normaly.
🥰🥰🥰

**Comment by dllexport** [comment]
just update my xcode to 12.5 and encounter the same issue

**Comment by aarzilli** [comment]
Reported to LLVM to https://bugs.llvm.org/show_bug.cgi?id=50169

**Comment by mensurm** [comment]
Had this problem as well. 
Installed via 
`go install github.com/go-delve/delve/cmd/dlv@latest` 

It installed 1.6.0

It seems this was fixed, just isn't released yet. 
So when I installed it this way, the debugger is working.

```
$ git clone https://github.com/go-delve/delve
$ cd delve
$ go install github.com/go-delve/delve/cmd/dlv
```

**Comment by andig** [comment]
Or simpler:

    go install github.com/go-delve/delve/cmd/dlv@master

**Comment by tamsanh** [comment]
Thank you @mensurm, @ormissia 

These are the steps that I took that worked for me with GoLand 2021.1 on Mac 11.2.3

I first took @mensurm's [advice](https://github.com/go-delve/delve/issues/2436#issuecomment-833564263) (can be done in any directory) 
```
git clone https://github.com/go-delve/delve
cd delve
go install github.com/go-delve/delve/cmd/dlv
```

This makes the new `dlv` available in your `$GOPATH/bin`. One can get the path with:

```
ls $GOPATH/bin/dlv
```
![image](https://user-images.githubusercontent.com/1330789/117531968-bb6ab100-b017-11eb-847b-c33d8a4fb065.png)

If no errors appear, then that's the path you can use when you follow @ormissia 's [advice](https://github.com/go-delve/delve/issues/2436#issuecomment-828903032), and paste the value in the `idea.properties` file.

![image](https://user-images.githubusercontent.com/1330789/117531990-d50bf880-b017-11eb-866d-e993c98b5303.png)

**Comment by rsippl** [comment]
No need to clone the repo, just install with

`go install github.com/go-delve/delve/cmd/dlv@master`

Once the fix is released, switch back to `latest`:

`go install github.com/go-delve/delve/cmd/dlv@latest`

**Comment by manavdahra** [comment]
@tamsanh Your solution really helped me! thanks a ton

**Comment by MarcelXia** [comment]
Updated to a newer version of Go and now there's the issue again. I tried the patch on the latest version of delve, but the code of the Connect function is rewritten, so it is not possible to implement the fix at that point. Perhaps someone with in-depth knowledge can make a new fix proposal?

**Comment by zakhar-petukhov** [comment]
how to fix ` error failed to allocate vm space for aot`

**Comment by microyahoo** [comment]
The issue still exists in new version again.
```
🍺 /Users/zhl/go/src/github.com/grpc/grpc-go/examples/helloworld ☞ git:(master) ✗ dlv exec client
Type 'help' for list of commands.
(dlv) b main.main
Breakpoint 1 (enabled) set at 0x13d919b for main.main() ./greeter_client/main.go:37
(dlv) c
rosetta error: failed to allocate vm space for aot
Stopped at: 0x0
=>   1:	no source available
(dlv) exit
🍺 /Users/zhl/go/src/github.com/grpc/grpc-go/examples/helloworld ☞ git:(master) ✗ dlv version
Delve Debugger
Version: 1.6.1
Build: de117a2f4f16350a59b06970693d383613399782
🍺 /Users/zhl/go/src/github.com/grpc/grpc-go/examples/helloworld ☞ git:(master) ✗ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/zhl/Library/Caches/go-build"
GOENV="/Users/zhl/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/zhl/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/zhl/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.4"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/zhl/go/src/github.com/grpc/grpc-go/examples/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/x2/p8kghjr100j209q5zspdwhgc0000gn/T/go-build2395424900=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by myungsworld** [comment]
@MarcelXia Did you fix it? if you did can you advise a little?

**Comment by MarcelXia** [comment]
I did by going back to an older version of the xcode developers tools

**Comment by pokitpeng** [comment]
same environment, I cant run dlv but program cannot stop at a breakpoint.
