### ISSUE TITLE
Couldn't debug codes compiled by gccgo

### ISSUE THREAD

**Issue by RobotHuang** [go-delve/delve#2438]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 1.6.0
Build: $Id: 8cc9751909843dd55a46e8ea2a561544f70db34d $
```
2. What version of Go are you using? (`go version`)?
```
go version go1.14.2 gccgo (GCC) 10.1.0 linux/amd64
```
3. What operating system and processor architecture are you using?
```
Centos7 amd64
```
4. What did you do?
`dlv debug --headless --listen=:2345 --api-version=2`
5. What did you expect to see?
run successfully
6. What did you see instead?
```
go build: when using gccgo toolchain, please pass compiler flags using -gccgoflags, not -gcflags
API server listening at: [::]:2345
could not launch process: could not parse .eh_frame section: pointer encoding not supported 0x3 at 0x730
```

**Comment by aarzilli** [comment]
gccgo is not supported.
