### ISSUE TITLE
Can't determine source file for 'runtime.call64' and 'runtime.call1024'

### ISSUE THREAD

**Issue by JadenSimon** [go-delve/delve#2442]
1. What version of Delve are you using (`dlv version`)?
- 1.6.0
2. What version of Go are you using? (`go version`)?
- 1.16.3 
3. What operating system and processor architecture are you using?
- darwin/amd64

I'm running Delve in headless exec mode and using VS Code's Go extension (https://github.com/golang/vscode-go) as a debug client. I'm also cross-compiling the target binary and Delve to linux/amd64. The binary + Delve are being run in a container on my local machine. Delve will hit breakpoints correctly in my program, but for some reason it will send an empty file location ("") for functions `runtime.call64` and `runtime.call1024` when the correct location is `/usr/local/go/src/runtime/asm_amd64.s`. The Go extension's debug client breaks because it does not expect an empty file location. Delve will send the correct location when the binary is compiled with Go1.14, but not for Go1.15 or Go.1.16. 

Here is an example taken from the Go extension debug client logs (StackTraceRequest):
``{"pc":4627612,"file":"","line":0,"function":{"name":"runtime.call1024","value":4627520,"type":0,"goType":0,"optimized":true},"Locals":[],"Arguments":[],"FrameOffset":-2280,"FramePointerOffset":-2296,"Defers":[],"Err":""}``

Here is what I expect (binary compiled with Go1.14.15):
``{"pc":4589589,"file":"/usr/local/go/src/runtime/asm_amd64.s","line":1,"function":{"name":"runtime.call1024","value":4589504,"type":0,"goType":0,"optimized":true},"Locals":[],"Arguments":[],"FrameOffset":-2328,"FramePointerOffset":-2344,"Defers":[],"Err":""}``

Binary is built with `-gcflags="all=-N -l"`and Delve is run with API version 2 for all cases.
Unfortunately, I cannot access Delve's debugline logs at this time. I'll update this issue if I can get them.

**Comment by aarzilli** [comment]
This is happening because of a change to Delve, introduced to work around a different bug with the debug_line table. Given that the other bug was common and more damaging and this basically only affects assembly functions generated with the macro feature of the go assembler, that nobody seems to use, this bug is a likely "won't fix".

**Comment by JadenSimon** [comment]
Understandable. My concern was primarily with the debug client breaking from this bug. I've opened an issue with the Go extension, since a fix on their end makes more sense in this scenario.

**Comment by aarzilli** [comment]
Closing, won't fix as described above.
