### ISSUE TITLE
Allow attaching to a process without pausing the execution

### ISSUE THREAD

**Issue by dlsniper** [go-delve/delve#245]
Sorry, the issue was created too fast :D 
Proper description:
Given the following app:

``` go
package main

import (
    "fmt"
    "net/http"
)

func handler(w http.ResponseWriter, r *http.Request) {
    fmt.Fprintln(w, "hello")
}

func main() {

    handlers := http.NewServeMux()
    handlers.HandleFunc("/", handler)
    server := &http.Server{Addr: ":8889", Handler: handlers}

    server.ListenAndServe()
}
```

When I'm doing the following steps:

``` bash
go build -gcflags "-N -l" -o demo demo.go
./demo &
dlv attach `pgrep demo`
```

I can observe a pause in execution until I send the `continue` command to the debugger.

While I do understand that it might be useful to have that functionality, say for example I want to hook up in a staging app that has traffic on it (sample traffic), attaching to its process and having it paused is not ideal (for example I want to set tracepoints rather that breakpoints).

Do you think it would be useful to have an `attach --no-pause` flag?

**Comment by derekparker** [comment]
I can't see the value of starting an actual debug session without pausing unless you're simply relying on providing an `init` file (to load breakpoints / tracepoints) and then want to simply immediately continue execution, which you _could_ do by simply writing a `continue` command at the end of the init file.

You can already set tracepoints without stopping the program indefinitely with the `trace` subcommand, which takes a pid flag.

**Comment by luisgarciaalanis** [comment]
@derekparker I run the code in a docker container and remote debug. So for normal development its nice to auto run, then I could click the play button on VSCODE to attach, add a breakpoint and rerun to hit the breakpoint. 

it would be quite convinient to be able to do this.

**Comment by luisgarciaalanis** [comment]
reflex -s -r '\.go$' -- dlv --listen=:5432 debug --headless=true --init <(printf continue)
this does not auto continue :(

**Comment by aarzilli** [comment]
Closed by 9a216211d3461ab031f822c012bc27cab9758da0

**Comment by dlsniper** [comment]
@aarzilli I read the changelog of the commit that closed this but I'm not sure how to use delve to do it (and I haven't tried it yet either). Is the original reported case possible now? Thank you.

**Comment by gm42** [comment]
In case of `--headless` the `--init` gets ignored with the following message in output:
```
Warning: init file ignored
```

Thus a separate client connection is needed to start the process; this is not container friendly and some hack is needed to trigger the operation externally.

**Comment by hypnoce** [comment]
I'm not sure if this problem is solved, but in some scenarios it can be nice to start a go binary with delve without pausing the execution, like running java with `suspend=n`.
Do you see any value into this ?

**Comment by derekparker** [comment]
I'm going to reopen this as it technically is not fixed, we currently just support a workaround.

**Comment by briandealwis** [comment]
Having a no-suspend option is useful for debugging go-based microservices in containers.
