### ISSUE TITLE
No SSE/AVX/AVX-512 registers visible on darwin/amd64

### ISSUE THREAD

**Issue by vsivsi** [go-delve/delve#2479]
1. What version of Delve are you using (`dlv version`)?
v1.6 / latest master

2. What version of Go are you using? (`go version`)?
v1.6.3

3. What operating system and processor architecture are you using?
MacOS 10.15.7  darwin/amd64

4. What did you do?
Tried to inspect XMMn / YMMn / ZMMn / Kn register values using `regs -a` and the new 
`print <reg>` functionality (PR: https://github.com/go-delve/delve/pull/2446)

5. What did you expect to see?
The current value(s) of these vector/mask registers. 

6. What did you see instead?

```
(dlv) print %x RAX
c0001ec000
(dlv) print %x XMM0
Command failed: could not find symbol value for XMM0
```

And

```
(dlv) regs -a
   Rip = 0x000000000116eff5
   Rsp = 0x000000c0000c8d10
   Rax = 0x000000c0001ec000
   Rbx = 0x0000000000000000
   Rcx = 0x0000000000000000
   Rdx = 0x000000000085c5bc
   Rsi = 0x00000000000000c0
   Rdi = 0x000000c0001ec0c0
   Rbp = 0x000000c0000c8ec8
    R8 = 0x00000000000000b0
    R9 = 0x0000000000000016
   R10 = 0x0000000000000000
   R11 = 0x0000000000000000
   R12 = 0x000000000880f606
   R13 = 0x0000000000000000
   R14 = 0x00000000000000c0
   R15 = 0x000000000000000c
 ST(0) = 0x7fff0000000000000000	-Inf
 ST(1) = 0x00000000000000000000	0
 ST(2) = 0x7fff0000000000000000	-Inf
 ST(3) = 0x7fff00000000fe9d66b0	-Inf
 ST(4) = 0x7fff0000000000000000	-Inf
 ST(5) = 0x7fff0000000000000000	-Inf
 ST(6) = 0x7fff00000000fffff85c	-Inf
 ST(7) = 0x7fff00000000ffffe822	-Inf
Rflags = 0x0000000000000246	[PF ZF IF IOPL=0]
    Cs = 0x000000000000002b
    Fs = 0x0000000000000000
    Gs = 0x0000000000000000
 MXCSR = 0x00001fa0	[RZ/RN=0 PM UM OM ZM DM IM PE]
```

**Comment by aarzilli** [comment]
Can you post the output of `dlv --log --log-output=gdbwire ...`. There's a test for this we're running in CI so it's quite strange.

**Comment by vsivsi** [comment]
@aarzilli   Sure thing: https://gist.github.com/vsivsi/013097364a1fb6b092aab6549c7cc754

**Comment by vsivsi** [comment]
BTW, I have replicated this on a completely clean MacOS machine.  Starting from installing command line dev tools, homebrew, golang, building dlv / master from source, and then debugging a hello world program. So it does not appear to be something strange about the configuration of my dev box.

**Comment by vsivsi** [comment]
Also, running `go test` in the `service/test` directory on my dev box produces this failure:

```
--- FAIL: TestClientServer_FpRegisters (0.43s)
    support.go:252: enabling recording for github.com/go-delve/delve/service/test_test.TestClientServer_FpRegisters
    integration2_test.go:1538: state after continue: &api.DebuggerState{Running:false, Recording:false, CoreDumping:false, CurrentThread:(*api.Thread)(0xc00870da40), SelectedGoroutine:(*api.Goroutine)(0xc0096d4280), Threads:[]*api.Thread{(*api.Thread)(0xc00870dab0), (*api.Thread)(0xc00870db20), (*api.Thread)(0xc00870db90), (*api.Thread)(0xc00870dc00), (*api.Thread)(0xc00870dc70)}, NextInProgress:false, Exited:false, ExitStatus:0, When:"", Err:error(nil)}
    integration2_test.go:1547: avx2 variable: &api.Variable{Name:"avx2", Addr:0xc000112f36, OnlyAddr:false, Type:"bool", RealType:"bool", Flags:0x0, Kind:0x1, Value:"true", Len:0, Cap:0, Children:[]api.Variable{}, Base:0x0, Unreadable:"", LocationExpr:"[block] DW_OP_fbreg -0x52 ", DeclLine:22}
    integration2_test.go:1547: avx512 variable: &api.Variable{Name:"avx512", Addr:0xc000112f35, OnlyAddr:false, Type:"bool", RealType:"bool", Flags:0x0, Kind:0x1, Value:"true", Len:0, Cap:0, Children:[]api.Variable{}, Base:0x0, Unreadable:"", LocationExpr:"[block] DW_OP_fbreg -0x53 ", DeclLine:23}
    integration2_test.go:1586: register XMM0 not found:    Rip = 0x000000000107390a
           Rsp = 0x000000c000112ef8
           Rax = 0x0000000000000001
           Rbx = 0x00000000d39ff7eb
           Rcx = 0x000000c000000480
           Rdx = 0x00000000bc000400
           Rsi = 0x0000000000000001
           Rdi = 0x00000000010f4a40
           Rbp = 0x000000c000112f78
            R8 = 0x0000000000000002
            R9 = 0x0000000000000008
           R10 = 0x00000000010940f8
           R11 = 0x000000c000192020
           R12 = 0x0000000000000001
           R13 = 0x0000000000000001
           R14 = 0x0000000000000003
           R15 = 0xffffffffffffffff
         ST(0) = 0x3fffe666660000000000	1.7999999523162842
         ST(1) = 0x3fffd9999a0000000000	1.7000000476837158
         ST(2) = 0x3fffcccccd0000000000	1.600000023841858
         ST(3) = 0x3fffc000000000000000	1.5
         ST(4) = 0x3fffb333333333333000	1.4
         ST(5) = 0x3fffa666666666666800	1.3
         ST(6) = 0x3fff9999999999999800	1.2
         ST(7) = 0x3fff8cccccccccccd000	1.1
        Rflags = 0x0000000000000216	[PF AF IF IOPL=0]
            Cs = 0x000000000000002b
            Fs = 0x0000000000000000
            Gs = 0x0000000000000000
         MXCSR = 0x00001fa0	[RZ/RN=0 PM UM OM ZM DM IM PE]
```

**Comment by vsivsi** [comment]
More information that may be helpful. When stepping through the above test, the `debugserver` that is being run is:

```
% /Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver --version
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1103.0.22
 for x86_64.
```

**Comment by vsivsi** [comment]
One problem appears to be this code in the function `Slice`:  https://github.com/go-delve/delve/blob/master/pkg/proc/gdbserial/gdbserver.go#L1878-L1929

There is no `case reginfo.Bitsize == 512 {...}`

All of my testing has been on newer Intel Macs with AVX-512. So the registers being reported in the thread state are zmm0-zmm31, which are 512 bits wide. These registers are completely dropped by this code, which means that the AVX ymm and SSE xmm register state (which is a subset of the ZMM0-ZMM15) is also lost, because this slice function is discarding all vector registers.

**Comment by vsivsi** [comment]
Another issue is that the file https://github.com/go-delve/delve/blob/master/pkg/dwarf/regnum/amd64.go
is out of date with respect to the latest versions of the AMD64 Arch Processor Supplement, which cover AVX-512, defining DWARF register numbers for vector regs xmm16-xmm31 and mask registers k0-k7. A relatively recent copy of the spec can be found here:  https://raw.githubusercontent.com/wiki/hjl-tools/x86-psABI/x86-64-psABI-1.0.pdf

**Comment by vsivsi** [comment]
@aarzilli  @derekparker   This is brilliant new functionality, thanks so much for working through the AVX512 issues with me!

**Comment by vsivsi** [comment]
Although, this issue is not yet fixed on master because of the regression I point out here: 

https://github.com/go-delve/delve/pull/2498#issuecomment-849089321
