### ISSUE TITLE
support breakpoints with hit count conditions

### ISSUE THREAD

**Issue by suzmue** [go-delve/delve#2481]
This is a feature request for Hit Condition support.

Similar to conditional breakpoints, users may want to set a breakpoint based on how many times that breakpoint has been hit.

Here is the VS Code UI for setting a hit condition:
![Screen Shot 2021-05-14 at 3 24 05 PM](https://user-images.githubusercontent.com/6634754/118319207-71c31000-b4c8-11eb-8d22-8cb03c763a81.png)

Possible HitConditions to support would be:
- `== expr`
- `>= expr`
- `<= expr`
- `% expr`

This is part of the DAP spec, and could be implemented on the DAP side but I think would be better if this could be supported / implemented where the breakpoint conditions are checked. Hit Conditions would probably need to be binary expressions where the TotalHitCount can be substituted in for `expr.X`

**Comment by derekparker** [comment]
@suzmue is there anything more to do here with https://github.com/go-delve/delve/pull/2490 merged or can I close this out?

**Comment by suzmue** [comment]
This can be closed! @aarzilli  added support for hit count conditions in the terminal package with #2518
