### ISSUE TITLE
Cannot inspect contents of field using hover

### ISSUE THREAD

**Issue by RobGraham** [go-delve/delve#2491]
Please answer the following before submitting your issue:

1. What version of Delve are you using (`dlv version`)?  **1.6.0**
2. What version of Go are you using? (`go version`)?   **1.15.5**
3. What operating system and processor architecture are you using? **MacOS Catalina, 64bit**
4. What did you do? **Hover over a field of a struct. i.e. attempt to inspect the contents of field `b` when code is `a.b`**
5. What did you expect to see?  **The value of `b`**
6. What did you see instead? **nothing**

This behavior has been something I've lived with for years and never found an answer online nor did colleagues know how to get it to work. I don't want to have to use the debug side panel or hover over `a` and expand the contents to then find the field's value. I expect to be able to hover over any field regardless of depth to see it's contents. 

Apparently Goland offers this feature but I don't want to move away from VS Code

**Comment by aarzilli** [comment]
cc @hyangah @polinasok @suzmue

**Comment by suzmue** [comment]
Thanks for the report! We can support this feature by setting `supportsEvaluateOnHover`.

We will need to make sure that the error reporting does not end up annoying the user when we get evaluate requests as users are hovering over their code (need to set showUser=false)

**Comment by RobGraham** [comment]
Thanks for the reply but how do i do this in VS Code? I'm using the following delve settings but it's not working. 

`{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "port": 3001,
            "host": "127.0.0.1",
            "program": "${workspaceRoot}/cmd/main.go",
            "showLog": true,
            "dlvLoadConfig": {
                "followPointers": true,
                "maxStringLen": 500,
                // will slow down debugging but provides deeper inspection of iterative types
                // "maxVariableRecurse": 3,
                "maxArrayValues": 128,
                "maxStructFields": -1,
                "supportsEvaluateOnHover": true,
            }
        }
    ]
}
`

**Comment by suzmue** [comment]
@RobGraham this is not yet available.

I filed an issue to track this in the vscode-go repo as well: golang/vscode-go#1510

**Comment by suzmue** [comment]
@RobGraham what version of vscode are you using (`$ code -v`)? Could you also share an example of this failing?

It looks to me like VS Code has support for some of this already built in, even if we don't supply the evaluation.

**Comment by RobGraham** [comment]
Thanks, Suzy. Right now i'm running version 1.56.2 of VS Code. 
VS has support for hovering over the root struct which requires the user to then expand it's contents to find the field they wish to view. Similar to the debug side panel. 
![evaluation](https://user-images.githubusercontent.com/1311204/118731882-2ec9ab00-b7ee-11eb-9342-4429df54cfa7.png)

But there's no evaluation of the field itself
![no-evaluation](https://user-images.githubusercontent.com/1311204/118731869-28d3ca00-b7ee-11eb-93f5-0a65faf5bd4e.png)

**Comment by suzmue** [comment]
Thanks for sharing the example!

VS Code has limited support that does not work with the way we display pointers (@polinasok).

```
type hello struct {
    s string
}
x := hello{"hello"}
x.s // hover on x.s works
y := &hello{"hello"}
y.s // hover on y.s does not work
```

**Comment by hyangah** [comment]
@suzmue Is it after https://github.com/go-delve/delve/pull/2496 or before?

**Comment by suzmue** [comment]
> @suzmue Is it after #2496 or before?

Before. #2496 uses our evaluate implementation so it can handle the pointer case as well.

**Comment by RobGraham** [comment]
Does that mean the limitation is with vs code?

**Comment by suzmue** [comment]
#2496 was just merged and should fix the issue in the delve debug adapter implementation (`dlv dap`).

This implementation is not the default in VS Code yet. To use `dlv dap` in VS Code, you can set `"debugAdapter": "dlv-dap"` in your launch configurations. Hope this works for you!

**Comment by RobGraham** [comment]
Thanks for working so fast to provide a solution! Unfortunately i'm getting `connect ECONNREFUSED 127.0.0.1:3001`  no matter which port i try to use. Ideas?

**Comment by suzmue** [comment]
If you drop `port` and `host`, the extension should take care of launching the debug adapter for you.

**Comment by RobGraham** [comment]
:'( It works!!! I'm crying with joy right now...

So am I to be using dlv-dap from now on? Is this the future state of dlv,
like a dev version? Just trying to understand when I should use one or the
other.

**Comment by aarzilli** [comment]
I believe it will eventually become the default.
