### ISSUE TITLE
Fails to open file in debug mode but works fine when not in debug mode

### ISSUE THREAD

**Issue by DenisKnez** [go-delve/delve#2497]
dlv version: 1.6.0
go version 1.16.4
os/arch: linux/amd64

I have a problem when debugging the project the file is not found BUT  when running the program without the debugger the program works great and the file is found.

It gets to this function from the os package and it returns err and nil file, but when running normally it gets the file and not nil
![19 05 2021_10 44 45_REC](https://user-images.githubusercontent.com/43232648/118783602-81a76f00-b88f-11eb-9cad-38476934dada.png)

The path variable that you see in the image is **./the_name_of_the_file.json** because the file is in the root of the project
Also tried to provide the full path to the folder and the same thing happens

These are the only warnings (there is alot of warnings but their all the same just the different addresses), and I've looked up those warnings and they say it's nothing that would cause this to fail.

**btw, it does not kill the process or anything like that the process stopped because it passed all the breakpoints and finished**

![19 05 2021_10 52 50_REC](https://user-images.githubusercontent.com/43232648/118784596-7143c400-b890-11eb-8661-c20d30c4c860.png)

I've expected that it works the same as it does when it is not debugging...

**Comment by aarzilli** [comment]
I think you are just executing your program inside a different working directory.

**Comment by DenisKnez** [comment]
Yea that was the problem, I was starting the debugger while in the root directory of the program but the main.go is not in the root of the project so I had to start the debugger from that directory. @aarzilli Thanks for the help and quick response
