### ISSUE TITLE
Goland2021.1.1 not work

### ISSUE THREAD

**Issue by DiskGetor** [go-delve/delve#2500]
![Screenshot_20210520_132008_com realvnc viewer android](https://user-images.githubusercontent.com/19886504/118923549-462fa200-b96e-11eb-9b7b-a1b203537850.jpg)

Go1.16.4
Goland2021.1.1
Manjaro xfce on termux

**Comment by aarzilli** [comment]
I'm not sure what we're supposed to see here.

**Comment by s0xzwasd** [comment]
Could you please try to download GoLand Nightly via [Toolbox App](https://www.jetbrains.com/toolbox-app/) and try to debug your application again?

It'd be great if you could fill out a new ticket on GoLand bug-tracker: https://youtrack.jetbrains.com/issues/GO.

Thank you.

**Comment by DiskGetor** [comment]
> Could you please try to download GoLand Nightly via [Toolbox App](https://www.jetbrains.com/toolbox-app/) and try to debug your application again?
> 
> It'd be great if you could fill out a new ticket on GoLand bug-tracker: https://youtrack.jetbrains.com/issues/GO.
> 
> Thank you.

![Screenshot_20210521_080908_com realvnc viewer android](https://user-images.githubusercontent.com/19886504/119063534-ef78a580-ba0b-11eb-8f9f-f32bf70075db.jpg)

I am very sorry  i can not run box

**Comment by s0xzwasd** [comment]
Please, run the script via CLI: _./jetbrains-toolbox_

**Comment by DiskGetor** [comment]
> Please, run the script via CLI: _./jetbrains-toolbox_

![Uploading Screenshot_20210521_201734_com.realvnc.viewer.android.jpg…]()

**Comment by DiskGetor** [comment]
> Please, run the script via CLI: _./jetbrains-toolbox_

You can replay  this bug :
install termux on you Android mobile phone, then install manjaro Linux,go and goland,then write a hello world and debug it,  the bug will view.

Use this script for install manjaro:

[[ $(command -v curl) ]] || sudo pacman -Syu curl
    bash -c "$(curl -L https://gitee.com/mo2/linux/raw/2/2)"

**Comment by s0xzwasd** [comment]
Are you using a mobile device with amd or arm architecture? If you're using arm64 architecture, then you need to compile Delve manually and specify the path to it in GoLand (https://youtrack.jetbrains.com/issue/GO-10971#focus=Comments-27-4852093.0-0) because we provide GoLand with amd64 Delve binary on Linux distributions.

**Comment by DiskGetor** [comment]
> Are you using a mobile device with amd or arm architecture? If you're using arm64 architecture, then you need to compile Delve manually and specify the path to it in GoLand (https://youtrack.jetbrains.com/issue/GO-10971#focus=Comments-27-4852093.0-0) because we provide GoLand with amd64 Delve binary on Linux distributions.

Sure,i was rebuild  delve

**Comment by s0xzwasd** [comment]
Please, create a new ticket on our tracker (https://youtrack.jetbrains.com/issues/GO) and attach IDE logs via _Help | Collect Logs and Diagnostic Data_ action. Thank you.

**Comment by aarzilli** [comment]
I still don't understand what's going on here. Should this be closed? Should it stay open?

**Comment by s0xzwasd** [comment]
@aarzilli I think we can investigate from our side and if there is something with Delve, we can reopen the issue.
