### ISSUE TITLE
Goland debug hang when set env and program arguments

### ISSUE THREAD

**Issue by travelliu** [go-delve/delve#2509]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?

```
WARN[0000] CGO_CFLAGS already set, Cgo code could be optimized.  layer=dlv
Delve Debugger
Version: 1.6.0
Build: c5d58f494a266d9f95bf597bce894bd8d9204a65
```

2. What version of Go are you using? (`go version`)?

```
go version go1.16.3 darwin/amd64

```
3. What operating system and processor architecture are you using?

mac os 11.3.1 

4. What did you do?

start debug  hang when set env or program arguments 
![image](https://user-images.githubusercontent.com/7792329/119675776-eb1b1500-be6f-11eb-9373-2e39efb5ef4a.png)

![image](https://user-images.githubusercontent.com/7792329/119675927-05ed8980-be70-11eb-843d-98df6ec00e4d.png)

start debug normail when not set env or program arguments  

![image](https://user-images.githubusercontent.com/7792329/119676156-3af9dc00-be70-11eb-8d56-df40969eac49.png)

WARN[0000] CGO_CFLAGS already set, Cgo code could be optimized.  layer=dlv

is because use db2 database driver [go_ibm_db](github.com/ibmdb/go_ibm_db)

![image](https://user-images.githubusercontent.com/7792329/119676627-92984780-be70-11eb-9548-82ff37974006.png)

**Comment by s0xzwasd** [comment]
Hello,

Could you please fill out a new ticket on our tracker https://youtrack.jetbrains.com/issues/GO with a minimal reproducible example? We'll take a look.

Thank you.

**Comment by travelliu** [comment]
I am not sure that it can be reproduced. Let me try

**Comment by travelliu** [comment]
https://youtrack.jetbrains.com/issue/GO-11150 @s0xzwasd

**Comment by aarzilli** [comment]
Closing, GoLand issue (probably)
