### ISSUE TITLE
Support inputrc

### ISSUE THREAD

**Issue by loyalpartner** [go-delve/delve#2515]
hi, thanks for your job, i really like this debug tool!

here i have a question, i'm a bash shell user,
 i can use above config(~/.inputrc) bind key `C-n` to `step` command , this skill i really like it.

``` bash
# keybind for python or python3
$if gdb
"\C-n": "step\C-m"
"\C-c": "continue\C-m"
"\C-r": "run\C-m"
$endif
```
when i try dlv, i try to bellow config, but it hasno effect, could you tell me how to do it?

```bash
# keybind for python or python3
$if dlv
"\C-n": "step\C-m"
"\C-c": "continue\C-m"
"\C-r": "run\C-m"
$endif
```

**Comment by aarzilli** [comment]
AFAIK the line editor we use does not support inputrc https://github.com/peterh/liner/issues/120

**Comment by loyalpartner** [comment]
i got it, thanks for you reply!
