### ISSUE TITLE
“dlv” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by Digital-Nomad** [go-delve/delve#2520]
1. What version of Delve are you using (`dlv version`)?
 using 1.6.1 from forked branch for mac m1:
https://github.com/rfay/delve/releases/tag/v1.6.1-alpha1

2. What version of Go are you using? (`go version`)?
 1.6.3 for arm64

3. What operating system and processor architecture are you using?
MacOS 11.2

4. What did you do?
trying to debug

5. What did you expect to see?
Debug

 debug menu

7.  What did you see instead?
 https://imgur.com/SKuhNIp

**Comment by aarzilli** [comment]
We do not make binary releases and we are not responsible for what github.com/rfay/delve is distributing. Whether you choose to trust a random binary off the internet is up to you, as is figuring out how to tell your computer that you are in charge.
