### ISSUE TITLE
Problem about Go version support

### ISSUE THREAD

**Issue by Ace-Tang** [go-delve/delve#2528]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

What version of Delve are you using (`dlv version`)?
![image](https://user-images.githubusercontent.com/10334997/121004651-86da4880-c7c1-11eb-855e-97c60284b6bf.png)

What version of Go are you using? (`go version`)?
dlv command not show go version

What operating system and processor architecture are you using?
centos

What did you do?

When I use dlv to debug golang software, I find that next command stuck in debug, for example, I use [pouch](https://github.com/alibaba/pouch) to test, pouchd build with golang 1.12.9, and dlv I used a old version, not record version, and dlv self not keep version(or I not found). The debug step

1. set a breakpoint
 
![image](https://user-images.githubusercontent.com/10334997/121005279-3dd6c400-c7c2-11eb-9e6f-fb33d67aafbb.png)

2. enter next to debug

![image](https://user-images.githubusercontent.com/10334997/121007020-28629980-c7c4-11eb-9746-e9e91f7f176f.png)

sometimes the next command hang, use ctrl + c to stop, and sometimes not

If use dlv build by same golang version to debug pouchd, the problem not occur, I want to know it is related to golang source change that dlv only support some version of golang ?

I see dlv write the golang version to support in code
![image](https://user-images.githubusercontent.com/10334997/121007825-d66e4380-c7c4-11eb-8eb7-b1d973e0d277.png)

but I also see --check-go-version the flag is default be true, I wonder why it not told user the golang version to support ?

/cc @fuweid

**Comment by aarzilli** [comment]
Not sure what you are asking here. The version check was added in version 1.3.0 of Delve, prior to that version we would not make any check.

**Comment by aarzilli** [comment]
Closing, no feedback.
