### ISSUE TITLE
Version of Go is too old for this version of Delve (minimum supported version 1.14, suppress this error with --check-go-version=false)

### ISSUE THREAD

**Issue by Ganesh-Ponipireddy** [go-delve/delve#2531]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)? 1.6.1
2. What version of Go are you using? (`go version`)? 1.13.15
3. What operating system and processor architecture are you using? Mac OS
4. What did you do? I had installed the dlv
5. What did you expect to see? I expect my code running.
6. What did you see instead?
version of Go is too old for this version of Delve (minimum supported version 1.14, suppress this error with --check-go-version=false)
Process exiting with code: 1

**Comment by icholy** [comment]
@Ganesh-Ponipireddy is the error message unclear?

**Comment by Ganesh-Ponipireddy** [comment]
@icholy Error msg is clear. But how to set that flag to false. 

I had tried below cmd using help but no luck for me. 
dlv exec ./<excutable_application> --check-go-version false

**Comment by icholy** [comment]
@Ganesh-Ponipireddy flags go before positional arguments:

```
dlv exec --check-go-version=false ./bin
```

**Comment by Ganesh-Ponipireddy** [comment]
@icholy 
when I had given the cmd as you suggested it is going into the help mode. please find the screenshot for ref.
![image](https://user-images.githubusercontent.com/48117290/121516500-e6c42f80-ca0b-11eb-80c5-519ffe074beb.png)

**Comment by derekparker** [comment]
@Ganesh-Ponipireddy the debugger is starting up successfully in your last example. It always shows that message on startup, the problem is once you've entered the debug session you're trying to use a command that doesn't exist. Try typing 'help' to see what commands are available. From there you can see how to set breakpoints and continue your program.
