### ISSUE TITLE
Q: should the go version in go.mod be updated?

### ISSUE THREAD

**Issue by nd** [go-delve/delve#2532]
Delve uses `debug/elf` from standard library to parse DWARF. Go sdk prior to go1.14 doesn't support DWARF v5 produced by go1.16. Shouldn't the go version in go.mod be updated to make such problem more visible?

**Comment by aarzilli** [comment]
IMO no, for various reasons:
1. no version of go emits DWARFv5
2. if they did we should probably handle it with a check at runtime (by comparing the version delve was built with with the version of the target executable)
3. the version in go.mod doesn't specify the minimum supported version, it just changes the behavior of cmd/go and the compiler in strange ways.

**Comment by nd** [comment]
I've got an error saying DWARFv5 is not supported trying to read this file https://drive.google.com/file/d/1Ois7BPge3Omnefh0m79n-yi2TupHQT6K/view?usp=sharing. It was produced by go1.16.4 from:

```
package main

/*
	#include <stdlib.h>
	char* cstring = "C string example";
*/
import "C"
import (
	"fmt"
	"unsafe"
)

func main() {

	var gstring string = "Go string example"

	//Go to C String, Output: *C.char
	cs := C.CString(gstring)
	defer C.free(unsafe.Pointer(cs))
	fmt.Println(cs)

	//C to Go String, Output: string
	gs := C.GoString(C.cstring)
	fmt.Println(gs)

	//C string, length to Go string
	gs2 := C.GoStringN(C.cstring, (C.int)(len(gs)))
	fmt.Println(gs2)

}
```

I guess DWARFv5 comes from C.

**Comment by nd** [comment]
The error was `could not launch process: could not open debug info`. Delve was built using go1.12.6 on revision 7a3faca71f7e01a97833e11ebf0683543e8159cb. Debug works fine in delve built with go1.16.4 .

**Comment by nd** [comment]
I guess the question is answered, updating go version is not a proper solution.
