### ISSUE TITLE
time.Sleep is identified as a 'User' location instead of a 'Runtime' location

### ISSUE THREAD

**Issue by BarrensZeppelin** [go-delve/delve#2542]
`dlv` version: `1.6.1`
`go` version: `1.16.2`
`OS/Arch`: Ubuntu on X86_64

I have the following program that reproduces the bug:

```go
package main

import "time"

func main() {
	go func() {
		time.Sleep(2 * time.Second)
	}()
	time.Sleep(1 * time.Second)
	println("ASD")
}
```

I start the debugger and set a breakpoint at the println-statement.
When the breakpoint is hit the anonymous goroutine will be in the `time.Sleep` function.

```
$ dlv debug main.go
Type 'help' for list of commands.
(dlv) b main.go:10
Breakpoint 1 (enabled) set at 0x46f365 for main.main() ./main.go:10
(dlv) c
> main.main() ./main.go:10 (hits goroutine(1):1 total:1) (PC: 0x46f365)
     5:	func main() {
     6:		go func() {
     7:			time.Sleep(2 * time.Second)
     8:		}()
     9:		time.Sleep(1 * time.Second)
=>  10:		println("ASD")
    11:	}
(dlv) grs
* Goroutine 1 - User: ./main.go:10 main.main (0x46f365) (thread 7933)
  Goroutine 2 - User: /usr/lib/go-1.16/src/runtime/proc.go:337 runtime.gopark (0x437695) [force gc (idle)]
  Goroutine 3 - User: /usr/lib/go-1.16/src/runtime/proc.go:337 runtime.gopark (0x437695) [GC sweep wait]
  Goroutine 4 - User: /usr/lib/go-1.16/src/runtime/proc.go:337 runtime.gopark (0x437695) [GC scavenge wait]
  Goroutine 5 - User: /usr/lib/go-1.16/src/runtime/time.go:193 time.Sleep (0x463d12) [sleep]
[5 goroutines]
(dlv) gr 5
Switched from 1 to 5 (thread 7933)
(dlv) gr
Thread 7933 at ./main.go:10
Goroutine 5:
	Runtime: /usr/lib/go-1.16/src/runtime/proc.go:337 runtime.gopark (0x437695)
	User: /usr/lib/go-1.16/src/runtime/time.go:193 time.Sleep (0x463d12)
	Go: ./main.go:6 main.main (0x46f355)
	Start: ./main.go:6 main.main.func1 (0x46f3a0)
(dlv) bt
0  0x0000000000437695 in runtime.gopark
   at /usr/lib/go-1.16/src/runtime/proc.go:337
1  0x0000000000463d12 in time.Sleep
   at /usr/lib/go-1.16/src/runtime/time.go:193
2  0x000000000046f3ca in main.main.func1
   at ./main.go:7
3  0x0000000000466aa1 in runtime.goexit
   at /usr/lib/go-1.16/src/runtime/asm_amd64.s:1371
```

The anonymous goroutine has ID 5 here. I would expect its 'User' location to be identified as the function in stack frame 2 (`main.main.func1`), and not the `time.Sleep` function in the runtime library.

**Comment by aarzilli** [comment]
"User current" means "not a runtime private function" and was added mainly because otherwise almost every goroutine will be reported in runtime.gopark. It could have meant other things ("not in standard library", "not outside of the main module", etc...), but it doesn't and changing it could potentially create backwards compatibility problems. Those who wish to use different definitions can do so in a user script.

**Comment by BarrensZeppelin** [comment]
That's fail.

By "user script" do you mean that a different definition is achievable with a lightweight script (extension)?
Or do you mean a program that interfaces with delve in headless mode to parse backtraces?
