### ISSUE TITLE
Why does the file generated by breakpoint rage jump to the *. RL file instead of the generated *. Go file

### ISSUE THREAD

**Issue by jinsuojinsuo** [go-delve/delve#2545]
Why does the file generated by breakpoint rage jump to the *. RL file instead of the generated *. Go file

**Comment by aarzilli** [comment]
What's a RL file? Whats a breakpoint rage jump?

**Comment by jinsuojinsuo** [comment]
Go file generated by Regal

**Comment by aarzilli** [comment]
And what's Regal? In any case, you have to ask whoever maintains it. Presumably they don't generate the appropriate line directives.
