### ISSUE TITLE
dap: inconsistencies with how signals are forwarded to process

### ISSUE THREAD

**Issue by polinasok** [go-delve/delve#2552]
The original plan was to have dlv-dap server behave as would a headless dlv-rpc server. Thus, `service.Config.Foreground` was always set to true. This got changed when `tty` flag was introduced: https://github.com/go-delve/delve/commit/3e60ae202b7d7c67fe7ea5fffafc92c7e39e4b67#r47528045. And while `tty` is not a global flag and doesn't show up in dlv-dap mode, the change also made the code depend on the value of `--headless`. As a result the foreground behavior changes if `--headless` is changed, even though code prints a warning that this flag is ignored because dap mode is always headless. I thought this was merely cosmetic and never got around to correcting this. But now I am realizing that started relying on SIGINT not being forwarded as part of clean shutdown (see #2445). Perhaps it is worth adding an explicit flag to forward or not forward the signals? Some users do need to forward the signals while others appreciate the simplicity of killing the server with Ctrl-C.

```
package main

import (
	"fmt"
	"os"
	"os/signal"
	"syscall"
)

func main() {

	sigs := make(chan os.Signal, 1)
	done := make(chan bool, 1)

	signal.Notify(sigs, syscall.SIGINT)

	go func() {
		sig := <-sigs
		fmt.Println()
		fmt.Println(sig)
		done <- true
	}()

	fmt.Println("awaiting signal")
	<-done
	fmt.Println("got signal: exiting...")
}
```

```
$ go run sigint.go
awaiting signal
^C
interrupt
got signal: exiting...

$ dlv debug sigint.go ############# Does not forward signals
Type 'help' for list of commands.
(dlv) c
awaiting signal
received SIGINT, stopping process (will not forward signal)
Stopped at: 0x7fff20323cde
=>   1:	no source available
(dlv) exit

$ dlv debug sigint.go --headless ############# Forwards signals
API server listening at: 127.0.0.1:58781
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1205.0.27
 for x86_64.
Got a connection, launched process /Users/polina/delve/__debug_bin (pid = 81180).
awaiting signal
^C
interrupt
got signal: exiting...

$ ./dlv dap --listen=:54321 ############ Foreground=false
DAP server listening at: [::]:54321
awaiting signal
^C

$ ./dlv dap --listen=:54321 --headless=false ########### Foreground=false
DAP server listening at: [::]:54321
awaiting signal
^C

$ ./dlv dap --listen=:54321 --headless=true ########### Foreground=true
Warning: dap mode is always headless
DAP server listening at: [::]:54321
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1205.0.27
 for x86_64.
Got a connection, launched process /Users/polina/delve/__debug_bin (pid = 81498).
awaiting signal
^C
interrupt
got signal: exiting...
2021-06-25T00:04:03-07:00 error layer=dap runtime error: EOF
2021-06-25T00:04:34-07:00 error layer=dap write tcp 127.0.0.1:58887->127.0.0.1:58888: write: broken pipe

**Comment by aarzilli** [comment]
Why not set `headless = true` in `dapCmd`, after printing the warning?

**Comment by polinasok** [comment]
That's essentially what the code used to do. And I was going to just fix it to go back to always using true. But then I realized that we started relying on `headless` being false and being able to SIGINT the server and get the process and the binary cleaned up. So how do we get the best of both worlds? Offer forwarding flag? Support clean shutdown with SIGTERM?

**Comment by aarzilli** [comment]
Doesn't disconnecting shut down the server and clean up the executable? Killing the server with a signal shouldn't be needed.

**Comment by polinasok** [comment]
It does if everything goes as planned. This was a solution for when we are forced to kill, which should be rare.

**Comment by hyangah** [comment]
Even when we force to kill, if the debugee dies, the server should die too, shouldn't it?
I still want to understand the use case before adding an extra flag - if there was an option to place debugee to foreground, I think vscode-go will use that option always to forward the signals to the process to be debuged.

**Comment by polinasok** [comment]
> Even when we force to kill, if the debugee dies, the server should die too, shouldn't it?

I am not sure what you are asking here.

> I still want to understand the use case before adding an extra flag - if there was an option to place debugee to foreground, I think vscode-go will use that option always to forward the signals to the process to be debugged.

Due to an accidental change when the tty flag was introduced, dlv-dap currently does NOT foreground the process by default. Vscode-go relies on Foreground being false to be able to use SIGINT to shut things down gracefully. False also allows one to use Ctrl-C to kill dlv-dap server that was launched manually. We can either fix Foreground to be true always (like any headless server) or control this setting by a flag for a middle ground.

If you start a launch session with dlv-dap from vscode-go and not command-line, how do you enter stdin or signal to the process without supporting external console?

Whether or not we add the flag,  I also want to make sure there is another mechanism to kill the server cleanly. We don't want temp binary around when things are forced to shut down.

**Comment by hyangah** [comment]
>>Even when we force to kill, if the debugee dies, the server should die too, shouldn't it?
> I am not sure what you are asking here.

You said "This was a solution for when we are forced to kill, which should be rare". What I meant is even when we(?) are forced to kill, the debugee should be killed first, and when the debugee dies, the debug session will end. Currently the dlv dap dies if the session ends, so I don't see why we need signal to kill the server.

> Due to an accidental change when the tty flag was introduced, dlv-dap currently does NOT foreground the process by default.

Yes, I think that's a bug in dlv-dap and I hoped this to be fixed and to be consistent with the delve's headless mode, and delve in headless mode (including dlv dap) should always place the debugee to foreground. I want to understand why we need additional flag. Is it a prep to make `dlv dap` work as a long running server to serve multiple attach/launch requests?

**Comment by polinasok** [comment]
> > > Even when we force to kill, if the debugee dies, the server should die too, shouldn't it?
> > > I am not sure what you are asking here.
> 
> You said "This was a solution for when we are forced to kill, which should be rare". What I meant is even when we(?) are forced to kill, the debugee should be killed first, and when the debugee dies, the debug session will end. Currently the dlv dap dies if the session ends, so I don't see why we need signal to kill the server.

There was issue #2445 where things did not work out this way. The server shutdown, but the program that it launched stayed.

> > Due to an accidental change when the tty flag was introduced, dlv-dap currently does NOT foreground the process by default.
> 
> Yes, I think that's a bug in dlv-dap and I hoped this to be fixed and to be consistent with the delve's headless mode, and delve in headless mode (including dlv dap) should always place the debugee to foreground. I want to understand why we need additional flag. Is it a prep to make `dlv dap` work as a long running server to serve multiple attach/launch requests?

I know dlv-rpc-headless always uses foreground. And personally I wish that there was a flag to control that. Not every debug session needs to handle stdin or signals. And it can be very convenient to use Ctrl-C to take down the server instead of dealing with pgrep, especially if you are in-between client sessions and don't have a quick way to request exit from a client. Since by mistake here we started relying on non-foreground mode, I thought it was a good way to start a dialogue about making this setting configurable with a flag. There is no requirement for dlv-dap to be exactly the same as dlv-rpc, even if we eventually hook up dlv-dap to the traditional commands. What is the reason against the flag other than consistency with dlv-rpc-headless?

**Comment by hyangah** [comment]
I don't think #2445 is a representative example - #2445 was reported long ago when `dlv dap` wasn't able to process stop requests 
while running. As a workaround for the unresponsive dlv dap server, the VS Code Go extension had to rely on SIGINT it sends after waiting for some time. I think that's a catastrophic case and shouldn't happen often. (If it happens often, that's a bug.) 

Now `dlv dap` can handle stop/disconnect/terminate(eventually) even while the program is running. So I expect the dlv dap server can trigger the right, normal teardown sequence as part of handling DAP instead of relying on the SIGINT signal.

I am not against adding the flag as long as there is need for configure the behavior.

For signal processing, if dlv is going to handle the signal first and forward to the debugee, I wish users could control how to handle signals https://sourceware.org/gdb/onlinedocs/gdb/Signals.html

**Comment by polinasok** [comment]
> If dlv is going to handle the signal first and forward to the debugee, I wish users could control how to handle signals https://sourceware.org/gdb/onlinedocs/gdb/Signals.html
> 
> EDIT: Re: #2445 - the extension sends the signal directly to the delve dap process, so the foregroundness of the target shouldn't change the cleanup process.

This has been clarified in #2580. Delve doesn't handle the signal first when the foregrounded process gets it from the terminal. And yes, sending a direct signal from extension should work in any case. So that's good news.

This flag if added would only be impacting the command-line experience. It should not impact integration with dlv-rpc. These commands would be handled by different functions in commands.go. I don't feel strongly about it. If everybody is against it, I can just fix this issue without the flag. I was just somehow under the impression that the flag was an option we discussed last time we had a VC with @derekparker and @aarzilli. Maybe my memory is playing tricks on me.

**Comment by aarzilli** [comment]
> If dlv is going to handle the signal first and forward to the debugee, I wish users could control how to handle signals https://sourceware.org/gdb/onlinedocs/gdb/Signals.html

That's a different thing still. Gdb doesn't forward signals sent to gdb to the target process either. What gdb does is it lets you control what happens to signals *sent to the target proces*.

> I was just somehow under the impression that the flag was an option we discussed last time we had a VC with @derekparker and @aarzilli. Maybe my memory is playing tricks on me.

I remember that we decided we would make it consistent with `dlv --headless` preferentially, but a flag was also a possibility if a reason existed to add it.

**Comment by polinasok** [comment]
With the flag-less fix in, this issue has been addressed. We can revisit the flag as needed outside of this issue. Closing.

**Comment by aarzilli** [comment]
For future reference I think I've tracked down where the problem is in debugserver. If debugserver launched the target process in its own process group we could work around the issue by simply pushing it ourselves to the foreground. Unfortunately it doesn't, the target process and debugserver are always in the same process group, meaning that, no matter what we do, a ^C press will send SIGINT to both. The culprit is in

lldb/tools/debugserver/source/MacOSX/MachProcess.mm

the function MachProcess::PosixSpawnChildForPTraceDebugging should add the flag POSIX_SPAWN_SETPGROUP to the flags variables, it does not. There actually is a launch mode that does put the child process in its own process group (the fork-exec mode) but we can't use it because it doesn't have a disable_aslr option. Adding that flag and then doing a tcsetpgrp (when appropriate) on delve's side would probably fix the issue.
