### ISSUE TITLE
runtime.Breakpoint isn't handled with --backend=rr

### ISSUE THREAD

**Issue by hyangah** [go-delve/delve#2555]
The breakpoint trap isn't handled which isn't consistent(?) with other mode dlv operations. 

```
 ~/go/bin/dlv debug --backend=rr testvariables.go
Type 'help' for list of commands.
rr: Saving execution to trace directory `/home/hakim/.local/share/rr/__debug_bin-1'.
SIGTRAP: trace trap
PC=0x46ec41 m=0 sigcode=128

goroutine 1 [running]:
runtime.breakpoint()
	/usr/lib/golang/src/runtime/asm_amd64.s:249 +0x1 fp=0xc0000478a8 sp=0xc0000478a0 pc=0x46ec41
runtime.Breakpoint()
	/usr/lib/golang/src/runtime/proc.go:4279 +0x25 fp=0xc0000478b8 sp=0xc0000478a8 pc=0x446665
main.foobar(0x4e0e36, 0x9, 0xa, 0x4e0683, 0x5)
	/home/hakim/delve/_fixtures/testvariables.go:65 +0xa25 fp=0xc000047f38 sp=0xc0000478b8 pc=0x4ba725
main.main()
	/home/hakim/delve/_fixtures/testvariables.go:73 +0x7c fp=0xc000047f88 sp=0xc000047f38 pc=0x4bb79c
runtime.main()
	/usr/lib/golang/src/runtime/proc.go:225 +0x223 fp=0xc000047fe0 sp=0xc000047f88 pc=0x43d3a3
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000047fe8 sp=0xc000047fe0 pc=0x470a61

rax    0xc0000641b0
...
```

rr: 5.4.0
dlv: built from master (v1.6.2-0.20210626071635-741129046849)
go version: 1.16.3

**Comment by aarzilli** [comment]
If I'm not mistaken that's just the output from the program being recorded, after that you should be able to debug the recorded program normally, until the point where it calls runtime.Breakpoint.

**Comment by hyangah** [comment]
Yes, I could be able to debug the recorded program. I think this is working as intended ? - 
A bit surprised that `dlv debug --backend=rr` started to run the program immediately.
In other modes, dlv cli doesn't start the program execution until the user requests to start.

**Comment by aarzilli** [comment]
It starts recording the program immediately but once it's done recording it will stop and go back to the start. The first time the program is executed it is not being debugged, just recorded, that's where the difference from other modes comes from.

**Comment by hyangah** [comment]
Ok. I will close this because this is Working As Intended.
