### ISSUE TITLE
No response to RPCServer.State request

### ISSUE THREAD

**Issue by nd** [go-delve/delve#2573]
1. What version of Delve are you using (`dlv version`)?

```
Delve Debugger
Version: 1.6.1
Build: 7a3faca71f7e01a97833e11ebf0683543e8159cb
```

2. What version of Go are you using? (`go version`)?

`1.14.4`

3. What operating system and processor architecture are you using?

`Mac OS X (10.15.7, x86_64)`

4. What did you do?

Debugged the program:

```
package main

import "fmt"

func main() {
	a := 1
	fmt.Println(a) // breakpoint
}
```

Delve was launched from IDE with the command:

`dlv --listen=0.0.0.0:57555 --headless=true --api-version=2 --check-go-version=false --only-same-user=false exec /path/to/executable --`

The executable was compiled with the `-gcflags "all=-N -l"` option.

5. What did you expect to see?

Debugger responds to IDE requests.

6. What did you see instead?

Debugger doesn't respond.

Judging by IDE logs it connected to delve successfully and sent the `{"method":"RPCServer.State","params":[{"NonBlocking":true}],"id":1}` request, but didn't get any response back.

If delve is launched with `--log --log-output lldbout,rpc`, it prints only

```
API server listening at: [::]:55744
2021-07-05T18:48:22+07:00 debug layer=rpc API server pid = 43752
```

in its own log. [Debugserver log](https://gist.github.com/nd/2361c8300dc73b2026ad4e0cb63b817c) doesn't seem to contain any errors.

Reportedly delve does work fine if launched as `dlv debug /path/to/main.go`.

**Comment by aarzilli** [comment]
There are a few obvious hypotheses:

1. it is possible that we have a problem parsing the executable file, a way to check this would be to manually give the `dlv exec /path/to/executable`. `dlv debug /path/to/main.go` could be debugging a different program, unless you are sure it isn't.
2. it is possible that we had problems starting or connecting to debugserver, how was debugserver.log obtained? Passing `gdbwire` to `--log-output` would help determining if this is the case.
3. if neither of the above is happening then the most likely explanation is a problem with the user's computer, such as a firewall preventing communication to delve (application level firewalls were fairly popular among macos users at some point).

**Comment by nd** [comment]
Gdbwire log: https://gist.github.com/nd/dce79f0cdafc670cb379c02e7243bb41. Seems like it doesn't contain any problems?

**Comment by aarzilli** [comment]
There's nothing wrong there, seems like the most likely explanation is that it is not a problem with delve.

**Comment by aarzilli** [comment]
Anything new with this?

**Comment by nd** [comment]
Sorry, forget to close it. It looks like something called VMware Carbon Black Endpoint was blocking the debugger.

**Comment by aarzilli** [comment]
> VMware Carbon Black Endpoint

Awesome name. Thank you.
