### ISSUE TITLE
dap variables response can be `null` but must be empty

### ISSUE THREAD

**Issue by mfussenegger** [go-delve/delve#2590]
Some users of nvim-dap reported that they get an error when using `dlv dap` as debug adapter.

You can find the full issue here: https://github.com/mfussenegger/nvim-dap/issues/225

We managed to figure out that they do get a `null` variables response, and that trips up some code in nvim-dap that doesn't expect a null value - because according to the debug adapter protocol specification, the `variables` result must not be `null`:

    debug layer=dap [-> to client]{"seq":0,"type":"response","request_seq":7,"success":true,"command":"variables","body":{"variables": null}}

The odd thing is that I wasn't able to reproduce it, and instead get a correct empty variables response:

    debug layer=dap [-> to client]{"seq":0,"type":"response","request_seq":7,"success":true,"command":"variables","body":{"variables":[]}}

I had a quick look at the code - including it's history - and didn't find anything suspicious:

> https://github.com/go-delve/delve/blob/5dd4b7df9da1770edb4c2fd86535b58b1df294e7/service/dap/server.go#L1566-L1570

But I'm also not too familiar with Go.

1. What version of Delve are you using (`dlv version`)?

```
Version: 1.6.1
Build: $Id: 114218c22f3791287c4bc2f4ff35a846a1416ee9 $
```

2. What version of Go are you using? (`go version`)?

Unfortunately I didn't ask the issue reporters in the original issue.

With the following version it works for me:

```
> go version
go version go1.16.5 linux/amd64
```

Unknown

3. What operating system and processor architecture are you using?

- Works on Linux/ x86_64
- Original issue reporters are on MacOS

4. What did you do?

Set a breakpoint in the following code in the `Println` Line. `nvim-dap` automatically retrieves the scopes and variables if a breakpoint is hit.

```go
package main

import "fmt"


func main() {
    words := "world"
    fmt.Println("hello" + words)
}
```

5. What did you expect to see?
6. What did you see instead?

- See description above

Maybe you have an idea what's going on - if not feel free to close, I will be merging a workaround - although I think it ought to be fixed in delve given that it is not compliant with the specification.

**Comment by hyangah** [comment]
Thanks for the report @mfussenegger 
Can you please ask the user to run the following command to see the real version of `dlv`?

```
$ go version -m /path/to/dlv
```

I could reproduce the issue with the delve built from the master, but not with the latest release (v1.6.1).
So, I suspect the dlv binary the user was using is newer than v1.6.1 (even though dlv version reports 1.6.1).

cc @suzmue @polinasok  https://github.com/go-delve/delve/blob/master/service/dap/server.go#L1719-L1740

**Comment by polinasok** [comment]
I am seeing the same - [] with mid-May 1.6.1 version and null with top of the tree. Will send out a fix shortly and see if we can get it into the release candidate that's about to be released.

**Comment by mfussenegger** [comment]
> Can you please ask the user to run the following command to see the real version of dlv?

Yes I did - this is the output:

```
$ which dlv
/Users/user/go/bin/dlv

$ go version -m /Users/user/go/bin/dlv
/Users/user/go/bin/dlv: go1.16.5
	path	github.com/go-delve/delve/cmd/dlv
	mod	github.com/go-delve/delve	(devel)
	dep	github.com/cosiner/argv	v0.1.0	h1:BVDiEL32lwHukgJKP87btEPenzrrHUjajs/8yzaqcXg=
	dep	github.com/cpuguy83/go-md2man	v1.0.10	h1:BSKMNlYxDvnunlTymqtgONjNnaRV1sTpcovwwjF22jk=
	dep	github.com/google/go-dap	v0.5.0	h1:RMHAVn5xeunBakYk65ggHXttk6qjZVdbmi+xhAoL2wY=
	dep	github.com/hashicorp/golang-lru	v0.5.4	h1:YDjusn29QI/Das2iO9M0BHnIbxPeyuCHsjMW+lJfyTc=
	dep	github.com/mattn/go-isatty	v0.0.3	h1:ns/ykhmWi7G9O+8a448SecJU3nSMBXJfqQkl0upE1jI=
	dep	github.com/peterh/liner	v0.0.0-20170317030525-88609521dc4b	h1:8uaXtUkxiy+T/zdLWuxa/PG4so0TPZDZfafFNNSaptE=
	dep	github.com/russross/blackfriday	v1.5.2	h1:HyvC0ARfnZBqnXwABFeSZHpKvJHJJfPz81GNueLj0oo=
	dep	github.com/sirupsen/logrus	v1.6.0	h1:UBcNElsrwanuuMsnGSlYmtmgbb23qDR5dG+6X6Oo89I=
	dep	github.com/spf13/cobra	v0.0.0-20170417170307-b6cb39589372	h1:eRfW1vRS4th8IX2iQeyqQ8cOUNOySvAYJ0IUvTXGoYA=
	dep	github.com/spf13/pflag	v0.0.0-20170417173400-9e4c21054fa1	h1:7bozMfSdo41n2NOc0GsVTTVUiA+Ncaj6pXNpm4UHKys=
	dep	go.starlark.net	v0.0.0-20200821142938-949cc6f4b097	h1:YiRMXXgG+Pg26t1fjq+iAjaauKWMC9cmGFrtOEuwDDg=
	dep	golang.org/x/arch	v0.0.0-20190927153633-4e8777c89be4	h1:QlVATYS7JBoZMVaf+cNjb90WD/beKVHnIxFKT4QaHVI=
	dep	golang.org/x/sys	v0.0.0-20200625212154-ddb9806d33ae	h1:Ih9Yo4hSPImZOpfGuA4bR/ORKTAbhZo2AbWNRCnevdo=
	dep	gopkg.in/yaml.v2	v2.2.1	h1:mUhvW9EsL+naU5Q3cakzfE91YhliOondGd6ZrsDBHQE=
```

**Comment by hyangah** [comment]
Thanks! It looks like the dlv was built by checkout out the delve repository and built from it instead of `go get` or `go install`. 

@derekparker @aarzilli https://github.com/go-delve/delve/blob/master/Documentation/installation/README.md#installation suggests `git clone + go install`, but IMO, with Go modules, it's better to suggest `go get` or `go install` (for 1.16+). What do you think?

**Comment by aarzilli** [comment]
> @derekparker @aarzilli https://github.com/go-delve/delve/blob/master/Documentation/installation/README.md#installation suggests `git clone + go install`, but IMO, with Go modules, it's better to suggest `go get` or `go install` (for 1.16+). What do you think?

`go install @latest` works on one version of go. `go get` does different things depending on the verison of go, environment variables and which directory it runs in. `git clone + go install` works consistently on every version of go.
