### ISSUE TITLE
Delve exists on attempt to evaluate long array

### ISSUE THREAD

**Issue by nd** [go-delve/delve#2603]
1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 1.6.1
Build: f0a32c8e1b6571c8c1cd4ed89dcb9c784481f422
```

2. What version of Go are you using? (`go version`)?
```
go version go1.17beta1 windows/amd64
```

3. What operating system and processor architecture are you using?
windows/amd64 

4. What did you do?

Evaluated dat at breakpoint in:
```
package main

import "io/ioutil"

func main() {
	dat, _ := ioutil.ReadFile("file")
	print(dat) //break
}
```

File is any file longer than ~250Kb.

Variable is evaluated fully with the request

```
2021-07-19T11:35:55+02:00 debug layer=rpc <- RPCServer.Eval(rpc2.EvalIn{"Scope":{"GoroutineID":1,"Frame":0,"DeferredCall":0},"Expr":"dat","Cfg":{"FollowPointers":true,"MaxVariableRecurse":1,"MaxStringLen":269957,"MaxArrayValues":269957,"MaxStructFields":-1}})
```

5. What did you expect to see?

Either full content or error describing why it cannot be evaluated

6. What did you see instead?

Delve exists with exit code 0. Before exiting it allocates ~500Mb of memory. From windows event log it seems like delve wasn't killed and existed by itself.

--

250K array is big and client should be smarter and use paging, but maybe delve can report an error instead of exiting. The issue is not specific to windows and can be observed on mac.

**Comment by derekparker** [comment]
I'm not able to reproduce this either on Linux or Windows with the settings I see in the request.

Can you reproduce with the terminal client or only headless with an IDE frontend?

**Comment by aarzilli** [comment]
Delve 1.6.1 is incompatible with go 1.17beta1, you should try with 1.7.0

**Comment by aarzilli** [comment]
On second thought this probably has nothing to do with the version of delve/go. You are asking for `"MaxArrayValues":269957` and given the overhead we have on the protocol for each array element it's likely that we do end up allocating a ton of memory.

**Comment by nd** [comment]
Cannot reproduce in terminal, looks like a client problem indeed.
