### ISSUE TITLE
can not run under Rosetta

### ISSUE THREAD

**Issue by yj20060714** [go-delve/delve#2610]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
 % dlv version
Delve Debugger
Version: 1.7.0
Build: $Id: e353a65161e6ed74952b96bbb62ebfc56090832b $

2. What version of Go are you using? (`go version`)?
% go version
go version go1.15.14 darwin/amd64

3. What operating system and processor architecture are you using?
 % uname -a
Darwin YANG-MB1 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101 arm64

4. What did you do?
% dlv debug main.go
could not launch process: can not run under Rosetta, check that the installed build of Go is right for your CPU architecture

5. What did you expect to see?
Type 'help' for list of commands.
(dlv) 

6. What did you see instead?
% dlv debug main.go
could not launch process: can not run under Rosetta, check that the installed build of Go is right for your CPU architecture

**Comment by aarzilli** [comment]
What would you say is hard to understand for you in that error message?

**Comment by yj20060714** [comment]
> What would you say is hard to understand for you in that error message?
I just wonder dlv is compatible with Mac M1?

**Comment by yj20060714** [comment]
> What would you say is hard to understand for you in that error message?

I just wonder dlv is compatible with Mac M1?

**Comment by yj20060714** [comment]
<img width="897" alt="image" src="https://user-images.githubusercontent.com/9796366/126607202-08e8b3f0-c0a7-4fcd-9d05-24b1f16fed6e.png">


> What would you say is hard to understand for you in that error message?

<img width="897" alt="image" src="https://user-images.githubusercontent.com/9796366/126607240-74d3d407-0b71-4f40-8625-daece5abbfe6.png">

**Comment by yj20060714** [comment]
> What would you say is hard to understand for you in that error message?

<img width="897" alt="image" src="https://user-images.githubusercontent.com/9796366/126607286-d7ade62f-7ce8-41bb-baf1-9d4aa69d1dae.png">

**Comment by aarzilli** [comment]
Delve is compatible with M1 but not with Rosetta.

**Comment by yj20060714** [comment]
> Delve is compatible with M1 but not with Rosetta.

Then what should I do ? can I use sth else to replace Rosetta?

**Comment by yj20060714** [comment]
> Delve is compatible with M1 but not with Rosetta.

I just git clone go source and execute make, then I git clone delve source and execute "go install github.com/go-delve/delve/cmd/dlv"。

Then I execute "dlv debug xx.go" to debug my code, report error : could not launch process: can not run under Rosetta, check that the installed build of Go is right for your CPU architecture

So I need help, how can I use delve with my mac(M1)?
 Thank you every much!

**Comment by yj20060714** [comment]
> Delve is compatible with M1 but not with Rosetta.
step1:
$ download https://golang.org/dl/go1.15.14.darwin-amd64.tar.gz
$ cd go/src && make.bash

step2:
$ git clone https://github.com/go-delve/delve
$ cd delve
$ go install github.com/go-delve/delve/cmd/dlv

step3:
$ cd my_app
$ dlv debug main.go

then report error : could not launch process: can not run under Rosetta, check that the installed build of Go is right for your CPU architecture

So I need help, how can I use delve with my mac(M1)?
Thank you very much!

**Comment by yj20060714** [comment]
> Delve is compatible with M1 but not with Rosetta.

Hello, aarzilli: 
I need your help~ my steps as below:
step1:
$ download https://golang.org/dl/go1.15.14.darwin-amd64.tar.gz
$ cd go/src && make.bash


step2:
$ git clone https://github.com/go-delve/delve
$ cd delve
$ go install github.com/go-delve/delve/cmd/dlv

step3:
$ cd my_app
$ dlv debug main.go

then report error : could not launch process: can not run under Rosetta, check that the installed build of Go is right for your CPU architecture

So I need help, how can I use delve with my mac(M1)?
Thank you very much!

**Comment by mario-shippo** [comment]
> > Delve is compatible with M1 but not with Rosetta.
> 
> Hello, aarzilli: I need your help~ my steps as below: step1: $ download https://golang.org/dl/go1.15.14.darwin-amd64.tar.gz $ cd go/src && make.bash
> 
> step2: $ git clone https://github.com/go-delve/delve $ cd delve $ go install github.com/go-delve/delve/cmd/dlv
> 
> step3: $ cd my_app $ dlv debug main.go
> 
> then report error : could not launch process: can not run under Rosetta, check that the installed build of Go is right for your CPU architecture
> 
> So I need help, how can I use delve with my mac(M1)? Thank you very much!

Hey @yj20060714 one alternative is to 
`brew install dlv`
This will install proper version of it, also, remove the version from your "step2"....
You may find required to create some link in order to VS code to reconize it...
`ls -s /opt/homebrew/bin/dlv $GOPATH/bin/dlv`

Hope it helps.

**Comment by yashtibrewal** [comment]
I there a way/possibility to use docker and ubuntu and run it?

**Comment by tweissin** [comment]
> Hey @yj20060714 one alternative is to `brew install dlv` This will install proper version of it, also, remove the version from your "step2".... You may find required to create some link in order to VS code to reconize it... `ls -s /opt/homebrew/bin/dlv $GOPATH/bin/dlv`
> 
> Hope it helps.

The `ln -s /opt/homebrew/bin/dlv $GOPATH/bin/dlv` helped, thanks. I tried to set a breakpoint in VSCode and it won't hit my breakpoint. Is anyone else experiencing the same?

**Comment by JoeFerrucci** [comment]
### ✅  SOLUTION ✅ 

I provided a solution over on another issue thread: https://github.com/go-delve/delve/issues/2604#issuecomment-1468766540

**Comment by xiantang** [comment]
> I there a way/possibility to use docker and ubuntu and run it? (on Mac M1)有没有办法在Mac M1上使用Docker和Ubuntu并运行它？

export GOARCH="arm64"
git clone https://github.com/go-delve/delve
cd cmd/dlv/cmds/
go install .

build dlv by your self in container or VM

<img width="1512" alt="image" src="https://github.com/go-delve/delve/assets/34479567/3a442f35-5b93-4115-a8aa-c5cdfe92a014">

**Comment by cvigo** [comment]
> ### ✅ SOLUTION ✅
> I provided a solution over on another issue thread: [#2604 (comment)](https://github.com/go-delve/delve/issues/2604#issuecomment-1468766540)

That solution is ok to run natively in a M1 chip but not under Rosetta, that is always the case you need if you have to link C libraries made for Intel.
