### ISSUE TITLE
How to debug code with delve on Mac Pro M1

### ISSUE THREAD

**Issue by yj20060714** [go-delve/delve#2612]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1.What version of Delve are you using (dlv version)?
<img width="425" alt="image" src="https://user-images.githubusercontent.com/9796366/126626996-f7fd4de9-c16e-4ed7-87e7-bb9634020598.png">

2.What version of Go are you using? (go version)?
<img width="291" alt="image" src="https://user-images.githubusercontent.com/9796366/126627125-e15ab5d0-7265-472b-8fa5-df3a3a2cdf5a.png">

3.What operating system and processor architecture are you using?
<img width="947" alt="image" src="https://user-images.githubusercontent.com/9796366/126627205-dfb5de3a-fdbe-4dfe-b09b-876d62d677c2.png">

4.What did you do?
<img width="876" alt="image" src="https://user-images.githubusercontent.com/9796366/126627287-0cf18e80-e461-4b3e-8113-2b490da48846.png">

5.What did you expect to see?
<img width="264" alt="image" src="https://user-images.githubusercontent.com/9796366/126627804-2162c035-199e-4789-9847-8ed1db1d6efe.png">

6.What did you see instead?
<img width="897" alt="image" src="https://user-images.githubusercontent.com/9796366/126627997-3ea22397-526a-424f-9788-ecec360e7efc.png">

Details as below:

step1:
$ download https://golang.org/dl/go1.15.14.darwin-amd64.tar.gz
$ cd go/src && make.bash

step2:
$ git clone https://github.com/go-delve/delve
$ cd delve
$ go install github.com/go-delve/delve/cmd/dlv

step3:
$ cd my_app
$ dlv debug main.go

Then reports error :
 could not launch process: can not run under Rosetta, check that the installed build of Go is right for your CPU architecture

So, how to debug go code with delve on MacBook Pro(M1). Thanks!

**Comment by derekparker** [comment]
Your Go version is `darwin/amd64`, it must be `darwin/arm64`. Download the correct arm version of the Go toolchain, recompile Delve, and things will work just fine.

**Comment by yj20060714** [comment]
> Your Go version is `darwin/amd64`, it must be `darwin/arm64`. Download the correct arm version of the Go toolchain, recompile Delve, and things will work just fine.


Hello, derekparker.
I have installed Go version of darwin/arm64, but "dlv debug xx.go" reports the same error:

<img width="891" alt="image" src="https://user-images.githubusercontent.com/9796366/126731078-26bbea0c-d4a2-45b3-9eb9-bb8a381f24bc.png">

Which path of go does delve use? Is the first path in $PATH?

**Comment by derekparker** [comment]
@yj20060714 did you recompile the Delve binary you're using with the arm64 toolchain?

**Comment by yj20060714** [comment]
> @yj20060714 did you recompile the Delve binary you're using with the arm64 toolchain?

It works!!! Thank you very much!!!
