### ISSUE TITLE
Test Debugging stopped working

### ISSUE THREAD

**Issue by Davincible** [go-delve/delve#2657]
1. What version of Delve are you using (`dlv version`)? 
```
Delve Debugger
Version: 1.7.0
Build: $Id: e353a65161e6ed74952b96bbb62ebfc56090832b $

```
2. What version of Go are you using? (`go version`)?
`go version go1.16.7 linux/amd64`
3. What operating system and processor architecture are you using?
Manjaro 5.13, x86_64
4. What did you do?
`dlv test -test.v -test.run TestUploadPhoto`, `b tests.TestUploadPhoto`, `c`
5. What did you expect to see?
Stop at breakpoint
6. What did you see instead?
Stuck in loop:
```
   569: // int64 futex(int32 *uaddr, int32 op, int32 val,
   570: //      struct timespec *timeout, int32 *uaddr2, int32 val2);
   571: TEXT runtime·futex(SB),NOSPLIT,$0
   572:         MOVQ    addr+0(FP), DI
   573:         MOVL    op+8(FP), SI
   574:         MOVL    val+12(FP), DX
   575:         MOVQ    ts+16(FP), R10
   576:         MOVQ    addr2+24(FP), R8
   577:         MOVL    val3+32(FP), R9
   577:         MOVL    val3+32(FP), R9
   578:         MOVL    $SYS_futex, AX
   579:         SYSCALL
   580:         MOVL    AX, ret+40(FP)
   581:         RET
```

It never gets to the breakpoint. Regular stopping does work. And this has worked before. It just stopped working

**Comment by aarzilli** [comment]
Use `goroutines`, `goroutine` and `stack` to figure out what your program is doing. It is likely just stuck somewhere.

**Comment by aarzilli** [comment]
Closing, no feedback.
