### ISSUE TITLE
Next command skips lines with code

### ISSUE THREAD

**Issue by nd** [go-delve/delve#2664]
1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 1.7.0
Build: b41e47a30539294818283b89dae4d4879242e0c5
```

2. What version of Go are you using? (`go version`)?
```
go version go1.17 windows/amd64
```

3. What operating system and processor architecture are you using?
```
windows/amd64
```

4. What did you do?

Cloned github.com/dolthub/dolt. Built tests using:

```
go.exe test -c -o test.exe -gcflags "all=-N -l" github.com/dolthub/dolt/go/libraries/doltcore/sqle
```

in the `go` directory. Ran the `TestTableEditor` using delve:
```
dlv.exe --log --log-output rpc --log-dest dlv.log exec test.exe -- -test.run ^\QTestTableEditor\E$
```

Added a breakpoint at [testutil.go:116](https://github.com/dolthub/dolt/blob/master/go/libraries/doltcore/sqle/testutil.go#L116). Once it is reached, executed `next`.

5. What did you expect to see?

Program stops on the next line with code, line 120.

6. What did you see instead?

Program skips lines 120 and 121 and stops at 122.

If one explicitly adds breakpoints at lines 120 and 121, program stops there.

Delve log: https://gist.github.com/nd/82776aba8fcdc82bdbae419975dca839

**Comment by aarzilli** [comment]
What happens if you press next again?

**Comment by nd** [comment]
Debugger stops at line 126

**Comment by aarzilli** [comment]
I suspect this is just the compiler getting line numbers wrong, I'll look more into it later.

**Comment by aarzilli** [comment]
I was wrong, it's the compiler getting the statement flag wrong.

**Comment by aarzilli** [comment]
Closing this in favor of upstream issue, I don't think there's nothing to do about this in delve.
