### ISSUE TITLE
Install Error: too many memory references for `mov'

### ISSUE THREAD

**Issue by ruhan1** [go-delve/delve#2672]
I hit below error when install dlv by VS code Go extension. Here are the details. I use Fedora release 34.

$ go get -v github.com/go-delve/delve/cmd/dlv
github.com/go-delve/delve/pkg/proc/amd64util
mod/github.com/go-delve/delve@v1.7.1/pkg/proc/amd64util/xsave_amd64.s: Assembler messages:
mod/github.com/go-delve/delve@v1.7.1/pkg/proc/amd64util/xsave_amd64.s:1: Error: no such instruction: `text ·cpuid(SB),$0-24'
mod/github.com/go-delve/delve@v1.7.1/pkg/proc/amd64util/xsave_amd64.s:2: Error: junk `(FP)' after expression
mod/github.com/go-delve/delve@v1.7.1/pkg/proc/amd64util/xsave_amd64.s:2: Error: too many memory references for `mov'
mod/github.com/go-delve/delve@v1.7.1/pkg/proc/amd64util/xsave_amd64.s:3: Error: junk `(FP)' after expression
mod/github.com/go-delve/delve@v1.7.1/pkg/proc/amd64util/xsave_amd64.s:3: Error: too many memory references for `mov'
mod/github.com/go-delve/delve@v1.7.1/pkg/proc/amd64util/xsave_amd64.s:5: Error: too many memory references for `mov'
mod/github.com/go-delve/delve@v1.7.1/pkg/proc/amd64util/xsave_amd64.s:6: Error: too many memory references for `mov'
mod/github.com/go-delve/delve@v1.7.1/pkg/proc/amd64util/xsave_amd64.s:7: Error: too many memory references for `mov'
mod/github.com/go-delve/delve@v1.7.1/pkg/proc/amd64util/xsave_amd64.s:8: Error: too many memory references for `mov'

$ go version
go version go1.16.5 gccgo (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1) linux/amd64

$ arch 
x86_64

**Comment by aarzilli** [comment]
gccgo is not supported.

**Comment by ruhan1** [comment]
thank you @aarzilli . I happened to have gccgo installed. Although I don't know what is that actually, the issue is gone after I remove gccgo. I put it here in case someone hit same problem.
