### ISSUE TITLE
Wrong constant is returned in a variable value

### ISSUE THREAD

**Issue by nd** [go-delve/delve#2681]
1. What version of Delve are you using (`dlv version`)?

```
Delve Debugger
Version: 1.7.0
Build: b41e47a30539294818283b89dae4d4879242e0c5
```

2. What version of Go are you using? (`go version`)?

```
go version go1.17 windows/amd64
```

3. What operating system and processor architecture are you using?

```
windows/amd64
```

4. What did you do?

Debugged a program

```
package main

import (
  "net/http"
  "time"
)

func main() {
  t := 10 * time.Second
  println(t) //break
  http.ServeTLS(net.Listener(nil), nil, "", "") // just to make net/http.http2prefaceTimeout appear in the executable
}

```

5. What did you expect to see?

value of t is `10000000000`

6. What did you see instead?

value of t is `net/http.http2prefaceTimeout (10000000000)`

If I remove the `http.ServeTLS` line and the corresponding import, the value is returned as expected.

**Comment by aarzilli** [comment]
Why is this wrong, in your opinion? The value of the constant `net/http.http2prefaceTimeout` is 10000000000. What should be the rule for when we use a constant as the value of a variable?

**Comment by kszafran** [comment]
I have had this issue with constant names from completely different packages showing up. For example, I was debugging NATS-related code and one of the variables showed as an unexported Kafka constant. That's very confusing and made me wonder how these two could have gotten mixed up.

The same applies here. If a value shows up as `net/http.http2prefaceTimeout`, then it's reasonable to conclude that somewhere in the code there is `myvar = http2prefaceTimeout`, except that is not the case. The value just happens to be the same as some random constant, somewhere in the codebase.

**Comment by aarzilli** [comment]
I see but what we have is the type of the variable, its value and the list of constants for that type. There is no way to know if the variable happens to have a certain vaule because it was assigned from a constant or if it is a coincidence.

**Comment by nd** [comment]
if the constant is unexported and comes from a different package it seems to be a coincidence

**Comment by aarzilli** [comment]
> if the constant is unexported and comes from a different package it seems to be a coincidence

A different package compared to what? The current function? The type of the variable? Suppose your main function has a variable of some `net/http` type with a private member of type `time.Second` that happens to have the value 10000000000, should the constant be used?

**Comment by nd** [comment]
Looks like any 'different package' heuristics breaks some valid cases..

**Comment by aarzilli** [comment]
I'm going to close the issue for now because no one has proposed anything concrete. Ideas on how to improve this are welcome.
