### ISSUE TITLE
dap: Pause request while stopped prevents forward progress on following Continue

### ISSUE THREAD

**Issue by suzmue** [go-delve/delve#2685]
1. What version of Delve are you using (`dlv version`)?
at tip
2. What version of Go are you using? (`go version`)?
`go version go1.17 linux/amd64`
3. What operating system and processor architecture are you using?
linux/amd64
4. What did you do?
- Debug a process.
- Send a manual halt request
- Continue

5. What did you expect to see?
I expected the process to continue beyond the location it was stopped at
6. What did you see instead?
Process is still stopped at same location 

From my investigation it seems that the signal sent to halt the process, is being received by the Continue call, blocking the program from making forward progress

**Comment by suzmue** [comment]
This is causing the test failures on linux in PR #2634

**Comment by aarzilli** [comment]
This is working as intended.

**Comment by suzmue** [comment]
> This is working as intended.

Updated the issue to address the issue in DAP only.

**Comment by polinasok** [comment]
This can be closed now, right? Halt while halted may or may not be applied to the Continue that follows, so we just make sure not to issue double halts.
