### ISSUE TITLE
dlv display hits goroutine but don't stop at the breakpoint

### ISSUE THREAD

**Issue by crazypaul123** [go-delve/delve#2695]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
   Delve Debugger
   Version: 1.4.0
   Build: $Id: 67422e6f7148fa1efa0eac1423ab5594b223d93b $
2. What version of Go are you using? (`go version`)?
   Go Info:
   go version go1.14.14 linux/amd64
3. What operating system and processor architecture are you using?
   uname -a
   Linux push-press-test06.py 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
4. What did you do?
    Breakpoint 1 set at Example.go:322
    cond 1 var=="111"
5. What did you expect to see?
    the program stop at the goroutine
6. What did you see instead?
    most of times ,dlv display  (hits goroutine(717):1 total:2) (PC: 0xba6e2d) but not stop at the goroutine,only a few times stop at the goroutine; It seems to be  a random event

**Comment by aarzilli** [comment]
Do you have a way to reproduce this or a transcript of this happening, possibly with `--log --log-output=rpc`?

**Comment by crazypaul123** [comment]
![881631286602_ pic_hd](https://user-images.githubusercontent.com/35377067/132876281-4214d557-e58a-4eb2-b613-9c03e795f77d.jpg)
Like the red circle in the picture, dlv just display hits goroutine(4025) but  not  stop . I didn't input continue but dlv continue to exec the program. This situation  shows lots of times  in the morning,   but only once in the evening, I don't know why

**Comment by crazypaul123** [comment]
> Do you have a way to reproduce this or a transcript of this happening, possibly with `--log --log-output=rpc`?

> ![881631286602_ pic_hd](https://user-images.githubusercontent.com/35377067/132876281-4214d557-e58a-4eb2-b613-9c03e795f77d.jpg)
> Like the red circle in the picture, dlv just display hits goroutine(4025) but not stop . I didn't input continue but dlv continue to exec the program. This situation shows lots of times in the morning, but only once in the evening, I don't know why

**Comment by aarzilli** [comment]
I think you just pressed return twice, delve will repeat the last command if you just press return. Your return key may be bouncy.

**Comment by crazypaul123** [comment]
> I think you just pressed return twice, delve will repeat the last command if you just press return. Your return key may be bouncy.

thank you
