### ISSUE TITLE
debugging of tests

### ISSUE THREAD

**Issue by goen** [go-delve/delve#27]
$ dlv -run
[Could not start process: fork/exec ./debug: permission denied]
$ chmod +x ./debug
$ dlv -run
[Could not start process: fork/exec ./debug: permission denied]

**Comment by ajpen** [comment]
I just came across this issue when trying to debug a 'non-main' package. That's likely the cause.

**Comment by derekparker** [comment]
@ajpen if you want to debug a non-main package (that has tests) you can use `dlv test <pkg>`. If that doesn't work please submit a new issue.

**Comment by ajpen** [comment]
@derekparker Good to hear from you Derek. I just placed that comment up to give some context for anyone else that might run into it and find themselves here. Thanks
