### ISSUE TITLE
Unable to parse Go+BoringCrypto release version 

### ISSUE THREAD

**Issue by yang-wei** [go-delve/delve#2711]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?

```
> dlv version
Delve Debugger
Version: 1.7.1
Build: $Id: 3bde2354aafb5a4043fd59838842c4cd4a8b6f0b $
```

2. What version of Go are you using? (`go version`)?

```
> go version
go version go1.16 darwin/amd64
```

3. What operating system and processor architecture are you using?
```
> uname   
Darwin
> uname -p
i386
```

4. What did you do?
We are using https://go.googlesource.com/go/+/dev.boringcrypto/misc/boring and the format is a bit different from Go Version. delve parser didn't expect `<GoVersion>b<BoringCryptoVersion>` format so it was unable to parse and lead to `Version of Go is too old for this version of Delve ...` when I `dlv exec <binary-built-with-go-1.16.4b7>`

5. What did you expect to see?

I expect delve to parse boringcrypto version string and executed normally

6. What did you see instead?

Version of Go is too old for this version of Delve (minimum supported version 1.15, suppress this error with --check-go-version=false)

If you plan to support BoringCrypto Version I can work on it

*FYI for anyone who needs more contexts, please see https://kupczynski.info/2019/12/15/fips-golang.html*

**Comment by aarzilli** [comment]
The version is parsed in pkg/goversion/go_version.go
