### ISSUE TITLE
dap: consider []string for Launch BuildFlags

### ISSUE THREAD

**Issue by hyangah** [go-delve/delve#2718]
DAP [`LaunchConfig.BuildFlags`](https://github.com/go-delve/delve/blob/c7e2a9b6fb902d685e77b28b001c0c95e5eb95b3/service/dap/types.go#L101) is defined as `string` type.
It is `string` because VS Code Go defined the `buildFlags` in that way in its legacy debug adapter that invokes `dlv debug` or `dlv test`, and `dlv` command line takes the build flags (--build-flags) as a string.

DAP can take Launch configuration in JSON, which can support more rich types than a simple command line flag.
Historically, the subtle difference between how dlv is parsing the build flags and how go command is parsing the flags was annoying and sometimes frustrating (e.g. https://github.com/golang/vscode-go/issues/1027).

Please consider to take `[]string` and bypass delve's flag parsing.

**Comment by aarzilli** [comment]
I believe if you bypass config.SplitQuotedFields completely and users write this:

```
buildFlags: [ "-ldflags='-X main.V=Hello'" ],
```

they will have the same problem.

**Comment by aarzilli** [comment]
I wonder if it's better to just add double-quote handling to SplitQuotedFields

**Comment by hyangah** [comment]
I guess users should write If `[]string` is allowed
 
```
buildFlags: ["-ldflags=-X main.V=Hello"]
```

Right? Launching go commands in node.js seems fine with both `["-ldflags='-X main.V=Hello'"]` and `["-dlflags=-X main.V=Hello"]`, but it looks like `go` command doesn't seem happy with the former as you guessed.

Currently vscode-go and gopls both use `[]string` for buildFlags. So, the flag plumbing from vscode-go to gopls is a bit easier. For delve, if we want to the the flag plumbing, is it ok to simply concatenate buildFlags setting with ' '?

**Comment by aarzilli** [comment]
> is it ok to simply concatenate buildFlags setting with ' '?

With a space? No it will not work if they contain spaces themselves.
They need to be quoted and then concatenated with spaces if they are to be passed to SplitQuotedFields, or just call SplitQuotedFields on each. Regardless if double quotes are used it won't work.

It probably works with node.js because it's doing some shell-like quote processing magic (or just going through the shell).

**Comment by aarzilli** [comment]
> or just call SplitQuotedFields on each.

This would actually be wrong, BTW. But something like it that strips quotes. OTOH I think doing nothing and letting 

> ```
> buildFlags: [ "-ldflags='-X main.V=Hello'" ],
> ```

fail would also be ok.

**Comment by hyangah** [comment]
@aarzilli We are currently debating whether you're against this feature request completely or not. Can you please clarify to end our confusion :-)?
