### ISSUE TITLE
Delve crashes in dwarf2Ranges

### ISSUE THREAD

**Issue by gmottram** [go-delve/delve#2719]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)? 1.7.2
2. What version of Go are you using? (`go version`)?  go1.17.1 linux/amd64
3. What operating system and processor architecture are you using?  linux/amd64
4. What did you do? Ran the command:  dlv debug mintest.go, b main.main, c
5. What did you expect to see? Program would stop at main.main
6. What did you see instead?

When I ran the "c" (continue) command to start the program, it looked like this:

bash-5.0$ dlv debug mintest.go
Type 'help' for list of commands.
(dlv) b main.main
Breakpoint 1 set at 0x71120f for main.main() ./mintest.go:17
(dlv) c
panic: runtime error: slice bounds out of range [728332:33664]

goroutine 73 [running]:
debug/dwarf.(*Data).dwarf2Ranges(0xc006d20a80, 0xc00002db85, 0x0, 0x7f08fc148100, {0x0, 0x44bfb4, 0x8})
        /usr/local/go/src/debug/dwarf/entry.go:1105 +0x2b9
debug/dwarf.(*Data).Ranges(0xc006d20a80, 0xc008082cf0)
        /usr/local/go/src/debug/dwarf/entry.go:1067 +0x511
github.com/go-delve/delve/pkg/dwarf/godwarf.(*Tree).resolveRanges(0xc008064ea0, 0x2db85, 0x7ff5fd61d000)
        /usr/local/go/pkg/mod/github.com/go-delve/delve@v1.7.2/pkg/dwarf/godwarf/tree.go:131 +0x4c
github.com/go-delve/delve/pkg/dwarf/godwarf.LoadTree(0x6e5d2e0, 0xc006d20a80, 0xc00152dc6c)
        /usr/local/go/pkg/mod/github.com/go-delve/delve@v1.7.2/pkg/dwarf/godwarf/tree.go:84 +0x13a
github.com/go-delve/delve/pkg/proc.(*Image).getDwarfTree(0xc006eba0e0, 0x2db85)
        /usr/local/go/pkg/mod/github.com/go-delve/delve@v1.7.2/pkg/proc/bininfo.go:813 +0xa5
github.com/go-delve/delve/pkg/proc.(*BinaryInfo).loadDebugInfoMaps(0xc00012cc80, 0xc006eba0e0, {0xc008f6a000, 0xc3e8c, 0xc3e8c}, {0xc00902e000, 0x24400, 0x24400}, 0xc0084dde90, 0x0)
        /usr/local/go/pkg/mod/github.com/go-delve/delve@v1.7.2/pkg/proc/bininfo.go:1830 +0x1145
created by github.com/go-delve/delve/pkg/proc.loadBinaryInfoElf
        /usr/local/go/pkg/mod/github.com/go-delve/delve@v1.7.2/pkg/proc/bininfo.go:1249 +0x6df

It was working fine and then I added about five lines of new source code to one file and then this happened. If I comment out the new lines of code, it runs fine again. If you need some binaries or code, please let me know. At this point the project is only about five files plus the "github.com/magiconair/properties/" package.

Thanks and great product, BTW.

**Comment by aarzilli** [comment]
Can you try applying #2687? It should be that.

**Comment by gmottram** [comment]
Sweet! That fixes it.

Thank you aarzilli for your prompt and excellent help.
