### ISSUE TITLE
Can not show the source code when i use dlv attach my application

### ISSUE THREAD

**Issue by Jun10ng** [go-delve/delve#2724]
Please answer the following before submitting your issue:

Can not show the source code when i use dlv attach my application.

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
 
2. What version of Go are you using? (`go version`)?
 12.7
3. What operating system and processor architecture are you using?
 linux x86
4. What did you do?
 my code dir is /root/go/src/git.company.com/pkg/service/

 `dlv attach {pid}`
 `(dlv) b git.company.com/pkg/service/order-server/plugins.CreateOrderProcess`
  and it outputs
 `Breakpoint 1 set at 0x27fe69b for git.company.com/pkg/service/order-server/plugins.CreateOrderProcessor() /tmp/goc-build-7e5b20ef452c/order-server/plugins/create_order.go:39`
`(dlv) c`
 then I post a request.
5. What did you expect to see?
```
  git.company.com/pkg/service/order-server/plugins.CreateOrderProcessor() /tmp/goc-build-7e5b20ef452c/order-server/plugins/create_order.go:39 (hits goroutine(1459):1 total:1) (PC: 0x27fe69b)
Warning: debugging optimized function
  => {there will display source code}
```
6. What did you see instead?
```
   git.company.com/pkg/service/order-server/plugins.CreateOrderProcessor() /tmp/goc-build-7e5b20ef452c/order-server/plugins/create_order.go:39 (hits goroutine(1459):1 total:1) (PC: 0x27fe69b)
Warning: debugging optimized function
```

At first I suspected that it was a ”substitute-path“ problem, but  when I run command `sources order-server`, it outputs all files.

**Comment by aarzilli** [comment]
Whatever you used to build your program was reading source code from /tmp/goc-build-7e5b20ef452c/ which is where delve will search for them.

**Comment by Jun10ng** [comment]
Thx.
