### ISSUE TITLE
how to use dlv with go build temporary directory?

### ISSUE THREAD

**Issue by Jun10ng** [go-delve/delve#2727]
I using dlv debugs my application and I found that the source code of my application was copied to a temporary directory `/tmp/goc-buiild-xxxx` which created by go build when the program was compiled.

`/tmp/goc-buiild-xxxx`  is a random string. When I set a breakpoint, dlv will prompt me the exact name of this temporary directory, then I set 
`substitute-path /tmp/goc-buiild-xxxx  /real-source-code-dir`

I am wondering **how to get the exact name of this temporary directory before I enter dlv?**

This is my other issue https://github.com/go-delve/delve/issues/2724

**Comment by aarzilli** [comment]
I don't think you are using "go build", I think you are using [goc](https://github.com/qiniu/goc). It is more likely that you will find your answer by asking them.

**Comment by Jun10ng** [comment]
!! Thx !! aarzilli you are my superman!
