### ISSUE TITLE
how to set folder of debug binary file

### ISSUE THREAD

**Issue by liyoubdu** [go-delve/delve#2758]
today i install dlv in vscode on windows.
press F5 to start debug in vscode.

when i run the code below,  value of 'exeDir' is '"C:\\Users\\86137\\AppData\\Local\\Temp"'
`exePath, _ := os.Executable()`
`exeDir := filepath.Dir(exePath)`

but my code locate at 'F:\code\test\'.  i wish value of 'exeDir' is 'F:\code\test\'. what should i do?

**Comment by aarzilli** [comment]
This fell through the cracks but the documentation of launch.json is at https://github.com/golang/vscode-go/blob/master/docs/debugging.md.
