### ISSUE TITLE
No error on attempt to call optimized function

### ISSUE THREAD

**Issue by nd** [go-delve/delve#2767]
1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 1.7.0
Build: b41e47a30539294818283b89dae4d4879242e0c5
```

2. What version of Go are you using? (`go version`)?
```
go version go1.17.2 darwin/amd64
```

3. What operating system and processor architecture are you using?
darwin/amd64

4. What did you do?

Debugged the program

```
package main

func main() {
  res := math.Floor(2.5)
  println(res)
}
```

and called `math.Floor(2.5)` at line with println.

5. What did you expect to see?

Result 2 or error why result cannot be computed

6. What did you see instead?

Result 0 and no error.

Command-line delve client shows the error saying that calling of optimized function is not possible. In go1.16.5 same call produces 'too many function arguments' error.

Ide log: https://gist.github.com/nd/65887e7c494da72ce768a9ef040d4752
Delve command-line client log: https://gist.github.com/nd/a6a15b6cdaeaf03eb46e60d2408dd874

**Comment by aarzilli** [comment]
Upstream bug: https://bugs.llvm.org/show_bug.cgi?id=52362 (funny)

**Comment by aarzilli** [comment]
PS. the thing about the command line returning an error is a red herring, you just compiled the executable without 'all=', or something like that.

**Comment by aarzilli** [comment]
It seems that there's a problem with linux/arm64 builds on teamcity:

```
Amazon EC2 connection (profile 'Graviton\Arm64'{id=amazon-1}, operation:describeInstances). Unable to perform operation 'describeInstances': UnauthorizedOperation: 'You are not authorized to perform this operation.
```

**Comment by nd** [comment]
>  problem with linux/arm64 builds on teamcity
reported it, hope will be fixed soon

**Comment by aarzilli** [comment]
Cool, thank you. When you have time can you see if the workaround works for you?

**Comment by nd** [comment]
Tested, it works. Thank you!

**Comment by nd** [comment]
teamcity problem was fixed

**Comment by aarzilli** [comment]
> teamcity problem was fixed

Thanks!
