### ISSUE TITLE
p string([]byte(`{"json": "encoded"...}`)) result in dlv wasn't shown correct string

### ISSUE THREAD

**Issue by awsom82** [go-delve/delve#2776]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.7.1
Build: $Id: 3bde2354aafb5a4043fd59838842c4cd4a8b6f0b $

2. What version of Go are you using? (`go version`)?
go version go1.17.2 darwin/amd64

3. What operating system and processor architecture are you using?
macOS v12.0.1 on Intel i9 10910 x86-64

4. What did you do?
`dlv> p string(payload)` // payload 

to debug `json.Marshal` results
```go
	var err error
	var payload []byte
	var result bytes.Buffer
	var req *http.Request
	var resp *http.Response

	payload, err = json.Marshal(p)
	if err != nil {
		return fmt.Errorf("[QIWI] %w: %s", ErrBadJSON, err)
	}
```

5. What did you expect to see?
`{"amount":{"value":503.00,"currency":"RUB"},"expirationDateTime":"2021-11-04T16:09:42+07:00","flags":["SALE"]}`

6. What did you see instead?
<img width="721" alt="Снимок экрана 2021-11-04 в 17 35 54" src="https://user-images.githubusercontent.com/5804704/140320490-bdf18a90-458d-486c-8422-8d6f79f52464.png">

The `config max-string-len 255` was applied, but in a debugger, it wasn't represented correctly. The output of `p string()` wasn't show actual data. The date was produced by custom MarshalJSON, code available at https://github.com/sendtips/qiwi/blob/master/qiwitime.go#L42

**Comment by aarzilli** [comment]
Because of how conversions happen max-array-len should be changed instead here.

**Comment by awsom82** [comment]
@aarzilli big thanks! Don't notice `config max-array-values` parameter. Works well now!
