### ISSUE TITLE
Add support for watchpoints

### ISSUE THREAD

**Issue by derekparker** [go-delve/delve#279]
Add support for hardware / software watchpoints. Initially should only support watching a variable, but in the future should be expanded to support expressions.
- Watch a variable and break when the program reads it.
- Watch a variable and break when program writes it.
- Combination of both above.

**Comment by mattkelly** [comment]
Any update on this? Is there a different thread I can follow along with?

**Comment by glycerine** [comment]
Watchpoints are the reason I use a debugger at all. They are invaluable. If possible, please prioritize them.

**Comment by cloehle** [comment]
Especially setting watchpoints on channels would be really useful to follow execution flow.

**Comment by chainhelen** [comment]
I have a question here: are `hardware watchpoints` realized by CPU debug registers DR0 ~ DR3 on amd64?

**Comment by aarzilli** [comment]
> Especially setting watchpoints on channels would be really useful to follow execution flow.

Writing to a channel is actually converted into a function call, so it would just be a regular conditional breakpoint on runtime.chansend/runtime.chanrecv (however it is currently impossible to write the appropriate condition).

> I have a question here: are hardware watchpoints realized by CPU debug registers DR0 ~ DR3 on amd64?

Yes, however things are complicated substantially by stack resize operations.

**Comment by baiwfg2** [comment]
Hi. Is this being working on ? Right now I've found during VSCode + dlv debugging, I can see the watched variables' value, but can't see the program is stopped when the watched variables are changed, which seems not to match `watch` semantics. Better to behave like gdb watch

**Comment by aarzilli** [comment]
Support for watchpoints was added to the extent that it is doable.
