### ISSUE TITLE
1.7.3 Dependency on Tools version not released

### ISSUE THREAD

**Issue by jonyoder** [go-delve/delve#2799]
Go version: `go version go1.17.1 linux/amd64`
Running in Docker on Mac/Intel

Attempting to install delve:
```bash
PATH="$PATH:/usr/local/go/bin" \
  GOPATH=/usr/local/gotools \
  go get -u -v \
    golang.org/x/tools/... \
    github.com/go-delve/delve
```

Results in this error:
```
/cmd/dlv go get: github.com/go-delve/delve@v1.7.3 (matching github.com/go-delve/delve/cmd/dlv@upgrade) requires golang.org/x/tools@v0.1.8-0.20211028023602-8de2a7fd1736, not golang.org/x/tools@v0.1.7 (matching golang.org/x/tools/...@upgrade)
```

**Comment by jonyoder** [comment]
@aarzilli - No, just some code I inherited from an older Dockerfile. I'll take a look at the latest install instructions.

**Comment by jonyoder** [comment]
Adjusting to use the recommended install method works. Not sure if this is still worth reporting or not, so feel free to close if you want.

**Comment by aarzilli** [comment]
At this point (after 1.11) `go get -u` is always going to be the wrong way to install things. I'm not even sure what that command does now, used outside of a module, but clearly it's wrong since it's forcing the use of the wrong version of a dependency.
