### ISSUE TITLE
Debuggin gives error "%1 is not a valid win32 application" which uses gcc to compile

### ISSUE THREAD

**Issue by ironytr** [go-delve/delve#2809]
Hello, im newbie at programming. i had a issue with debuggin my project with go1.17.3 which is not worked, downgraded to go1.17.2 now works. i wanted to share here whos stucks at this situation (for win10 users  gcc TDM-GCC-64 is working correctly tried others... not every gcc version works). Feel free remove this if i did wrong while opening this topic, i just wanted to notice you.

1. What version of Delve are you using (`dlv version`)?
1.a  1.7.3
2. What version of Go are you using? (`go version`)?
2.a go1.17.3 windows/amd64
3. What operating system and processor architecture are you using?
3.a windows 10 pro, x86_64
4. What did you do?
4a. freshly installation of windows 10 and downloaded latest go packages working on my project debuggin is not started "%1 is not a valid win32 application" while go run or builds working with go1.17.3
5. What did you expect to see?
5a. sample project given by gorm to run which uses gcc

```
package main

import (
	"fmt"

	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)

type Product struct {
	gorm.Model
	Code  string
	Price uint
}

func main() {
	db, err := gorm.Open(sqlite.Open("test.db"), &gorm.Config{})
	if err != nil {
		panic("failed to connect database")
	}

	// Migrate the schema
	db.AutoMigrate(&Product{})

	// Create
	db.Create(&Product{Code: "D42", Price: 100})

	// Read
	var product Product
	db.First(&product, 1)                 // find product with integer primary key
	db.First(&product, "code = ?", "D42") // find product with code D42

	// Update - update product's price to 200
	db.Model(&product).Update("Price", 200)
	// Update - update multiple fields
	db.Model(&product).Updates(Product{Price: 200, Code: "F42"}) // non-zero fields
	db.Model(&product).Updates(map[string]interface{}{"Price": 200, "Code": "F42"})
	fmt.Println(product)
	// Delete - delete product
	db.Delete(&product, 1)
}
```
6. What did you see instead?
6a.debuggin with vscode or goland crashs with error %1 is not a valid win32 application

i had a day to figure out why this happens, because normally debuggin works with non gcc compiles but not with gcc. so i downgraded go1.17.3 to go1.17.2 now everything is working normally.

**Comment by aarzilli** [comment]
What happens if you run `go build -gcflags='all=-N -l' yourprogram.go`? If it works with 1.17.2 but not with 1.17.3 it is probably a Go bug.

**Comment by ironytr** [comment]
> What happens if you run `go build -gcflags='all=-N -l' yourprogram.go`? If it works with 1.17.2 but not with 1.17.3 it is probably a Go bug.
i have now 1.17.2 can't test that, sorry for lack of info for this topic sir. but when i build that sample code (1.17.3 go run main.go or go build main.go)  it was working. i just couldnt debug. i could debug which projects not using gcc. i hope i could clarify to problem. (debuggin was working with non gcc req. but with not gcc required projects)
