### ISSUE TITLE
VSCode Delve debugger: Could not launch process '%1 is not a valid Win32 application'

### ISSUE THREAD

**Issue by meistars** [go-delve/delve#2821]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.7.3
Build: $Id: 4c81a2a322716591167f0bd690f7ef656781b6f4 $

2. What version of Go are you using? (`go version`)?
go version go1.16 windows/amd64

3. What operating system and processor architecture are you using?
OSArchitecture  
64-bit Microsoft Windows 11 Enterprise

4. What did you do?
Start a go debugging session with delve with following launch settings:
```json
{
"configurations": [
        {
            "name": "Launch Package",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "C:\\app\\main.go",
        }
    ]
}
```
5. What did you expect to see?
Successfully started debugging session
6. What did you see instead?

`Starting: C:\{redacted}\dlv-dap.exe dap --check-go-version=false --listen=127.0.0.1:1052 --log=true from C:\app
DAP server listening at: 127.0.0.1:1052
2021-12-08T15:28:58+02:00 info layer=debugger launching process with args: [C:\{redacted}\AppData\Local\Temp\__debug_bin974861539.exe]`

Got:

Visual Studio Code  
[Content]    
`Failed to launch: could not launch process: fork/exec C:\{redacted}\AppData\Local\Temp\__debug_bin083632647.exe: %1 is not a valid Win32 application.`
[Open 'launch.json'] [Cancel]

More details:
This happens only when the application uses CGO (requires gcc).
I have two environments, where setup "seems" to be exactly the same versions of (gcc, vscode, go, dlv, OS).
However one has this issue the other not. Seems to be related how delve builds solution before debugging when cgo is used.

Workaround:
Build unoptimized version:  `go build -gcflags="all=-N -l"` the solution builds and works fine.
Then I can use following settings in VSCode launch.json: ("mode": "exec", "program": "program.exe").

However its not clear to me yet what is causing the dlv to behave like this when building for debugging from vscode.
As when I build unoptimized version manually and then exec, the breakpoints are hit and the debugger runs fine.

>go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\{redacted}\AppData\Local\go-build
set GOENV=C:\{redacted}\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\{redacted}\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\{redacted}\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\{redacted}\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\{redacted}\AppData\Local\Temp\go-build90370722=/tmp/go-build -gno-record-gcc-switches

**Comment by aarzilli** [comment]
>  Failed to launch: could not launch process: fork/exec C:{redacted}\AppData\Local\Temp__debug_bin974861539.exe: %1 is not a valid Win32 application.

Does this really not have a slash after Temp or did you edit it out?

**Comment by meistars** [comment]
Updated with the right path, edit issue.

**Comment by polinasok** [comment]
Can you reproduce this problem by running "dlv debug <file>" directly?

**Comment by meistars** [comment]
> Updated with the right path, edit (markdown `\__`) issue if not wrapped in single quotes then \ is discarded.



> > Failed to launch: could not launch process: fork/exec C:{redacted}\AppData\Local\Temp__debug_bin974861539.exe: %1 is not a valid Win32 application.
> 
> Does this really not have a slash after Temp or did you edit it out?
> 
> Edit: Never mind, it doesn't appear because of markdown. Delve doesn't do anything special to build the executable, it just runs the same command you ran manually. It could be an issue with your antivirus software.

Thanks for the tip, went full sysadmin by setting exclusions and etc but still with no avail.



> Can you reproduce this problem by running standalone `dlv debug <file>` directly?

That's a good idea and I got some progress with that:

At first I see the same issue:
`C:\{app}\>dlv debug main.go --log
2021-12-09T09:29:54+02:00 info layer=debugger launching process with args: [C:\{app}\__debug_bin]
could not launch process: fork/exec C:\{app}\__debug_bin: %1 is not a valid Win32 application.`

From the same process I look at my go env:

C:\>go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\{redacted}\AppData\Local\go-build
set GOENV=C:\Users\{redacted}\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\{redacted}\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\{redacted}\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\app\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\{redacted}\AppData\Local\Temp\go-build2935100284=/tmp/go-build -gno-record-gcc-switches

Occam's Razor, from the same process I take these values respective to CGO and set them for my User.

C:\app>set CGO_ENABLED=1
C:\app>set CGO_CFLAGS=-g -O2
C:\app>set CGO_CXXFLAGS=-g -O2
C:\app>set CGO_FFLAGS=-g -O2
C:\app>set CGO_LDFLAGS=-g -O2
C:\app>set PKG_CONFIG=pkg-config
C:\app>set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\{redacted}\AppData\Local\Temp\go-build227367209=/tmp/go-build -gno-record-gcc-switches
C:\app>dlv debug main.go --log

Now the debugger starts up:
`time="2021-12-09T09:39:26+02:00" level=warning msg="CGO_CFLAGS already set, Cgo code could be optimized." layer=dlv`
`2021-12-09T09:39:30+02:00 info layer=debugger launching process with args: [C:\app\__debug_bin]`
`2021-12-09T09:39:31+02:00 warning layer=debugger reading debug_info: concrete subprogram without address range at 0x2882a1`

First it seems to me is that some flags are set by delve and some are not. Secondly same issue in VSCode and for some reason go env environment variables are not respected. Now just have to figure out how to fix that properly. One way would probably be to set all go env variables as permanent in the User sys env.

**Comment by aarzilli** [comment]
Delve sets CGO_CFLAGS='-O0 -g' if it isn't already set to something else. Disabling optimizations shouldn't lead to a broken executable but it's a bug in whatever version of gcc you are using.

**Comment by meistars** [comment]
Not sure how is this related to a bug of gcc, if I can normally do an unoptimized go build and then in VSCode exec with a delve. Interestingly I have the same gcc bits on the other dev env where this works perfectly fine. Will try to investigate what and how this can happen. Meanwhile I have tried MSYS2 and ran into the same issue as recently posted here: https://github.com/golang/vscode-go/issues/1914

**Comment by aarzilli** [comment]
Try setting `CGO_CFLAGS='-O0 -g'` then build with `go build -gcflags='all=-N -l'` and run the resulting binary. Does it work?

**Comment by meistars** [comment]
This works:
```
C:\apo>set CGO_CFLAGS=-g -O2
C:\apo>go build -gcflags="all=-N -l"
C:\apo>main.exe
Hello from app!
```

When I switch CGO_CFLAGS to this, it builds but:
```
c:\app\>set CGO_CFLAGS=-O0 -g
c:\app\>go build -gcflags="all=-N -l"
Access is denied.
```
And a popup of `This app can't run on your PC. To find a version for your PC, check with the software publisher.`
Effectively saying the same that its not a valid Win32 app.
Note: Other env (working system) `CGO_CFLAGS=-O0 -g` and `go build -gcflags="all=-N -l"` executable works (I know it’s a bad answer but it does really bother me that I see no diff and explanation).

Else I tried:
Build without `-gcflags="all=-N -l"` just `go build`
```
C:\apo>set CGO_CFLAGS=-O0 -g
C:\apo>go build
C:\apo>main.exe
Hello from app!
```
The executable file size is larger and it works.
Once I add `-gcflags="all=-N -l"` file size is smaller it builds but the same the same issue.

- Didn’t spot any difference when providing a verbose  `go build -x` when setting `CGO_CFLAGS=-O0 -g` comparing to working.
- Didn’t spot any difference when when doing gcc debug `go tool cgo -debug-gcc main.go`. 
- Manually copy pasted all the gcc bits over to from working environment instead of using same installer, with no avail.

Feels so weird, it must be something simple I am not seeing. And many thanks for taking time to look into this. I will understand if you will close the case, as this seems to be not related to Delve and I will continue my adventures.

Some references with similar issue I have found so far:
https://stackoverflow.com/questions/69450393/unable-to-debug-go-code-on-windows-using-vscode-goland-getting-1-is-not-a-val with only 100+ views (atm), so it might be that this problem is very isolated/specific to the dev environment.

**Comment by aarzilli** [comment]
Cgo applications also go through the system linker, so it could also be that ld is different. I'm going to close this issue since it isn't caused by delve, and probably not by go either, and we can't do anything about it. However if you ever figure it out I'd be personally curious to know what it was.

**Comment by jcbritobr** [comment]
I had this issue also. Then, we cant debug go code if it was linked with cgo?

**Comment by hiPsyDuck** [comment]
Have you solved the problem?

**Comment by jcbritobr** [comment]
> Have you solved the problem?

an update solved this issue.

**Comment by ArisAachen** [comment]
Since I update golang to newest version.
This issure occured 

go version go1.25.2 windows/amd64

**Comment by phantomnat** [comment]
For go 1.25, 
- Update the gcc to have newer binutil version (3.27 or newer).
- Or set this env `GOEXPERIMENT=nodwarf5` as the workaround.

Ref: https://github.com/golang/go/issues/75077

**Comment by o5h** [comment]
I had this issue after I upgraded go to 1.25.5
It was because I was using TDM-GCC-64.
Fixed by uninstalling TDM-GCC-64 and installing latest msys2-x86_64
