### ISSUE TITLE
Can't install Delve with certain ld versions

### ISSUE THREAD

**Issue by dino-ma** [go-delve/delve#2827]
`
[root@dino-ma soft]# go install github.com/go-delve/delve/cmd/dlv@master
go: downloading github.com/go-delve/delve v1.7.4-0.20211214142608-b81f618fb3aa
# github.com/go-delve/delve/cmd/dlv
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: /tmp/go-link-432756995/000008.o(.text+0x74): unresolvable Hø@>HFHøHÁïHÁè@~FÃHø@~HÁè8HøHÁè0FHøHÁè(FHøHÁè FHøHÁèFHøHÁèFHøHÁFÃfD relocation against symbol `stderr@@GLIBC_2.2.5'
/usr/bin/ld: BFD version 2.20.51.0.2-5.48.el6_10.1 20100205 internal error, aborting at reloc.c line 443 in bfd_get_reloc_size

/usr/bin/ld: Please report this bug.

collect2: ld returned 1 exit status

[root@dino-ma soft]# go version
go version go1.16.7 linux/amd64`

**Comment by aarzilli** [comment]
Googling around it looks like this is a bug in the version of ld you are using, setting CGO_ENABLE=0 should fix this.
@derekparker do we ignore this or do we switch back ebpf to being opt-in? I'm thinking we should wait to see if more people complain.

**Comment by derekparker** [comment]
> Googling around it looks like this is a bug in the version of ld you are using, setting CGO_ENABLE=0 should fix this. @derekparker do we ignore this or do we switch back ebpf to being opt-in? I'm thinking we should wait to see if more people complain.

That's my instinct as well, let's see if this continues to be a problem at a larger scale for folks and then decide.

**Comment by verdverm** [comment]
I got the following error today

```
github.com/go-delve/delve/pkg/proc/internal/ebpf
cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in $PATH
The command '/bin/sh -c go get -u github.com/go-delve/delve/cmd/dlv' returned a non-zero code: 2
```

Running `go install github.com/go-delve/delve/cmd/dlv@v1.7.1` looks to still work. I have not bisected to see when the gcc requirement was introduced.

**Comment by aarzilli** [comment]
@verdverm have you tried simply setting CGO_ENABLE=false?

**Comment by verdverm** [comment]
I have not. I did not expect a patch version change to break 'go get' or 'go install'
