### ISSUE TITLE
What does "*"  actually mean

### ISSUE THREAD

**Issue by Hansanshi** [go-delve/delve#2829]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?      1.7.3
2. What version of Go are you using? (`go version`)?    16.9
3. What operating system and processor architecture are you using?     macOS x86
4. What did you do? analyze coredump file
5. What did you expect to see?
6. What did you see instead?

I use delve to anayze coredump file of my golang program.
when I use command `goroutines` to list all goroutines, I find some special goroutine start with `*` like below

<img width="272" alt="9ec-854a-c80172f2a7af" src="https://user-images.githubusercontent.com/37737754/146485002-eea2ac52-53ff-4eb1-ad38-292bcf7d299c.png">

Now I know it's the goroutine crashed，but I wonder what `*` actually mean. I  didn't find explantion in the documentation.

**Comment by derekparker** [comment]
That is the "current" goroutine, in other words it's the goroutine that you are currently on in the debugger and the one that will be used for any command within the debugger.
