### ISSUE TITLE
"dlv trace" with "--ebpf" broken?

### ISSUE THREAD

**Issue by shadyabhi** [go-delve/delve#2845]
### Version info
```
 ➤ dlv version
Delve Debugger
Version: 1.8.0
Build: $Id: 6a6c9c332d5354ddf1f8a2da3cc477bd18d2be53 $

➤ go version
go version go1.16.2 linux/amd64
```
Picked a simple HTTP server example from https://gobyexample.com/http-servers

```bash
$ go build -o server
$ ./server # starts with PID 15671
```
### dlv trace usage

When I use `dlv trace`, I'm unable to initialize it. 

```
➤ dlv trace -p 15671 --ebpf
could not retrieve CFA for current PC

```

Just a sidenote, even if I don't use `--ebf`, it still fails to trace the program. 

```
 ➤ dlv trace -p 15671
could not find function net.isZeros
```

**Comment by derekparker** [comment]
Hm, not sure exactly what's happening here but I think it's related to misuse of the command. I think the command should print an error if you do not specify anything to trace.

What happens if you actually provide an argument?

**Comment by derekparker** [comment]
I was able to reproduce the `could not retrieve CFA for current PC` issue. I'll dig into it.
