### ISSUE TITLE
Support hardware breakpoint for linux/arm64

### ISSUE THREAD

**Issue by erifan** [go-delve/delve#2855]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
    tip
2. What version of Go are you using? (`go version`)?
    tip
3. What operating system and processor architecture are you using?
    linux/arm64
4. What did you do?
    $ dlv debug main.go
    $ watch XXX
5. What did you expect to see?
    The hardware breakpoint function works.
6. What did you see instead?
    Command failed: hardware breakpoints not implemented

**Comment by aarzilli** [comment]
Works for me, make sure you are not using an old version of delve.

**Comment by erifan** [comment]
Yes, it works. I thought I was using the latest dlv version. Thanks
