### ISSUE TITLE
High CPU use when *not* using `GODEBUG=asyncpreemptoff=1`

### ISSUE THREAD

**Issue by lberki** [go-delve/delve#2858]
When debugging my little binary, `dlv` sometimes uses 200% CPU and at the same time, the execution of the main binary slows to a crawl, sometimes to less than 10% of the usual execution time with Delve.

After some debugging, it turned out that the reason is that the Go runtime uses SIGURG to interrupt OS threads (I don't know under what circumstances) and since Delve uses ptrace, it has no choice but to be informed about these signals and since dealing with them takes time, the slowdown happens.

When attaching a debugger to Delve itself, one can clearly see that `trapWaitInternal()` gets called many times and `dbp.wait()` returns with "process stopped with signal SIGURG". In addition, bpftrace confirms that these signals to the code being debugged are in fact being sent, that Delve issues the `wait4()` system calls to be informed about them, that their return value indicates the signal and that there is no other activity between the two processes.

The obvious fix is to set `GODEBUG=asyncpreemptoff=1`, thereby disabling the preemption and thus the signals that cause trouble. I feel a bit uneasy about that, though, because the documentation for preemption:

https://github.com/golang/proposal/blob/master/design/24543-non-cooperative-preemption.md

makes me think that's a pretty well thought out feature and I'm not very certain that disabling it will be possible in the indefinite future and I don't fully understand the ramifications of doing so.

I guess I could figure out where those signals come from and what I can do about it (it's possible that it's e.g. memory pressure), but I'm not that familiar with Go and Delve should work with any binary, shouldn't it?

Unfortunately, I don't see a lot of other options since ptrace doesn't allow one to selectively be informed about signals. Maybe one could arrange for multiple threads in Delve to monitor the threads of the process being debugged, but I don't know if that's possible at all with ptrace. 

Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
HEAD (`fcc9561cbeb`)

2. What version of Go are you using? (`go version`)?
`go version go1.18beta1 linux/amd64`

3. What operating system and processor architecture are you using?
Linux, x86_64

4. What did you do?
5. What did you expect to see?
6. What did you see instead?
(see above)

**Comment by aarzilli** [comment]
> makes me think that's a pretty well thought out feature and I'm not very certain that disabling it will be possible in the indefinite future and I don't fully understand the ramifications of doing so.

If you have a loop that isn't preemptible (a loop that doesn't make function calls) it will make garbage collection pauses longer. There are several bad interactions between asynchronous preemption and debuggers: it slows down debugging too much on macOS and is disabled by default, it's completely incompatible with debugging on Windows (and it's disabled by default there too) and there are also problems on linux/arm64 with restartable instruction sequences, so we have disabled it there by default too.

AFAIK there are no plans of removing asyncpreemptoff. You are correct that everything that touches ptrace needs to happen in the same thread.

**Comment by lberki** [comment]
I see. I didn't realize that it's also problematic on Windows and mac OS. Then I feel better about my workaround.

**Comment by derekparker** [comment]
I'm going to close this as it's not necessarily a bug with Delve as there's no current workaround other than to disable async preemption.
