### ISSUE TITLE
Propose: "advance" command

### ISSUE THREAD

**Issue by thockin** [go-delve/delve#2861]
1. What version of Delve are you using (`dlv version`)?

```
$ dlv version
Delve Debugger
Version: 1.8.0
Build: $Id: 6a6c9c332d5354ddf1f8a2da3cc477bd18d2be53 $
```

2. What version of Go are you using? (`go version`)?

```
$ go version
go version go1.17 linux/amd64

$ gotip version
go version devel go1.18-b357b05b Thu Dec 23 20:03:38 2021 +0000 linux/amd64
```

3. What operating system and processor architecture are you using?

Linux AMD64

4. What did you do?

Wanted to advance to a particular line of code and then stop.  GDB has "advance" (I propose to alias it to "adv", also) which says `Continue the program up to the given location (same form as args for break command).`

I can fake it by setting a BP, continuing, then clearing the BP.  Would be nice for muscle-memory to use the same "adnavce"/"adv" command.

5. What did you expect to see?

An "adv"  command.

6. What did you see instead?

An error :)

**Comment by aarzilli** [comment]
Both this and the other one (break without arguments) are easy to implement in pkg/terminal/command.go.

**Comment by thockin** [comment]
Actually, I see that `cont <linespec>` is supported.  As much as my fingers would love an alias, I don't think we need every alias under the sun.
