### ISSUE TITLE
Cross platform core dump debugging not working

### ISSUE THREAD

**Issue by isbee** [go-delve/delve#2866]
I'm trying to debug linux core dump on windows but it doesn't work. When I do `dlv core LINUX_GO_BINARY LINUX_DUMP` on linux os(specifically which is EKS linux node) it works. I can see all working goroutines via `grs` command. On the other side, When I `do dlv core LINUX_GO_BINARY LINUX_DUMP` on windows/wsl it doesn't work. I also tried `dlv core WINDOWS_GO_BINARY LINUX_DUMP` and it's same.

All environments use go1.17.1 and dlv 1.8. Used same commit/go-binary/dump.
- For details, I used `go build -ldflags "-extldflags=-static"`. `GOOS` is different depend on OS.

The only difference is
1. OS
2. Only linux environment used 'plain' dump. Windows/WSL used tar/gz compressed dump. (decompressed before debugging)

But I don't think compression is problem so I think cross platform core dump debugging is not working.

***

1. What version of Delve are you using (`dlv version`)?
1.8

2. What version of Go are you using? (`go version`)?
1.17.1

3. What operating system and processor architecture are you using?
Linux (Amazon Linux) with x86_64
Windows10 with x86_64
WSL with x86_64

4. What did you do?
I do `dlv core LINUX_GO_BINARY LINUX_DUMP` and `grs` on each OS. Only linux works fine.

5. What did you expect to see?
I must can see working goroutines via `grs`. On linux(EKS amazon linux node) it works as expected.

```
[root@ip-xxxx dumps]# uname -m
x86_64
[root@ip-xxxx dumps]# cat /etc/os-release 
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/" 
[root@ip-XXXX dumps]# dlv core LINUX_GO_BINARY LINUX_DUMP
Type 'help' for list of commands.
(dlv) grs
 ...
  Goroutine 685 - User: /go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20210226220824-aa7126864d82/clientv3/watch.go:810 go.etcd.io/etcd/clientv3.(*watchGrpcStream).serveSubstream (0xe93e65) [select]
  Goroutine 686 - User: /go/pkg/mod/google.golang.org/grpc@v1.29.1/internal/transport/transport.go:186 google.golang.org/grpc/internal/transport.(*recvBufferReader).readClient (0xd9696a) [select]
  Goroutine 687 - User: /go/pkg/mod/google.golang.org/grpc@v1.29.1/stream.go:318 google.golang.org/grpc.newClientStream.func5 (0xdcf058) [select]
  Goroutine 688 - User: /go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20210226220824-aa7126864d82/clientv3/watch.go:810 go.etcd.io/etcd/clientv3.(*watchGrpcStream).serveSubstream (0xe93e65) [select]
  Goroutine 689 - User: /go/pkg/mod/google.golang.org/grpc@v1.29.1/internal/transport/transport.go:186 google.golang.org/grpc/internal/transport.(*recvBufferReader).readClient (0xd9696a) [select]
[145 goroutines]
(dlv)
```

6. What did you see instead?
When I do `dlv core LINUX_GO_BINARY LINUX_DUMP` or `dlv core WINDOWS_GO_BINARY LINUX_DUMP` on Windows/WSL and `grs`, I can't see goroutines.

WSL
```
$ dlv core LINUX_GO_BINARY LINUX_DUMP
Type 'help' for list of commands.
(dlv) grs
(dlv) grs
```

Windows
```
$ dlv core LINUX_GO_BINARY LINUX_DUMP
Type 'help' for list of commands.
(dlv) grs
Command failed: error while reading spliced memory at 0x546ca58: EOF
(dlv) exit

$ dlv core WINDOWS_GO_BINARY LINUX_DUMP
bad magic number '[77 90 144 0]' in record at byte 0x0
```

**Comment by aarzilli** [comment]
Strange, can you share the executables and core dumps?

**Comment by aarzilli** [comment]
By the way, what you are doing with `dlv core WINDOWS_GO_BINARY LINUX_DUMP` can not work, the executable you pass needs to be the one that produced the core dump.

**Comment by isbee** [comment]
> the executable you pass needs to be the one that produced the core dump.

According to the advice you gave, I copied the 'exact same' binary from EKS Pod's container, and `dlv core EKS_CONTAINER_LINUX_GO_BINARY LINUX_DUMP` works on both Windows/WSL. When I said 'same' go binary before, I meant a binary created using the same commit and `go build` command.

So the issue scope has been narrowed down a bit. Core dump debugging does not seem to work if `go build` environment is different, or the go binary must 'exact same' that produced the core dump, not just same commit and `go build` command. 

Which case is correct? If the former is correct, I'll give you more information about `go build` environment difference. 
- Success env
   - `go build -ldflags "-extldflags=-static"` on `golang:1.17.2-buster` based docker image. (`GOOS=linux`)
- Failure env
   - `go build -ldflags "-extldflags=-static"` on Windows/WSL. (`GOOS=windows` on Windows, `GOOS=linux` on WSL)
- Maybe `-ldflags "-extldflags=-static"` is the problem?

If latter is correct, is there a possibility that this restriction will be removed in the future?

**Comment by aarzilli** [comment]
This is not a bug. Core dumps do not contain enough information to be interpretable without the binary that produced them.
