### ISSUE TITLE
"debugging optimized function" warning

### ISSUE THREAD

**Issue by thockin** [go-delve/delve#2867]
1. What version of Delve are you using (`dlv version`)?

```
$ dlv version
Delve Debugger
Version: 1.8.0
Build: $Id: 6a6c9c332d5354ddf1f8a2da3cc477bd18d2be53 $
```

2. What version of Go are you using? (`go version`)?

```
$ go version
go version go1.17 linux/amd64

$ gotip version
go version devel go1.18-b357b05b Thu Dec 23 20:03:38 2021 +0000 linux/amd64
```

3. What operating system and processor architecture are you using?

Linux AMD64

4. What did you do?

I built my binary with `-gcflags "-N -l"`.  When I debug in delve, I still get "Warning: debugging optimized function".  I don't know if this is really impacting debug or not - there are sometimes when "next" jumps in weird ways or some local vars are not vailable.  Mostly I don't know why this is popping up or how to stop it.

5. What did you expect to see?

No error

6. What did you see instead?

"Warning: debugging optimized function"

**Comment by thockin** [comment]
Huh, I just found `-gcflags=“all=-N -l”` and that seems better - maybe delve should suggest it?

**Comment by aarzilli** [comment]
It's already documented in `go help build`. I don't see any obvious place where delve could suggest it.
