### ISSUE TITLE
Dlv with a plugin will err.

### ISSUE THREAD

**Issue by weatune** [go-delve/delve#2873]
The err is "plugin was built with a different version of package runtime/internal/sys".

1. dlv version 1.7.3
2. go version 1.16 and 1.17 all version.
3. os: debian, amd64.
4. I use command "go run ..." or "go build " no any problem.

I just in program start load a plugin, the plugin also is golang build, just little ".so".

**Comment by aarzilli** [comment]
Delve passes `-gcflags=all=-N -l` to `go build`, because of how plugin works the plugin needs to also be built like that.

**Comment by weatune** [comment]
@aarzilli, you are right, thank you!

**Comment by mxvsh** [comment]
is there any way to work with plugins while using dlv?
