### ISSUE TITLE
[Question] How do I debug always in assembly?

### ISSUE THREAD

**Issue by Jun10ng** [go-delve/delve#2878]
Hi team,
I debug a `.go` file and I hope the source code it displays always is assembly.
The steps I did it now:
```
$ step-instruction
// output a lot of golang code.
$ disass
// output assembly.
```

I want:
```
$ step-instruction
// output assembly directly.
```

Is there any flag that can help me save `disass` command?

**Comment by aarzilli** [comment]
Not currently.

**Comment by aarzilli** [comment]
PS. the code for the command line client is in pkg/terminal/command.go, see `stepInstruction`.
