### ISSUE TITLE
Delve goes into infinity loop with the debug command

### ISSUE THREAD

**Issue by rfc2119** [go-delve/delve#2884]
1. What version of Delve are you using (`dlv version`)?
> Version: 1.8.0
> Build: $Id: 6a6c9c332d5354ddf1f8a2da3cc477bd18d2be53 $

2. What version of Go are you using? (`go version`)?
> go1.16.6 linux/amd64

3. What operating system and processor architecture are you using?
> Linux main 5.13.0-27-generic #29~20.04.1-Ubuntu SMP Fri Jan 14 00:32:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

4. What did you do?
This my first time using Delve. I cloned [this repository](https://github.com/charmbracelet/glow) and simply ran `dlv debug`

5. What did you expect to see?
I am new to Delve. Probably a gdb-like prompt.

6. What did you see instead?
Delve refuses to start and my CPU usage grows exponentially (it takes 15 seconds to get to 700%). It seems Delve goes into an infinite loop, drawing all my resources. Using `--log --log-dest dlv.log` did not yield any output. I am clueless on how to debug this

**Comment by derekparker** [comment]
Thanks for filing this report.

I've tested locally and it's not Delve which is hitting an infinite loop but likely the `glow` program itself. When I reproduce this locally with `dlv debug` I try and continue to `main.main` and I never reach it. This is because `glow` has some code in `init` functions (or a dep does) and so I end up seeing the following backtrace:


```
 0  0x00000000004df97b in syscall.Syscall
    at /usr/local/go/src/syscall/asm_linux_amd64.s:26
 1  0x00000000005c3d98 in golang.org/x/sys/unix.ioctl
    at /home/deparker/go/pkg/mod/golang.org/x/sys@v0.0.0-20210113181707-4bcb84eeeb78/unix/zsyscall_linux.go:41
 2  0x00000000005c393d in golang.org/x/sys/unix.IoctlSetTermios
    at /home/deparker/go/pkg/mod/golang.org/x/sys@v0.0.0-20210113181707-4bcb84eeeb78/unix/ioctl.go:48
 3  0x000000000060041d in github.com/muesli/termenv.termStatusReport
    at /home/deparker/go/pkg/mod/github.com/muesli/termenv@v0.8.1/termenv_unix.go:189
 4  0x00000000005ff7eb in github.com/muesli/termenv.backgroundColor
    at /home/deparker/go/pkg/mod/github.com/muesli/termenv@v0.8.1/termenv_unix.go:65
 5  0x00000000005ff0e7 in github.com/muesli/termenv.BackgroundColor
    at /home/deparker/go/pkg/mod/github.com/muesli/termenv@v0.8.1/termenv.go:50
 6  0x00000000005ff15e in github.com/muesli/termenv.HasDarkBackground
    at /home/deparker/go/pkg/mod/github.com/muesli/termenv@v0.8.1/termenv.go:55
 7  0x000000000061198c in github.com/charmbracelet/charm/ui/common.init
    at /home/deparker/go/pkg/mod/github.com/charmbracelet/charm@v0.8.6/ui/common/common.go:17
 8  0x0000000000448cc7 in runtime.doInit
    at /usr/local/go/src/runtime/proc.go:6498
 9  0x0000000000448c19 in runtime.doInit
    at /usr/local/go/src/runtime/proc.go:6475
10  0x000000000043bbb4 in runtime.main
    at /usr/local/go/src/runtime/proc.go:238
11  0x000000000046a801 in runtime.goexit
    at /usr/local/go/src/runtime/asm_amd64.s:1581
```

Since `glow` is a terminal gui based program I'd imagine it and Delve are fighting over the terminal. What I was able to do in order to successfully debug the `glow` program was to start Delve in headless mode and then connect to it from another terminal. See [the documentation](https://github.com/go-delve/delve/blob/master/Documentation/faq.md#how-can-i-use-delve-to-debug-a-cli-application) for more information on using this technique.

**Comment by rfc2119** [comment]
Thank you Derek for your input.

I don't know why, but on my machine `dlv debug --headless` bugs out as well o. it gives the same behavior as `dlv debug` and `go build -gcflags=all="-N -l"` (suggested by [vscode-go docs](https://github.com/golang/vscode-go/blob/master/docs/debugging.md#connecting-to-delve-dap-with-target-specified-at-client-start-up)) which is: consume all my memory+swap till my PC freezes. I will try to figure this out.

**Comment by derekparker** [comment]
> Thank you Derek for your input.
> 
> I don't know why, but on my machine `dlv debug --headless` bugs out as well . It gives the same behavior as `dlv debug` and `go build -gcflags=all="-N -l"` (suggested by [vscode-go docs](https://github.com/golang/vscode-go/blob/master/docs/debugging.md#connecting-to-delve-dap-with-target-specified-at-client-start-up)) which is: consume all my memory+swap till my PC freezes. I will try to figure this out.

Hm, that's really interesting. Can you get any more info on what Delve is doing while it's hanging and what's causing it to eat up so much memory? I can't reproduce this locally.

**Comment by aarzilli** [comment]
If it happens with `go build` then delve is just waiting on `go build`.

**Comment by rfc2119** [comment]
Hi, `go build` builds ok, but `go build -gcflags=all="-N -l"` eats up all of my RAM. If Delve builds the binary with the custom GC flags (I don't know if it does), then that's probably the reason. Here's a [recording](https://asciinema.org/a/P61tpIUcpx0ek68XoJZhDasE8). TBH, I am not sure why building with custom GC flags needs all this memory

_Note_: near the end of the recording, my terminal frozen. In other recordings, all of the swap memory gets drawn out as well

**Comment by aarzilli** [comment]
delve does use `-gcflags='all=-N -l'` to build. If you can reproduce this with a more recent version of go it could be worth reporting to golang/go.

**Comment by rfc2119** [comment]
Any clue on what debug/log flags to pass ?

**Comment by aarzilli** [comment]
`-x` will tell you what `go build` is doing.
