### ISSUE TITLE
could not launch process: fork/exec in Ubuntu 20.04

### ISSUE THREAD

**Issue by antonvlasov** [go-delve/delve#2886]
### Versions
Delve Debugger
Version: 1.8.0
Build: $Id: 6a6c9c332d5354ddf1f8a2da3cc477bd18d2be53 $
go1.17.6 linux/amd64
Ubuntu 20.04.3 LTS (Focal Fossa)

### Actions
When debugging in vscode with following config I get  an error.
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Package",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${fileDirname}"
        }
    ]
}
```
```could not launch process: fork/exec /tmp/__debug_bin1874603807: operation not permitted```
Executing files from /tmp is allowed, it is not the issue.

I get similar result with running dlv from terminal:

```
user@my-machine:~/test$ /home/user/go/bin/dlv debug
could not launch process: fork/exec /home/user/test/__debug_bin: operation not permitted
```

### What I have tried to fix it

- Setting ```kernel.yama.ptrace_scope = 0``` in ```/etc/sysctl.d/10-ptrace.conf``` - it does not help.

- Running as root:

```
user@my-machine:~/test$ su root
Password: 
root@my-machine:/home/user/test# export PATH=$PATH:/usr/local/go/bin
root@my-machine:/home/user/test# go version
go version go1.17.6 linux/amd64
root@my-machine:/home/user/test# ../go/bin/dlv debug
Type 'help' for list of commands.
(dlv) quit
```
The error does not happen but I want to be able to debug as non-root with vscode.

- Reinstalling dlv :
Deleting dlv binary and running ```go install github.com/go-delve/delve/cmd/dlv@latest``` does not help.

### Expectations
Being able to debug go program.

**Comment by aarzilli** [comment]
If this is docker or something like it you probably need to add some capability.

**Comment by aarzilli** [comment]
Alternatively it could be that there's a problem with apparmor configuration.

**Comment by antonvlasov** [comment]
This is not docker.
I have figured out that setting ```kernel.yama.ptrace_scope = 0``` did not work for some reason, however ```echo 0 > /proc/sys/kernel/yama/ptrace_scope``` helped.
