### ISSUE TITLE
service/dap: `dlv config` should print existing configuration, not panic

### ISSUE THREAD

**Issue by polinasok** [go-delve/delve#2889]
I keep thinking that `dlv config`, not `dlv config -list` is the command to list all current configuration values.
With dlv@v1.7.3:
![image](https://user-images.githubusercontent.com/51177946/152393348-891c1f94-a75a-42b4-99af-b5a1e1ea8d79.png)

With dlv@v1.8.0 and dlv@latest:
![image](https://user-images.githubusercontent.com/51177946/152393607-e011e649-44b0-4317-bb0b-479caf80b10a.png)

@suzmue

**Comment by aarzilli** [comment]
Fixed by 13ad7dc1d581b86d7000f6fc4bd37309c30ec480

**Comment by nyngwang** [comment]
@aarzilli I still have this problem.
