### ISSUE TITLE
Support debugging Go executable stripped from symbols using information from pclntab

### ISSUE THREAD

**Issue by tymonx** [go-delve/delve#2899]
It should be possible to retrieve debug information from internal [pclntab](https://go.dev/src/debug/gosym/pclntab.go) table built in executable even after striping it from debug symbols. This table is always present in executable because it used by the `runtime` package.

1. What version of Delve are you using (`dlv version`)?

```plaintext
1.8.0
```

2. What version of Go are you using? (`go version`)?

```plaintext
1.17.5
```

3. What operating system and processor architecture are you using?

```plaintext
Linux Fedora 35 Kinoite, AMD64
```

4. What did you do?

Strip executable from debug symbols:

```plaintext
go build -ldflags '-s -w' -trimpath -o <name> <file>.go
```

Run it via Delve:

```plaintext
dlv exec ./<name>
```

5. What did you expect to see?

```plaintext
Type 'help' for list of commands.
(dlv)
```

6. What did you see instead?

```plaintext
could not launch process: could not open debug info
```

**Comment by aarzilli** [comment]
It isn't worth doing, we'd take a dependency on a lot of internal details of the compiler/runtime and the only thing we could do is stack traces.
