### ISSUE TITLE
dlv exec ./app error layer=debugger can't find build-id note on binary Type 'help' for list of commands.

### ISSUE THREAD

**Issue by jessezax** [go-delve/delve#2909]
dlv exec ./app
2022-02-20T12:59:49+08:00 error layer=debugger can't find build-id note on binary
Type 'help' for list of commands.

and list can't show code

**Comment by aarzilli** [comment]
That message is not relevant and list can't show your code is because the paths recorded in the executable don't match your local file system. See `help config` the part about `substitute-path`.
