### ISSUE TITLE
duplicate symbol reference

### ISSUE THREAD

**Issue by Southclaws** [go-delve/delve#2917]
Trying to debug a test via VS Code on Windows 11, it did work at some point but today I was hit with this:

```
[C:/Program]() Files/TDM-GCC-64/bin/.[./lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/lib/../lib/libmsvcrt.a]()(/2203): duplicate symbol reference: _unlock_file in both libgcc(.text) and libgcc(.data)
libgcc(.text): relocation target atexit not defined (exit status 2)
```

No idea where to start, can't find any mention of this error in any issues or discussions. Resorting to printf for now but I'd really appreciate some help with this one as I rely heavily on step-through debugging.

Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

Delve version:
```
Version: 1.8.1
Build: $Id: d85f1f6b736db99a1c239c34fd4a081dcff08a3c $
```

Go version:
```
go version go1.17.7 windows/amd64
```

Environment:
- Windows 11 22000.434
- AMD64/x86_64
- The error mentions gcc and mingw for some reason so I guess here's a version I managed to get from mingw-make:
  ```
  gcc.exe (tdm64-1) 10.3.0
  GNU Make 3.82.90
  Built for i686-pc-mingw32
  ```
  (Shouldn't this be using native Windows tooling not this GNU stuff? I'm not even entirely sure why I have it installed)

**Comment by aarzilli** [comment]
This probably doesn't have anything to do with delve, it's a linker error and it's probably caused by something in the C toolchain, see https://github.com/golang/go/issues/47119 and related issues. It's also possible that it only happens for some values of CGO_CFLAGS, delve sets it to `-O0 -g`, other values may work better.
