### ISSUE TITLE
Delve intermittently crashes running multiple debuggers in vscode

### ISSUE THREAD

**Issue by mrjrieke** [go-delve/delve#2931]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
  Delve Debugger
  Version: 1.8.0
  Build: $Id: 6a6c9c332d5354ddf1f8a2da3cc477bd18d2be53 $

2. What version of Go are you using? (`go version`)?
   go version go1.17.8 linux/amd64
4. What operating system and processor architecture are you using?
   #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux
6. What did you do?
   Using two debuggers simultaneously trigger exception stack trace below.
8. What did you expect to see?
   No stack trace
10. What did you see instead?

Stack trace:
2022-03-16T05:52:31-07:00 error layer=dap recovered panic: runtime error: invalid memory address or nil pointer dereference
goroutine 7 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/go-delve/delve/service/dap.(*Session).recoverPanic(0xc0002b8000, {0xb0b7c0, 0xc005e6f3b0})
	/home/<redacted>/delve/service/dap/server.go:559 +0x66
panic({0x9a92c0, 0xe5dcb0})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/go-delve/delve/service/dap.(*Session).onScopesRequest(0xc0002b8000, 0xc005e6f3b0)
	/home/<redacted>/delve/service/dap/server.go:2060 +0x8d5
github.com/go-delve/delve/service/dap.(*Session).handleRequest(0xc0002b8000, {0xb0b7c0, 0xc005e6f3b0})
	/home/<redacted>/delve/service/dap/server.go:762 +0x14be
github.com/go-delve/delve/service/dap.(*Session).ServeDAPCodec(0xc0002b8000)
	/home/<redacted>/delve/service/dap/server.go:545 +0x3b0
github.com/go-delve/delve/service/dap.(*Server).runSession(0xc0001c3590, {0x7fb0245d2458, 0xc000010620})
	/home/<redacted>/delve/service/dap/server.go:482 +0xc5
github.com/go-delve/delve/service/dap.(*Server).Run.func1()
	/home/<redacted>/delve/service/dap/server.go:474 +0x118
created by github.com/go-delve/delve/service/dap.(*Server).Run
	/home/<redacted>/delve/service/dap/server.go:456 +0x66

**Comment by mrjrieke** [comment]
This could be improper launch of delve... but an error output rather than a crash might be nice.

**Comment by polinasok** [comment]
@mrjrieke  Thank you for your report.

What do you mean by "Using two debuggers simultaneously"?
What do your launch configurations look for these sessions?
Is it by any chance possible to isolate this into something we can reproduce on our own?
