### ISSUE TITLE
Duplicate / in paths are not stripped

### ISSUE THREAD

**Issue by nicoche** [go-delve/delve#2939]
Hi!

First, thanks for working on delve.

This issue is probably in between a bug and a feature request. Basically, it happens to me often to copy-paste some path to a file where I want to put a breakpoint in and sometimes, a duplicate `/` finds its way in there.

With most unix tools, duplicate paths are stripped (e.g. `cd /tmp//test` == `cd /tmp/test`). GDB and Delve do not do that out of the box.

What do you think, would it be something you are willing to add to delve? If yes, how easy would it be to implement?

_________

1. What version of Delve are you using (`dlv version`)? 

```
$ dlv version
Delve Debugger
Version: 1.7.1
Build: $Id: 3bde2354aafb5a4043fd59838842c4cd4a8b6f0b $
```

2. What version of Go are you using? (`go version`)?

```
$ go version
go version go1.17.2 darwin/amd64
```

3. What operating system and processor architecture are you using?

```
$ uname -a
Darwin Nicolass-MBP 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:34:37 PST 2022; root:xnu-8020.101.4~2/RELEASE_X86_64 x86_64
```

4. What did you do?

```
dlv debug main.go
Type 'help' for list of commands.
(dlv) funcs SomeFunc
example.com/m/pkg/accounts.SomeFunction
(dlv) break example.com/m/pkg//accounts.SomeFunction
Command failed: location "example.com/m/pkg//accounts.SomeFunction" not found
(dlv) break example.com/m/pkg/accounts.SomeFunction
Breakpoint 1 set at 0x10abc06 for example.com/m/pkg/accounts.SomeFunction() ./pkg/accounts/accounts.go:7
```

5. What did you expect to see?

```
$ dlv debug main.go
Type 'help' for list of commands.
(dlv) funcs SomeFunc
example.com/m/pkg/accounts.SomeFunction
(dlv) break example.com/m/pkg//accounts.SomeFunction
Command failed: location "example.com/m/pkg//accounts.SomeFunction" not found
(dlv) break example.com/m/pkg/accounts.SomeFunction
Breakpoint 1 set at 0x10abc06 for example.com/m/pkg/accounts.SomeFunction() ./pkg/accounts/accounts.go:7
```

6. What did you see instead?

```
(dlv) funcs SomeFunc
example.com/m/pkg/accounts.SomeFunction
(dlv) break example.com/m/pkg//accounts.SomeFunction
Breakpoint 1 set at 0x10abc06 for example.com/m/pkg/accounts.SomeFunction() ./pkg/accounts/accounts.go:7
```

**Comment by aarzilli** [comment]
Closing, I don't think this feature should be implemented.
