### ISSUE TITLE
tmoe linux over android not supported

### ISSUE THREAD

**Issue by ddkwork** [go-delve/delve#2983]
dlv 1.8.2 not work on arm64 Linux with go 1.18，please see this video。

https://b23.tv/lztH90n

**Comment by aarzilli** [comment]
Does this happen with every program or just with one program in particular? If it's a particular program it would be useful to see its source code, otherwise you will have to instrument delve yourself and see where it gets stuck. We do test delve on linux/arm64 and it does not get stuck.

**Comment by ddkwork** [comment]
Every app



---Original---
From: "Alessandro ***@***.***&gt;
Date: Fri, Apr 22, 2022 13:52 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [go-delve/delve] arm64 not work (Issue #2983)




 
Does this happen with every program or just with one program in particular? If it's a particular program it would be useful to see its source code, otherwise you will have to instrument delve yourself and see where it gets stuck. We do test delve on linux/arm64 and it does not get stuck.

**Comment by aarzilli** [comment]
In that case we can not reproduce your issue.

**Comment by ddkwork** [comment]
Can you pad some time install termux and manjaro linux on Android mobile for test dedlv 1.8.2? This is steps:
1 install termux
2 run this bash command on termux windows


[[ $(command -v curl) ]] || sudo pacman -Syu curl
&nbsp; &nbsp; bash -c "$(curl -L https://gitee.com/mo2/linux/raw/2/2)"


And do some choose by that ui interfere,
Then you will get a arm64 arch or manjaro linux on your Android mobile phone.


3 create some go mod project and debug them with delve or goland, you can found you can not debug any project.



---Original---
From: "Alessandro ***@***.***&gt;
Date: Fri, Apr 22, 2022 14:23 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [go-delve/delve] arm64 not work (Issue #2983)




 
In that case we can not reproduce your issue.

**Comment by aarzilli** [comment]
Delve works on a normal install of linux on arm64, if it doesn't specifically under tmoe-linux then it's a bug with tmoe-linux, not with delve.
I'm not sure what they are doing to run linux on top of android and their documentation doesn't say. If they are using qemu it can not work, if they are using docker or something similar they might just be missing some capabilities.
It could be interesting to see if gdb works.

**Comment by ddkwork** [comment]
Gdb and lldb worked. Tome linux used a proot container like docker. I was tested gdb and lldb in clion debug, that's work well.



---Original---
From: "Alessandro ***@***.***&gt;
Date: Fri, Apr 22, 2022 14:49 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [go-delve/delve] arm64 not work (Issue #2983)




 
Delve works on a normal install of linux on arm64, if it doesn't specifically under tmoe-linux then it's a bug with tmoe-linux, not with delve.
 I'm not sure what they are doing to run linux on top of android and their documentation doesn't say. If they are using qemu it can not work, if they are using docker or something similar they might just be missing some capabilities.
 It could be interesting to see if gdb works.

**Comment by ddkwork** [comment]
this is install steps, if you can try


https://b23.tv/PKzfPdC


Thank you.



---Original---
From: "Alessandro ***@***.***&gt;
Date: Fri, Apr 22, 2022 14:49 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [go-delve/delve] arm64 not work (Issue #2983)




 
Delve works on a normal install of linux on arm64, if it doesn't specifically under tmoe-linux then it's a bug with tmoe-linux, not with delve.
 I'm not sure what they are doing to run linux on top of android and their documentation doesn't say. If they are using qemu it can not work, if they are using docker or something similar they might just be missing some capabilities.
 It could be interesting to see if gdb works.

**Comment by ddkwork** [comment]
> Delve works on a normal install of linux on arm64, if it doesn't specifically under tmoe-linux then it's a bug with tmoe-linux, not with delve.
> I'm not sure what they are doing to run linux on top of android and their documentation doesn't say. If they are using qemu it can not work, if they are using docker or something similar they might just be missing some capabilities.
> It could be interesting to see if gdb works.
> 

Please install this for test

https://www.aidlux.com/apk/AidLux_1.1_Free.apk

More info

https://www.aidlux.com/product
