### ISSUE TITLE
proc: flag register corruption after call injection on amd64

### ISSUE THREAD

**Issue by ohir** [go-delve/delve#2985]
```
Delve Version: 1.8.2
Build: $Id: dbb493ec14d1e7753504d016b1e1ef1665b75b16 $
go version go1.18.1 darwin/amd64
MacOS 12.3 Monterey/amd64
Delve via VSCode frontend v1.66.2 (Go extension: v0.32.0)
gopls@v0.8.3 h1:Mxm94ix8oSARQ6svioO6SxKEYWT/VCP54/448LOHzrk=
```
5. What did you do?
In debug session (with Visual Studio Code frontend) while stepping through code I noticed that delve steps into the `if false { block }` (ie. steps into despite of conditional expression evaluating to false).

6. What did you expect to see?
block being omitted due to the `if` condition being `false`

7. What did you see instead?
debugger stepped into the block.

-- formalities done, now real description:

(5) In bigger (pure Go) project while debugging bitmap based filter I noticed (7) that step by step execution entered into the if block where it should not (6). 

- on the normal run, ie. going between breakpoints, this block is *not* entered.
- if stepped by, delve enters into the block despite `if` condition being `false`.

Unfortunately I could not make delve behave this way with minimal reproduction code, so I am filling this issue mostly for future reference. Filter carved out to a command (and decorated with explicit locals per each part of condition separately) reproduced this behavior - to be seen as screenshot:

![dlvBoolExprBug](https://user-images.githubusercontent.com/12509338/164700131-18041eac-3934-4712-a2bc-b2e36e8ad53c.jpg)

[Here is](https://gist.github.com/ohir/9f633f411305b5dd164ec12626afadf9) my unsuccessful try to get at minimal reproduction code, the crux in below snippet:

``` go
func Atest(a uint32) {
	// on this kind (short-circuited ors) debugger entered
	// in "true" block with all three parts being false (see pic)
	if a>>16 != 0xE0D0 ||
		Bms.b2[((a>>8)&b4m)] == 0 ||
		Bms.b3[Bms.b2[(a>>8)&b4m]]&(1<<(a&b6m)) == 0 {
		fmt.Printf("%08x !match by || short ciruit\n", a)
	}
	// on short-circuited ands debug worked ok
	if a>>16 == 0xE0D0 &&
		(Bms.b2[((a>>8)&b4m)] != 0) &&
		Bms.b3[Bms.b2[(a>>8)&b4m]]&(1<<(a&b6m)) != 0 {
		fmt.Printf("%08x  match by && short ciruit\n", a)
	}
}
```
*Note that this minimal code does **not** reproduce the bug I've seen as on the screenshot above*.

--
Edits: Go and VCS versions update

**Comment by aarzilli** [comment]
Also is the code really executed or does it just look like it is being executed? Will it actually panic?
It could be that the compiler assigned the wrong line number to an instruction (you'd have to look at a disassembly to determine if this is the case).

**Comment by ohir** [comment]
> is the code really executed

Yes. It really executed this panic.
I just refreshed all components, ie. Go updated to `1.18.1` and VSCode to `1.66.2`, and checked again.
Still step by step enters into the block and executes panic.

**Comment by ohir** [comment]
[Here is](https://gist.github.com/ohir/1ecfa5ee4308decd9aca5278958043fa) disassembly of `if` block seen on the screenshot.

**Comment by ohir** [comment]
Ok, as I needed to go on cli for disassembly, i stepped through in the cli.
And - surprise - the CLI delve did **not** stepped into the block.
So culprit is either somewhere in the socket version, or possibly because of some weird things gopls said.

**Comment by aarzilli** [comment]
Interesting, can you post the logs output by adding `logOutput: "dap"` to launch.json?

cc @polinasok

**Comment by ohir** [comment]
Update on the hunt:
After removing all watchers (many of them unresolvable in current debug session context) delve no longer misbehaves. Now I am trying to bisect which single one may trigger the bug.
Will post both - misbehaving and ok - logs for diffing soon (where soon could be tomorrow).

**Comment by aarzilli** [comment]
Were any of those logpoints or function calls?

**Comment by ohir** [comment]
No logs needed. I've nailed it. Below is the minimal repro code:

``` go
package main

func main() {
	if InMap(3771728130) {
		println("3771728130 is there!")
	}
	if NotInMap(3771728130) {
		println("3771728130 is Not there!")
	}
}

// add call InMap(a) watch to unearth the bug
func InMap(a uint32) bool {
	return a>>16 == 0xE0D0 && a&255 == 2
}

func NotInMap(a uint32) bool {
	x1 := a>>16 != 0xE0D0
	x2 := a&255 != 2
	if x1 || x2 {
		println("x1 || x2 true!")
	}
	// condition in at least two lines activates
	// bug via call to the InMap(a) watch (returns ~r0: true)
	if a>>16 != 0xE0D0 ||
		a&255 != 2 {
		println("False recognized as true!")
		return true // not in map
	}
	return false // in map
}
```

The bug's origin is in the ~r0 being set to true by each call to InMap(a) - then this result is mistakenly used within the step logic. Confirmed with cli:

```
> main.NotInMap() ./dlvbug.go:27 (PC: 0x105a13a)
    22:		}
    23:		// condition in at least two lines activates
    24:		// bug via call to the InMap(a) watch
    25:		if a>>16 != 0xE0D0 ||
    26:			a&255 != 2 {
=>  27:			println("False recognized as true!")
    28:			return true // not in map
    29:		}
    30:		return false // in map
    31:	}
```

**Comment by polinasok** [comment]
This reminds me of #2593 and subsequent bug against the Go compiler https://github.com/golang/go/issues/47260.

**Comment by ohir** [comment]
@polinasok, @aarzilli 
This is more severe. 
**Any** call watcher breaks the step logic. With PoB code below set breakpoint at `a:=4`, set watcher `call ck(a)`, then see debug session stepping into the second case:

``` go
package main

var Res int

func main() {
	a := 4 // set breakpoint here
	switch {
	case a < 1 &&
		a/2 > 0:
		println("<1")
		ck(a)
	case a < 2 &&
		a/2 > 0:
		println("<2") // you step here
		ck(a)
	case a < 5 &&
		a/2 > 1:
		println("<5")
		ck(a)
	}
	println(">3")
	ck(a)
}

func ck(a int) string {
	Res = a
	return "call done"
}
```
