### ISSUE TITLE
Is there a switch make dlv execute step, continue stop show the source info ?

### ISSUE THREAD

**Issue by loyalpartner** [go-delve/delve#3016]
Please answer the following before submitting your issue:

I write a vim plugin [loyalpartner/termdebug-go: termdebug for golang](https://github.com/loyalpartner/termdebug-go/tree/main), it can fllow the vim's code, so i want the dlv process stop show source list when i run next,step, continue command, Is there a switch make dlv execute step, continue stop show the source info ?

![image](https://github.com/loyalpartner/termdebug-go/raw/main/images/display.gif)

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

If this is about source listing not showing up (or breakpoints not being
accepted) while running in a container please read our
[FAQ](https://github.com/go-delve/delve/blob/master/Documentation/faq.md#substpath)
first.

1. What version of Delve are you using (`dlv version`)?
2. What version of Go are you using? (`go version`)?
3. What operating system and processor architecture are you using?
4. What did you do?
5. What did you expect to see?
6. What did you see instead?

**Comment by aarzilli** [comment]
source-list-line-count changes the number of lines printed but it will always print at least one.

**Comment by loyalpartner** [comment]
@aarzilli thank you

Accoding to your hint

1. find $HOME/.config/dlv/config.toml
2. uncoment source-list-line-count and set value = 0
