### ISSUE TITLE
can not install dlv in ubuntu with go 1.18.2, cgo_export.c:3:10: fatal error: s

### ISSUE THREAD

**Issue by yudar1024** [go-delve/delve#3018]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

If this is about source listing not showing up (or breakpoints not being
accepted) while running in a container please read our
[FAQ](https://github.com/go-delve/delve/blob/master/Documentation/faq.md#substpath)
first.

1. What version of Delve are you using (`dlv version`)?
latest
3. What version of Go are you using? (`go version`)?
go version 1.18.2
4. What operating system and processor architecture are you using?
ubuntu
6. What did you do?
```
git clone https://github.com/go-delve/delve/cmd/dlv
cd delve
go install github.com/go-delve/delve/cmd/dlv
# github.com/go-delve/delve/pkg/proc/internal/ebpf
_cgo_export.c:3:10: fatal error: stdlib.h: No such file or directory
    3 | #include <stdlib.h>
      |          ^~~~~~~~~~
compilation terminated.
```
8. What did you expect to see?
install success
10. What did you see instead?
cgo_export.c:3:10: fatal error: s

**Comment by aarzilli** [comment]
You can either install the build-essential package or set the CGO_ENABLED environment variable to 0.
