### ISSUE TITLE
MacOS Brew installation

### ISSUE THREAD

**Issue by shivan-s** [go-delve/delve#3037]
Hello all, 

Sorry to deviate from the recommended issue format. However, I just want to make a small change to the documentation in regards to macOS installation.

I'm running M1 architecture and I think the best way to install is using brew:
```shell
brew install dlv
```

I think this should be added to the docs (even though it's quite obvious). A reason being is that I tried the way mentioned in the current documentation and it wants to run the Rosetta version, which won't work if you have Go installed for ARM architecture (I think).

Thanks in advance.

**Comment by aarzilli** [comment]
We used to mention homebrew but then the old formula became unmaintained and we removed it. We could re-add it now that it is being maintained again, I'm not sure where.

**Comment by shivan-s** [comment]
Excellent thanks for your quick response. I wasn't aware of the history! 

(Apologies I only had a quick glance at the issues).

Let's see what others think?

**Comment by derekparker** [comment]
Looks like this homebrew formula is being actively maintained still:

```
==> delve: stable 1.9.1 (bottled)
Debugger for the Go programming language
https://github.com/go-delve/delve
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/delve.rb
License: MIT
```

I'll add it back to the docs.
