### ISSUE TITLE
dap: out of memory disassembly view CGo program

### ISSUE THREAD

**Issue by ii64** [go-delve/delve#3040]
<details><summary>
1. Delve version:
</summary>

```
Delve Debugger
Version: 1.8.3
Build: $Id: f92bb46b82b3b92d79ce59c4b55eeefbdd8d040c $
```
</details>

<details><summary>
2. Go version, and my OS:
</summary>

```
go version go1.18.3 linux/amd64
Ubuntu 22.04 - GNU/Linux 5.16.17 AMD64
```
</details>

<details><summary>
4. What did you do?
</summary>

Debugging pre-compiled Go program `-gcflags="all=-N -l"`, irst try works just fine, but second one DAP crashed because it's trying to allocate huge block of bytes.

I don't know for sure what causes the `endAddr` to be that big:
```
startAddr: 0x47dc20
endAddr: 0x7f6ab2faf700
```
https://github.com/go-delve/delve/blob/35d4f05c4eca61dcb714108d23bc9e9b5264d43e/pkg/proc/disasm.go#L136

main code:
```go
package main

/*
int a(int v) {
	return 0xff + v;
}
*/
import "C"
import "fmt"

func main() {
	fmt.Println("aaa")
	print(C.a(11))
}
```

</details>

<details><summary>
5. What did you expect to see?
</summary>

Don't crash.
</details>

<details><summary>
6. OOM crash, logs and crash traceback:
</summary>

https://gist.github.com/ii64/f48b9ee63d0bf0a8a550a9e41c83d57d
</details>

**Comment by aarzilli** [comment]
Nevermind, I've figured out why I can't reproduce it.
