### ISSUE TITLE
Unable to debug plugin within precompiled binary using dlv exec

### ISSUE THREAD

**Issue by tomglenn** [go-delve/delve#3042]
1. What version of Delve are you using (`dlv version`)?

1.8.3

2. What version of Go are you using? (`go version`)?

1.16

3. What operating system and processor architecture are you using?

Running inside a linux/amd64 docker container (I read the FAQs, the suggestions there didn't seem to help with my issue)

4. What did you do?

I have a precompiled binary and a precompiled Go plugin (as a `.so` file) which the binary loads at runtime.
Both are compiled with `--gcflags "all=-N -l"`.

In the source for my plugin I have a `main.go` file with an `RpcTest` function, which I can execute via a web interface that the main binary exposes at runtime.

When executing `dlv exec /path/to/binary` and trying to set a `break RpcTest` the function is not found. I also cannot see that plugin's `main.go` file when doing `sources main.go`; instead I only see the `main.go` for the main binary itself.

After reading this issue (https://github.com/go-delve/delve/issues/1653) I have also attempted to set a breakpoint in the main binary and `continue` execution up to the point where the plugin would have been loaded. Again running `sources` I still do not see anything that looks like it belongs to the plugin.

5. What did you expect to see?

Sources belonging to the plugin when running the `sources` command and the ability to set a `break` on code within the plugin.

6. What did you see instead?

No trace of anything related to my plugin when running `sources` and running `break RpcTest` returns `location "RpcTest" not found`.

When doing a `dlv exec /path/to/binary` I do see this in the logs which may or may not be relevant:

```
2022-06-22T09:55:51Z warning layer=debugger reading debug_info: concrete subprogram without address range at 0x9b50b4
2022-06-22T09:55:51Z warning layer=debugger reading debug_info: concrete subprogram without address range at 0x9b50c0
2022-06-22T09:55:51Z warning layer=debugger reading debug_info: concrete subprogram without address range at 0x9b50cd
... (a lot more lines like these)
```

**Comment by aarzilli** [comment]
Did delve find the plugin? What's the output of `libraries` **after** the plugin has been loaded? Those log lines aren't relevant.

**Comment by aarzilli** [comment]
Is there a simple reproducer for this? We have tests for debugging plugins and they work.

**Comment by tomglenn** [comment]
Hi @aarzilli apologies for the delay in getting back to you. I have created a repo to reproduce my exact scenario https://github.com/tomglenn/dlv-remote-reproducer

**Comment by aarzilli** [comment]
Sure enough if I create /data/modules and copy backend.so there I get this:

```
{"level":"info","ts":"2022-06-28T15:13:34.407Z","caller":"server/runtime_go.go:2396","msg":"Initialising Go runtime provider","path":"/data/modules"}
{"level":"error","ts":"2022-06-28T15:13:34.411Z","caller":"server/runtime_go.go:2492","msg":"Could not open Go module","path":"/data/modules/backend.so","error":"plugin.Open(\"/data/modules/backend\"): plugin was built with a different version of package internal/unsafeheader"}
```
I don't know what it's complaining about but it isn't delve's fault.

**Comment by tomglenn** [comment]
@aarzilli I have now got this working (I updated the repo and readme to reflect the changes). I'm right in thinking (from reading previous issues) that it's not possible to remotely debug plugins with breakpoints in an IDE such as GoLand/VSCode due to the plugin not being loaded yet at the time the IDE tries to set the breakpoints? 

https://github.com/go-delve/delve/issues/1653

**Comment by aarzilli** [comment]
You can, you just have to first progress the program until the plugin is loaded. After #1653 is fixed (should happen in the next few months) and IDEs are upgraded for it, it won't be needed.
Reopen if there are other problems.
