### ISSUE TITLE
Support show friendly func args on `bt` and `goroutines -t`

### ISSUE THREAD

**Issue by yangxikun** [go-delve/delve#3043]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

If this is about source listing not showing up (or breakpoints not being
accepted) while running in a container please read our
[FAQ](https://github.com/go-delve/delve/blob/master/Documentation/faq.md#substpath)
first.

1. What version of Delve are you using (`dlv version`)? 1.8.3
2. What version of Go are you using? (`go version`)? go1.17.5
3. What operating system and processor architecture are you using? linux
4. What did you do? runt `bt` or `goroutines -t`
5. What did you expect to see?

show readable args on `runtime.chanrecv` and `main.chanLock.func1`:
```
0  0x000000000102e596 in runtime.gopark
   at /usr/local/Cellar/go/1.17.5/libexec/src/runtime/proc.go:367
1  0x00000000010049cc in runtime.chanrecv((*runtime.hchan)(0xc0000220c0), unsafe.Pointer(0x0), true)
   at /usr/local/Cellar/go/1.17.5/libexec/src/runtime/chan.go:576
2  0x0000000001004438 in runtime.chanrecv1()
   at /usr/local/Cellar/go/1.17.5/libexec/src/runtime/chan.go:439
3  0x00000000010574f0 in main.chanLock.func1(888)
   at ./lock/main.go:24
4  0x000000000105748d in main.chanLock·dwrap·1
   at ./lock/main.go:27
5  0x0000000001053121 in runtime.goexit
   at /usr/local/Cellar/go/1.17.5/libexec/src/runtime/asm_amd64.s:1581
```
If this feature is acceptable, I can try to contribute for it.

**Comment by aarzilli** [comment]
What does this mean exactly? What would readable arguments look like, to which functions would it apply?

**Comment by yangxikun** [comment]
@aarzilli

**Comment by yangxikun** [comment]
@aarzilli show runtime.chanrecv args when run `bt` or `goroutines -t`:

1  0x00000000010049cc in runtime.chanrecv`((*runtime.hchan)(0xc0000220c0), unsafe.Pointer(0x0), true)`
   at /usr/local/Cellar/go/1.17.5/libexec/src/runtime/chan.go:576

**Comment by aarzilli** [comment]
It is already showing the arguments of chanrecv. What would change?

**Comment by yangxikun** [comment]
@aarzilli I add the args manually..., its what I want to see.

**Comment by yangxikun** [comment]
Can `goroutines -t` also add `-full` flag?

**Comment by aarzilli** [comment]
That's reasonable. We could also change `goroutines` to accept a command that gets run on every goroutine:

```
(dlv) goroutines -exec stack -full
```

**Comment by yangxikun** [comment]
> That's reasonable. We could also change `goroutines` to accept a command that gets run on every goroutine:
> 
> ```
> (dlv) goroutines -exec stack -full
> ```

That's great, I will try to implement it.
