### ISSUE TITLE
Starlark dependency is outdated

### ISSUE THREAD

**Issue by alexsaezm** [go-delve/delve#3048]
I maintain the Starlark package in Fedora and I'm packing Delve too. but currently the version of the Starlark package is more recent than the version Delve uses, and looks like that version of Starlark doesn't behave in the same way anymore.

That makes the following test fail:

```
=== RUN   TestStarlarkVariable
    starlark_test.go:156: for "v = eval(None, \"f1\").Variable; print(v.Value)"
        expected "3"
        got "3.0"
--- FAIL: TestStarlarkVariable (0.44s)

FAIL
```

I run the whole test suite on aarch64 and amd64 on Linux and everything looks fine with the newest version of Starlark apart from that test.

Of course one easy solution on my side is to patch the test inside the package. But I was wondering if there's a reason why the dependency hasn't been updated that I should be aware of before doing the patch.

**Comment by aarzilli** [comment]
We don't update dependencies without a reason to do it.

**Comment by eclipseo** [comment]
> We don't update dependencies without a reason to do it.

How do you deal with CVE fixes?

**Comment by aarzilli** [comment]
That would be a reason to update. However I'm curious what you think a relevant CVE would look like for us, considering `dlv exec` and `call` exist.

**Comment by alexsaezm** [comment]
> We don't update dependencies without a reason to do it.

Understood. I'll fix it on the package side. Thanks
