### ISSUE TITLE
Feature Request: `condition -hitcount` support per goroutine hitcount as operand.

### ISSUE THREAD

**Issue by yangxikun** [go-delve/delve#3050]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

If this is about source listing not showing up (or breakpoints not being
accepted) while running in a container please read our
[FAQ](https://github.com/go-delve/delve/blob/master/Documentation/faq.md#substpath)
first.

1. What version of Delve are you using (`dlv version`)? 1.8.3
2. What version of Go are you using? (`go version`)? go1.17.5
3. What operating system and processor architecture are you using? linux
4. What did you do?
5. What did you expect to see?
6. What did you see instead?

Currently, `condition -hitcount bp > n` use total hitcount to compare n, we need per goroutine hitcount to support more debug scene.

**Comment by yangxikun** [comment]
@aarzilli If this feature is acceptable, I can try to implement it.

Implement design, please review:
1. Add `-per-g-hitcount` flag, it's exclusive with `-hitcount`
2. Add `CmpPerGHitcount bool` field to `api.Breakpoint`
3. Add `CmpPerGHitcount` field to `proc.LogicalBreakpoint`
4. In `checkHitCond`, if `LogicalBreakpoint.CmpPerGHitcount` is true, compare n with current g hitcount, instead of total hitcount.

**Comment by aarzilli** [comment]
I'd say `s/CmpPerGHitcount/HitCondPerG/`
