### ISSUE TITLE
Debugger doesn't stop on some breakpoints in fuzz tests

### ISSUE THREAD

**Issue by nd** [go-delve/delve#3077]
1. What version of Delve are you using (`dlv version`)?

```
Delve Debugger
Version: 1.9.0
Build: 3fb2d49829187388d75c70fa46a18e0361a0292f
```

2. What version of Go are you using? (`go version`)?

```
go version go1.19rc2 windows/amd64
```

3. What operating system and processor architecture are you using?

```
windows/amd64
```

4. What did you do?

Went through go fuzz tutorial: [go.mod](https://go.dev/play/p/HjSZMuFRQZ6), [main.go](https://go.dev/play/p/mK5txfSyJAj), [main_test.go](https://go.dev/play/p/O3Ia-CSqPlo). Compiled the test as suggested in https://github.com/golang/go/issues/54001:

```
go test -c -o test.exe -fuzz=. -gcflags=all="-N -l" gofuzztutorial
```

and ran it under delve:

```
dlv exec path/to/test.exe -- -test.v -test.paniconexit0 -test.fuzz ^\QFuzzReverse\E$ -test.fuzzcachedir path/to/fuzz/cache -test.run ^$
```

Created breakpoints at main_test.go:9, maint_test.go:14, and main.go:15 and let it run. 

5. What did you expect to see?

Debugger stops at all breakpoints.

6. What did you see instead?

Debugger stops at main_test.go:9, but not on other breakpoints.

**Comment by aarzilli** [comment]
I'll look into it but I think the reason is that fuzzing spawns a bunch of subprocesses to do its thing and we don't support that.

**Comment by aarzilli** [comment]
As I suspected it should be because of subprocesses. I didn't test this on windows because I don't have a version of delve that can follow subprocess execution on windows yet. But on linux:

```
(dlv) b main_test.go:9
Breakpoint 1 set at 0x64e0ae for gofuzztutorial.FuzzReverse() ./main_test.go:9
(dlv) b main_test.go:14
Breakpoint 2 set at 0x64dbc1 for gofuzztutorial.FuzzReverse.func1() ./main_test.go:14
(dlv) b main_test.go:15
Breakpoint 3 set at 0x64dc23 for gofuzztutorial.FuzzReverse.func1() ./main_test.go:15
(dlv) target follow-exec -on
(dlv) c
=== FUZZ  FuzzReverse
> gofuzztutorial.FuzzReverse() ./main_test.go:9 (hits goroutine(6):1 total:1) (PC: 0x64e0ae)
     4:		"testing"
     5:		"unicode/utf8"
     6:	)
     7:	
     8:	func FuzzReverse(f *testing.F) {
=>   9:		testcases := []string{"Hello, world", " ", "!12345"}
    10:		for _, tc := range testcases {
    11:			f.Add(tc) // Use f.Add to provide a seed corpus
    12:		}
    13:		f.Fuzz(func(t *testing.T, orig string) {
    14:			rev := Reverse(orig)
(dlv) c
fuzz: elapsed: 0s, gathering baseline coverage: 0/4 completed
Switch target process from 799174 to 799186 (./test -test.fuzzworker -test.v -test.paniconexit0 -test.fuzz=^\QFuzzReverse\E$ -test.fuzzcachedir fuzzcache/ -test.run ^$)
> gofuzztutorial.FuzzReverse() ./main_test.go:9 (hits goroutine(20):1 total:2) (PC: 0x64e0ae)
     4:		"testing"
     5:		"unicode/utf8"
     6:	)
     7:	
     8:	func FuzzReverse(f *testing.F) {
=>   9:		testcases := []string{"Hello, world", " ", "!12345"}
    10:		for _, tc := range testcases {
    11:			f.Add(tc) // Use f.Add to provide a seed corpus
    12:		}
    13:		f.Fuzz(func(t *testing.T, orig string) {
    14:			rev := Reverse(orig)
(dlv) target list
799174  
799186  ./test -test.fuzzworker -test.v -test.paniconexit0 -test.fuzz=^\QFuzzReverse\E$ -test.fuzzcachedir fuzzcache/ -test.run ^$
799187  ./test -test.fuzzworker -test.v -test.paniconexit0 -test.fuzz=^\QFuzzReverse\E$ -test.fuzzcachedir fuzzcache/ -test.run ^$
799189  ./test -test.fuzzworker -test.v -test.paniconexit0 -test.fuzz=^\QFuzzReverse\E$ -test.fuzzcachedir fuzzcache/ -test.run ^$
799197  ./test -test.fuzzworker -test.v -test.paniconexit0 -test.fuzz=^\QFuzzReverse\E$ -test.fuzzcachedir fuzzcache/ -test.run ^$
(dlv) 
```

Therefore this is a duplicate of #2551 and I close it as such. FWIW I plan to implement that feature for linux (I already have but it will take a while to merge all the necessary changes, it's rather involved) and windows. It can't be implemented on macOS because debugserver itself does not support it.

**Comment by aarzilli** [comment]
PS the trace I copied doesn't show the child process making it all the way to the fuzz function but eventually it will.
