### ISSUE TITLE
Cannot run the debugger in NixOS

### ISSUE THREAD

**Issue by namnd** [go-delve/delve#3085]
1. What version of Delve are you using (`dlv version`)?
> Delve Debugger
> Version: 1.9.0
> Build: $Id: 69310c2f438e492f892d6af22e8e62c8ea1e9d8d

2. What version of Go are you using? (`go version`)?
> go version go1.18.2 linux/arm64

3. What operating system and processor architecture are you using?
> Linux devbox 5.15.55 #1-NixOS SMP Fri Jul 15 08:13:00 UTC 2022 aarch64 GNU/Linux

4. What did you do?
> Start debugging test

5. What did you expect to see?

6. What did you see instead?

> Build Error: go test -c -o /home/../../__debug_bin -gcflags all=-N -l /home/../../**_test.go
> # runtime/cgo
> In file included from /nix/store/y7g7iskbmzpy7wxc4v4sxqg0p3z5w5b4-glibc-2.34-210-dev/include/bits/libc-header-start.h:33,
>                  from /nix/store/y7g7iskbmzpy7wxc4v4sxqg0p3z5w5b4-glibc-2.34-210-dev/include/stdlib.h:25,
>                  from _cgo_export.c:3:
> /nix/store/y7g7iskbmzpy7wxc4v4sxqg0p3z5w5b4-glibc-2.34-210-dev/include/features.h:412:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
>   412 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
>       |    ^~~~~~~
> cc1: all warnings being treated as errors (exit status 2)

**Comment by aarzilli** [comment]
See https://github.com/NixOS/nixpkgs/issues/18995. You can probably work around this by setting CGO_CFLAGS to something (it doesn't matter what).

**Comment by namnd** [comment]
Thanks @aarzilli i was able to work around by adding `hardeningDisable = [ "all" ];` to the `shell.nix`

**Comment by W1M0R** [comment]
The [NixOS Wiki](https://nixos.wiki/wiki/Go#Using_cgo_on_NixOS) also suggest adding the following line to `shell.nix`:

```nix

hardeningDisable = [ "fortify" ];

```

Related:

1. https://nixos.wiki/wiki/C#Hardening_flags
2. https://nixos.org/manual/nixpkgs/stable/#sec-hardening-in-nixpkgs
3. https://github.com/NixOS/nixpkgs/issues/101979

**Comment by adamcstephens** [comment]
the official NixOS wiki is now here: https://wiki.nixos.org/wiki/Go#Using_cgo_on_NixOS

**Comment by kelvincesar** [comment]
I can confirm that I was having this problem when debuging a golang program with delve on vscode.

Added the hardeningDisable into my shell.nix and now it is working. Thanks!

```nix
pkgs.mkShell {
  hardeningDisable = [ "fortify" ]; 
  ....
}
```
