### ISSUE TITLE
examinemem: `-fmt addr` is documented but doesn't work

### ISSUE THREAD

**Issue by dominikh** [go-delve/delve#3086]
1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 1.9.0
Build: $Id: 69310c2f438e492f892d6af22e8e62c8ea1e9d8d $
```

3. What version of Go are you using? (`go version`)?
```
go version go1.18.4 linux/amd64
```

5. What operating system and processor architecture are you using?
Linux/amd64

7. What did you do?
`x -fmt addr -count 1 -size 8 0xc000171f40`

9. What did you expect to see?
The output of `help x` says that
> Format represents the data format and the value is one of this list (default hex): bin(binary), oct(octal), dec(decimal), hex(hexadecimal), addr(address).

so I expected `-fmt addr` to work.

11. What did you see instead?
`Command failed: "addr" is not a valid format`

**Comment by aarzilli** [comment]
We removed it during review but the documentation wasn't updated. It basically did the same thing as hex.
