### ISSUE TITLE
How to support delve in go1.17

### ISSUE THREAD

**Issue by ningyougang** [go-delve/delve#3089]
In go1.17. i can't execute `go get -u github.com/go-delve/delve/cmd/dlv@v1.8.1`.

I debug this Dockerfile: https://github.com/apache/openwhisk-runtime-go/blob/master/golang1.17/Dockerfile one line by one line.
When executed at 41 line:  `go get -u github.com/go-delve/delve/cmd/dlv@v1.8.1`. reported below error

```
root@14d5d623ca0e:/go# go get -u github.com/go-delve/delve/cmd/dlv@v1.8.1
go get: installing executables with 'go get' in module mode is deprecated.
	Use 'go install pkg@version' instead.
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
# github.com/rivo/uniseg
pkg/mod/github.com/rivo/uniseg@v0.3.1/properties.go:130:6: missing function body
pkg/mod/github.com/rivo/uniseg@v0.3.1/properties.go:130:20: syntax error: unexpected [, expecting (
note: module requires Go 1.18
```
It seems  v1.8.1 doesn't support in Go1.17. it needs Go1.18 (Btw, i checked in Go1.18, works well)
How to support dlv in Go1.17? Btw, i have tried several lower version(e.g. v1.7.1, 1.6.1, etc), the same error happened

**Comment by aarzilli** [comment]
Installing executables with 'go get' in module mode is deprecated. Use 'go install pkg@version' instead.
For more information, see https://golang.org/doc/go-get-install-deprecation or run 'go help get' or 'go help install'.
