### ISSUE TITLE
Support Multiplatform assembly

### ISSUE THREAD

**Issue by aleass** [go-delve/delve#3113]
1. What version of Delve are you using (`dlv version`)?
`Delve Debugger                                        
Version: 1.9.0                                        
Build: $Id: 69310c2f438e492f892d6af22e8e62c8ea1e9d8d `
3. What version of Go are you using? (`go version`)?
`go 1.19`
4. What operating system and processor architecture are you using?
`windows and macos`
5. What did you do?
`debug and disass`
6. What did you expect to see?
Assembly of Linux can be printed on any system,like go on multi-platform.
7. What did you see instead?
There is no such feature

I hope I can print out the assembly of AMD64 Linux in ARM MacOS or Windows, so as to facilitate learning and viewing.

**Comment by aarzilli** [comment]
What do you mean with this? If you load an amd64 core dump on arm you will be able to disassemble it. You can't disassemble an amd64 executable as arm assembly.

**Comment by aleass** [comment]
> What do you mean with this? If you load an amd64 core dump on arm you will be able to disassemble it. You can't disassemble an amd64 executable as arm assembly.
When I am debugging on an M1-chip MAC system, I can output x86 Linux assembly.

**Comment by aleass** [comment]
When I am debugging on an M1-chip MAC system, I can output x86 Linux assembly.

**Comment by aleass** [comment]
> What do you mean with this? If you load an amd64 core dump on arm you will be able to disassemble it. You can't disassemble an amd64 executable as arm assembly.


When I am debugging on an M1-chip MAC system, I can output x86 Linux assembly.

**Comment by aarzilli** [comment]
The disassembler shows you what's inside the executable you are debugging, not the contents of other, hypothetical, executables.

**Comment by aleass** [comment]
> The disassembler shows you what's inside the executable you are debugging, not the contents of other, hypothetical, executables.

I see. Thank you for your answer.
