### ISSUE TITLE
Can't install delve with go 1.19

### ISSUE THREAD

**Issue by jhaumont** [go-delve/delve#3118]
Hello

When installing 1.19 go version & reinstall/update the additional go tools like `gopls` & `dlv`, I have an issue with delve and the package https://github.com/hashicorp/golang-lru/tree/master/simplelru.
So, I can't install delve. But if I use the 1.18.5 version of go, I have no issue and I can install the last delve version.

1. What version of Delve are you using (`dlv version`)?
**1.9.0**

2. What version of Go are you using? (`go version`)?
**1.19.0**

3. What operating system and processor architecture are you using?
**WSL on windows with amd64 processor**

4. What did you do?
I try to do a fresh install of go (with 1.19.0) and then, install delve.

- Install go:

```bash
rm -rf ${HOME}/bin/go
cd "$(mktemp -d)"
wget https://go.dev/dl/go1.19.linux-amd64.tar.gz
tar -C ${HOME}/bin -xzf go1.19.linux-amd64.tar.gz
```

- Install devel:

```bash
go install -v github.com/go-delve/delve/cmd/dlv@latest
```

5. What did you expect to see?
No error,  devel is correctly installed

7. What did you see instead?
`pkg/mod/github.com/hashicorp/golang-lru@v0.5.4/simplelru/lru.go:1:1: expected 'package', found 'EOF'`

Maybe I miss something? 🤔 

Thanks for your help 🙏

**Comment by aarzilli** [comment]
It looks like something broke while you were downloading do `go clean -modcache` and try again.

**Comment by aarzilli** [comment]
Is your disk full?

**Comment by bcmills** [comment]
> But if I use the 1.18.5 version of go, I have no issue and I can install the last delve version.

I wonder if this is a bug in the new `cmd/go` module indexing path.
Does it install successfully with 1.19 if you set `GODEBUG=goindex=0` in the environment?

**Comment by jhaumont** [comment]
> > But if I use the 1.18.5 version of go, I have no issue and I can install the last delve version.
> 
> I wonder if this is a bug in the new `cmd/go` module indexing path. Does it install successfully with 1.19 if you set `GODEBUG=goindex=0` in the environment?

it works!

**Comment by jhaumont** [comment]
By the way, I like the comment in the source code: https://github.com/golang/go/blob/bf2ef26be3593d24487311576d85ec601185fbf4/src/cmd/go/internal/modindex/read.go#L39 😄

**Comment by bcmills** [comment]
@jhaumont, could you file an issue at https://go.dev/issue/new? If possible, could you include the contents of `~/pkg/mod/cache/download/github.com/hashicorp/golang-lru` and `~/pkg/mod/github.com/hashicorp/golang-lru@v0.5.4`?

It sounds like perhaps the module was indexed before it was fully downloaded, but that shouldn't be possible. The contents of those directories might help us narrow down the bug.

**Comment by jhaumont** [comment]
@bcmills done, I close this one

**Comment by Idisis32** [comment]
Guys, what should I do?
I installed the GO language
installed the extension of this language in VSCode
I run "Hello world", nothing works
 can you tell me what I'm doing wrong?

**Comment by Idisis32** [comment]
And who can tell me why my GitHub doesn't see the new repositories that I create in vscode?
