### ISSUE TITLE
dlv exec requires libgo.so on linux/arm64 ?

### ISSUE THREAD

**Issue by erifan** [go-delve/delve#3121]
1. What version of Delve are you using (`dlv version`)?
  Delve Debugger
  Version: 1.9.1
  Build: $Id: d81b9fd12bfa603f3cf7a4bc842398bd61c42940 $

3. What version of Go are you using? (`go version`)?
  go version devel go1.20-75cdd2c75d Wed Aug 24 02:54:32 2022 +0000 linux/arm64

5. What operating system and processor architecture are you using?
  linux arm64, kernel version: 5.15.52-051552-generic-64k

7. What did you do?
  $ cat main.go

`package main

import(
        "fmt"
)

func foo(a, b string) string {
        var arr [10000]string
        for i := 0; i < 10000; i++ {
                arr[i] = a + b
        }
        return arr[90]
}

func main() {
        s := ""
        for i := 0; i < 1000; i++ {
                s += foo("a", "b")
        }
        fmt.Println(s)
}
`

  $ go build -o main main.go
  $ dlv exec ./main
  $ b main.main
  $ c

9. What did you expect to see?
  Normal debugging

11. What did you see instead?
  main: error while loading shared libraries: libgo.so.21: cannot open shared object file: No such file or directory

**Comment by aarzilli** [comment]
No. This is something about how you are compiling the binary. Gccgo is not supported.

**Comment by erifan** [comment]
> 

I compiled the program with main Go, not Gccgo.

**Comment by aarzilli** [comment]
Can I see the executable?

**Comment by erifan** [comment]
> 

Did you read the problem description above?

**Comment by aarzilli** [comment]
Yes I did, but we also have a linux/arm64 builder, including for go-tip, and it works. So the problem is likely with your setup.

**Comment by erifan** [comment]
> Yes I did, but we also have a linux/arm64 builder, including for go-tip, and it works. So the problem is likely with your setup.

Thanks, I have tried on a clean environment, it works, so it should be the problem of my setup.
