### ISSUE TITLE
delve can not attach to process owned by other user on windows

### ISSUE THREAD

**Issue by wubolin** [go-delve/delve#3136]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

If this is about source listing not showing up (or breakpoints not being
accepted) while running in a container please read our
[FAQ](https://github.com/go-delve/delve/blob/master/Documentation/faq.md#substpath)
first.

1. What version of Delve are you using (`dlv version`)?
  Delve Debugger
  Version: 1.9.1
  Build: $Id: d81b9fd12bfa603f3cf7a4bc842398bd61c42940 $
2. What version of Go are you using? (`go version`)?
  go version go1.19.1 windows/amd64
3. What operating system and processor architecture are you using?
   windows 10
   amd64
4. What did you do?
  i want to debug a service of windows. i want to attach the process of windows service by delve. but delve give a error:
   when i run C:\Projects\wireguard-windows>dlv attach 10026 . it outputs:
    "could not attach to pid 10026: Access is denied."
5. What did you expect to see?
  i expect delve attach success.
6. What did you see instead?
  windbg can attach the process of windows service

**Comment by wubolin** [comment]
thank you, reply so quickly!  i already run delve in admin.  whether i run in admin, the same mistake occurs

**Comment by aarzilli** [comment]
The error comes out of the Attach function in pkg/proc/native/proc_windows.go, you'll have to figure out why.

**Comment by wubolin** [comment]
according to[https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debug-privilege](url) , somone needs debug privilege to debug a process that he wouldn’t otherwise have access to.  user of service process is "system", so need SetPrivilege to adust privilege of user.  following is code example:

```
//
//  SetPrivilege enables/disables process token privilege.
//
BOOL SetPrivilege(HANDLE hToken, LPCTSTR lpszPrivilege, BOOL bEnablePrivilege)
{
    LUID luid;
    BOOL bRet=FALSE;

    if (LookupPrivilegeValue(NULL, lpszPrivilege, &luid))
    {
        TOKEN_PRIVILEGES tp;

        tp.PrivilegeCount=1;
        tp.Privileges[0].Luid=luid;
        tp.Privileges[0].Attributes=(bEnablePrivilege) ? SE_PRIVILEGE_ENABLED: 0;
        //
        //  Enable the privilege or disable all privileges.
        //
        if (AdjustTokenPrivileges(hToken, FALSE, &tp, NULL, (PTOKEN_PRIVILEGES)NULL, (PDWORD)NULL))
        {
            //
            //  Check to see if you have proper access.
            //  You may get "ERROR_NOT_ALL_ASSIGNED".
            //
            bRet=(GetLastError() == ERROR_SUCCESS);
        }
    }
    return bRet;
}
```
```
HANDLE hProcess=GetCurrentProcess();
HANDLE hToken;

if (OpenProcessToken(hProcess, TOKEN_ADJUST_PRIVILEGES, &hToken))
{
    SetPrivilege(hToken, SE_DEBUG_NAME, TRUE);
    CloseHandle(hToken);
}
```

the Attach function in pkg/proc/native/proc_windows.go don't  adopt SetPrivilege
