### ISSUE TITLE
goroutine wait time is incorrect

### ISSUE THREAD

**Issue by qingyunha** [go-delve/delve#3137]
https://github.com/go-delve/delve/blob/9bcccf81ed7c93a6f1ea4bfc0d905178e6db8e81/pkg/terminal/command.go#L1079

`g.WaitSince` is a CLOCK_MONOTONIC  nanotime，and it can't used in`time.Unix`.

There is a  `runtime.runtimeInitTime` , we may use it as a base time.

**Comment by qingyunha** [comment]
Can we use `g.WatiSince - runtime.runtimeInitTime` , Then user can use the process start time to calculate the wait time ?

**Comment by derekparker** [comment]
This should be closed via #3139 if not please reopen.
