### ISSUE TITLE
Wrong map children after setting a value

### ISSUE THREAD

**Issue by nd** [go-delve/delve#3138]
1. What version of Delve are you using (`dlv version`)?

```
9bcccf81ed7c93a6f1ea4bfc0d905178e6db8e81
```

2. What version of Go are you using? (`go version`)?

```
go version go1.19.1 windows/amd64
```

3. What operating system and processor architecture are you using?

windows/amd64

4. What did you do?

Debugged the program

```
package main

import (
	"fmt"
	"runtime"
)

type Set struct {
	data map[interface{}]struct{}
}

func (set *Set) Add(items ...interface{}) {
	for _, v := range items {
		set.data[v] = struct{}{}
	}
}

func main() {
	var set = &Set{
		data: make(map[interface{}]struct{}),
	}
	for i := 0; i < 300; i++ {
		if i == 100 {
			runtime.Breakpoint()
		}
		set.Add(fmt.Sprintf("%d", i))
	}
}
```

Once a breakpoint is reached stepped over the set.Add.

5. What did you expect to see?

set.data contains all previously added keys

6. What did you see instead?

all entries in set.data are empty

Full log: https://gist.github.com/nd/c07934cb2c057f8ced93b31fc546552c

**Comment by aarzilli** [comment]
It looks fine to me, both the log and on the command line. It's just hitting the recursion limit:

```
(dlv) c
> [hardcoded-breakpoint] main.main() ./test.go:24 (hits total:0) (PC: 0x49ac4a)
    19:		var set = &Set{
    20:			data: make(map[interface{}]struct{}),
    21:		}
    22:		for i := 0; i < 300; i++ {
    23:			if i == 100 {
=>  24:				runtime.Breakpoint()
    25:			}
    26:			set.Add(fmt.Sprintf("%d", i))
    27:		}
    28:	}
(dlv) p set
*main.Set {
	data: map[interface {}]struct {} [
		*(*interface {})(0xc000104008): {}, 
		*(*interface {})(0xc000104018): {}, 
		*(*interface {})(0xc000104028): {}, 
(snip)
		*(*interface {})(0xc000104578): {}, 
		*(*interface {})(0xc000104588): {}, 
		*(*interface {})(0xc000104998): {}, 
		...+36 more
	],}
(dlv) p *(*"interface {}")(0xc000104008)
interface {}(string) "27"
(dlv) config max-variable-recurse 2
(dlv) p set
*main.Set {
	data: map[interface {}]struct {} [
		"27": {}, 
		"45": {}, 
		"60": {}, 
(snip)
		"53": {}, 
		"62": {}, 
		"82": {}, 
		...+36 more
	],}
```

For some reason we can't resolve the type in `p *(*interface {})(0xc000104008)` but that's a different problem.

**Comment by nd** [comment]
The client evaluates the same expression `*(*\"map[interface {}]struct {}\")(824634809920)` on lines 36 and 48 in the log. On line 36 (before stepping over set.Add call) it gets string keys with values filled. On the line 48 all key values are empty. Both calls to eval have the same MaxVariableRecurse=1.

**Comment by aarzilli** [comment]
Line 36 is the result of evaluating `*(*\"map[interface {}]struct {}\")(824634809920)`, line 48 is the result of evaluating `*(*\"main.Set\")(824634809920)`. In the first case you are evaluating the data field of the main.Set struct, in the second you are evaluating the main.Set struct itself. In the second case there is one extra step of recursion, therefore the evaluation ends earlier, before loading the value of the string keys.
It is the equivalent of evaluating `p set` and `p set.data` on the command line interface.

**Comment by nd** [comment]
Thanks, seems like a client problem then.
