### ISSUE TITLE
error installing delve io timeout

### ISSUE THREAD

**Issue by aquaty** [go-delve/delve#3140]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

If this is about source listing not showing up (or breakpoints not being
accepted) while running in a container please read our
[FAQ](https://github.com/go-delve/delve/blob/master/Documentation/faq.md#substpath)
first.

1. What version of Delve are you using (`dlv version`)?
latest 1.9.1
3. What version of Go are you using? (`go version`)?
1.18
4. What operating system and processor architecture are you using?
mac intel v11.7

5. What did you do?

I am trying to install a go debugger from this post https://blog.jetbrains.com/go/2020/05/06/debugging-a-go-application-inside-a-docker-container/ and I added this line to docker file

RUN go install github.com/go-delve/delve/cmd/dlv@latest
but it keeps on getting a timeout error

 => ERROR [build-env 2/5] RUN go install github.com/go-delve/delve/cmd/dlv@latest                                                                                                   

    30.6s
------
 > [build-env 2/5] RUN go install github.com/go-delve/delve/cmd/dlv@latest:
#7 30.56 go install github.com/go-delve/delve/cmd/dlv@latest: module github.com/go-delve/delve/cmd/dlv: Get "https://proxy.golang.org/github.com/go-delve/delve/cmd/dlv/@v/list": dial tcp 172.217.168.209:443: i/o timeout
------
executor failed running [/bin/sh -c go install github.com/go-delve/delve/cmd/dlv@latest]: exit code: 1
make: *** [build-func] Error 1
when I try to visit that url in the browser

https://proxy.golang.org/github.com/go-delve/delve/cmd/dlv/@v/list

not found: module github.com/go-delve/delve/cmd/dlv: no matching versions for query "latest"

6. What did you expect to see?
was expecting go install to complete

7. What did you see instead?
docker build failed due to timeout

**Comment by aarzilli** [comment]
We don't run the golang proxy, you could report this to https://github.com/golang/go/issues/ but likely it's just a network issue on your side.
