### ISSUE TITLE
Allow ability to set user id, including root, while in delve

### ISSUE THREAD

**Issue by mellowdrifter** [go-delve/delve#3163]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

If this is about source listing not showing up (or breakpoints not being
accepted) while running in a container please read our
[FAQ](https://github.com/go-delve/delve/blob/master/Documentation/faq.md#substpath)
first.

1. What version of Delve are you using (`dlv version`)? 1.9.1
2. What version of Go are you using? (`go version`)? 1.19
3. What operating system and processor architecture are you using? Linux - x86-64
4. What did you do? Can't debug app with a user, without sudo'ing to that user first
5. What did you expect to see? I want to be able to set user while in delve
6. What did you see instead? nothing

**Comment by aarzilli** [comment]
To do this dlv would need to be a setuid binary and making a program with such a big attack surface setuid is a bad idea. That's one reason why this shouldn't be done. The other reason is that there is no precedent for this feature in other debuggers.
