### ISSUE TITLE
Wrong behaviour of reflect when using dlv

### ISSUE THREAD

**Issue by dbadura** [go-delve/delve#3166]
1. What version of Delve are you using (`dlv version`)? 1.9.1
2. What version of Go are you using? (`go version`)? 1.19.2 linux/amd16
3. What operating system and processor architecture are you using? Ubuntu 20.04 amd64
4. What did you do?
I have such unit test with `reflect`:
```
import (
	"fmt"
	"reflect"
	"runtime"
	"strings"
	"testing"
)

func returnFunc() func() {
	return func() {
	}
}

func TestName(t *testing.T) {
	expectedName := "TestName"
	fn := returnFunc()

	fnName := runtime.FuncForPC(reflect.ValueOf(fn).Pointer()).Name()
	if !strings.Contains(fnName, expectedName) {
		t.Fail()
	}
	fmt.Printf("%s, should contain: %s", fnName, expectedName)
}
```
6. What did you expect to see?
When I run it normally the test pass.
In debug mode the test fails.

9. What did you see instead?
Failed test in debug mode.

**Comment by aarzilli** [comment]
This is not a bug with delve. The go compiler names anonymous functions inconsistently when inlining is enabled (see https://github.com/golang/go/issues/55980). In your case when inlining is enabled the anonymous function gets the (arguably wrong) name main.TestName.func1, if inlining is disabled (either with `test -gcflags='-l'` or by annotating returnFunc with `go:noinline`, or by letting delve build it) it will get the (arguably better) name main.returnFunc.func1.
