### ISSUE TITLE
call not at safe point

### ISSUE THREAD

**Issue by kmillikin** [go-delve/delve#3175]
Delve will allow breaking at or stepping to places where it's not possible to evaluate expressions:

```
> call ref.String()
Unable to evaluate expression: call not at safe point
```

It's common for users to set breakpoints or single step through code in order to inspect the values of expressions.  The user doesn't really know where safe points are and they shouldn't have to know that.

Is it really not possible to generate a safepoint at every place that the debugger can stop when compiling in debug mode?

**Comment by aarzilli** [comment]
It would mean having a safepoint after every instruction, which would bloat binaries significantly. In any case this would be a request to make to the compiler.

**Comment by superbobry** [comment]
@aarzilli is there a chance you could forward this to the compiler issue tracker? It is tricky for users to predict where safe points are, and having to guess at all significantly degrades the usability of `call`.
