### ISSUE TITLE
Wrong position after step in on mac 

### ISSUE THREAD

**Issue by nd** [go-delve/delve#3194]
1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 1.9.1
Build: $Id: d81b9fd12bfa603f3cf7a4bc842398bd61c42940 $
```
2. What version of Go are you using? (`go version`)?
```
go version 1.19.3 darwin/amd64
```
3. What operating system and processor architecture are you using?

MacOS 12.5.1

4. What did you do?

Debugged the program

```
package main

import "fmt"
import _ "k8s.io/cli-runtime/pkg/resource"

func main() {
	f() // break here
}

func f() {
	fmt.Println("ok")
}
```

Once breakpoint is reached stepped twice.

6. What did you expect to see?

Debugger stops somewhere inside the fmt package.

7. What did you see instead?

Debugger stops in runtime (proc.go). Log: https://gist.github.com/nd/0445e4ed453155388cca9594ab37bd79.

Got wrong position in go1.19.2+ and go1.18.7+, works as expected in go1.19.1 and go1.18.6.

Also happens if k8s import is replaced with cgo:

```
package main

/*
#cgo LDFLAGS: -framework CoreFoundation
#cgo LDFLAGS: -framework CFNetwork
#include <CFNetwork/CFProxySupport.h>
*/
import "C"
import "fmt"

func main() {
	f() // break here
}

func f() {
	fmt.Println("ok")
}
```

Works as expected if the cgo import is removed.

**Comment by aarzilli** [comment]
I tried reproducing this on the m1 builder and I couldn't. Is this something that happens systematically or just sometimes?

**Comment by inksnw** [comment]
> I tried reproducing this on the m1 builder and I couldn't. Is this something that happens systematically or just sometimes?

systematically, on intel mac

**Comment by aarzilli** [comment]
Turns out this is our old friend https://github.com/golang/go/issues/25841 I guess the problem was *not* PIE after all. Curious.
