### ISSUE TITLE
On-prem windows/arm64 builder 

### ISSUE THREAD

**Issue by qmuntal** [go-delve/delve#3197]
> Steal an arm64 laptop and hide it in a closet. @aarzilli [source](https://github.com/go-delve/delve/pull/3063#pullrequestreview-1079246540)

I finally got a Windows ARM64 PC without breaking any law nor any Microsoft policy, just had to apply to the [Windows Dev Kit 2023](https://blogs.windows.com/windowsdeveloper/2022/10/24/available-today-windows-dev-kit-2023-aka-project-volterra/) project 😄.

Delve windows/arm64 is still experimental, gated behind the `exp.winarm64` build tag waiting for a builder. Well, I can provide this builder and time to debug issues. Just a couple of conditions:
- I plan to have it up and running all the time, but I can't commit to any SLA nor support it outside office hours.
- I will probably have the hardware for at least one year, can commit to any further timeframe. Hopefully windows/arm64 hardware availability will increase during this time period so my on-prem machine won't be necessary in 1 year.

I already have the TimeCity On-prem agent installer and running named `windows/arm64-qmuntal-2`. Just missing the approval to run builds.

@aarzilli @derekparker

**Comment by aarzilli** [comment]
I have no problems with those conditions. Pretty cool.

**Comment by derekparker** [comment]
This is great! Thank you for setting this all up.

So if I'm not mistaken the agent is [windows/arm64-qmuntal-2](https://delve.teamcity.com/agent/265) however it appears to be offline according to the TeamCity UI. I've authorized the agent so once it's online it should be good to go.

**Comment by derekparker** [comment]
Nevermind, it seems to be connected again now. Thanks for this!
