### ISSUE TITLE
   error was happen using vscode  build  

### ISSUE THREAD

**Issue by jersbo** [go-delve/delve#3199]
Build Error: go build -o d:\dock\godev\godo\__debug_bin.exe -gcflags all=-N -l .
# internal/bytealg
go_asm.h:1: expected identifier, found "%"
asm: assembly of C:\Program Files\Go\src\internal\bytealg\compare_amd64.s failed (exit status 2)
 
dlv 1.9.1 
go 1.19.3  windows 64 bits

**Comment by aarzilli** [comment]
This is an error with running `go build`, you should report it to https://github.com/golang/go/issues, however the most likely explanation is that your install of go is simply broken.
