### ISSUE TITLE
DWARF unwinding (CFI) fixes

### ISSUE THREAD

**Issue by javierhonduco** [go-delve/delve#3206]
Hi!! First of all, thanks so much for Delve, been using it since I've started using Go and works incredibly well and fast :tada:.

Long story short, we've used some of Delve's code, in particular, the [DWARF CFI parser ](https://github.com/go-delve/delve/blob/d481eabab941a7baafbcd583be72fbc9d60442ed/pkg/dwarf/frame/table.go)which has been working great for us. We've modified this code to suit our needs better, and while working on this we noticed that some of the DWARF opcodes might not be handled correctly, in particular:
- **save/restore opcodes**, which don't restore the CFA appropriately;
- **DWARF expressions**, some of the constants are not correct;

I was wondering why this wasn't noticed before. As far as I understand Delve implements this to debug cgo code exclusively, is this correct? 

I am more than happy to submit PRs for both of these issues in the next few weeks, but first I wanted to bring this up to see if this would be something you would be interested in.

Thanks!!

cc/ @aarzilli @kakkoyun

**Comment by javierhonduco** [comment]
Sounds good! Will aim to send the PRs in a few weeks :). 

For context, I work on [Parca Agent](https://github.com/parca-dev/parca-agent/) project, which is a continuous profiler written in Go which uses BPF to collect stack traces. As we speak I am working on a blog post that will be published tomorrow with all the details, but the gist of it is that currently there's no easy way to profile applications that were compiled without frame pointers. And as you are probably aware, this is a very common toggle that gets disabled by many distros and packagers.

To allow profiling without frame pointers we've developed a BPF-based unwinder that uses information extracted from dwarf unwinding tables. We use quite a bit of Delve's code to do this. Unfortunately, we had to fork it for a variety of reasons, but we plan to upstream all the improvements that we might make, such as the correctness patches I mentioned 😄 

> It's also used for Go but the subset used by Go is small and cgo testing is lacking.

Out of curiosity, do you happen to know when this is the case? I was under the impression that Go unwinding/stack walking could be done with `gopclntab`. Why is DWARF unwinding needed in non-cgo cases?

**Comment by aarzilli** [comment]
> Out of curiosity, do you happen to know when this is the case? I was under the impression that Go unwinding/stack walking could be done with gopclntab. Why is DWARF unwinding needed in non-cgo cases?

It's always used, we could use the spdelta table but we never did, the standard library doesn't have a convenient interface for that and we didn't write one and it's better to minimize dependencies on internals of the go runtime.

**Comment by javierhonduco** [comment]
Just pushed https://github.com/go-delve/delve/pull/3218. Note that this code is dead. The current constants used by Delve are perfectly correct :)

**Comment by javierhonduco** [comment]
For the first issue, [this is the current code we run, adapted to this codebase](https://github.com/javierhonduco/delve/commit/27688551122dbea2abb58e554167de1d907d3b0a). Can open a PR in few days. We need to do this to follow the DWARF spec which specifies that a stack should be used as there could be a series of remember opcodes in a row

**Comment by aarzilli** [comment]
Looks ok, except StateStack shouldn't be exported and prevRegs should be deleted.

**Comment by javierhonduco** [comment]
Good catch, missed pushing the change that removed `prevRegs`
