### ISSUE TITLE
In Apple MacBook Pro M1 chip, dlv 1.20 version exec command will report an error "could not set controlling process: invalid argument"

### ISSUE THREAD

**Issue by hanlei** [go-delve/delve#3210]
1. What version of Delve are you using (`dlv version`)?
dlv version
Delve Debugger
Version: 1.20.0
Build: $Id: 8ec46ee3d275c276b8e7465d69a23399e0e14789 $

2. What version of Go are you using? (`go version`)?
go version
go version go1.18.5 darwin/arm64

3. What operating system and processor architecture are you using?
MacBook Pro with Apple M1 Pro

4. What did you do?
with dlv 1.20.0

dlv --listen=:2345 --headless=true --api-version=2 --accept-multiclient exec ./test

5. What did you expect to see?
with dlv 1.9.0, it's ok :

API server listening at: [::]:2345
2022-12-10T21:02:20+08:00 warning layer=rpc Listening for remote connections (connections are not authenticated nor encrypted)
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1400.0.38.13
 for arm64.
Got a connection, launched process ./test (pid = 88054).

6. What did you see instead?
but using the dlv 1.20.0 version, there may be cases where the service cannot be started

API server listening at: [::]:2345
2022-12-10T21:00:17+08:00 warning layer=rpc Listening for remote connections (connections are not authenticated nor encrypted)
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1400.0.38.13
 for arm64.
Got a connection, launched process /Users/amao/go/src/amao/dlv/test (pid = 88043).
2022-12-10T21:00:17+08:00 error layer=debugger could not set controlling process: invalid argument
could not launch process: invalid argument

**Comment by aarzilli** [comment]
Can you test https://github.com/go-delve/delve/pull/3211?

**Comment by aarzilli** [comment]
Reopening until the fix is merged.
