### ISSUE TITLE
Cannot attach debugger to go process in container in EC2

### ISSUE THREAD

**Issue by danielptm** [go-delve/delve#3216]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

Log output:

```
$  sudo dlv --listen=:2345 --headless=true --api-version=2 attach 17159
API server listening at: [::]:2345
2022-12-12T23:08:20Z warning layer=rpc Listening for remote connections (connections are not authenticated nor encrypted)
could not attach to pid 17159: could not open debug info - debuggee must not be built with 'go run' or -ldflags='-s -w', which strip debug info
$
```

1. What version of Delve are you using (`dlv version`)?
```
$ dlv version
Delve Debugger
Version: 1.20.1
Build: $Id: 96e65b6c615845d42e0e31d903f6475b0e4ece6e $
```
3. What version of Go are you using? (`go version`)?
```
$  go version
warning: GOPATH set to GOROOT (/home/dev/go) has no effect
go version go1.19.3 linux/amd64
$
```

5. What operating system and processor architecture are you using?

```
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
```
7. What did you do?
I build the go project with the below command.
```
go build -gcflags="all=-N -l" -mod vendor -o ./build/output/abc -ldflags "-X $(IL_MOD_PATH).FileVersion=$(VERSION)" ./cmd/abc
```
I run docker-compose up. Everything spins up without problem.
I get the PID of the go process with `docker top my-container`
I run ```sudo dlv --listen=:2345 --headless=true --api-version=2 attach <my-pid>```
I get 
```
API server listening at: [::]:2345
2022-12-12T23:08:20Z warning layer=rpc Listening for remote connections (connections are not authenticated nor encrypted)
could not attach to pid 17159: could not open debug info - debuggee must not be built with 'go run' or -ldflags='-s -w', which strip debug info
```

9. What did you expect to see?
I expect to see console output that does not say the above message.
11. What did you see instead?
I see the above message

**Comment by cao2358** [comment]
how do you resolve this problem ?
