### ISSUE TITLE
ebpf probes don't work after time.Sleep()

### ISSUE THREAD

**Issue by andreimatei** [go-delve/delve#3227]
Introducing a `time.Sleep()` seems to break the ebpf uprobes.
Consider `trace --ebpf` on the program below:
```
sudo ./dlv trace /home/andrei/src/github.com/andreimatei/play/example-go/main.go tracedFunction --ebpf --log --log-output=debugger
```

```
package main

import (
	"fmt"
	"time"
)

func main() {
	i := int64(0)
	for i = 0; i < 5; i++ {
		tracedFunction(i)
	}
	for i = 0; i < 5; i++ {
		tracedFunction(i)
		time.Sleep(time.Second)
	}
}

//go:noinline
func tracedFunction(x int64) {
	fmt.Println(x)
}
```

The output I get looks like this:

```
0
1
2
3
4
0
> (1) main.tracedFunction(0)
> (1) main.tracedFunction(1)
> (1) main.tracedFunction(2)
> (1) main.tracedFunction(3)
> (1) main.tracedFunction(4)
> (1) main.tracedFunction(0)
1
2
3
4
```

So, the probe works fine for the first round of invocations of `tracedFunction` but they don't seem to work after the sleeps start - although the program is still running.
What's mesmerizing is that the duration of the sleep seems to matter. On my machine, durations shorter than 90ms work fine, and then somewhere in between 90ms and 100ms things get weird; sometimes the probe hits for the 7th call, other times is doesn't.

Without `--ebpf`, tracing works as expected.

I'm using Delve from today's `master` at `72c77b1c30fccead4c8d03e9bb9fbe071c156ace`.

**Comment by mayanksingh2298** [comment]
Hi.. Has there been any update on this?
