### ISSUE TITLE
killing delve started with `trace --ebpf` does not kill the debugged program

### ISSUE THREAD

**Issue by andreimatei** [go-delve/delve#3228]
When using `dlv trace --ebpf` and then ctrl-C'ing `dlv`, `dlv` exits but the inferior survives.
This is in contrast to `dlv trace --ebpf=false`, where killing `dlv` also kills the inferior. I assumed killing it is the desired behavior.

I'm using Delve from today's master at 72c77b1c30fccead4c8d03e9bb9fbe071c156a.

**Comment by mayanksingh2298** [comment]
I want to use `dlv trace` but not kill the inferior process as I Ctrl-C `dlv`. 
Is this possible with delve?
