### ISSUE TITLE
can't figure out source-list-* configs

### ISSUE THREAD

**Issue by thockin** [go-delve/delve#3238]
1. What version of Delve are you using (`dlv version`)?

```
$ dlv version
Delve Debugger
Version: 1.20.1
Build: $Id: 96e65b6c615845d42e0e31d903f6475b0e4ece6e $
```

2. What version of Go are you using? (`go version`)?

```
$ go version
go version go1.19.1 linux/amd64
```

3. What operating system and processor architecture are you using?

Linux AMD64

Trying to use the color configs, and having 2 different problems.

First, I started by uncommenting the examples I found somewhere:

```
source-list-keyword-color: "\x1b[0m"
source-list-string-color: "\x1b[92m"
source-list-number-color: "\x1b[0m"
source-list-comment-color: "\x1b[95m"
source-list-arrow-color: "\x1b[93m"
```

This does some coloring but not readable for me.  I want to change it:

```
(dlv) config -list
...
source-list-line-color    <nil>
source-list-arrow-color   "\x1b[93m"
source-list-keyword-color "\x1b[0m"
source-list-string-color  "\x1b[92m"
source-list-number-color  "\x1b[0m"
source-list-comment-color "\x1b[95m"
...

(dlv) config source-list-string-color "\x1b[96m"

(dlv) config -list
...
source-list-arrow-color   "\x1b[93m"
source-list-keyword-color "\x1b[0m"
source-list-string-color  "\"\\x1b[96m\""
source-list-number-color  "\x1b[0m"
source-list-comment-color "\x1b[95m"
...
```

Not the extra quotes.  Weird that I can't cut-paste the output to the input.  OK:

```
(dlv) config source-list-string-color \x1b[96m

(dlv) config -list
...
source-list-line-color    <nil>
source-list-arrow-color   "\x1b[93m"
source-list-keyword-color "\x1b[0m"
source-list-string-color  "\\x1b[96m"
source-list-number-color  "\x1b[0m"
source-list-comment-color "\x1b[95m"
...
```

OK, so how am I supposed to do this?

Second problem: `source-list-line-color` looks interesting

```
(dlv) config source-list-line-color 35
Command failed: unsupported type for configuration key "source-list-line-color"

(dlv) config source-list-line-color "\x1b[35m"
Command failed: unsupported type for configuration key "source-list-line-color"

(dlv) config source-list-line-color \x1b[35m
Command failed: unsupported type for configuration key "source-list-line-color"
```

I have no clue what to put here.

Any help someone can offer?

**Comment by derekparker** [comment]
Seems like an issue with how we parse this particular config value in the CLI.

If you try setting this directly from the config file, does that work for you? In the meantime I'll work on a fix for this particular issue. Thanks for raising it!

**Comment by thockin** [comment]
Both source-list-line-color and the rest seem to work from the config file.  My actual colors don't seem to match the documented ANSI colors, so I was going to play, but there's not `config -reload` command (another feature request?) so it's tedious to quit and restart over and over.

The thing I was actually looking for was a way to highlight the current line, a la vim `cursorline`.  Sometimes the distance between `=>` and the code is wide enough to make it hard to see.  Does such a thing exist?

**Comment by thockin** [comment]
Looking at pkg/terminal/terminal.go I see it configures `t.stdout.colorEscapes` once, but if the config is changed within dlv, it doesn't seem to get updated?

**Comment by derekparker** [comment]
> Looking at pkg/terminal/terminal.go I see it configures `t.stdout.colorEscapes` once, but if the config is changed within dlv, it doesn't seem to get updated?

That's correct, it doesn't. I have a local patch I'm working on which fixes that as well.

**Comment by thockin** [comment]
Poking around I did this, if it helps:  https://github.com/go-delve/delve/pull/3239
