### ISSUE TITLE
losing breakpoints

### ISSUE THREAD

**Issue by thockin** [go-delve/delve#3241]
1. What version of Delve are you using (`dlv version`)?

```
$ dlv version
Delve Debugger
Version: 1.20.1
Build: $Id: 96e65b6c615845d42e0e31d903f6475b0e4ece6e $
```

2. What version of Go are you using? (`go version`)?

```
$ go version
go version go1.19.1 linux/amd64
```

3. What operating system and processor architecture are you using?

Linux AMD64

I have this this several times now.  I'm debugging, walking thru code, setting breakpoints and conditions, maybe restarting, and suddenly one of my breakpoints stops firing.  When I list breakpoints, it is still there, but the address is 0x0.

```
Breakpoint 1 (enabled) at 0x0 for main.getPackages() ./main.go:99 (1)
```

I do not yet have a clean repro.

**Comment by aarzilli** [comment]
I've seen this too, it happens on restart but I'm not sure under what circumstances.

**Comment by aarzilli** [comment]
I haven't seen this in a while. I think there was briefly a bug in the restart code that deleted disabled breakpoints that was fixed over the course of merging the multi-process set of patches. So I'm closing this one.
