### ISSUE TITLE
Miscalculated breakpoint address results in skipped breakpoint

### ISSUE THREAD

**Issue by nh731685** [go-delve/delve#3261]
Environment:
* Delve Debugger Version: 1.20.1 Build: Id: 96e65b6c615845d42e0e31d903f6475b0e4ece6e
* go version go1.18.3 linux/amd64
* CentOS Linux release 7.9.2009 (Core)
* x86_64

I compiled the below program without optimization, ran it in Delve, and set a breakpoint on the call to `w.foo(w)`. The breakpoint didn't trigger. Neighboring breakpoints do trigger. Stepping also does not stop at that line.

Precise steps:
Create "bug.go":
```
package main

type mystruct struct {
	w *mystruct
}

func main() {
	w := &mystruct{
		w: &mystruct{},
	}
	i := 0
	if w.w == nil {
		if i == 0 {
		}
	}
	w.foo(w)
}

func (w *mystruct) foo(_ *mystruct) {
}
```
Run:
```
go mod init example.com/main
go mod tidy
go build -gcflags="all=-N -l" .
dlv exec ./main
b bug.go:16
breakpoints
c
```
Result:
Program exited without stopping at the breakpoint.
```
$ dlv exec ./main
Type 'help' for list of commands.
(dlv) b bug.go:16
Breakpoint 1 set at 0x45b54f for main.main() ./bug.go:16
(dlv) breakpoints
Breakpoint runtime-fatal-throw (enabled) at 0x430320 for runtime.throw() <PATH>/1.18/go/src/runtime/panic.go:982 (0)
Breakpoint unrecovered-panic (enabled) at 0x4306e0 for runtime.fatalpanic() <PATH>/1.18/go/src/runtime/panic.go:1065 (0)
	print runtime.curg._panic.arg
Breakpoint 1 (enabled) at 0x45b54f for main.main() ./bug.go:16 (0)
(dlv) c
Process 26878 has exited with status 0
```

Expected result:
I expected that a breakpoint on line 16 (`w.foo(w)`) would work as well as one on line 12 (`if w.w == nil`) or line 17 (`}`) which both work.

Working example, using line 17 instead of line 16:

```
$ dlv exec ./main
Type 'help' for list of commands.
(dlv) b bug.go:17
Breakpoint 1 set at 0x45b565 for main.main() ./bug.go:17
(dlv) breakpoints
Breakpoint runtime-fatal-throw (enabled) at 0x430320 for runtime.throw() <PATH>/1.18/go/src/runtime/panic.go:982 (0)
Breakpoint unrecovered-panic (enabled) at 0x4306e0 for runtime.fatalpanic() <PATH>/1.18/go/src/runtime/panic.go:1065 (0)
	print runtime.curg._panic.arg
Breakpoint 1 (enabled) at 0x45b565 for main.main() ./bug.go:17 (0)
(dlv) c
> main.main() ./bug.go:17 (hits goroutine(1):1 total:1) (PC: 0x45b565)
    12:		if w.w == nil {
    13:			if i == 0 {
    14:			}
    15:		}
    16:		w.foo(w)
=>  17:	}
    18:	
    19:	func (w *mystruct) foo(_ *mystruct) {
    20:	}
    21:	
(dlv) 
```

Note that the 20 line program is as short as I could make it while still reproducing the bug; yes it's quite silly once condensed this far. To reproduce the bug, it is necessary for foo to be a method receiver. It is necessary for foo to accept an argument. It is necessary for the call to foo to follow an if statement. It is necessary for the if statement to evaluate a struct pointer. It is necessary for a variable declaration to immediately preceed the if statement. If you change any of that, breakpoints or stepping both stop at line 16 as expected.

If I step-instruction starting from line 12, I can see that the breakpoint address for line 16 is miscalculated. Delve set the breakpoint at "0x45b54f" whereas the unconditional instructions that perform line 16 begin one instruction later at "0x45b551". Instruction "0x45b54f" is jumped over, and thus the line's breakpoint doesn't trigger:

```
(dlv) si
> main.main() ./bug.go:12 (PC: 0x45b54b)
	bug.go:12	0x45b53c*	488b4c2418	mov rcx, qword ptr [rsp+0x18]
	bug.go:12	0x45b541	8401		test byte ptr [rcx], al
	bug.go:12	0x45b543	48833900	cmp qword ptr [rcx], 0x0
	bug.go:12	0x45b547	7502		jnz 0x45b54b
	bug.go:12	0x45b549	eb02		jmp 0x45b54d
=>	bug.go:12	0x45b54b	eb04		jmp 0x45b551
	bug.go:13	0x45b54d	eb00		jmp 0x45b54f
	bug.go:16	0x45b54f*	eb00		jmp 0x45b551
	bug.go:16	0x45b551	488b5c2418	mov rbx, qword ptr [rsp+0x18]
	bug.go:16	0x45b556	488b442418	mov rax, qword ptr [rsp+0x18]
	bug.go:16	0x45b55b	0f1f440000	nop dword ptr [rax+rax*1], eax
(dlv) si
> main.main() ./bug.go:16 (PC: 0x45b551)
	bug.go:12	0x45b547	7502		jnz 0x45b54b
	bug.go:12	0x45b549	eb02		jmp 0x45b54d
	bug.go:12	0x45b54b	eb04		jmp 0x45b551
	bug.go:13	0x45b54d	eb00		jmp 0x45b54f
	bug.go:16	0x45b54f*	eb00		jmp 0x45b551
=>	bug.go:16	0x45b551	488b5c2418	mov rbx, qword ptr [rsp+0x18]
	bug.go:16	0x45b556	488b442418	mov rax, qword ptr [rsp+0x18]
	bug.go:16	0x45b55b	0f1f440000	nop dword ptr [rax+rax*1], eax
	bug.go:16	0x45b560	e81b000000	call $main.(*mystruct).foo
	bug.go:17	0x45b565	488b6c2440	mov rbp, qword ptr [rsp+0x40]
	bug.go:17	0x45b56a	4883c448	add rsp, 0x48
```

**Comment by derekparker** [comment]
I don't believe this is a bug with Delve, but rather an upstream bug with how the debug information is created, or how the compiler handles generation of assembly for all these empty blocks without optimizations.

You asked Delve to create a breakpoint in `bug.go:16`, looking at the disassembly output the address the breakpoint is set at (`0x45b54f`) is marked as the first instruction of that `file:line` combination, so Delve is doing what you asked it to do.

**Comment by aarzilli** [comment]
FWIW this works correctly in go1.20.
