### ISSUE TITLE
SubstitutePath doesn't work well when debugging remotely

### ISSUE THREAD

**Issue by tttoad** [go-delve/delve#3265]
1. What version of Delve are you using (`dlv version`)?
   v1.20.1

2. What version of Go are you using? (`go version`)?
   v1.19

3. What operating system and processor architecture are you using?
 client: MacOS arm64
 server: windows amd64

4. What did you do?
 Set SubstitutePath value to 
```
{
  "from": "/Users/toad/work",
  "to":"C:\\Users\\toad\\work\\"
}
```
The client's program in "/Users/toad/work/demo/main.go".
The server's program in "C:\\Users\\toad\\work\\demo\\main.go".

5. What did you expect to see?
"/Users/toad/work/demo/main.go” is changed to "C:\\Users\\toad\\work\\demo\\main.go" instead of  "C:\\Users\\toad\\work\\/demo/main.go"

**Comment by derekparker** [comment]
If I'm understanding correctly you are trying to replace the local source location with the remote source location, is that right? This is the incorrect way to use the substitute path rule. The source files are read by the client, not the server, so substituting the path to the sources on the remote server will not work.

Please comment if my understanding is incorrect and I can reopen and investigate.

**Comment by tttoad** [comment]
@derekparker PTAL.

**Comment by derekparker** [comment]
@tttoad where is the source code during compilation? That is what's going to be stored in the binary and what Delve will use to set a breakpoint. If you type `sources` and get the list of source files used during compilation what paths do you see?

**Comment by tttoad** [comment]
@derekparker Both Mac and windows.
The client uses `nvim-dap` to run on mac. It sees the source path as `/Users/toad/work/demo3/main.go`.So the breakpoint path is `"source":{"name":"main.go","path":"/Users/toad/work/demo3/main.go"},"breakpoints":[{"line":13}],"lines":[13]}`.
The `delve` runs on windows.  It sees the source path as `C:\Users\lx\work\demo3\main.go`.So I want to do the path conversion by using the `substitutePath` configuration.
The `delve` converts paths with text replacement only, and does not convert other `/` symbols.(mac and linux use `/`,, but windows uses `\` ).
` If you type sources and get the list of source files used during compilation what paths do you see?`
 It will not be available until I get home.(My windows laptop is at home.

**Comment by derekparker** [comment]
@tttoad Ah, ok. I think what you want is to change the `substitutePath` rule in your DAP launch config rather than in the Delve config. See: https://github.com/golang/vscode-go/blob/master/docs/debugging.md (I know it's not VSCode but vim but I assume nvim-dap has a launch config you can modify?).

**Comment by tttoad** [comment]
@derekparker 
I set the `substitutePath` configuration correctly.
But it does not work as I expected.

**Comment by derekparker** [comment]
Alright, reopening and labeling as a bug, sorry for my misunderstanding. It seems you have configured everything correctly, but the path is not being formatted correctly.

**Comment by derekparker** [comment]
@tttoad can you try not using backslahes? Windows should accept forward slash for path separation as well.

**Comment by tttoad** [comment]
> @tttoad can you try not using backslahes? Windows should accept forward slash for path separation as well.

Thank you, it works.

**Comment by derekparker** [comment]
@tttoad great, going to close this as resolved then.

**Comment by nnarayen** [comment]
@tttoad I have a similar issue with nvim-dap running locally on my machine and connecting to `dlv` running in headless mode on a remote server. Could you provide more detail on how you set up `substitutePath` correctly on the client side? Thanks!

**Comment by tttoad** [comment]
> 
If the local project path is `/Users/xxx/work/demo/main.go` and the remote project path is `/root/demo/main.go`, then the configuration should look like this:
```
	substitutePath = {
			{
				from = "/Users/xxx/work"; 
				to = "/root";
			}
		}
```
Full configuration: 
```
{
		type = 'delve';
		name = 'remote-default';
		request = 'launch';
		mode = "debug";
		program = function()
			return vim.fn.input('Program: ')
		end;
		outputMode = 'remote';
		substitutePath = {
			{
				from = "/Users/toad/work";
				to = "/root";
			}
		},
		args = function()
			local args_string = vim.fn.input('arguments: ')
			-- return vim.split(args_string, " +")
			return util.splitArgs(args_string)
		end
}，
{
		type = 'delve';
		name = 'remote';
		request = 'launch';
		mode = "debug";
		program = function()
			return vim.fn.input('Program: ')
		end;
		outputMode = 'remote';
		substitutePath = {
			function()
				local from_to = vim.split(vim.fn.input('localWorkspace/remoteWorkspace:'), " +")
				return {
					from = from_to[1];
					to = from_to[2];
				}
			end;
		},
		args = function()
			local args_string = vim.fn.input('Arguments: ')
			-- return vim.split(args_string, " +")
			return util.splitArgs(args_string)
		end
	}

```
You can use `-log` to view dlv's logs. 
It displays the result of the conversion.
```
2023-02-07T02:05:30+08:00 debug layer=dap [<- from client]{"seq":2,"type":"request","command":"setBreakpoints","arguments":{"source":{"name":"main.go","path":"/Users/toad/work/demo3/main.go"},"breakpoints":[{"line":13}],"lines":[13]}}
2023-02-07T02:05:30+08:00 debug layer=dap client path=/Users/toad/work/demo3/main.go converted to server path=C:\Users\lx\work\/demo3/main.go

```
