### ISSUE TITLE
Document using pointer expressions to set watch points on arbitrary memory locations

### ISSUE THREAD

**Issue by felixge** [go-delve/delve#3266]
> 1. What version of Delve are you using (`dlv version`)?

Version: 1.20.1

> 2. What version of Go are you using? (`go version`)?

go version go1.20 darwin/arm64

> 3. What operating system and processor architecture are you using?

macOS 12.6.2 / Apple M1 Max

> 4. What did you do?

Try to set a watch point from the dlv cli on an arbitrary memory addr:

```
(dlv) watch -w 0x14000092408
```

I got this memory addr from manually computing an offset against a register, I don't have a variable name I can reference.

> 5. What did you expect to see?

```
(dlv) watch -w 0x14000092408
Watchpoint 0x14000092408 set at 0x14000092408
```

> 6. What did you see instead?

```
(dlv) watch -w 0x14000092408
Command failed: can not watch "0x14000092408"
```

This is a feature request I guess :)

FWIW, I have a [local patch](https://gist.github.com/felixge/73475181d095135683655898756b4c8e) that seems to work. But I figured I check with y'all before trying to tidy that up for submission.

**Comment by derekparker** [comment]
Feel free to submit your patch!

**Comment by aarzilli** [comment]
You can't watch arbitrary addresses because they don't have a type and therefore we don't know how many bytes to watch. You can watch an arbitrary address if you type it:

```
(dlv) watch -w *(*int)(0x14000092408)
```

**Comment by felixge** [comment]
> You can't watch arbitrary addresses because they don't have a type and therefore we don't know how many bytes to watch.

My patch defaults to the arch pointer size. Alternatively watch could also take a `-size` argument similar to `-size `? 

You can watch an arbitrary address if you type it:
> 
> ```
> (dlv) watch -w *(*int)(0x14000092408)
> ```

That works for my use case. And I guess something like this should work for watching a memory region?

```
(dlv) watch -w *([128]byte)(0x14000092408)
```

If that's the case, maybe I can just send a patch to add these kind of examples to the watch documentation?

**Comment by aarzilli** [comment]
> My patch defaults to the arch pointer size. Alternatively watch could also take a `-size` argument similar to `-size `?

I see that and it would be ok to choose an arbitrary size, but it is arbitrary and picking 1 byte instead of 4/8 would be just as valid. I'm against adding a size option, it is no better than the typecast (which we should document better, although it is implied by the rules).

> Is there also a way to watch an arbitrary region of memory? This doesn't seem to work:

No, we would have to start doing things with memory protection to support it instead of using hardware watchpoints.

> Maybe I can just send a patch to add an example like this to the docs?

That would be great.

**Comment by felixge** [comment]
Patch submitted: https://github.com/go-delve/delve/pull/3268
