### ISSUE TITLE
Code does not stop at breakpoints in some condition.

### ISSUE THREAD

**Issue by libinglong** [go-delve/delve#3267]
jack@jackmbp guestbook % dlv version
Delve Debugger
Version: 1.20.1
Build: $Id: 96e65b6c615845d42e0e31d903f6475b0e4ece6e $

jack@jackmbp guestbook % go version
go version go1.19.1 darwin/amd64

```go
package main

import (
	"errors"
	"fmt"
	_ "net/http/pprof"
)

func main() {
	if err := test(); err != nil {
		fmt.Println("heh")
		if !errors.Is(err, nil) {
			fmt.Println("heh")
		}
	}

        # set a breakpoint at the next line
	if err := test(); err != nil {
		fmt.Println("heh")
		if !errors.Is(err, nil) {
			fmt.Println("heh")
		}
	}
}

func test() error {
	return nil
}
```

Following the comment to set a breakpoint. Code does not stop at the breakpoint.

**Comment by aarzilli** [comment]
This is a problem with the go compiler but it has been fixed already in 1.20.
