### ISSUE TITLE
Support go 1.20.1 WARNING: undefined behavior - version of Delve is too old for Go version 1.20.1 (maximum supported version 1.19)

### ISSUE THREAD

**Issue by donhuvy** [go-delve/delve#3280]
```go
package main

import "fmt"

func main() {
	s := []string{"a", "b", "c"}
	for i, v := range s {
		fmt.Printf("Index = %d, value = %s.\n", i, v)
	}
}
```

Error

```
WARNING: undefined behavior - version of Delve is too old for Go version 1.20.1 (maximum supported version 1.19)
```
![image](https://user-images.githubusercontent.com/1328316/219253563-f8429335-17f2-4136-b78e-79a8850d993b.png)

![image](https://user-images.githubusercontent.com/1328316/219253650-4e026ed9-2275-4ef2-83a1-dea1c3a3cede.png)

IDE

```
GoLand 2022.3.2
Build #GO-223.8617.58, built on January 27, 2023
Licensed to Nga Do Thi
Subscription is active until April 4, 2023.
For educational use only.
Runtime version: 17.0.5+1-b653.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2002M
Cores: 8
Registry:
    suggest.all.run.configurations.from.context=true
    ide.completion.variant.limit=500
```
Related https://youtrack.jetbrains.com/issue/GO-13234/Update-dlv-version-in-GoLand-for-support-go-1.19-when-dlv-will-be-ready

https://stackoverflow.com/questions/74072271/goland-2022-2-4-delve-panic-version-of-delve-is-too-old-for-go-version-1-19-0

**Comment by aarzilli** [comment]
The current version of delve supports Go 1.20. You need to report this to jetbrains, there's probably something wrong with your install.

**Comment by icetech233** [comment]
big  bug
