### ISSUE TITLE
Official install directions do not work on Mac OS

### ISSUE THREAD

**Issue by iMacker2020** [go-delve/delve#3282]
1. What version of Delve are you using (`dlv version`)? 1.20.1
2. What version of Go are you using? (`go version`)? 1.20.1
3. What operating system and processor architecture are you using? Mac OS 12.3.1 ARM64
4. What did you do?  git clone https://github.com/go-delve/delve
 cd delve
 go install github.com/go-delve/delve/cmd/dlv
5. What did you expect to see? I expected Delve to install and work.
6. What did you see instead? I saw no messages. Delve did not work. I even opened a new terminal window. Delve was not found. I don't think it was installed.

The only way I was able to install Delve was to use this command: sudo GOBIN=/usr/local/go/bin go install github.com/go-delve/delve/cmd/dlv@latest

**Comment by aarzilli** [comment]
The install instructions are fine. See `go help install` as well as documentation of your shell regarding the PATH environment variable.

**Comment by aarzilli** [comment]
You would have to propose this to golang/go.
