### ISSUE TITLE
windows 10 install failed

### ISSUE THREAD

**Issue by GanBob** [go-delve/delve#3301]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

If this is about source listing not showing up (or breakpoints not being
accepted) while running in a container please read our
[FAQ](https://github.com/go-delve/delve/blob/master/Documentation/faq.md#substpath)
first.

1. What version of Delve are you using (`dlv version`)?
Version: 1.20.1

2. What version of Go are you using? (`go version`)?
go version go1.20 windows/amd64

3. What operating system and processor architecture are you using?
windows10 amd64

4. What did you do?
go install

5. What did you expect to see?
install succecss

6. What did you see instead?
service/dap/server.go:1414:27 cannot use dap.Source{...} as *dap.Source value in assignment

**Comment by aarzilli** [comment]
Delve builds correctly, what did you do exactly?

**Comment by stoffeastrom** [comment]
My guess is @GanBob is upgrading dependencies and hence get the https://github.com/google/go-dap/releases/tag/v0.7.0 version which is not compatible with current delve version. Fortunately it's fixed https://github.com/go-delve/delve/pull/3237 here. So until there is a new release I propose you downgrade `go-dap`

```sh
go get github.com/google/go-dap@v0.6.0
```

**Comment by aarzilli** [comment]
Closing, likely user error.
