### ISSUE TITLE
mannual compiled delve cant be use on aarch64

### ISSUE THREAD

**Issue by MansonLuo** [go-delve/delve#3321]
Please answer the following before submitting your issue:
after mannuly compile delve.

run "dlv debug main.go",the terminal didnt response or output anything for a long time

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.
below is my steps for mannully compile delve.
git clone https://github.com/go-delve/delve.git
cd delve/cmd/dlv
go build
go install

If this is about source listing not showing up (or breakpoints not being
accepted) while running in a container please read our
[FAQ](https://github.com/go-delve/delve/blob/master/Documentation/faq.md#substpath)
first.

1. What version of Delve are you using (`dlv version`)?  
version: 1.20.1
3. What version of Go are you using? (`go version`)?
go1.20.2
5. What operating system and processor architecture are you using?
android, aarch64
7. What did you do?
debug a simple go program
9. What did you expect to see?
cant see dlv terminal after run dlv debug main.go
(dlv)
11. What did you see instead?
see nothing after long time

**Comment by aarzilli** [comment]
We do not support android.
