### ISSUE TITLE
default name of output binary causes confusing behavior when delve is run twice from the same directory

### ISSUE THREAD

**Issue by valscale** [go-delve/delve#3345]
Up front: we are using a slightly forked version of Go; feel free to close as WONTFIX but it seems like something that would likely be present with mainline go.

I am running "dlv debug" simultaneously on two processes, one named "tailscale" and one named "tailscaled". Twice today I have restarted dlv, hit "c" to run, and gotten an error message from the binary I am debugging in my OTHER dlv session.

AFAICT, this happens when I kill and restart dlv while the other dlv session is running.

Specific steps:

1. The "tailscaled" process is running in the first dlv.
2. The "tailscale" process in the second dlv has run and exited.
3. I quit the first dlv with "tailscaled" and restart it with exactly the same arguments and source. I type "c" to run it and it is running, waiting for API calls.
4. In the second dlv, I type "r" to restart the "tailscale" process. I then type "c" to run it.
5. At this point, I get an error message saying I've passed invalid command line arguments. It's the error message from the code I am debugging in the OTHER dlv session.
6. If I then quit the first dlv session, restart it with the exact same arguments and source, and type "c", I get an error message from the code I am debugging in the second dlv session.

1. What version of Delve are you using (`dlv version`)? 1.20.1
2. What version of Go are you using? (`go version`)? go1.20.3-tsddff070 (1.20.3 with some tailscale specific patches)
3. What operating system and processor architecture are you using? MacOS 13.3.1, arm64
4. What did you do? Quit and restarted dlv while running another dlv session simultaneously, then ran the program.
5. What did you expect to see? The output from the source code I specified on the command line.
6. What did you see instead? The output from the source code I specified in the OTHER dlv session currently running.

**Comment by aarzilli** [comment]
If you can reproduce this (semi)reliably you could reproduce it with `--log --log-output=gdbwire` so we could see what is happening.
