### ISSUE TITLE
expected 'EOF', found cmd

### ISSUE THREAD

**Issue by stephane-archer** [go-delve/delve#3352]
with `cmd := exec.Command("ssh", hostname, shellCommand)`
```
(dlv) print cmd.ProcessState.ExitCode()
Command failed: function calls not allowed without using 'call'
(dlv) print call cmd.ProcessState.ExitCode()
Command failed: 1:6: expected 'EOF', found cmd
```

1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 1.20.2
Build: $Id: e0c278ad8e0126a312b553b8e171e81bcbd37f60 $
```
3. What version of Go are you using? (`go version`)?
```
go version go1.20.3 darwin/amd64
```
5. What operating system and processor architecture are you using?
```
darwin/amd64
```

**Comment by aarzilli** [comment]
```(dlv) call cmd.ProcessState.ExitCode()```
