### ISSUE TITLE
[Feature Request] Allow substitute-path when the "from" file path is not in the debug binary sources

### ISSUE THREAD

**Issue by r-hang** [go-delve/delve#3385]
**Summary of Proposed Feature**

Support substitutePath replacements when the “from” file path is not in the file sources in the debug binary but the “to” file path is in the file sources in the debug binary. Today, substitute-paths are only a factor in the [NormalLocationSpec](https://github.com/go-delve/delve/blob/master/pkg/locspec/locations.go#L374) case.

**Triage Survey**

1. What version of Delve are you using (`dlv version`)? 1.20.1

2. What version of Go are you using? (`go version`)? 1.20.4

3. What operating system and processor architecture are you using? darwin, arm64

4. What did you do?
```
# after successfully connecting to the dlv server
# (dlv) sources # lists bazel-out/darwin_arm64-dbg-ST-eccb913b7463/bin/root/a/gen_/source_gen.go

> (dlv) config substitute-path root/a/source.go bazel-out/darwin_arm64-dbg-ST-eccb913b7463/bin/root/a/gen_/source_gen.go
> (dlv) break root/a/source.go:11
> "root/a/source.go:11" not found
```

5. What did you expect to see? A message that a breakpoint was successfully created

6. What did you see instead? "root/a/source.go:11" not found

**Background**

My build system ‘dlv exec’s a headless server from a Bazel built debug binary that clients (e.g. dlv cli, VSCode) establish a remote connection to. 

I have a root/a/source.go in my repository that our build system (Bazel) uses as a source for a code generator and also replaces the root/a/source.go with a code generated source_gen.go in the final compiled binary. 

The generated file is a drop-in replacement for the original source file. All line positions that are valid breakpoint positions in the source file are also valid breakpoint positions in the generated file – the code generation step is essentially an append operation to the original file. However, this leads to an interesting situation where debug clients (e.g. dlv cli, VSCode) only see the source (root/a/source.go) file but this specific file path is not known to the debug server.

Summary Snippet
```
source files:
- root/main.go
- root/a/source.go

files compiled into to debug binary after build system code generation and processing:
- root/main.go
- bazel-out/darwin_arm64-dbg-ST-eccb913b7463/bin/root/a/gen_/source_gen.go
```

Through the use of `config substitute-path` I would like breakpoint requests to `root/a/source.go` to substitute to the `bazel-out/darwin_arm64-dbg-ST-eccb913b7463/bin/root/a/gen_/source_gen.go`
 file actually compiled into the debug binary.

Tracing the logic, I don’t believe delve supports this behavior yet. The implementation for [locspec.Parse](https://github.com/go-delve/delve/blob/master/service/debugger/debugger.go#L722) only honors substitute-paths when the “from” file [is known to the debug binary](https://github.com/go-delve/delve/blob/master/pkg/locspec/locations.go#L380).

**Proposed Solution**

I propose modifying the [path lookup logic](https://github.com/go-delve/delve/blob/master/pkg/locspec/locations.go#L374) to produce breakpoint location candidate files when the “to” file is a match to something in the debug binary, regardless of what the “from” file path is. I’ve [prototyped this idea](https://github.com/r-hang/delve/pull/1/files) and I am able to set breakpoints where the “from” path is not known to the debug binary. I’ll put up a formal PR against delve if this idea seems reasonable.

The result after my proposed change
```
# after successfully connecting to the dlv server
# (dlv) sources # lists bazel-out/darwin_arm64-dbg-ST-eccb913b7463/bin/root/a/gen_/source_gen.go

(dlv) config substitute-path root/a/source.go bazel-out/darwin_arm64-dbg-ST-eccb913b7463/bin/root/a/gen_/source_gen.go
(dlv) break root/a/source.go:11
Breakpoint 1 set at 0x100cb254c for … bazel-out/darwin_arm64-dbg-ST-eccb913b7463/bin/root/a/gen_/source_gen.go:11
```

An additional note: I plan to use delve as a library to parse debug binaries to generate mappings between source and debug path as part of a system that I’m creating. I believe delve is the right place to make this change over IDE specific plugins because a change here would provide support for this functionality across multiple debugger clients (dlv cli, VSCode, etc…) and drop the need to re-implement this logic across multiple clients.

**Comment by aarzilli** [comment]
Regarding this:

> I believe delve is the right place to make this change over IDE specific plugins because a change here would provide support for this functionality across multiple debugger clients (dlv cli, VSCode, etc…) and drop the need to re-implement this logic across multiple clients.

If I understand this correctly, this is wrong: the path substitution configuration is client side. It can never be server side because, in principle, the server doesn't know where the sources are on the client and different client may have sources located at different paths.

Further discussion: https://github.com/go-delve/delve/issues/3333

**Comment by r-hang** [comment]
Thank you for your prompt reply! Yes, I can confirm the swapping the paths in the substitute-path command resolves the issue.

It also makes sense to me that path-substitution should be a client-side only concern.
