### ISSUE TITLE
Potential leak in starlark.go

### ISSUE THREAD

**Issue by hhheiaenia** [go-delve/delve#3393]
I notice the ctx.Done() needs a cancel function to unblock the statement of ctx.Done in https://github.com/go-delve/delve/blob/master/pkg/terminal/starbind/starlark.go#LL291C21-L291C21, since the case may block forever if the case not met.
  I was wondering if this may leak the goroutine where the ctx.Done() locates?

Maybe what I said is not right, thank you for taking a look.

**Comment by aarzilli** [comment]
That select statement is non-blocking, the default branch is taken if Done isn't closed.

**Comment by aarzilli** [comment]
Close, not an issue.
