### ISSUE TITLE
delve Failed to build in RISC-V architecture

### ISSUE THREAD

**Issue by mstsky115** [go-delve/delve#3437]
[  144s] + go build -mod=vendor -buildmode=pie -o dlv ./cmd/dlv
[  145s] service/debugger/debugger.go:32:2: found packages native (dump_linux.go) and your_linux_architecture_is_not_supported_by_delve (support_sentinel_linux.go) in /home/abuild/rpmbuild/BUILD/delve-1.21.0/pkg/proc/native
[  145s] error: Bad exit status from /var/tmp/rpm-tmp.2bO3nb (%build)

**Comment by aarzilli** [comment]
RISC-V is not supported.

**Comment by mstsky115** [comment]
> 不支持 RISC-V。

Are there many things that need to be changed if riscv is to be supported, such as what?

**Comment by aarzilli** [comment]
A backend for RISC-V needs to be written. For example this is the commit adding ppc64 support: https://github.com/go-delve/delve/commit/71f12207175a1cc09668f856340d8a543c87dcca.

**Comment by mstsky115** [comment]
> A backend for RISC-V needs to be written. For example this is the commit adding ppc64 support: [71f1220](https://github.com/go-delve/delve/commit/71f12207175a1cc09668f856340d8a543c87dcca).

Wow, that's a lot. I thought if it was less, I could try it. It looks a lot now. I don't think I'm good at it. Then may I ask when you plan to support riscv?

**Comment by lrzlin** [comment]
@mstsky115 Hi, there is an initial RISC-V support if you still needed:  [delve: add linux-riscv64 support](https://github.com/go-delve/delve/pull/3785).
