### ISSUE TITLE
dlv test - symbols from the same package undefined

### ISSUE THREAD

**Issue by m-kru** [go-delve/delve#3440]
1. `Version: 1.21.0`
2. `go version go1.20.4 linux/amd64`
3. `Linux riis 5.15.0-76-generic 83~20.04.1-Ubuntu SMP Wed Jun 21 20:23:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

I have package in my go project under path `internal/token/`.  I try to run tests from one of the files of this package using `dlv test internal/token/parse_test.go`.  However, the command fails with following errors:
```
internal/token/parse_test.go:17:4: undefined: Stream
internal/token/parse_test.go:18:5: undefined: Token
internal/token/parse_test.go:18:17: undefined: NEWLINE
```
All of these 3 symbols are defined in the same package. 

When I try to run all tests using dlv I get
```
no Go files in /home/user/project
exit status 1
```
I lack ideas what might be wrong, as my project contains `go.mod` file and I do not have any problems running go commands.

**Comment by aarzilli** [comment]
If you specify a file on the command line only that file will be compiled. The same thing happens with `go test`.
