### ISSUE TITLE
"net/http" debugging not supported

### ISSUE THREAD

**Issue by haoside666** [go-delve/delve#3452]
1.What version of Delve are you using (dlv version)?
$ dlv version       
Delve Debugger
Version: 1.21.0
Build: $Id: fec0d226b2c2cce1567d5f59169660cf61dc1efe $

2.What version of Go are you using? (go version)?
go version go1.20.3 linux/amd64

3.What operating system and processor architecture are you using?
linux/amd64

4.What did you do?
    Debugging a program that import "net/http".
    I've tried many programs and found that as soon as import "net/http", dlv will show no source available, which is really bad!
Here is a simple example:
$ cat main.go    
package main
import "fmt"
import "net/http"
func main() {
	http.HandleFunc("/user", func (writer http.ResponseWriter, request *http.Request) {fmt.Fprintln(writer, "user") })
	if err := http.ListenAndServe("127.0.0.1:8080", nil); err != nil {
		defer func() {
			fmt.Println("http server start failed, err:", err)
		}()
	}

}
$  http dlv debug main.go 
Type 'help' for list of commands.
(dlv) b main.main
Breakpoint 1 set at 0x774b4f for main.main() ./main.go:4
(dlv) r
Process restarted with PID 12202
(dlv) n
Stopped at: 0x7f6374e6c100
=>   1:	no source available
Command failed: no source for PC 0x7f6374e6c100
(dlv)

5.What did you expect to see?
    I expect my web program to be debugged so that I can identify problems.

**Comment by aarzilli** [comment]
Use `continue` instead of `next`.

**Comment by casatwy** [comment]
meet same problem, and I'm using macOS 14.1.1 sonoma, xcode 15 installed.
[use `continue` instead of `next`] not works.

![截屏2023-11-11 00 08 40](https://github.com/go-delve/delve/assets/1005781/8ebc209b-6893-4465-bd10-6e4aecda7ff3)
