### ISSUE TITLE
How to watch interface create?

### ISSUE THREAD

**Issue by zhaoxueye** [go-delve/delve#3466]
There are many http. Handler interfaces, how can I know when they were created?
struct a, struct b, struct c ... are http.Handler interfaces. They implemented the ServeHTTP method. Although they have their own creation methods, but I don't know. I want to monitor where they were created. The only useful information is that they have all implemented the ServeHTTP method, they are http.Handler interfaces.

**Comment by aarzilli** [comment]
You have to provide more context.

**Comment by zhaoxueye** [comment]
> There are many http. Handler interfaces, how can I know when they were created?

struct a, struct b, struct c ... are http.Handler interfaces. They implemented the ServeHTTP method. Although they have their own creation methods, but I don't know. I want to monitor where they were created. The only useful information is that they have all implemented the ServeHTTP method, they are http.Handler interfaces.

**Comment by aarzilli** [comment]
There is no way to do this. An object that implements te http.Handler interface could be created with the literal struct syntax `&someHandler{ ... }` which does not produce the call. And converting and existing object to http.Handler does not produce a call to anything either.
