### ISSUE TITLE
Debugger hangs with Go 1.21

### ISSUE THREAD

**Issue by JobberRT** [go-delve/delve#3472]
1. What version of Delve are you using (`dlv version`)?
`GoLand bundled dlv 1.21.0 and custom installed dlv 1.21.0`
3. What version of Go are you using? (`go version`)?
`Go 1.19 ~ Go 1.21.0`
4. What operating system and processor architecture are you using?
`macOS 13 with M1 CPU`
6. What did you do?
`Not quite remember, but I upgrade Go to 1.21.0 and GoLand to 2023.2 latest`
8. What did you expect to see?
`Normally debug and pause on breakponit`
10. What did you see instead?
```
1. When debugging a single thread program, everything worked
2. When debugging a multi-thread program, if there's no breakponit set, dlv will hang on a certain line of code(fastjson.Parse). If there's breakpoints set before and after that line of code, dlv will stuck when passing the BEFORE breakpoint and stuck at that line of code.
3. Before upgrading GoLand(which also is basically dlv) and go, everything worked. After upgrading GoLand, nothing worked and downgrading GoLand/Go Version/ dlv won't help
```

This is my first issue about delve, I don't know if dlv has some log file or what and can only provide as detailed information as I can, if there's some kind of information I can provide please tell me and I will post it here.

**Comment by aarzilli** [comment]
What's the output of `--log --log-output=gdbwire`?

**Comment by derekparker** [comment]
@JobberRT do you have any more information to provide here?

**Comment by JobberRT** [comment]
@derekparker 

I'm sorry, although I haven't solved this problem, due to my recent busy work schedule, I don't have the time to investigate further. I've decided to close this issue for now and will open a new one with a more detailed problem description when I have the time in the future.
