### ISSUE TITLE
default action for "Warning: debugging optimized function"

### ISSUE THREAD

**Issue by shawndx** [go-delve/delve#3484]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

If this is about source listing not showing up (or breakpoints not being
accepted) while running in a container please read our
[FAQ](https://github.com/go-delve/delve/blob/master/Documentation/faq.md#substpath)
first.

1. What version of Delve are you using (`dlv version`)? 
              Version: 1.20.1
2. What version of Go are you using? (`go version`)?
              go version go1.20.5 linux/amd64
3. What operating system and processor architecture are you using?
              debian-8
4. What did you do?
              keep hitting the "debugging optimized function" warning when stepping into function calls, and keep press "[c] continue" to move on.
5. What did you expect to see?
              Could delve be featured an action for setting the default choice, say I'd like to continue every time.  
6. What did you see instead?

Thanks.

**Comment by aarzilli** [comment]
The "debugging optimized function" warning doesn't stop anything, it's just printed after the debugger stops for another reason inside an optimized function.
