### ISSUE TITLE
dap: strip package paths from variable types

### ISSUE THREAD

**Issue by stefanhaller** [go-delve/delve#3516]
Now that we strip paths from function names in the stacktrace view (since #3500), I want the same for the types of variables in the variables view.

Here's a simple example. With a reasonably sized side bar, I can't see any variable names or values, only the beginnings of the paths:
<img width="1125" alt="image" src="https://github.com/go-delve/delve/assets/1225667/0ace2c0d-9fe8-4cde-a95a-cf8866ea8ab5">

This is how ridiculously wide I would have to make the side bar so that I can see variable names and values (impractical on a laptop screen):
<img width="1125" alt="image" src="https://github.com/go-delve/delve/assets/1225667/735cebb2-7463-464a-9f61-543226429334">

This is what I would like to see instead:
<img width="1125" alt="image" src="https://github.com/go-delve/delve/assets/1225667/d8be1496-572b-47f4-914b-dde76231c885">

I'd be interested in working on this, but it looks a lot less straighforward than #3500 was, so I'd need some guidance.

**Comment by aarzilli** [comment]
> I'd be interested in working on this, but it looks a lot less straighforward

It is. Gdlv does something like this but it doesn't work in all cases with generics, if it's the type is too complicated it gives up: https://github.com/aarzilli/gdlv/blob/master/internal/prettyprint/short.go

**Comment by stefanhaller** [comment]
@aarzilli This is very helpful, thanks. Would you be ok with reusing that code here?

However, when I said I need help I didn't only mean the algorithm to shorten the types, but also where in the code to do this. I suppose it needs to be in various places inside of [`childrenToDAPVariables`](https://github.com/go-delve/delve/blob/899ba72505492eb555e21f09151c3a409d7745aa/service/dap/server.go#L2305), but I'm a bit overwhelmed by the complexity of that code, to be honest.

**Comment by aarzilli** [comment]
> @aarzilli This is very helpful, thanks. Would you be ok with reusing that code here?

yes

> However, when I said I need help I didn't only mean the algorithm to shorten the types, but also where in the code to do this. 

I think it's just getTypeIfSupported

**Comment by stefanhaller** [comment]
> I think it's just getTypeIfSupported

I had hoped so too, but unfortunately that's not enough.

**Comment by hyangah** [comment]
cc @suzmue

**Comment by stefanhaller** [comment]
I looked into this some more, and if I'm not mistaken this can't be fixed in `service/dap/server.go` alone. I think this needs to be done in `service/api/prettyprint.go`, and I'm very much lacking the overview over the delve code base to tell what consequences it would have to change code there. Maybe other callers of that code would also benefit from shortening the types names? I really have no idea.

It would be fantastic if a more experienced developer would have the time to look into this and give some guidance; like #3500, it would be a big usability improvement.

**Comment by aarzilli** [comment]
prettyprint is used in several places, it can't be changed unconditionally, but it would be fine to add a flag to it, to simplify type names.

**Comment by suzmue** [comment]
This would definitely be a big improvement. We have a similar request filed in the vscode-go extension issue tracker: golang/vscode-go#2569

I have a similar wip change that removes the types altogether, but that may be a more controversial change. Shortening the type names would probably need to touch the same places in the code: https://github.com/go-delve/delve/compare/master...suzmue:delve:vartyps

**Comment by stefanhaller** [comment]
Here's a PR: #3535
