### ISSUE TITLE
your_linux_architecture_is_not_supported_by_delve on AARCH64 Raspbian arm64

### ISSUE THREAD

**Issue by Fyb3roptik** [go-delve/delve#3525]
Trying to install on the latest Raspbian which is AARCH64 and getting this error

`your_linux_architecture_is_not_supported_by_delve`

It says AARCH64 is supported but it will not install

**Comment by aarzilli** [comment]
Fill the new issue form.

**Comment by aarzilli** [comment]
Closing, no user feedbak. Likely either the OS or the version of go installed was arm32 instead of arm64.
