### ISSUE TITLE
Debugging broken after Mac OS Sonoma Update

### ISSUE THREAD

**Issue by tfnaylor** [go-delve/delve#3538]
Delve Version: 1.21.1
Go Version: go1.21.3
XCode Version: 15.01
VSCode Version: : 1.83.1

2019 Macbook Pro (intel)

After installing Mac OS Sonoma, I get the following terminal output when attempting to debug:

*** START OUTPUT ***
runtime: g 23: unexpected return pc for runtime.sigpanic called from 0x2e16009
stack: frame={sp:0xc000083c88, fp:0xc000083cb8} stack=[0xc000083000,0xc000084000)
0x000000c000083b88:  0x00000000010413be <runtime.panicmem+0x000000000000003e>  0x000000c000083c68 
0x000000c000083b98:  0x000000c00051f6c0  0x0000000000000000 
0x000000c000083ba8:  0x000000c000083c58  0x000000000104293f <runtime.gopanic+0x000000000000015f> 
0x000000c000083bb8:  0x0000000000000018  0x000000000000000d 
0x000000c000083bc8:  0x000000000000000d  0x000000000000000d 
0x000000c000083bd8:  0x000000c0003d5a00  0x0000000000000000 
0x000000c000083be8:  0x0000000002053cc0  0x0000000000000000 
0x000000c000083bf8:  0x0000000000000000  0x0000000000000000 
0x000000c000083c08:  0x0000000000000000  0x000000c00051f6c0 
0x000000c000083c18:  0x0000000002bb8070  0x0000000000000000 
0x000000c000083c28:  0x0000000002053cc0  0x0000000002bb8070 
0x000000c000083c38:  0x0000000000000000  0x0000000000000000 
0x000000c000083c48:  0x0000000000000000  0x0000000000000000 
0x000000c000083c58
2023-10-24T11:29:35-06:00 error layer=dap runtime error: EOF
Unable to retrieve goroutines: write tcp 127.0.0.1:50488->127.0.0.1:50489: write: broken pipe
Detaching and terminating target process
*** END OUTPUT ***

At this point debugging is paused and must be manually terminated (using VSCode IDE widget).

I have tried the xcode-select --install command, which has worked in the past with Mac OS updates, but it just tells me the command line tools are already installed and does not resolve the problem.

I would think that a lot of people are running into this but I did not see anything in current issues so I created this one.

**Comment by aarzilli** [comment]
Other people had a similar problem that was solved by reinstalling the command line tools: #3535
Do you always get it? Can you reproduce it using the command line program? What's the output with `--log --log-output=gdbwire`?

**Comment by tfnaylor** [comment]
Thanks for the quick feedback. Unless I am missing something (likely), the referenced pull request doesn't seem to provide information about how to reinstall command line tools and I am not sure how to do this. Is there a handy article you can point me to?

I will try running debug from a command line soon - will need to look this up as well since I rely on VSCode exclusively. Will provide this feedback ASAP.

**Comment by tfnaylor** [comment]
Well, it's fixed but I failed to get the extra debug information you asked for so I apologize for that. 

For anyone who sees this issue and is looking for a fix, here is how I did it:

From the command line: 
xcode-select -p

This gave me the directory where the command line tools live. I manually deleted the contents of that directory then from the command line:
xcode-select --install

This invoked a dialog that reinstalled the tools. After this my debugger started working again.

Hope this helps.

**Comment by ExcitingFrog** [comment]
reinstall xcode and fix it.
if anyone who update macos and this bug occurs, can try this way.

**Comment by gitkrtuck** [comment]
initially I found this solution, but it did not work because "xcode-select -p" does not return the correct path to delete (it displayed a "Developer" directory). However, removing the "CommandLineTools" directory mentioned in issues/3519 did work.

**Comment by RuiEusebio** [comment]
Resolve the issue by reinstalling the Xcode command-line tools; this solution was effective for me.

```
sudo rm -rf /Library/Developer/CommandLineTools
xcode-select --install
```

**Comment by langsen111** [comment]
> 通过重新安装Xcode命令行工具解决问题；这个解决方案对我来说很有效。
> 
> ```
> sudo rm -rf /Library/Developer/CommandLineTools
> xcode-select --install
> ```


I tried this, but it still interrupted unexpectedly.

**Comment by bourke-floyd-pf** [comment]
> > 通过重新安装Xcode命令行工具解决问题；这个解决方案对我来说很有效。
> > ```
> > sudo rm -rf /Library/Developer/CommandLineTools
> > xcode-select --install
> > ```
> 
> I tried this, but it still interrupted unexpectedly.

same. resinstall command line tools had no change
