### ISSUE TITLE
arm coredump bt get wrong stack when nil pointer dereference

### ISSUE THREAD

**Issue by gnlsw** [go-delve/delve#3544]
Please answer the following before submitting your issue:

1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 1.21.1
Build: $Id: a358c02f24aa7047ecc562b0587dc2d08330b2cf $
```

2. What version of Go are you using? (`go version`)?
`go version go1.20.10 linux/arm64`

4. What operating system and processor architecture are you using?
`CentOS Linux release 7.9.2009 (AltArch)`

6. What did you do?
```
package main

func main() {
	var p_value *int = nil
	*p_value = 1
}
```
go build demo.go
print the backtrace when **"panic: runtime error: invalid memory address or nil pointer dereference"**

8. What did you expect to see?
```
./demo
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x65238]
goroutine 1 [running]:
panic({0x75ce0, 0xe12e0})
        /home/wsl/go/go1.20.10/src/runtime/panic.go:987 +0x3ac fp=0x4000160700 sp=0x4000160640 pc=0x3afac
runtime.panicmem()
        /home/wsl/go/go1.20.10/src/runtime/panic.go:260 +0x48 fp=0x4000160720 sp=0x4000160700 pc=0x39a78
runtime.sigpanic()
        /home/wsl/go/go1.20.10/src/runtime/signal_unix.go:841 +0x214 fp=0x4000160760 sp=0x4000160720 pc=0x4fea4
main.main()
        /home/wsl/demo/demo.go:5 +0x8 fp=0x4000160770 sp=0x4000160770 pc=0x65238
runtime.main()
        /home/wsl/go/go1.20.10/src/runtime/proc.go:250 +0x200 fp=0x40001607d0 sp=0x4000160770 pc=0x3d9a0
runtime.goexit()
        /home/wsl/go/go1.20.10/src/runtime/asm_arm64.s:1172 +0x4 fp=0x40001607d0 sp=0x40001607d0 pc=0x62e34
```

`When dlv core demo core_demo_128920, we expect the bt command print the same funcation frame.`

10. What did you see instead?
```
[root@localhost demo_1]# dlv core demo core_demo_128920
Type 'help' for list of commands.
(dlv) bt
 0  0x0000000000063c88 in runtime.raise
    at /home/wsl/go/go1.20.10/src/runtime/sys_linux_arm64.s:158
 1  0x000000000004ff24 in runtime.dieFromSignal
    at /home/wsl/go/go1.20.10/src/runtime/signal_unix.go:883
 2  0x0000000000050428 in runtime.sigfwdgo
    at /home/wsl/go/go1.20.10/src/runtime/signal_unix.go:1096
 3  0x000000000004ef2c in runtime.sigtrampgo
    at /home/wsl/go/go1.20.10/src/runtime/signal_unix.go:432
 4  0x0000000000063c88 in runtime.raise
    at /home/wsl/go/go1.20.10/src/runtime/sys_linux_arm64.s:157
 5  0x000000000004ff24 in runtime.dieFromSignal
    at /home/wsl/go/go1.20.10/src/runtime/signal_unix.go:883
 6  0x000000000003b6e8 in runtime.crash
    at /home/wsl/go/go1.20.10/src/runtime/signal_unix.go:975
 7  0x000000000003b6e8 in runtime.fatalpanic
    at /home/wsl/go/go1.20.10/src/runtime/panic.go:1172
 8  0x000000000003afac in runtime.gopanic
    at /home/wsl/go/go1.20.10/src/runtime/panic.go:987
 9  0x0000000000039a78 in runtime.panicmem
    at /home/wsl/go/go1.20.10/src/runtime/panic.go:260
10  0x000000000004fea4 in runtime.sigpanic
    at /home/wsl/go/go1.20.10/src/runtime/signal_unix.go:841
11  0x0000000000065238 in main.main
    at ./demo_1.go:5
12  0x0000000000065238 in main.main
    at ./demo_1.go:5
13  0x0000000000065238 in main.main
    at ./demo_1.go:5
14  0x0000000000065238 in main.main
    at ./demo_1.go:5
15  0x0000000000065238 in main.main
    at ./demo_1.go:5
16  0x0000000000065238 in main.main
    at ./demo_1.go:5
17  0x0000000000065238 in main.main
    at ./demo_1.go:5
18  0x0000000000065238 in main.main
    at ./demo_1.go:5
19  0x0000000000065238 in main.main
    at ./demo_1.go:5
20  0x0000000000065238 in main.main
    at ./demo_1.go:5
21  0x0000000000065238 in main.main
    at ./demo_1.go:5
22  0x0000000000065238 in main.main
    at ./demo_1.go:5
23  0x0000000000065238 in main.main
    at ./demo_1.go:5
24  0x0000000000065238 in main.main
    at ./demo_1.go:5
25  0x0000000000065238 in main.main
    at ./demo_1.go:5
26  0x0000000000065238 in main.main
    at ./demo_1.go:5
```

**Comment by aarzilli** [comment]
The stack trace you see when you run demo directly is taken at a different time, and in a different code path, than the one you will find inside a core file. The one inside a core file had to ask the operating system to create a core dump.
This is expected.

**Comment by gnlsw** [comment]
The problem is:
Before the nil pointer dereference, the bt is normal.
After the nil pointer dereference, the bt is wrong with endless main.main.
The following content is output of dlv exec demo.*

```
[root@localhost demo]# go env
GO111MODULE="off"
GOARCH="arm64"
```

```
package main

func main() {
	var p_value *int = nil
	*p_value = 1
}
```

`go build demo.go`

```
[root@localhost demo]# dlv exec demo
Type 'help' for list of commands.
(dlv) break main.main
Breakpoint 1 set at 0x65230 for main.main() ./demo.go:5
(dlv) c
> main.main() ./demo.go:5 (hits goroutine(1):1 total:1) (PC: 0x65230)
Warning: debugging optimized function
     1: package main
     2:
     3: func main() {
     4:         var p_value *int = nil
=>   5:         *p_value = 1
     6: }
(dlv) bt
0  0x0000000000065230 in main.main
   at ./demo.go:5
1  0x000000000003d9a0 in runtime.main
   at /home/wsl/go/go1.20.10/src/runtime/proc.go:250
2  0x0000000000062e34 in runtime.goexit
   at /home/wsl/go/go1.20.10/src/runtime/asm_arm64.s:1172
(dlv) n
> [unrecovered-panic] runtime.fatalpanic() /home/wsl/go/go1.20.10/src/runtime/panic.go:1145 (hits goroutine(1):1 total:1) (PC: 0x3b680)
Warning: debugging optimized function
        runtime.curg._panic.arg: interface {}(string) "runtime error: invalid memory address or nil pointer dereference"
  1140: // fatalpanic implements an unrecoverable panic. It is like fatalthrow, except
  1141: // that if msgs != nil, fatalpanic also prints panic messages and decrements
  1142: // runningPanicDefers once main is blocked from exiting.
  1143: //
  1144: //go:nosplit
=>1145: func fatalpanic(msgs *_panic) {
  1146:         pc := getcallerpc()
  1147:         sp := getcallersp()
  1148:         gp := getg()
  1149:         var docrash bool
  1150:         // Switch to the system stack to avoid any stack growth, which
(dlv) bt
 0  0x000000000003b680 in runtime.fatalpanic
    at /home/wsl/go/go1.20.10/src/runtime/panic.go:1145
 1  0x000000000003afac in runtime.gopanic
    at /home/wsl/go/go1.20.10/src/runtime/panic.go:987
 2  0x0000000000039a78 in runtime.panicmem
    at /home/wsl/go/go1.20.10/src/runtime/panic.go:260
 3  0x000000000004fea4 in runtime.sigpanic
    at /home/wsl/go/go1.20.10/src/runtime/signal_unix.go:841
 4  0x0000000000065238 in main.main
    at ./demo.go:5
 5  0x0000000000065238 in main.main
    at ./demo.go:5
 6  0x0000000000065238 in main.main
    at ./demo.go:5
 7  0x0000000000065238 in main.main
    at ./demo.go:5
 8  0x0000000000065238 in main.main
    at ./demo.go:5
 9  0x0000000000065238 in main.main
    at ./demo.go:5
10  0x0000000000065238 in main.main
    at ./demo.go:5
11  0x0000000000065238 in main.main
    at ./demo.go:5
12  0x0000000000065238 in main.main
    at ./demo.go:5
13  0x0000000000065238 in main.main
    at ./demo.go:5
14  0x0000000000065238 in main.main
    at ./demo.go:5
15  0x0000000000065238 in main.main
    at ./demo.go:5
16  0x0000000000065238 in main.main
    at ./demo.go:5
17  0x0000000000065238 in main.main
    at ./demo.go:5
18  0x0000000000065238 in main.main
    at ./demo.go:5
19  0x0000000000065238 in main.main
    at ./demo.go:5
```

**Comment by gnlsw** [comment]
> The problem is: Before the nil pointer dereference, the bt is normal. After the nil pointer dereference, the bt is wrong with endless main.main. The following content is output of dlv exec demo.*
> 
> ```
> [root@localhost demo]# go env
> GO111MODULE="off"
> GOARCH="arm64"
> ```
> 
> ```
> package main
> 
> func main() {
> 	var p_value *int = nil
> 	*p_value = 1
> }
> ```
> 
> `go build demo.go`
> 
> ```
> [root@localhost demo]# dlv exec demo
> Type 'help' for list of commands.
> (dlv) break main.main
> Breakpoint 1 set at 0x65230 for main.main() ./demo.go:5
> (dlv) c
> > main.main() ./demo.go:5 (hits goroutine(1):1 total:1) (PC: 0x65230)
> Warning: debugging optimized function
>      1: package main
>      2:
>      3: func main() {
>      4:         var p_value *int = nil
> =>   5:         *p_value = 1
>      6: }
> (dlv) bt
> 0  0x0000000000065230 in main.main
>    at ./demo.go:5
> 1  0x000000000003d9a0 in runtime.main
>    at /home/wsl/go/go1.20.10/src/runtime/proc.go:250
> 2  0x0000000000062e34 in runtime.goexit
>    at /home/wsl/go/go1.20.10/src/runtime/asm_arm64.s:1172
> (dlv) n
> > [unrecovered-panic] runtime.fatalpanic() /home/wsl/go/go1.20.10/src/runtime/panic.go:1145 (hits goroutine(1):1 total:1) (PC: 0x3b680)
> Warning: debugging optimized function
>         runtime.curg._panic.arg: interface {}(string) "runtime error: invalid memory address or nil pointer dereference"
>   1140: // fatalpanic implements an unrecoverable panic. It is like fatalthrow, except
>   1141: // that if msgs != nil, fatalpanic also prints panic messages and decrements
>   1142: // runningPanicDefers once main is blocked from exiting.
>   1143: //
>   1144: //go:nosplit
> =>1145: func fatalpanic(msgs *_panic) {
>   1146:         pc := getcallerpc()
>   1147:         sp := getcallersp()
>   1148:         gp := getg()
>   1149:         var docrash bool
>   1150:         // Switch to the system stack to avoid any stack growth, which
> (dlv) bt
>  0  0x000000000003b680 in runtime.fatalpanic
>     at /home/wsl/go/go1.20.10/src/runtime/panic.go:1145
>  1  0x000000000003afac in runtime.gopanic
>     at /home/wsl/go/go1.20.10/src/runtime/panic.go:987
>  2  0x0000000000039a78 in runtime.panicmem
>     at /home/wsl/go/go1.20.10/src/runtime/panic.go:260
>  3  0x000000000004fea4 in runtime.sigpanic
>     at /home/wsl/go/go1.20.10/src/runtime/signal_unix.go:841
>  4  0x0000000000065238 in main.main
>     at ./demo.go:5
>  5  0x0000000000065238 in main.main
>     at ./demo.go:5
>  6  0x0000000000065238 in main.main
>     at ./demo.go:5
>  7  0x0000000000065238 in main.main
>     at ./demo.go:5
>  8  0x0000000000065238 in main.main
>     at ./demo.go:5
>  9  0x0000000000065238 in main.main
>     at ./demo.go:5
> 10  0x0000000000065238 in main.main
>     at ./demo.go:5
> 11  0x0000000000065238 in main.main
>     at ./demo.go:5
> 12  0x0000000000065238 in main.main
>     at ./demo.go:5
> 13  0x0000000000065238 in main.main
>     at ./demo.go:5
> 14  0x0000000000065238 in main.main
>     at ./demo.go:5
> 15  0x0000000000065238 in main.main
>     at ./demo.go:5
> 16  0x0000000000065238 in main.main
>     at ./demo.go:5
> 17  0x0000000000065238 in main.main
>     at ./demo.go:5
> 18  0x0000000000065238 in main.main
>     at ./demo.go:5
> 19  0x0000000000065238 in main.main
>     at ./demo.go:5
> ```



> The stack trace you see when you run demo directly is taken at a different time, and in a different code path, than the one you will find inside a core file. The one inside a core file had to ask the operating system to create a core dump. This is expected.
