### ISSUE TITLE
Slice out of bounds error while debugging the test

### ISSUE THREAD

**Issue by iamwavecut** [go-delve/delve#3563]
I have a test which runs smooth with no debug, and fails when I debug run it, even if no breakpoints set.
The weird thing is if I set the breakpoint to the line where it fails - I can access the causing slice just fine, index it the same way as it done in code, etc. And then if I make a step forward - it panics.

Involved package: @GoWebProd [/uuidv7](https://github.com/GoWebProd/uuidv7)

I'm attaching the screenshot which shows the exact line, where it ends. I've added a couple of watched statements there, to point out, that everything works fine interactively.

| env | val |
| ------------- | ------------- |
| OS | `Linux 6.2.0-36-generic #37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux` |
| Go | `go1.21.4 linux/amd64` |
| dlv | `Version: 1.21.2; Build: $Id: 98f8ab2662d926245917ade2f2bb38277315c7fc` $ |
| uuidv7 package | `v0.0.0-20230623091058-5f5954faed6a` |
| Jetbrains GoLand IDE | `GoLand 2023.2.4; Build #GO-232.10203.20, built on October 27, 2023` |

Tests failing. Both have common property that's not in successful tests - **JSON marshalling**.
```go
func (s *UUIDv7Suite) TestUnmarshalValidUUIDv7JSONString() {
	had := NewUUIDv7()
	got := &UUIDv7{}

	bytes, err := had.MarshalJSON()
	s.NoError(err)
	err = got.UnmarshalJSON(bytes)
	s.NoError(err)

	s.Equal(had.String(), got.String())
}

func (s *UUIDv7Suite) TestReturnsNilErrorOnSuccessfulUnmarshalling() {
	uuid := &UUIDv7{}
	data, err := json.Marshal(validTestUUID)
	s.NoError(err)
	err = uuid.UnmarshalJSON(data)
	s.NoError(err)
}
```

*UUIDv7.UnmarshallJSON(data):
```go
func (u *UUIDv7) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("cant unmarshal JSON: %w", err)
	}

... // a bunch of unmarshalled data validations

	uuid, err := uuid7.Parse(s) // <- the error goes here
	if err != nil {
		return fmt.Errorf("cant parse JSON: %w", err)
	}
	u.uuid = uuid

	return nil
}
```

![image](https://github.com/go-delve/delve/assets/239034/df9f2728-0b71-4567-9e9a-b28d78845acc)
![image](https://github.com/go-delve/delve/assets/239034/fde674ba-e2d3-4a95-b637-2cb35ae6ee50)

test output failures log:
```log
=== RUN   TestUUIDv7Suite/TestReturnsNilErrorOnSuccessfulUnmarshalling
    types_test.go:42: 
        	Error Trace:	/home/wavecut/GolandProjects/brokerage-connectors/internal/shared/types/types_test.go:42
        	Error:      	Received unexpected error:
        	            	invalid UUIDv7: non-parsable
        	Test:       	TestUUIDv7Suite/TestReturnsNilErrorOnSuccessfulUnmarshalling
    --- FAIL: TestUUIDv7Suite/TestReturnsNilErrorOnSuccessfulUnmarshalling (5.45s)

=== RUN   TestUUIDv7Suite/TestUnmarshalValidUUIDv7JSONString
    types_test.go:32: 
        	Error Trace:	/home/wavecut/GolandProjects/brokerage-connectors/internal/shared/types/types_test.go:32
        	Error:      	Received unexpected error:
        	            	invalid UUIDv7: non-parsable
        	Test:       	TestUUIDv7Suite/TestUnmarshalValidUUIDv7JSONString
    types_test.go:34: 
        	Error Trace:	/home/wavecut/GolandProjects/brokerage-connectors/internal/shared/types/types_test.go:34
        	Error:      	Not equal: 
        	            	expected: "018bcd63-8a41-77c1-8004-707af094af67"
        	            	actual  : "00000000-0000-0000-0000-000000000000"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-018bcd63-8a41-77c1-8004-707af094af67
        	            	+00000000-0000-0000-0000-000000000000
        	Test:       	TestUUIDv7Suite/TestUnmarshalValidUUIDv7JSONString
    --- FAIL: TestUUIDv7Suite/TestUnmarshalValidUUIDv7JSONString (0.00s)

Expected :018bcd63-8a41-77c1-8004-707af094af67
Actual   :00000000-0000-0000-0000-000000000000
<Click to see difference>



FAIL

Debugger finished with the exit code 0
```
![image](https://github.com/go-delve/delve/assets/239034/fae9acc3-b288-4897-9bd0-c2215ed05040)

**Comment by aarzilli** [comment]
If you run the tests like this `go test -gcflags='all=-N -l'`, do they all pass? Could you share the definition of the type UUIDv7 and its methods?

**Comment by aarzilli** [comment]
> 1. It fails with the same two tests using these flags. So, not a `delve` bug I suppose...

It's a compiler bug then, it should be reported to golang/go. It would be better if you did it yourself so you can answer questions from the maintainers.

**Comment by iamwavecut** [comment]
Closing to not to hang in here
