### ISSUE TITLE
Feature req: `list` more lines

### ISSUE THREAD

**Issue by thockin** [go-delve/delve#3602]
Please answer the following before submitting your issue:

1. What version of Delve are you using (`dlv version`)?

Delve Debugger
Version: 1.21.1
Build: $Id: a358c02f24aa7047ecc562b0587dc2d08330b2cf $

2. What version of Go are you using? (`go version`)?

go version go1.21.3 linux/amd64

4. What operating system and processor architecture are you using?

linux amd64

6. What did you do?

List the code at a specific line, but needed more, just this once.  I usually show 10 lines before and after cursor.  That's not quite enough to see the whole loop.  So my only option (I think) is to `l` another line.  e.g.

I am at line 145.  I see a loop that runs past 155.  I have to `l 155`.  That's not enough either so I `l 165`.  I'd like to be able to say `l +30` (or something) but that means "list +/- 10 at current+30".  How can I specify a "width" for a single listing?

GDB does this by auto-incrementing successive `l` commands.  So if I am at 145, `l` shows me 135-155.  `l` again (or enter) shows 156-176.  Again shows 177-197.  This is nice because it is incremental but I can scroll-back and see a linear listing.  Do do this in dlv I need to `l`, `l +21`, `l +42`.

Maybe dlv could do the same?  `l .` could reset it (making "." mean "current PC"

Or something similar, like `l` shows current PC, `l+` shows current PC plus a saved incrementing offset, so successive `l+` would increment the view window, and `l` would reset it back to PC.

7. What did you expect to see?

An extra argument to specify number of lines

9. What did you see instead?

The same number of lines as always

**Comment by aarzilli** [comment]
This was requested before as https://github.com/go-delve/delve/issues/2030 and declined due to a lack of implementation difficulties, limited usefulness (given the existence of edit) and apparent lack of interest.

**Comment by thockin** [comment]
You mentioned implementation difficulty with no details.  The previous issue asking for this was closed but not really resolved.  "edit" is not the same.  I can understand not liking the GDB way (byt there's power in muscle-memory!).  What about something like `l ~50` meaning list the PC +/- 50 line (same as temporarily setting  `config source-list-line-count` to 50).  This is still not ideal, because it's rare I need to see behind me by as much as I need ahead.

How about `l 50@` meaning "50 lines at <locspec>" - `l 50@+10` = 50 lines around current+10L.  `l 10,50@220` means L210-L271.

Does "lack of interest" mean from you or from us?

**Comment by aarzilli** [comment]
> You mentioned implementation difficulty with no details.

The argument of list is a [location specified](https://github.com/go-delve/delve/blob/master/Documentation/cli/locspec.md) so whatever syntax you come up with needs to work and be able to distinguish arbitrary go expressions (for example you could do `list m["some string"]` if m is a map of functions).

> Does "lack of interest" mean from you or from us?

In general, #2030 was open for 2 years and almost nobody commented, upvoted or submitted a PR for it.

**Comment by aarzilli** [comment]
> I cannot figure out how edit could be made to work if you have to run in a docker container

Have `less` in the container and `export DELVE_EDITOR=less`
