### ISSUE TITLE
Feature req 'print' to a file or pager

### ISSUE THREAD

**Issue by thockin** [go-delve/delve#3615]
1. What version of Delve are you using (`dlv version`)?

Delve Debugger
Version: 1.21.1
Build: $Id: a358c02f24aa7047ecc562b0587dc2d08330b2cf $

2. What version of Go are you using? (`go version`)?

go version go1.21.3 linux/amd64

4. What operating system and processor architecture are you using?

linux amd64

6. What did you do?

Printed a large stucture

7. What did you expect to see?

A way to redirect output to a file

9. What did you see instead?

No option for this

Two use cases:

1) p bigObj | less

2) p bigObj > out.file

**Comment by aarzilli** [comment]
For the file:

[code]
(dlv) transcript test.txt
(dlv) p bigObj
(dlv) transcript -off
[/code]

**Comment by aarzilli** [comment]
The approach we have for paging so far is that it is done automatically when needed. The attached PR extends this mechanism to print (and a few related commands). Thoughts?

**Comment by thockin** [comment]
oh, I didn't know about transcript.  That's what I need.

Whatever existing paging we have did NOT kick in when printing my large object.  That PR looks like it would fix it.  How does paging intersect with transcript?  :)

**Comment by aarzilli** [comment]
> Whatever existing paging we have did NOT kick in when printing my large object

It wasn't applied to print, deliberately.

>  How does paging intersect with transcript?

It'll write to the file everything you see, at least.
