### ISSUE TITLE
Problem when debugging code using golang.org/x/sys/windows

### ISSUE THREAD

**Issue by mkch** [go-delve/delve#3626]
1. What version of Delve are you using (`dlv version`)?
> Delve Debugger
> Version: 1.22.0
> Build: \$Id: 61ecdbbe1b574f0dd7d7bad8b6a5d564cce981e9 $

2. What version of Go are you using? (`go version`)?
> go version go1.21.5 windows/amd6

4. What operating system and processor architecture are you using?
> Windows 10 Professional 64-bit
> Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz

6. What did you do?
```
// main.go
package main

import (
	"fmt"
	"unsafe"

	"golang.org/x/sys/windows"
)

type ACCEL struct {
	Virt byte
	Key  uint16
	Cmd  uint16
}

func CreateAcceleratorTableW(accel []ACCEL) (uintptr, error) {
	r, _, err := windows.NewLazySystemDLL("user32.dll").
		NewProc("CreateAcceleratorTableW").
		Call(uintptr(unsafe.Pointer(&accel[0])), uintptr(len(accel)))
	if r == 0 {
		return 0, err
	}
	return r, nil
}

func someAccels() []ACCEL {
	return []ACCEL{{83, 13, 100}}
}

func main() {
	var accels []ACCEL
	accels = append(accels, someAccels()...)
	h, err := CreateAcceleratorTableW(accels)
	fmt.Println(h, err)
}
```

> dlv debug main.go
> Type 'help' for list of commands.
> (dlv) continue
> 0 Invalid access to memory location.
> Process 7764 has exited with status 0
> (dlv)

8. What did you expect to see?
A valid handle value and nil error. Such as the following output generated by `go run main.go`
> go run main.go
> 19071465 \<nil>

10. What did you see instead?
> 0 Invalid access to memory location.

**Comment by aarzilli** [comment]
Usually this type of thing is caused by windows system libraries having a different behavior and extra checks when they are debugged. Compile your program and run it under windbg and see what it does.

**Comment by mkch** [comment]
Thank you for all your time.

After some investigation, I found that the problem is related to the build flags.

If I build the code with `go build -gcflags "-l -N"`, the problem will be reproduced even without delve.

I know this may not be a bug in delve itself, but I need some suggestions to go through this.

Please feel free to close this issue if it is off topic. Thank you.

**Comment by aarzilli** [comment]
If this happens just by disabling optimizations then it isn't a bug with delve. There's a problem with accel not being alive when the system call runs, which you could solve with runtime.KeepAlive but I don't think that's the problem.
