### ISSUE TITLE
Remaining Windows work

### ISSUE THREAD

**Issue by derekparker** [go-delve/delve#363]
- [x] **TestDebugLinePrologueParser**
  Only on some  machines and Go versions.  Appears to be because of buffers in the debugline data which are larger than they should be in Windows binaries?  I suspect there is a bug in the Go compiler on Windows that we'll need to work around.
- [x] **TestNextConcurrent flakiness**
  Occasional occurrences of the following errors:
  `proc_test.go:355: Program did not continue to correct next location expected 11 was parallel_next.go:10`
  `proc_test.go:355: Program did not continue to correct next location expected 11 was parallel_next.go:8`
  `proc_test.go:355: Program did not continue to correct next location expected 10 was parallel_next.go:8`
  `proc_test.go:410: Program did not continue to correct next location expected 11 was parallel_next.go:10`
  `proc_test.go:403: Initial breakpoint triggered twice for the same goroutine`
- [x] **Attach is not supported**
  Should also add test coverage for attach on all platforms.
- [x] **TestNextNetHTTP is disabled on Windows**
  Temporarily disabled this test, need to investigate the failure.
- [ ] **Should we load symbols on Windows?**
  Thread information is not displayed nicely for most non-active threads because the PC on those threads is in ntdll or other dynamically loaded code. To address this, we would need to load symbols on Windows and merge that information with the DWARF symbols. This should be possible, but worth discussing before implementing.
- [x] **thread.halt() may need to actually halt threads in some cases**
  See comment in implementation.
- [x] **Can we remove canContinue?**
  dbp.Step currently relies on checking this, but would be nice to factor it to not need this concept in addition to blocked and stopped.
- [x] **Infrequent failures in TestBreakPointCount**
  Pretty infrequent occurence, and seemingly always with 101 + 99.  So it appears that one of the breakpoint hits is getting recorded as being on the wrong thread. 

Once merged, we will also want to do:
- [x] **Add Appveyor project tracking derekparker/delve and badge in README**
- [x] **Update docs with info on building/running on Windows**
  Mostly just MinGW requirement which is likely not present for many Windows Go users.

**Comment by lukehoban** [comment]
> **Update docs with info on building/running on Windows.** Mostly just MinGW requirement which is likely not present for many Windows Go users.

This is updated in the wiki now at https://github.com/derekparker/delve/wiki/Building#windows.

**Comment by uuf6429** [comment]
@lukehoban Regarding the wiki update, there are at least two issues:
1. This is not valid for Windows:
    $ GO15VENDOREXPERIMENT=1 make install
Instead, it should be something like this:
    > SET GO15VENDOREXPERIMENT=1
    > make install
2. after installing MinGW-W64, from the suggested link, `make` is still missing. Maybe we need a different toolchain install?

**Comment by mantzas** [comment]
@uuf6429 first i installed mingw with the following setting(which make nore sense): arch x86_64, threads:win32,exception:seh. Then u can find a make executable named mingw32-make.exe which worked.

**Comment by uuf6429** [comment]
@mantzas funny I didn't see those options back when I was installing it. I'll try again in a couple of hours.
Also, nice job on the port... Can't wait to get it working on my system!

**Comment by lukehoban** [comment]
@uuf6429 and @mantzas Thanks - I've updated the wiki page with more complete/correct instructions.

**Comment by asampal** [comment]
@lukehoban, it might be better to include separate instructions depending if one is building from the Windows command prompt (typically cmd.exe) or a Unix-y shell such as Bash which will be available if MSYS (or MSYS2) is installed along with MinGW (as is also very typical). If the latter shell is being used, then the instructions you had for Linux should also apply here. Also, make is one of the packages available in MSYS2, and could be used instead of mingw32-make.

BTW, I would recommend pointing people to MSYS2/MinGW-w64 as the "distro" of choice since it is very well maintained, has frequent updates, has a large number of packages, using a port of the very nice Arch Linux Pacman package manager for management.

You can find the one-click installer for MSYS2 [here](http://msys2.github.io), some notes on installation [here](http://sourceforge.net/p/msys2/wiki/MSYS2%20installation) and an introduction [here](http://sourceforge.net/p/msys2/wiki/MSYS2%20introduction).

**Comment by lukehoban** [comment]
@asampal Makes sense - added a note about MSYS2 / CYGWIN in the wiki page.

**Comment by mattn** [comment]
One more task.

https://github.com/golang/proposal/blob/master/design/12416-cgo-pointers.md

```diff
diff --git a/proc/threads_windows.go b/proc/threads_windows.go
index c82fc7b..b5adccd 100644
--- a/proc/threads_windows.go
+++ b/proc/threads_windows.go
@@ -1,6 +1,11 @@
 package proc
 
-// #include <windows.h>
+/*
+#include <windows.h>
+BOOL _ReadProcessMemory(HANDLE hProcess, LPCVOID lpBaseAddress, uintptr_t lpBuffer, SIZE_T nSize, SIZE_T* lpNumberOfBytesRead) {
+  return ReadProcessMemory(hProcess, lpBaseAddress, (LPVOID*) lpBuffer, nSize, lpNumberOfBytesRead);
+}
+*/
 import "C"
 import (
 	"fmt"
@@ -136,7 +141,7 @@ func (t *Thread) stopped() bool {
 
 func (t *Thread) writeMemory(addr uintptr, data []byte) (int, error) {
 	var (
-		vmData = C.LPCVOID(unsafe.Pointer(&data[0]))
+		vmData = C.LPCVOID(uintptr(unsafe.Pointer(&data[0])))
 		vmAddr = C.LPVOID(addr)
 		length = C.SIZE_T(len(data))
 		count  C.SIZE_T
@@ -154,12 +159,12 @@ func (t *Thread) readMemory(addr uintptr, size int) ([]byte, error) {
 	}
 	var (
 		buf    = make([]byte, size)
-		vmData = C.LPVOID(unsafe.Pointer(&buf[0]))
+		vmData = C.uintptr_t(uintptr(unsafe.Pointer(&buf[0])))
 		vmAddr = C.LPCVOID(addr)
 		length = C.SIZE_T(size)
 		count  C.SIZE_T
 	)
-	ret := C.ReadProcessMemory(C.HANDLE(t.dbp.os.hProcess), vmAddr, vmData, length, &count)
+	ret := C._ReadProcessMemory(C.HANDLE(t.dbp.os.hProcess), vmAddr, vmData, length, &count)
 	if ret == C.FALSE {
 		return nil, fmt.Errorf("could not read memory")
 	}
```
