### ISSUE TITLE
[BUG]Unable to perform single-step debugging

### ISSUE THREAD

**Issue by wulling1024** [go-delve/delve#3633]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

If this is about source listing not showing up (or breakpoints not being
accepted) while running in a container please read our
[FAQ](https://github.com/go-delve/delve/blob/master/Documentation/faq.md#substpath)
first.

1. What version of Delve are you using (`dlv version`)?
![image](https://github.com/go-delve/delve/assets/27014777/5c290e60-ab33-40d4-9cde-5266e28e1fb8)
2. What version of Go are you using? (`go version`)?
![image](https://github.com/go-delve/delve/assets/27014777/03f8663d-9414-43df-8317-6e51091321ce)
3. What operating system and processor architecture are you using?
![image](https://github.com/go-delve/delve/assets/27014777/c5834c83-8cd8-4acb-8768-8b22ddd5bb6b)
![image](https://github.com/go-delve/delve/assets/27014777/757a0324-2874-4d1c-8ef8-0139313bab2a)
4. What did you do?
(1: My editor is VSCODE, and I use dlv for single-step debugging of golang projects.
(2: The startup command is `dlv dap --check-go-version=false --log=true --log-output=debugger --listen=127.0.0.1:51354 --log-dest=3 from xxxx
DAP server listening at: 127.0.0.1:51354`
There is no problem when the program starts
(3: There is no problem when the program starts.

vscode version:
```
Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:48:06.308Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 23.2.0
```
5. What did you expect to see?
Able to perform normal single-step debugging operations
6. What did you see instead?
When the program reaches the breakpoint, an error will occur
![image](https://github.com/go-delve/delve/assets/27014777/458e1908-4d00-4baa-bec0-d2d378be9f45)

**Comment by wulling1024** [comment]
@aarzilli  master, can you help to check it?

**Comment by aarzilli** [comment]
Did you just run the program under delve and did nothing else? Can you reproduce this using the command line UI of delve (without dap)?

**Comment by wulling1024** [comment]
> Did you just run the program under delve and did nothing else?

yes. I started debugging using vscode. My configuration information is as follows:
```
    "go.delveConfig": {
        "dlvFlags": [
            "--check-go-version=false",
        ],
        "showLog": true,
        "debugAdapter": "dlv-dap",
        "apiVersion": 2
    },
```

> Can you reproduce this using the command line UI of delve (without dap)

can reproduce.
start command: `dlv exec --check-go-version=false --api-version=2 ./main`
![image](https://github.com/go-delve/delve/assets/27014777/ee9ecd53-1040-437f-aab9-c6ef0d780bed)

Recently I did an upgrade to the macos version, I don’t know if it’s relevant.

**Comment by aarzilli** [comment]
But this is a completely different error from the one on the first post.

**Comment by wulling1024** [comment]
maybe it's just the same as displaying information.
the first post it is sent is the 'vscode debug console'.
dlv cmd is just a short message.
The key to the current two is that the program is terminated when a breakpoint is encountered.

**Comment by wulling1024** [comment]
I tried lowering the version to '1.8.3', but the problem still persists

**Comment by aarzilli** [comment]
No in the first screenshot the target program is crashing, in the second one debugserver isn't working. Also:

>  The key to the current two is that the program is terminated when a breakpoint is encountered.

did you set a breakpoint in the second example? I just see `continue` in the screenshot.

**Comment by wulling1024** [comment]
I followed this process again：
1、start command: `dlv debug --check-go-version=false app/main.go`
2、use `continue` to startup project. because this is a Gin http service
3、add breakpoint
4、use postman to request `http://127.0.0.1:8888/api/health_check/`
5、`continue`
we got error and the program is crashing..

![image](https://github.com/go-delve/delve/assets/27014777/fadb0865-29a5-43eb-8c83-4b0dade40fd3)

**Comment by aarzilli** [comment]
This looks similar to #3538, #3599, #3554, #3519.

**Comment by wulling1024** [comment]
hi @aarzilli. thank you very much, my problem is solved. respect
