### ISSUE TITLE
Highlight (new) AGPL (Affero General Public License dependency go-delve/gore

### ISSUE THREAD

**Issue by aktau** [go-delve/delve#3661]
Since 2023-11-03 (6c77c3558606bdc8735a815af7520e44962cf719), Delve has an AGPL dependency in the form of:

 1. First pkg/internal/moduledata/moduledata.go (mostly taken from goretk/gore), the separate license is not highlighted here but can be inferred by the attribution to the source project.
 2. Later: Direct dependency on goretk/gore (6e8e1cee9b4b068f0720de2fc0d39d908e00ce15).
 3. Now: A fork of the dependency (go-delve/gore) (dda8f693e6f2f8ad80f615d37ed5fea5e6709999)

The authors can (of course) use any compatible licensed library that they wish. But, the AGPL is often prohibited for use/import in larger companies due to the stringency of the requirements. This means that Delve won't be usable in those places (without patching at least). There may also be other users who'd like to know about the new restrictions.

My request isn't to stop using the library or anything like that (that's up to the authors), but to highlight the new AGPL nature of Delve more prominently somewhere. Thanks!

**Comment by derekparker** [comment]
Hey,

Thank you for calling this out. The AGPL dependency was an unintended consequence of using that library, and we are working towards removing the dependency going forward.

**Comment by adonovan** [comment]
@prattmic points out that https://github.com/golang/go/issues/58474 may be helpful to you.

**Comment by derekparker** [comment]
> @prattmic points out that [golang/go#58474](https://github.com/golang/go/issues/58474) may be helpful to you.

Thanks, yes I've been following that issue and https://github.com/golang/go/issues/58474#issuecomment-1785681472 would certainly be helpful going forward. The issue is maintaining current feature support in the meantime.
