### ISSUE TITLE
upstream "cmd/compile: move runtime.itab to internal/abi.ITab" causes Delve to no longer print variables

### ISSUE THREAD

**Issue by aktau** [go-delve/delve#3672]
Just a quick heads up, as we noticed this internally, I can post more details later but I assume that the problem is not too difficult to spot for the maintainers:

- Link to upstream: [cmd/compile: move runtime.itab to internal/abi.ITab (549435) · Gerrit Code Review](https://go.dev/cl/549435)

The effect is an error like this: `(unreadable invalid interface type)`

1. What version of Delve are you using (`dlv version`)? v1.22.1-0.20240221111041-4a72c523bed8
2. What version of Go are you using? (`go version`)? go1.23-aaf8e844ed (everything up to upstream commit https://go-review.git.corp.google.com/c/go/+/550435)
3. What operating system and processor architecture are you using? Linux
4. What did you do? `break main.main ; c ; p myVar`
5. What did you expect to see? A structure
6. What did you see instead?  `(unreadable invalid interface type)`

**Comment by aarzilli** [comment]
Did you see 5bd835a801f8144fd902fb3d12f6a2abf1227cf4?

**Comment by aktau** [comment]
I did not, apologies. I will check it out.

**Comment by aktau** [comment]
This indeed fixes the issue. Thanks and sorry for the noise.

**Comment by aarzilli** [comment]
No problem.
