### ISSUE TITLE
In debug mode, the process does not stop at a breakpoint

### ISSUE THREAD

**Issue by petervalencic** [go-delve/delve#3709]
Hi, have strange issue from a while. I'm unable to debug golang project using dlv and vscode. 

1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.22.1
Build: $Id: 0c3470054da6feac5f6dcf3e3e5144a64f7a9a48 $

3. What version of Go are you using? (`go version`)?
go version go1.21.4 linux/386

5. What operating system and processor architecture are you using?
WSL Ubuntu 

7. What did you do?
Trying to debug a simple code (worked in past). The debugger won't to stop on the breakpoint

9. What did you expect to see?
To be able to debug the code

11. What did you see instead?
I see the same result as if the run command were used..

This is my launch.json file:
```
 "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch Package",
      "type": "go",
      "request": "launch",
      "mode": "auto",
      "program": "${fileDirname}",
    }
  ]
}

```

When trying to debug the code I get:
![image](https://github.com/go-delve/delve/assets/10866388/2d512687-b74f-4ff6-b9a1-cf9abfc8414c)

Don't know what is wrong or how to make the debugger to stop at the breakpoint in the code..

**Comment by aarzilli** [comment]
Do you have a way for us to reproduce this?

**Comment by aarzilli** [comment]
Is this WSL 1 or WSL 2?

**Comment by petervalencic** [comment]
Hi, I'm using WSL2:
![image](https://github.com/go-delve/delve/assets/10866388/2fe3b351-6fef-4328-9769-6c4cd708e2e2)

The strange thing is that some time ago I was able to debug the Go app. I mainly use vscode for Go, Java, node and Python development (switching projects depending on work).. The last week was debugging Python project and then switched back to Go and the debugger just ran over the code without considering breakpoints. At the same time, the toolbar with the debug buttons did not appear on the vscode screen.

![debug](https://github.com/go-delve/delve/assets/10866388/c72dd161-f65a-4955-a700-0625817304bc)

**Comment by aarzilli** [comment]
You also need to add `"showLog": true` apparently. The way to run the command line client is `dlv debug` not `dlv debug ./test`. Once it's running type `help` for how to set breakpoints and run the program. 
Also please post text not screenshots or videos.

**Comment by petervalencic** [comment]
What I have done is that I have removed Go from my system.. reinstalled the latest version of Go and installed Delve ...
![image](https://github.com/go-delve/delve/assets/10866388/545b60a0-7264-42f4-9f9a-b9b8e2810aab)


Now the debug is working well:
![image](https://github.com/go-delve/delve/assets/10866388/77e08e25-5184-465b-8d83-ebda6aee6303)

**Comment by petervalencic** [comment]
I didn't have time to investigate more on what was wrong, but I'm able to debug it now. That solved my problem. You can close the ticket. Thank you for your help and time!
