### ISSUE TITLE
How build arm version 

### ISSUE THREAD

**Issue by sixhj** [go-delve/delve#3728]
1. What version of Delve are you using (`dlv version`)?    v1.22.1
3. What version of Go are you using? (`go version`)? go1.22.0
4. What operating system and processor architecture are you using?  windows 10 
5. What did you do?
fix  
build: $(GO_SRC)
	GOOS=linux GOARCH=arm GOARM=7 @go run _scripts/make.go build

7. What did you expect to see?

I want use dlv 

can you help me

**Comment by aarzilli** [comment]
It doesn't exist, there is only an arm64 version. See #2051.
