### ISSUE TITLE
Explore better starting points for debugged process

### ISSUE THREAD

**Issue by derekparker** [go-delve/delve#374]
Currently, we stop the process as soon as it is `exec`ed, so it really isn't anywhere useful. The reason we do not continue directly to `main.main` is because that would skip package init functions, which users may want to debug. Possible solutions include:

1) Continue directly to `main.main`, but optionally provide a flag to prevent this
2) Continue directly to `runtime.main` which would not be user code, but should (iirc) be before any package initialization, and would provide useful feedback when executing commands in the debugger.
3) Do nothing, and either print a startup message telling user to set a breakpoint, or otherwise consider it a documentation problem instead of a software one.

I'm open to suggestions, I want whatever ultimately makes the user experience better.

**Comment by jussij** [comment]
Speaking as a Windows user, my preference would be for the the debugger to stop on main.main entry point, only because this mimics how the Visual Studio debugger works.

However, to also let developers debug the earlier startup process, I would expect the debugger also stops on any breakpoints set in that startup code (once again mimicking how the Visual Studio debugger works).

Using this approach, it should be fairly easy for developers wanting debug the startup process as they would have access to the stack as soon as the  main.main point is hit:
    
    stack
    0  0x0000000000401240 in main.main
       at C:/Go/src/github.com/jussij/DelveTest/main.go:15
    1  0x000000000042b669 in runtime.main
       at c:/go/src/runtime/proc.go:111
    2  0x0000000000456610 in runtime.goexit
       at c:/go/src/runtime/asm_amd64.s:1721

They could use that stack information to navigate back into that startup code, looking for a place to put a breakpoint in that startup code.

**Comment by derekparker** [comment]
@jussij that seems reasonable to me, overall. Default to stopping at main, if you want to checkout an init function or something, then you can set a breakpoint there.

**Comment by jussij** [comment]
I tried out this auto-advance change on Windows 10 and it is working perfectly. Great stuff :)

**Comment by aarzilli** [comment]
I think at this point the ship has sailed, the current behavior has existed for too long and thus we should not auto-advance to main.main, or runtime.main or anything else. I think we should close this.

**Comment by hick** [comment]
most Go programmers pay more attention for the Go code written by themselves indeed.  

BUT some Go programmers concern on something deeper like Go runtime,  especially for those want to inspect Go under the  hood ,  like the Go contributors, or someone want to be a  Go contributor.  

how about add a config parameter to show more choices?

or maybe the third way is good and convinient for  both the delve developers and the delve users,  now I did not find a dlv way to get thr program entry point liek "info files" in gdb,   maybe I can use " readelf -s a_go_bin  | grep _rt0_amd64_linux" to find it,  comparing gdb's output of info files:

![image](https://user-images.githubusercontent.com/38886/147559594-b3bb025a-b4f7-4c43-8ecc-2e37cff9f86b.png)


or add sub-command like "config entry" to display or switch the stop point, may be delve can notice the startup message:

```
vagrant@u20-ehick:/data/hick/go/my/dlvme$ dlv debug dlvme
Type 'help' for list of commands.
```

change  like this

```
vagrant@u20-ehick:/data/hick/go/my/dlvme$ dlv debug dlvme
Type 'help' for list of commands,   'config entry' for deeper stop point
```

or  "'config entry' for deeper stop point" just in the  context of 'help' message

thanks for your works for such a good debug tool for Go  :)

**Comment by thockin** [comment]
I'd like to see a commandline flag to set initial breakpoints.  E.g. I know I want to stop at `foo.Bar` - load and run to that point.  It's a small convenience.

**Comment by thockin** [comment]
Oh  nice.  Can it be done without a file?

**Comment by aarzilli** [comment]
> Oh nice. Can it be done without a file?

`--init <(echo ...)`

**Comment by thockin** [comment]
indeed, that solves the needI had :)

**Comment by aarzilli** [comment]
Closing this, at this point doing extra stuff after startup would be too much of a backwards incompatible change.
