### ISSUE TITLE
Unable to find escape variables when using Delve

### ISSUE THREAD

**Issue by W1NB0** [go-delve/delve#3764]
1. What version of Delve are you using (`dlv version`)? 
Delve Debugger
Version: 1.22.1
Build: $Id: 0c3470054da6feac5f6dcf3e3e5144a64f7a9a48 $

2. What version of Go are you using? (`go version`)?
go version go1.22.5 linux/amd64

3. What operating system and processor architecture are you using?
Linux Ubuntu 22.04 LTS

4. What did you do?
go build  -gcflags="all=-N -l" main.go
main.go contains some code like this:
```
func escape() *int {
        var escapeVar int = 76
        pointer := & escapeVar
        return pointer
}
func main() {
	pointer := escape()
	fmt.Println("escapeVar value", *pointer)
}
```
dlv exec ./main
set breakpoints at `fmt.Println("escapeVar value", *pointer)`
run `continue`、`locals` and `vars main` to get variables.

5. What did you expect to see?
According to escape analysis, the variable escapeVar will escape, so I think it's possible to find the variable through some commands.

6. What did you see instead?
(dlv) locals
pointer = (*int)(0xc00009a010)
(dlv) vars main
runtime.main_init_done = chan bool 0/0
runtime.mainStarted = true
(dlv) stack
0  0x000000000049b33c in main.main
   at ./test.go:16
1  0x000000000043c992 in runtime.main
   at /usr/local/go/src/runtime/proc.go:271
2  0x000000000046afa1 in runtime.goexit
   at /usr/local/go/src/runtime/asm_amd64.s:1695

If I set breakpoint at `return pointer`, running `locals` and `stack` will get
(dlv) locals
escapeVar = 76
pointer = (*int)(0xc00009a010)
(dlv) stack
0  0x000000000049b2fb in main.escape
   at ./test.go:11
1  0x000000000049b337 in main.main
   at ./test.go:15
2  0x000000000043c992 in runtime.main
   at /usr/local/go/src/runtime/proc.go:271
3  0x000000000046afa1 in runtime.goexit
   at /usr/local/go/src/runtime/asm_amd64.s:1695

So is it impossible to get the escapeVar after function `escape()` call ended?

**Comment by aarzilli** [comment]
> So is it impossible to get the escapeVar after function `escape()` call ended?

Yes, it is no longer in scope.

**Comment by W1NB0** [comment]
> > So is it impossible to get the escapeVar after function `escape()` call ended?
> 
> Yes, it is no longer in scope.

Will Delve be able to find these escaped variables? These variables can be found in the coredump file and sometimes it's helpful to know about these variables.

**Comment by aarzilli** [comment]
No, it's impossible. The region of memory exists but there is no association between it and any specific name.

**Comment by aarzilli** [comment]
Yes.

**Comment by W1NB0** [comment]
> Yes.
``
Is there a method that prohibits optimization? I have built file with `go build -gcflags="all=-N -l" main.go`

**Comment by aarzilli** [comment]
The runtime package is always compiled with optimizations on.
