### ISSUE TITLE
Fail to set watchpoint after clearing one of four

### ISSUE THREAD

**Issue by emilykmarx** [go-delve/delve#3765]
1. What version of Delve are you using (`dlv version`)?
Backend=rr (5.7.0), on a recent commit of delve (https://github.com/go-delve/delve/commit/979e487ac7f187512c4a4c58567d5d742444a962)
3. What version of Go are you using? (`go version`)?
```go version go1.22.4 linux/amd64```
5. What operating system and processor architecture are you using?
Ubuntu 22 LTS, amd64

Summary:

- I set four watchpoints
- I try to set a fifth watchpoint, which fails as expected since my machine only supports four
- I clear one of the four watchpoints
- I try to set another watchpoint. I would expect this to succeed, since I’ve cleared one of the four, but it fails

Trying to set the fifth watchpoint seems important - without that, it works as expected.
I also tried with the native backend, and there it works as expected. (I also tried with rr alone, without delve, using raw addresses since it doesn’t seem to understand enough about slices – but rr seems to let you set the 5th watchpoint.)

The CLI sessions for both backends are in this gist: https://gist.github.com/emilykmarx/67d92e5cf76fbd07f28f9a73d405a067, and the target file is the same one as in this gist: https://gist.github.com/emilykmarx/c9bb39fdefd2ac8cfb843d53e867a12d#file-test-go

Some details:

- The rr errors in the CLI session is logging I added to rr, shown here: https://github.com/emilykmarx/rr/commit/81a0138ea361179fa0e016b1bfba4a6649882741. You can ignore if it’s not useful (I know very little about the rr code), but I do notice the `regs` argument has 4 elements when the clear command is invoked, and based on its size in the previous commands I wonder if it should have 3 (since it seems to be the regs you want, not that you already have)
- Sometimes I have noticed the CLI hang in this scenario, either after trying to set the 5th watchpoint, or after the last one post-clearing
- I initially ran into this when the stack got resized while there were four watchpoints set (and I had previously tried to set a fifth), so adjustStackWatchpoint() failed upon trying to set the updated watchpoint. But I think the target in the gist will be easier to work with 

Thanks in advance, and thanks for the fix for https://github.com/go-delve/delve/issues/3739

**Comment by aarzilli** [comment]
What's the output with `--log --log-output=gdbwire`?

**Comment by emilykmarx** [comment]
> What's the output with `--log --log-output=gdbwire`?

Added that to the gist: https://gist.github.com/emilykmarx/67d92e5cf76fbd07f28f9a73d405a067#file-gdbwire-txt

**Comment by aarzilli** [comment]
Closing this since it's an upstream (of rr) bug that is now fixed: https://github.com/rr-debugger/rr/issues/3777. Thanks.
