### ISSUE TITLE
Feature request: restart the current function

### ISSUE THREAD

**Issue by tdegris** [go-delve/delve#3768]
What version of Delve are you using (`dlv version`)? 1.22.1
What version of Go are you using? (`go version`)? 1.22
What operating system and processor architecture are you using? Linux, amd64

Is there a command to restart the current function? If not, would it be possible to implement such a command?

Such command is very useful in practice. For example:
* when skipping accidentally over a function
* when the output of a call is unexpected and the user needs to re-execute that call for investigation
* set a breakpoint on an error, then restart the function to re-run the code triggering that error
Being able to restart the current function can also save a lot of time for users for which restarting the debugging session is expansive and time consuming.

Thank you very much for all your work on Delve.

**Comment by aarzilli** [comment]
As described this is not possible, code that has been executed has been executed.
However if you are using linux/amd64 you can install [rr](https://github.com/rr-debugger/rr/) and use the `--backend=rr` option, which has a fairly similar effect.

**Comment by tdegris** [comment]
Thank you very much for your quick answer and the pointer to rr. I will definitely try this.

Naïvely, I would have thought that implementing such a feature would "just" require to set the pointer to the next instruction to the beginning of the function. Would you have any pointer to get some context about why this is not possible? Thank you.

**Comment by aarzilli** [comment]
The only time something like that could work is if the function was nothing but nop instructions.

**Comment by tdegris** [comment]
Thank you very much for your super-fast answer and for your patience. I am asking because I used this feature a lot with Visual Studio 6 on Windows while I was doing C++ back in 2000 and also in Java with Eclipse 3 later on. So, I am wondering what is the fundamental difference between Go and C++/Java that makes such a feature impossible for Go? (just curious).

In case I am unclear: from the state of the program point of view, restarting to the beginning of the function was equivalent to re-run the same code multiple times meaning producing the same side effects multiple times (no rollback). So, if the debugged code creates a single go-routine for example, and the user restart the current function twice, the user would end-up with 3 go-routines (initial creation + two restarts).

**Comment by aarzilli** [comment]
It's a broken feature in every language, subsequent executions will see the partial side-effects (sometimes hidden and non obivious) of every execution of the function. As for Go: arguments are passed in registers so you might not even get the same input arguments, but it is not a fundamentally different category of problem: it's an operation with hard to predict consequences.

That said, it isn't just resetting the program counter, you also have to reset the stack.

**Comment by tdegris** [comment]
Yes, you are absolutely correct: it is a broken feature and yes, the stack also needs to be reset. I just remember using that feature super often. Once in a while, when it would indeed break my debugging session because, for example, of hidden partial side-effects, then I would just restart the session like I do presently in delve. How are the partial side-effects or consequences different from calling `call` from the delve console?
