### ISSUE TITLE
Seeing a warning that delve is too old for the latest Go version 1.22.5

### ISSUE THREAD

**Issue by tpietsch-rcp** [go-delve/delve#3777]
WARNING: undefined behavior - version of Delve is too old for Go version 1.22.5 (maximum supported version 1.21)

go version go1.22.5 darwin/arm64

Delve Debugger
Version: 1.22.1
Build: $Id: 0c3470054da6feac5f6dcf3e3e5144a64f7a9a48 $

Is the project not planning on any more updates?

I am seeing some undefined behavior in that I need to prefix the dlv command with `arch -arm64`  on my M3

**Comment by aarzilli** [comment]
Delve 1.22 can not print that message, you are using 1.21. The fact that you need to prefix with `arch -arm64` is unrelated but likely also wrong.
