### ISSUE TITLE
Improper string representation of Google uuid.UUID type

### ISSUE THREAD

**Issue by Jasonsd19** [go-delve/delve#3792]
1. Delve version 1.22.1
2. Go version 1.22.4
3. Ubuntu-20.04 x86
4. Debugged code containing Google UUID
5. A properly formatted string representation of the UUID
6. An incorrect string representation

![uuid](https://github.com/user-attachments/assets/e7564ea4-97e8-411c-b4ca-f7c3744812da)

I imagine this is due to Delve using the default ASCII or UTF-8 encoding instead of parsing it as a hexadecimal string. Currently it is possible to work around this by using `call newID.String()` and viewing the proper string representation. However when dealing with large amounts of UUIDs and trying to keep track of all of them it becomes tedious. Is there a way we can write our own parser for specific data types?

**Comment by aarzilli** [comment]
At the moment there isn't. Duplicate of #2887
