### ISSUE TITLE
Support request - Unix socket support when running as DAP Client

### ISSUE THREAD

**Issue by n1lesh** [go-delve/delve#3814]
Unix socket support was added here: https://github.com/go-delve/delve/issues/3654.

However, there's currently no way to initiate a connection from dlv dap to a server listening on a Unix socket. This feature is essential for extensions like vscode-go, which initiate a connection in reverse mode by running dlv dap with the client-addr flag and need to support Unix sockets.

I would love to hear your thoughts on this, and I’d be happy to give it a try.

**Comment by aarzilli** [comment]
> This feature is essential for extensions like vscode-go

Considering that vscode-go has been written and support for DAP over unix sockets doesn't exist, I wouldn't use the word "essential" here.

**Comment by n1lesh** [comment]
@aarzilli It becomes essential since I'm working on adding the support for unix sockets in vscode-go. That's how I got to know dlv dap can listen on a unix socket but cannot connect to one, at least when running the dap subcommand.
