### ISSUE TITLE
could not read debug info (decoding dwarf section info at offset 0x0: too short) and could not read go symbol table (could not find rodata struct member)

### ISSUE THREAD

**Issue by TelenLiu** [go-delve/delve#3823]
MacOS 15， GoLand team released 2024.2.3， use （https://github.com/djimenez/iconv-go | https://github.com/faiface/beep | https://github.com/shirou/gopsutil/v3） error like：

Warning: no debug info found, some functionality will be missing such as stack traces and variable evaluation.
Exiting.
could not launch process: could not read debug info (decoding dwarf section info at offset 0x0: too short) and could not read go symbol table (could not find rodata struct member)

1. What version of Delve are you using (`dlv version`)?
go: downloading github.com/go-delve/delve v1.23.2-0.20241004174457-025d47c6e96e

3. What version of Go are you using? (`go version`)?
go version go1.21.13 darwin/arm64

5. What operating system and processor architecture are you using?
mac os 15.0.1  Apple M1 Pro

7. What did you do?
”go run main.go“，that ok， but use goland run or debug wil error。
mac os 14、 mac os  15 ， goland run or debug is ok

8. What did you expect to see?
I hope to debug normally on Mac OS 15

9. What did you see instead?
![image](https://github.com/user-attachments/assets/8e98122c-c136-4583-a8dc-62aac3769c53)

**Comment by aarzilli** [comment]
The version of go that you are using is too old for your version of macOS, try updating.
