### ISSUE TITLE
go get gives error slices": import path does not begin with hostname

### ISSUE THREAD

**Issue by anilpuliyeril** [go-delve/delve#3833]
```GO111MODULE=off go get -v github.com/go-delve/delve/cmd/dlv
package slices: unrecognized import path "slices": import path does not begin with hostname
```

1. What version of Delve are you using (`dlv version`)? latest git code
2. What version of Go are you using? (`go version`)? go 1.20
3. What operating system and processor architecture are you using? macos RELEASE_ARM64_T6030 arm64
4. What did you do? got get
5. What did you expect to see? successfully completed without the slices error
6. What did you see instead? `unrecognized import path "slices": import path does not begin with hostname`

**Comment by aarzilli** [comment]
We only support the three latest versions of Go (1.23, 1.22 and 1.21). If you need to use go1.20 you should install delve 1.22.
Furthermore if you are using macOS 15 nothing but 1.23 will work.
