### ISSUE TITLE
How to add a new builder

### ISSUE THREAD

**Issue by abner-chenc** [go-delve/delve#3843]
Hi, @artspb

I want to add a Loong64 architecture builder and prepare for Loong64 (https://github.com/go-delve/delve/pull/3685) support. The basic steps are as follows:
Step 1:  Download https://delve.teamcity.com/update/buildAgentFull.zip as prompted.
Step 2:  Modify the property values ​​of serverUrl, Name, and authorizationToken in conf/buildAgent.properties.
Step 3:  Execute ./bin/agent.sh start

My settings are as follows:
```
serverUrl=https://delve.teamcity.com
name=Linux-Fedora38-loong64
authorizationToken=
```

But I don't see the corresponding agent in https://delve.teamcity.com/agents/overview.
I can only log in as a guest at https://delve.teamcity.com, but generating authorizationToken requires Admin login to execute.

What should I do next?

Thanks.

**Comment by lrzlin** [comment]
Hi, I already setup a new builder for riscv64, according to my experience, you need to modify the `.teamcity/settings.kts` and add loong64 to it, then it should be enough. The authorizationToken will be generate automatically once the agents being approved by the admin.

Ref: https://github.com/go-delve/delve/pull/3785#issuecomment-2400457268

If the teamcity's agent log shows something like this, just waiting for the teamcity's server admin to approve it, then everything should be okay.

Also, you need to install the docker and start the docker deamon on the agent builder machine, see [TeamCity is reporting "Unmet requirements: docker.server.version exists"](https://github.com/lawrenceching/gitbook/blob/master/teamcity-is-reporting-unmet-requirements-docker.server.version-exists.md) for more details.

**Comment by aarzilli** [comment]
Closing, since the question has been answered, as far as I can tell.
