### ISSUE TITLE
examinemem -count doesn't support hex arguments

### ISSUE THREAD

**Issue by prattmic** [go-delve/delve#3845]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

If this is about source listing not showing up (or breakpoints not being
accepted) while running in a container please read our
[FAQ](https://github.com/go-delve/delve/blob/master/Documentation/faq.md#substpath)
first.

1. What version of Delve are you using (`dlv version`)?

```
dlv version
Delve Debugger
Version: 1.23.1
Build: $Id: 2eba762d75437d380e48fc42213853f13aa2904d $
```

3. What version of Go are you using? (`go version`)?

N/A (but tip)

5. What operating system and processor architecture are you using?

linux-amd64

7. What did you do?

```
(dlv) x -len 0x10 0xc05d78f000
```

9. What did you expect to see?

16 byte dump of memory

11. What did you see instead?

```
Command failed: count/len must be a positive integer
```

Using decimal values works, but that is awkward when picking a size based on subtracting addresses.

**Comment by aarzilli** [comment]
This is the code that parses the argument of len:

```
			arg := nextArg()
			if arg == "" {
				return errors.New("expected argument after -count/-len")
			}
			var err error
			count, err = strconv.ParseInt(arg, 0, 64)
			if err != nil || count <= 0 {
				return errors.New("count/len must be a positive integer")
			}
```

it already supports hexadecimal numbers. Needless to say I can not reproduce the problem:

```
(dlv) x -len 0x10 0xc05d78f000
Command failed: input/output error
```

(if I replace it with an address that's mapped it works)
Something else must have gone wrong, but I'm not sure what.

**Comment by prattmic** [comment]
Ah, looks like this was broken in 1.23.1 but works at tip. I bisected to https://github.com/go-delve/delve/commit/52405ba86bd9e14a2e643db391cbdebdcbdb3368, which indeed changes the parsing.

(I see that commit also raises the 1000-byte limit which was annoying me. Thanks!)
