### ISSUE TITLE
Debug REST api on windows running in Parallels on Mac Apple Silicon M4

### ISSUE THREAD

**Issue by pbeccegato** [go-delve/delve#3863]
I'm a newbie with go, I wrote a rest api with go and I can debug it on my mac using VSCode; everything works fine.
Now I'm trying to do same thing on windows, installed on Parallels on my mac, so I installed on windows vscode, go and delve. Running the app on windows, using "go run .", rest api works fine also on windows and I can use it from my mac calling my shared windows ip as http://10.211.55.3:8080 as endpoint.
In this case, into the terminal I see:
```
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] POST   /                         --> DGEDApi/routes.base (3 handlers)
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on :8080
```

When I start the debug on windows, into the "DEBUG CONSOLE", the output debug still remain with:
```
Starting: C:\Users\myuser\go\bin\dlv.exe dap --listen=127.0.0.1:51704 from z:\path_of_my_project\my_project
DAP server listening at: 127.0.0.1:51704
```

and the rest API is unreachable.

Googling for an help, I found some infos about possibile windows paths configuration issues between go and delve; I tryed to apply some advices, but without success.

Thanks in advance

Peter

**Comment by aarzilli** [comment]
A dap server will not actually do anything until a client connects to it and tells it what to start.
