### ISSUE TITLE
max-string-len option

### ISSUE THREAD

**Issue by sirmo** [go-delve/delve#3878]
Is there a way to set this by command line switches or by a config file? Having to change this every time I debug is very tedious. Perhaps an ENV variable?

**Comment by aarzilli** [comment]
Yes: https://github.com/go-delve/delve/blob/master/Documentation/cli/README.md (also `help config`)

**Comment by sirmo** [comment]
`max-string-len` is not mentioned in that document.

**Comment by aarzilli** [comment]
Yes, it should be better somehow.
