### ISSUE TITLE
On OS X only the first SIGINT received by inferior is delivered to it

### ISSUE THREAD

**Issue by aarzilli** [go-delve/delve#489]
dlv version: 0.11.0-alpha Build: e60942a39d2485275cc75f9518932a8208dc5e2d
go version: go version go1.5.2 darwin/amd64

On OS X only the first SIGINT received by inferior is delivered to it.

Example program:

```
package main

import (
        "fmt"
        "os"
        "os/signal"
)

func main() {
        fmt.Println("hello0")
        c := make(chan os.Signal, 1)
        signal.Notify(c, os.Interrupt)
        <-c
        signal.Stop(c)

        fmt.Println("hello1")

        c2 := make(chan os.Signal, 1)
        signal.Notify(c2, os.Interrupt)
        <-c2
        signal.Stop(c2)

        fmt.Println("hello2")
}
```

Run the program inside dlv then send SIGINT twice to it from another terminal.

This bug was [originally reported](https://github.com/derekparker/delve/issues/483#issuecomment-206505322). by @Wizermil.

**Comment by derekparker** [comment]
@aarzilli can we close this out?

**Comment by aarzilli** [comment]
It's a bug that affects the native backend on macOS, do we want to keep those issues open given that it has more serious ones and we aren't going to fix those either?

**Comment by derekparker** [comment]
@aarzilli I'm inclined to close these issues out for the OSX native backend. Maintenance on that backend is a nightmare compared to the others, and we have a solution that works without having to react to undocumented kernel changes, etc.

Thoughts?

**Comment by aarzilli** [comment]
Reasonable.
