### ISSUE TITLE
Release Compiled Binaries With Each Release

### ISSUE THREAD

**Issue by joefitzgerald** [go-delve/delve#494]
It would be wonderful if you could release compiled binaries along with your version tags at https://github.com/derekparker/delve/releases. 

There are multiple editor packages that make use of Delve, and there is a desire to automatically install a binary in a user's `$GOPATH/bin` or somewhere else on their `$PATH` to obviate the need for the user to build from source (which has varying degrees of complexity depending on the platform).

In essence, we would like to provide a "it just works" getting started experience for users on some subset of platforms.

Jetbrains currently maintains this: https://bintray.com/jetbrains/golang/delve/view , which provides a short term fix.

It would be ideal if the binaries were produced by the CI associated with this repo itself and were released as part of your normal process for cutting releases.

This entire issue is predicated on the assumption that there are no immediate plans to make `delve` go gettable on all of: OS X / Windows / Linux (acknowledging it is go gettable on Linux currently).

/cc @dlsniper @lloiser

~~Please answer the following before submitting your issue:~~

~~Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.~~

~~1. What version of Delve are you using (`dlv version`)?~~
~~2. What version of Go are you using? (`go version`)?~~
~~3. What operating system and processor architecture are you using?~~
~~4. What did you do?~~
~~5. What did you expect to see?~~
~~6. What did you see instead?~~

**Comment by derekparker** [comment]
@joefitzgerald I completely agree. I hope to have this in place before cutting the next release. This will be one of a few improvements to the release process that I have planned.

**Comment by joefitzgerald** [comment]
@derekparker Wonderful news - thank you! Any idea on timeframe for the next release (don't want to hold you to anything, just want to determine if we should write code to download from https://bintray.com/jetbrains/golang/delve/view in the interim).

**Comment by derekparker** [comment]
@joefitzgerald the plan is to cut a release this week, but no hard time frame at the moment. However, following this release we will start cutting releases at a specified cadence. I will keep this thread updated on progress.

**Comment by lukehoban** [comment]
@derekparker Out of curiosity - is your plan to publish signed binaries for OS/X?

**Comment by derekparker** [comment]
@lukehoban that would be ideal, however I haven't looked into it and am unsure of what all would be involved. Definitely something I will look into before next release is cut.

**Comment by dlsniper** [comment]
I'll ping @ignatov for this to track as well.

**Comment by derekparker** [comment]
Just wanted to update folks who are following this thread: was not able to get everything in for a release last week, so I'm aiming for cutting a release today or tomorrow. The plan is to include pre-compiled binaries along with that release.

**Comment by joefitzgerald** [comment]
@derekparker thanks for the update! Had a chance to investigate signing the OS X binary?

**Comment by ignatov** [comment]
BTW, we're at JetBrains use our developer certificate for signing Delve Mac OS binaries.

**Comment by derekparker** [comment]
@joefitzgerald @ignatov yeah I think the only solution is to cough up $99 to enroll in their developer program and get a developer cert I can sign the binaries with.

**Comment by joefitzgerald** [comment]
@derekparker got anywhere we can send you some cash?

**Comment by derekparker** [comment]
@joefitzgerald thanks for asking. Not currently, but that would be very helpful. I will look into getting something set up, and post some information regarding explicitly what the funds are used for.

**Comment by alexbrainman** [comment]
> This entire issue is predicated on the assumption that there are no immediate plans to make delve go gettable on all of: OS X / Windows / Linux (acknowledging it is go gettable on Linux currently).

`go get` works for me fine on Windows.

```
C:\>go get github.com/derekparker/delve/cmd/dlv

C:\>%GOPATH%\bin\dlv
Delve is a source level debugger for Go programs.

Delve enables you to interact with your program by controlling the execution of the process,
evaluating variables, and providing information of thread / goroutine state, CPU register state and more.

The goal of this tool is to provide a simple yet powerful interface for debugging Go programs.

Usage:
  dlv [command]

Available Commands:
  version     Prints version.
  run         Deprecated command. Use 'debug' instead.
  debug       Compile and begin debugging program.
  exec        Runs precompiled binary, attaches and begins debug session.
  trace       Compile and begin tracing program.
  test        Compile test binary and begin debugging program.
  attach      Attach to running process and begin debugging.
  connect     Connect to a headless debug server.

Flags:
      --accept-multiclient[=false]: Allows a headless server to accept multiple client connections. Note that the server API is not reentrant and clients will have to coordinate
      --api-version=1: Selects API version when headless
      --build-flags="-ldflags=-linkmode internal": Build flags, to be passed to the compiler.
      --headless[=false]: Run debug server only, in headless mode.
  -h, --help[=false]: help for dlv
      --init="": Init file, executed by the terminal client.
  -l, --listen="localhost:0": Debugging server listen address.
      --log[=false]: Enable debugging server logging.

Use "dlv [command] --help" for more information about a command.

C:\>

```

Alex

**Comment by derekparker** [comment]
Another update on this thread:

It's looking like I will not be cutting a new release this week. However, on the bright side, it's because I'm working on some major changes, including a pretty significant refactor, and I'm hopeful that the next release will essentially be either 1.0.0.rc1 or very close to that. The plan is for the next release to include the new API changes @aarzilli has been working on, as well as a bunch of code cleanup, stability improvements (especially on OSX), and build artifacts attached to the release.

The plan is to finish up all of the more intense refactoring I'm doing over the weekend, and (fingers crossed) have a release out by middle/late next week. Thanks for everyone's patience on this, but the next release will be a pretty big one.

**Comment by dlsniper** [comment]
If you'll need help with testing the changes, feel free to ping me. Thank you for your work!

**Comment by joefitzgerald** [comment]
Anything we can do to unblock things @derekparker?

**Comment by derekparker** [comment]
@joefitzgerald nothing in particular, unfortunately. The next release is blocked on an ambitious refactor I'm playing on top of some OSX fixes, and it's just a matter of me getting it over the finish line. I'm nearly there, and the next release should be out within the next few days.

**Comment by joegrasse** [comment]
@derekparker, just curious if this coming release will include 32bit support?

**Comment by derekparker** [comment]
@joegrasse no, next release will not, but we should be set up to get that feature added within the next 2 releases. The next release will focus on all patches already merged, plus OSX stability fixes and code cleanup.

**Comment by derekparker** [comment]
Update: making great progress on refactor. Spoke with @aarzilli and we are planning on cutting a new release this week, so stay tuned.

**Comment by joefitzgerald** [comment]
@derekparker is there some way to just cut a release (manually) based on the most recently released version (January) that has signed OS X binaries? I totally understand the desire to cut one based on the latest bits, but it feels like a moving target that may still be weeks or months away?

**Comment by derekparker** [comment]
@joefitzgerald sorry for the late response, I have been swamped lately. With the homebrew installation method we have now, which will self-sign the binary upon installation, is there still a lot of benefit for shipping signed binaries? For example, would it still be too much to ask to have a user run `brew install go-delve/delve/delve`?

Just putting that out there, not ruling out shipping signed binaries.

**Comment by joefitzgerald** [comment]
@derekparker no I don't think homebrew will supplant the need for signed release binaries as many OSX users (rightly or wrongly) don't use homebrew.

And I totally understand - you don't have to apologize. I also do this on the side, and am making no demands :)

**Comment by dlsniper** [comment]
Maybe using the BinTray repo JetBrains has is an option? But ask them first as I don't speak for them :)

**Comment by joefitzgerald** [comment]
That's already happening, but the releases belong here.

**Comment by joefitzgerald** [comment]
@derekparker any updates on releasing binaries in Github releases?

**Comment by kishaningithub** [comment]
I truly recommend [goreleaser](https://goreleaser.com/) to automate the creation of binaries and  [godownloader](https://github.com/goreleaser/godownloader) for automated generation of install scripts.

For inspiration on the integration you can look into the awesome [golangci-lint](https://github.com/golangci/golangci-lint)

Also, Thank you for developing [delve](https://github.com/derekparker/delve)!!

**Comment by Slach** [comment]
@joefitzgerald could you describe why this issue is closed? why delve can't be distributed as precompiled binary?

**Comment by joefitzgerald** [comment]
@Slach 5 years on, this issue seems stale. I don’t see it being prioritized, so I closed it as the original requester. I’m fine if the delve maintainers want to reopen the issue.

**Comment by loeffel-io** [comment]
Friendly ping @derekparker @aarzilli 

There are a lot of issues and duplicates feature requesting this. It's 2026

https://github.com/go-delve/delve/issues/3956#issuecomment-4015956273

**Comment by derekparker** [comment]
> Friendly ping [@derekparker](https://github.com/derekparker) [@aarzilli](https://github.com/aarzilli)
> 
> There are a lot of issues and duplicates feature requesting this. It's 2026
> 
> [#3956 (comment)](https://github.com/go-delve/delve/issues/3956#issuecomment-4015956273)

Yes you are correct this has been an ask for some time, which is why yesterday I submitted https://github.com/go-delve/delve/pull/4278. Once that lands I will create official binaries for v1.26.1 and then every release going forward will have binaries included.

**Comment by ofek** [comment]
Thanks! Is there work yet to be done for publishing the previous release's binaries?

**Comment by derekparker** [comment]
> Thanks! Is there work yet to be done for publishing the previous release's binaries?

The release configuration did not exist at that tag, so the current plan is to have official binaries with the next release. Apologies for the confusion there.

**Comment by ofek** [comment]
Ah, no worries. Do you have an idea of when the next release may occur?

**Comment by derekparker** [comment]
> Ah, no worries. Do you have an idea of when the next release may occur?

We don't have an exact timeline for point releases, but we will ship the next release sooner than usual so we can get the first official binaries out.
