### ISSUE TITLE
App being debugged cannot change tty parameters (via ioctl ala tcsetattr)

### ISSUE THREAD

**Issue by idcmp** [go-delve/delve#587]
Shell:
`go get github.com/jroimartin/cogui`
`cd $GOPATH/src/github.com/jroimartin/_examples`
`dlv debug demo.go`

Delve:
`break tcsetattr`
`continue`
Step or Next through until app hangs, for me it's just after:

syscall.Syscall() /usr/local/go/src/syscall/asm_linux_amd64.s:27 (PC: 0x4ac4e4)
    22:     MOVQ    $0, R10
    23:     MOVQ    $0, R8
    24:     MOVQ    $0, R9
    25:     MOVQ    trap+0(FP), AX  // syscall entry
    26:     SYSCALL
=>  27:     CMPQ    AX, $0xfffffffffffff001
    28:     JLS ok
    29:     MOVQ    $-1, r1+32(FP)
    30:     MOVQ    $0, r2+40(FP)
    31:     NEGQ    AX
    32:     MOVQ    AX, err+48(FP)
1. What version of Delve are you using (`dlv version`)? 0.11.0-alpha
2. What version of Go are you using? (`go version`)? go1.7beta2 linux/amd64

**Comment by aarzilli** [comment]
You can run the application on a different tty and attach to it.

**Comment by aarzilli** [comment]
On addition to the previous suggestion the `--tty` option now also exists.
