### ISSUE TITLE
Add optional -run flag to dlv test

### ISSUE THREAD

**Issue by bbatha** [go-delve/delve#636]
Please add a -run flag to dlv test to mimic the behavior of the go test command. This can be achieved through a command pass through but requires memorizing the test runner flags instead of the more common `go test` interface.

For reference, pass through looks like this (borrowed from #422):

``` bash
    dlv test --build-flags='github.com/dlsniper/u/tmp/mypack' -- -test.run ^TestHello$
```

Using the arg pass through trick also makes the pwd of the runner the shell's pwd, instead of go test's behavior where the pwd is the folder of the module being tested which can make flipping between `dlv` and `go test` frustrating.

**Comment by cyli** [comment]
I tried the above, but I keep getting the error `cannot use -c flag with multiple packages`.  The package I have looks like:

`github.com/cyli/foo/bar` - which contains tests (including the one I'm trying to run), but also another subpackage `github.com/cyli/foo/bar/baz`, which I'm not trying to test.

Is there some other argument I need to pass?

**Comment by whit537** [comment]
Why should `dlv` diverge from `go` at all? Adds cognitive overhead ... for what?

**Comment by whit537** [comment]
I think the `--build-flags` is unnecessary. You can pass an import path directly to `dlv test`. It's the `-- -test.run FooBar` that does the trick of singly out a single test. However, that seems to clobber the `-N -i` needed to print symbols?

**Comment by whit537** [comment]
Eep! Cross-posted on https://github.com/derekparker/delve/issues/636. 😊

**Comment by whit537** [comment]
P.S. The `--build-flags` are extraneous, because you can specify packages directly to `dlv test`. All that's needed to filter tests is `-- -test.run Foo`. The above could be shortened to:

```
dlv test github.com/dlsniper/u/tmp/mypack -- -test.run ^TestHello$
```

**Comment by derekparker** [comment]
Closing, we will not be adding this. As mentioned above, the `-test.run` flag can be used when passed to the test binary.
