### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by fubarhouse** [go-delve/delve#710]
Please answer the following before submitting your issue:

1. What version of Delve are you using (`dlv version`)?
```` 0.11.0-alpha ````
2. What version of Go are you using? (`go version`)?
```` 1.7.4 ````
3. What operating system and processor architecture are you using?
```` Mac OSX Sierra, amd64x ````
4. What did you do?
```` N/A - Not a bug````
5. What did you expect to see?
```` N/A - Not a bug ````
6. What did you see instead?
```` N/A - Not a bug ````

Delve team, is there a roadmap to 1.0, or a stacked list of things to complete before a 1.0 release can be considered? If not, what are the setbacks? I'd love to see some future certainty in this project. I've been using it a bit lately where it's integrated with the JetBrains IDE/plugin - but in my experience 0.xx releases normally drag infinitely or seemingly infinitely - one exception here I know about would be something known as Drupal Console, but they're really pushing for a stable 1.0 release at the moment.

**Comment by derekparker** [comment]
Hey, thanks for the concern here!

We are absolutely striving for a 1.0 release, and with all of the amazing adoption of this project we are continuously getting closer to hitting that milestone. 

As it stands right now, most of the time of the maintainers (myself an @aarzilli) has been spent evangelizing, fixing issues, and adding features. As most of the original `1.0` blockers have been implemented, it is certainly time to re-evaluate a list of what must be included in an official `1.0` release. It has been helpful to have a lot of the editor integrations as they have helped us solidify the API layer, and bring this software to a much wider audience, allowing us to continuously harden and improve the code base.

@aarzilli and I will be meeting soon to discuss solidifying plans for implementing not only steady releases on a regular cadence, but also road mapping and assigning priorities to issues that a paramount for a `1.0` version.

Again, thanks for your interest in the project, thanks for opening this issue, and look out for future releases!

**Comment by aarzilli** [comment]
IMHO the big thing missing from 1.0 is solving issue #186 and related issues. Those are blocked by issues in the go compiler that hopefully will be fixed in 1.9. 

Other than that there's the ability to call functions from the debugger but I think that could wait for post-1.0, since I think that requires special support from the go runtime.

OTOH there's really no pressure for us to make a 1.0 release, we are already giving a backwards compatibility guarantee for the API, the 1.0 thing would just be symbolic.

**Comment by joegrasse** [comment]
I am also hopeful that issues like #20 and #656 are solved soon as well.

**Comment by derekparker** [comment]
@aarzilli yes, there are upstream blockers, and we should absolutely be more vocal about getting those fixed. However, overall I think we need to re-evaluate our issue list and come up with an exact milestone of features (including external blockers) that must happen for a 1.0 release.

I also agree a 1.0 release is mostly symbolic, but that's also one of the motivations, is to mark this project as finally "stable" in terms of not only API compatibility but from an implementation and usability standpoint.

**Comment by ahakanbaba** [comment]
Great news about the 1.0 progression. 
I have recently started using delve on kubernetes code and it had great potential to ease development efforts. 

@derekparker Are you aware anyone else attempting something similar?

Looking forward to improvements and I would love to get my hands dirty on some of the bugs I have created. #711 #712 and more to come !

**Comment by aarzilli** [comment]
@ahakanbaba your three bugs shouldn't be hard to fix, if you want to do it you should start reading terminal/command.go.

**Comment by dlsniper** [comment]
@derekparker / @aarzilli is there anything that we can do, now that Go 1.9 branch has been open so that we can get the blockers fixed in Go asap and not have them delayed yet again? I know one of the issues currently sits open in Go for more than 3 releases.
I'd love to be able to contribute more than just pushing around so I'll try and make time for this but currently my level of knowledge does not bring much on the table for this.

I want to thank you both for the amazing effort you've put into this. Thank you!

**Comment by jinleileiking** [comment]
* autocompletion 
* run method when debug

**Comment by derekparker** [comment]
Just to update this thread:

The current plan is to cut a `v1.0.0-rc.1` release after https://github.com/derekparker/delve/pull/804 merges. Following that, we will allow 2 weeks for user testing, and then from there either cut another RC or cut the first real `v1.0.0` release.

Barring any Go issues, we feel the project is stable and widely used enough at this point, and with our API guarantees, we feel comfortable finally cutting a `1.0` release soon. Be on the lookout and please help test!

**Comment by fubarhouse** [comment]
I'll do what I can to help :)

**Comment by joegrasse** [comment]
@derekparker Just curious, will 32bit support make it in the 1.0.0 release?

**Comment by fubarhouse** [comment]
@joegrasse see f6091694b6f8516bc1d4e5241fdb51e20dd04719

**Comment by derekparker** [comment]
@joegrasse it will not make it in, unfortunately, but we will try to bump that up the priority this, I know it's needed!

**Comment by joegrasse** [comment]
Thanks for the update.

**Comment by komuW** [comment]
Talking of upstream blockers; I came across https://github.com/derekparker/delve/issues/119 which led me to open https://github.com/golang/go/issues/21678 upstream

**Comment by derekparker** [comment]
We have cut the 1.0 release some time ago now.
