### ISSUE TITLE
Simple "getting started" documentation

### ISSUE THREAD

**Issue by wolever** [go-delve/delve#743]
It would be fantastic if there was one document which had:

1. Links to the (already fantastic) installation instructions
2. Use `dlv debug -- your-args` to start the debugger
3. Use `continue` to run the program

Otherwise it takes a bit of clicking around to go from zero to having something working.

**Comment by lukemarsden** [comment]
I attempted something similar here: https://github.com/derekparker/delve/pull/973

PTAL 😄

**Comment by derekparker** [comment]
Closing, we have https://github.com/go-delve/delve/blob/master/Documentation/cli/getting_started.md.
