### ISSUE TITLE
Remaining work to support core files

### ISSUE THREAD

**Issue by aarzilli** [go-delve/delve#794]
- [x] Support floating point registers on linux (the code to parse an XSAVE area already exists in registers_linux_amd64.go, likely the same format is used in core dumps)
- [ ] Support parsing of core dumps produced on macOS
- [x] Support parsing of core dumps produced on Windows

**Comment by hyangah** [comment]
@heschik

**Comment by jtanx** [comment]
Is there any way to walk the stack of a core file with `up`/`down`?

**Comment by aarzilli** [comment]
@jtanx `frame 7 command` to execute "command" on frame 7. Change goroutine with `goroutine 5`

**Comment by jtanx** [comment]
Ah... ok. That's not very intuitive. GDB supports using up/down in a core dump, which I find much more useful.

**Comment by aarzilli** [comment]
I've looked into supporting macOS core fie but I can't find any way to retrieve the thread_handle of every thread, which we need to associate threads with goroutines.

**Comment by dlsniper** [comment]
@aarzilli I think that the Windows support can also be ticked as done now, given minidumps support has landed, correct?

**Comment by aarzilli** [comment]
@dlsniper yes.

**Comment by aarzilli** [comment]
Closing this, we support dumps created by delve's dump command on macOS. We can't support native core dumps because they don't have all the registers that we need so there is nothing else to do here.
