### ISSUE TITLE
Setting a string value is not currently supported

### ISSUE THREAD

**Issue by dlsniper** [go-delve/delve#826]
1. What version of Delve are you using (`dlv version`)?
1.0.0 RC1
2. What version of Go are you using? (`go version`)?
1.8.1
3. What operating system and processor architecture are you using?
Windows 10 / amd64
4. What did you do?
Tried to set a variable of type string
5. What did you expect to see?
The new value.
6. What did you see instead?
```
(dlv) set myEnvVar = "some val"
Command failed: can not set variables of type string (not implemented)
```

I understand that this is currently not implemented but because there's also no issue to keep track of it I thought it might be a good idea to at least raise one.

Thank you.

**Comment by aarzilli** [comment]
The problem with changing a string is that to change a string we need to allocate memory, to allocate memory we need to execute code on the inferior and to execute code on the inferior we need to make function calls and that's hard because of a GC and scheduler.

**Comment by justinclift** [comment]
Looks like some work on this has been happening in your `fncalls_pt2` branch:

https://github.com/aarzilli/delve/commits/fncalls_pt2

Is that just experimental stuff, or is it likely to be merged into the main Delve `master` branch at some point (and then into a future release)? :smile:

**Comment by aarzilli** [comment]
It just needs to be reviewed, you can try it if you want by applying manually #1503 and #1504

**Comment by justinclift** [comment]
Oh excellent!  I'm almost finished the thing I'm working on atm, so can probably get time to try either in a few hours or tomorrow morning. :smile:
