### ISSUE TITLE
OSX 'make install' fails but manual `codesign $GOPATH/bin/dlv` completes build

### ISSUE THREAD

**Issue by jasonrharris** [go-delve/delve#891]
1. What version of Delve are you using (`dlv version`)?
1.0.0-rc.1
2. What version of Go are you using? (`go version`)?
go version go1.8 darwin/amd64
3. What operating system and processor architecture are you using?
macOS Sierra 10.12.5
4. What did you do?
 make install
5. What did you expect to see?
`scripts/gencert.sh || (echo "An error occurred when generating and installing a new certicate"; exit 1)
go install -ldflags="-s" github.com/derekparker/delve/cmd/dlv
codesign -s "dlv-cert"  /bin/dlv`

6. What did you see instead?
`scripts/gencert.sh || (echo "An error occurred when generating and installing a new certicate"; exit 1)
go install -ldflags="-s" github.com/derekparker/delve/cmd/dlv
codesign -s "dlv-cert"  /bin/dlv
/bin/dlv: No such file or directory`

This was resolved by running `codesign $GOPATH/bin/dlv`

**Comment by aarzilli** [comment]
looks like you didn't have GOPATH defined when you ran make.

**Comment by jasonrharris** [comment]
I thought the same but `echo $GOPATH` directly after `make install` had
failed reported the correct path and immediately after that `codesign -s
"dlv-cert" $GOPATH/bin/dlv` worked. I hadn't set $GOPATH in the meantime
and its been setup correctly on my system for a very long time.

**Comment by aarzilli** [comment]
Very odd, I don't see what else could cause this.

**Comment by justinclift** [comment]
Arrgh, that's a bit of scripting I wrote. 👼 

Hmmm, maybe it's something to do with $GOPATH not being exported correctly in some cases...

I'll try to get time to investigate this over the weekend.

**Comment by justinclift** [comment]
@jasonrharris Actually, would you have time to check if the latest master branch source still gives the problem?

**Comment by KISSMonX** [comment]
export GOBIN=$GOPATH/bin

**Comment by aarzilli** [comment]
Given the changes to how we build and sign the executable (we moved from Makefile to a go script), I think this isn't relevant anymore.
