### ISSUE TITLE
Step did not step into function call (13)

### ISSUE THREAD

**Issue by dlsniper** [go-delve/delve#892]
Running tests @ https://github.com/derekparker/delve/commit/04c4b019f7557344910ade621f68e2695eabe2e5 on Windows 10 with Go 1.8.3 gives this:

```
z=9900
	support.go:129: enabling recording for github.com/derekparker/delve/pkg/proc_test.TestStepConcurrentPtr
	proc_test.go:2386: Step did not step into function call (13): D:/go/src/github.com/derekparker/delve/_fixtures/teststepconcurrent.go:23
```

It happened only once, I'm not sure I can reproduce.

**Comment by aarzilli** [comment]
https://travis-ci.org/derekparker/delve/jobs/274299091

**Comment by derekparker** [comment]
Closing, please reopen if still an issue.
