### ISSUE TITLE
behavior of 'next' seems problematic for just-born processes

### ISSUE THREAD

**Issue by danielbprice** [go-delve/delve#893]
1. What version of Delve are you using (`dlv version`)? **Version: 1.0.0-rc.1  (I built from 04c4b019f7557344910ade621f68e2695eabe2e5, 20 Jun 2017)**

2. What version of Go are you using? (`go version`)?  **go version go1.8 linux/amd64**

3. What operating system and processor architecture are you using?  **Centos 7.1.1503**

4. What did you do?  **Started delve exec, and typed next**

5. What did you expect to see?

Some advancement of program execution, or a clean error message.

6. What did you see instead?
```
$ bin/dlv exec bin/hello
(dlv) next
Command failed: Invalid address 0x1
```

I spent some time tracking this down.  It took me a while to work out that 0x1 is _argc_.  So, for example, 5 arguments total yields an invalid address of 0x5.
```
$ bin/dlv exec bin/hello foo bar baz quux
Type 'help' for list of commands.
(dlv) next
Command failed: Invalid address 0x5
```

The problem seems to stem from the special layout of the stack at the birth of the process (I found a reference for that here: http://dbp-consulting.com/tutorials/debugging/linuxProgramStartup.html).  Instead of a return PC where delve expects to find it, we have argc.  And so the attempt to set a breakpoint for the return-PC in the below code will fail:

pkg/proc/threads.go
```
        if bp, err := dbp.SetBreakpoint(topframe.Ret, NextBreakpoint, retFrameCond); err != nil {
                if _, isexists := err.(BreakpointExistsError); isexists {
                        if bp.Kind == NextBreakpoint {
                                // If the return address shares the same address with one of the lines
                                // of the function (because we are stepping through a recursive
                                // function) then the corresponding breakpoint should be active both on
                                // this frame and on the return frame.
                                bp.Cond = sameOrRetFrameCond
                        }
                } else {
                        return err
                }
```

I spent some time thinking about this problem.  I'm new to delve, but it seems like a first possibility is to try to correct the stack backtrace code to notice this case, as it is generating a bogus frame.  However the real solution will probably depend on what the project maintainers think the behavior of 'next' should be in this corner case.

As an experiment, I tried simply commenting out the `return err` line, allowing the return address breakpoint set to fail, and drive on.  This works (it's similar to what we'd see if the stack backtrace code was fixed for this case), and delve can step one assembly instruction at a time through `rt0_linux_amd64.s`, for a few instructions.  However, delve loses control of the executable right after the first JMP; the assembly has violated its ideas about where breakpoints need to be set.

```
> _rt0_amd64_linux() /home/build/x86_64-el6-tools/golang/go1.8/src/runtime/rt0_linux_amd64.s:11 (PC: 0x44e840)
     6:
     7: TEXT _rt0_amd64_linux(SB),NOSPLIT,$-8
     8:         LEAQ    8(SP), SI // argv     <--- start of everything
     9:         MOVQ    0(SP), DI // argc
    10:         MOVQ    $main(SB), AX
=>  11:         JMP     AX      <-----delve loses control after 'next' from here
    12:
    13: // When building with -buildmode=c-shared, this symbol is called when the shared
    14: // library is loaded.
    15: // Note: This function calls external C code, which might required 16-byte stack
    16: // alignment after cmd/internal/obj applies its transformations.

Hello, world.    <--- output of my program
No current thread available
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x70acfa]
```

(The SIGSEGV represents (IMO) a different bug in `next` which is out of scope for this report.)

One way I can see to approach this problem is to simply say that the first "next" advances execution to some well known point in the process startup where we know the stack looks sensible and there won't be any more JMPs to confuse delve.  There are probably other solutions.

I'm interested in this problem, so if there is consensus on the desired behavior, I could try to propose something.

**Comment by aarzilli** [comment]
> I spent some time thinking about this problem. I'm new to delve, but it seems like a first possibility is to try to correct the stack backtrace code to notice this case, as it is generating a bogus frame. However the real solution will probably depend on what the project maintainers think the behavior of 'next' should be in this corner case.

I don't think we should change the behavior of next here, I think fixing the behavior of the stack trace, and then not setting the return breakpoint is the right solution. 

> However, delve loses control of the executable right after the first JMP; the assembly has violated its ideas about where breakpoints need to be set.

I don't think this is a bug, if you were stopped on a call to a function that calls `os.Exit`  and used `next` the program would also end, a similar thing happens here. The SIGSEGV is a bug.

**Comment by derekparker** [comment]
Closing, please reopen if this is still an issue.
