### ISSUE TITLE
Add an alias for 'stepout'

### ISSUE THREAD

**Issue by swors** [go-delve/delve#931]
Please add an alias for 'stepout'.
Fox example, 'up',

**Comment by derekparker** [comment]
@swors you can absolutely add a default alias if you'd like, the process for contributing this is actually very easy, simply add the alias [here](https://github.com/derekparker/delve/blob/master/pkg/terminal/command.go#L105). 

Also, you can define your own aliases via the configuration file that should be found in `$HOME/.dlv/config.yaml`.

**Comment by swors** [comment]
@derekparker
Yes, I've modified the source code and build a private version for myself. But I still think that it is better to set a  default official alias.
'$HOME/.dlv/config.yaml' is great. Thank you very much.

**Comment by aarzilli** [comment]
I don't think up is a great choice since gdb uses it for something else.

**Comment by swors** [comment]
@aarzilli My mistake. up is not suitable. Maybe 'finish' which used by gdb is a better choice

**Comment by aarzilli** [comment]
finish is one letter shorter than stepout

**Comment by lukemarsden** [comment]
+1 for `up` aliased to `stepout`, I'm familiar with that from `pdb`.

**Comment by QuLogic** [comment]
`down` and `up` are commands to move around the stack frames. This is true in pdb as well, so I'm not sure what you mean.

+1 to `finish`

**Comment by stigok** [comment]
This should probably be closed. `so` is now an alias:
```
stepout (alias: so) --------- Step out of the current function.
```

**Comment by aarzilli** [comment]
Yes, thank you.
