### ISSUE TITLE
how to save breakpoints with dlv?

### ISSUE THREAD

**Issue by idevz** [go-delve/delve#938]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
```bash
❯ dlv version                                                                                                                      z@z
Delve Debugger
Version: 0.12.1
Build:
```
2. What version of Go are you using? (`go version`)?
```bash
❯ go version                                                                                                                       z@z
go version go1.8.3 
```
3. What operating system and processor architecture are you using?
```bash
linux/amd64
```
4. What did you do?
I want to save the breakpoints like what GDB dose which I added in my debug process.

**Comment by gertcuykens** [comment]
Can breakpoints maybe be included with `(dlv) config -save` ?

**Comment by aarzilli** [comment]
Sure.

**Comment by aarzilli** [comment]
Just noticed that there already was a feature request for this https://github.com/go-delve/delve/issues/719
