### ISSUE TITLE
Add special formatting for time.Time

### ISSUE THREAD

**Issue by insight1111** [go-delve/delve#999]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.0.0-rc.2
2. What version of Go are you using? (`go version`)?
go version go1.9 windows/amd64
3. What operating system and processor architecture are you using?
Windows10 64bit
4. What did you do?

``` golang
package main

import (
    "fmt"
    "time"
)
func main() {
    t:=time.Now()
    fmt.Println(t)
}
```

and run 
```bash
dlv debug
b main.main
c
...
print t
```

5. What did you expect to see?
I want to get string like below formatted time text
`2017-10-23 11:03:00 ...`
6. What did you see instead?

```
time.Time {
        wall: 13723543243807126424,
        ext: 4158612300,
        loc: *time.Location {
                name: "",
                zone: []time.zone len: 0, cap: 0, nil,
                tx: []time.zoneTrans len: 0, cap: 0, nil,
                cacheStart: 0,
                cacheEnd: 0,
                cacheZone: *time.zone nil,},}
```

How to get formatted time text in dlv debug mode?

**Comment by pjebs** [comment]
`time.Duration` too. Is it possible to get this with breakpoints and `print` command?

**Comment by pjebs** [comment]
@aarzilli I looked at your fork? Can you also print out `time.Duration` in a format that is better than the default (nanoseconds)?

**Comment by aarzilli** [comment]
I'd rather not:

1. I think nanoseconds is an acceptable representation for time.Duration
2. There's nowhere to save a different representation, the other types are structs and I can write the pretty print version in Variable.Value, this is a scalar value and Variable.Value is already used for its real value
3. With the upcoming 1.10 release you will be able to evaluate "dt/time.Millisecond" to have the value of a duration in milliseconds.

**Comment by pjebs** [comment]
Can you explain point 3 please?

**Comment by aarzilli** [comment]
> Can you explain point 3 please?

If you have go 1.10 installed and `dt` is a variable of `time.Duration` the command `print dt/time.Millisecond` will print `dt` in milliseconds.

**Comment by derekparker** [comment]
Closing, you can instead call methods on the time value to format via the `call t.Format(...)` or `call t.String()`.

**Comment by ppggff** [comment]
> Closing, you can instead call methods on the time value to format via the `call t.Format(...)` or `call t.String()`.

you can not call these function when dealing with coredump file

**Comment by joaowiciuk** [comment]
If I would be interested in calling `t.Format(...)` or `t.String()` then why would I be using a debugger in first place?

**Comment by torlarse** [comment]
I support reopening this issue, my application relies heavily on time and duration bookkeeping. Debugging time would decrease significantly with readable time and duration values in debugger window, instead of cycling 
```
...
call t1.String()
call t2.String()
call t3.String()
call d1.String()
call t1.String()
...
``` 
I respect that this feature could be a large effort for the Delve contributors. Please consider probing the problem complexity and eventual external contributor guidance (if that makes sense).

**Comment by polinasok** [comment]
The issue of time pretty printing got new attention in #2841 and golang/vscode-go/issues/1980 (and earlier in https://github.com/golang/vscode-go/issues/158#issuecomment-749176403).

I see that there was an attempt to implement this earlier. What was the complication?
The topic of pretty-printing comes up a lot for various types. Perhaps, it is worth it for delve backend to add another Variable field for some kind of pretty-printed value that clients are free to use (if populated) or ignore if they want to pretty-print themselves?

**Comment by aarzilli** [comment]
> I see that there was an attempt to implement this earlier. What was the complication?

It was closed because the pretty printing can be done through call injection. IMO call injection has enough complications that it would still be worth doing it manually.

**Comment by hyangah** [comment]
Was the possibility of reverse engineering `time.Time`'s `String`/`GoString` implementation and implement a simplified version that interprets the time.Time internal data explored already?
I am not suggesting we should do it (given that `time.Time` formatter implementation is non-trivial already and `time.Time` internal representation can change over time, putting more ongoing maintenance burden to delve maintainers) but want to close the loop completely.

**Comment by aarzilli** [comment]
@hyangah if you look at formatTime, formatBigRat, etc in https://github.com/aarzilli/delve/commit/608864025e5df40fc59b9f3467dc1a665b44f5b5 that's what I did.

**Comment by hyangah** [comment]
@derekparker What do you think? Go's `time.Time` internal was stable for some time AFAIK. Formatting without depending on the heavy-weight `call` will enhance UX greatly.

**Comment by derekparker** [comment]
> @derekparker What do you think? Go's `time.Time` internal was stable for some time AFAIK. Formatting without depending on the heavy-weight `call` will enhance UX greatly. (especially for more recent features like watchpoint, DAP, ...)

I'm +1 on this approach.

**Comment by eduardo-mior** [comment]
I work a lot with time.Time. It's terrible to debug this way, if there was a readable String it would make my life a lot easier.

**Comment by hyangah** [comment]
@eduardo-mior Can you please be more specific about what you need?

The following is the current state.
![Screen Shot 2022-04-01 at 11 20 42 AM](https://user-images.githubusercontent.com/4999471/161293232-88eece5c-792c-4b24-a655-3f5c9067c689.png)

```
(dlv) p now
time.Time(2022-04-01T15:22:35Z, +78461){
        wall: 13873870879360299128,
        ext: 78461,
        loc: *time.Location {
                name: "",
                zone: []time.zone len: 0, cap: 0, nil,
                tx: []time.zoneTrans len: 0, cap: 0, nil,
                extend: "",
                cacheStart: 0,
                cacheEnd: 0,
                cacheZone: *time.zone nil,},}
```

**Comment by eduardo-mior** [comment]
My VSCode shows as follows in debug.

How can I make it show the same way as yours?

![image](https://user-images.githubusercontent.com/32434418/161531920-790a3afd-8f78-47bb-9b6a-cc0ab4792ce8.png)
